plugins/lookup/passwordstore.py, tests/integration/targets/lookup_passwordstore/tasks/tests.yml
passwordstore lookup plugin now can handle equal sign in user input
Fixes: ansible/ansible#68265
plugins/lookup/passwordstore.py
tests/integration/targets/lookup_passwordstore/tasks/tests.yml
=> passwordstore: Honor equal sign in userpass

plugins/modules/database/mysql/mysql_user.py
This stops a false positive warnings that the `update_password` param
doesn't have the `no_log` set.
Similar to the issue in #17.
module mysql_user
Related to https://github.com/ansible/ansible/pull/68118
=> Fix false positive for MySQL user module

plugins/modules/database/postgresql/postgresql_user.py
This stops a the false positive warnings that the `no_password_changes`
doesn't have the `no_log` set.
Fixes https://github.com/ansible/ansible/issues/68106
module postgresql_user
Related to https://github.com/ansible/ansible/pull/68116
=> Fix false positive warnings for PostgreSQL User

plugins/module_utils/postgres.py, plugins/modules/database/postgresql/postgresql_copy.py, plugins/modules/database/postgresql/postgresql_idx.py, plugins/modules/database/postgresql/postgresql_owner.py, plugins/modules/database/postgresql/postgresql_publication.py, plugins/modules/database/postgresql/postgresql_sequence.py, plugins/modules/database/postgresql/postgresql_slot.py, plugins/modules/database/postgresql/postgresql_subscription.py, plugins/modules/database/postgresql/postgresql_table.py, plugins/modules/database/postgresql/postgresql_tablespace.py
(cherry picked from commit fb6583a15c1f7fd8e48f4f3ef214ed4e74c3d8c6)
postgres: make interfaces of postgres.exec_sql clearer
This function was introduced by me.
Now, despite this typical for DDL queries, i'm convinced that it will make the function's interface clearer.
```plugins/module_utils/postgres.py```
```plugins/modules/database/postgresql/postgresql_copy.py```
```plugins/modules/database/postgresql/postgresql_idx.py```
```plugins/modules/database/postgresql/postgresql_owner.py```
```plugins/modules/database/postgresql/postgresql_table.py```
```plugins/modules/database/postgresql/postgresql_sequence.py```
```plugins/modules/database/postgresql/postgresql_slot.py```
```plugins/modules/database/postgresql/postgresql_tablespace``` …
=> postgres: make interfaces of exec_sql clearer

shippable.yml
community.general doesn't have any Ansible Tower tests, so remove them
=> Remove unused Tower tests from Shippable

galaxy.yml
We really don't want any more run-time dependencies adding to `community.general`, so lets document that
I will go through remove as many of these as we can.
=> galaxy.yml - Do not add anymore dependencies

tests/unit/plugins/cache/test_memcached.py, tests/unit/plugins/cache/test_redis.py, tests/unit/plugins/lookup/test_avi.py
Tests need to be adjusted to handle FQCN to loader, and not short name.
tests/unit/plugins/cache/test_memcached.py
tests/unit/plugins/cache/test_redis.py
tests/unit/plugins/lookup/test_avi.py
=> Fix remaining failing plugin unit tests

plugins/lookup/cartesian.py
`lookup`/`query` plugin can't be used as filter with `template error while templating string: no filter named 'lookup'`.
See ansible/ansible#68478
lookup
=> Fix example since lookup/query is not filter

plugins/module_utils/compat/ipaddress.py, plugins/modules/cloud/scaleway/scaleway_security_group_rule.py, plugins/modules/net_tools/hetzner_firewall.py, plugins/modules/net_tools/nios/nios_fixed_address.py
As discussed in #ansible-devel. This allows to drop the dependency on ansible.netcommon once all network modules have been moved out.
plugins/module_utils/compat/ipaddress.py
=> Add copy of ipaddress.py from ansible.netcommon

plugins/modules/packaging/os/homebrew.py, tests/integration/targets/homebrew/aliases, tests/integration/targets/homebrew/tasks/main.yml
Handle upgrade options in upgrade_all state in homebrew module.
Fixes: ansible/ansible#54541
plugins/modules/packaging/os/homebrew.py
=> homebrew: Add upgrade_options in upgrade_all

tests/utils/shippable/shippable.sh
`set -e` was still active, thus retry doesn't work (see f.ex. https://app.shippable.com/github/ansible-collections/community.general/runs/211/3/console).
tests/utils/shippable/shippable.sh
=> Fix retry on shippable setup

plugins/inventory/docker_machine.py, plugins/inventory/docker_swarm.py, plugins/inventory/gitlab_runners.py
Their `verify` method uses `self.NAME`, which now includes `community.general.`.
Somewhat related problem as #50.
docker_swarm inventory plugin
docker_machine inventory plugin
gitlab_runners inventory plugin
=> Fix docker_swarm, docker_machine and gitlab_runners inventory plugins

plugins/modules/database/influxdb/influxdb_user.py
influxdb_user module don't change the admin flag for existing
user
Fixes: ansible/ansible#68139
plugins/modules/database/influxdb/influxdb_user.py
=> influxdb_user: Don't grant admin privilege in check mode

tests/utils/shippable/shippable.sh
=> HACK: Use ansible/ansible#68550 instead of devel branch of Ansible to prevent full CI runs when changelog fragments are added

shippable.yml
This reverts commit f2418d343db7ad6a490b4d78bd9dbeec9ab5ab67.
Looks like we have no CI anymore right now.
CI
=> Revert "Don't run CI on Master (#73)"

plugins/become/doas.py, plugins/become/dzdo.py, plugins/become/ksu.py, plugins/become/machinectl.py, plugins/become/pbrun.py, plugins/become/pfexec.py, plugins/become/pmrun.py, plugins/become/sesu.py, tests/unit/plugins/become/helper.py, tests/unit/plugins/become/test_doas.py, tests/unit/plugins/become/test_dzdo.py, tests/unit/plugins/become/test_ksu.py, tests/unit/plugins/become/test_pbrun.py, tests/unit/plugins/become/test_pfexec.py
Currently all become plugins in community.general are broken (if `become_exe` is not explicitly specified by the user), since https://github.com/ansible/ansible/blob/01638e0ea222b115909bfd73677b97be92744ff2/lib/ansible/playbook/play_context.py#L358 explicitly uses the `become_name` as a default value, which for become plugins in community.general is prefixed with `community.general.`.
This fix is a hack. If we want this collection to work with current versions of 2.9, we need to keep it, otherwise we can get rid of it once ansible/ansible is fixed.
plugins/become/
=> Fix become plugins

changelogs/fragments/68374_rhn_channel.yml, plugins/modules/packaging/os/rhn_channel.py
Provide parameter to override HTTPS verification.
Fixes: ansible/ansible#68374
changelogs/fragments/68374_rhn_channel.yml
plugins/modules/packaging/os/rhn_channel.py
=> rhn_channel: Add validate_certs parameter

tests/integration/targets/supervisorctl/aliases, tests/integration/targets/supervisorctl/tasks/main.yml, tests/integration/targets/supervisorctl/tasks/test_stop.yml, tests/integration/targets/supervisorctl/templates/supervisord.conf
Fix problem with supervisorctl tests on OSX: the .sock filename seems to be "too long" (for OSX). ([CI run where it breaks](https://app.shippable.com/github/ansible-collections/community.general/runs/239/36/tests)) This is probably caused by the output dir to be longer since it includes `ansible_collections.community.general` and stuff.
supervisorctl
=> supervisorctl tests: shorten path to .sock file to make OSX happy.

changelogs/fragments/80-update_docker_connection_plugin.yml, plugins/connection/docker.py
Duplicate of https://github.com/ansible/ansible/pull/68012 . Hoping to merge here and then backport to ansible stable-2.9.
https://github.com/ansible/ansible/pull/67832 fixes the need to run powershell modules on windows containers via docker connection. However, while running win_copy on windows containers, destination path is prefixed, which doesn't work in the case of windows. The changes in this PR take care of bypassing that while running the role on windows containers.
Docker connection plugin
```paste below
```
=> Update docker connection plugin

changelogs/fragments/66592_ipa_encoding_fix.yml, plugins/module_utils/ipa.py
Fixes: ansible/ansible#66592
changelogs/fragments/66592_ipa_encoding_fix.yml
plugins/module_utils/ipa.py
=> ipa: Remove redundant encoding in json.loads

changelogs/fragments/59376-homebrew_fix.yml, plugins/modules/packaging/os/homebrew.py
homebrew now returns details about changed and unchanged packages
after performing the operations.
Fixes: ansible/ansible#59376
plugins/modules/packaging/os/homebrew.py
=> homebrew: Add info about changed packages

tests/integration/targets/zypper_repository/aliases
The tests currently fail reliably:
- https://app.shippable.com/github/ansible-collections/community.general/runs/359/23/tests https://app.shippable.com/github/ansible-collections/community.general/runs/359/24/tests
- https://app.shippable.com/github/ansible-collections/community.general/runs/358/23/tests https://app.shippable.com/github/ansible-collections/community.general/runs/358/24/tests
- https://app.shippable.com/github/ansible-collections/community.general/runs/357/23/tests https://app.shippable.com/github/ansible-collections/community.general/runs/357/24/tests
- https://app.shippable.com/github/ansible-collections/community.general/runs/356/31/tests https://app.shippable.com/github/ansible-collections/community.general/runs/356/32/tests
- …
=> Temporarily disable zypper_repository tests

plugins/modules/cloud/docker/docker_container.py
Improve docs to avoid misunderstanding when removing docker container
In docker docs, it said [Note that if a volume was specified with a name, it will not be removed](https://docs.docker.com/engine/reference/commandline/rm/#remove-a-container-and-its-volumes), so only anonymous volumes can be removed with container.
Related issue: https://github.com/ansible/ansible/issues/19858
=> docker_container: improve docs in keep_volumes

changelogs/fragments/ldap-params-removal.yml, plugins/modules/net_tools/ldap/ldap_attr.py, plugins/modules/net_tools/ldap/ldap_entry.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.9.txt
Fix for CVE-2020-1746
Module options that circumvent Ansible's option handling were disallowed
in:
https://meetbot.fedoraproject.org/ansible-meeting/2017-09-28/ansible_dev_meeting.2017-09-28-15.00.log.html
Additionally, this particular usage can be insecure if bind_pw is set
this way as the password could end up in a logfile or displayed on
stdout.
Initially opened as https://github.com/ansible/ansible/pull/67866.
=> Remove the params module option from ldap_attr and ldap_entry

changelogs/fragments/22-jira.yaml, plugins/modules/web_infrastructure/jira.py
Added Jira JQL Search support updated docs and  error handling
modules/web_infrastructure/jira.py
```
(venv) pto:ansible pto$ ansible-playbook jira-test.yml
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
PLAY [localhost] ************************************************************************************************* …
```
=> Added search function to jira module and bugfixes

tests/integration/targets/mysql_info/tasks/main.yml
mysql_info: added spaces and comments to CI tests
they disappeared since the migration to community.general
```tests/integration/targets/mysql_info/tasks/main.yml```
=> mysql_info: added spaces to CI tests

changelogs/fragments/114-puppet-commandline-construction.yml, plugins/modules/system/puppet.py
Fix command line construction in the `puppet` module related to check mode and using manifests directly
puppet
Commit 69ead0ba7864b1e7367eb9755b51d30ecc0da0d2 in the ansible/ansible
repository introduced another if-statement in the middle of a if/elif pair,
which causes the elif to execute together with the original if
which created '--noop --no-noop' commands.
Another issue I noticed while fixing that was that if I apply an manifest directly, it tries to execute `--noop/path/manifest.pp` which fails.
**Test case 1**
```
---
tasks:
- puppet:
```
Executed with:
```
ansible-playbook --check /test.yaml
```
Before change:
```
/usr/bin/puppet agent --onetime --no-daemonize --no-usecacheonfailure --no-splay --detailed-exitcodes --verbose --color 0 --noop …
```
=> Fix command line construction in the puppet module

changelogs/fragments/mysql_info_add_parameter.yml, plugins/modules/database/mysql/mysql_info.py
Add parameter for `__collect` method
By default the class `MySQL_Info` get all MySQL instance information,
add  parameter for `__collect` to  get only what wants to know(information)
lib/ansible/modules/database/mysql/mysql_info.py
=> mysql_info: Add parameter for __collect method

changelogs/fragments/142-mysql_user_add_resource_limit_parameter.yml, plugins/modules/database/mysql/mysql_user.py, tests/integration/targets/mysql_user/aliases, tests/integration/targets/mysql_user/tasks/main.yml, tests/integration/targets/mysql_user/tasks/resource_limits.yml
mysql_user: add resource_limits parameter
Fixes: https://github.com/ansible-collections/community.general/issues/133
```
resource_limits:
description:
- Limit the user for certain server resources. Provided since MySQL 5.6 / MariaDB 10.2.
- "Available options are C(MAX_QUERIES_PER_HOUR: num), C(MAX_UPDATES_PER_HOUR: num),
C(MAX_CONNECTIONS_PER_HOUR: num), C(MAX_USER_CONNECTIONS: num)."
- Used when I(state=present), ignored otherwise.
type: dict
```
```
- name: Limit bob's resources to 10 queries per hour and 5 connections per hour
mysql_user:
name: bob
resource_limits:
MAX_QUERIES_PER_HOUR: 10
MAX_CONNECTIONS_PER_HOUR: 5
```
```plugins/modules/database/mysql/mysql_user.py```
=> mysql_user: add resource_limits parameter

changelogs/fragments/116-postgresql_user_add_trust_input_parameter.yml, plugins/module_utils/database.py, plugins/modules/database/postgresql/postgresql_user.py, tests/integration/targets/postgresql_user/defaults/main.yml, tests/integration/targets/postgresql_user/tasks/postgresql_user_general.yml, tests/unit/plugins/module_utils/test_database.py
related to https://github.com/ansible-collections/community.general/issues/106
The PR:
1. implements checks for potentially dangerous output (like SQL injections)
2. intreduces ```trust_input``` parameter to postgresql_user module (not to break current pipelines it's set as ```yes```)
If it's approved by community and merged:
1. it'll be intruduced to postgresql_privs, postgresql_membership and other modules where needed.
2. we'll continue to solve https://github.com/ansible/ansible/issues/66422 and other stuff to be able to use names containing dots.
**Note: it has unit tests, but would be really great if anybody who's experienced in re-module regexp looks at this to recheck.**
```plugins/module_utils/database.py``` …
=> postgresql_user: add trust_input parameter

changelogs/fragments/83-dense-callback-warning.yml, plugins/callback/dense.py
Migrated from ansible/ansible#65377
Fixes ansible/ansible#64628
Removes a warning message that is displayed every time dense callback plugin is used.
This should also make dense callback plugin effectively take its configuration variables into account.
plugins/callback/dense
Warning message mentioned in ansible/ansible#64628 is:
```
[WARNING]: Failure using method (v2_runner_on_start) in callback plugin
(<ansible.plugins.callback.dense.CallbackModule_dense object at 0x1105c6890>): 'show_per_host_start'
```
Absence of `v2_runner_on_start()` in callback `dense` is not an issue here because method inherited from callback `default` should work.
The true problem is that plugin class is named `CallbackModule_dense` instead of `CallbackModule`.
Therefore …
=> Fix warning message in dense callback plugin

changelogs/fragments/55919-rabbitmq_publish-fix-for-recent-pika-versions.yml, changelogs/fragments/lookup_rabbitmq-is_closing-bug.yml, changelogs/fragments/rabbitmq_publish-certificate-checks.yml
When adding changelog fragments from ansible/ansible in #156, I forgot to exclude the rabbitmq fragments - the rabbitmq content has been removed from community.general in #13.
This PR removes these changelog fragments.
CC @odyssey4me since you might be interested in them :)
changelog
=> Remove rabbitmq-related changelog fragments

changelogs/fragments/178-postgresql_membership_remove_unused_import.yml, plugins/modules/database/postgresql/postgresql_membership.py
postgresql_membership: remove unused import of exec_sql function
```plugins/modules/database/postgresql/postgresql_membership.py```
=> postgresql_membership: remove unused import of exec_sql function

changelogs/fragments/158-postgresql_membership_add_trust_input_parameter.yml, plugins/modules/database/postgresql/postgresql_membership.py, tests/integration/targets/postgresql_membership/defaults/main.yml, tests/integration/targets/postgresql_membership/tasks/postgresql_membership_initial.yml
postgresql_membership: add trust_input parameter
continuing to introduce https://github.com/ansible-collections/community.general/pull/116
```plugins/modules/database/postgresql/postgresql_membership.py```
=> postgresql_membership: add trust_input parameter

plugins/modules/source_control/gitlab/gitlab_user.py
Adds support to gitlab_user to block/unblock the account of a given user (#187)
Fixes #187
Fixes https://github.com/ansible/ansible/issues/61754
Fixes https://github.com/ansible/ansible/pull/61864
Fixes https://github.com/ansible/ansible/pull/66273
gitlab_user
It is currently not possible to specify state=blocked or state=unblocked to block/unblock the user's account in GitLab.
Previously, the only possible options were to create or delete the account.
=> gitlab_user: add support to block / unblock user

changelogs/fragments/68251-redfish_config-fix-boolean-bios-attr-support.yaml, plugins/modules/remote_management/redfish/redfish_config.py
Currently the redfish_config module will convert boolean bios_attribute_value
settings to strings (type str). This will cause BMCs expecting booleans to
error out.
This PR will change the default type of bios_attribute_value to 'raw' in order
to support strings and booleans.
Fixes ansible/ansible#68251
Note that this is a copy/pasta of ansible/ansible#68382. 
This fixes the behavior in Ansible 2.10 (also present in Ansible 2.9 and Ansible 2.8) that converts boolean based BIOS values to strings.
Note that I opened another PR against `stable-2.9` initially: ansible/ansible#68254
I can close this out and open a separate backport request to fix this bug in `stable-2.9` and `stable-2.8`. The backport request will require a slight tweak to redfish_utils.py to fix this bug because …
=> redfish_config: fix support for boolean BIOS attributes

changelogs/fragments/123-slack-add_bot_token_support_thread_id.yml, plugins/modules/notification/slack.py, tests/unit/plugins/modules/notification/test_slack.py
The main point of this PR is to add support for threaded messages in slack.
Add support for user/bot/application tokens (and Slack WebAPI).
Fix input type for thread_id, which needs to be string.
Return thread_ts/thread_id when user/bot tokens are used, so they can be reused later
Fixes:
https://github.com/ansible/ansible/pull/56862 
https://github.com/ansible/ansible/pull/65320
notifications/slack
Slack Notification module has a support for posting message as a threaded reply, however  
thread_id was incorrectly set to float. 
Additionally, Slack's Webhook API responds with plain 'http/2 200' and 'OK'. In order to 
utilize thread_ts, a support for Slack WebAPI had to be added as it returns more details 
about the message  being posted, including `ts`.
```paste …
```
=> Slack: Add bot/user token support, correct thread_ts support

changelogs/fragments/202-jenkins_plugin-fix-import.yml, plugins/modules/web_infrastructure/jenkins_plugin.py
The `jenkins_plugin` module imported `text_type` and `binary_type` from `ansible.module_utils._text`, which in turn imported them from `ansible.module_utils.six`. ansible/ansible#68965 removed them from `_text`, hence the module broke and CI also failed for unrelated modules/plugins.
plugins/modules/web_infrastructure/jenkins_plugin.py
=> Fix CI and jenkins_plugin module

plugins/modules/database/postgresql/postgresql_db.py, tests/integration/targets/postgresql_db/defaults/main.yml, tests/integration/targets/postgresql_db/tasks/state_dump_restore.yml
Fixes https://github.com/ansible-collections/community.general/issues/106
1. postgresql_db: add trust_input parameter
2. allow db names containing dots
Both are closely related, so one PR
```plugins/modules/database/postgresql/postgresql_db.py```
=> postgresql_db: add trust_input parameter

plugins/modules/net_tools/ip_netns.py
Was referenced as 'namespace' while it should have been 'ip_netns'.
Closes: #203
Signed-off-by: Marcelo Ricardo Leitner <marcelo.leitner@gmail.com>
ip_netns
=> ip_netns: fix module name in example

plugins/modules/web_infrastructure/jira.py
Fixes #204.
The call to pathname2url was broken in Python 2. Fix it by importing from module_utils.six instead of importing urllib and calling it from there.
The code being fixed is pretty new, see https://github.com/ansible-collections/community.general/pull/22 where it was added. So I don't think this bug is in a released version yet. For that reason maybe there's no need for a changelog, but let me know if you think otherwise.
jira
See more details in #204. I've tested this locally with Python 3 and Python 2 and it works well for me.
=> jira: Fix incompatible pathname2url import (#204)

changelogs/fragments/151-mysql_db_add_use_shell_parameter.yml, plugins/modules/database/mysql/mysql_db.py, tests/integration/targets/mysql_db/tasks/state_dump_import.yml
Fixes https://github.com/ansible/ansible/issues/20196
```mysql_db```: prevent broken pipe errors when ```state=import``` by using an intermediate shell process
Added the ```use_shell``` parameter.
```plugins/modules/database/mysql/mysql_db.py```
=> mysql_db: add use_shell parameter to prevent Broken pipe errors

changelogs/fragments/100-postgresql_user_scram_sha_256_support.yml, plugins/module_utils/saslprep.py, plugins/modules/database/postgresql/postgresql_user.py, tests/integration/targets/postgresql_user/tasks/test_password.yml, tests/unit/module_utils/test_saslprep.py
postgresql_user: add scram-sha-256 password support
i rewrote https://github.com/ansible/ansible/pull/51121 in part of saslprep
implemended RFC from scratch with BSD licence
```plugins/modules/database/postgresql/postgresql_user.py```
```plugins/module_utils/saslprep.py```
=> postgresql_user: add scram-sha-256 password support

plugins/modules/database/mysql/mysql_user.py
Fixes: https://github.com/ansible-collections/community.general/issues/217
mysql_user:
1. add check_implicit_admin parameter's documentation
2. add an example
```plugins/modules/database/mysql/mysql_user.py```
=> mysql_user: improve check_implicit_admin parameter's documentation

changelogs/fragments/223-manageiq_provider-fix-serialization.yml, plugins/modules/remote_management/manageiq/manageiq_provider.py
… running module on Python 3 Environment
delete_nulls function was changed in manageiq_provider.py to fix Serialization Error ocurring on a python 3 environment.
Fix was tested with:
- python 3.7.3
- python 2.7.16
Fixes #222 
```paste below
This pull request is supposed to ensure compatibility with python2 and python3 for module manageiq_provider
```
=> fix "TypeError: Object of type map is not JSON serializable"

tests/integration/targets/consul/aliases, tests/utils/shippable/shippable.sh
Use the same hack as in ansible-collections/community.crypto#36 to avoid the always unstable macOS result when `setup_openssl` is used. This allows to re-enable the consul tests.
The hack can be removed once ansible/ansible#68701 has been fixed.
Closes #117.
consul
CI
=> Reenable consul test, fix issues with a hack

changelogs/fragments/221-parted-fs_type-parameter.yml, plugins/modules/system/parted.py, tests/unit/plugins/modules/system/test_parted.py
Closes #135
Allow to customize the file system type for parted.
parted
=> parted: support fs_type

changelogs/fragments/198-postgresql_owner_add_trust_input_parameter.yml, plugins/modules/database/postgresql/postgresql_owner.py, tests/integration/targets/postgresql_owner/defaults/main.yml, tests/integration/targets/postgresql_owner/tasks/postgresql_owner_initial.yml
Related to https://github.com/ansible-collections/community.general/issues/106
The PR:
1. Adds the trust_input parameter to the postgresql_owner module
2. Allows to pass values containing dots to the following parameters:
- new_owner
- reassign_owned_by
- session_role
- obj_name when obj_type is database/tablespace
Note:
1. I added a lot of spaces to CI tests which were removed (unexpectedly) during the migration to the collections. I'll add also disappeared comments by separate PR later.
2. Names of the other types like `table` or `function` can't contain dots right now because in the current design they are used to determine database/schema identifiers for these objects. We'll necessarily solve that somehow later. …
=> postgresql_owner: add trust_input parameter

changelogs/fragments/23-hashi-vault-lookup-refresh.yaml, plugins/lookup/hashi_vault.py, tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml, tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml, tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml
<s>The original had a changelog fragment but I don't see where to put that in the new repo.</s> 
New changelog added.
----
This PR adds support for the AWS IAM Login auth method in Hashicorp Vault. Along the way ran into some small bugs and possible improvements and so it ended up being a larger change.
- Added INI sources for some of the parameters like the vault URL, role ID, and some of the newer params.
- [BUG] Previously, this plugin didn't work correctly when used with `with_`. If you passed `with_hashi_vault` a list of terms strings, it would look up the first one, and then for each subsequent one it would ignore what was passed and return the first result again. This is fixed.
- When passing params through the term string, you can now pass secrets as an unnamed argument, if it …
=> hashi_vault refresh - Add AWS login methods, bugfixes, cleanup

tests/integration/targets/postgresql_owner/tasks/postgresql_owner_initial.yml
- All comments desappeared from postgresql_owner CI tests after migration to the collections.
- Change formatting of some (relatively long) SQL statements to make them more readable
```tests/integration/targets/postgresql_owner/tasks/postgresql_owner_initial.yml```
=> postgresql_owner: fix CI test formatting, return some disappeared comments to place

changelogs/fragments/243-cloudflare_dns_fix_keyerror.yml, plugins/modules/net_tools/cloudflare_dns.py
Fixes https://github.com/ansible-collections/community.general/issues/236
cloudflare_dns
Fix errors of the type `KeyError: 'success'` to show a more meaningful message, like:
`API user does not have permission; Status: 401; Method: DELETE: Call: /zones/a8222778e37a0276468013d671b39e15/dns_records/b8051d66e565436cd6f24fbd34621f52; Error details: You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard.`
=> cloudflare_dns: fix KeyError

changelogs/fragments/259-postgresql_schema_add_trust_input_parameter.yml, plugins/modules/database/postgresql/postgresql_schema.py, tests/integration/targets/postgresql_schema/defaults/main.yml, tests/integration/targets/postgresql_schema/tasks/postgresql_schema_initial.yml
postgresql_schema: add trust_input parameter
Related to #106
The PR:
- Adds the trust_input parameter to the postgresql_schema module
- Allows to pass values containing dots to the following parameters:
name
owner
session_role
```plugins/modules/database/postgresql/postgresql_schema.py```
=> postgresql_schema: add trust_input parameter

changelogs/fragments/240-postgresql_tablespace_add_trust_input_parameter.yml, plugins/modules/database/postgresql/postgresql_tablespace.py, tests/integration/targets/postgresql_tablespace/defaults/main.yml, tests/integration/targets/postgresql_tablespace/tasks/postgresql_tablespace_initial.yml
Related to https://github.com/ansible-collections/community.general/issues/106
The PR:
1. Adds the trust_input parameter to the postgresql_tablespace module
2. Allows to pass values containing dots to the following parameters:
- tablespace/name
- owner
- session_role
- rename_to
Note: I added a lot of empty lines to CI tests which were removed (unexpectedly) during the migration to the collections.
```plugins/modules/database/postgresql/postgresql_tablespace.py```
=> postgresql_tablespace: add trust_input parameter

plugins/modules/database/postgresql/postgresql_info.py
The `sample` value contains a dictionary with a non-string key. That's not a valid JSON value and cannot be returned by the module.
Found with ansible/ansible#69287.
postgresql_info
=> postgresql_info: fix invalid 'sample' value

changelogs/fragments/278-zfs_delegate_admin_add_diff_hold_release.yml, plugins/modules/storage/zfs/zfs_delegate_admin.py
Moved from https://github.com/ansible/ansible/pull/64562
zfs_delegate_admin module has a whitelist of zfs permissions that it can manage. 'hold', 'release', and 'diff' are missing, so add them (in theory this list should also include all properties, but hold/release fix my immediate problem :)
zfs_delegate_admin module
=> zfs_delegate_admin: add diff,hold,release to list of permissions

changelogs/fragments/264-postgresql_idx_add_trust_input_parameter.yml, plugins/modules/database/postgresql/postgresql_idx.py, tests/integration/targets/postgresql_idx/tasks/postgresql_idx_initial.yml
postgresql_idx:
- we can pass parameters where spec symbols are technically allowed
- remove the extra condition with schema `public` (because if it is not passed, it'll be set as `public` in the class constructor)
- add empty lines between tests (which were disappeared after the migration from ansible/ansible to community.general
```plugins/modules/database/postgresql/postgresql_idx.py```
=> postgresql_idx: add trust_input parameter

changelogs/fragments/280-postgresql_subscription_add_trust_input_session_role.yml, plugins/modules/database/postgresql/postgresql_subscription.py, tests/integration/targets/postgresql_subscription/tasks/postgresql_subscription_initial.yml
postgresql_subscription:
- add session_role parameter
```plugins/modules/database/postgresql/postgresql_subscription.py```
=> postgresql_subscription: add trust_input and session_role parameters

changelogs/fragments/279-postgresql_publication_add_trust_input_session_role.yml, plugins/modules/database/postgresql/postgresql_publication.py, tests/integration/targets/postgresql_publication/tasks/postgresql_publication_initial.yml
postgresql_publication:
- add session_role parameter, i missed it creating the module:(
```plugins/modules/database/postgresql/postgresql_publication.py```
=> postgresql_publication: add trust_input and session_role parameters

changelogs/fragments/272-postgresql_lang_add_trust_input_parameter.yml, plugins/modules/database/postgresql/postgresql_lang.py, tests/integration/targets/postgresql_lang/tasks/postgresql_lang_add_owner_param.yml
postgresql_lang:
- we can pass parameters where spec symbols are technically allowed
```plugins/modules/database/postgresql/postgresql_lang.py```
=> postgresql_lang: add trust_input parameter

changelogs/fragments/277-datadog_monitor-adds-missing-log-alert-type.yml, plugins/modules/monitoring/datadog/datadog_monitor.py
Fixes #251
Adds missing `'log alert'` type supported by the datadog python module
before (using old code before process alert even):
```
"msg": "value of type must be one of: metric alert, service check, event alert, got: log alert"}
```
after:
```
datadog_monitor:
type: "log alert"
...
query: "@msg:\"some log message\"\").index(\"main\").rollup(\"count\").last(\"10m\") >= 1"
```
creates the monitor (tested) and log output is nominal
=> datadog_monitor: adds missing 'log alert' type to supported types

plugins/cache/redis.py
Just a working example to use redis as a cache with security enabled.
redis cache plugin
I struggled to find a working example, so wanted to update the documentation.
```paste below
```
=> Update documentation for example of redis connection string

changelogs/fragments/295-postgresql_sequence_add_trust_input.yml, plugins/modules/database/postgresql/postgresql_sequence.py, tests/integration/targets/postgresql_sequence/tasks/postgresql_sequence_initial.yml
Have added the trust_input option to the postgresql_sequence module.
Related to: #106 and #210 
`plugins/modules/database/postgresql/postgresql_sequence.py`
```paste below
```
=> postgresql_sequence: add trust_input option

changelogs/fragments/294-postgresql_query_add_trust_input_parameter.yml, plugins/modules/database/postgresql/postgresql_query.py, tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
postgresql_query: add trust_input parameter
```plugins/modules/database/postgresql/postgresql_query.py```
=> postgresql_query: add trust_input parameter

changelogs/fragments/298-postgresql_slot_add_trust_input.yml, plugins/modules/database/postgresql/postgresql_slot.py, tests/integration/targets/postgresql_slot/tasks/postgresql_slot_initial.yml
Have added a trust_input option to the postgresql_slot module. This
only checks the session_role since all other options are passed as
parameters.
Related to  #106 and #210.
`plugins/modules/database/postgresql/postgresql_slot.py`
```paste below
```
=> Add trust_input option to postgresql_slot module

changelogs/fragments/listen_ports_facts_doc.yml, plugins/modules/system/listen_ports_facts.py
Updated listen_ports_facts module documentation to reflect
- Linux only support
- Required netstat command
Fixes: ansible/ansible#68077
changelogs/fragments/listen_ports_facts_doc.yml
plugins/modules/system/listen_ports_facts.py
=> Updated listen_ports_facts documentation

plugins/modules/database/postgresql/postgresql_db.py, plugins/modules/database/postgresql/postgresql_ext.py, plugins/modules/database/postgresql/postgresql_idx.py, plugins/modules/database/postgresql/postgresql_lang.py, plugins/modules/database/postgresql/postgresql_membership.py, plugins/modules/database/postgresql/postgresql_owner.py, plugins/modules/database/postgresql/postgresql_privs.py, plugins/modules/database/postgresql/postgresql_publication.py, plugins/modules/database/postgresql/postgresql_schema.py, plugins/modules/database/postgresql/postgresql_sequence.py, plugins/modules/database/postgresql/postgresql_subscription.py, plugins/modules/database/postgresql/postgresql_tablespace.py, plugins/modules/database/postgresql/postgresql_user.py, tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml, tests/integration/targets/postgresql_privs/tasks/postgresql_privs_initial.yml, tests/integration/targets/postgresql_publication/tasks/postgresql_publication_initial.yml, tests/integration/targets/postgresql_subscription/tasks/postgresql_subscription_initial.yml, tests/integration/targets/postgresql_user/tasks/postgresql_user_general.yml, tests/integration/targets/postgresql_user/tasks/postgresql_user_initial.yml
postgresql modules: improve `trust_input` parameter's documentation, improve CI tests
```plugins/modules/database/postgresql/postgresql_db.py```
...
=> postgresql modules: improve trust_input parameter's documentation, improve CI tests

changelogs/fragments/308-postgresql_info_add_trust_input_parameter.yml, plugins/modules/database/postgresql/postgresql_info.py, tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml
postgresql_info: add trust_input parameter
```plugins/modules/database/postgresql/postgresql_info.py```
=> postgresql_info: add the trust_input parameter

tests/unit/requirements.txt
One part of #296 I forgot to include into #306: make sure that `semantic_version` is included in unit test requirements. (It is included in the `default` docker container for Ansible 2.10, but not for 2.9.)
tests/unit/requirements.txt
=> Update tests/unit/requirements.txt for maven_artifact

plugins/modules/cloud/univention/udm_dns_record.py
Fixing #315 
udm_dns_record
```paste below
Please note, that IPv6 addresses are stored in the univention ldap as "A" records, not "AAAA"
This is my first pull-request to ansible, please be kind.
```
=> Fix udm_dns_record example, fixing #315

changelogs/fragments/269-flatpak-command-list.yaml, plugins/modules/packaging/os/flatpak.py, plugins/modules/packaging/os/flatpak_remote.py
Using a list ensures that all subprocess arguments are correctly
escaped. By building strings and then calling .split(), potential
arguments with a space will be incorrectly split over two arguments.
When a string is needed for presentation, join to the list to build the
string.
flatpak
=> flatpak: Build commands as lists instead of strings

changelogs/fragments/310-postgresql_user_obj_stat_info_add_trust_input.yml, plugins/modules/database/postgresql/postgresql_user_obj_stat_info.py, tests/integration/targets/postgresql_user_obj_stat_info/tasks/postgresql_user_obj_stat_info.yml
Have added a trust_input option to the postgresql_user_obj_stat_info
module. This only checks the session_role since all other options are
passed as parameters. Have also refactored the module to try to simplify
the code.
Related to #106 and #210
`plugins/modules/database/postgresql/postgresql_user_obj_stat_info.py`
```paste below
```
=> Add trust_input to postgresql_user_obj_stat_info

changelogs/fragments/313-postgresql_copy_add_trust_input_session_role.yml, plugins/modules/database/postgresql/postgresql_copy.py, tests/integration/targets/postgresql_copy/tasks/postgresql_copy_initial.yml
postgresql_copy: add trust_input parameter
```plugins/modules/database/postgresql/postgresql_copy.py```
=> postgresql_copy: add trust_input parameter

changelogs/fragments/312-postgresql_ping_add_trust_input_session_role.yml, plugins/modules/database/postgresql/postgresql_ping.py, tests/integration/targets/postgresql_ping/tasks/postgresql_ping_initial.yml
postgresql_ping:
- add session_role parameter
```plugins/modules/database/postgresql/postgresql_ping.py```
=> postgresql_ping: add session_role and trust_input parameters

changelogs/fragments/302-postgresql_set_add_trust_input_parameter.yml, plugins/modules/database/postgresql/postgresql_set.py, tests/integration/targets/postgresql_set/tasks/postgresql_set_initial.yml
postgresql_set: add trust_input parameter
```plugins/modules/database/postgresql/postgresql_set.py```
=> postgresql_set: add trust_input parameter

.github/BOTMETA.yml
Adds me (`joshuaconner`) to ignore list for `docker_container` module in `BOTMETA`
BOTMETA
I'm not an active user of this module anymore, so am unable to provide meaningful review.
=> BOTMETA: ignore joshuaconner for docker_container module

.gitignore, plugins/modules/database/misc/redis.py, plugins/modules/database/misc/redis_info.py, plugins/modules/redis_info.py, tests/integration/targets/redis_info/aliases, tests/integration/targets/redis_info/defaults/main.yml, tests/integration/targets/redis_info/meta/main.yml, tests/integration/targets/redis_info/tasks/main.yml, tests/integration/targets/setup_redis_replication/defaults/main.yml, tests/integration/targets/setup_redis_replication/handlers/main.yml, tests/integration/targets/setup_redis_replication/meta/main.yml, tests/integration/targets/setup_redis_replication/tasks/main.yml, tests/integration/targets/setup_redis_replication/tasks/setup_redis_cluster.yml, tests/unit/plugins/modules/database/misc/test_redis_info.py
Added a new command `info` to retrieve information and statistics about the Redis server.
This will be useful for getting server status.
redis
In my case, I use Redis server information to data migration between old and new versions of environment. Example:
```yaml
- name: "start_redis : Activate slave mode"
redis:
login_host: "{{ project_redis_host }}"
login_port: "{{ project_redis_port }}"
command: slave
master_host: "{{ _project_redis_source_address }}"
master_port: "{{ _project_redis_source_port }}"
- name: "start_redis : Wait to sync to be done"
redis:
command: info
login_host: "{{ project_redis_host }}"
login_port: "{{ project_redis_port }}"
register: _result
until: (_result.info.master_link_status | default('down')) == 'up'
retries: 150
delay: 1
- name: …
```
=> Add info command to redis module

changelogs/fragments/326-pacman_improve_package_state_detection_speed.yml, plugins/modules/packaging/os/pacman.py
Don't query for full details of a package. It is sufficient to query
the name and version. This also simplifies parsing the output.
When using a large amount packages  the  pacman module takes very long to determine the version numbers, because it parses the `pacman -Qi` (full-detail) output.
pacman
Instead of parsing `gcc -Qi gcc`:
```
Name            : gcc
Version         : 9.3.0-1
Description     : The GNU Compiler Collection - C and C++ frontends
Architecture    : x86_64
URL             : https://gcc.gnu.org
Licenses        : GPL  LGPL  FDL  custom
Groups          : base-devel
Provides        : gcc-multilib
Depends On      : gcc-libs=9.3.0-1  binutils>=2.28  libmpc
Optional Deps   : lib32-gcc-libs: for generating code for 32-bit ABI
Required By     : clang  ghc …
```
=> pacman: Improve package state detection speed

changelogs/fragments/318-linode-inventory-access_token-fix.yaml, plugins/inventory/linode.py
Read config before trying to use the config.
Original issue: https://github.com/ansible/ansible/issues/66874
linode inventory plugin
=> linode inventory plugin: fix parsing of access_token

plugins/modules/packaging/os/apk.py, plugins/modules/packaging/os/homebrew_tap.py, plugins/modules/packaging/os/layman.py, plugins/modules/packaging/os/opkg.py, plugins/modules/packaging/os/pkg5_publisher.py, plugins/modules/packaging/os/pkgin.py, plugins/modules/packaging/os/pkgutil.py, plugins/modules/packaging/os/portage.py, plugins/modules/packaging/os/portinstall.py, plugins/modules/packaging/os/rhn_channel.py, plugins/modules/packaging/os/slackpkg.py, plugins/modules/packaging/os/sorcery.py, plugins/modules/packaging/os/svr4pkg.py, plugins/modules/packaging/os/swdepot.py, plugins/modules/remote_management/hpilo/hpilo_info.py, plugins/modules/remote_management/ipmi/ipmi_boot.py, plugins/modules/remote_management/ipmi/ipmi_power.py, plugins/modules/source_control/bzr.py, plugins/modules/source_control/git_config.py, plugins/modules/source_control/github/github_deploy_key.py, plugins/modules/source_control/github/github_hooks.py, plugins/modules/storage/hpe3par/ss_3par_cpg.py, plugins/modules/system/openwrt_init.py, plugins/modules/system/osx_defaults.py, plugins/modules/web_infrastructure/apache2_mod_proxy.py, plugins/modules/web_infrastructure/apache2_module.py, plugins/modules/web_infrastructure/django_manage.py, plugins/modules/web_infrastructure/htpasswd.py, plugins/modules/web_infrastructure/supervisorctl.py, plugins/modules/web_infrastructure/taiga_issue.py
https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#examples-block
Per playbook best practices, each example should include a name: line:
```
EXAMPLES = r'''
- name: Ensure foo is installed
modulename:
name: foo
state: present
'''
```
The name: line should be capitalized and not include a trailing dot.
**I'm gonna fix all modules in next PRs**
=> Fix Ansible documentation in part of example formatting. Part 2

shippable.yml, tests/integration/targets/setup_docker/tasks/Fedora.yml, tests/integration/targets/timezone/tasks/main.yml
Implements ansible-collections/overview#59. I opted to drop Fedora 30 from CI since community.general is already eating a lot of CI resources, and since it is EOL soon.
CI
=> Add Fedora 32 to CI; drop Fedora 30 which is soon EOL

changelogs/fragments/245-proxmox.yml, plugins/modules/cloud/misc/proxmox.py
adding missing options for the Proxmox LXC container.
- hookscript
- description
proxmox
no big change only added 2 new parameters.
example:
```
- proxmox:
vmid: 100
node: uk-mc02
api_password: 1q2w3e
api_host: node1
password: 123456
hostname: example.org
ostemplate: 'local:vztmpl/debian-10.0-standard_10.0-1_amd64.tar.gz'
hookscript: 'local:snippets/vm_hook.sh'
description: created with ansible
```
=> add description and hookscript parameters to proxmox LXC container

changelogs/fragments/115-deprecated-helm-module.yaml, meta/routing.yml, plugins/modules/cloud/misc/helm.py
Put Helm module as deprecated
helm
Like explain in https://github.com/ansible/ansible/issues/61546 current helm module is obsolete.
A new module has been written and waiting to be merged inside kubernetes.collection ref: https://github.com/ansible-collections/kubernetes/pull/61
=> Deprecated Helm module

tests/utils/shippable/aws.sh, tests/utils/shippable/azure.sh, tests/utils/shippable/cloud.sh, tests/utils/shippable/hcloud.sh
Smoketests are not needed in collections, and none exist in this collection anyway.
Also remove scripts for aws, azure and hcloud tests that aren't needed anyway.
https://github.com/ansible-collections/overview/issues/45#issuecomment-630466482
CI
=> Remove smoketest traces

changelogs/fragments/372-gcp_storage_file-gracefully.yml, plugins/lookup/gcp_storage_file.py
Instead of dying with an `ImportError`, the lookup should die gracefully when google.cloud cannot be found (or changed in an incompatible way).
plugins/lookup/gcp_storage_file.py
=> gcp_storage_file: error gracefully when google.cloud is not there

plugins/connection/oc.py
This was using k8S_AUTH_CONTEXT with a lowercase k.  That doesn't match
with any of the other K8s stuff so users would probably be confused why
their envvar wasn't working.
community.general/plugins/connection/oc.py
```paste below
```
=> Fix the environment variable

plugins/filter/time.py
makes the error hint message less verbosy and more readable.
```
TASK [filter_time : test fail unknown unit] ***************************************************************************************
fatal: [testhost]: FAILED! => {"msg": "to_time_unit() can not convert to the following unit: lightyears. Available units (singular or plural): week, msecond, msec, month, second, sec, year, day, minute, millisecond, hour, min. Available short units: w, s, d, ms, y, h, mo, m"}
```
time_filter
```paste below
```
=> time_filter: improve hints in error message

tests/integration/targets/setup_openldap/tasks/main.yml
Use `xargs -r` in pipe , instead of plain `xargs` in `tests/integration/targets/setup_openldap/tasks/main.yml`
tests
PS: checked all other source code files for `xargs` usage - everything else uses `xargs -r`
=> [tests] trivial correction to openldap integration tests

plugins/lookup/dig.py, plugins/lookup/nios.py
The return docs for both of these didn't follow what the docs build
would understand.  Changed them so that they are properly formatted.
* lookup/dig.py
* lookup/nios.py
```paste below
```
=> Fix the docs for dig and nios.

tests/integration/targets/inventory_docker_swarm/runme.sh
Setting the exit code in a trap overrides the exit code that caused the trap to be called. This means if the test failed and called the trap, the test will exit with 0 rather than the failure exit code.
`tests/integration/targets/inventory_docker_swarm/runme.sh`
=> inventory_docker_swarm test - Remove exit code from trap

plugins/modules/net_tools/nmcli.py
Fix typo in nmcli.py documentation for prerequisite package name NetworkManager-**libnm** (reads NetworkManager-**nmlib** on this one line in the documentation, but is correct elsewhere).
- BugFix (Documentation) Pull Request
nmcli.py
=> Fix NetworkManager-libnm typo in nmcli.py documentation.

changelogs/fragments/183-parted_check_mode.yml, plugins/modules/system/parted.py, tests/unit/plugins/modules/system/test_parted.py
Fixed check_mode to consider current partition state when label and partition was already created.
Fixes: #183 
parted
=> parted: consider current partition state even in check_mode

changelogs/fragments/276-java_keystore-private_key_passphrase.yaml, plugins/modules/system/java_keystore.py, tests/unit/plugins/modules/system/test_java_keystore.py
* Migrated PR from https://github.com/ansible/ansible/pull/47768
Added support for entering a pass phrase for private_key (optionally). Fixes #275 
java_keystore
A new optional parameter named private_key_passphrase has been added to the java_keystore module. If source private_key does not require a password, then the new parameter can be omitted (or set as a blank string).
Steps to reproduce are available in the original issue description.
Before:
```
TASK [java_keystore] **********************************************************************************************************************************************************************************************
Enter pass phrase for /tmp/cert.key:
```
After:
```
TASK [java_keystore] …
```
=> java_keystore: Added support for private key pass phrase

changelogs/fragments/362-parted_documentation_fix.yml, plugins/modules/system/parted.py
Corrected documentation of parted module return value
Fixes: #362
parted
* general info is returned id 'disk' key (not 'device')
* documented 'script' key
=> parted: fix return value documentation

changelogs/fragments/412-docker-machine-add-ip-fallback.yaml, plugins/inventory/docker_machine.py
This PR addresses an issue observed initially by @benroose whereby the `docker-machine inspect <machine name>` command output unexpectedly lacks an `IPAddress` value but the IP address was/is available via the `docker-machine ip <machine name>` command.
docker_machine inventory plugin
The issue was brought to my attention by @gvashchenkolineate in [PR #1](https://github.com/ximon18/ansible-docker-machine-inventory-plugin/pull/1) against my original plugin repository for the Docker Machine Inventory plugin, along with the information that the issue was seen in the wild on the Google Compute Platform.
=> Add validity check for [Driver][IPAddress] else use docker-machine ip command.

changelogs/fragments/389-datadog_monitor-corrects-deprecated-message-param.yml, plugins/modules/monitoring/datadog/datadog_monitor.py
Noticed that `datadog_monitor.py` had not updated `_update_monitor` to use `notification_message` which deprecated `message` due to being a reserved keyword.
This PR makes that small correction.
Monitoring / datadog_monitor
before:
```
The error was: KeyError: 'message'
failed:
```
after:
works as expected
=> datadog_monitor: kwargs for _update_monitor used message vs notification_message

changelogs/fragments/227-sesu-use-defined-prompt.yaml, plugins/become/sesu.py
Make `sesu` become method use the defined prompt.
plugins/become/sesu.py
The `BecomeBase` expects the prompt in the `prompt` variable.
=> Update sesu.py: use defined prompt

galaxy.yml
Updated minimum version required for ansible.netcommon and google.cloud
in community.general collection.
This is required since ansible.posix collection CI is failing to download
non-existing versions of ansible.netcommon and google.cloud collection.
changelogs/fragments/update_dependency.yml
galaxy.yml
=> Update dependency versions in galaxy.yml

changelogs/fragments/418-add-tags-parameter-to-packet-device.yaml, plugins/modules/cloud/packet/packet_device.py
packet_device module currently does not handle tags in device creation. Tags are supported by packet.net api. This change is intended to fill this gap.
packet_device
Before the change:
- name: Create 1 device
tasks:
- packet_device:
project_id: 89b497ee-5afc-420a-8fb5-56984898f4df
hostnames: myserver
operating_system: ubuntu_16_04
plan: baremetal_0
facility: sjc1
After the change:
- name: Create 1 device
tasks:
- packet_device:
project_id: 89b497ee-5afc-420a-8fb5-56984898f4df
hostnames: myserver
tags: ci-xyz
operating_system: ubuntu_16_04
plan: baremetal_0
facility: sjc1
=> Add tags parameter to packet_device

changelogs/fragments/442-add-new-parameter-pvresize.yaml, plugins/modules/system/lvg.py, tests/integration/targets/lvg/tasks/main.yml, tests/integration/targets/lvg/tasks/test_pvresize.yml
Prior to this adjustment, if the underlying physical device was resized, the physical volume built on it would not be resized. 
An additional (optional) parameter was added with default to "no" .
In order to detect if the physical volume must be resized, a simple check verifies if the difference between the physical device size and the sum of the physical volume size and extent start size (reserved for metadata) is greater than one extent. If that is the case, the resize occurs
Fixes https://github.com/ansible/ansible/issues/29139
lvg
```paste below
```
=> LVG: add new parameter pvresize

changelogs/fragments/410-redis_cache-add_tls_support.yaml, plugins/cache/redis.py
- Add support for encryption in transit / TLS connections, via a `tls://` prefix added onto the connection uri.
- Update documentation.
Current connection string looks like this: `localhost:6379:0:changeme`.
With this change, above still works, but if you need TLS now you can do: `tls://localhost:6379:0:changeme`.
redis.py
The connection uri in this plugin is split on `:` and then each element is sent verbatim positionally to [the `Redis` library's constructor](https://redis-py.readthedocs.io/en/latest/#redis.Redis), which works great for the `host`, `port`, `db`, `password` params as they are the first four.
> classredis.Redis(host=u'localhost', port=6379, db=0, password=None, socket_timeout=None, socket_connect_timeout=None, socket_keepalive=None, …
=> redis cache - add support for TLS/encryption in transit

changelogs/fragments/428-mysql_db_add_unsafe_login_password_param.yml, plugins/modules/database/mysql/mysql_db.py, tests/integration/targets/mysql_db/tasks/state_dump_import.yml
mysql_db: add unsafe_login_password parameter
Fixes: https://github.com/ansible/ansible/issues/63955
One thing i'm worried about is that i can't reproduce `Access denied` described in https://github.com/ansible/ansible/issues/63955 neither in my local environment nor in ansible CI tests.
Would be cool if anybody confirms that the problem exists.
mysql_db
=> Mysql db unsafe passwd

changelogs/fragments/444-scaleway_fix_http_header_casing.yml, plugins/module_utils/scaleway.py
The common http api client class used by the scaleway modules only
enables automatic jsonification of the request body if the
"Content-Type" header is application/json. The client only included
"Content-type" in its default set of headers (notice the case
variation).
This caused a KeyError on send() if the caller relied on the default
content-type value.
plugins.module_utils.scaleway
Originally proposed in https://github.com/ansible/ansible/pull/68295
=> scaleway: Fix case mismatch causing key lookup failure

changelogs/fragments/394-terraform-add-config_file.yml, plugins/modules/cloud/misc/terraform.py
This PR adds support for multiple variables_file for "terraform" module, Fixes #224 issue. Moreover, this adds support for "backend_config_file" to provide at init state to the -backend-config parameter. This can accept a list of paths to multiple configuration files.
terraform module
It is possible to pass multiple var-files in terraform cli:
```
terraform apply -var-file="file-1.tfvars" -var-file="file-2.tfvars" -var-file="file-3.tfvars"
```
This is required when there are multiple var-files in different locations.
Also the "-backend-config" parameter, accepts both "key=value" type and "PATH" type. This parameter can also be passed multiple backend config files:
```
terraform init -backend-config=path/to/backend_config_file_1 …
```
=> terraform module: Added backend_config_file and multiple variables_file

changelogs/fragments/382-install_upgrade_specific_args.yaml, plugins/modules/packaging/os/zypper.py, tests/integration/targets/zypper/tasks/zypper.yml, tests/integration/targets/zypper/templates/duplicate.spec.j2
Add `extra_install_args` to zypper to allow for installation / upgrade specific arguments.
Example install / upgrade zypper arguments that faisl using the `extra_args`
* --allow-vendor-change
* --replacefiles and
* --force-resolution
Some zypper installation / upgrade options could not be used with the zypper module. Added a new `extra_install_args` argument to the module to handle install / upgrade specific zypper arguments.
Fixes issue #381
zypper
Please issue #381
```paste below
```
=> Added 'extra_install_args' module option to allow extra upgrade/install specific zypper arguments

.github/BOTMETA.yml
Entry in `BOTMETA.yml` for `modules/packaging/os/` should be in fact `modules/packaging/os/pkg5` as in https://github.com/ansible/ansible/blob/stable-2.9/.github/BOTMETA.yml#L411
This mistake have also side effect that for all modules in `modules/packaging/os/` without `maintainers` field, people from `team_solaris` were mentioned in issues and PRs.
Fixes #469
```paste below
```
=> Fix modules/packaging/os/pkg5 authors/maintainers in BOTMETA.yml

changelogs/fragments/468-mysql_db_add_restrict_config_file_param.yml, plugins/modules/database/mysql/mysql_db.py, tests/integration/targets/mysql_db/tasks/state_dump_import.yml
Fixes https://github.com/ansible/ansible/issues/34488
mysql_db: add restrict_config_file parameter
`plugins/modules/database/mysql/mysql_db.py`
=> mysql_db: add restrict_config_file parameter

changelogs/fragments/476-docker_swarm_service_add_init_option.yml, plugins/modules/cloud/docker/docker_swarm_service.py, tests/integration/targets/docker_swarm_service/tasks/tests/options.yml, tests/integration/targets/docker_swarm_service/vars/main.yml
Added support for init option, which corresponds to --init option in docker service create.
```
docker_swarm_service:
init: true
```
docker_swarm_service
=> Add 'init' option for docker_swarm_service.

README.md
Badges were pointing to the transitional repository
Fixing the URLs
```paste below
```
=> Fix README Badge urls

changelogs/fragments/450-slackpkg-package-matching.yml, plugins/modules/packaging/os/slackpkg.py
Change glob.glob() to os.listdir() and match name using regular expression.
It fixes case when we want to install package which name is part of other already installed package. For example if `openssl-solibs` is installed, it's not possible to install package `openssl` because module wrongly claim that desired package is already installed.
Fixes case described in #450
slackpkg
```paste below
```
=> slackpkg: fix name matching in package installation (#450)

changelogs/fragments/458-rshm_repository-reduce_execution_time_when_changed_is_false.yml, plugins/modules/packaging/os/rhsm_repository.py
This PR reduce of about 50% the execution time of this module when the module doesn't change the state of RHSM repositories.
Fixes #452 
This module execute the command subscription-manager two times:
1. Executing "subscription-manager repos --list" to identify enabled/disabled repositories before execute any change
2. Executing "subscription-manager repos <variable arguments>" to enable/disable repositories and change the state of enabled/disabled repositories
The execution of subscription-manager command in some condition is slow (it can take about 40 seconds)
Before this PR, this module call subscription-manager always two times also when there aren't changes.
After this PR, this module skip the second execution of subscription-manager when there …
=> rshm_repository: reduce execution time when changed == False

changelogs/fragments/444-scaleway-improve_removal_handling.yml, plugins/modules/cloud/scaleway/scaleway_compute.py
To remove a scaleway compute node, one needs to stop it first. This is
handled internally within the module by shutting down before removing.
Shutting down the node transitions it to a "stopping" state, which is
not the "stopped" state we expect. We thus need the transition to
complete so that we can put it in the actual target state (absent, i.e.
delete it).
The mechanism for waiting for such transitions today is controlled by
module parameters, with default to not being enabled at all, which
includes the transition from ([running] -(stopping)-> [stopped]).
Without this chage, in case of a running node, we would shut it down
(transition it to "stopping"), not wait for it complete the transition,
realize that it's not yet stopped and issue a second shut down command
to the api. This would …
=> scaleway_compute: When removing node, wait for transition

changelogs/fragments/461-resolve-domain-for-iscsi-portal.yml, plugins/modules/system/open_iscsi.py
iscsiadm support domain resolution (ex: iscsiadm -m discovery -t sendtargets -p iscsi.chiehmin.com).
However, open_iscsi module will try to match the portal with discovered results which will never
matched cause the discovered results use IP to represent node.
This patch do portal DNS resolution first to solve this situation.
Signed-off-by: Chieh-Min Wang <chiehminw@synology.com>
```paste below
```
=> Do domain resolution for portal

tests/unit/requirements.txt
None were missing. The only consistently skipped test is `modules/packaging/os/test_rhn_register.py`, which requires libxml/libxml2 (which is not available properly via PyPI).
Fixes #488.
unit tests
=> Update unit test requirements

changelogs/fragments/490-mysql_user_fix_cursor_errors.yml, plugins/modules/database/mysql/mysql_user.py
Fixes https://github.com/ansible/ansible/issues/29644
Fixes incorrect passing parameters to cursor.execute() method
```mysql_user```
=> mysql_user: fix cursor-related host_all arguments conversion string formatting error

plugins/callback/diy.py, tests/integration/targets/callback_diy/aliases, tests/integration/targets/callback_diy/handlers/main.yml, tests/integration/targets/callback_diy/inventory.yml, tests/integration/targets/callback_diy/tasks/main.yml
Customize the output via templating
Fixes: ansible/ansible#14367
Fixes: ansible/ansible#32584
DIY Callback Plugin
Originally submitted here ansible/ansible#65844
Tested on the following Python versions:
- 2.7.15rc1
- 3.5.8
- 3.6.7
Tested on the following Ansible versions:
- 2.10.0.dev0
- 2.9.2
- 2.8.5
Example use case: [ansible-playbook-execute](https://github.com/theque5t/ansible-playbook-execute)
Allows the user to fully customize the output using templates supplied via Ansible configuration, environment variables, and Ansible variables(extra vars, play vars, tasks vars etc.). I've copied the example from the plugin documentation down below.
__ansible.cfg__
```
[defaults]
stdout_callback=diy
[callback_diy]
playbook_on_start_msg="diy output(via ansible.cfg): playbook …
```
=> Added DIY callback plugin

changelogs/fragments/511-cloudflare_dns-verbose-failure.yml, plugins/modules/net_tools/cloudflare_dns.py
This is a very small change, so I open a PR without bug report.
I spent some time debugging an error, where the unexpected HTTP return code was reported to be -1:
> Failed API call /zones?name=example.com; got unexpected HTTP code -1
After searching the internet, I found multiple threads where this was reported (e.g. [this](https://community.cloudflare.com/t/failed-api-call-zones-name-domain-com-got-unexpected-http-code-1/48621)) and it was mostly attributed to a problem with the Cloudflare API, Access Permissions etc.
Digging deeper, I found the cause:
> An unknown error occurred: ~/.netrc access too permissive: access permissions must restrict access to only the owner
So this was just a fault of my local setup, totally unrelated to ansible and cloudflare.
This patch makes this message …
=> cloudflare_dns: Be more verbose on unexpected failure.

changelogs/fragments/505-slackpkg_fix_matching_some_special_cases_in_package_names.yml, plugins/modules/packaging/os/slackpkg.py
There are some special cases in Slackware package naming which are not covered by `$ARCH|noarch` condition:
- package `kernel-headers` has architecture set to `x86` on `x86_64`
- there are also some firmware packages with architecture set to `fw`
This PR adds check for `kernel-headers` special case and adds `fw` to other expected architectures.
slackpkg.py
For example, try to install package `kernel-headers`.
Module runs `slackpkg install kernel-headers` (installs it if package is not present), then check is run if package is installed, but it can't find it because architecture part of package name is different (`x86` instead of expected `x86_64`) and task fails.
Similar thing for firmware files, for example `zd1211-firmware-1.4-fw-1`. It fails because architecture …
=> slackpkg: fix matching some special cases in package names.

changelogs/fragments/29253-pear_add_prompts_parameter.yml, plugins/modules/packaging/language/pear.py
This is a copy of https://github.com/ansible-collections/community.general/pull/233
Add a new parameter to pear module allowing user to pass one or more regex and (optionnally) their answer for each package that will be installed.
Depending on what package we want to install, pear can ask for some information or just typing a character.
This hangs Ansible execution and the added parameter is used to detect these questions and answer them with a newline character by default or a user specified string.
* Bugfix Pull Request
pear
This fixes an issue created on repo 2 and half years ago :
Exemple playbook:
The example below have a prompt specified but no answer. Thus, the module will input newline caracter "\n" by default
```yaml
pear:
name: pecl/apcu
state: installed
prompts:
- (.*)Enable …
```
=> Pear - Add prompt parameter on pear module that allows to specify one or more prompts

changelogs/fragments/153-yarn_fix_checkmode-ec61975fc65df7f0.yaml, plugins/modules/packaging/language/yarn.py, tests/integration/targets/yarn/tasks/run.yml
Fixes #152 
`yarn` module
When running check mode on yarn module, it returns an empty string by default when it expects two values for err and out. For instance:
```py
out, err = yarn.install()
```
Currently the return is like:
```py
return ''
```
and should be at least:
```py
return(None, None)
```
From my point of view, this module needs to be have some checks for idempotency and dry-runs, but for now this will fix the issue. If you think it is interesting refactoring it, let me know and I can work on it.
After the change
```json
changed: [localhost] => {
"err": null,
"executable": null,
"global": true,
"ignore_scripts": false,
"name": "now",
"path": null,
"production": false,
"registry": null,
"state": "present", …
```
=> Return correct values when running yarn in check mode

changelogs/fragments/apt_rpm_typefix.yml, plugins/modules/packaging/os/apt_rpm.py
apt_rpm does not support install packages provided as list, only as comma delimited string. So package module does not work with apt_rpm
Fixes #143 
apt_rpm
```paste below
```
edits by Gundalow: Update summary and title
=> apt_rpm: support installing a list of packages (Fixes #143)

changelogs/fragments/241-fix-ipa-modules-when-ipa_host-empty.yml, plugins/module_utils/ipa.py
Fix the behavior of ipa modules in case IPA_HOST is empty
The expected behavior, when the env is empty, is to
fallback on DNS.
ipa
Without this fix, if IPA_HOST is empty,
there are different errors, depending on urllib version,
which additionally confuses the user. Example errors:
* `host_find: Request failed: <urlopen error no host given>`
* `Failed to connect to None at port 443: [Errno 111]
Connection refused", "status": -1, "url":
"https:///ipa/session/json`
```paste below
2020-04-26 16:27:13 | fatal: [undercloud]: FAILED! => changed=false 
2020-04-26 16:27:13 |   msg: 'host_find: Request failed: <urlopen error no host given>'
fatal: [localhost]: FAILED! => {"changed": false,
"msg": "Failed to connect to None at port 443: [Errno 111] Connection refused", …
```
=> Fix the behavior of ipa modules in case IPA_HOST is empty

changelogs/fragments/513-mysql_db_config_overrides_defaults.yml, plugins/module_utils/mysql.py, plugins/modules/database/mysql/mysql_db.py, tests/integration/targets/mysql_db/tasks/config_overrides_defaults.yml, tests/integration/targets/mysql_db/tasks/main.yml
fixes: https://github.com/ansible/ansible/issues/26919
mysql_db: add config_overrides_defaults parameter
mysql_db
=> mysql_db: add config_overrides_defaults parameter

changelogs/fragments/405-parted_align_undefined.yml, plugins/modules/system/parted.py
Added option align: undefined to support parted versions < 2.1
parted
I've actually tested parted 1.8.3 on some ancient system, but it failed. The reason was that -a option was added in parted 2.1.
Alternative solutions:
* omit -a option for 'optimal' (parted's default setting is 'optimal' too, works in my patched ansible 2.7)
* update required version of parted to 2.1 instead
=> parted option align: undefined to maintain parted 1.8.3 compatibility

changelogs/fragments/55658_hashi_vault.yml, plugins/lookup/hashi_vault.py, tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml, tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml
Fixes: ansible/ansible#55658
changelogs/fragments/55658_hashi_vault.yml
plugins/lookup/hashi_vault.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml
=> hashi_vault: Handle equal sign in secret name value

changelogs/fragments/firewalld_zone_target.yml, plugins/modules/system/firewalld.py, tests/integration/targets/firewalld/tasks/run_all_tests.yml, tests/integration/targets/firewalld/tasks/zone_target_test_cases.yml
Add Zone target setting
Fixes https://github.com/ansible/ansible/issues/49232
Signed-off-by: Adam Miller <admiller@redhat.com>
firewalld
=> firewalld: add zone target set

changelogs/fragments/aix_filesystem-module_util-routing-issue.yml, galaxy.yml, plugins/modules/system/aix_filesystem.py
changelogs/fragments/aix_filesystem-module_util-routing-issue.yml
plugins/modules/system/aix_filesystem.py
=> aix_filesystem - fix module_util pathing issue for ansible 2.9

changelogs/fragments/parted_negative_numbers.yml, plugins/modules/system/parted.py, tests/unit/plugins/modules/system/test_parted.py
Allow passing negative numbers to specify partition boundary relative to disk end
Fixes: https://github.com/ansible/ansible/issues/43369
parted
=> parted: Allow passing negative numbers to specify partition boundary relative to disk end

changelogs/fragments/303-consul_kv-fix-env-variables-handling.yaml, plugins/lookup/consul_kv.py
ANSIBLE_CONSUL_URL variable is ignored if ANSIBLE_CLIENT_CERT or ANSIBLE_VALIDATE_CERTS are undefined.
Fixes ansible/ansible#51960
lookup/consul_kv
- ``_raw`` is not required anymore since this option was never used in plugin
- Options handling was switched to ``get_option`` approach
- ``url`` option for scheme/host/port override is now available not only as env variable, but as argument/ini setting as well
=> Fix for lookup/consul_kv environment varibles handling

changelogs/fragments/548_apk.yml, plugins/modules/packaging/os/apk.py
Add `--no-cache` option to apk module.
apk
=> apk: Add no-cache option

changelogs/fragments/33979-xfs_growfs.yml, plugins/modules/system/filesystem.py
reopening of https://github.com/ansible/ansible/pull/55646
xfs needs to be mounted to be expanted.
Add function to get mountpoint of filesystem.
* Fail if xfs filesystem is not mounted
xfs growfs needs to be executed on a mountpoint. That will be enforced
now by xfsprogs-4.12.
https://bugzilla.redhat.com/show_bug.cgi?id=1477192
Fixes https://github.com/ansible/ansible/issues/33979
filesystem.py
before:
```
server1| FAILED! => {
"cmd": "/usr/sbin/xfs_growfs -n /dev/vg00/work.tmp",
"msg": "xfs_growfs: /dev/vg00/work.tmp is not a mounted XFS filesystem",
"rc": 1,
"stderr": "xfs_growfs: /dev/vg00/work.tmp is not a mounted XFS filesystem\n",
"stderr_lines": [
"xfs_growfs: /dev/vg00/work.tmp is not a mounted XFS filesystem"
],
"stdout": "", …
```
=> filesystem.py: fix xfs growfs

changelogs/fragments/560-pkgng-add-stdout-and-stderr.yaml, plugins/modules/packaging/os/pkgng.py
To ease debugging if something goes wrong during pkg run.
Expose the stdout and stderr of pkg through the result object of the pkgng module. Currently, if something goes wrong during the pkg run, the user has no way to see what happened, which makes recovering from that situation more difficult.
pkgng
=> pkgng: Add stdout and stderr to response object

plugins/connection/oc.py
This import is broken, and this fixes it.
plugins/connection/oc.py
The connection plugin being imported here was moved out of this collection, so this is like a dead link, but a dead import.
```
$ PYTHONPATH=target/:$PYTHONPATH python -c 'import ansible_collections.community.general.plugins.inventory.scaleway'
File "<frozen importlib._bootstrap>", line 900, in _find_spec
AttributeError: '_AnsibleCollectionFinder' object has no attribute 'find_spec'
During handling of the above exception, another exception occurred:
File "<string>", line 1, in <module>
File "/Users/alancoding/Documents/repos/collection-dependencies-demo/target/ansible_collections/community/general/plugins/inventory/scaleway.py", …
```
=> Point to correct location in kubernetes plugin import

changelogs/fragments/547-start-service-condition.yaml, plugins/modules/cloud/docker/docker_compose.py
Fixes #532. This PR adds a condition to prevent service startup if parameter `stopped: yes` is set.
docker_compose
=> docker_compose: dont start the service if parameter stopped is true

changelogs/fragments/airbrake_deployment_add_version.yml, plugins/modules/monitoring/airbrake_deployment.py
The aibrake v4 API allows for distinct `version` and `revision` params.
The `revision` param is meant to indicate a revision from the version
control system (such as a Git hash), whereas the `version` param is
meant to be a version number (such as 1.2.3). This is especially
noticeable in the Airbrake UI where revisions are truncated to 7
characters, and used to build GitHub style diff links (such as
`https://github.com/ansible-collections/community.general/compare/689a25edcf03a3b8513faf347a957d2ad443c124...e54dd3a01f2c421b558ef33b5f79db936e2dcf15`).
airbrake_deployment
none
```paste below
```
=> airbrake_deployment: Add version param

plugins/modules/monitoring/airbrake_deployment.py
As suggested in #583 ([here](https://github.com/ansible-collections/community.general/pull/583#discussion_r445994800))
airbrake_deployment
```paste below
```
=> airbrake_deployment: Add types to the argument_spec

changelogs/fragments/55903_kubevirt.yml, plugins/inventory/kubevirt.py
Fixes: ansible/ansible#55641
changelogs/fragments/55903_kubevirt.yml
plugins/inventory/kubevirt.py
=> kubevirt: Add aliases 'interface_name' for 'network_name'

changelogs/fragments/596-splunk-add-option-to-not-validate-cert.yaml, plugins/callback/splunk.py
Add an boolean option validate_certs to not validate the certificate of
the HTTP Event Collector.
callback splunk
=> [splunk] Add an option to not fail when the certificate is not valid

changelogs/fragments/564-docker_container_use_config_macaddress_by_default.yaml, plugins/modules/cloud/docker/docker_container.py
mac_address in `NetworkSettings`  is empty when using `macvlan` network only
`docker_container`
```
$ ansible --version
ansible 2.9.10
configured module search path = [u'/Users/k-petrov/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /Users/k-petrov/Library/Python/2.7/lib/python/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```
```
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/Users/k-petrov/work/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/Users/k-petrov/work/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/k-petrov/work/ansible/ansible.cfg) = …
```
=> use Config MacAddress by default instead of Networks

changelogs/fragments/562-nmcli-fix-idempotency.yaml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
`nmcli` module does not know the previous state of an interface and always returns a status of "changed" even when nothing does. This PR implemented an idempotent check to modify connections only if changes are detected. The command line arguments and property aliases are slightly different between a variety of connection types.
- Implement show_connection() to retrieve connection profile from command line
- Parse integer enumeration values in show_connection()
- Convert 'bond.options' to alias shortcuts
- Modify connection only if changes are detected
- Support generic alias in during the property comparison
Fixes #481
tests/unit/plugins/modules/net_tools/test_nmcli.py
An example of playbook snippet to reproduce this issue:
```yaml …
```
=> nmcli: add idempotent support for any kinds of connections

README.md, changelogs/fragments/296-ansible-2.9.yml, shippable.yml, tests/sanity/ignore-2.9.txt, tests/utils/shippable/shippable.sh
=> Run tests with Ansible 2.9 as well

plugins/modules/cloud/docker/docker_swarm_info.py, plugins/modules/cloud/docker/docker_swarm_service.py
This PR combines two PRs from the original ansible repository: https://github.com/ansible/ansible/pull/67991 (opened by @aniejek) and https://github.com/ansible/ansible/pull/68335 (opened by @teadur). Picking up these small fixes due to inactivity in original PRs.
docker_swarm_info
docker_swarm_service
In docker_swarm_info the option fixing typo in example
In docker_swarm_service the `mount` property doesn't have property mode, but `type`
=> Fix documentation mistakes for docker_swarm_info and docker_swarm_service

changelogs/fragments/615-digital-ocean-tag-info-bugfix.yml, plugins/modules/cloud/digital_ocean/digital_ocean_tag_info.py
This fixes a bug in the digital_ocean_tag_info module. Previously, it crashed with a `KeyError` if you tried to retrieve a single tag. After this change, it works correctly.
digital_ocean_tag_info module
=> Fix bug in digital_ocean_tag_info module

changelogs/fragments/618-mysql_user_add_missed_privileges.yml, plugins/modules/database/mysql/mysql_user.py
Fixes https://github.com/ansible-collections/community.general/issues/617
mysql_user: add missed privileges
mysql_user
=> mysql_user: add missed privileges

changelogs/fragments/609-mysql_user_fix_overriding_password_to_the_same.yml, plugins/modules/database/mysql/mysql_user.py, tests/integration/targets/mysql_user/tasks/user_password_update_test.yml
Fixes https://github.com/ansible-collections/community.general/issues/543
mysql_user: fix overriding user passowrd to the same
`user_mod` function checks a server version and compare two hashed passwords (current and new)
but `user_add` stores a new password in a different form (but they are actually the same),
so `user_mod` wrong considers that the passwords are different.
The fix makes `user_add` to store a password in the proper encrypted form at once.
For details see `user_mod` function.
mysql_user
=> mysql_user: fix overriding user passowrd to the same

changelogs/fragments/63767_selective.yml, plugins/callback/selective.py
Added additional condition to detect failed task in
selective callback plugin when ran with loop or with_items.
Fixes: ansible/ansible#63767
changelogs/fragments/63767_selective.yml
=> selective: mark task failed correctly

plugins/lookup/tss.py, tests/unit/plugins/lookup/test_tss.py
Add a lookup plug-in capable of retrieving Secrets from Thycotic's Secret Server. The plug-in uses python-tss-sdk which is available here: https://pypi.org/project/python-tss-sdk/
tss
The cyclomatic complexity of this plug-in is 5 and the SDK on which it's based is 3. As such, I've opted not to include a pytest. If future versions have increased complexity, I will add tests at that point.
=> Add the Thycotic Secret Server lookup plugin.

plugins/lookup/dsv.py, tests/unit/plugins/lookup/test_dsv.py
Add a lookup plug-in capable of retrieving Secrets from Thycotic's DevOps Secrets Vault. The plug-in uses python-dsv-sdk which is available here: https://pypi.org/project/python-dsv-sdk/
dsv
- This is a re-submission of a closed PR with the changes suggested in that PR.
- The cyclomatic complexity of this plug-in is 5 and the SDK on which it's based is 3.  As such, I've opted not to include a pytest.  If future versions have increased complexity, I will add tests at that point.
=> Add Thycotic DevOps Secrets Vault lookup plugin

changelogs/fragments/651-fix-postgresql_set-warning.yaml, plugins/modules/database/postgresql/postgresql_set.py
Motivation: my logs are flooded with "warnings" when I run roles against instances. So even though I understand the need for this "warning", it's a false positive when nothing needs to be done.
I would also argue an "INFO" is more suited? Thoughts? I can add that to `AnsibleMolecule` if wanted.
postgresql_set
=> Update: only "warn" when restart is required

changelogs/fragments/611-gitlab-runners-env-vars-intput-and-default-item-limit.yaml, plugins/inventory/gitlab_runners.py
Ability to pick options values from env vars on gitlab_runners inventory plugin
Remove default 20 items limit to runners list on gitlab_runners inventory plugin
Remove default 20 items limit to runners list by adding "all" bool to True in gl.runners.all ref
Permit env var input for server_url and api_token options values
plugins/inventory/gitlab_runners.py
```paste below
```
=> gitlab_runners inventory plugin: runtime en var and list default behavior

changelogs/fragments/add_argument_check_for_rundeck.yaml, plugins/modules/web_infrastructure/rundeck_acl_policy.py
This change simply introduce a sanity check over the name of the policy. 
Using this module and using a name that is not compatible with rundeck prerogatives lead to a cryptic error 
`"Unhandled HTTP status -1, please report the bug"`
This pull request will check if the name passed to the module passes rundeck name policy. If not, it will output a more understandable error.
rundeck_acl_policy
Simply execute this task on any rundeck of your choice. 
```
- name: "Create or update a rundeck ACL policy for users to be able to read"
rundeck_acl_policy:
name: "Name with forbidden characters ( here , spaces for exemple )"
api_version: 21
url: "https://my.rundeck"
token: "{{ rundeck_api_token }}"
state: present
project: "allow_users_for_project_{{ item.name }}"
policy: …
```
=> Add check for rundeck_acl_policy name

changelogs/fragments/650_pacman_support_zst_package_files.yaml, plugins/modules/packaging/os/pacman.py
Archlinux switched default package compression to Zstandard [recently](https://www.archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/). That means that new packages files have a .zst extension.
This PR add .zst extension to the heuristic determining whether a `name` is a file or an Archlinux package name.
Side note : Wouldn't it better to allow any extension after `.pkg.tar` instead of listing them ?
pacman
Playbook triggering the problem :
```paste below
- pacman:
name: /tmp/example.pkg.tar.zst
```
=> pacman: Treat .zst package names as files

tests/integration/targets/pids/tasks/main.yml
Currently the `pids` tests fail because the latest psutil package breaks with older pip versions. 
pids
=> Prevent CI failure with older pip versions

changelogs/fragments/474-yarn_fix-outdated-fix-list.yml, plugins/modules/packaging/language/yarn.py, tests/integration/targets/yarn/templates/package.j2
This PR fixes two issues with the yarn module:
1. `Index out of range` with `state: 'latest'` and no outdated packages
2. `Too many values to unpack` with scoped packages installed
yarn
Example:
```yaml
- yarn:
path: '/var/www/test.domain.tld/some_app'
name: 'imagemin'
state: 'latest'
```
```bash
File "/var/tmp/ansible-tmp-1591514673.7097096-9690-36426478672085/AnsiballZ_yarn.py", line 102, in <module>
File "/var/tmp/ansible-tmp-1591514673.7097096-9690-36426478672085/AnsiballZ_yarn.py", line 94, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File "/var/tmp/ansible-tmp-1591514673.7097096-9690-36426478672085/AnsiballZ_yarn.py", line 40, in invoke_module …
```
=> yarn: Fix handling of empty outdated & scoped packages

changelogs/fragments/687-fix-redfish-payload-decode-python35.yml, plugins/module_utils/redfish_utils.py
Added to_native() wrapper around the read of the Redfish response payload to ensure proper decoding of the bytes on all supported Python versions (2.7, 3.5, 3.6, 3.7, 3.8).
Fixes #686 
Also, see the original issue in https://github.com/ansible/ansible/issues/65889
redfish_info
redfish_config
redfish_utils
The original code (`json.loads(resp.read())`) is failing on Python 3.5 because `json.loads()` expects a `str` and the `HTTPResponse.read()` returns `bytes`.
In Python 3.6 and later,  `json.loads()` will also take `bytes`, so it worked there. And in Python 2.7 the `HTTPResponse.read()` returns `str`, so it worked there as well.
**Before** the fix, running a play with the Python 3.5 interpreter:
```paste below
$ ansible-playbook -i myinventory.yml …
```
=> Fix decoding of response payloads for python 3.5

changelogs/fragments/693-big-revamp-on-xfconf-adding-array-values.yml, plugins/modules/system/xfconf.py
Adds arrays support for xfconf module. There is another PR already open adding that feature (https://github.com/ansible/ansible/pull/50108). However, in that PR, the maintainer of the xfconf module asked if anyone is interested in taking over the module (https://github.com/ansible/ansible/pull/50108#issuecomment-471218315).
So, I have contacted him and I am creating this PR after his instructions.
This PR is virtually the same as the pending PR https://github.com/ansible/ansible/pull/62578 at the main ansible repository. There was also a previous PR, already in the community.general repo: https://github.com/ansible-collections/community.general/pull/482 => this one was closed to have a clean separate branch here, rather than having to rebase all the changes coming from upstream.
Fixes …
=> big revamp on xfconf, adding array values

changelogs/fragments/677-jenkins_plugins_sha1.yaml, plugins/modules/web_infrastructure/jenkins_plugin.py
Fixes ansible/ansible issue number 34304 (https://github.com/ansible/ansible/issues/34304)
Re-do of ansible/ansible PR number  50234 (https://github.com/ansible/ansible/pull/50234)
All content in this description and code changes originally by @jesstruck
The hashlib.md5(...) function is disabled on systems running in FIPS 140-2 mode. To accommodate that, this commit just switches to a hash function (hashlib.sha1(...)) that is allowed by FIPS 140-2.
jenkins_plugin
From @jesstruck:
```This is a second try of getting 34349 accepted and merged in, I have simply reimplemented @karlmdavis solution in the previous mentioned pull request, together with the suggested changes he got.```
=> Shameless recommit of changes in jesstruck/ansible:jenkins_plugins_sha1

changelogs/fragments/311-jira-error-handling.yaml, plugins/modules/web_infrastructure/jira.py
Jira's API can return a empty "errorMessages" list, and the real error is in the "errors" object. This happens, for example, if a user tries to file a ticket in a project that does not exist (tested with Jira v7.13.8)
Check both "errorMessages" and "errors", and report both values with `fail_json()`.
jira
=> jira: log error messages in "errors" key

changelogs/fragments/xfconf_add_uint_type.yml, plugins/modules/system/xfconf.py
This MR adds support for the `uint` type in the xfconf module.
When set from the UI (ie. xfce4-settings-manager), some XFCE settings are of type `Unsigned Int`.
In xfce4-settings-editor, though they appear as `Integer` in the type column of the _table_ view; their actual type is revealed to be `Unsigned Int` in the type _drop-down list_, shown when editing the property.
For most properties, creating an `int` property from Ansible is properly handled by XFCE, but not for all.
When the following properties are created as `int`, their value does not show properly in xfce4-settings-manager and may not be taken into account by the system
- /xfce4-power-manager/inactivity-on-battery
- /xfce4-power-manager/inactivity-on-ac
- (not exhaustive)
xfconf
Was initially submitted …
=> Added uint type to xfconf module

plugins/modules/files/archive.py
Describe more precisely how exclude_path works: it used only to limit results of `path` glob expansion.
Fixes: #593 
archive
=> archive: exclude_path documentation

changelogs/fragments/704-doas-set-correct-default-values.yml, plugins/become/doas.py
The module expects `become_user` and `become_flags` to by empty
string by default.
See: https://github.com/ansible-collections/community.general/pull/701
doas
=> doas: properly set the default values

changelogs/fragments/porting-guide-2.yml
This adds entries from the Ansible-base porting guide that do not belong there (because they belong to this collection). This data has already been moved to the ansible changelog (https://github.com/ansible-community/ansible-build-data/blob/main/2.10/changelog.yaml), but it would be better if it appears in the changelog of the collection it applies to.
(Looks like I forgot this one earlier...)
changelog
=> Add porting guide entries from Ansible-base porting guide

changelogs/fragments/702-slack-support-for-blocks.yaml, plugins/modules/notification/slack.py, tests/unit/plugins/modules/notification/test_slack.py
Adds basic support for building Slack messages with blocks. I say basic, but the affordances here are the same as for attachments, in that whatever structure of blocks a user wants to send (mirroring [Slack’s documentation](https://api.slack.com/block-kit) for building Block Kit messages) should be defined directly in the YAML, and no altering or modification of that structure is done before the message is sent.
Fixes #380.
Example:
```
- name: Use the blocks API
community.general.slack:
token: thetoken/generatedby/slack
blocks:
- type: section
text:
type: mrkdwn
text: |-
*System load*
Display my system load on host A and B
- type: context
elements:
- type: mrkdwn
text: |-
*System A*
load average: 0,74, 0,66, 0,63
- type: mrkdwn
text: |-
*System B*
load average: 5,16, 4,64, 2,43
```
- …
=> slack: support for blocks

changelogs/fragments/707-jira-error-handling.yaml, plugins/modules/web_infrastructure/jira.py
This is a follow-on fix for a corner case I uncovered while testing https://github.com/ansible-collections/community.general/pull/311
jira
Sometimes Jira returns dicts as "`errors`" instead of simple strings. For example, when a user specifies a field that cannot be set, Jira returns a dict with the field name as a key and the error message as the value.
In the rare case that we have both a "`errorMessages`" list and an "`errors`" dict, when we combine those values later with `join()`, Python raises a `TypeError`.
Transform each individual error message into a string, and then `join()` the list of strings.
=> jira: cast individual error messages to strings

changelogs/fragments/689-haproxy_agent_and_health.yml, plugins/modules/net_tools/haproxy.py
Health and agent checks can cause a disabled service to re-enable
itself.  This adds "health" and "agent" options that will also
enable or disable those checks, matching if the service is to be
enabled/disabled.
The haproxy module sends the "disable server" command, but if health and agent checks are enabled, the server immediately re-enables itself due to these checks passing.
I have a fix on https://github.com/linsomniac/ansible-modules-extras/tree/haproxy-agent-health which adds "health" and "agent" options and will send "disable health" and "disable agent" commands in addition to "disable server". The same is done for the "enable".
I was unable to figure out how to submit a PR of this change in this repo, because ansible-modules-extra is a locked repo and instructions on how to submit …
=> haproxy: Enable/disable health and agent checks

plugins/modules/net_tools/nmcli.py
Fixes package names for CentOS and Fedora.
Replaces #668.
Thanks to @fbruetting for reporting this and preparing a fix.
nmcli
=> nmcli: fix package name

changelogs/fragments/711-lxd-target.yml, plugins/modules/cloud/lxd/lxd_container.py
When creating new container in LXD cluster deployment, LXD algorithm will decide on which node new container must be created. [POST (optional ?target=<member>)](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#post-optional-targetmember) can create container on a specific node in the cluster.
Some LXD cluster operators may prefer this approach of distributing containers in cluster, rather than letting LXD decide that. 
For example, one particular container will require a lot of resources, and not all cluster members can provide or share them.
lxd_container
You can control LXD via HTTPS API. Most of container configuration is passed via json payload, however this particular - target - is passed in URL. `target` is optional parameter.
URL would look like …
=> module lxd_container - added target parameter for cluster deployments

plugins/modules/cloud/docker/docker_stack_task_info.py, plugins/modules/docker_stack_task_info.py, plugins/modules/docker_stack_tasks_info.py, tests/integration/targets/docker_stack_task_info/aliases, tests/integration/targets/docker_stack_task_info/files/stack_compose_base.yml, tests/integration/targets/docker_stack_task_info/files/stack_compose_overrides.yml, tests/integration/targets/docker_stack_task_info/meta/main.yml, tests/integration/targets/docker_stack_task_info/tasks/main.yml, tests/integration/targets/docker_stack_task_info/tasks/test_stack_task_info.yml, tests/integration/targets/docker_stack_task_info/vars/main.yml
Implement docker_stack_task_info functionality
Fixes #729
`docker_stack_task_info.py`
Shows Docker stack tasks from a given stack name
```yaml
---
- name: Docker stack list
tasks:
- name: List stack
docker_stack_info:
register: output
- name: show stack
debug:
msg: "{{ output.results }}"
- name: Get stack tasks from first element
docker_stack_task_info:
name: "{{ output.results[0].Name }}"
register: output
- name: Show stack tasks
debug:
msg: "{{ output.results }}"
```
Output
```json
"msg": [
{
"current state": "Running 24 hours ago",
"desired state": "Running",
"error": "",
"id": "eda0cda3-1bc",
"image": "grafana/grafana",
"name": "grafana_grafana-0",
"node": "docker-desktop",
"ports": …
```
=> New Docker Stack Task Info Module with Tests

tests/integration/targets/setup_docker/tasks/RedHat-7.yml
The AMI repositories recently changed and removed the `rhui-` prefix. That was fixed in `ansible-base` with https://github.com/ansible/ansible/pull/71130, but a similar fix is needed here.
`tests/integration/targets/setup_docker`
=> Remove "rhui-" prefix from RHEL repository

tests/integration/targets/setup_docker/defaults/main.yml, tests/integration/targets/setup_docker/handlers/main.yml, tests/integration/targets/setup_docker/tasks/main.yml
The docker pypi package bumped its default API version to 1.39. Since some of the CI nodes have an older docker daemon version, this will break the docker tests. One way to fix this is to restrict docker pypi to < 4.3.0 (see https://github.com/ansible/ansible#71193). Since we want to be able to use the new docker pypi package, we make sure to install < 4.3.0 only when the API version of the docker daemon is < 1.39.
CI
=> Try to fix docker tests

tests/integration/targets/docker_stack_task_info/tasks/test_stack_task_info.yml
The tests sometimes result in errors because the stack hasn't been started yet: https://app.shippable.com/github/ansible-collections/community.general/runs/3249/35/console
docker_stack_task_info
=> Fix docker_stack_task_info tests

changelogs/fragments/744-xfconf_make_locale-independent.yml, plugins/modules/system/xfconf.py
- ensure correct behaviour, even in desktop environments which don't use English as the default language. This is done by providing LANG=C environment variable to the xfconf-query executable.
- add double as content type
Make xfconf locale-independent
In addition to the locale change, also added support for the double type in the process.
=> Update xfconf.py: make locale-independent

tests/integration/targets/shutdown/tasks/main.yml
MacOS integration test is not correct.
shutdown
https://app.shippable.com/github/ansible-collections/community.general/runs/3265/34/console
```
07:01 TASK [Verify shutdown delay is present in minutes in Void, MacOSX, OpenBSD] ****
07:01 skipping: [testhost] => {"changed": false, "skip_reason": "Conditional result was False"}
```
=> Fix MacOS shutdown integration test

changelogs/fragments/776-postgresql_set_allow_empty_string.yaml, plugins/modules/database/postgresql/postgresql_set.py, tests/integration/targets/postgresql_set/tasks/main.yml, tests/integration/targets/postgresql_set/tasks/postgresql_set_initial.yml
postgresql_set: allow to pass an empty string as a value
Fixes https://github.com/ansible-collections/community.general/issues/775
(there are unrelated CI problems with restarting unsupported 9.4 on ubuntu 16 and freebsd 11, so i increased the min postgres version to 9.6)
postgresql_set
=> postgresql_set: allow to pass an empty string as a value

changelogs/fragments/776-postgresql_set_allow_empty_string.yaml, plugins/modules/database/postgresql/postgresql_set.py, tests/integration/targets/postgresql_set/tasks/main.yml, tests/integration/targets/postgresql_set/tasks/postgresql_set_initial.yml
(cherry picked from commit 05556dc67161c28eee72e25bf4690641ff4fa37a)
Backport of postgresql_set: allow to pass an empty string as a value (#776)
postgresql_set.py
=> [stable-1] postgresql_set: allow to pass an empty string as a value (#776)

plugins/modules/system/sysupgrade.py, plugins/modules/sysupgrade.py, tests/unit/plugins/modules/system/test_sysupgrade.py
This module will let users use OpenBSD's sysupgrade functionality with Ansible. This command is similar to syspatch, which is already in this repo, but handles upgrades between releases and snapshots.
sysupgrade
This module doesn't currently allow for `check_mode`, as the script within OpenBSD doesn't currently allow support for checking if a version is available. This will likely be resolved in a future release.
```paste below
- name: Upgrade to latest release
sysupgrade:
become: true
register: sysupgrade
- name: Upgrade to latest snapshot
sysupgrade:
snapshot: true
register: sysupgrade
- name: Have Ansible reboot if required
reboot:
when: sysupgrade.changed
- name: Have sysupgrade automatically reboot
sysupgrade:
fetch_only: false
become: true
register: …
```
=> Module: Adding OpenBSD sysupgrade support

.github/BOTMETA.yml
Disable notifications for jose-delarosa from team_redfish. Jose moved to a new company and new role last year and is no longer involved with the Redfish module maintenance. I had previously removed him from the team_redfish list, but he was still getting notifications via the `authors` keyword. In this PR I disabled notifications for him via the `ignore` keyword.
I also added myself to the authors list since I have been adding new features for a while. 
- Other
=> Disable notifications for jose-delarosa

tests/integration/targets/hg/aliases
=> Disable hg tests: these use bitbucket.org, which dropped mercurial support on 2020-08-26

tests/integration/targets/lookup_lmdb_kv/dependencies.yml
Since 1.0.0 (released 2020-08-28), lmdb includes a patch for the library (https://lmdb.readthedocs.io/en/release/#installation-unix). Unfortunately in CI, installing lmdb now fails, probably because of this. This PR tries to get it working.
plugins/lookup/lmdb_kv.py
=> Fix lmdb lookup tests

changelogs/fragments/homebrew-cask-at-symbol-fix.yaml, plugins/modules/packaging/os/homebrew_cask.py
Allow Homebrew casks with `@` in the name to be installed/removed correctly.  Fixes #733 .
homebrew_cask
Fixes a valid cask with `@` in the name incorrectly being reported as invalid:
```
"msg": "Invalid cask: unity@2019.3.9f1."
```
=> Fix for error trying to install cask with '@' in the name

changelogs/fragments/783-fix-gem-installed-versions.yaml, plugins/modules/packaging/language/gem.py
Fix get_installed_versions: correctly parse "default" version.
gem query output of
bundler (default: 2.1.4, 1.17.2)
Gets parsed as:
['default:', '1.17.2']
Fix this by skipping "default: " if present in the list of versions - by adding
it as an optional part of the regex, grouped as a non-capturing group to keep
the index of existing group.
This now correctly parses the above input as
['2.1.4:', '1.17.2']
Fixes #782 - makes gem correctly recognize already installed modules and avoids installing them again.
gem
Details in #782 - and this is a refreshed version of https://github.com/ansible/ansible/pull/57331
Issue can be reproduced e.g. with Ruby 2.7.1 installed into /usr/local/rbenv/versions/2.7.1 - comes with bundler 2.1.4 installed into …
=> gem: Fix get_installed_versions: correctly parse "default" version.

changelogs/fragments/802-pushover-device-parameter.yml, plugins/modules/notification/pushover.py
When bringing Linux systems up-to-date and rebooting those machines, I'd like to have a notification sent to only one device via Pushover just when the reboot is issued. For this reason, I've enhanced the Pushover module.
With this change, you can specify to which device the notification should be delivered.
pushover
New parameter: device
Example:
```
- community.general.pushover:
msg: '{{ inventory_hostname }} has been lost somewhere'
app_token: wxfdksl
user_key: baa5fe97f2c5ab3ca8f0bb59
device: admins-iPhone
```
Using the Pushover API, you can specify a device where the message should be delivered to. Instead of notifying all devices (the default), the message is sent only to the specified device. Multiple devices can be given separated by a …
=> Specify device for Pushover notification

changelogs/fragments/811-proxmox-kvm-state-absent.yml, plugins/modules/cloud/misc/proxmox_kvm.py
When the `vmid` parameter is not supplied and the module can only rely on name look-up an early failure can happen if the targeted VM doesn't exist.
In this case a task execution with the parameter `state` set to `absent` will actually fail instead of being considered ok.
This patch introduces a deferred error-checking for non-existent VMs by assigning the value -1 to the `vmid` parameter, allowing the actual verification to be performed in the right code paths.
Is also help to differentiate between a non-existent `vmid` or non-existent VM `name`.
proxmox_kvm
Previously:
TASK [ansible-role-proxmox-instance : Remove instance-test]
changed: [localhost]
...
TASK [ansible-role-proxmox-instance : Remove instance-test]
fatal: [localhost]: FAILED! => changed=false
msg: VM …
=> proxmox_kvm: fix idempotency issue with state=absent

changelogs/fragments/849-proxmox-kvm-state-absent-force.yml, plugins/modules/cloud/misc/proxmox_kvm.py
Recognize `force=yes` in conjunction with `state=absent` to forcibly remove a running VM instead of issuing a warning.
Requires #811.
proxmox_kvm
Using these tasks:
```
- name: "Ensure test-instance is forcibly removed"
proxmox_kvm:
api_host: "{{ host }}"
api_user: "{{ user }}@{{ method }}"
api_password: "{{ password }}"
name: test-instance
state: absent
force: yes
register: test
- debug:
msg: "{{ test }}"
```
Before:
```
TASK [ansible-role-proxmox-instance : Ensure test-instance is removed] ***
ok: [localhost]
TASK [ansible-role-proxmox-instance : debug] ***********************************
ok: [localhost] => 
msg:
changed: false
failed: false
msg: VM 42 is running. Stop it before deletion.
```
After:
```
TASK [ansible-role-proxmox-instance : Ensure test-instance is …
```
=> proxmox_kvm: recognize force=yes with state=absent

changelogs/fragments/892-slack-token-validation.yml, plugins/modules/notification/slack.py
Changes to support validation for longer token types than what was there
community.general.slack
Moved from `\w+-\w+` to `\S+` to capture until there is a space
*Before*
```paste below
fatal: [host]: FAILED! => changed=false 
msg: Slack has updated its webhook API.  You need to specify a token of the form XXXX/YYYY/ZZZZ in your playbook
```
*After*
```
changed: [host]
```
Fixes #862
=> Slack: moves to \S+ check instead of \w+-\w+

changelogs/fragments/831-proxmox-kvm-wait.yml, plugins/modules/cloud/misc/proxmox_kvm.py
Allows some factorization of redundant code in stop_vm(), start_vm(), create_vm() and main().
This new function also waits one extra second after a successful task execution as the API can be a bit ahead of Proxmox in my experience, resulting in consecutive tasks failing wrongly (example bellow).
proxmox_kvm
Before:
TASK [ansible-role-proxmox-instance : Ensure test-instance is created]
changed: [localhost]
TASK [ansible-role-proxmox-instance : Ensure test-instance is updated]
fatal: [localhost]: FAILED! => changed=false
msg: VM test-instance does not exist in cluster.
After:
TASK [ansible-role-proxmox-instance : Ensure test-instance is created]
changed: [localhost]
TASK [ansible-role-proxmox-instance : Ensure test-instance is updated]
changed: [localhost]
=> proxmox_kvm: new function wait_for_task()

changelogs/fragments/858-postgresql_privs_should_allow_public_role_lowercased.yml, plugins/modules/database/postgresql/postgresql_privs.py, tests/integration/targets/postgresql_privs/tasks/postgresql_privs_initial.yml
Fixes https://github.com/ansible-collections/community.general/issues/857
1. Allow passing PUBLIC role written in lowercase letters.
2. Also, in case of PUBLIC, the module reports that nothing has been changed, fixed to `always changed`.
postgresql_privs
=> postgresql_privs: allow lowercased PUBLIC role

changelogs/fragments/825-bootsource-override-option.yaml, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/redfish/redfish_command.py
Fixes #824  
Updates redfish_command and redfish_utils to allow setting BootSourceOverrideEnabled to all allowable schema values.
=> redfish_command: allow setting the BootSourceOverrideEnabled property

changelogs/fragments/777-interfaces_file-re-escape.yml, plugins/modules/system/interfaces_file.py
(cherry-picked from commit b87eb7e91120a6758f751eeab6b7acace73c5a50)
Backport of interfaces_file: re.escape() old value (#873)
interfaces_file
```paste below
```
=> [stable-1] interfaces_file: re.escape() old value

plugins/modules/database/postgresql/postgresql_user.py
Recently reexamined doc recommendations / requirements. According to them:
- use active voice where suits
- use the present tense, no future
- use proper identifiers, e.g. I(), C(), etc.
- supports check mode to `note:` section
- parameter -> option
- misc fixes
postgresql_user
=> postgresql_user: improve documentation

changelogs/fragments/887-rollback-if-nothing-changed.yml, plugins/modules/database/postgresql/postgresql_privs.py
Since the module unconditionally issues ALTER statements in order to
observe their effect on the postgres catalog - to determine whether the
privileges have changes - a rollback is thus advisable when in fact
nothing has changed.
fix #885
Fixes #885
postgresql_privs
```paste below
```
=> Rollback if nothing changed

tests/integration/targets/setup_docker/meta/main.yml, tests/integration/targets/setup_openssl/meta/main.yml, tests/integration/targets/setup_openssl/tasks/main.yml, tests/utils/constraints.txt
A version of cffi was yanked which makes pyOpenSSL crash, but pip on macOS is too old to know about yanked packages.
setup_openssl
=> Fix CI (problem with cffi)

changelogs/fragments/897-lookup-plugin-hashivault-add-approle-mount-point.yaml, plugins/lookup/hashi_vault.py
The `mount_point` parameter wasn't used by the `approle` auth method
hashi_vault lookup plugin
With the following task
```
- name: get_secret$
debug:$
msg: "{{ lookup('community.general.hashi_vault', 'secret=path/to/my/secret:secret auth_method=approle mount_point=awx url=' ~ vault_url) }}"
```
Before
```
TASK [get_secret] ****************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'community.general.hashi_vault'. Error was a <class 'hvac.exceptions.InvalidRequest'>, original message: invalid role ID, on …
```
=> [lookup_plugin/hashi_vault] add missing 'mount_point' param for approle

changelogs/fragments/831-proxmox-kvm-wait.yml, plugins/modules/cloud/misc/proxmox_kvm.py
Allows some factorization of redundant code in stop_vm(), start_vm(),
create_vm() and main().
This new function also waits one extra second after a successful task execution as the API can be a bit ahead of Proxmox.
Before:
TASK [ansible-role-proxmox-instance : Ensure test-instance is created]
changed: [localhost]
TASK [ansible-role-proxmox-instance : Ensure test-instance is updated]
fatal: [localhost]: FAILED! => changed=false
msg: VM test-instance does not exist in cluster.
After:
TASK [ansible-role-proxmox-instance : Ensure test-instance is created]
changed: [localhost]
TASK [ansible-role-proxmox-instance : Ensure test-instance is updated]
changed: [localhost]
With suggestions from Felix Fontein <felix@fontein.de>.
(cherry picked from commit 9a5fe4c9afffed61e24b0493be663cbac746ee5f)
- …
=> [PR #831 backport][stable-1] proxmox_kvm: new function wait_for_task()

changelogs/fragments/929-vault-namespace-support.yml, plugins/lookup/hashi_vault.py
As per https://learn.hashicorp.com/tutorials/vault/namespaces, setting VAULT_NAMESPACE env var is a completely supported mechanism to make all vault command use said namespace, so hashi_vault lookup function should do the same.
Fix namespace support for the `hashi_vault` lookup function by allowing use of `VAULT_NAMESPACE`
`lookup('hashi_vault')`
My local ansible environment is using an older version of this file where I also had to do this:
```
self.namespace = kwargs.get('namespace', os.environ.get('VAULT_NAMESPACE'))
```
but it seems like with this version, adding this env var field here is all that needs to happen. This would be pretty hard to test with a non-empty `VAULT_NAMESPACE` value, given that the server in question would have to be running Vault …
=> Support use of VAULT_NAMESPACE env var

changelogs/fragments/902-hashi_vault-token-path.yml, plugins/lookup/hashi_vault.py
Fixes #373 
As pointed out in that issue, setting the `token_path` via ini config is practically unusable, since the parameter also allows setting via the `$HOME` env var (which is pretty much always set, and can't be changed without affecting other things), and in Ansible env vars take precedence over ini values.
This is usually correct; but in most cases the env var is very specific to that config value and not really something that would be set accidentally.
The original intention of this setup was to fall back to the default location where the vault cli places the token file, but to be able to override the value via config.
----
This PR makes a few changes toward that:
* Removes `HOME` from the env vars in spec for `vault_path`
* Adds `VAULT_TOKEN_PATH` to the env vars in spec for …
=> hashi_vault - Change token_path env var loading precedence

changelogs/fragments/939-zypper_repository_proper_failure_on_missing_python-xml.yml, plugins/modules/packaging/os/zypper_repository.py
Fail appropriately when `python-xml` is missing.
This has been brought up on `#ansible IRC` first and someone faced this error when `python-xml` was missing:
```
- name: Repositorio > Agrega repositorio de descarga
zypper_repository:
name: bareos
description: "{{ bareos_repo_desc }}"
repo: "{{ bareos_repo_url }}"
autorefresh: no
auto_import_keys: yes
runrefresh: yes
state: present
{"changed": false, "module_stderr": "Shared connection to servidor.lan closed.
", "module_stdout": "Traceback (most recent call last):
File \"/root/.ansible/tmp/ansible-tmp-1600580309.7887352-52465957645063/AnsiballZ_zypper_repository.py\", line 102, in <module>
File \"/root/.ansible/tmp/ansible-tmp-1600580309.7887352-52465957645063/AnsiballZ_zypper_reposi …
```
=> zypper_repository: Proper failure when python-xml is missing

changelogs/fragments/903-enhance-redfish-manager-reset-actions.yml, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/redfish/redfish_command.py
Support the same power reset actions on Managers as on Systems.
Fixes #901 
After the change, a play like this can be created:
```paste below
---
- hosts: myhosts
name: Turn manager power on
gather_facts: False
tasks:
- name: Turn manager power on
redfish_command:
category: Manager
command: PowerOn
resource_id: BMC
```
Running it will produce output like this:
```
$ ansible-playbook -i myinventory.yml  playbooks/manager/power_on.yml
PLAY [Turn manager power on] *********************************************************
TASK [Turn manager power on] ***************************************************
ok: [mockup-localstorage]
PLAY RECAP …
```
=> Support same reset actions on Managers as on Systems

changelogs/fragments/900-aerospike-migration-handle-unstable-cluster.yaml, plugins/modules/database/aerospike/aerospike_migrations.py
When cluster is unstable, aerospike client raises a ServerError. We need to handle it in `_cluster_stable` so it doesn't bubble up to the module. 
aerospike_migrations
Before the fix, a cluster with pending migration will error out with the following error
```
FAILED! => {"changed": false, "msg": "Error: (1L, 'unstable-cluster, 127.0.0.1:3000', 'src/main/client/info_node.c', 177, False)"}
```
After:
it will continue to try until `tries_limit` is reached. which is working properly.
=> [aerospike_migrations] - handle exception for unstable-cluster

changelogs/fragments/945-darwin-timezone-py3.yaml, plugins/modules/system/timezone.py
In Python3, `platform.platform()` returns `macOS-10.15.6-x86_64-i386-64bit` instead of `Darwin-10.15.6-x86_64-i386-64bit`. 
`platform.system()` returns `Darwin` On py2 and py3.
plugins/modules/system/timezone.py
```paste below
```
=> Use platform.system for Darwin comparisons

.github/patchback.yml
This change adds an explicit config for the Patchback robot.
- Maintenance Pull Request
N/A
Merging this config must be coupled with renaming [`backport-stable-1`](https://github.com/ansible-collections/community.general/labels/backport-stable-1) label to `backport-1`.
=> 🤖 Add initial Patchback config

changelogs/fragments/979-docker_container-published_ports-empty-idempotency.yml, plugins/modules/cloud/docker/docker_container.py, tests/integration/targets/docker_container/tasks/tests/options.yml
When strict comparison is used and `published_ports` is `[]`, it is treated the same as not specified, i.e. `[]` is not enforced.
Fixes #978.
=> docker_container: fix idempotency problem with empty published_ports list

changelogs/fragments/zfs-root-snapshot.yml, plugins/modules/storage/zfs/zfs.py
Added support for snapshots when working with a root zvol that contains no / in its path.
Updated zfs.py to support working with snapshots when on the root zvol, Fixes #932 
zfs
The issue in #932 is caused because when working with a root zvol, there is no / i.e:
normally, when you have subvolumes, creating a snapshot would look like this: `myvol/mysubvol@snapshotname`
the code in the zfs.py module finds the root volume name by splitting out the /, which works fine for subvolumes.
but when you try to create a snapshot on the root volume, i.e `myvol@snapshotname` it errors, as the `.split('/')` doesn't split anything out, and so the full name `myvol@snapshotname` gets passed to `zpool version` hence the error. 
before:
```
fatal: [hob-ssv]: FAILED! => {
"changed": …
```
=> Fix zfs snapshot handling on root zvols

changelogs/fragments/522-parted_change_label.yml, plugins/modules/system/parted.py, tests/unit/plugins/modules/system/test_parted.py
calling mkpart even when partition existed before mklabel call 
Fixes #522
parted
Below playbook created empty partition label, even when partition table was not used by kernel.
My first diagnose of #522 was wrong, this is proper fix
```yaml
become: yes
tasks:
- name: create msdos partition
parted: 
device: /dev/loop0
number: 1
state: present
label: msdos
- name: create gpt partition
parted: 
device: /dev/loop0
number: 1
state: present
label: gpt
```
=> parted: proper fix for change of partition label case

changelogs/fragments/967-use-fqcn-when-calling-a-module-from-action-plugin.yml, plugins/action/system/iptables_state.py, tests/integration/targets/iptables_state/aliases
The ansible builtin module `async_status` is called 2 times, each by its short name, by the `iptables_state` action plugin.
This update uses FQCN instead, following [porting guide 2.10 guidelines](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.10.html#action-plugins-which-execute-modules-should-use-fully-qualified-module-names)
iptables_state
=> use FQCN when calling a module from action plugin

changelogs/fragments/699-django_manage-createcachetable-fix-idempotence.yml, plugins/modules/web_infrastructure/django_manage.py
This Pull Request fixes the problem that ansible always says that there always was a change made during `manage.py createcachetable`.
* django_manage
The reason why it didn't work before:
* manage.py prints `Cache table 'cache_table' already exists.` to stdout if there is no changes and _nothing_ if there were changes
* the code seems to correctly check this if manage.py returns non-zero exit code and whites its status to _stderr_ (which I didn't observed, no idea which version of Django does this) but fails if manage.py returns 0 and writes its status to stdout (which is what happens in my case) and in that case there are few problems:
* the code checks for phrase `Already exists` but the real spelling is `already exists` (case differs)
* there is always an empty …
=> Fix changes detection for django_manage createcachetable

changelogs/fragments/998-nagios-added_forced_check_for_all_services_or_host.yml, plugins/modules/monitoring/nagios.py
Added functionality to force an active service check for all services of a particular host or for the host itself.
Note that I've renamed the `service_check` command to `forced_check` since we now are able to check both a particular service, all services of a particular host and the host itself. This aligns to the `downtime` command.
nagios.py
```paste below
```
=> nagios: force an active service check for all services of a particular host or for the host itself

changelogs/fragments/951-ipa_user-add-userauthtype-param.yaml, plugins/modules/identity/ipa/ipa_user.py
Add `userauthtype` param to allow setting an IPA user's authentication type.
ipa_user
[Freeipa client API docs for ipauserauthtype param](https://python-freeipa.readthedocs.io/en/latest/index.html?highlight=user_mod#python_freeipa.client_meta.ClientMeta.user_mod)
```paste below
```
=> ipa_user: Add userauthtype param

changelogs/fragments/996-postgresql_privs_fix_function_handling.yml, plugins/modules/database/postgresql/postgresql_privs.py, tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
Fixes https://github.com/ansible-collections/community.general/issues/994
postgresql_privs: fix the module mistakes a procedure for a function
`plugins/modules/database/postgresql/postgresql_privs.py`
=> postgresql_privs: fix the module mistakes a procedure for a function

changelogs/fragments/992-nmcli-locale.yml, plugins/modules/net_tools/nmcli.py
Set `C` locale when executing `nmcli` binary. This avoids localization problems, such when `nmcli` uses `ja` instead of `yes` because the `LANG=de`.
Fixes #989.
nmcli
=> nmcli: set C locale when executing nmcli

changelogs/fragments/pkgutil-check-mode-etc.yaml, plugins/modules/packaging/os/pkgutil.py, tests/integration/targets/pkgutil/aliases, tests/integration/targets/pkgutil/tasks/main.yml
Taken from https://github.com/ansible/ansible/pull/51651 by @dagwieers, which was taken from https://github.com/ansible/ansible/pull/27866 by @scathatheworm.  Let’s have one last attempt to get this merged.
> ##### SUMMARY
>
> Original PR #27866 from @scathatheworm
>
> When working with Solaris pkgutil CSW packages, I came across this module
being very basic in functionality, in particular, that I could not use it
to update all CSW packages.
>
> When going into details into the code I also found it did not incorporate
a possibility of doing dry-run from the underlying utility, or supported to
specify multiple packages for operations.
>
> This module probably sees very little use, but it seemed like nice
functionality to add and make it behave a little more like other package
modules.
> …
=> pkgutil: add update all, check-mode, squashing and examples

tests/integration/targets/inventory_kubevirt/runme.sh
Since yesterday one of the FreeBSD CI nodes constantly fails: https://app.shippable.com/github/ansible-collections/community.general/runs/4094/115/console
It did work two days ago: https://app.shippable.com/github/ansible-collections/community.general/runs/4050/115/console
kubevirt
=> Fix failing FreeBSD CI

changelogs/fragments/xml-remove-changed.yml, plugins/modules/files/xml.py, tests/integration/targets/xml/tasks/main.yml, tests/integration/targets/xml/tasks/test-remove-attribute-nochange.yml, tests/integration/targets/xml/tasks/test-remove-element-nochange.yml, tests/integration/targets/xml/tasks/test-remove-namespaced-attribute-nochange.yml, tests/integration/targets/xml/tasks/test-remove-namespaced-element-nochange.yml
`xml` module reports changed even if the xpath to be deleted already does not exist.
xml
=> Fix xml reports changed when node is not deleted

plugins/inventory/stackpath_compute.py, tests/unit/plugins/inventory/test_stackpath_compute.py
This adds an inventory plugin for Stackpath's Edge Compute product.
stackpath_compute inventory plugin
This leverages the Stackpath public API to get an inventory of hosts for both containers and VM workloads.
Details on Stackpath Edge Compute https://www.stackpath.com/products/edge-compute/
Details on the Stackpath API https://stackpath.dev/reference
=> Add inventory plugin for Stackpath Edge Compute

changelogs/fragments/349-pacman_improve_group_expansion_speed.yml, plugins/modules/packaging/os/pacman.py
For each package check membership in the list instead of checking each
package individually using pacman to see if it is a pacman group.
When using a large amount packages the pacman module takes very long to generate the final list of packages, because it checks each pkg individually for group membership via `pacman --sync --groups --quiet pkgname`.
pacman
This improves package installation by 50% on my system (when all packages are already installed).
Master:
```
- Play recap -
herakles                   : ok=1    changed=0    unreachable=0    failed=0    rescued=0    ignored=0   
Friday 15 May 2020  19:34:58 +0200 (0:00:17.214)       0:00:17.231 ************ 
```
PR:
```
- Play recap -
herakles                   : ok=1    changed=0    unreachable=0    failed=0 …
```
=> Improve group expansion speed: query list of pacman groups once (#349)

changelogs/fragments/1024-vault-skip-verify-support.yml, plugins/lookup/hashi_vault.py, tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_test.yml, tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml
The standard way of disabling certificate verification for hashicorp vault is by setting the `VAULT_SKIP_VERIFY` environment variable to True.
Currently the hashi_vault lookup plugin does not respect the setting of this environment variable (you instead need to set `validate_certs` to `False` to disable certificate verification).
This adds an the functionality to set the value of `validate_certs` to the inverse of `VAULT_SKIP_VERIFY` (if it is set)
hashi_vault
```paste below
```
=> Respect VAULT_SKIP_VERIFY envionment variable setting in hashi_vault lookup plugin

changelogs/fragments/968-gitlab_variables-pagination-increase.yml, changelogs/fragments/968-gitlab_variables-pagination.yml, plugins/modules/source_control/gitlab/gitlab_group_variable.py, plugins/modules/source_control/gitlab/gitlab_project_variable.py, tests/integration/targets/gitlab_group_variable/tasks/main.yml, tests/integration/targets/gitlab_project_variable/tasks/main.yml
The ansible `gitlab` module_utils does not enable support for gitlab pagination at Gitlab object instanciation, so at the moment the queries to the API end up using the default pagination of **20** items to list per page  thus limiting to 20 the number of variables returned to  both `gitlab_project_variables` and `gitlab_group_variable` ansible modules.
As a temporary measure the instantiated gitlab object `per_page` property could be set  to its [max value of 100](https://docs.gitlab.com/ee/api/#pagination) at class init  and before performing the API call for groups and projects.
Long term solution beyond 100 variables would need to  cater for pagination support. 
What is not clear to me  yet is if in the underlying [python-gitlab](https://github.com/python-gitlab/python-gitlab) python …
=> Gitlab variables pagination

changelogs/fragments/1028-proxmox-kvm-linked-clone.yml, plugins/modules/cloud/misc/proxmox_kvm.py
Fixes #1027 
The source problem is that _format_ parameter has a default value _qcow2_.
The underlying API does not allow to create a linked clone and at the same time specify _format_ parameter.
For backward compatibility reason, I left the default value of _format_ parameter untouched but allowed to set this parameter to null (None) to cancel it out.
proxmox_kvm
How to create a linked clone after the change:
```
- name: clone vm
proxmox_kvm:
api_host: "{{ hypervisor_ip }}"
api_password: "{{ pass }}"
api_user: "{{ user }}"
node: "{{ proxmox_node }}"
clone: "{{ clone }}"
name: "{{ inventory_hostname }}"
full: no
format: null
delegate_to: "{{ hypervisor_ip }}"
```
Old response:
```paste below
"Unable to clone vm cysoc-test-first-vm-1 from vmid 30000=500 Internal …
```
=> proxmox_kvm: allow setting format to null (None)

changelogs/fragments/1036-redis-cache-keyset-name.yaml, plugins/cache/redis.py
make the hard coded key of the available key set in redis configurable. default is `ansible_cache_keys`. In my usecase I want to  to cache facts with different prefixes in the same redis db. to prevent mixing of different cache prefix keys,a way to configure the key set name is desirable.
cache/redis
```paste below
```
=> cache/redis: make keyset keyname configurable

changelogs/fragments/1078-postgresql_ext_fix_version_selection_when_version_is_latest.yml, plugins/modules/database/postgresql/postgresql_ext.py
If `version == 'latest'` then the version is set to `available_versions[-1]` however `available_versions` was not previously sorted so the ordering was the natural order of the `pg_available_extension_versions` view.
This PR sorts the version using `LooseVersion` so that the version taken is in fact the latest available version.
postgresql_ext
=> postgresql_ext: sort list of available versions

changelogs/fragments/1091-postgresql_info_add_in_recovery_ret_val.yml, plugins/modules/database/postgresql/postgresql_info.py, tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml
Fixes https://github.com/ansible-collections/community.general/issues/1068
postgresql_info: add in_recovery return value to show if a service in recovery mode or not 
`plugins/modules/database/postgresql/postgresql_info.py`
=> postgresql_info: add in_recovery return value to show if a service in recovery mode or not

changelogs/fragments/1099-postgresql_ext_fix_failing_when_version_cannot_be_compared.yml, plugins/modules/database/postgresql/postgresql_ext.py, tests/integration/targets/postgresql_ext/tasks/postgresql_ext_version_opt.yml, tests/unit/plugins/modules/database/postgresql/test_postgresql_ext.py
Fixes https://github.com/ansible-collections/community.general/issues/1095
postgresql_ext: fix module's failing when available ext versions contain a pure string
`plugins/modules/database/postgresql/postgresql_ext.py`
=> postgresql_ext: fix module's failing when available ext versions contain a pure string

changelogs/fragments/993-file-capabilities.yml, plugins/modules/system/capabilities.py
When module is run with recent version of libcap (getcap / setcap), playbook run returns error, since libcap has changed output of getcap. Fix it with this PR.
Fixes #993 
plugins/modules/system/capabilities.py
Tested on debian 10 (version 2.25-2 of libcap) and debian sid (libcap version 2.43-1). 
Works, with `state:` variable `present` and/or `absent`, on the following playbook : 
```
$ cat ~/ansible.dev/playbooks/getcap.yml
---
- name: community.general/issues/993
hosts: debian10
become: true
tasks:
- name: ensure capabilities for ping are set
community.general.capabilities:
path: /bin/ping
capability: cap_net_raw+ep
state: present
```
will try to write a test unit as well (if there's no globals or whatever)...
=> [capabilities] fix for a newer versions of libcap

plugins/modules/web_infrastructure/django_manage.py
Updates the django_manage database parameter docs to show that it can be used with migrate. 
Here are the parameters supported by django_manage migrate (you can see it includes "database"): https://github.com/ansible-collections/community.general/blob/3d19e15a7d97f2e956722522a58c612c706098f9/plugins/modules/web_infrastructure/django_manage.py#L200
=> update django_manage migrate docs to include database param

changelogs/fragments/1101-slack-ts-fix.yaml, plugins/modules/notification/slack.py, tests/unit/plugins/modules/notification/test_slack.py
at one point in do_notify_slack, we do operations on the payload
variable assuming it's a dict, but it's not: it's a json encoded string.
it's useful to operate on the payload as a dict rather than a string, so
solve this problem by moving the jsonify call to right before sending
the payload to the slack API.
fixes #1097
`plugins/modules/notification/slack.py`
=> move conversion of data to json in slack API handling

changelogs/fragments/1079-redis-use-regexp-to-check-if-the-value-matches-expected-form.yaml, plugins/modules/database/misc/redis.py
Fixes #1076 
check the value with a regexp to check if it matches something like
regexp should match values like:
- 1B
- 10MB
- 10mb
- 1.0kB
redis
```paste below
ansible -m community.general.redis -b -a"command=config name=save value='900 1 300 10 60 10000'" aio
aio | SUCCESS => {
"name": "save",
"value": "900 1 300 10 60 10000"
}
```
=> redis: use regexp to check if the value matches expected form

changelogs/fragments/1055-redis-cache-sentinel.yaml, plugins/cache/redis.py
Add redis sentinel functionality to redis cache plugin. Used for high available redis setups controlled by redis sentinel.   
The plugin asks the sentinels which redis node is currently the active master and sets the connection internally. There is no change in logic how the redis cache backend works, only where to connect.
Redis Sentinel is available since redis python >=2.9.0 (https://github.com/andymccurdy/redis-py/commit/46e475d9b95501a46c7abba9f05d415e27e9a62d). the minimal requirement at the moment for the redis cache module is >= 2.4.5
To not break backwards compatibility, Sentinel is imported when a sentinel uri is configured. additionally the sentinel config is sepparated by `;` to maintain the existing uri layout.
merge #1036 first. this PR is built uppon. …
=> cache/redis: feature redis sentinel

changelogs/fragments/886-postgresql_query_add_ret_vals.yml, plugins/modules/database/postgresql/postgresql_query.py, tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
Fixes  https://github.com/ansible-collections/community.general/issues/838
Adds `query_list` and `query_all_results` ret values
postgresql_query
=> postgresql_query: add query_all_results ret value

changelogs/fragments/1127-maven_artifact_client_cert.yml, plugins/modules/packaging/language/maven_artifact.py
Added an option to use client_cert and client_key in maven_artifact. Matches the function of get_url since they both use fetch_url in the background.
Fixes #1123 
maven_artifact
```paste below
```
=> Added client_cert and client_key to the maven_artifact module.

changelogs/fragments/1140-iptables_state-fix-race-condition.yml, plugins/action/system/iptables_state.py, plugins/modules/system/iptables_state.py
Fixes #1136
Also remove irrelevant/unneeded display.v() and display.warning() around connection reset, by the way.
iptables_state
For the rationale, see the issue description. This PR applies the solution 3 as found at the end of this description:
https://github.com/ansible-collections/community.general/issues/1136
=> iptables_state: fix race condition between module and its action plugin

changelogs/fragments/409-datadog-monitor-include-tags.yaml, plugins/modules/monitoring/datadog/datadog_monitor.py
Add `include_tags` option to `datadog_monitor` module.
Closes https://github.com/ansible/ansible/issues/57441
- `datadog_monitor`
- https://docs.datadoghq.com/api/?lang=python#create-a-monitor
=> Add include_tags to datadog_monitor

changelogs/fragments/nmcli-refactor.yml, plugins/modules/net_tools/nmcli.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt, tests/unit/plugins/modules/net_tools/test_nmcli.py
Refactor `nmcli` module for consistency and to remove duplicate and/or unused code:
* Connection creation/modification methods:
* `connection_update`: replaces all `{create,modify}_connection_*` methods
* `connection_options`: returns consistent nmcli options for all connection types and when detecting changes. 
* Use consistent settings across connection all types:
* IP settings: e.g., `ipv4.addresses` instead of `ip4` or `ipv4.address`.
* Connection settings: e.g., `connection.autoconnect, `connection.interface-name` instead of `autoconnect`, `ifname`.
* Bridges: e.g., `bridge-port.hairpin-mode` instead of `bridge-port.hairpin`.
* Tunnels: e.g., `ip-tunnel.parent` instead of `dev`.
* Use all settings when creating a connection so it doesn't need to be immediately modified (less `nmcli` …
=> nmcli: module refactor

tests/integration/targets/pids/tasks/main.yml
The pids integration test regularly fails on macOS. Adds a small delay to hopefully make it more stable.
- Test Request
tests/integration/targets/pids/tasks/main.yml
=> Try to make pids test more stable

plugins/modules/database/postgresql/postgresql_copy.py, plugins/modules/database/postgresql/postgresql_db.py, plugins/modules/database/postgresql/postgresql_ext.py, plugins/modules/database/postgresql/postgresql_idx.py, plugins/modules/database/postgresql/postgresql_info.py, plugins/modules/database/postgresql/postgresql_lang.py, plugins/modules/database/postgresql/postgresql_membership.py, plugins/modules/database/postgresql/postgresql_owner.py, plugins/modules/database/postgresql/postgresql_ping.py, plugins/modules/database/postgresql/postgresql_privs.py, plugins/modules/database/postgresql/postgresql_publication.py, plugins/modules/database/postgresql/postgresql_query.py, plugins/modules/database/postgresql/postgresql_schema.py, plugins/modules/database/postgresql/postgresql_sequence.py, plugins/modules/database/postgresql/postgresql_set.py, plugins/modules/database/postgresql/postgresql_slot.py, plugins/modules/database/postgresql/postgresql_table.py, plugins/modules/database/postgresql/postgresql_tablespace.py, plugins/modules/database/postgresql/postgresql_user.py, plugins/modules/database/postgresql/postgresql_user_obj_stat_info.py
I noticed that the postgresql_db module's [documentation](https://docs.ansible.com/ansible/latest/collections/community/general/postgresql_db_module.html) on `trust_input` says that
> It makes sense to use `yes` only when SQL injections via the parameters are possible.
I think this is a typo, and it should say 'use `no`' instead of 'use `yes`'. My understanding is that the input should not be trusted by the Ansible script when injection attacks are possible.
This PR fixes the relevant documentation, as well as the documentation of other modules that have the `trust_input` parameter.
Related to ansible-collections/community.general#309.
- postgresql_copy
- postgresql_db
- postgresql_ext
- postgresql_idx
- postgresql_info
- postgresql_lang
- postgresql_membership
- …
=> postgresql modules: Fix documentation of trust_input parameter

changelogs/fragments/1154-django_manage-docs.yml, plugins/modules/web_infrastructure/django_manage.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Updates the django_manage documentation: markups and a typo
Adjusted the markup for a number of terms, also fixed a typo in the alias for virtualenv.
=> Fixed django_manage markup in docs

changelogs/fragments/436-infoblox-use-stderr-and-environment-for-config.yaml, scripts/inventory/infoblox.py
Originally from https://github.com/ansible/ansible/pull/49685
Errors should send to stderr, and this allows the use of an environment var to point to where the YAML config lives.
This is particularly useful when using this script with AWX and custom credentials (injecting YAML config).
infoblox.py
=> infoblox inventory script: Use stderr, and allow use of environment for config

changelogs/fragments/1149-filesystem-fix-355-state-absent.yml, plugins/modules/system/filesystem.py, tests/integration/targets/filesystem/tasks/main.yml, tests/integration/targets/filesystem/tasks/remove_fs.yml, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Add `state` option to the module:
- `present` is the default value (backward compatibility).
- When `state=present` or `state` is omitted, the module still behaves as it did before.
- When `state=absent`, other options are ignored but `dev`: it is still mandatory, but the module doesn't fail if the device/file doesn't exist.
- When `state=absent`, if the device exists and holds a filesystem, filesystem signatures are wiped.
Fixes #355
filesystem
This PR also comes with tests matching the new feature.
Possible implementations:
- `wipefs`: comes with util-linux, not implemented on FreeBSD (which is supported by the module); `resizefs` option is also based on util-linux commands (`findmnt`, `blockdev`) and probably not supported too.
- `dd`: much more portable; needs to …
=> filesystem: fix 355 state absent

changelogs/fragments/1119-docker_container-device-reqests.yml, plugins/modules/cloud/docker/docker_container.py, tests/integration/targets/docker_container/tasks/tests/options.yml
Fixes ansible/ansible#65748.
Unfortunately it is hard to test this in CI, since we don't have special hardware and docker runtimes installed. The tests are therefore very minimalistic and don't really test something.
=> docker_container: add device_requests option

changelogs/fragments/360_syspatch_apply_patches_by_default.yml, plugins/modules/system/syspatch.py
I've made syspatch apply patches by default, so one can call it without any parameters. This is how the command line tool is used, so this will make the module work similarly.
I also made minor documentation cleanup updates, and used a better comparison operator for when calling `.find()` on stdout output. This would likely never be an issue in the real world, but figured I should do it anyways.
syspatch
```paste below
- name: Calling with parameter
syspatch:
apply: True
- name: Calling with parameter
syspatch:
apply: True
- name: Call without parameter
syspatch:
```
=> OpenBSD Syspatch: Apply patches by default. Minor module cleanup

changelogs/fragments/remove-ansible.posix-dependency.yml, galaxy.yml, plugins/module_utils/_mount.py, plugins/modules/system/aix_filesystem.py, tests/requirements.yml, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt, tests/utils/shippable/shippable.sh
As mentioned [here](https://github.com/ansible-collections/overview/discussions/117#discussioncomment-106136) by vendoring the one file used by the `filesystem` module.
(Also part of #354.)
filesystem
collection
=> Remove ansible.posix dependency

.github/BOTMETA.yml
I should be listed as the maintainer for the xconf module.
I havealready  done a big revamp of the module in #693 after Joe Benden requested maintainers to step up in https://github.com/ansible/ansible/pull/50108#issuecomment-471218315
.github/BOTMETA.yaml
=> added russoz as maintainer of xfconf

changelogs/fragments/1185-proxmox-ignore-qemu-templates.yml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
Current implementation caused `_get_vm_status method` to fail, as the host has not been created in inventory at line [304](https://github.com/ansible-collections/community.general/blob/master/plugins/inventory/proxmox.py#L304-L306). This patch changes the condition to ignore templates altogether instead of skipping the creation of the host in the inventory.
proxmox
```
[WARNING]:  * Failed to parse inventory.proxmox.yml with auto plugin: Could not identify group or host named Ubuntu20.04
File "/usr/local/lib/python3.8/dist-packages/ansible/inventory/manager.py", line 289, in parse_source
plugin.parse(self._inventory, self._loader, source, cache=cache)
File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/inventory/auto.py", line 58, in parse …
```
=> proxmox: ignore QEMU templates altogether

changelogs/fragments/823-terraform_init_reconfigure.yaml, plugins/modules/cloud/misc/terraform.py
When using terraform init, we might want to use the "reconfigure" option to reinitialize the backend (https://www.terraform.io/docs/commands/init.html):
terraform
Original PR https://github.com/ansible/ansible/pull/66216
```
- terraform:
project_path: "/tfpath"
variables: "{{ tfvars }}"
backend_config: "{{ terraform_backend_config_vars }}"
state: 'planned'
workspace: "{{ env_name }}"
force_init: true
init_reconfigure: true
plan_file: "terraform.planfile"
```
From PR comments switched from a generic "extra_args" option to a specific "init_reconfigure" one, as this was the main purpose of the PR
=> Add support for "reconfigure" option for terraform init

changelogs/fragments/1223-nios-remove-redundant-aliases.yml, plugins/modules/net_tools/nios/nios_fixed_address.py, plugins/modules/net_tools/nios/nios_host_record.py, plugins/modules/net_tools/nios/nios_zone.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt
Fixes #852.
Redundant aliases were present in the argument specs of these modules, causing unnecessary [WARNING] messages on execution.
nios_fixed_address
nios_host_record
nios_zone
See #852
=> Remove redundant aliases from NIOS modules

changelogs/fragments/850-proxmox_kvm-remove_hard_coded_defaults.yml, plugins/modules/cloud/misc/proxmox.py, plugins/modules/cloud/misc/proxmox_kvm.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
**This is a backport of PR #850 as merged into main (`d6f5029`).**
Extends https://github.com/ansible-collections/community.general/pull/794 to more options.
Some defaults are not proxmox defaults like cpuunits which has been mentioned on https://github.com/ansible-collections/community.general/pull/794.
Also none of them are necessary and proxmox itself has a default value for them which may change in the future.
=> [PR #850/d6f5029 backport][stable-1] proxmox, proxmox_kvm: Deprecate hard-coded defaults

changelogs/fragments/odbc.yml, plugins/modules/database/misc/odbc.py
Adding a parameter which disables the auto-commit feature within the module.
We had an auto commit in the module incase someone was passing in a DDL statement.
As noted in the referenced bug this commit was causing issues with some databases after trying to perform a select.
This new parameter will prevent the module from auto-committing after the execute statement.
Fixes #1137
odbc
```paste below
```
=> odbc: adding parameter to disable auto-commit (#1137)

changelogs/fragments/216-fix-lxc-container-container_config-parameter.yaml, plugins/modules/cloud/lxc/lxc_container.py
Fix the parameter type of `container_config`.
The documentation of the module states that `container_config` is a list but the type specified in the module code is `str` which generate an annoying warning when `container_config` is used.
lxc_container
=> lxc_container: fix the type of the 'container_config' parameter

changelogs/fragments/1244-renamed-parameter.yaml, plugins/modules/web_infrastructure/django_manage.py
Per issue #1044 it was concluded that neither `app_path` nor `chdir` are the best names for the parameter, so changing it to `project_path` and adding those other terms as aliases.
Fixes #1044 
Module users should be able to continue using it as-is, but the name of the parameter is now `project_path`.
=> Changed parameter name, added aliases for compatibility.

changelogs/fragments/229_lvol_percentage_fix.yml, plugins/modules/system/lvol.py
Changed the behavior when using %VG or %PVS to make the size_requested an even modulus with the VGs physical extents by rounding down.  This makes the usage of %VG or %PVS idempotent when the calculated size_requested does not end on a physical extent boundary and the VG is fully allocated.
Fixes #290.
lvol
The VG looks like this:
> vgs --noheadings --nosuffix -o vg_name,size,free,vg_extent_size --units 'm' --separator ';' mysql_vg
>
> mysql_vg;3060.00;0;4.00
Based on the logic of the module the size requested looks like this:
> size_requested = size_percent * this_vg['size'] / 100
> 2295.0 = 25 * 3060.00 / 100
>
When divided by the extent size we can see it is not whole number:
> size_requested / 4 = 573.75
This is not an issue unless the VG is fully allocated. …
=> Fix idempotent issue when using lvol with %VG or %PVS size options and VG is fully allocated

changelogs/fragments/community.docker-31-docker-secret.yml, plugins/modules/cloud/docker/docker_secret.py
Backport of ansible-collections/community.docker#31.
docker_secret
=> Add a warning when ansible_key label is not found on a secret. (#31)

changelogs/fragments/1196-use_description-in-gitlab-group-creation.yml, plugins/modules/source_control/gitlab/gitlab_group.py, tests/integration/targets/gitlab_group/tasks/main.yml, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_group.py
Adds the description parameter to the creation request.
Fixes #138 
gitlab_group
Issue #138 is a couple of months old and a lot has changed since then. Nonetheless, the `description` parameter is still not used in the creation of groups.
The **Steps to Reproduce** should change a bit, from:
```
- name: "Create GitLab Group"
gitlab_group:
server_url: https://gitlab.example.com/
validate_certs: True
api_username: dj-wasabi
api_password: "MySecretPassword"
name: my_first_group
path: my_first_group
description: My First Group
state: present
```
to 
```
- name: "Create GitLab Group"
gitlab_group:
api_url: https://gitlab.example.com/
validate_certs: True
api_username: dj-wasabi
api_password: "MySecretPassword"
name: my_first_group
path: my_first_group
description: My First …
```
=> added description parameter to create request

changelogs/fragments/openbsd_pkg.yml, plugins/modules/packaging/os/openbsd_pkg.py
Just before an OpenBSD release and after the beta phase the OpenBSD tag points to the next release. If you follow -current, you have to set `-Dsnap` to update/install packages.  However, this was not possible with this module.
=> Add OpenBSD pkg_add(1) snapshot support

plugins/modules/monitoring/pagerduty_change.py, plugins/modules/pagerduty_change.py, tests/unit/plugins/modules/monitoring/test_pagerduty_change.py
PagerDuty recently released a new feature called change events that behave similar to events that can trigger incidents, except they are used to track code/infrastrucure changes rather than triggering incidents. This change adds a module to easily allow creating change events from ansible deploys.
pagerduty_change
```paste below
- name: Track the deployment as a PagerDuty change event
community.general.monitoring.pagerduty_change:
integration_key: abcdabcdabcdabcdabcdabcdabcdabcd
summary: The application was deployed
```
=> Adds a module for sending PagerDuty change events.

changelogs/fragments/1270-linode-v4-stackscript-support.yaml, plugins/modules/cloud/linode/linode_v4.py
This adds support for Linode StackScripts when creating instances via the Linode v4 module and hopefully closes https://github.com/ansible-collections/community.general/issues/723. I also fixed some stale documentation links while I was here.
linode_v4
I decided against making an envelope as diagrammed in the issue above. Additionally, I decided to make the ansible argument explicitly `stackscript_id` to be more explicit than Linode's Python wrapper, which accepts `stackscript` as either a numeric parameter _or_ an object.
=> Add support for StackScripts to Linode v4 module

changelogs/fragments/1258-proxmox_kvm-ignore-pool-on-update.yaml, plugins/modules/cloud/misc/proxmox_kvm.py
Updating a VM with `pool` parameter set fails with a 400 status code, since it's not in the parameter list of the `qemu/<vmid>/config` endpoint. I only found the API docs of PVE 6.2, so I don't know if it ever worked. Would have added a version check otherwise.
The correct way to update it should be using the /pools endpoint. But I think that's be something for another module or a feature of the API itself (like with the disks).
Like for `virtio`, ... I added the removal of the key for `update` and mentioned it at the same place in the docs. 
proxmox_kvm
It's my first contribution to any ansible related code, so I had some issues with the dev environment... I tried the tests, but kubevirt fails. The doc generation also failed, so I couldn't check if the formatting is …
=> proxmox_kvm: pool parameter not supported by qemu/<vmid>/config API endpoint

changelogs/fragments/805-docker_image-build-output.yml, plugins/modules/cloud/docker/docker_image.py, tests/integration/targets/docker_image/tasks/tests/docker_image.yml
The build output is only added during failures, but its useful to have this available during normal task execution as well.
docker_image
This change adds a new key `build_output` to the task result which includes all the docker build steps. This is useful to understand for e.g. what steps were run for the build, as well as steps that used / not used the image cache.
=> Add docker build output to task result

tests/unit/plugins/modules/net_tools/test_hetzner_failover_ip.py, tests/unit/plugins/modules/net_tools/test_hetzner_failover_ip_info.py
The `hetzner_failover_ip` and `hetzner_failover_ip_info` had no tests so far.
hetzner_failover_ip
hetzner_failover_ip_info
=> Add hetzner_failover_ip* tests

changelogs/fragments/1138-hashi_vault_fix_approle_authentication_without_secret_id.yml, plugins/lookup/hashi_vault.py, tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_secret_id_less_setup.yml, tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_secret_id_less_test.yml, tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
Fix hashi_vault lookup approle authentication without a secret_id
hashi_vault
As per the plugin documentation and the Hashicorp Vault documentation (https://www.vaultproject.io/docs/auth/approle#secretid)
secret_id is not mandatory.
Moreover, using this lookup plugin without a secret_id used to work in
Ansible 2.9.
=> Fix hashi_vault lookup approle authentication

changelogs/fragments/1206-proxmox-api-token.yml, plugins/modules/cloud/misc/proxmox.py, plugins/modules/cloud/misc/proxmox_kvm.py, plugins/modules/cloud/misc/proxmox_template.py
Provides an alternative authentication method to the password.
The token validity is only tested during the first request after the instantiation of `ProxmoxAPI`, thus the presence of a call to `proxmox.version.get()` in `proxmox_template`.
Fixes #559, idea from @d4vydm.
Require testing for modules `proxmox` and `proxmox_template`.
proxmox_kvm, proxmox_template, proxmox
Example of use:
```
- name: Ensure test-vm is created
proxmox_kvm:
api_host: prx-test
api_user: tleguern@pve
api_token_id: api-pve-test
api_token_secret: fad3db3d-b335-ee15-9fb0-ea1bf70128db
node: prx-test-01
name: test-vm
...
```
=> proxmox*: add support for API tokens

changelogs/fragments/1243-pkgng-present-ignoreosver.yaml, plugins/modules/packaging/os/pkgng.py
By applying this merge request we would be able to:
- use "_ignore_osver_" as option to define `IGNORE_OSVERSION` as environment variable;
- make possible to ignore **FreeBSD** OS version check on `pkg` versions _>= 1.11_;
- be able to freely use `pkg` on systems running _-STABLE_ and _-CURRENT_ branches.
```
plugins/modules/packaging/os/pkgng.py
```
- `pkg`'s config manpage: [pkg.conf(5)](https://www.freebsd.org/cgi/man.cgi?query=pkg.conf&sektion=5)
- [Changes from pkg 1.10.99.7 to 1.10.99.8](https://github.com/freebsd/pkg/blob/release-1.11/NEWS#L51)
-  Reddit thread: [Fix pkg mismatch after updating](https://www.reddit.com/r/freebsd/comments/f360r2/fix_pkg_mismatch_after_updating/)
=> [pkgng] present the 'ignore_osver' option to pkg

changelogs/fragments/1246-flatpak-use-non-interactive-argument.yaml, plugins/modules/packaging/os/flatpak.py
Replace the argument `-y` by `--non-interactive` if the Flatpak version is >= 1.1.3 ([changelog](https://github.com/flatpak/flatpak/releases/tag/1.1.3)).
Idea from the PR #268 by @jdufresne.
flatpak
=> Add --non-interactive argurment to Flatpak

.github/BOTMETA.yml
In the `BOTMETA.yml` file now, `$team_aix` is responsible for all modules under `system` which does not seem to make sense - given the variety range of modules in that directory. On top of that, the `aix_lvol.py` module has its maintainer set to this one single user, **adejoux**. In the `ansible` repository, this user last commit was in 2017, so it does not look like it is someone actively working on these modules.
Modules with maintainer set to team_aix:
aix_devices.py
aix_filesystem.py
aix_inittab.py
aix_lvg.py
aix_lvol.py
=> BOTMETA.yml - setting aix modules for team_aix

.github/BOTMETA.yml, changelogs/fragments/1322-module_helper_and_xfconf.yaml, plugins/module_utils/module_helper.py, plugins/modules/system/xfconf.py, tests/unit/plugins/module_utils/test_module_helper.py, tests/unit/plugins/modules/system/test_xfconf.py
After I had worked on xfconf, I became maintainer for the django_manage module as well, and doing that big cleanup work on the ignore files, it wasn't impossible to deny many - most, perhaps - of the modules follow the same patterns. That prompted me to think of a common class that would encompass the standard AnsibleModule and that would provide a scaffolding structure for writing modules. Thus was born `module_helper`.
Right now this is a bit experimental, and I also intend to write unit tests for `module_helper` itself, but right now both `module_helper` and `xfconf` itself are passing sanity tests, and `xfconf` is still passing the tests it passed before (with some adjustments in the internal representation of values, see the big commit message appended below for more details).
I …
=> Adding module_utils/module_helper.py + big revamp in xfconf.py to use it

changelogs/fragments/docker-migration.yml
Documents the upcoming docker content removal for community.general 2.0.0.
collection
=> [WIP] [stable-1] Add information on docker module migration

changelogs/fragments/773-resize-partition.yml, plugins/modules/system/parted.py, tests/unit/plugins/modules/system/test_parted.py
This allows parted to resize existing partitions if they exist and part_end doesn't match the current value.
Has a safety check and fails if the given part_end would shrink the partition rather than extend it.
A typical use-case I have for this is to allow the OS of a virtual machine to update the partitions on a disk following a disk resize - hypervisors typically don't have functionality to do this. 
parted
=> Add ability to resize existing partition

changelogs/fragments/1264-dict_kv-new-filter.yaml, plugins/filter/dict_kv.py, tests/integration/targets/filter_dict_kv/aliases, tests/integration/targets/filter_dict_kv/tasks/main.yml
Add dict_kv filter which returns a single key-value pair from two arguments. Useful for generating complex dictionaries without using loops.
Example 1
```
vars:
myvar: myvalue
tasks:
- debug:
msg: "{{ myvar | dict_kv('thatsmyvar') }}" 
OUTPUT:
"msg": {
"thatsmyvar": "myvalue"
}   
}
```
Example 2
```
vars:
common_config:
type: host
database: all 
myservers:
- server1
- server2
tasks:
- debug:
msg: "{{ myservers | map('dict_kv', 'server') | map('combine', common_config) }}" 
OUTPUT:
"msg": [
{
"database": "all",
"server": "server1",
"type": "host"
},  
{   
"database": "all",
"server": "server2",
"type": "host"
}   
]   
}
``` 
plugin/filter …
=> Add filter dict_kv

.github/BOTMETA.yml
Relates to https://github.com/ansible-collections/community.general/pull/1264
BOTMETA.yml: add a new maintainer of dict_kv plugin
=> BOTMETA.yml: add a new maintainer of dict_kv plugin

changelogs/fragments/1331-proxmox-info-modules.yml, plugins/doc_fragments/proxmox.py, plugins/module_utils/proxmox.py, plugins/modules/cloud/misc/proxmox_domain_info.py, plugins/modules/cloud/misc/proxmox_group_info.py, plugins/modules/cloud/misc/proxmox_user_info.py, plugins/modules/proxmox_domain_info.py, plugins/modules/proxmox_group_info.py, plugins/modules/proxmox_user_info.py, tests/integration/targets/proxmox/aliases, tests/integration/targets/proxmox/tasks/main.yml
Add a doc_fragment to share the documentation regarding authentication
parameters (`api_host`, `api_user`, `api_password`, `api_token_id`,
`api_token_secret` as well as the lone `validate_certs`).
Add a module_utils to hold common code such as the argument spec (again
related to authentication parameters), a helper function to convert from
Proxmox boolean representation to python and the base class
`ProxmoxAnsible`.
For now it only handles the connection to Proxmox VE API but more can be
added in the future.
To check if everything is well in place add three new modules:
`proxmox_domain_info`, `proxmox_group_info` and `proxmox_user_info`.
And finally tests these new modules.
- proxmox_domain_info
- proxmox_group_info
- proxmox_user_info
=> proxmox: create a common base

changelogs/fragments/1338-datadog-mark-notification_message-no_log.yml, plugins/modules/monitoring/datadog/datadog_monitor.py
This message field is often used to page people or teams inside
an organization when a monitor goes off, by using `@` mentions.
If Ansible is configured to use Datadog's callback plugin [1], an
unwanted interaction would happen: 
When a monitor fails to create, the callback sends an error event
to Datadog which contains all the task's loggable fields in it.
If the message field contains `@` mentions, this event would page
the people on them.
[1] https://github.com/DataDog/ansible-datadog-callback
`community.general.datadog_monitor`
=> Datadog: Mark notification_message as no_log

changelogs/fragments/docker-migration.yml, changelogs/fragments/hetzner-migration.yml
With `>` instead of `|`, all the text ends up in one paragraph in the changelog.
CC @Andersson007 
changelog
=> Improve docker and hetzner removal announcement fragments

changelogs/fragments/postgresql-migration.yml
PostgreSQL content migration announcement
Relates to https://github.com/ansible-collections/overview/issues/128#issuecomment-730620706
The template was originally written by @felixfontein 
`changelogs/fragments/postgresql-migration.yml`
=> PostgreSQL content migration announcement

.github/BOTMETA.yml
Relates to https://github.com/ansible-collections/community.general/pull/773
BOTMETA.yml: Add a new maintainer of parted module
=> BOTMETA.yml: Add a new maintainer of parted module

changelogs/fragments/1307-macports-fix-status-check.yml, plugins/modules/packaging/os/macports.py, tests/unit/plugins/modules/packaging/os/test_macports.py, tests/unit/plugins/modules/packaging/os/test_redhat_subscription.py
Fixes #1307: MacPorts fails to install package whose name is contained within already installed package
Instead of using `grep` on full list of installed packages, have macports filter to only the requested package and then use native python to search the output for a match.
plugins/modules/packaging/os/macports.py
See #1307 for more info about the problem. Here's more info about suggested solution:
The macports output format looks really stable. According to github blame, it hasn't changed in over a decade:
https://github.com/macports/macports-base/blob/ec8a2bc682c7afbde198aee23a1920557721b508/src/port/port.tcl#L3320-L3323
Instead of this approach, I considered just changing the `grep` pattern. I think it is preferable to eliminate the `use_unsafe_shell=True` flag, …
=> Fix macports package present/active detection

changelogs/fragments/891-packet_net-fix-not-subscriptable.yaml, scripts/inventory/packet_net.py
I fixed the broken inventory script for [packet_net.py](https://github.com/ansible-collections/community.general/blob/905239f530b712c3609ef375a2587dfe48d0a846/scripts/inventory/packet_net.py), and I have no idea why it was broken before (I am not the creator), but it appeared that it needed a dictionary object (or subscriptable object (don't know what that means, but looked it up [here](https://stackoverflow.com/questions/216972/what-does-it-mean-if-a-python-object-is-subscriptable-or-not)) and the object had a built in function called `__dict__` (which I figured out by importing the `python-packet` package (`import packet`) and did a `help(packet.OperatingSystem)` in python). So, I added that to the objects and the script worked... :slightly_smiling_face:  …
=> adding fix for packet_net.py

plugins/modules/cloud/spotinst/spotinst_aws_elastigroup.py, plugins/modules/cloud/univention/udm_share.py, plugins/modules/net_tools/nios/nios_host_record.py, plugins/modules/storage/zfs/zfs_facts.py, plugins/modules/storage/zfs/zpool_facts.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Tidy up on sanity tests' ignore files, removing lines with validation-modules for these modules.
The focus was to pass the tests so no code was changed other than adjusting argument_spec for missing types or inconsistencies with the docs. The priority has been not to change any functionality, but to ensure that code and docs are synchronized.
Some lines were added back to the files, but a total of 17 lines were removed (among 2.9, 2.10 and 2.11).
plugins/modules/storage/zfs/zpool_facts.py
plugins/modules/storage/zfs/zfs_facts.py
plugins/modules/net_tools/nios/nios_host_record.py
plugins/modules/cloud/univention/udm_share.py
plugins/modules/cloud/spotinst/spotinst_aws_elastigroup.py
=> Tidy up validate-modules nonexistent-parameter-documented

.github/BOTMETA.yml
BOTMETA.yml: add a maintainer for pagerduty_user module
Relates to https://github.com/ansible-collections/community.general/pull/1025
BOTMETA.yml
=> BOTMETA.yml: add a maintainer for pagerduty_user module

changelogs/fragments/1399-fixed-wrong-elements-type.yaml, plugins/modules/cloud/xenserver/xenserver_guest.py, plugins/modules/identity/ipa/ipa_hbacrule.py, plugins/modules/identity/keycloak/keycloak_client.py, plugins/modules/identity/keycloak/keycloak_clienttemplate.py, plugins/modules/net_tools/nios/nios_fixed_address.py, plugins/modules/net_tools/nios/nios_host_record.py, plugins/modules/net_tools/nios/nios_member.py, plugins/modules/net_tools/nios/nios_network.py, plugins/modules/net_tools/nios/nios_nsgroup.py, plugins/modules/net_tools/nios/nios_zone.py, plugins/modules/remote_management/redfish/redfish_config.py, plugins/modules/source_control/github/github_webhook.py, plugins/modules/web_infrastructure/sophos_utm/utm_proxy_exception.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt
Tidy up on sanity tests' ignore files, removing lines with validation-modules for these modules.
The focus was to pass the tests so no code was changed other than adjusting argument_spec for missing types or inconsistencies with the docs. The priority has been not to change any functionality, but to ensure that code and docs are synchronized.
Some lines were added back to the files, but a total of 26 lines were removed (among 2.9, 2.10 and 2.11).
plugins/modules/web_infrastructure/sophos_utm/utm_proxy_exception.py
plugins/modules/source_control/github/github_webhook.py
plugins/modules/remote_management/redfish/redfish_config.py
plugins/modules/net_tools/nios/nios_nsgroup.py
plugins/modules/net_tools/nios/nios_network.py
plugins/modules/net_tools/nios/nios_member.py …
=> Tidy up validate-modules:doc-elements-mismatch

plugins/modules/packaging/os/mas.py
I think most people uses homebrew to install mas-cli. In this case, mas is installed in /usr/local/bin but Ansible doesn't find it when ssh connection is used.
Added example shows how to configure environment to workaround the issue.
I've tested with:
- macOS 10.15.7 (Catalina)
- macOS 11.0.1 (Big Sur)
mas
Without custom environment, error is: 
```yaml
failed: [targethost] (item=413857545) =>
{ ansible_loop_var: item
changed: false
item: 413857545
msg: Required `mas` tool is not installed }
```
=> mas : Add example using PATH: /usr/local/bin

changelogs/fragments/335-icinga2_host-return-error-code.yaml, plugins/modules/monitoring/icinga2_host.py
Currently the module tries to return the `data`, which can result in a blank message instead of the code being shown.
```
"msg": "bad return code creating host: "
```
icinga2_host.py
Trying to access an API with invalid cert and `validate_certs` set to `no` will reproduce this.
=> [icinga2_host.py] Actually return codes instead of data

.github/BOTMETA.yml
See https://github.com/ansible-collections/community.general/pull/1330 for details.
=> Remove adejoux as maintainer from aix_lvol

plugins/modules/packaging/os/yum_versionlock.py, plugins/modules/yum_versionlock.py, tests/integration/targets/yum_versionlock/aliases, tests/integration/targets/yum_versionlock/tasks/main.yml
This module adds support to lock packages in their version to prevent these from updating by yum.
This has been first implemented by @florianpaulhoberg in https://github.com/ansible/ansible/pull/41778 and then copied to https://github.com/ansible-collections/community.general/pull/324, but didn't finish there.
I'm going to add some integration tests to this and hopefully this time the module will get merged :)
=> yum_versionlock: new module

changelogs/fragments/320_unsafe_text.yml, plugins/filter/json_query.py
jmespath library does not undestand custom string types
such as AnsibleUnicode, and AnsibleUnsafeText.
So user need to use ``to_json | from_json`` filter while using
functions like ``starts_with`` and ``contains`` etc.
This hack will allow user to get rid of this filter.
Fixes: #320
changelogs/fragments/320_unsafe_text.yml
plugins/filter/json_query.py
=> json_query: Handle AnsibleUnicode, AnsibleUnsafeText

tests/integration/targets/zypper_repository/aliases
They are currently failing since ~yesterday: https://app.shippable.com/github/ansible-collections/community.general/runs/5783/45/tests https://app.shippable.com/github/ansible-collections/community.general/runs/5783/46/tests
=> Temporarily disable zypper_repository tests.

changelogs/fragments/1436-mas-fix-no-app-installed.yml, plugins/modules/packaging/os/mas.py
All details are in issue #1435
=> Fix #1435: mas : Fix "invalid literal" when no app

tests/integration/targets/zypper_repository/aliases, tests/integration/targets/zypper_repository/tasks/test.yml, tests/integration/targets/zypper_repository/tasks/zypper_repository.yml
Fixes #1446
It seems that https://en.opensuse.org/Additional_package_repositories#Apache_modules Tumbleweed version is missing.
Maybe it's temporary but I guess this change is OK to test the module.
=> zypper_repository: fix broken tests

changelogs/fragments/1426-nmcli-add-zone-parameter.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Add support of connection.zone to nmcli.
This is similar to: `nmcli connection profile modify connection.zone zone_name`.
Fixes #949.
nmcli
=> nmcli: add connection.zone parameter

changelogs/fragments/gluster-deprecation.yaml, meta/runtime.yml, plugins/modules/storage/glusterfs/gluster_heal_info.py, plugins/modules/storage/glusterfs/gluster_peer.py, plugins/modules/storage/glusterfs/gluster_volume.py, tests/sanity/ignore-2.9.txt
The gluster_* modules have been in gluster.gluster for some time (https://github.com/ansible-collections/community.general/issues/761), that collection has been included since Ansible 2.10.0 (https://github.com/ansible-community/ansible-build-data/commit/f73bb171fc3eb2ee6cf61d0d337e5ece4a8ca4e8#diff-d4908359527020805b8e055ee817d68b049157109fc2516d2a9f76c32384b58d), and since ansible-base 2.10.1 the short names redirect to gluster.gluster (https://github.com/ansible/ansible/pull/71240, https://github.com/ansible/ansible/pull/71264). So it's time to deprecate the modules here (for community.general 2.0.0), with removal for 3.0.0 (a bit shorter than our usual deprecation period, but I think it's ok since it mostly affects Ansible 2.9 users), and redirect users to the gluster.gluster …
=> Deprecate gluster_* modules

changelogs/fragments/fix_parsing_array_values_in_osx_defaults.yml, plugins/modules/system/osx_defaults.py, tests/integration/targets/osx_defaults/tasks/main.yml
Unquote values and unescape double quotes when reading array values from osx defaults.
When reading array values from defaults on osx, some value may be double-quoted.
But osx_defaults module do not unquote them currently.
In some cases, array_add option may not idempotent because of this.
Additionally, double quotes in the value is escaped like `\\"`.
They also should be unescaped.
osx_defaults
For example, the task below adds value every time even if the value is already added.
```
- osx_defaults:
domain: com.apple.systemuiserver
key: menuExtras
value:
- '/System/Library/CoreServices/Menu Extras/Volume.menu'
type: array
array_add: yes
```
Values read from osx is double-quoted, and it's different from the value in task(not quoted).
So ansible always try to add the …
=> Bugfix: Fix parsing array values from osx_defaults

changelogs/fragments/1462-splunk-millisecond.yaml, plugins/callback/splunk.py, tests/unit/plugins/callback/test_splunk.py
This change adds millisecond granularity to the timestamp data in the event. Multiple fast-resolving tasks can be executed in the same second and without millisecond granularity Splunk could display these events in an incorrect order, which could lead to some confusion when looking at the events.
Splunk plugin
```paste below
```
=> Add millisecond data to splunk callback timestamp

changelogs/fragments/1419-xfconf-return-values.yaml, plugins/modules/system/xfconf.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt, tests/unit/plugins/modules/system/test_xfconf.py
In #1322 #1305 it looks like we long returning values that are called out in the documentation. Also, the test coverage has a logic bug that would cause this case to not get exercised in the tests.
Changes:
* Add return values by calling `update_xfconf_output()` at appropriate times to match documentation
* Update `RETURNS` documentation to reflect returning either scalar `str` or `list(str)` in `value` and `value_type`
* Fix logical bug in test to cover `value`, `msg`, and `previous_value` in the case where they are not in `result` but should be
* Add coverage for return values of `value_type`.
* Fix test data to match documentation of returning `previous_value = None` in some cases.
Fixes #1418 
Using the following task:
```yaml
- …
```
=> xfconf: add return values and expand test coverage

changelogs/fragments/1484-fix-property-name-in-redfish-memory-inventory.yml, plugins/module_utils/redfish_utils.py
The method `get_memory_inventory()` in redfish_utils.py has a typo in one of the property names: `PartNuber` should be `PartNumber`. With the misspelled property name, the `PartNumber` will not be shown in the memory inventory.
Fixes #1483 
Run a play to issue the `GetMemoryInventory` command. Note that the `PartNumber` property is not shown in the output.
After the fix, the `PartNumber` property is shown in the output.
=> Fix property name typo in get_memory_inventory()

changelogs/fragments/331_keycloak.yml, plugins/module_utils/identity/keycloak/keycloak.py
When user provides auth URL value which does not startswith
http or https protocol schema, provide a meaningful error message
stating so.
Fixes: #331
changelogs/fragments/331_keycloak.yml
plugins/module_utils/identity/keycloak/keycloak.py
=> keycloak: Provide meaningful error message to user

changelogs/fragments/nios_host_record-fix-aliases-removal.yml, plugins/module_utils/net_tools/nios/api.py
fix so module `nios_host_record` can remove aliases
nios_host_record
Fix for https://github.com/ansible-collections/community.general/issues/1335
I couldn't find any other module in https://github.com/ansible-collections/community.general/tree/main/plugins/modules/net_tools/nios with another argument named `aliases` so this change should only affect module `nios_host_record`
=> fix so module `nios_host_record` can remove aliases

plugins/modules/datadog_downtime.py, plugins/modules/monitoring/datadog/datadog_downtime.py, tests/unit/plugins/modules/monitoring/test_datadog_downtime.py, tests/unit/requirements.txt
Managing downtimes with the current datadog_monitor module is not really practical and the recommended solution anymore.
This adds the downtime module for managing monitor downtimes
`datadog_downtime`
=> Add downtime module

changelogs/fragments/1472-saltstack-fix-put_file-to-preserve-checksum.yml, plugins/connection/saltstack.py
Use hashutil.base64_decodefile to ensure that the file checksum
is preserved, since file.write only supports text files. This solves
ansible copy module failure triggered when the checksum is not
preserved. For example, if the content parameter is an empty
string, then the checksum fails to match because the file.write
function always appends a newline.
saltstack
```json
$ ansible myhost -c saltstack -m ansible.builtin.copy -a "content= dest=/tmp/empty-file.txt"
myhost | FAILED! => {
"checksum": "adc83b19e793491b1c6ea0fd8b46cd9f32e592fc",
"expected_checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
"msg": "Copied file does not match the expected checksum. Transfer failed."
}
```
=> saltstack: fix put_file to preserve checksum

changelogs/fragments/630-git_config-handling-invalid-dir.yaml, plugins/modules/source_control/git_config.py
Try to use the parameter ``ignore_invalid_cwd=True`` on the call to ``module.run_command()``, available from ansible base 2.10.4 onwards.
Fixes #630 
plugins/modules/source_control/git_config.py
=> Raises error for non-existent repo path

plugins/modules/cloud/misc/proxmox_snap.py, plugins/modules/proxmox_snap.py, tests/unit/plugins/modules/cloud/misc/test_proxmox_snap.py
This commit adds proxmox_snap for snapshot management on PVE, previously worked on in #535 
This is that same module on a new branch (a lot of time passed and I messed up my git checkouts :-) )
proxmox_snap: based on 'proxmox', adapted to manage snapshots for LXC/Qemu machines (OpenVZ might work, but I didn't test it as it is no longer supported in PVE)
Status: fully functional, lacks tests
proxmox_snap
=> New module: proxmox_snap

changelogs/fragments/1527-fix-nios-api-member-normalize.yaml, plugins/module_utils/net_tools/nios/api.py
Force a copy of the member_spec dict keys to allow change during iteration.
Fixes #1526 
nios_member
The nios_member module uses a method in `plugins/module_utils/net_tools/nios/api.py` to normalise the request data attributes.  However this method tries to modify the `member_spec` dictionary whilst iterating the same dict.
This is not permitted in Python 3.
This PR changes to use a copy of the dict keys, rather than a iter.
```paste below
```
=> nios_member: fix nios api member_normalize error with python 3

changelogs/fragments/1413-proxmox-features.yml, plugins/modules/cloud/misc/proxmox.py
Adds the `features` flag to pass to ProxMox LXC
- Fixes #816, proxmox lxc - add features (nesting, nfs, cifs...) 
https://github.com/ansible-collections/community.general/blob/main/plugins/modules/cloud/misc/proxmox.py
Containers in Proxmox-LXC has a features string one can set to enable specific things such as container nesting, NFS, CIFS, FUSE, etc. This patch allows the ansible role to pass that feature string to Proxmox in raw form. The user of this role must understand which flags are compatible with each other and how to pass them.
=> Proxmox - add `features` flag

changelogs/fragments/1555-ipa-sudorule-add-commandgroup.yml, plugins/modules/identity/ipa/ipa_sudorule.py
Added code to support command groups inside sudo rules (Fixes #1555)
ipa_sudorule.py
Free IPA API allows sudo rules to use sudo command groups. However, the current version of the module allows only for a list of commands, not command groups. This update allows for also using command groups (which by the way can be created using an existing module: plugins/modules/identity/ipa/ipa_sudocmdgroup.py)
=> Added code to support command groups inside sudo rules

changelogs/fragments/1552_launchd.yml, plugins/modules/system/launchd.py
* readPlist and writePlist are deprecated from plistlib.
Handle this in the module code.
Fixes: #1552
changelogs/fragments/1552_launchd.yml
plugins/modules/system/launchd.py
=> launchd: Handle deprecated APIs in plistlib

changelogs/fragments/remove-ansible.netcommon-dependency.yml, galaxy.yml, plugins/modules/net_tools/nios/nios_network.py, tests/requirements.yml, tests/utils/shippable/shippable.sh
Since it is not clear whether the nios modules are actually removed before 2.0.0 is released, I've created this small PR which vendors the two ansible.netcommon functions used in the nios_network module.
The functions are pretty simple and the module itself will hopefully be removed in the near future anyway, so I don't see much problem with replicating the code in this collection.
collection
nios_network
=> Remove ansible.netcommon dependency

changelogs/fragments/1481-deprecated-brew-cask-command.yaml, plugins/modules/packaging/os/homebrew_cask.py, tests/unit/plugins/modules/packaging/os/test_homebrew_cask.py
Replaced deprecated `brew cask` commands with `--cask` (e.g `brew install --cask <app>`)
See https://brew.sh/2020/12/01/homebrew-2.6.0/ & https://github.com/Homebrew/brew/pull/8899
Fixes #1524.
plugins/modules/homebrew_cask.py
```paste below
```
=> updated deprecated homebrew cask commands

changelogs/fragments/47680_pam_limits.yml, plugins/modules/system/pam_limits.py
Migrated from ansible/ansible#47680
Based upon the work of pgerber
Unlike all other limits, nice and priority must have a value between -19 and 20 and -1,
unlimited and infinity are unsupported. See limits.conf(5) for details.
changelogs/fragments/47680_pam_limits.yml
plugins/modules/system/pam_limits.py
=> pam_limits: add support nice and priority limits

plugins/inventory/online.py
Online SAS is rebranded as Scaleway in 2015. Updated
inventory documentation for the same.
Fixes: #814
plugins/inventory/online.py
=> Scaleway: Update documentation

changelogs/fragments/470-spacewalk-legacy-python-certificate-validation.yaml, plugins/modules/packaging/os/rhn_channel.py
Fix Python 2.7.5 problem with ssl certificate validation.
See: https://github.com/ansible-collections/community.general/pull/79
plugins/modules/packaging/os/rhn_channel.py
=> Legacy Python certificate validation fixed

changelogs/fragments/1517-bridge-slave-from-list-of-ip-based-connections.yml, plugins/modules/net_tools/nmcli.py
…since nmcli does not accept IP options for bridge-slave connections.
The nmcli does not accept IP based options that automatically get injected for bridge-slave connection type. 
Fixes #1500.
nmcli
=> Remove bridge-slave from list of IP based connections

changelogs/fragments/1532-monit-support-all-services.yaml, plugins/modules/monitoring/monit.py, tests/unit/plugins/modules/monitoring/test_monit.py
The changes introduced by @snopoke [here](https://github.com/ansible-collections/community.general/pull/1107) did not include support for other [monit service checks](https://mmonit.com/monit/documentation/monit.html#Service-checks) besides "Process". Other service checks return a process status of "missing".
This change checks the output of `monit validate <name>` or `monit status <name>` for all of the potential monit service checks. I've tested this locally when running the "File" service check and it works as expected. The "File" service check is also how I noticed the issue in the first place. 
The unit test assumes the text returned from other service checks based on the pattern observed in the "Process" and "File" service checks. To be safe, this was my reasoning for ignoring case …
=> monit: add support for all monit services when checking process state

changelogs/fragments/1394-pamd-removing-comments.yaml, plugins/modules/system/pamd.py
- The module was searching back (and forward, in the ``after`` state) for lines that were not comments, assuming it would be a valid rule or an include.
Fixes #1394 
pamd
=> pamd - fixed bug

changelogs/fragments/1493-fix_passwordstore.py_to_be_compatible_with_gopass_versions.yml, plugins/lookup/passwordstore.py
`gopass show` is deprecated and executing it will result in these messages:
```
gopass mypass
DEPRECATION WARNING: Use gopass show
mysecret
```
The `DEPRECATION WARNING: Use gopass show` will be written to a file looked up by `passwordstore.py`.
This commit fixes it by using `pass show` instead of `pass`.
passwordstore.py
=> fix passwordstore.py to be compatible with gopass versions

changelogs/fragments/1574-make-question.yaml, plugins/modules/system/make.py
Platforms that do not use GNU ``make`` (why oh why) will not recognize the long option ``--question`` for check mode. Must use ``-q`` instead.
plugins/modules/system/make.py
=> changed make parameter from --question to -q

plugins/connection/lxd.py
… plugin
For https://github.com/ansible-collections/community.general/issues/1441
Add support for specifying remote and project in the LXD connection plugin.
community.general.lxd
Tested the PR as below:
~~~
root@lxd:~# lxc --version
4.0.4
root@lxd:~# lxc remote list
+-----------------+------------------------------------------+---------------+-------------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    |  AUTH TYPE  | PUBLIC | STATIC |
+-----------------+------------------------------------------+---------------+-------------+--------+--------+
| images          | https://images.linuxcontainers.org       | simplestreams | none        | YES    | NO     |
+-----------------+------------------------------------------+--- …
=> Added support for remote project in the LXD connection plugin

changelogs/fragments/google-migration.yml, changelogs/fragments/hashi_vault-migration.yml, changelogs/fragments/oc-migration.yml
See ansible-collections/overview#128.
changelog
=> [stable-1] Add OC, hashi_vault and Google removal announcements

tests/integration/targets/connection_chroot/aliases
Fixes #1017.
tests/integration/targets/connection_chroot/aliases
=> chroot: clarify disabling of connection chroot tests on macos

plugins/modules/identity/ipa/ipa_pwpolicy.py, plugins/modules/ipa_pwpolicy.py, tests/unit/plugins/modules/identity/ipa/test_ipa_pwpolicy.py
Add a module for modifying FreeIPA password policies
ipa_pwpolicy
The module is based heavily on the existing IPA modules, and extends the base IPA arguments/documentation
A couple considerations:
- The arguments all use the raw LDAP name, which are pretty long, eg `krbpwdfailurecountinterval`. I added shorter aliases based on the `ipa` command that are easier to use.
I did it this way because this is how the existing IPA modules do it, but I can change the default name to the shorter versions if preferred.
- All of the arguments are strings instead of integers because they're passed directly to the IPA web API, which stores them as strings. I can switch them to integers if preferred.
=> Add ipa_pwpolicy module

tests/integration/targets/connection_chroot/aliases
Backport of #1591 to stable-1.
chroot tests
=> [stable-1] chroot: re-enable connection chroot tests (#1591)

plugins/modules/packaging/os/rpm_ostree_pkg.py, plugins/modules/rpm_ostree_pkg.py, tests/unit/plugins/modules/packaging/os/test_rpm_ostree_pkg.py
Added functionality to manage overlay packages using
rpm-ostree command.
Signed-off-by: Dusty Mabe <dusty@dustymabe.com>
changelogs/fragments/rpm_ostree_package_manager.yml
plugins/modules/packaging/os/rpm_ostree_pkg.py
=> rpm_ostree_pkg: new module

changelogs/fragments/1590-influxdb-shard-group-duration-parameter.yml, plugins/modules/database/influxdb/influxdb_retention_policy.py
For https://github.com/ansible-collections/community.general/issues/529
Adds the shard_group_duration parameter
influxdb_retention_policy.py
~~~
- name: test influxdb retention policy
collections:
- community.general
tasks:
- name: create retention policy
community.general.influxdb_retention_policy:
hostname: localhost
password: redhat
username: ishwar
port: 8086
database_name: awx
policy_name: awx
replication: 1
default: true
duration: 10w
shard_group_duration: 1d
~~~
With shard_group_duration: 1d
~~~
ansible-playbook 2.10.4
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = …
=> Added shard_group_duration to influxdb_retention_policy module

changelogs/fragments/snmp_facts.yml, plugins/modules/net_tools/snmp_facts.py
**SECURITY** - CVE-2021-20178
Hide user sensitive information like `privkey` and `authkey`
while logging in console.
changelogs/fragments/snmp_facts.yml
plugins/modules/net_tools/snmp_facts.py
=> snmp_facts: Hide user sensitive information in console

changelogs/fragments/1411_homebrew_tap.yml, plugins/modules/packaging/os/homebrew_tap.py
* When module fails return meaningful error message to user
returned by homebrew-tap command.
* Doc update
Fixes: #1411
changelogs/fragments/1411_homebrew_tap.yml
plugins/modules/packaging/os/homebrew_tap.py
=> homebrew_tap: Return error message to user

changelogs/fragments/1620-terraform_init_reconfigure_fix.yml, plugins/modules/cloud/misc/terraform.py
If parameter `init_reconfigure` is true, the task fails because it runs terraform as:
`terraform init -input=false - r e c o n f i g u r e`
Ansible `module.run_command` expects an array of strings.
How to reproduce
```paste below
---
tasks:
- community.general.terraform:
project_path: "/tmp/tf-test"
force_init: true
init_reconfigure: true
mkdir /tmp/tf-test
ansible-playbook test.yml
```
=> init_reconfigure fails on module cloud/misc/terraform.py

changelogs/fragments/cve_bitbucket_pipeline_variable.yml, plugins/modules/source_control/bitbucket/bitbucket_pipeline_variable.py
**SECURITY** - CVE-2021-20180
Hide user sensitive information which is marked as ``secured``
while logging in console.
changelogs/fragments/cve_bitbucket_pipeline_variable.yml
plugins/modules/source_control/bitbucket/bitbucket_pipeline_variable.py
=> bitbucket_pipeline_variable: Hide secured values in console log

changelogs/fragments/1550-add-jobs-parameter-to-make.yml, plugins/modules/system/make.py
I added this to allow use of the -j or --jobs argument for make/gmake. If hardware supports multiple jobs this significantly speeds up compile time
community.general.make
I kept my changes to a minimum focused only on adding and documenting the new parameter. I refactored the existing file parameter since it was also a commandline argument to make/gmake. I tried to add appropriate comments to the code as well.
=> added jobs parameter to make module

changelogs/fragments/1549-add-tag-filter-to-linode-inventory.yml, plugins/inventory/linode.py, tests/unit/plugins/inventory/test_linode.py
This adds a ``tags`` option to the linode inventory plugin to filter instances
Fixes #1549 
inventory plugin linode
Use the tags option like the regions or types option to filter the returned nodes
=> Add tags filter to linode inventory plugin

changelogs/fragments/1610-bugfix-onepassword-lookup-plugin.yaml, plugins/lookup/onepassword.py
With the command line utility `op` version 1.8, the password field exists, while the fields list is empty.  This will look for the desired field without it being listed in the fields list.
When using the onepassword lookup plugin, passwords were being sent back as empty even if the record was found.  I found it was because the fields list returned empty, even though the password key existed in the item's details.
this is for the onepassword lookup plugin
In summary the password would return as an empty string instead of the value from 1P.
=> onepassword: find the password field out of the fields list

changelogs/fragments/1632-using_check_rc_in_terraform.yml, plugins/modules/cloud/misc/terraform.py
The terraform module has code which just checks if the return code has failed. Then prints just the error message. Though this doesn't show the format of the command that was run. See https://github.com/ansible-collections/community.general/pull/1629 as an example of an issue that can occur with the format of the command.
This PR uses the underlying ansible module's run_command to check the rc which will print the command that was run when a failure occurs.  
=> Fixing return code not showing the command that fails in terraform.

changelogs/fragments/lldp-use-get_bin_path-to-locate-the-lldpctl-executable.yaml, plugins/modules/net_tools/lldp.py
Use get_bin_path to locate the lldpctl executable.
This prevents failures [1] on hosts that have lldpd installed and running but
where the PATH directories haven't been hashed recently. With this patch
the full pathname of the lldpctl will be used to avoid potential hashing issues
(typically /sbin/lldpctl will be used).
References:
1 - Failures seen:
FAILED! => {"changed": false, "cmd": "lldpctl -f keyvalue",
"msg": "[Errno 2] No such file or directory", "rc": 2}
lldp
Tested against:
* Linux servers running CentOS 7 and 8, and
* Mellanox switch running Cumulus Linux 4.2
=> lldp - use get_bin_path to locate the lldpctl executable

changelogs/fragments/1491-gitlab-runner-owned-parameter.yml, plugins/modules/source_control/gitlab/gitlab_runner.py, tests/unit/plugins/modules/source_control/gitlab/gitlab.py, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_runner.py, tests/unit/requirements.txt
This change adds an 'owned' option to gitlab_runner to toggle between the `runners/` and `runners/all` API methods and allow non-admins to use it. It also cleans up the runner tests which were hitting the wrong mocks. Fixes #440, #484
gitlab_runner
See #440 for a description of the problem
=> Allow gitlab_runner to function for non-admin users

changelogs/fragments/1589-passwordstore-fix-passwordstore.py-to-be-compatible-with-gopass.yaml, plugins/lookup/passwordstore.py
...even when used with create=true.
The same output snippet matches for both, `pass` and `gopass`, but while `pass` returns `1` on a non-existant password, `gopass` returns `10`, or `11`, depending on whether a similar named password was stored.
So I'd propose to change `e.returncode == 1` to `e.returncode != 0` to cover both cases here.
What do you think?
./plugins/lookup/passwordstore.py
In a module fall like the following:
```yaml
- debug:
msg: "{{ lookup('passwordstore', 'test create=true nosymbols=true') }}"
```
Everything works with pass, but with gopass the new password is created but the ansible module call fails because it's return code is unexpected
=> fix passwordstore.py to be compatible with gopass.

changelogs/fragments/1654-dnsmadeeasy-http-400-fixes.yaml, plugins/modules/net_tools/dnsmadeeasy.py
* When creating a record the module fails on monitor API call
* TXT records are surrounded by quotes in the API response
Fixes: #1237
dnsmadeeasy
=> dnsmadeeasy: Fix HTTP 400 errors when creating a TXT record

changelogs/fragments/community.docker-73-docker_image-fix-old-docker-py-version.yml, plugins/modules/cloud/docker/docker_image.py, tests/integration/targets/docker_image/tasks/tests/options.yml
Backport of https://github.com/ansible-collections/community.docker/pull/73 to stable-1.
docker_image
=> [stable-1] docker_image: do not crash in load_image for docker-py < 2.5.0.

changelogs/fragments/1679-homebrew_search_path.yml, plugins/modules/packaging/os/homebrew.py, plugins/modules/packaging/os/homebrew_cask.py, plugins/modules/packaging/os/homebrew_tap.py
Add default search path for `brew` on Apple silicon hardware per https://docs.brew.sh/Installation
Fixes: #1660
- homebrew
- homebrew_cask
- homebrew_tap
=> Add default `brew` search path for non-Intel / Apple silicon hardware

changelogs/fragments/community.docker-76-leading-v-support-in-docker-version.yml, plugins/connection/docker.py
Backport of https://github.com/ansible-collections/community.docker/pull/76 to stable-1.
plugins/connection/docker.py
=> [stable-1] docker.py: allow docker versions beginning with 'v'

changelogs/fragments/1691-add-name-and-id-props-to-redfish-inventory-output.yml, plugins/module_utils/redfish_utils.py
Most of the resource inventory commands show the standard `Id` and `Name` properties in the output. But a few of the commands did not (`GetSystemInventory`, `GetNicInventory`, etc.).
This fix updates the commands to include the `Name` and/or `Id` properties in the output, if appropriate.
Fixes #1650 
Run a play like this:
```
command: GetNicInventory
```
Notice that the output does not include the `Name` or `Id` properties.
**Before:**
```paste below
{
"redfish_facts": {
"nic": {
"entries": [
[
{
"resource_uri": "/redfish/v1/Systems/437XR1138R2"
},
[
{
"Description": "System NIC 1",
"FQDN": "web483.contoso.com",
"IPv4Addresses": [
{
"Address": "192.168.0.10", …
```
=> Add Name and/or Id properties to resource inventory output

changelogs/fragments/1702_homebrew_tap.yml, plugins/modules/packaging/os/homebrew_tap.py
User can specify search path for brew executable.
Fixes: #1702
changelogs/fragments/1702_homebrew_tap.yml
plugins/modules/packaging/os/homebrew_tap.py
=> homebrew_tap: Add support for brew search path

changelogs/fragments/1703-sensu_silence-fix_json_parsing.yml, plugins/modules/monitoring/sensu/sensu_silence.py
`sensu_silence` is broken on Python3 and shows unexpected behavior on silencing, as well as on unsilencing. This is caused by a missing cast from bytestream to string. JSON parser is failing in consequence, resulting in errors when comparing target state with current state.
In consequence, on `state: present` states gets changed on every Ansible run and checks gets always silenced (again). On `state: absent` checks gets never unsilenced.
`community.general.sensu_silence`
Before:
```paste below
{"changed": true, "invocation": {"module_args": {"creator": "account-admin-ansible", "check": null, "reason": "running deployment", "expire": null, "url": "http://127.0.01:4567", "expire_on_resolve": null, "subscription": "client:accountadmin-staging-app-00", "state": …
```
=> sensu-silence: fix json parsing of sensu API response

changelogs/fragments/CVE-2021-20191_no_log.yml, plugins/module_utils/_netapp.py, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/web_infrastructure/sophos_utm/utm_proxy_auth_profile.py
This will prevent potentially sensitive information from being printed to the console.
See: CVE-2021-20191
=> Add no_log to some module arguments

changelogs/fragments/CVE-2021-20191_no_log_docker.yml, plugins/modules/cloud/docker/docker_swarm.py
This will prevent accidental disclosure.
See: CVE-2021-20191
Backport from community.docker: https://github.com/ansible-collections/community.docker/pull/80
=> [stable-1] docker swarm - Add no_log to the signing_ca_key argument

changelogs/fragments/1695-parted-updatedregex.yaml, changelogs/fragments/813-parted-updatedregex.yaml, plugins/modules/system/parted.py, tests/unit/plugins/modules/system/test_parted.py
Rewrite/extends PR #817 with corrected regex for parted version.
Original PR - Modify 2 regex expressions to support:
1 - Different version strings
2 - Support optional white space between numeral and unit designator in partition size output from parted
Fixes #812
Fixes #813
plugins/modules/system/parted.py
Please see original PR #817 for the discussion. 
Thanks.
PS: someone could help me with a test unit, if it even possible for this module
=> parted: fix regex for version match and partition size output

changelogs/fragments/1723-datadog_monitor-add-missing-monitor-types.yml, plugins/modules/monitoring/datadog/datadog_monitor.py
This PR adds additional Datadog monitor types that were missing from the module: `query alert`, `trace-analytics alert`, `rum alert`
Tested against Datadog
```yaml
- name: Create query Monitors
community.general.datadog_monitor:
api_key: "{{ dd_api_key }}"
app_key: "{{ dd_app_key }}"
type: "query alert"
name: "Ansible Service frontend has a high error rate on env:ruby-shop"
state: "present"
query: "sum(last_10m):( sum:trace.rack.request.errors{env:ruby-shop,service:frontend}.as_count() / sum:trace.rack.request.hits{env:ruby-shop,service:frontend}.as_count() ) > 0.02"
notification_message: "Service frontend on env:ruby-shop has a high error rate."
tags:
- "env:ruby-shop"
- "service:frontend"
thresholds:
warning: "0.01"
critical: "0.02"
- name: Create …
```
=> datadog_monitor: Add missing monitor types query alert, trace-analytics alert, rum alert

tests/utils/constraints.txt
Backport of #1752 to stable-1.
CI
=> [stable-1] Fix CI

changelogs/fragments/1724-various-fixes-for-updating-existing-gitlab-user.yml, plugins/modules/source_control/gitlab/gitlab_user.py, tests/integration/targets/gitlab_user/tasks/main.yml, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_user.py
This PR packs together various bug fixes all related to updating an existing gitlab user. In detail:
1. Makes changes to admin state of user working, which failed before because the attribute key when querying the user object `is_admin` is different from the json payload key needed for setting `admin`
2. Makes user password changes working which were simply ignored before
3. Supports confirmation skipping or more preciesly reconfirmation skipping also for user updates (before it only worked for new users), which according to my experiments is essential when trying to change the user email address
gitlab_user
All these changes made some substantial upgrades necessary for the internal process which handles gitlab user updates. For 1) we needed the possibility to …
=> Various fixes for updating existing gitlab users

plugins/modules/remote_management/ipmi/ipmi_boot.py, plugins/modules/remote_management/ipmi/ipmi_power.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Tidy up validate-modules ignores for remote_management/ipmi modules.
plugins/modules/remote_management/ipmi/ipmi_power.py
plugins/modules/remote_management/ipmi/ipmi_boot.py
=> Tidy up validate-modules ignores for remote_management/ipmi modules

changelogs/fragments/1753-document-fstypes-supported-by-resizefs.yml, plugins/modules/system/filesystem.py, plugins/modules/system/lvol.py
Document which filesystem types are supported by the `resizefs` param of the `lvol` and `filesystem` modules.
- lvol
- filesystem
- Fix `filesystem` documentation claiming that `resizefs` param supports swap filesystem, although this is not the case.
- List filesystem types supported by `resizefs` param in `lvol` module, that differs from `filesystem`'s list.
See also #790
=> document what filesystem types are supported by 'resizefs' option

changelogs/fragments/1475-xfconf-facts.yml, plugins/modules/system/xfconf.py
Added feature flag to disable facts and its associated deprecation warning.
Fixes: #1475 
plugins/modules/xfconf.py
=> xfconf: feature flag to disable facts and deprecation warning

changelogs/fragments/1722_timezone.yml, plugins/modules/system/timezone.py
Fix `timezone` module to work with Alpine and Gentoo linux.
Fixes #781
timezone
Tested with alpine:
```
alpine:~# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.1
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
and Gentoo in a docker container...
PS: completely untested code path with `hwclock` on Gentoo/Alpine
=> timezone: add gentoo and alpine linux support

changelogs/fragments/1744-case-insensitive-hostname-fqdn-matching.yml, plugins/module_utils/redfish_utils.py
If instead of an IP one wants to use FQDN and the case on iLO doesn't match Ansible's {{ baseuri }} case the task will fail.
This PR implements basic case insensitive comparison.
```
- name: Set Manager NIC
community.general.redfish_config:
category: Manager
command: SetManagerNic
nic_config:
DHCPv4:
DHCPEnabled: False
IPv4StaticAddresses:
Address: "{{ ilo.address }}"
Gateway: "{{ ilo.gateway }}"
SubnetMask: "{{ ilo.netmask }}"
baseuri: "{{ ilo.baseuri }}"
```
=> redfish module_utils: case insesitive search for situations where the hostname/FQDN on iLO is in caps

changelogs/fragments/816-only-invocate-feature-when-variable-is-set.yml, plugins/modules/cloud/misc/proxmox.py
- only invoke param feature when variable is set
Fixes #816 
- proxmox
- the param requires root@pam permissions on Proxmox PVE side
- so, it makes only sense to provide this param, when the variable is set, and the user explicitly wants to use this param
- btw.  if feature param is provided with "none", `pct` creates the container but `pct list` on Proxmox PVE side fails. 
> pct list
> vm 103 - unable to parse config: features:
> vm 104 - unable to parse config: features:
> vm 105 - unable to parse config: features:
>
=> only set param features when variable is not empty

changelogs/fragments/1740-aerospike_migration.yml, plugins/modules/database/aerospike/aerospike_migrations.py
Uses `migrate_tx_key` instead of `migrate_rx_key` when populating `namespace_rx`.
aerospike_migration
=> Fix typo in aerospike_migration module

changelogs/fragments/1-community-postgresql_backports.yml, plugins/modules/database/postgresql/postgresql_info.py, plugins/modules/database/postgresql/postgresql_ping.py, plugins/modules/database/postgresql/postgresql_query.py, plugins/modules/database/postgresql/postgresql_set.py, plugins/modules/database/postgresql/postgresql_user.py, tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml, tests/integration/targets/postgresql_set/tasks/main.yml, tests/integration/targets/postgresql_set/tasks/options_coverage.yml, tests/integration/targets/postgresql_set/tasks/postgresql_set_initial.yml
Backports of
https://github.com/ansible-collections/community.postgresql/pull/32
https://github.com/ansible-collections/community.postgresql/pull/46
https://github.com/ansible-collections/community.postgresql/pull/51
https://github.com/ansible-collections/community.postgresql/pull/43
https://github.com/ansible-collections/community.postgresql/pull/42
https://github.com/ansible-collections/community.postgresql/pull/36
https://github.com/ansible-collections/community.postgresql/pull/52
postgresql modules
=> [stable-1] Various backports from community.postgres 

changelogs/fragments/1776-git_config-tilde_value.yml, plugins/modules/source_control/git_config.py, tests/integration/targets/git_config/tasks/main.yml, tests/integration/targets/git_config/tasks/set_value_with_tilde.yml
Prevents `run_command()` from expanding all arguments.
Fixes #1776 
git_config
=> Prevented the expansion of parameters in run_command()

changelogs/fragments/1776-git_config-tilde_value.yml, plugins/modules/source_control/git_config.py, tests/integration/targets/git_config/tasks/main.yml, tests/integration/targets/git_config/tasks/set_value_with_tilde.yml
Backport of #1794 to stable-1.
@russoz I had to manually cherry-pick this, could you please check whether the result is correct?
git_config
=> [stable-1] Prevented the expansion of parameters in run_command()

changelogs/fragments/1765-proxmox-params.yml, plugins/modules/cloud/misc/proxmox.py, plugins/modules/cloud/misc/proxmox_kvm.py, plugins/modules/cloud/misc/proxmox_snap.py, plugins/modules/cloud/misc/proxmox_template.py, plugins/modules/cloud/misc/proxmox_user_info.py
While looking into the code for the purpose of reviewing #1763 , I noticed we could use ``required_if``, ``required_one_of`` and  ``required_together`` for some of the proxmox modules.
plugins/modules/cloud/misc/proxmox_snap.py
plugins/modules/cloud/misc/proxmox_template.py
plugins/modules/cloud/misc/proxmox_user_info.py
=> Improved parameter handling on proxmox modules

tests/integration/targets/django_manage/files/base_test/1045-single-app-project/single_app_project/manage.py, tests/integration/targets/django_manage/files/base_test/simple_project/p1/manage.py, tests/integration/targets/django_manage/files/base_test/simple_project/p1/p1/settings.py, tests/integration/targets/django_manage/files/base_test/simple_project/p1/p1/urls.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Adjusted the tests files to ansible standards.
tests/integration/targets/django_manage/files/base_test/1045-single-app-project/single_app_project/manage.py
tests/integration/targets/django_manage/files/base_test/simple_project/p1/manage.py
tests/integration/targets/django_manage/files/base_test/simple_project/p1/p1/settings.py
tests/integration/targets/django_manage/files/base_test/simple_project/p1/p1/urls.py
=> Adjusted django_manage integration test files to reduce ignore lines in sanity tests

changelogs/fragments/1771-centurylink-validation-elements.yml, plugins/modules/cloud/centurylink/clc_alert_policy.py, plugins/modules/cloud/centurylink/clc_blueprint_package.py, plugins/modules/cloud/centurylink/clc_firewall_policy.py, plugins/modules/cloud/centurylink/clc_loadbalancer.py, plugins/modules/cloud/centurylink/clc_modify_server.py, plugins/modules/cloud/centurylink/clc_publicip.py, plugins/modules/cloud/centurylink/clc_server.py, plugins/modules/cloud/centurylink/clc_server_snapshot.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt
Tidy up validate-modules ignores for cloud/centurylink modules
plugins/modules/cloud/centurylink/clc_server.py
plugins/modules/cloud/centurylink/clc_server_snapshot.py
plugins/modules/cloud/centurylink/clc_publicip.py
plugins/modules/cloud/centurylink/clc_modify_server.py
plugins/modules/cloud/centurylink/clc_loadbalancer.py
plugins/modules/cloud/centurylink/clc_firewall_policy.py
plugins/modules/cloud/centurylink/clc_blueprint_package.py
plugins/modules/cloud/centurylink/clc_alert_policy.py
=> Tidy up validate-modules ignores for cloud/centurylink modules

changelogs/fragments/1771-centurylink-validation-elements.yml, plugins/modules/cloud/centurylink/clc_alert_policy.py, plugins/modules/cloud/centurylink/clc_blueprint_package.py, plugins/modules/cloud/centurylink/clc_firewall_policy.py, plugins/modules/cloud/centurylink/clc_loadbalancer.py, plugins/modules/cloud/centurylink/clc_modify_server.py, plugins/modules/cloud/centurylink/clc_publicip.py, plugins/modules/cloud/centurylink/clc_server.py, plugins/modules/cloud/centurylink/clc_server_snapshot.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt
Backport of #1771 to stable-1.
plugins/modules/cloud/centurylink/clc_server.py
plugins/modules/cloud/centurylink/clc_server_snapshot.py
plugins/modules/cloud/centurylink/clc_publicip.py
plugins/modules/cloud/centurylink/clc_modify_server.py
plugins/modules/cloud/centurylink/clc_loadbalancer.py
plugins/modules/cloud/centurylink/clc_firewall_policy.py
plugins/modules/cloud/centurylink/clc_blueprint_package.py
plugins/modules/cloud/centurylink/clc_alert_policy.py
=> [stable-1] Tidy up validate-modules ignores for cloud/centurylink modules

changelogs/fragments/1714-gitlab_runner-required-reg-token.yml, plugins/modules/source_control/gitlab/gitlab_runner.py
registration_token is no longer required
Fixes #1714 
gitlab_runner
=> Implemented fix pointed in issue

changelogs/fragments/1721-fix-nomad_job_info-no-jobs-failure.yml, plugins/modules/clustering/nomad/nomad_job_info.py
If a nomad cluster has no jobs and we try to list its jobs the module crashes because the returned value of `nomad_client.jobs.get_jobs()` and thus it will be no iteration and result will never be initialized/declared, however the module will try to use it later on.
Result not being declared outside loop:
https://github.com/ansible-collections/community.general/blob/2297f2f802f286abdc76bbae0c9d3aae44255554/plugins/modules/clustering/nomad/nomad_job_info.py#L317-L320
Trying to return result even when it's not declared.
https://github.com/ansible-collections/community.general/blob/2297f2f802f286abdc76bbae0c9d3aae44255554/plugins/modules/clustering/nomad/nomad_job_info.py#L336
plugins/modules/clustering/nomad/nomad_job_info.py
The change is just to initialize the result …
=> Fix undeclared result for nomad_job_info module

changelogs/fragments/1715-proxmox_kvm-add-vmid-to-returns.yml, plugins/modules/cloud/misc/proxmox_kvm.py
Also added in the docs promised return of MAC and devices when state ==
current.
Added the requested return values to the module.
Fixes: #1410 
proxmox_kvm
```
TASK [Get vm] ********************************************************************************************************
task path: /root/projects/playground/playbooks/proxmox_kvm.yml:6
[DEPRECATION WARNING]: The proxmox_default_behavior option will change its default value from "compatibility" to 
"no_defaults" in community.general 4.0.0. To remove this warning, please specify an explicit value for it now. This 
feature will be removed from community.general in version 4.0.0. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ok: [localhost] => changed=false …
```
=> Added VMID to all returns

changelogs/fragments/1788-ease-nios_host_record-dns-bypass-check.yml, plugins/module_utils/net_tools/nios/api.py
DNS bypass should be allowed when `configure_dns` is `false` and `view` is set other than default.
Fixes #1786 
`community.general.nios_host_record`
Removal of the limiting check.
After removal results are as expected (as opposed to those in the Issue)
```
changed: [xxxxx] => changed=true
invocation:
module_args:
aliases: null
comment: null
configure_for_dns: false
dns_view: default.my-custom-view
extattrs: null
ipv4:
- add: null
address: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
configure_for_dhcp: false
ipv4addr: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
mac: null
remove: null
ipv4addrs:
- add: null
address: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
configure_for_dhcp: false
ipv4addr: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
mac: null
remove: null
ipv6addrs: null
name: testi_vm
provider: …
```
=> ease limitation for nios_host_record DNS Bypass

changelogs/fragments/1783-proxmox-kvm-fix-args-500-error.yaml, plugins/modules/cloud/misc/proxmox_kvm.py
vm_args should not be added as 'args' if proxmox_default_behavior is set to no_defaults.
Otherwise the API might always throw 500 - Error because only root@pam is permitted to set 'args'.
This is still tricky, as the Proxmox API does not allow API Tokens to be used when setting "root-only" parameters, even if the user of the token is 'root@pam'. 
Will fix this in a separate issue, as multiple  other parameter are affected by this.
Also we should never add 'force' parameter, even if set to false, the Proxmox API seems to expect the 'archive' parameter if 'force' is submitted. The 'archive' parameter is not implemented at all and will result in a '400 Bad Request: Parameter verification failed'.
In the Proxmox API 'force' is always assumed to be 'false | 0' anyways.
Fixes #1641 
- Bugfix …
=> proxmox_kvm: 500 error args parameter

changelogs/fragments/1795-list-elements-batch1.yml, plugins/doc_fragments/oracle_creatable_resource.py, plugins/module_utils/oracle/oci_utils.py, plugins/modules/cloud/lxd/lxd_container.py, plugins/modules/cloud/packet/packet_device.py, plugins/modules/cloud/pubnub/pubnub_blocks.py, plugins/modules/cloud/smartos/vmadm.py, plugins/modules/cloud/softlayer/sl_vm.py, plugins/modules/files/xml.py, plugins/modules/identity/keycloak/keycloak_client.py, plugins/modules/identity/onepassword_info.py, plugins/modules/monitoring/librato_annotation.py, plugins/modules/monitoring/pagerduty.py, plugins/modules/monitoring/statusio_maintenance.py, plugins/modules/net_tools/dnsimple.py, plugins/modules/net_tools/nsupdate.py, plugins/modules/net_tools/omapi_host.py, plugins/modules/notification/mail.py, plugins/modules/notification/nexmo.py, plugins/modules/notification/office_365_connector_card.py, plugins/modules/notification/rocketchat.py, plugins/modules/notification/sendgrid.py, plugins/modules/notification/slack.py, plugins/modules/notification/twilio.py, plugins/modules/packaging/os/redhat_subscription.py, plugins/modules/source_control/gitlab/gitlab_runner.py, plugins/modules/storage/netapp/na_ontap_gather_facts.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Fixed missing `elements` in both docs and `argument_spec` for a bunch of modules.
plugins/doc_fragments/oracle_creatable_resource.py
plugins/module_utils/oracle/oci_utils.py
plugins/modules/cloud/lxd/lxd_container.py
plugins/modules/cloud/packet/packet_device.py
plugins/modules/cloud/pubnub/pubnub_blocks.py
plugins/modules/cloud/softlayer/sl_vm.py
plugins/modules/files/xml.py
plugins/modules/identity/keycloak/keycloak_client.py
plugins/modules/identity/onepassword_info.py
plugins/modules/monitoring/librato_annotation.py
plugins/modules/monitoring/pagerduty.py
plugins/modules/net_tools/dnsimple.py
plugins/modules/net_tools/nsupdate.py
plugins/modules/net_tools/omapi_host.py
plugins/modules/notification/mail.py …
=> Tidy up validate-modules:parameter-list-no-elements (batch 1)

changelogs/fragments/1814-dnsimple-add-support-for-caa-records.yml, plugins/modules/net_tools/dnsimple.py
I've been using the dnsimple functionality, and found out the whitelist of valid record types doesn't include `CAA` records.
My personal feeling is probably that it shouldn't whitelist them at all, and instead capture errors from the upstream API, so these PR's aren't necessary - but I want this merged so I can use it ;)
So: this adds `CAA` to the valid record types.
I couldn't find tests specific to this module, unless I'm mistaken.
First PR to the Ansible project; do advise if anything else is required. Hopefully this is small enough to just merge.
**Edit:** Oh, and I've checked this against https://support.dnsimple.com/articles/supported-dns-records/ - this is the only record type missing to make it "complete".
dnsimple
N/A
=> dnsimple: Add support for CAA records

changelogs/fragments/1813-lxd_profile-merge-profiles.yml, plugins/modules/cloud/lxd/lxd_profile.py
Previously LXD profiles were overwritten, now a parameter is added to merge these are merge together.
lxd_profile: Profile Management
Previously LXD profiles were overwritten, now, activated by "merge_profile" these are merged.
So far, only configurations that were defined in Ansible have been adopted. Local changes were thus rejected. E.g. a configuration was only made in the config section, then the existing configurations in all other sections disappeared. especially in the default profile that was uncomfortable.
=> Previously LXD profiles were overwritten, now these are merged.

changelogs/fragments/1847-proxmox-kvm-fix-status.yml, plugins/modules/cloud/misc/proxmox_kvm.py
PR #1715 introduced a bug in calls to the `proxmox_kvm` module where the parameter `state` is either `stopped`, `started`, `restarted` or `absent` because the local variable `status` passed to `fail_json` was not defined in these branches.
Sorry, I could not run the code earlier :(
proxmox_kvm
=> proxmox_kvm: fix undefined local variable status

tests/integration/targets/proxmox/tasks/main.yml
Minimal integration tests for the module `proxmox_kvm`: create, start, stop then destroy.
proxmox_kvm
~~Need PR #1847 and~~ will unlock PR #1422.
=> proxmox_kvm: add integration tests

tests/integration/targets/flatpak_remote/aliases
See https://dev.azure.com/ansible/b24bf3ca-6168-45d7-99e2-bf8029e67c87/_apis/build/builds/7226/logs/534:
```
fatal: [testhost]: FAILED! => {
"cmd": "/usr/bin/flatpak remote-add --user flatpak-test /tmp/flatpak/repo/dummy-repo.flatpakrepo",
"executable": "flatpak",
"flatpakrepo_url": "/tmp/flatpak/repo/dummy-repo.flatpakrepo",
"method": "user",
"name": "flatpak-test",
"state": "present"
}
},
"msg": "error:********@example.com>\"\nKey expired Fri 19 Feb 2021 04:30:48 PM UTC",
"rc": 1,
"stderr": "error: Signature made Wed 20 Feb 2019 05:44:53 PM UTC using RSA key ID 09DF558DBAA79AE4\nBAD signature from \" <test@example.com>\"\nKey expired Fri 19 Feb 2021 04:30:48 PM UTC\n",
"stderr_lines": [
"error: Signature made Wed 20 Feb 2019 05:44:53 PM …
```
=> Disable flatpak_remote test due to expired key

changelogs/fragments/1871-infoblox-inventory.yml, scripts/inventory/infoblox.py
The infoblox inventory script does not work out of the box: it imports from `ansible_collections.community.general.plugins.module_utils.net_tools.nios.api`, which is only importable in a regular Python script when community.general is installed as part of Ansible 2.10/3, or has somehow otherwise been installed in PYTHONPATH.
This PR also makes the script work when Ansible 2.9 is installed, and provides a more helpful error in case neither 2.9, 2.10 or 3 are installed.
infoblox inventory script
=> Improve infoblox inventory script dependencies

changelogs/fragments/1852-deploy-helper-fix-state-is-clean-without-release.yaml, plugins/modules/web_infrastructure/deploy_helper.py
Fixes #1852 
Do not try to `remove_unfinished_link` if no release was specifed.
plugins/modules/web_infrastructure/deploy_helper.py
The deploy_helper module is useful when doing software deploys in versioned releases. It prepares the folder structure, and also cleans up failed deploys and/or older releases. 
In the case of calling `state=clean`, only the cleanup procedure is called. Specifying a release is optional in that case.
In my opinion, this bug stems from the fact that we are accessing `self.release` in the function `remove_unfinished_link` without passing that value as a parameter. So `self.release` is a hidden dependency of this method.
The current solution is to return early from within the `remove_unfinished_link` method - but a better solution would be …
=> deploy_helper: fix a bug when not defining release on state=clean

plugins/modules/source_control/gitlab/gitlab_project_members.py
I didn't notice during review that the new gitlab_project_members module (added in #1829) is a slightly adjusted copy of the gitlab_group_members module. Because of that, it needs to keep the copyright notice and `author:` line of the gitlab_group_members module. This updates the module accordingly.
@metanovii please note that you have to include the original copyright and author the next time you adjust an existing module.
@zanssa since you are the author of gitlab_project_members, I copied your copyright header over and added you to the `author:` list. Please approve this PR if this is ok for you! If you don't want to be listed as an author of the new module, I can revert the `author:` change.
=> Update gitlab_project_members copyright and author list

plugins/inventory/linode.py
The documentation is currently broken due to a typo.
Fixes #1886.
linode inventory plugin
=> linode inventory plugin: fix documentation

changelogs/fragments/1895-proxmox-kvm-fix-issue-1875.yml, plugins/modules/cloud/misc/proxmox_kvm.py
Fixes issue #1875: parameter `vmid` passed twice to `exit_json()`.
proxmox_kvm
=> proxmox_kvm: trivial patch for github issue #1875

changelogs/fragments/1880-fix_cobbler_system_ssl.yml, plugins/modules/remote_management/cobbler/cobbler_sync.py, plugins/modules/remote_management/cobbler/cobbler_system.py
Fixes  #1878.
cobbler_system now check self signed certificates correctly. Followed implementation [pep-0476](https://www.python.org/dev/peps/pep-0476/).
cobbler_system
=> [Fix] fix cobbler_system ssl cert checkwhen validate_certs set to no

tests/integration/targets/yum_versionlock/aliases
The yum_versionlock tests are **extremely** slow: the locking and unlocking operation both take up to 10 minutes!
See for example:
- https://dev.azure.com/ansible/b24bf3ca-6168-45d7-99e2-bf8029e67c87/_apis/build/builds/7679/logs/1194
- https://dev.azure.com/ansible/b24bf3ca-6168-45d7-99e2-bf8029e67c87/_apis/build/builds/7679/logs/1187
Timestamps of interest:
- RHEL 8.2 on Ansible 2.10:
```
2021-02-26T09:31:35.8642168Z 06:52 TASK [yum_versionlock : Lock all packages] *************************************
2021-02-26T09:41:41.5695147Z 16:58 changed: [testhost] => {"changed": true, "meta": {"packages": ["epel-release", "rh-amazon-rhui-client", ..., "microcode_ctl"], "state": "present"}}
```
for locking and
```
2021-02-26T09:41:45.1511543Z 17:02 TASK [yum_versionlock : Unlock all packages] …
```
=> Disable way too slow yum_versionlock tests

changelogs/fragments/1912-yum_versionlock-lock_unlock_concurrently.yml, plugins/modules/packaging/os/yum_versionlock.py, tests/integration/targets/yum_versionlock/aliases
Fixes #1908 
Change module to lock/unlock all packages at once instead of doing it one by one.
=> yum_versionlock: do lock/unlock concurrently

changelogs/fragments/1914-add-sanitization-to-url.yml, plugins/inventory/proxmox.py
I received an email a few days ago about an interesting issue with this module. A user configured this module with a trailing / for the Proxmox URL, which breaks the Proxmox API.
I added a small patch to strip any and all trailing slashes from the url field, so this will no longer occur.
proxmox
Before this patch, running the inventory with a trailing slash resulted in the error below
```paste below
[WARNING]:  * Failed to parse /root/projects/playground/inventory/carrier.proxmox.yml with
ansible_collections.community.general.plugins.inventory.proxmox plugin: Expecting value: line 1 column 1 (char 0)
```
=> Proxmox inventory: Add some sanitization to url parameter

changelogs/fragments/1928-bigpanda-message.yml, plugins/modules/monitoring/bigpanda.py
When `message` was made an alias of `deployment_message`, the code was never adjusted to actually use `deployment_message`.
bigpanda
=> bigpanda: actually use option

changelogs/fragments/1929-grove-message.yml, plugins/modules/notification/grove.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt
grove still has a `message` option (the option name is also used internally by Ansible). Add a `message_content` option, make `message` its alias, and deprecate `message` for removal in community.general 4.0.0.
grove
=> grove: message -> message_content

changelogs/fragments/1867-modhelper-cmdmixin-dict-params.yml, plugins/module_utils/module_helper.py, plugins/modules/system/xfconf.py
Improved run_command signature and behaviour
- extra_params has been removed from the signature
- params now can be either str or dict (containing the param value)
The purpose is to simplify passing custom values to parameters (either parameters declared in the module's `argument_spec` or custom ones)
=> Improved ModuleHelper.run_command()

CHANGELOG.rst, changelogs/changelog.yaml
The 2.0.0 changelog claims to contain all changes since 1.0.0. It does, except the modules/plugins added in 1.1.0, 1.2.0 and 1.3.0.
Fixes #1933. (Fixed by using ansible-community/antsibull-changelog#52.)
changelog
=> [stable-2] Also mention plugins/modules added in 1.1.0, 1.2.0 and 1.3.0 in 2.0.0 changelog

plugins/lookup/tss.py
A more detailed example using self-hosted secrets server as investigated in #1943
There is only one example in the `tss` module which is very simple. Adding another, slightly more elaborate example which is likely to be used for self-hosted secrets servers.
tss
=> Adding another example for tss lookup

tests/integration/targets/docker_container/filter_plugins/ipaddr_tools.py
A filter plugin included in the docker_container test uses ipaddress from ansible.netcommon, which has been removed in the 2.0.0 release yesterday. Switches to the vendored copy in community.crypto.
=> [stable-1] fix docker_container tests

changelogs/fragments/620-consul_io-env-variables-conf-based.yml, scripts/inventory/consul_io.py
System like AWX/TOWER can't use an .ini file to source variables. 
The PR extends the inventory `scripts/inventory/consul_io.py` by adding all configuration options via environment variables. (author: @atbore-phx)
The PR also fixes a decode bug to use the script group feature with python 3 (author @Bondeau). 
scripts/inventory/consul_io.py
AWX v.13
python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
ansible v. 2.9.10
Requirements:
At this time the script is not working due different issues a main PR, which restores the basic functions can be found here: https://github.com/ansible/ansible/pull/56969 with the labels :label:collection,collection:community.general,needs_collection_redirect
- apply this PR to get a working …
=> consul_io inventory script: fixes awx and python 3 kv_group

changelogs/fragments/1833-zfs-creation-only-properties.yaml, plugins/modules/storage/zfs/zfs.py
Fixes #868 
zfs
As discussed in the linked issue, there are a few zfs properties that can only be set at creation time. Assuming I haven't missed any, those properties are:
- volblocksize
- encryption
- casesensitivity
- normalization
- utf8only
Additionally, there are two properties that can only be set at creation time or with the `zfs change-key` command:
- keyformat
- pbkdf2iters
For the purpose of this merge request, I don't try to special-case `keyformat` or `pbkdf2iters`, since I would expect that most of the time, users attempting to change these values would be doing so mistakenly. I mention them here in case someone wants to add that feature in.
The problem is that because `zfs list` gives these properties a source of '-' (indicating read-only), they are …
=> zfs: avoid errors with creation-only properties

changelogs/fragments/1882-fix-nmcli-ensure-slave-type-for-bond-slave.yml, plugins/modules/net_tools/nmcli.py
Hello 🙂 
NMCLI module do not work with bond-slave type.
Bug in module
nmcli
When using bond-slave type, by default command sent to nmcli by module is:
`['/usr/bin/nmcli', 'con', 'add', 'type', 'bond-slave', 'con-name', 'enp129s0f0', 'connection.interface-name', 'enp129s0f0', 'connection.autoconnect', 'yes', 'connection.master', 'bond0']`
Which is not enough, nmcli will complain that connection.slave-type is missing. This small fix solve this issue.
If this change is approved, I will add the changelog fragment.
=> Fix: nmcli - Ensure slave-type for bond-slave

changelogs/fragments/1927-removed-parameter-invalid.yml, plugins/modules/packaging/language/composer.py, plugins/modules/packaging/os/apt_rpm.py, plugins/modules/packaging/os/homebrew.py, plugins/modules/packaging/os/homebrew_cask.py, plugins/modules/packaging/os/opkg.py, plugins/modules/packaging/os/pacman.py, plugins/modules/packaging/os/slackpkg.py, plugins/modules/packaging/os/urpmi.py, plugins/modules/packaging/os/xbps.py, plugins/modules/source_control/github/github_deploy_key.py, plugins/modules/system/puppet.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Deprecating the parameters, removal on version 5.0.0.
plugins/modules/system/puppet.py
plugins/modules/source_control/github/github_deploy_key.py
plugins/modules/packaging/os/xbps.py
plugins/modules/packaging/os/urpmi.py
plugins/modules/packaging/os/slackpkg.py
plugins/modules/packaging/os/pacman.py
plugins/modules/packaging/os/opkg.py
plugins/modules/packaging/os/homebrew_cask.py
plugins/modules/packaging/os/homebrew.py
plugins/modules/packaging/os/apt_rpm.py
plugins/modules/packaging/language/composer.py
=> Deprecation of parameters triggering the parameter-invalid sanity-check

changelogs/fragments/1970-valmod-batch7.yml, plugins/modules/cloud/heroku/heroku_collaborator.py, plugins/modules/cloud/linode/linode_v4.py, plugins/modules/cloud/opennebula/one_host.py, plugins/modules/cloud/opennebula/one_image_info.py, plugins/modules/cloud/opennebula/one_vm.py, plugins/modules/cloud/packet/packet_volume_attachment.py, plugins/modules/cloud/scaleway/scaleway_compute.py, plugins/modules/cloud/scaleway/scaleway_lb.py, plugins/modules/remote_management/manageiq/manageiq_alert_profiles.py, plugins/modules/remote_management/manageiq/manageiq_policies.py, plugins/modules/remote_management/manageiq/manageiq_provider.py, plugins/modules/remote_management/manageiq/manageiq_tags.py, plugins/modules/remote_management/oneview/oneview_datacenter_info.py, plugins/modules/remote_management/oneview/oneview_enclosure_info.py, plugins/modules/remote_management/oneview/oneview_ethernet_network_info.py, plugins/modules/remote_management/oneview/oneview_network_set_info.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Tidy up some validation checks - `validate-modules:parameter-list-no-elements` - on a number of modules.
plugins/modules/remote_management/oneview/oneview_enclosure_info.py
plugins/modules/remote_management/oneview/oneview_datacenter_info.py
plugins/modules/remote_management/oneview/oneview_ethernet_network_info.py
plugins/modules/remote_management/oneview/oneview_network_set_info.py
plugins/modules/cloud/scaleway/scaleway_compute.py
plugins/modules/cloud/scaleway/scaleway_lb.py
plugins/modules/cloud/opennebula/one_vm.py
plugins/modules/cloud/opennebula/one_image_info.py
plugins/modules/cloud/opennebula/one_host.py
plugins/modules/remote_management/manageiq/manageiq_tags.py
plugins/modules/remote_management/manageiq/manageiq_alert_profiles.py …
=> Tidy up sanity checks ignore lines modules (batch 7) 

changelogs/fragments/community.docker-87-docker_image-load-image-ids.yml, plugins/module_utils/docker/common.py, plugins/modules/cloud/docker/docker_image.py, plugins/modules/cloud/docker/docker_image_info.py
Backport of bugfix parts of https://github.com/ansible-collections/community.docker/pull/87 to stable-1.
docker_image
docker_image_info
=> [stable-1] docker_image: fix handling of image IDs

changelogs/fragments/1977-jenkinsjob-validate-certs.yml, plugins/modules/web_infrastructure/jenkins_job.py
Adds a `validate_certs` parameter, with default to `True`, that can be used to disable the validation of SSL/TLS certificates when contacting the Jenkins server. Under the hood this translates into setting the environment variable `PYTHONHTTPSVERIFY=0` as described in #255 .
Fixes: #255 
plugins/modules/web_infrastructure/jenkins_job.py
=> jenkins_job - added validate_certs parameter, setting the PYTHONHTTPSVERIFY env var

1949-proxmox-inventory-tags.yml, changelogs/fragments/1949-proxmox-inventory-tags.yml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
Allowing proxmox tags strings containing commas to be passed as facts
The current behavior of the proxmox inventory plugin will attempt to parse values containing commas from the PVE API configs endpoint as dictionaries. However tags strings disallow '=' characters which will always cause parsing to fail for tags strings presented as comma separated list. This change will explicitly allow the 'tags' config to bypass dict parsing.
=> Allow tags strings containing commas in proxmox inventory plug-in

changelogs/fragments/1991-proxmox-inventory-fix-template-in-pool.yml, plugins/inventory/proxmox.py
Exclude qemu templates from inclusion to the inventory via pools
Fixes #1986 
```paste below
```
=> Excluded qemu templates in pools

changelogs/fragments/2001-no_log-false.yml, plugins/module_utils/oracle/oci_utils.py, plugins/modules/cloud/pubnub/pubnub_blocks.py, plugins/modules/cloud/spotinst/spotinst_aws_elastigroup.py, plugins/modules/cloud/xenserver/xenserver_guest.py, plugins/modules/clustering/consul/consul_acl.py, plugins/modules/clustering/consul/consul_kv.py, plugins/modules/clustering/etcd3.py, plugins/modules/files/read_csv.py, plugins/modules/files/xattr.py, plugins/modules/net_tools/cloudflare_dns.py, plugins/modules/source_control/bitbucket/bitbucket_access_key.py, plugins/modules/source_control/bitbucket/bitbucket_pipeline_known_host.py, plugins/modules/source_control/github/github_deploy_key.py, plugins/modules/source_control/gitlab/gitlab_deploy_key.py, plugins/modules/system/dconf.py, plugins/modules/system/gconftool2.py, plugins/modules/system/osx_defaults.py
Fixes current `devel` sanity errors; see https://github.com/ansible/ansible/pull/73508.
oci_utils
pubnub_blocks
spotinst_aws_elastigroup
xenserver_guest
consul_acl
consul_kv
etcd3
read_csv
xattr
cloudflare_dns
bitbucket_access_key
bitbucket_pipeline_known_host
github_deploy_key
dconf
gconftool2
osx_defaults
=> Mark non-secret leaking module options with no_log=False

changelogs/fragments/1999-proxmox-fix-issue-1955.yml, plugins/modules/cloud/misc/proxmox.py
Removing the requirement that the password parameter be required when state = present.
Fixes #1955 
As mentioned in #1955 this proxmox plugin requires that a root password be supplied for an lxc instance which is not consistent with the proxmox API which will happily allow a lxc instance to be created with no root password or ssh public key for the root user.
Removing the module requirement will allow end users to provide either a root password, public key, both, or neither.
Documentation is also updated to reflect that password is no longer required when state=present.
If passwords were explicitly required for earlier versions of PVE (possibly <4.2) then the task will fail because of a 4XX response from the PVE API so this …
=> Remove password requirement when creating lxc containers

changelogs/fragments/missing-no_log-again.yml, plugins/modules/storage/netapp/na_cdot_user.py, plugins/modules/storage/netapp/sf_account_manager.py
Adds two missing `no_log=True` in two deprecated modules that were removed in community.general 2.0.0.
In the modules that replace these modules, the issue has already been fixed (https://github.com/ansible-collections/netapp/commit/a2d3b961f9bf7efb89d71e0caca0eef183cc632c#diff-cbb7bcd7441934dc6d76359036460841f01deb56bacce6813ae7935ebacc810cR151) or has never been there in the first place (https://github.com/ansible-collections/netapp/commit/c6018a86fc316b2bf1f27bda893f028e4be1f3e4).
CC @gundalow @relrod
na_cdot_user
sf_account_manager
=> [stable-1] Add missing no_log=True

plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/cloud/docker/docker_swarm_service.py, plugins/modules/cloud/google/gc_storage.py, plugins/modules/cloud/linode/linode_v4.py, plugins/modules/cloud/lxd/lxd_container.py, plugins/modules/cloud/lxd/lxd_profile.py, plugins/modules/cloud/misc/proxmox_kvm.py, plugins/modules/cloud/oneandone/oneandone_server.py, plugins/modules/cloud/profitbricks/profitbricks.py, plugins/modules/cloud/profitbricks/profitbricks_volume.py, plugins/modules/cloud/softlayer/sl_vm.py, plugins/modules/database/aerospike/aerospike_migrations.py, plugins/modules/monitoring/datadog/datadog_event.py, plugins/modules/monitoring/pagerduty_alert.py, plugins/modules/remote_management/manageiq/manageiq_provider.py, plugins/modules/source_control/gitlab/gitlab_user.py
Backport of #2010 to stable-1. Includes https://github.com/ansible-collections/community.docker/pull/102 and new changes to the modules `gc_storage`, `lxd_container`, `lxd_profile` which have been removed/updated in 2.0.0.
(`gc_storage` was moved to community.google, and in both `lxd_container` and `lxd_profile` the option was changed to type `path` since it is actually a path and not the value of the private key.)
docker_swarm_service
gc_storage
lxd_container
lxd_profile
keycloak
linode_v4
proxmox_kvm
oneandone_server
profitbricks
profitbricks_volume
sl_vm
aerospike_migrations
datadog_event
pagerduty_alert
gitlab_user
=> [stable-1] no_log: more false-positives (not flagged by sanity tests yet)

changelogs/fragments/2006-valmod-batch8.yml, plugins/modules/cloud/rackspace/rax.py, plugins/modules/cloud/rackspace/rax_cdb_user.py, plugins/modules/cloud/rackspace/rax_scaling_group.py, plugins/modules/cloud/smartos/smartos_image_info.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Tidy up some validation checks on some modules.
plugins/modules/cloud/rackspace/rax.py
plugins/modules/cloud/rackspace/rax_cdb_user.py
plugins/modules/cloud/rackspace/rax_scaling_group.py
plugins/modules/cloud/smartos/smartos_image_info.py
=> Tidy up sanity checks ignore lines modules (batch 8)

changelogs/fragments/2020-remove-unused-param-in-rax.yml, plugins/modules/cloud/rackspace/rax.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Parameter `service` in module `rax` is not being used since Ansible 2.3.0, but not using any of the (now) standard deprecation methods. If that paremeter receives a value, the module will call `module.fail_json()`.
This PR removes that parameter.
rax
=> rax - removed service parameter

changelogs/fragments/2014-allow-root-for-kibana-plugin.yaml, plugins/modules/database/misc/kibana_plugin.py
Allow specifying an `allow_root` option to pass the `--allow-root` flag to the `kibana` and `kibana-plugin` commands. 
The Kibana RPM from Elasticsearch by default installs everything as `root`, so this module fails when trying to 
1. Run `kibana --version` since it cannot read `/etc/kibana/kibana.yml`
2. Modify `/usr/share/kibana/plugins` since it is only writeable by `root`
kibana-plugin
Please let me know if I can provide any more information or need to make any further changes.
Thank you
=> allow passing the --allow-root flag to kibana_plugin module

changelogs/fragments/2000-proxmox_kvm-tag-support.yml, plugins/modules/cloud/misc/proxmox_kvm.py
New feature in proxmox_kvm plugin to allow VM tags to be passed as module parameters.
Fixes #1989 
Tags are supplied as a yaml list of strings to the tags parameter.
Within the module tags are restricted to only Proxmox version >=6.
Tags are validated against the format provided by the proxmox devs and failed validation will fail the module indicating which tag is at fault.
Tags are joined with commas and then passed to proxmoxer as a tag-list-string,
CRUD operations function as expected for tags as well.
=> Adding tags as module parameter to proxmox_kvm

changelogs/fragments/2036-scaleway-inventory.yml, plugins/module_utils/scaleway.py
`scaleway-inventory.py`
Scaleway inventory got a pagination issue which leads to redirect paginated call without taken in account the region specified in the base URL.  
Scaleway inventory parse the header returned from the API see https://github.com/ansible-collections/community.general/blob/main/plugins/inventory/scaleway.py#L120 and construct a new url with the page return by the `parse_pagination_link` function. 
Previously, the `parse_pagination_link` returned absolute URL like `/servers?page=2&per_page=50&` as we use the `urljoin` function, the new constructed URL is not regionified anymore see urljoin doc https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin
```
>>> import ansible.module_utils.six.moves.urllib.parse as urllib_parse
>>> …
```
=> fix: scaleway inventory pagination

changelogs/fragments/2040-fix-index-error-in-redfish-set-manager-nic.yml, plugins/module_utils/redfish_utils.py
If an array property is passed to the `SetManagerNic` command and the new array is longer than the current array, an IndexError will occur during the checks to see if the new properties are the same or different from the existing properties. The reason for checking if the arrays are different is to avoid making the change if the existing values already match the new values.
In the case where the new array is a different length than the existing array, there is no need to try to compare individual elements to see if any have changed. If the lengths are different, the arrays are different and we should attempt to make the change.
Fixes #1692 
Given a play like this:
```
---
- hosts: myhosts
name: Set Manager NIC …
```
=> Fix IndexError in SetManagerNic

changelogs/fragments/2013-proxmox-purge-parameter.yml, plugins/modules/cloud/misc/proxmox.py
Adding purge parameter to proxmox module to allow for deletion of containers with HA defined.
Fixes #1488 
Purge can be optionally included with any combination of parameters, but only has meaning when used with state=absent.
If state=absent and purge=true, then the purge parameter will be included as a keyword argument in the delete request.
Given that this is an optional parameter for the PVE API, it has no conflict with other PVE parameters, and is only used for deletion so this should be a low impact change.
=> Adding purge parameter to proxmox for use with lxc delete requests

.github/BOTMETA.yml
Adding xmadsen and renxulei from Lenovo as Redfish maintainers to help manage the module.
- Other
=> Adding xmadsen and renxulei as Redfish maintainers

changelogs/fragments/2057-nios-devel.yml, plugins/module_utils/net_tools/nios/api.py, tests/unit/plugins/module_utils/net_tools/nios/test_api.py, tests/unit/plugins/modules/net_tools/nios/test_nios_a_record.py, tests/unit/plugins/modules/net_tools/nios/test_nios_aaaa_record.py, tests/unit/plugins/modules/net_tools/nios/test_nios_cname_record.py, tests/unit/plugins/modules/net_tools/nios/test_nios_dns_view.py, tests/unit/plugins/modules/net_tools/nios/test_nios_host_record.py, tests/unit/plugins/modules/net_tools/nios/test_nios_mx_record.py, tests/unit/plugins/modules/net_tools/nios/test_nios_naptr_record.py, tests/unit/plugins/modules/net_tools/nios/test_nios_network_view.py, tests/unit/plugins/modules/net_tools/nios/test_nios_nsgroup.py, tests/unit/plugins/modules/net_tools/nios/test_nios_srv_record.py
The module_utils uses a private part of `AnsibleModule` that was removed in ansible/ansible#73703. (See also ansible/ansible#73983.)
plugins/module_utils/net_tools/nios/api.py
=> Fix nios modules to work with ansible-core 2.11

changelogs/fragments/2031-ipa_sudorule_add_runasextusers.yml, plugins/modules/identity/ipa/ipa_sudorule.py
ipa_sudorule.py
While moving from bash script to ansible the lack of being able to set sudorule runasuser came up. This pull request is meant to fix that. 
This code allow using ipa_sudorule module to do same as the code below. 
```
ipa sudorule-add-runasuser $SUDONAME --users=root
```
=> ipa_sudorule add support for setting runasextusers

changelogs/fragments/2061-archive-refactor1.yml, plugins/modules/files/archive.py
As of today, `archive` is a very long strip of code within `main()`. This PR is a first one out of more to come aiming at change that.
archive
=> archive - a first refactoring

plugins/module_utils/gandi_livedns_api.py, plugins/modules/gandi_livedns.py, plugins/modules/net_tools/gandi_livedns.py, tests/integration/targets/gandi_livedns/aliases, tests/integration/targets/gandi_livedns/defaults/main.yml, tests/integration/targets/gandi_livedns/tasks/create_record.yml, tests/integration/targets/gandi_livedns/tasks/main.yml, tests/integration/targets/gandi_livedns/tasks/record.yml, tests/integration/targets/gandi_livedns/tasks/remove_record.yml, tests/integration/targets/gandi_livedns/tasks/update_record.yml
This module uses REST API to register, update and delete domain name
entries in Gandi DNS service (https://www.gandi.net/en/domain).
Ansible module to control Gandi DNS service (https://www.gandi.net/en/domain)
- gandi_livedns
- This commit includes module_utils/gandi_livedns_api.py that will be used by a future gandi_livedns_fact module.
=> Add gandi_livedns module

changelogs/fragments/2037-add-from-csv-filter.yml, changelogs/fragments/XXXX-add-from-csv-filter.yml, plugins/filter/from_csv.py, plugins/module_utils/csv.py, plugins/modules/files/read_csv.py, tests/integration/targets/filter_from_csv/aliases, tests/integration/targets/filter_from_csv/tasks/main.yml, tests/integration/targets/filter_from_csv/vars/main.yml, tests/unit/plugins/module_utils/test_csv.py
This filter adapts the csv parsing features from the read_csv module to use directly with ansible text/variables
Fixes: #1881 
plugins/filter/from_csv.py
plugins/modules/read_csv.py
plugins/module_utils/csv.py
Feature set and core implementation is pulled directly from read_csv and adapted to the filter structure.
Common functions have been refactored into module_utils/csv.py which both read_csv and from_csv utilize
Notable Changes:
- Return of read_csv is a tuple of list and dict with populated result switching to dict if key is provided. For the purposes of a filter I have chosen to make the result a list of anonymous dicts which can be keyed using jinja e.g. some_var | community.general.from_csv | groupby('key') | flatten is equivalent to keyed output of read_csv …
=> New Filter plugin from_csv

changelogs/fragments/2072-stacki-host-params-fallback.yml, plugins/modules/remote_management/stacki/stacki_host.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
Some parameters were set with `default=os.environ.get(...)`, while the recommended way for doing that is to use `fallback=(env_fallback, ...)`
stacki_host
=> stacki_host - configured params to use fallback instead of default

plugins/modules/files/archive.py
"ansible.builtin.unarchive" module does not work on a file created by the "community.general.archive" module if this is an archive of a single file unless "force_archive" parameter is enabled
community.general.archive
I believe it is important to note that this parameter should be enabled for single file "archives" to be compatible with unarchive module.
"ansible.builtin.unarchive" module says in the docs :
"It will not unpack a compressed file that does not contain an archive."
This was tested with .tar and .tar.gz files and failed when this parameter was left at the default value. The only solution for this was to enable this parameter.
=> improve force_archive parameter documentation of archive module

tests/integration/targets/copr/aliases
```
TASK [copr : enable copr project] **********************************************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Chroot centos-stream-x86_64 does not exist in @copr/integration_tests"}
```
copr
=> Temporarily disable copr integration tests due to failures with remote repository

tests/utils/shippable/shippable.sh
Using Galaxy in CI is a total PITA (https://github.com/ansible/galaxy/issues/2429). This removes all uses of `ansible-galaxy collection install`.
CI
=> Install collections in CI directly with git

changelogs/fragments/2032-one_image-pyone.yml, plugins/modules/cloud/opennebula/one_image.py
This pull request ports the `one_image` module to use the `pyone` library instead of `python-oca`.
one_image
`one_image` is (was? :-)) the last module in cloud/opennebula that still depended on the old and unmaintained `python-oca` library, which does not work with Python 3.
Before the change, the output of this basic playbook failed with a syntax error because `python-oca` used the old python2 syntax for rescuing exceptions:
```yaml
---
module_defaults:
community.general.one_image:
api_url: 'https://some-opennebula-host/RPC2'
api_username: 'oneuser'
api_password: 'secret'
tasks:
- name: Fetch the IMAGE by name
community.general.one_image:
name: foxy-test
- name: Print the IMAGE properties
ansible.builtin.debug:
var: result
``` …
=> opennebula: port one_image to pyone

.github/BOTMETA.yml, plugins/modules/remote_management/lenovoxcc/xcc_redfish_command.py, plugins/modules/xcc_redfish_command.py, tests/unit/plugins/modules/remote_management/lenovoxcc/test_xcc_redfish_command.py
Add this module to manage Lenovo servers using Redfish APIs in order to cover Lenovo oem features that are currently not supported by standard Redfish modules in ansible. 
xcc_redfish_command
- Builds Redfish URIs locally and sends them to remote OOB controllers to
perform an action or get information back or update a configuration attribute.
- Manages virtual media.
- Supports getting information back via GET method.
- Supports updating a configuration attribute via PATCH method.
- Supports performing an action via POST method.
=> add new module xcc_redfish_command to manage Lenovo servers using Redfish APIs

plugins/become/sudosu.py, tests/unit/plugins/become/test_sudosu.py
Allow users to run Ansible tasks through `sudo su -` using password auth
This fixes ansible/ansible#8650 and ansible/ansible#12686
sudosu
So I have been using this at various customers for bootstrapping Ansible mostly.
Often you have an existing setup where there is a user that has root-access enabled through sudo, but only to run `su` to log using the user's password.
In these specific cases the root password is unique to the system and therefore not an easy way to automate bootstrapping.
Having a `sudo su -` become option **with password prompt** is not possible with the existing become methods (neither sudo nor su can be used) by abusing `become_exe` or `become_flags`.
=> Add support for `sudo su -` using password auth

.github/BOTMETA.yml
bgurney-rh does not work with VDO projects anymore.  This change re-points
maintainer pings to rhawalsh instead.
As mentioned.  bgurney-rh does not work with VDO projects any more.
```paste below
```
=> Updated vdo maintainer to rhawalsh.

changelogs/fragments/2094-bugfix-respect-PATH-env-variable-in-zypper-modules.yaml, plugins/modules/packaging/os/zypper.py, plugins/modules/packaging/os/zypper_repository.py
Currently the zypper modules use the hard-coded path `/usr/bin/zypper` for the zypper executable. So, in case of other locations the modules are not able to handle zypper actions correctly.
This Pull Request fixes this issue. Now, the zypper modules respect the PATH environment variable to find the zypper exceutable.
- community.general.zypper
- community.general.zypper_repository
=> Bugfix: Respect PATH env variable in zypper modules

changelogs/fragments/2110-vdo-add_force_option.yaml, plugins/modules/system/vdo.py
=> vdo: add force option

changelogs/fragments/2135-vmadm-resolvers-type-fix.yml, plugins/modules/cloud/smartos/vmadm.py
Fixes #2135
vmadm
Fixes type checking for the `resolvers` parameter for `vmadm`
=> fix type information for vmadm.resolvers

changelogs/fragments/2139-dimensiondata_network-str-format.yml, plugins/modules/cloud/dimensiondata/dimensiondata_network.py
Bug when formatting message, instead of `%` a simple comma was used.
dimensiondata_network
=> Dimensiondata network str format

changelogs/fragments/2143-kibana_plugin-fixed-function-calls.yml, plugins/modules/database/misc/kibana_plugin.py
Added missing arguments to `remove_plugin()` when `state=present force=true`.
While at it, when calling `run_command()` it was converting a list to str, so changed it to keep the list.
kibana_plugin
=> kibana_plugin: fixed remove call + run_command with list instead of str

changelogs/fragments/2144-atomic_get_bin_path.yml, plugins/modules/cloud/atomic/atomic_container.py, plugins/modules/cloud/atomic/atomic_host.py, plugins/modules/cloud/atomic/atomic_image.py
These modules were calling `run_command()` without submitting the command through `get_bin_path()`.
plugins/modules/cloud/atomic/atomic_container.py
plugins/modules/cloud/atomic/atomic_host.py
plugins/modules/cloud/atomic/atomic_image.py
=> using get_bin_path() on atomic modules

changelogs/fragments/2143-kibana_plugin-fixed-function-calls.yml, plugins/modules/database/misc/kibana_plugin.py
Backport of #2143 to stable-1.
CC @russoz - I had to adjust the patch since the `allow_root` parameter does not exist in stable-1. Could you please check whether it is correct?
kibana_plugin
=> [stable-1] kibana_plugin: fixed remove call + run_command with list instead of str

changelogs/fragments/2161-pkgutil-list-extend.yml, plugins/modules/packaging/os/pkgutil.py
Method `list.extend()` expects one argument, an `Iterable`
plugins/modules/packaging/os/pkgutil.py
=> fixed calls to list.extend()

changelogs/fragments/2163-java_keystore_1667_improve_temp_files_storage.yml, plugins/modules/system/java_keystore.py, tests/unit/plugins/modules/system/test_java_keystore.py
This PR covers temporary files handling:
- files containing certificate, private key and pkcs12 are created with `tempfile.mkstemp()`
- temporary pkcs12 is removed as well as other materials
Fixes #1667 
java_keystore
=> java_keystore/fix 1667 improve temp files storage

changelogs/fragments/2162-modhelper-variables.yml, plugins/module_utils/module_helper.py, tests/integration/targets/module_helper/aliases, tests/integration/targets/module_helper/library/mdepfail.py, tests/integration/targets/module_helper/library/msimple.py, tests/integration/targets/module_helper/library/mstate.py, tests/integration/targets/module_helper/tasks/main.yml, tests/integration/targets/module_helper/tasks/mdepfail.yml, tests/integration/targets/module_helper/tasks/msimple.yml, tests/integration/targets/module_helper/tasks/mstate.yml, tests/unit/plugins/module_utils/test_module_helper.py
Revamp on how ModuleHelper manages module variables. This is a new feature that brings automation to:
- publishing the variables on the output
- calculating the `changed` result
- generating `diff` result
tests/integration/targets/module_helper/aliases
tests/integration/targets/module_helper/library/mdepfail.py
tests/integration/targets/module_helper/library/msimple.py
tests/integration/targets/module_helper/library/mstate.py
tests/integration/targets/module_helper/tasks/main.yml
tests/integration/targets/module_helper/tasks/mdepfail.yml
tests/integration/targets/module_helper/tasks/msimple.yml
tests/integration/targets/module_helper/tasks/mstate.yml
=> ModuleHelper variables management

changelogs/fragments/2177-java_keystore_1668_dont_expose_secrets_on_cmdline.yml, plugins/modules/system/java_keystore.py, tests/unit/plugins/modules/system/test_java_keystore.py
This PR covers secret's handling by the module. It replaces insecure and clear password in keytool's commandline arguments by storing it in an environment variable (doing this from stdin is not supported by keytool).
This is achieved with the `environ_update` argument of `module.run_command()` (i.e. on a per-command basis) rather than with a more general `module.run_command_environ_update()` (that would export the variable in all subsequent `module.run_command()` calls, that means: when it is not needed).
Fixes #1668 
java_keytool
=> replace inline clear password by environment variable

changelogs/fragments/2185-xfconf-absent-check-mode.yml, plugins/modules/system/xfconf.py
Module `xfconf` was not honoring the check mode when `state=absent`.
xfconf
=> xfconf - state absent was not honoring check_mode

changelogs/fragments/1978-jira-transition-logic.yml, plugins/modules/web_infrastructure/jira.py, tests/integration/targets/jira/aliases, tests/integration/targets/jira/tasks/main.yml, tests/integration/targets/jira/vars/main.yml
Per discussion in #818 trying to send the `fields` (ansible module) under the `fields` key in JIRA APIv2, while adjusting for `summary`, `assignee` and `comment` (this last one goes into the `update` key in JIRA APIv2.
Fixes: #818 
plugins/modules/web_infrastructure/jira.py
=> jira - changing the logic for transition

changelogs/fragments/2185-xfconf-absent-check-mode.yml, plugins/modules/system/xfconf.py
This is a backport of PR #2185 as merged into main (9a5191d).
Module `xfconf` was not honoring the check mode when `state=absent`.
xfconf
=> [stable-1] xfconf - state absent was not honoring check_mode (#2185)

tests/utils/constraints.txt
=> [stable-1] Restrict docker to < 5.0.0 for Python < 3.6

changelogs/fragments/1993-haproxy-fix-draining.yml, plugins/modules/net_tools/haproxy.py
This pull request makes HAProxy change the state properly to `'DRAIN'` and if `drain=yes` changes to `'MAINT'` afterwards.
Fixes #1913  
haproxy.py
Inspired by @rldleblanc: https://github.com/ansible/ansible/issues/37591#issuecomment-610130611
=> Fix HAProxy draining

changelogs/fragments/2159-ipa-user-sshpubkey-multi-word-comments.yaml, plugins/modules/identity/ipa/ipa_user.py
This is one potential solution to #2158: Using a public ssh key fingerprint that is valid syntax for .authorized_keys and in IPA which has a comment that is more than 1 string (1 block of characters that is not separated by any whitespace), causes the ipa_user module to fail when calling the ipa_user module with no changes.  This patch allows the comment to contain multiple words, whereas the current code assumes it will only be one string returned by split().  See the issue for more detailed breakdown of the issue encountered.
Fixes #2158 
ipa_user
=> ipa_user sshpubkey can now support multi word comments in the key

changelogs/fragments/2174-ipa-user-userauthtype-multiselect.yml, plugins/modules/identity/ipa/ipa_user.py
The ipa_user module has a field for userauthtype, which is currently set to str. It also lists choices, which all seem to be the valid choices. However, the field is multiselect in IPA. With the type str and fixed choices, only one value is permitted with this implementation.
The solution is easy and just changing the type to list of str seems to work. That includes in a backwards compatible way (existing playbooks should still work). However, please validate this. 
Fixes #2173
ipa_user
=> Fix issue where multiselect field in userauthtype did not allow multiple values

.github/BOTMETA.yml, changelogs/fragments/path_join-shim-filter.yml, meta/runtime.yml, plugins/filter/path_join_shim.py, tests/integration/targets/filter_path_join_shim/aliases, tests/integration/targets/filter_path_join_shim/tasks/main.yml
The `path_join` filter has been added in ansible-base 2.10. Since it is very useful, and people might want to use it with Ansible 2.9 as well (or write roles using it that work for both 2.9 and newer), this PR provides a compatibility shim using redirects (used for ansible-base 2.10, ansible-core 2.11 or newer) and a fallback implementation of the filter which will be used with Ansible 2.9.
Using redirects for 2.10+ makes sure that the builtin implementation is preferred over the fallback implementation provided by this PR for ansible-base and ansible-core.
path_join
=> Add path_join compatibility shim

.github/BOTMETA.yml, changelogs/fragments/dict-filter.yml, plugins/filter/dict.py, tests/integration/targets/filter_dict/aliases, tests/integration/targets/filter_dict/tasks/main.yml
This adds a new filter:
1. `dict`: this is basically the `dict` function as a filter. Having it as a filter allows to use it in conjunction with other filters like `map`, which is not possible with the `dict` function.
2. ~~`list_to_dict`: this is a generalization of the `dict_kv` filter from single values and keys to lists of values and keys (see #1264). `x | list_to_dict(y)` is equivalent to `x | zip(y) | dict` with the above `dict` filter.~~
CC @giner you might be interested in this as well, or have opinions on it.
~~Example use case: I have a dictionary `domain_name: txt_value` (obtained from one module), and want to convert it to a list of dictionaries `{name: domain_name, value: txt_value}` to pass them to a module which waits for the TXT values for these domain names to change to …
=> Add dict filter

changelogs/fragments/2203-modhelper-cause-changes-deco.yml, plugins/module_utils/module_helper.py, tests/unit/plugins/module_utils/test_module_helper.py
**This is a backport of PR #2203 as merged into main ([0cd0f0e](https://github.com/ansible-collections/community.general/commit/0cd0f0eaf670d8da8afc6137ee19a53439e06e48)).**
The decorator `cause_changes` never really worked before. This PR fixes that and add unit tests for it.
* Bugfix Pull Request
=> [PR #2203/0cd0f0ea backport][stable-1] module_helper - fixed decorator cause_changes

changelogs/fragments/2162-proxmox-constructable.yml, plugins/inventory/proxmox.py
Implement Constructable so we can use
* keyed_groups
* groups
* compose 
* strict
inventory/proxmox
If we add this we would be able to create groups for example based on the assigned tags in proxmox
```
keyed_groups:
- key: proxmox_tags_parsed
prefix: ""
separator: ""
```
=> inventory/proxmox: added constructable and added keyed_groups, groups and compose

changelogs/fragments/2204-github_repo-fix-baseurl_port.yml, plugins/modules/source_control/github/github_repo.py, tests/unit/plugins/modules/source_control/github/test_github_repo.py
PyGithub bug does not allow explicit port in base_url for github_repo.py
Fixes #2193
github_repo
There is an issue open in PyGithub repo: https://github.com/PyGithub/PyGithub/issues/1913
=> Bugfix: PyGithub does not support explicit port in base_url

changelogs/fragments/2116-add-fields-to-ipa-config-module.yml, plugins/modules/identity/ipa/ipa_config.py
Added fields to the ipa_config module: ipaconfistring, ipadefaultprimarygroup, ipagroupsearchfields, ipahomesrootdir, ipakrbauthzdata, ipamaxusernamelength, ipapwdexpadvnotify, ipasearchrecordslimit, ipasearchtimelimit, ipauserauthtype, ipausersearchfields
Fixes #2115 
Fixes #498
ipa_config
=> Added fields to the ipa_config module

changelogs/fragments/2183-java_keystore_improve_error_handling.yml, plugins/modules/system/java_keystore.py, tests/integration/targets/java_keystore/tasks/main.yml, tests/unit/plugins/modules/system/test_java_keystore.py
The module currently calls `module.run_command` with `check_rc` explicitly set to **True**, although every call to `run_command` is followed by an `if rc != 0:` block. This is why those blocks are never executed, and module fails in case of alias or password mismatch, rather than regenerate the keystore.
This PR comes back to default `check_rc=False` and ensures results are returned as documented in case of error. It also fixes a buggy unit test.
UPDATE: follow the thread and #1671 to understand the change of scope of this PR and why its primary fix (overwrite keystore if password is changed) is delayed to next step.
java_keystore
=> java_keystore: improve error handling and returned results

changelogs/fragments/2148-proxmox-inventory-agent-interfaces.yml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
Adding fact to proxmox inventory plugin such that if a QEMU guest has an agent enabled and the QEMU agent is running the network interfaces will be returned as `proxmox_agent_interfaces`
Fixes #2147 
- 
The Proxmox API does not have an obvious way to determine if a QEMU agent is running so this new logic will attempt to retrieve interface data from the agent and return nothing if the request fails. (Proxmox responds with a 500 error if agent data is requested when the agent is not running)
Proxmox uses 0,1 for boolean values and those values are returned as strings hence the following:
`if config == 'agent' and int(value):`
=> Proxmox_Inv: Adding agent network interaces fact

changelogs/fragments/2192-add-jira-attach.yml, plugins/modules/web_infrastructure/jira.py
Adds the `attach` operation to the `web_infrastructure.jira` module,
which allows a user to attach a file to an issue. The user can supply
either the path to a file, which will be read from storage, or a file
name and content (as bytes).
`community.general.web_infrastructure.jira`
N/A
=> Add Jira attach operation

changelogs/fragments/allow_funcd_to_load.yml, plugins/connection/funcd.py
ansible's plugin loader was updated to only load those that inherit from ConnectionBase but the plugin was never updated to do so, why it cannot load.
connection/funcd
=> funcd connection plugin is now usable/loadable

plugins/modules/cloud/linode/linode_v4.py
There are bunch of unnecessary `required: false` in documentation and `required=False` in `argument_spec` of `linode_v4` module.
This PR removes them.
linode_v4
This results in other contributors to follow this too (https://github.com/ansible-collections/community.general/pull/2249).
=> Remove unnecessary required=False s in linode_v4 module

changelogs/fragments/2245-proxmox_fix_agent_string_handling.yml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
I noticed that when you enable options on KVM guest agents the inventory plugin started showing messages like:
```
[WARNING]:  * Failed to parse /root/projects/playground/inventory/proxmox.yml with
ansible_collections.community.general.plugins.inventory.proxmox plugin: invalid literal for int() with base 10:
'1,fstrim_cloned_disks=1'
```
I found it was caused by the feature added in (I just missed this testcase :-) ) #2148
proxmox.py
```paste below
```
=> Proxmox inv fix agent string parsing

changelogs/fragments/2223_nmcli_no_IP_config_on_slave.yaml, plugins/modules/net_tools/nmcli.py
The master interface holds the IP configuration. If we try to update the
IP configuration of the slaves, NetworkManager raises an error.
=> nmcli: do not set IP configuration bond slaves

changelogs/fragments/2230-java_keystore-1669-ssl-input-files-by-path.yml, plugins/modules/system/java_keystore.py, tests/integration/targets/java_keystore/defaults/main.yml, tests/integration/targets/java_keystore/tasks/main.yml, tests/integration/targets/java_keystore/tasks/prepare.yml, tests/integration/targets/java_keystore/tasks/tests.yml
This PR adds two options to the module, allowing one to generate the keystore from files stored on the target rather than files (or inline contents in playbooks) stored on the controller.
- `certificate` and *new* `certificate_path` are mutually exclusive, and one is required 
- `private_key` and *new* `private_key_path` are mutually exclusive, and one is required
Fixes #1669 
Refactor integration tests to play them twice.
Also refactor `DOCUMENTATION`
* Add useful info for better understanding of what options allow keystore regeneration on the fly, and what other options lead the module to fail, if their values change.
* Fix indentation, tenses, spelling.
* Add myself as author.
java_keystore
=> java_keystore: add `certificate_path` and `private_key_path` options

tests/utils/constraints.txt
This should fix the Python 2.6 problems in #2213.
tests/utils/constraints.txt
=> CI pip constraints file: fix problems with pip2.6 included in CentOS 6

changelogs/fragments/2244-hashids-filters.yml, plugins/filter/hashids.py, tests/integration/targets/filter_hashids/aliases, tests/integration/targets/filter_hashids/runme.sh, tests/integration/targets/filter_hashids/runme.yml, tests/integration/targets/filter_hashids/tasks/main.yml, tests/integration/targets/filter_hashids/vars/main.yml
Filters which implement the encode and decode methods from [hashids](https://github.com/davidaurelio/hashids-python) 
Fixes #1883 
plugins/filter/hashids.py
Valid inputs were adapted to play better with jinja:
- Single Integer input is wrapped as a singleton before being expanded so that input can be `int`, `(int,)`, or `[int]`
- Because input is a variable length list dereferenced dicts result in a null hash instead of throwing a type error
The initialization parameters `salt`, `alphabet`, and `min_length` work as expected without any changes.
=> New filter plugins: hashids_encode and hashids_decode

changelogs/fragments/2249-linode_v4-support-private_ip-option.yaml, plugins/modules/cloud/linode/linode_v4.py, tests/unit/plugins/modules/cloud/linode/test_linode_v4.py
This PR adds support for the `private_ip` parameter to the `linode.linode_v4` module.
The new parameter allows to enable private networking and to assign a private IPv4 IP upon instance creation.
`linode.linode_v4`
Linode docs about instance creation request body:
https://www.linode.com/docs/api/linode-instances/#linode-create__request-body-schema
=> linode_v4: add support for `private_ip` option.

changelogs/fragments/2257-ldap_entry-params.yml, plugins/modules/net_tools/ldap/ldap_entry.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
The parameter was removed in 11ef03e9dd1dc05fd80bbe74eafd89b3645965cf a year ago (first included in c.g 0.1.2), so I think it's ok to properly remove it for community.general 3.0.0. This also saves some ignore.txt lines :)
CC @russoz
ldap_entry
=> Remove ldap_entry's params option completely

changelogs/fragments/2262-java_keystore-passphrase.yml, plugins/modules/system/java_keystore.py, tests/integration/targets/java_keystore/tasks/tests.yml, tests/unit/plugins/modules/system/test_java_keystore.py
Fixes #1671. Completes what @quidame started in #2183.
java_keystore
=> java_keystore: overwrite instead of fail when password or alias does not match

plugins/modules/files/filesize.py, plugins/modules/filesize.py, tests/integration/targets/filesize/aliases, tests/integration/targets/filesize/defaults/main.yml, tests/integration/targets/filesize/tasks/basics.yml, tests/integration/targets/filesize/tasks/errors.yml, tests/integration/targets/filesize/tasks/floats.yml, tests/integration/targets/filesize/tasks/main.yml, tests/integration/targets/filesize/tasks/sparse.yml, tests/integration/targets/filesize/tasks/symlinks.yml
Moved from https://github.com/ansible-collections/ansible.posix/pull/148
New module `filesize` to create a file or resize it. This is a simple wrapper around `dd` that allows to grow or reduce (truncate) a file to any arbitrary size. Useful to manage swap files.
Supports `check_mode` and `diff`.
filesize
Example:
```yaml
- name: create/resize a swap file
filesize:
path: /var/swap
size: 2G
mode: u=rw,go=
group: root
owner: root
become: yes
diff: yes
```
=> new module: filesize - create or resize a file, given its size

changelogs/fragments/2224_nmcli_allow_MAC_overwrite.yaml, plugins/modules/net_tools/nmcli.py
Don't restrict the ability to manually set the MAC address to the
bridge. NetworkManager is able to set a static MAC address to the
vaste majority of the device types.
=> nmcli: manual overwrite MAC address for any devices

changelogs/fragments/2250-allow-keycloak-modules-to-take-token-as-param.yml, plugins/doc_fragments/keycloak.py, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/identity/keycloak/keycloak_client.py, plugins/modules/identity/keycloak/keycloak_clienttemplate.py, plugins/modules/identity/keycloak/keycloak_group.py, tests/unit/plugins/module_utils/identity/keycloak/test_keycloak_connect.py
This PR allow the module to receive either a token or the credentials for the authentication to make call to the Keycloak API . 
Also refactor `DOCUMENTATION` 
- Add an example a group creation with token 
`keycloak_group.py` 
`keycloak.py` 
```
=> Allow keycloak modules to take token as parameter for the auth. 

.github/BOTMETA.yml
https://github.com/ansible-collections/community.general/pull/1949#issuecomment-822471204
BOTMETA.yml
=> BOTMETA.yml: update team_virt

changelogs/fragments/2280-pids-new-pattern-option.yml, plugins/modules/system/pids.py, tests/integration/targets/pids/tasks/main.yml
A couple of new options `pattern` and `ignore_case` for the pids module to be able to retrieve PIDs for processes which contain the value supplied to `pattern`.
Fixes #756
plugins/modules/system/pids.py
My interpretation of #756 was for functionality equivalent to: (I usually see everything before the last pipe aliased as `psg`)
```bash
ps -ef | grep PATTERN | grep -v grep | awk '{print $2}'
```
In my experience this is used mostly as a plain substring test for finding particular `.jar.` or `.py` files so that is how it is implemented.
`.*` is treated as a special case which uses `psutil.pids()` to return all PIDs.
I played around with more pattern matching options, but passing user input to `re` is a llttle dangerous and it seems more reasonable at that point to …
=> pids module: Adding pattern and ignore_case options

plugins/lookup/filetree.py
The example code given deploys files with their .j2 extensions intact, which is probably not what you want.
Furthermore, the example code corrupts symlink target files to 0777 permissions.
`with_filetree`
=> `with_filetree:`: use `splitext` for compatibility with `template:`

changelogs/fragments/2259-proxmox-multi-nic-and-unsupported.yml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
Covers some edge cases that weren't taken into account. 
* Unsupported network-interface query even though agent is running (ex: Windows)
* Multiple network interfaces
* Network interfaces without IP addresses
* Allow us to control if we want to set ansible_host for proxmox nodes (in my case I have multiple primary nics, and it randomly cycles between them, until a more reliable way is found to dected the correct interface, this would allow us to not set the ansible_host ip)
inventory/proxmox
=> inventory/proxmox: Added some cases for unsupported network interface and multi-nic and unsupported guest error

changelogs/fragments/2308-terraform-add-plugin_paths-parameter.yaml, plugins/modules/cloud/misc/terraform.py
The list `plugin_paths` is used in the `init` phase of Terraform by setting the `-plugin-dir` command line argument to a path that contains Terraform plugins.
When the `-plugin-dir` argument is set, the plugin discovery and auto-download of Terraform is disabled.
This is useful when running Terraform in automation environments for testing where the production endpoints are strictly controlled or on air-gaped networks and you need to control the versions of plugins available.
terraform
The directory structure in the plugin path can be tricky. The [Terraform docs](https://learn.hashicorp.com/tutorials/terraform/automate-terraform#pre-installed-plugins) show a simple directory of files, but in testing that doesn't work, the directory structure has to follow the same …
=> Add plugin_paths parameter to terraform module.

changelogs/fragments/2329-hiera-lookup-plugin-return-type.yaml, plugins/lookup/hiera.py
Converts string returned by community.general.hiera lookup plugin to unicode.
community.general.hiera
On python3, this plugin returns an instance of 'bytes' instead of 'str'. This is because of the implementation of ansible.utils.cmd_functions.run_cmd function. This change converts the returned value to unicode string.
Reference: https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#string-encoding
=> convert string returned by plugin to unicode

changelogs/fragments/2340-jenkins_plugin-py2.yml, plugins/modules/web_infrastructure/jenkins_plugin.py
Resolves #1921.
I chose to only replace the non-binary `open()` call with `io.open()`, instead of globally replacing `open()` in that module by `io.open()`.
jenkins_plugin
=> jenkins_plugin: fix Python 2 compatibility issue

changelogs/fragments/2284-influxdb_retention_policy-idempotence.yml, plugins/modules/database/influxdb/influxdb_retention_policy.py
Fixes: #2281
Module `influxdb_retention_policy` is not idempotent. This is caused by incomplete analysis of both `duration` and `shard_group_duration` parameters. Only simple duration values are supported (`1h`, `2w`...), and because of that, complex values (like `1h30m15s`) are not taken into account when parsing user input and comparing it with the current server value.
InfluxDB allows those complex duration ranges and because of that, when querying server for existing retention policies, it returns a complex value like `1h0m0s` even if the original create query only specified `1h` as the value.
To solve this, both user input and server results are parsed and converted from duration strings to nanoseconds numbers and then compared. Also, `INF` values are considered as `0s` because …
=> influxdb_retention_policy: ensure duration parameters are idempotent (#2281)

.azure-pipelines/azure-pipelines.yml
As discussed in #ansible-devel and #ansible-community, this moves the stable CI runs to different times:
- 7 UTC ansible/ansible nightly runs,
- 8 UTC c.g main branch nightly run,
- 9 UTC most community collections (AZP) nightly runs,
- 10 UTC c.g stable-2 and stable-3 (active stable branches) nightly runs,
- 11 UTC c.g weekly run for old stable branches (right now stable-1) which only get important bugfixes and/or security fixes
@gundalow I've adjusted your suggestion a bit to avoid the other community collections, and I've implented a suggestion you already had earlier. Does this schedule make sense?
CC @relrod 
CI
=> CI: Spread nightly runs out

changelogs/fragments/2284-influxdb_retention_policy-fix_duration_parsing.yml, plugins/modules/database/influxdb/influxdb_retention_policy.py
A bug was introduced in my last PR (#2284) and it caused module failure when duration option was set to INF (a valid value) while creating or altering InfluxDB retention policies.
influxdb_retention_policy
Cherry-picked from #2385 so it can be backported to 3.0.1
=> influxdb_retention_policy: fix duration parsing to support INF values

changelogs/fragments/2348-composer-no-interaction-option-discovery-to-avoid-hang.yaml, plugins/modules/packaging/language/composer.py
Since the composer command provides a no-interaction option, and since
we always call it non-interactively, we should always use it.
The lack of this option caused composer to not exit at least in one
instance when called as 'php /usr/local/bin/composer help install'.
The '-n' added with this patch resolved that issue.
As far as I can tell from the open issues, I'm the first one to report this.
- composer
Versions and stuff.
On host:
```
$ uname -a
Linux pi 5.4.0-1034-raspi #37-Ubuntu SMP PREEMPT Mon Apr 12 23:14:49 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
$ php7.4 -v
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
$ …
```
=> composer: always use --no-interaction option

changelogs/fragments/2407-puppet-change_stdout_to_console.yaml, plugins/modules/system/puppet.py
Fixes https://github.com/ansible-collections/community.general/issues/1190
puppet
I guess it would be best if there could be an alias from `stdout` to `console` for now showing a deprecation warning, therefore users which have explicitly stated `stdout` (although it won't work) don't face issues with this change.
https://puppet.com/docs/puppet/7.6/man/agent.html
https://puppet.com/docs/puppet/6.22/man/agent.html
https://puppet.com/docs/puppet/5.5/man/agent.html
> `--logdest`
Where to send log messages. Choose between 'syslog' (the POSIX syslog service), 'eventlog' (the Windows Event Log), 'console', or the path to a log file.
=> puppet - replace stdout with console in logdest option

changelogs/fragments/2409-nmcli_add_slave-type_bridge_to_nmcli_command_if_type_is_bridge-slave.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
This should fix #2408: If type is `birdge-slave` then nmcli expects `slave-type brige` if any `bridge-port` settings are specified.
nmcli
=> nmcli: Add 'slave-type bridge' to nmcli command if type is bridge-slave

changelogs/fragments/2416-nmcli_compare_mac_addresses_case_insensitively.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
This should fix #2415: If the key in `conn_info` is either `bridge.mac-address` or `802-3-ethernet.cloned-mac-address` it compares the values (the current MAC from `nmcli connection show` address and the MAC address given as parameter to the `community.general.nmcli` module) in a case insensitive manner.  
nmcli
It also removes 'mac' from the list of potential parameter aliases:
https://github.com/ansible-collections/community.general/blob/main/plugins/modules/net_tools/nmcli.py#L1044
since that's already taken care of:
https://github.com/ansible-collections/community.general/blob/main/plugins/modules/net_tools/nmcli.py#L745
This avoids potential code duplication: The keys `bridge.mac-address` or `802-3-ethernet.cloned-mac-address` are (if present) always going to be …
=>  nmcli: Compare MAC addresses case insensitively

plugins/modules/files/xml.py
This change completes the documentation in community.general.xml module in regards of the use of yaml when adding a nested xml node with subnodes and/or attributes.
Nested node addition using "_" (to indicate sub nodes), and attributes are only documented in tests and issues, where is hard to find.
xml
The possibility of using this is not documented:
``` yml
add_children:
- node:
attribute: attribute_text
_:
- sub_node:
```
```paste below
```
=> 📝 Document nested node addition with "_" in xml module

changelogs/fragments/2430-linodev4-error-message.yml, plugins/modules/cloud/linode/linode_v4.py
Error message referred to Ansible's bugtracker URL in github. Changing to c.g.'s one.
plugins/modules/cloud/linode/linode_v4.py
=> linode_v4 - fixed error message

changelogs/fragments/2369-lvol_size_bug_fixes.yml, changelogs/fragments/2369-lvol_size_capitalization_bug_fix.yml, plugins/modules/system/lvol.py
Converted units to lowercase when using LVS or VGS command. 
Fixes #2360
Fixes #2370
lvol
```paste below
```
=> lvol - bug fix - Convert units to lowercase when using LVS or VGS command

plugins/modules/packaging/os/homebrew.py
- Just a lil' demo showing that we can utilize homebrew/cask/foo syntax
for given name of package to grab associated cask pacakge
Resolves: patch/sml-doc-example-update
Was encountering issues leveraging "homebrew_cask" realized that "homebrew" can also preform in the similar manner if given a certain syntax with the "name" property - so decided to make a small example to maybe demonstrate the use of installing cask based packages with "homebrew" if so desired
Just a little doc/example update, that may/or/may-not be useful for someone.
homebrew.py
```paste below
```
=> Small Documentation Example Of Cask Leveraging

changelogs/fragments/2454-detect_zfs_changed.yml, plugins/modules/storage/zfs/zfs.py
This change is inspired by https://github.com/ansible-collections/community.general/pull/502. I omitted the "diff mode" and focused on fixing the issue where the ZFS module incorrectly marks certain tasks as having been changed (also discussed in https://github.com/ansible-collections/community.general/issues/975)
For example, if a dataset has a quota of "1G" and the user changes it to "1024M", the actual quota vale has not changed, but since the module is doing a simple string comparison between "1G" and "1024M", it marks the step as "changed".
Instead of trying to handle all the corner cases of zfs (another example is when the zpool "altroot" property has been set, see https://github.com/ansible-collections/community.general/pull/502#discussion_r583994589), this change simply compares …
=> Avoid incorrectly marking zfs tasks as changed

changelogs/fragments/2334-redfish_config-skip-incorrect-attributes.yml, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/redfish/idrac_redfish_config.py, plugins/modules/remote_management/redfish/redfish_config.py
- plugins/module_utils/redfish_utils.py
- Modified `set_bios_attributes` function to skip invalid attribute instead of returning. Added skipped attributes to output
- plugins/modules/remote_management/redfish/idrac_redfish_config.py
- Modified `set_manager_attributes` function to skip invalid attribute instead of returning. Added skipped attributes to output
- Modified module exit to add warning variable
- plugins/modules/remote_management/redfish/redfish_config.py
- Modified module exit to add warning variable
Fixes #1995
Signed-off-by: Trevor Squillario Trevor_Squillario@Dell.com
idrac_redfish_config and redfish_config
```paste below
```
=> modified redfish_config and idrac_redfish_config to skip incorrect attributes

changelogs/fragments/2417-nmcli_remove_dead_code.yml, plugins/modules/net_tools/nmcli.py
This removes some dead code.
https://github.com/ansible-collections/community.general/blob/b10d707a8baa2530deb98a218c820762a2ce879a/plugins/modules/net_tools/nmcli.py#L1037-L1048
` _compare_conn_params` is only called from
https://github.com/ansible-collections/community.general/blob/b10d707a8baa2530deb98a218c820762a2ce879a/plugins/modules/net_tools/nmcli.py#L1096-L1101
However, `is_connection_changed` uses `connection_options` to construct the `options` dictionary
https://github.com/ansible-collections/community.general/blob/b10d707a8baa2530deb98a218c820762a2ce879a/plugins/modules/net_tools/nmcli.py#L718
and `connection_options` will never set any of the keys from `param_alias`.
nmcli
For reference: https://github.com/ansible-collections/community.general/pull/2416#p …
=> nmcli: Remove dead code, 'options' never contains keys from 'param_alias'

changelogs/fragments/2383-influxdb_retention_policy-add-state-option.yml, plugins/modules/database/influxdb/influxdb_retention_policy.py
Fixes: #2383
Add `state` parameter in module argument spec to support deletion of existing retention policies.
Also, simplify `duration` parsing logic as suggested on https://github.com/ansible-collections/community.general/pull/2284#discussion_r618210902.
~~A bug has also been discovered and fixed while developing the changes. It was introduced in my last PR (#2284) and it caused module failure when `duration` option was set to `INF` (a valid value).~~ (moved to #2396)
influxdb_retention_policy
```yaml
- name: create retention policy
community.general.influxdb_retention_policy:
database_name: test
policy_name: test
duration: 1h
replication: 1
state: present
- name: drop retention policy
community.general.influxdb_retention_policy:
database_name: test
policy_name: …
```
=> influxdb_retention_policy - add state argument to module spec (#2383)

plugins/modules/cloud/misc/proxmox_nic.py, plugins/modules/proxmox_nic.py, tests/integration/targets/proxmox/tasks/main.yml
Add proxmox_nic module to manage NIC's on Qemu(KVM) VM's in a Proxmox VE cluster.
Update proxmox integration tests and add tests for proxmox_nic module.
This partially solves https://github.com/ansible-collections/community.general/issues/1964#issuecomment-790499397
and allows for adding/updating/deleting network interface cards after
creating/cloning a VM.
The proxmox_nic module will keep MAC-addresses the same when updating a NIC. 
It only changes when explicitly setting a MAC-address.
I've created a separate module for handling the NIC's instead of updating the proxmox_kvm.py module.
This is done because it allows for cleaner and more manageable code. One can now manage NIC's separately.
When retrieving the VM config for a proxmox VM every piece of config is returned in one big …
=> Add proxmox_nic module

changelogs/fragments/2323-groupby_as_dict-filter.yml, plugins/filter/groupby.py, tests/integration/targets/filter_groupby/aliases, tests/integration/targets/filter_groupby/tasks/main.yml, tests/integration/targets/filter_groupby/vars/main.yml
This PR adds a filter `community.general.groupby_as_dict` which allows to transform a sequence of dictionaries into a dictionary of dictionaries indexed by one attribute.
Example:
```.yaml
sequence:
- key: value
foo: bar
- key: other_value
baz: bar
```
Then `sequence | community.general.groupby_as_dict('key')` gives the following dictionary:
```.yaml
value:
key: value
foo: bar
other_value:
key: other_value
baz: bar
```
groupby_as_dict
=> Add groupby_as_dict filter

changelogs/fragments/2505-proxmox_nic-set_mtu_on_interface_even_not_virtio.yml, plugins/modules/cloud/misc/proxmox_nic.py
I missed adding a comment about setting `mtu`. Again! :(
@Kogelvis First let me apologize for bugging you again and again on this option multiple times.
Even after #2449 has been merged :)
But do you think module should set `mtu` on proxmox nic and warn instead of just warning?
I know that this does not have any effect, but as you have said and tested proxmox allows setting this on other models which are not `virtio` although they don't work. Why shouldn't this module do this too?
plugins/modules/cloud/misc/proxmox_nic.py
=> proxmox_nic: set mtu on interface even if it's not virtio

changelogs/fragments/2485-java_keystore-ssl_backend-parameter.yml, plugins/modules/system/java_keystore.py, tests/integration/targets/java_keystore/tasks/main.yml, tests/integration/targets/java_keystore/tasks/tests.yml, tests/unit/plugins/modules/system/test_java_keystore.py
Adds a `ssl_backend` parameter to the 'java_keystore' module so that `cryptography` can be used as an alternative to the OpenSSL binary when loading keys/certs and generating pkcs12 bundles.
Fixes #1670
plugins/modules/system/java_keystore.py
- The module still defaults to OpenSSL as a backend for compatibility before eventual deprecation
- While adding support for `cryptography` the module has also been refactored to leverage an object data model to improve readability and reduce passing the same data with every function call.
-  With the new object structure temp file cleanup has also been moved into the destructor method.
-  Functionality to load DER formatted keys/certs has been implemented, but is not selectable by the user at this time.
- Future PR's could …
=> java_keystore: New ssl_backend option for cryptography

changelogs/fragments/1085-consul-acl-hcl-whitelist-update.yml, plugins/modules/clustering/consul/consul_acl.py
Fixes #1085 and all possible other tickets related to adding support for all ACL options
consul_acl
Full list of rules are here: https://www.consul.io/docs/security/acl/acl-rules
=> 1085 updating the hcl whitelist to include all supported options

changelogs/fragments/2499-influxdb_user-fix-multiple-no-privileges.yml, plugins/modules/database/influxdb/influxdb_user.py
**SUMMARY**
The current implementation iterates through the grants and removes the NO PRIVILEGE entries in the list.
However if a user has no privileges to 2 or more influx databases, the list will change size and there will always be 1 remaining NO PRIVILEGE entry in the list. This will result in an exception (error parsing query: found NO, expected READ, WRITE, ALL [PRIVILEGES] at line 1) when trying to revoke this privilege.
My proposed solution is to create a new list that excludes the NO PRIVILEGES entries in the first place.
**ISSUE TYPE**
**COMPONENT NAME**
influxdb_user
**ADDITIONAL INFORMATION**
To replicate:
Create 2 or more influx databases
Add influx User
=> Update influxdb_user.py Fixed Multiple No Privileges

changelogs/fragments/2518-nmap-fix-cache-disabled.yml, plugins/inventory/nmap.py
Code did not execute properly if cache setting is disabled
Fixes #2512
nmap
```paste below
```
=> nmap fix error when cache is disabled

tests/integration/targets/yum_versionlock/tasks/main.yml
They are currently failing because yum is waiting for an explicit yes/no input.
This makes both nightly CI runs fails, but also CI in #2525.
CI
=> Fix yum_versionlock tests

tests/integration/targets/yum_versionlock/tasks/main.yml
This test is failing on Fedora 34 and needs more investigation, this disables it for now.
CI
Also reverts change in https://github.com/ansible-collections/community.general/pull/2533 and puts a comment why.
=> yum_versionlock: disable fedora34 integration test

changelogs/fragments/2500-passwordstore-add_option_ignore_missing.yml, plugins/lookup/passwordstore.py, tests/integration/targets/lookup_passwordstore/tasks/tests.yml
Add ability to ignore error on missing pass file to allow processing the
output further via another filters (mainly the default filter) without
updating the pass file itself.
plugins/lookup/passwordstore.py
It is currently impossible to use the default filter to handle non-existent pass files if one uses read-only password store. This PR should fix that. This adds the ability to do following:
```paste below
- set_fact:
secret: "{{ lookup('passwordstore', 'secret ignore_missing=true') | default(default_secret, true) }}"                                                                                                  
```
=> Add option 'missing' to passwordstore lookup

changelogs/fragments/2540-zfs-delegate-choices.yml, plugins/modules/storage/zfs/zfs_delegate_admin.py
instead of whitelisting some subset of known existing permissions, just
allow any string to be used as permissions. this way, any permission
supported by the underlying zfs commands can be used, eg. 'bookmark',
'load-key', 'change-key' and all property permissions, which were
missing from the choices list.
zfs_delegate_admin
`ansible -b -vvvv -m zfs_delegate_admin -a 'name=z users=lauri permissions=bookmark' localhost`:
Before:
```
localhost | FAILED! => {
"everyone": false,
"name": "z",
"permissions": [
"bookmark"
],
"recursive": false,
"state": "present",
"users": [
"lauri"
]
}
},
"msg": "value of permissions must be one or more of: allow, clone, create, destroy, diff, hold, mount, promote, readonly, receive, …
```
=> zfs_delegate_admin: drop choices from permissions

changelogs/fragments/2526-java_keystore-password-via-stdin.yml, plugins/modules/system/java_keystore.py, tests/unit/plugins/modules/system/test_java_keystore.py
Follows up #1668 and #2177 
For whatever reason, I missed what *from stdin* is meaning (probably blinded by my habits with openssl or gpg, where `stdin` or file descriptor `0` are explicit arguments). There is no option to pass in secrets to `keytool` via stdin should be understood like: "secrets are passed in keytool via stdin when -storepass option is not used." 
java_keystore
=> java_keystore: pass in secret to keytool via stdin

changelogs/fragments/2514-mh-improved-changed.yml, plugins/module_utils/mh/base.py
Instead of overriding the `changed` property, by implementing a `__changed__()` method it gets automatically used.
=> ModuleHelper - better mechanism for customizing "changed" behaviour

changelogs/fragments/2364-influxdb_user-first_user.yml, plugins/modules/database/influxdb/influxdb_user.py
Fixes #2364
When starting an InfluxDB database with authentication enabled **and** no created users, InfluxDB automatically disables authentication for login but only allows `CREATE USER` queries.
Currently, `influxdb_user` module performs a series of check before executing that query, in order to ensure module idempotence, but it does not take into account that those checks fail on this specific scenario. As in this case we can be sure that we are creating and not updating an user (as we are sure that this user does not exist), we can safely bypass all checks if a 403 error is returned with an specific error message.
influxdb_user
InfluxDB returns 403 errors for any authorization (not authentication) issues. In this case, a 403 error is returned both if we are in …
=> influxdb_user: allow creation of first user with auth enabled (#2364)

changelogs/fragments/2517-cmd-params-from-vars.yml, plugins/module_utils/mh/mixins/cmd.py, plugins/modules/system/xfconf.py
`CmdMixin` now pulls the value for `run_command()` params from `self.vars`, as opposed to previously retrieving those from `self.module.params`.
=> ModuleHelper - cmd params now taken from self.vars instead of self.module.params

changelogs/fragments/2472_filesystem_module_revamp.yml, plugins/modules/system/filesystem.py, tests/integration/targets/filesystem/defaults/main.yml, tests/integration/targets/filesystem/tasks/create_device.yml, tests/integration/targets/filesystem/tasks/create_fs.yml, tests/integration/targets/filesystem/tasks/main.yml, tests/integration/targets/filesystem/tasks/overwrite_another_fs.yml, tests/integration/targets/filesystem/tasks/remove_fs.yml, tests/integration/targets/filesystem/tasks/setup.yml
This module has many holes (incomplete support for a feature, a filesystem, an OS, a version of something) that makes it hard to predict if it will work at any time except for ext2/3/4 fstypes on Linux.
Before to enhance this module in many ways (add of `diff` support, extend of `resizefs` support to fstypes allowing it, extend existing support for FreeBSD to all options of the module, drop dependency upon util-linux, allow the module to resize filesystems up and down, consistency between on-creation fs tunings and after, or whatever that could be requested by end-users or module's internal sanity and scope), this PR pretends to prepare next steps and give them a more consistent and clear starting point.
It is not intended to modify module's behavior.
filesystem …
=> filesystem: revamp module

changelogs/fragments/2525-iptables_state-fix-initialization-command.yml, plugins/action/system/iptables_state.py, plugins/modules/system/iptables_state.py
This PR fixes 2 function design flows (in the same function):
- Don't modify the value of a variable that is reused at each iteration (per-table) of the loop to avoid cumulative arguments over the loop.
- Use a more neutral command (`iptables -L` rather than `iptables-restore`, no need of temporary files) to load per-table needed modules.
Also cleanup code (pylints and a FutureWarning about regexp).
Fixes #2523 
iptables_state
=> iptables_state: fix per-table initialization command

changelogs/fragments/2524-pacman_add_bin_option.yml, plugins/modules/packaging/os/pacman.py
There are some nice [AUR helpers](https://wiki.archlinux.org/index.php/AUR_helpers) that extend the pacman interface and can be used interchangeably with pacman. This PR adds the option to specify the binary to be used, when executing package queries on Arch Linux.
pacman
With this PR an AUR package can be easily installed using [YAY](https://github.com/Jguer/yay). In this example the user needs to provide a non-root user with the privileges to install packages, otherwise yay will refuse to work:
```yaml
tasks:
- pacman:
state: present
name: foo
bin: yay
extra_args: --noconfirm --builddir /tmp/yay-build
become_user: yay
```
=> pacman: add 'executable' option to use an alternative pacman binary

changelogs/fragments/2564-mh-cmd-process-output.yml, plugins/module_utils/mh/mixins/cmd.py
`CmdMixin.run_command()` now accepts a `process_output` parameter specifying a function to process the outcome of the underlying `module.run_command()`.
=> ModuleHelper: CmdMixin custom function for processing cmd results

changelogs/fragments/2556-add-comment_visibility-parameter-for-comment-operation-of-jira-module.yml, plugins/modules/web_infrastructure/jira.py
This change includes the additional parameter for the jira module. When operation is set to comment, comment_visibility will be used to limit the visibility of the comment. JIRA itself provide 2 means for declaring the visibility: group and role. The parameter needs to include the type and value fields. For this reason the parameter is not simple but rather a dict.
Replaces: #2555
jira
For more information on visibility of comments in JIRA please see Visibility object under following section:
https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-comments/#api-rest-api-2-issue-issueidorkey-comment-post
=> Add comment_visibility parameter for comment operation for jira module

changelogs/fragments/2560-java_cert-pkcs12-alias-bugfix, changelogs/fragments/2560-java_cert-pkcs12-alias-bugfix.yml, plugins/modules/system/java_cert.py, tests/integration/targets/java_cert/tasks/state_change.yml
fix wrong certificate alias used when importing pkcs12
error message is now displaying  stdout instead of stderr, it was leading to misunderstanding (keytool related behavior)
modify test 
java_cert
Fixes #2374
=> java_cert - fix incorrect certificate alias on pkcs12 import

changelogs/fragments/2571-rhsm_release-fix-release_matcher.yaml, plugins/modules/packaging/os/rhsm_release.py, tests/unit/plugins/modules/packaging/os/test_rhsm_release.py
This is Tong He from Red Hat MPQE Entitlement QE Team.
At present, the release_matcher in rhsm_release.py considers 8, 7Client and 7Workstation as invalid releases then resists to set these values as release version. However these 3 values are valid releases corresponding on RHEL 8, RHEL 7 Client and RHEL 7 Workstation. Hence, this PR modifies the release_matcher in rhsm_release.py and adjusts the relevant test case to fix this issue.
rhsm_release
At present, when we try to set release 8 through the rhsm_release module, the playbook fails with the following message:
```
"release": "8"
}
},
"msg": "\"8\" does not appear to be a valid release."
}
```
This is unexpected since 8 is a …
=> rhsm_release: Fix the issue that rhsm_release module considers 8, 7Client and 7Workstation as invalid releases

changelogs/fragments/2590-netcup_dns-exception-no-message-attr.yml, plugins/modules/net_tools/netcup_dns.py
The `netcup_dns` module currently wraps most of its interaction with the `nc_dnsapi` Python package in a try-catch.
In the catch-clause it assumes that every exception that could be thrown has a `message` attribute, which is not true.
If `nc_dnsapi` throws an exception of a type that doesn't have a `message` attribute, the exception handling itself fails as well:
```
AttributeError: 'Exception' object has no attribute 'message'
```
This PR changes the source of the exception string from `ex.message` to `str(ex)`, because the second one is guaranteed to always return some form of string representation of the message, regardless of which attributes the exception object has.
netcup_dns
```
File …
```
=> [netcup_dns] Use str() to get exception message

changelogs/fragments/json_query_more_types.yml, plugins/filter/json_query.py
Added missing types for list and dicts, previously we had fixed the 'strings' issue
filters/json_query
=> json_query, no more 'unkown type' errors

changelogs/fragments/2510-jenkins_plugin_use_post_method.yml, plugins/modules/web_infrastructure/jenkins_plugin.py
Jenkins makeEnable/makeDisable api requests requires to use POST method
Fixes #2510 
jenkins_plugin
```paste below
```
=> jenkins_plugin: HTTP Error 405: Method Not Allowed on disable/enable plugin #2510

changelogs/fragments/2579-redis-cache-ipv6.yml, plugins/cache/redis.py, tests/unit/plugins/cache/test_redis.py
Improved the parsing of the connection string, from `.split(':')` to a regexp.
Fixes #497 
plugins/cache/redis.py
=> redis cache - better parsing of connection uri

plugins/lookup/tss.py
Adds a description of how to use the TSS lookup in a one-liner.
tss
I spent several days bashing my head against a wall trying to understand why trying to access `['items']` gave the following error:
```
The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'items'
```
Eventually I found out this was because the object was just a string, not an interpreted variable yet.
If this one-liner lookup example would be in the documentation, it would've saved me multiple days of screaming into the void hoping for it to return my desperate cries for help.
Please consider merging this to protect the sanity of the next person who needs to retrieve data from Thycotic.
=> Add one-liner lookup example

tests/integration/targets/iptables_state/aliases
Disable tests until #2627 is fixed, so that CI will run through again and not block other PRs.
iptables_state
=> Temporarily disable iptables_state tests

changelogs/fragments/2573-terraform-overwrite-init.yml, plugins/modules/cloud/misc/terraform.py
When a Terraform workspace is already _init_, with a foreign backend creds (by S3 creds from another workspace), Terraform fails to redo _init_.
Init can be skipped if the local statefile already exists.
terraform
Context:
By using workspaces and s3 backend, the `.terraform/terraform.tfstate` is a single file having properties to target a S3 bucket.
The S3 object is specific for each workspace (workspace name is part of object path)
Based on current shell AWS environment creds, the owner of the S3 object is subject to be specific, which makes an issue during init step, before Ansible Terraform module does workspace switch.
How to reproduce issue:
- deploy an empty terraform project with 2 workspaces + s3 backend for state
- ensure the init are using segregated IAM S3 …
=> Terraform overwrite init

plugins/modules/net_tools/haproxy.py
The HAproxy module example for the `drain` usage does not match its associated comment.
haproxy
The drain code example would wait one second and expire after one minute while the comment describe a one minute waiting time and an expiration after one hour.
=> HAproxy - Fix drain example with correct wait_interval value

changelogs/fragments/2557-cloud-misc-refactor.yml, plugins/modules/cloud/misc/cloud_init_data_facts.py, plugins/modules/cloud/misc/proxmox_group_info.py, plugins/modules/cloud/misc/proxmox_kvm.py, plugins/modules/cloud/misc/rhevm.py, plugins/modules/cloud/misc/serverless.py, plugins/modules/cloud/misc/terraform.py
Minor refactors on modules under `plugins/modules/cloud/misc`
plugins/modules/cloud/misc/cloud_init_data_facts.py
plugins/modules/cloud/misc/proxmox_group_info.py
plugins/modules/cloud/misc/rhevm.py
plugins/modules/cloud/misc/serverless.py
=> minor refactors on plugins/modules/cloud/misc

changelogs/fragments/2648-proxmox_kvm-fix-vmid-return-value.yml, plugins/modules/cloud/misc/proxmox_kvm.py
Updating VMID value for exit result when VM with `name` already exists. Previous behavior just returned the next id from the cluster sequence.
Fixes #2636
- If there are two VM's with the same name in the cluster it is still possible that the vmid result will be incorrect.
=> proxmox_kvm - Fixed vmid result when VM with name exists

changelogs/fragments/2616-archive-exclusion_patterns-option.yml, plugins/modules/files/archive.py, tests/integration/targets/archive/tasks/main.yml
Adding `exclusion_patterns` as an option to `archive` which will allow files/directories to be excluded from the archive itself rather than just excluding the source paths via `exclude_paths`. (See [here](https://github.com/ansible-collections/community.general/issues/2587#issuecomment-846425465) for more context)
- The use of `zipfile`  for `format=zip` makes the implementation slightly more cumbersome, but still extensible.
- However the `tarfile` filter function is very powerful so future features utilizing the filter may present issues for zips
- The filter is not applied in the single file case though it could be. (I guess that could be useful under certain contexts
=> archive - Adding exclusion_patterns option

changelogs/fragments/2635-nmcli-add-ignore-auto-arguments.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
nmcli: new arguments to ignore automatic dns servers and gateways
Closes #1087
nmcli
Manually tested. With the following task:
```YAML
- name: configure ethernet connection
conn_name: Ethernet
state: present
method4: auto
method6: auto
dns4_ignore_auto: true
dns6_ignore_auto: true
```
I got the following output from nmcli:
```
$ LANG=en_US.UTF-8 nmcli connection show Ethernet | grep ignore
ipv4.ignore-auto-routes:                no
ipv4.ignore-auto-dns:                   yes
ipv6.ignore-auto-routes:                no
ipv6.ignore-auto-dns:                   yes
```
And in nm-connection-editor, I got "Automatic (DHCP) addresses only" and "Automatic, addresses only" in "IPv4 Settings" and "IPv6 Settings", respectively.
=> nmcli: new arguments to ignore automatic dns servers and gateways

changelogs/fragments/2661-maven_artifact-add-sha1-option.yml, plugins/modules/packaging/language/maven_artifact.py
Fixes #2661 by adding a `checksum_alg` option. This option defaults to `md5` so that exiting users should be unaffected. `checksum_alg: sha1` can be added to use SHA1 as the checksum algorithm, which is allowed on FIPS systems.
maven_artifact
```paste below
$ cat download_war.yml
- name: test file
collections:
- community.general
tasks:
- name: Download war file
maven_artifact:
group_id: org.mybatis
artifact_id: jpetstore
extension: war
repository_url: https://nexus/repository/maven-snapshots/
dest: /home/centos/jpetstore.war
verify_checksum: always
$ ansible-playbook -i localhost ./download_war.yml
[WARNING]: Unable to parse /home/centos/localhost as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost …
```
=> Added SHA1 option to maven_artifact

changelogs/fragments/keycloak-realm-no-log-password-reset.yml, plugins/modules/identity/keycloak/keycloak_realm.py
This value is not sensitive but Ansible will complain about it otherwise
keycloak_realm
Using this module before the change:
```
[WARNING]: Module did not set no_log for reset_password_allowed
ok: [molecule_instance_1]
```
After the change:
```
ok: [molecule_instance_1]
```
=> keycloak_realm.py: Mark 'reset_password_allowed' as no_log=False

changelogs/fragments/keycloak_realm_ssl_required.yml, plugins/modules/identity/keycloak/keycloak_realm.py
The `ssl_required` parameter is a string and must be one of 'all',
'external' or 'none'. Passing a bool will make the server return a 500.
keycloak_realm
See https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_realmrepresentation for the representation. Sadly the values are not present here. One can see them by spawning a keycloak server and going to any realm, then 'login' and there is a dropdown with the actual text values.
Let me know if you prefer an issue first!
I was also not sure how to write tests for this since there doesn't seem to be any integration tests I could find?
=> keycloak_realm.py: Fix the `ssl_required` parameter according to the API

.github/BOTMETA.yml
Remove myself as maintainer from the zypper_repository module.
See #1985.
=> BOTMETA.yml: remove myself from zypper_repository

plugins/modules/packaging/os/pacman_key.py, plugins/modules/pacman_key.py, tests/unit/plugins/modules/packaging/os/test_pacman_key.py
Manage [pacman](https://wiki.archlinux.org/index.php/Pacman)'s keyring of trusted keys with [pacman-key](https://wiki.archlinux.org/index.php/Pacman/Package_signing). Similar to the [apt_key](https://docs.ansible.com/ansible/latest/modules/apt_key_module.html) & [rpm_key](https://docs.ansible.com/ansible/latest/modules/rpm_key_module.html) modules. Useful when adding additional repositories that have signed packages/databases.
pacman_key
EDIT: This is originally from this [PR](https://github.com/ansible/ansible/pull/68232) on ansible/ansible.
=> add module pacman_key

changelogs/fragments/2634-terraform-switch-workspace.yml, plugins/modules/cloud/misc/terraform.py
When terraform apply is failing (topology syntax valid, but unable to complete change), the module ends without resetting the workspace.
Instead of relying on `module.run_command()` exception, this PR resets workspace and renders equivalent output.
terraform
How to reproduce:
The following playbook + topology is expected to fail, since "test" bucket name is not available.
Run and check if topology workspace is back to "default" after the playbook failure.
```paste below
tasks:
- community.general.terraform:
workspace: "foo"
state: "present"
resource "aws_s3_bucket" "main" {
bucket = "test"
}
```
There is still an issue if the **plan** fails, IMHO this needs little refactoring to improve workspace switching.
=> Terraform: ensure workspace is reset to current value

changelogs/fragments/2124-consul_kv-pass-token.yml, changelogs/fragments/2126-consul_kv-pass-token.yml, plugins/lookup/consul_kv.py
a first contribution attempt: 
/lookup/consul_kv.py should now use it's exsistent parameter token,
if provided. 
plugins/lookup/consul_kv.py
see [issue comment](https://github.com/ansible-collections/community.general/issues/2124#issuecomment-808799307)
=> Wire token param into consul_api #2124

.github/BOTMETA.yml
After https://github.com/ansible-collections/community.general/pull/2739 has been merged, `supershipit` is no longer needed.
https://github.com/ansible-collections/community.general/pull/2739#issuecomment-855946775
=> Remove aminvakil from supershipit section as it is not needed anymore

changelogs/fragments/2722-zypper_repository-fix_idempotency_on_adding_repo_with_releasever.yml, plugins/modules/packaging/os/zypper_repository.py, tests/integration/targets/zypper_repository/tasks/zypper_repository.yml
Fixes https://github.com/ansible-collections/community.general/issues/1985
I'm not sure about this being a bugfix or feature request, please let me know if I should change it.
=> zypper_repository: fix idempotency on adding repo with releasever and basearch variables

tests/unit/plugins/inventory/test_cobbler.py, tests/unit/plugins/inventory/test_linode.py, tests/unit/plugins/inventory/test_lxd.py, tests/unit/plugins/inventory/test_proxmox.py, tests/unit/plugins/inventory/test_stackpath_compute.py
This PR adds a positive unit test for the inventory plugin function `verify_file`. So far there was only a negative test (non-existing config file)
- tests/unit/plugins/inventory/test_cobbler.py
- tests/unit/plugins/inventory/test_linode.py
- tests/unit/plugins/inventory/test_lxd.py
- tests/unit/plugins/inventory/test_proxmox.py
- tests/unit/plugins/inventory/test_stackpath_compute.py
=> add inventory plugin unit test `test_verify_file`

changelogs/fragments/2771-scaleway_inventory_json_accept_byte_array.yml, plugins/inventory/scaleway.py
Fix error `JSON error object must be str, not 'bytes'` : issue #2769 
Before the change :
```paste below
ansible-inventory [core 2.11.1] 
configured module search path = ['/home/loic/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /home/loic/.local/lib/python3.5/site-packages/ansible
ansible collection location = /home/loic/.ansible/collections:/usr/share/ansible/collections
executable location = .local/bin/ansible-inventory
python version = 3.5.3 (default, Apr  5 2021, 09:00:41) [GCC 6.3.0 20170516]
jinja version = 2.11.3
libyaml = False
No config file found; using defaults
setting up inventory plugins
host_list declined parsing …
```
=> [scaleway inventory] Fix JSON object must be str, not 'bytes'

changelogs/fragments/1942_timezone.yml, plugins/modules/system/timezone.py
Convert warning message to debug when timedatectl found but not usable.
Fixes: #1942
plugins/modules/system/timezone.py
=> timezone: change warning to debug

changelogs/fragments/2779_redhat_subscription-add_server_prefix_and_server_port.yml, plugins/modules/packaging/os/redhat_subscription.py, tests/unit/plugins/modules/packaging/os/test_redhat_subscription.py
This is Tong He from Red Hat MPQE Entitlement QE Team.
server.prefix and server.port are two arguments in 'subscription-manager config' but now not supported in this module. As I see more than one requests mentioning these, I think it is valuable to add these two as supported arguments.
This PR is in response to and implements the following feature requests:
Fixes https://github.com/ansible-collections/community.general/issues/1311
https://bugzilla.redhat.com/show_bug.cgi?id=1766342
An example of the contents in subscription-manager config:
```paste below
[server]
hostname = [subscription.rhsm.redhat.com]
insecure = [0]
no_proxy = []
port = [443]
prefix = [/subscription]
proxy_hostname = []
proxy_password = []
proxy_port = []
proxy_scheme = …
```
=> redhat_subscription: Add server_prefix and server_port as supported arguments

changelogs/fragments/2790-callback_splunk-batch-option.yml, plugins/callback/splunk.py, tests/unit/plugins/callback/test_splunk.py
Adding `batch` parameter as a user-configurable correlation id to associate multiple playbook executions. 
Fixes #2778
plugins/callback/splunk.py
Open to suggestions for the option and/or JSON attribute name.
=> callback_splunk - Add user-configurable event correlation id

CONTRIBUTING.md
As https://github.com/ansible/community-docs/pull/18 has renamed the filename, this fixes CONTRIBUTING.md here.
CONTRIBUTING.md
=> Rename test_pr_quick_start_guide.rst to test_pr_locally_guide.rst

changelogs/fragments/2774-datadog_event_api_parameter.yml, plugins/modules/monitoring/datadog/datadog_event.py
Users need the ability to define an API endpoint for the datadog_event Ansible module to send data to. By default, it sends to ``api.datadog.com`` which is not necessarily always the case. 
This change is to add an optional ``api_host`` parameter to pass to the module in order for the events to reach the right location. 
This is related to issue #2774 
datadog_event
The change mainly targets ``plugins/modules/monitoring/datadog/datadog_event.py`` to allow users to define datadog ``api_host`` in their playbooks
As a result of this change, the playbook now would accept ``api_host`` as an optional parameter for datadog_event module where it takes a string value. Example playbook after this change:
```yaml (paste below)
---
- name: Test
tasks:
- name: …
```
=> datadog_event : Adding api_host as an optional parameter

changelogs/fragments/2821-ipa_sudorule.yml, plugins/modules/identity/ipa/ipa_sudorule.py
fix sudorule_add_allow_command_group is not working on freeIPA 4.8.7 at least, sudorule_add_allow_command should be used instead with item sudocmdgroup
Fixes #2442
ipa_sudorule
Before
```
"msg": "response sudorule_add_allow_command_group: unknown command 'sudorule_add_allow_command_group'"
```
After, message is gone and request is processed correctly in FreeIPA Server
=> fix sudorule_add_allow_command_group

changelogs/fragments/2830-npm-version-update.yml, plugins/modules/packaging/language/npm.py, tests/unit/plugins/modules/packaging/language/test_npm.py
When the `version` property is used in the `npm` plugin, the comparison of installed vs missing will be used as `name@version` instead of just `name`, allowing for version specific updates.
Fixes #2021 
npm
```paste below
```
=> npm - fix updating version specific modules

changelogs/fragments/2732-nmcli_add_options.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Add option `routing_rules4` and `may_fail4` which translates to `ipv4.routing-rules` and `ipv4.may-fail` respctively.
Add `disabled` option to method6 to be able to completely disabled IPv6.
Fixes #2730 
=> Nmcli add options

changelogs/fragments/2841-proxmox_kvm_zfs_devstr.yml, plugins/modules/cloud/misc/proxmox_kvm.py, tests/unit/plugins/modules/cloud/misc/test_proxmox_kvm.py
ZFS-backed block devices may contain just the bare device name and
not have extra options like `,size=foo`, `,format=qcow2` etc. This
breaks an assumption in existing regex (which expects a comma).
Support such device strings and add a couple of testcases to validate.
Fixes #2840
proxmox_kvm
```
---
- name: Deploy VMs
hosts: bigpve
tasks:
- name: Create new minimal VM
community.general.proxmox_kvm:
api_password: "<redacted>"
api_host: bigpve
name: testvm
node: bigpve
proxmox_default_behavior: no_defaults
vmid: 1001
scsihw: virtio-scsi-pci
scsi:
scsi0: "local-zfs:vm-1001-disk-0"
net:
net0: 'virtio,bridge=vmbr0'
bootdisk: scsi0
```
On execution, it returns:
```
The full traceback is:
File "/tmp/ansible_community.general.proxmox_kvm_payload_mqneu62g/an …
```
=> proxmox_kvm: Fix ZFS device string parsing

changelogs/fragments/2844-ali_instance_info-deprecate-params.yml, plugins/modules/cloud/alicloud/ali_instance_info.py
Parameters were already marked as deprecated - pinning version 5.0.0 for removal.
Fixes #2429 
plugins/modules/cloud/alicloud/ali_instance_info.py
=> ali_instance_info - marked parameters for deprecation in c.g. 5.0.0

changelogs/fragments/2841-proxmox_kvm_zfs_devstr.yml, plugins/modules/cloud/misc/proxmox_kvm.py, tests/unit/plugins/modules/cloud/misc/test_proxmox_kvm.py
ZFS-backed block devices may contain just the bare device name and
not have extra options like `,size=foo`, `,format=qcow2` etc. This
breaks an assumption in existing regex (which expects a comma).
Support such device strings and add a couple of testcases to validate.
Manually backport of #2841
=> [backport][stable-2] proxmox_kvm: Fix ZFS device string parsing (#2841)

changelogs/fragments/2691-gitlab_user-support-identity-provider.yml, plugins/modules/source_control/gitlab/gitlab_user.py
This change includes the functionality to add and identity provider and the external UID that is required to use an external provider (e.g. Keycloak, google_oauth2, ...).
With this change I also included the option `reset_pasword` because either `password` or `reset_password` is required by the GitLab API. If you use an external identity provider you don't want/need to set a password so that is why the `reset_password` was mandatory for this change.
- `gitlab_user`
This module changes are for people who want to connect their external identity provider with a GitLab user.
You can add users with or without external provider now.
```paste below
TASK [Create GitLab user] ***************************************************************************************************** …
```
=> gitlab_user: add support for identity provider

tests/utils/shippable/shippable.sh
One problem with the flatmapping approach (symlinks) in community.general is that integration tests do not count for code coverage in plugins/modules and plugins/action (the other plugins/ directories are considered correctly). This is because Ansible loads code from the symlinks and the symlinks are reported as the filename, and not the file they link to. By temporarily adding meta/runtime.yml redirects during integration testing, at least ansible-base and ansible-core will use the real modules (and action plugins) instead of the symlinks, and thus code coverage will be reported correctly.
CI
=> Dynamically add meta/runtime.yml redirects for integration tests to correctly report coverage

changelogs/fragments/2850-jenkins_build-support-stop-jenkins-build.yml, plugins/modules/web_infrastructure/jenkins_build.py, tests/unit/plugins/modules/web_infrastructure/test_jenkins_build.py
The jenkins_build module at present has only 2 states support to create or delete a Jenkins job build. However python-jenkins, which jenkins_build module based on, support not only create and delete a Jenkins job, but also stop a running Jenkins job. Stopping a running Jenkins job is not that common comparing to creation or deletion, but still useful as sometimes people might encounter a weird situation that their Jenkins job runs 'forever'. 
So this PR mainly aims to support stop a running Jenkins build (adding a state 'stopped' to support this). Meanwhile I enrich the document content and test cases.
jenkins_build
Below is the source code of python-jenkins 0.4.12, the stop_build function is already inside so the dependencies remain the same. …
=> jenkins_build: Support stop a running Jenkins build

changelogs/fragments/2816-archive-refactor.yml, plugins/modules/files/archive.py, tests/integration/targets/archive/tasks/main.yml, tests/integration/targets/archive/tasks/remove.yml
`archive` has become difficult to maintain and debug so this PR seeks to refactor the module and in the process eliminate some obvious bugs.
Fixes #2818 
The existing issues with `archive` exposed during refactoring seem related to three core problems:
1. Internal state management
- Archive state is maintained throughout `main` and used both for control flow and to pass information in the `result` dict ~~(Since `state` will continue to be returned by the module with the same values I just changed the name of the intended result value to `dest_state`)~~
- The `result` dict will never show this information however because implementing `path` or `dest` as options causes `AnsibleModule` to overwrite `state` to the file state. (See …
=> archive - refactor and bugfix

changelogs/fragments/2867-redis-terminology.yml, plugins/modules/database/misc/redis.py, tests/integration/targets/redis_info/defaults/main.yml, tests/integration/targets/redis_info/tasks/main.yml, tests/integration/targets/setup_redis_replication/defaults/main.yml, tests/integration/targets/setup_redis_replication/handlers/main.yml, tests/integration/targets/setup_redis_replication/tasks/setup_redis_cluster.yml
In 2018, Redis started replacing `slave` with `replica` (https://github.com/redis/redis/issues/5335). The module still forces users to use `slave`. Let's change that!
redis
=> Redis: slave -> replica

changelogs/fragments/2843-modprobe-failure-conditions.yml, plugins/modules/system/modprobe.py, tests/unit/plugins/modules/system/test_modprobe.py
Fixed bug where false changes are reported for builtin modules on downstreams of `debian`
Fixes #1608 
plugins/modules/system/modprobe.py
- Minor refactor to facilitate reuse of module status checks
- Included warn statement to report why `modprobe` cannot load the module
- Added units for this module to cover these cases
=> modprobe - fix task status when module cannot be loaded

changelogs/fragments/2883-_mount-fixed-sanity-checks.yml, plugins/module_utils/_mount.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
Copying from https://github.com/ansible-collections/ansible.posix/blob/main/plugins/module_utils/mount.py the file `_mount.py` is no longer triggering sanity checks.
plugins/module_utils/_mount.py
=> _mount module utils - fixed sanity checks

changelogs/fragments/2883-_mount-fixed-sanity-checks.yml, plugins/module_utils/_mount.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
Backport of #2883 to stable-3.
plugins/module_utils/_mount.py
=> [stable-3] _mount module utils - fixed sanity checks

changelogs/fragments/2883-_mount-fixed-sanity-checks.yml, plugins/module_utils/_mount.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
Backport of #2883 to stable-2.
plugins/module_utils/_mount.py
=> [stable-2] _mount module utils - fixed sanity checks

changelogs/fragments/2874-terraform-check-destroy.yml, plugins/modules/cloud/misc/terraform.py
Adding a safety-check parameter - will not allow execution when resources are destroyed. This was coded originally in #398 by @effaamponsah.
=> terraform - added check_destroy

changelogs/fragments/2516_fix_2515_keystore_type_jks.yml, plugins/modules/system/java_keystore.py, tests/integration/targets/java_keystore/tasks/tests.yml, tests/unit/plugins/modules/system/test_java_keystore.py
This PR ensures the created keystore is of type JKS by adding an explicit `-deststoretype jks` (needed with keytool from OpenJDK 11)
Fixes #2515 
java_keystore
=> java_keystore: fix keystore type

plugins/modules/packaging/os/pacman.py
Adds description for the parameter options in state. Mostly copied from yum docs since the options are identical there.
Fixes #2889
pacman
=> pacman: Descriptive state documentation

changelogs/fragments/2827-nmcli_fix_team_slave.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Current collection doesn't work properly creating team-slaves.
```
failed: [localhost] (item={'conn_name': 'eno1', 'ifname': 'eno1', 'master': 'team2'}) => {"ansible_loop_var": "item", "changed": false, "item": {"conn_name": "eno1", "ifname": "eno1", "master": "team2"}, "msg": "Error: Failed to modify connection 'eno1': connection.slave-type: Cannot set 'master' without 'slave-type'\n", "name": "eno1", "rc": 1}
```
The patch fixes this and allows the proper configuration of slaves.
```
changed: [localhost] => (item={'conn_name': 'eno1', 'ifname': 'eno1', 'master': 'team2'})
```
Fixes #766
nmcli
```
---
vars:
nmcli_team_slave:
- conn_name: eno1
ifname: eno1
master: team2
tasks:
- name: Add an Team connection with static IP configuration …
```
=> [nmcli] add connection.slave-type for teamed devices

changelogs/fragments/1334-jenkins-plugin-fallback-urls.yaml, plugins/modules/web_infrastructure/jenkins_plugin.py, tests/unit/plugins/modules/web_infrastructure/test_jenkins_plugin.py
Motivation: Jenkins had down time in their plugin repository for a couple of days ( https://issues.jenkins.io/browse/INFRA-2811 )
The solution proposed in this PR enables several fallback options, which are customable, and do not require active engineer involvement for future down times from Jenkins' side.
What's implemented:
1.  updates_url is now a list of strings, instead of a string. In case of failure, the next items in list are tried. Ansible's input validation automatically converts strings to a list with a single string item, so this is backwards compatible.
2. Two new input variables, latest_plugins_url and versioned_plugins_url, which create separation between the updates json file and downloadable plugin urls. These are list of strings as well, and the fallback behaviour is the …
=> Add fallback url for jenkins plugin

changelogs/fragments/2904-fix-bug-when-2-identical-executions-in-same-auth-flow.yml, plugins/modules/identity/keycloak/keycloak_authentication.py, tests/unit/plugins/modules/identity/keycloak/test_keycloak_authentication.py
Currently impossible to create an authentication flow with 2 identical executions. If two execution with same name it will result as a single execution in the Keycloak configuration. 
This PR is solving this issue. 
For example : 
```paste below
- name: Create an authentication flow with 2 identical execution.
community.general.keycloak_authentication:
auth_keycloak_url: http://localhost:8080/auth
auth_username: admin
auth_password: password
realm: master
alias: "two_identical_exec"
copyFrom: "first broker login"
authenticationExecutions:
- providerId: "test-execution1"
requirement: "REQUIRED"
- displayName: "test-execution1"
requirement: "REQUIRED"
```
Would create only 1 execution "test-execution1" in the "two_identical_exec" authentication flow. …
=> Fix bug when 2 identical executions in same auth flow

tests/integration/targets/snap/aliases, tests/integration/targets/snap/tasks/main.yml
Quick basic integration tests for snap (only ubuntu and fedora right now)
This will fail right now until #2906 has been fixed.
=> Add integration tests for snap

changelogs/fragments/2816-archive-refactor.yml, plugins/modules/files/archive.py, tests/integration/targets/archive/tasks/main.yml, tests/integration/targets/archive/tasks/remove.yml
Manual Backport of #2816 into stable-2
archive has become difficult to maintain and debug so this PR seeks to refactor the module and in the process eliminate some obvious bugs.
Fixes #2818
The existing issues with archive exposed during refactoring seem related to three core problems:
1. Internal state management
- Archive state is maintained throughout main and used both for control flow and to pass information in the result dict (Since state will continue to be returned by the module with the same values I just changed the name of the intended result value to dest_state)
- The result dict will never show this information however because implementing path or dest as options causes AnsibleModule to overwrite state to the file state. (See here)
- In addition the …
=> [backport][stable-2] archive - refactor and bugfix (#2816)

tests/integration/targets/snap/tasks/main.yml
Tests should pass after https://github.com/ansible-collections/community.general/pull/2918 has been merged.
Also I've added `classic` to remove as well, I guess that should not have any effect? If it does this should be documented.
=> Add integration test for classic snap

changelogs/fragments/2923-archive-remove-bugfix.yml, plugins/modules/files/archive.py, tests/integration/targets/archive/tasks/remove.yml
Fixes a bug introduced in #2816 which causes false failures when recursively removing files added to `tar` archives.
Fixes #2919
Pre-refactor the module never entered the following segment of code:
```python
if os.path.isdir(path):
shutil.rmtree(path)
```
This is because sub-directories were not added to the list of successes hence the behavior was to remove each file individually and then remove the root paths. The refactor now adds all files and paths added to the archive to the list of successes so in the event that a sub-directory was removed before a file in that sub-directory a `FileNotFoundError` would be raised. The simple fix is to just check for file existence before attempting to remove a file. 
__Note:__ This was not an …
=> archive - fix removal failures for nested files with tar archives

changelogs/fragments/2924-npm-fix-package-json.yml, plugins/modules/packaging/language/npm.py, tests/unit/plugins/modules/packaging/language/test_npm.py
Correctly handle cases where a dependency does not have a `version` property because it is either missing or invalid
Fixes https://github.com/ansible-collections/community.general/issues/2917
npm
=> npm - fix installing from package.json

changelogs/fragments/2951-mh-vars-deepcopy.yml, plugins/module_utils/mh/mixins/vars.py, tests/unit/plugins/module_utils/test_module_helper.py
The change-tracking feature in ModuleHelper was naively retaining a reference to dictionaries and lists. Changing that to a `deepcopy()` of it.
plugins/module_utils/mh/mixins/vars.py
=> MH - dicts and lists change-tracking is fixed

changelogs/fragments/2948-jenkins_job_info-remove_necessities_on_password_or_token.yml, plugins/modules/web_infrastructure/jenkins_job_info.py
Remove necessities of password or token in the jenkins_job_info module.
There are many use cases that Jenkins is allowed to visit without authentication. Also in the original implementation, the get_jenkins_connection function supports connections that exclude of password or token. So I think it should not have the restriction to make password or token necessary.
jenkins_job_info
=> jenkins_job_info: Remove necessities of password or token.

changelogs/fragments/2949-add_authentication-flow-binding_keycloak-client.yml, plugins/modules/identity/keycloak/keycloak_client.py, tests/unit/plugins/modules/identity/keycloak/test_keycloak_client.py
Add `authentication_flow_binding_overrides` option to the keycloak_client module.
`keycloak_client.py`
It is now possible to use the `authentication_flow_binding_overrides` option, like on the following example: 
```
- name: Create or update a Keycloak client (with authentication_flow_binding_override)
community.general.keycloak_client:
token: "{{ access_token }}"
state: present
realm: master
client_id: test
authentication_flow_binding_override:
browser: 4c90336b-bf1d-4b87-916d-3677ba4e5fbb
```
New feature tested on Keycloak 8.0.1.
=> Add option to the keycloak_client module

tests/integration/targets/lookup_passwordstore/aliases
=> Temporarily disable passwordstore lookup tests on macOS and OSX

changelogs/fragments/2902-filesystem_extend_freebsd_support.yml, plugins/modules/system/filesystem.py, tests/integration/targets/filesystem/aliases, tests/integration/targets/filesystem/defaults/main.yml, tests/integration/targets/filesystem/tasks/create_device.yml, tests/integration/targets/filesystem/tasks/create_fs.yml, tests/integration/targets/filesystem/tasks/freebsd_setup.yml, tests/integration/targets/filesystem/tasks/main.yml, tests/integration/targets/filesystem/tasks/overwrite_another_fs.yml, tests/integration/targets/filesystem/tasks/remove_fs.yml
This PR adds support for `UFS`, the FreeBSD's native/default filesystem type. It also adds support for FreeBSD special devices (character devices), and fixes a potential issue (data loss) by querying filesystem type with FreeBSD's `fstyp` if `blkid` doesn't find one.
filesystem
=> filesystem: extend support for FreeBSD

changelogs/fragments/2967-proxmox_inventory-offline-node-fix.yml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
Adding logic to skip collecting facts and guests for `offline` nodes.
Fixes #2931
- Removed some unused imports and variables in unit tests as well,
=> proxmox inventory - fix parsing for offline nodes

tests/integration/targets/module_helper/tasks/main.yml, tests/integration/targets/module_helper/tasks/mdepfail.yml, tests/integration/targets/module_helper/tasks/msimple.yml, tests/integration/targets/module_helper/tasks/mstate.yml
While working on another issue, noticed those files had no copyright headers.
tests/integration/targets/module_helper/tasks/main.yml
tests/integration/targets/module_helper/tasks/mdepfail.yml
tests/integration/targets/module_helper/tasks/msimple.yml
tests/integration/targets/module_helper/tasks/mstate.yml
=> MH integration tests - added missing copyright notes

.github/ISSUE_TEMPLATE/feature_request.yml
While preparing https://github.com/ansible-collections/amazon.aws/pull/400 I noticed that the community.general feature request still talks about ansible-core rather than community.general.  This looks like a C&P error
.github/
=> feature request template - replace ansible-core with community.general

changelogs/fragments/2963-improve-diff-mode-on-keycloak_authentication.yml, plugins/modules/identity/keycloak/keycloak_authentication.py, tests/unit/plugins/modules/identity/keycloak/test_keycloak_authentication.py
The diff mode is now showing `before` and `after` state also when updating the authentication flow. Before the diff state was only displayed on the creation of a new authentication flow.
`keycloak_authentication.py`
The function `create_or_update_executions(kc, config, realm='master')` is now returning `dict(before='', after'')` if modifications have been done or `None` if no changes.
=> Keycloak: Improve diff mode on keycloak_authentication module

changelogs/fragments/2901-nmcli_teaming.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
This PR allows to select the runner for a team configuration. It also adds the possibility of select the hwaddr-policy for the activebackup runner.
Fixes #1950
nmcli
```paste below
```
=> [nmcli] add runner and runner-hwaddr-policy for network teaming

changelogs/fragments/3006-redfish_command-bootoverride-argument-check.yaml, plugins/module_utils/redfish_utils.py
Bypass the boot device argument check when the command is: DisableBootOverride
as it isn't needed to perform this operation.
Fixes #3005
This corrects a bug introduced in #825 from me. When disabling the redfish bootoverride = continuous, the module currently requires a boot device to be set unnecessarily. This proposed PR add a check for the Disabled command selection to bypass the boot device check as it isn't used anyway.
=> Redfish Bootoverride Disable behaves incorrectly

changelogs/fragments/2987-archive-stage-idempotency-fix.yml, plugins/modules/files/archive.py, tests/integration/targets/archive/tasks/main.yml, tests/integration/targets/archive/tests/core.yml, tests/integration/targets/archive/tests/idempotency.yml
Staging fix for idempotency checking in the `archive` module
- The new idempotency logic compares archived filenames and checksums against the original file at `dest` if possible and falls back to comparing file size when necessary.
- Minor refactoring was performed as well.
- New idempotency tests are also added and disabled for this PR. 
- The decision to stage these changes instead of directly implementing is based on the assumption that the actual implementation would be a breaking change.
=> archive - staging idempotency fix

changelogs/fragments/3038-enhance_github_repo_api_url.yml, plugins/modules/source_control/github/github_repo.py, tests/unit/plugins/modules/source_control/github/test_github_repo.py
The module github_repo is enhanced to accept an optional api_url and allow operations agains on premise installation. 
api_url is optional an has a default to api.github.com to not break the former behavior of this module. 
github_repo
-
=> github_repo: support GitHub on premise installations

changelogs/fragments/3052_proxmox_inventory_plugin.yml, plugins/inventory/proxmox.py
Plugin was crashing on this line on Python 3.9.2 deployed on qemu image with debian bullseye. It doesn't crash anymore.
community.general.proxmox
I suspect you'll grasp it.
=> proxmox inventory plugin: Easy fix

changelogs/fragments/3036-archive-root-path-fix.yml, plugins/modules/files/archive.py, tests/unit/plugins/modules/files/test_archive.py
Fixes an existing bug in `archive` that sets the archive root to `'///'` when the longest common root amongst all paths in `path` is `'/'`
- Uses standard lib and inline functions where possible for clarity
- Also makes root calculation a "query" as it's a derived value from `paths`
- Replaced regex substitution with built-in methods to reduce repetition and marginally improve performance
- Added `units` instead of `integration` tests.
=> archive - fixing determination of archive root when root is '/'

changelogs/fragments/3036-archive-root-path-fix.yml, plugins/modules/files/archive.py, tests/unit/plugins/modules/files/test_archive.py
__This is a backport of PR #3036 as merged into main (31189e9).__
Fixes an existing bug in `archive` that sets the archive root to '///' when the longest common root amongst all paths in `path` is `'/'`
- Uses standard lib and inline functions where possible for clarity
- Also makes root calculation a "query" as it's a derived value from `paths`
- Replaced regex substitution with built-in methods to reduce repetition and marginally improve performance
- Added `units` instead of `integration` tests.
=> [PR #3036/31189e96 backport][stable-2] archive - fixing determination of archive root when root is '/'

changelogs/fragments/3049-xfconf-deprecate-get.yaml, plugins/modules/system/xfconf.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt
When #3045 gets merged, then this PR should follow, to deprecate the use of the `get` state in `xfconf`. The new module should be used instead.
=> xfconf - deprecate get state in favour of the xfconf_info module

plugins/modules/monitoring/stackdriver.py, tests/integration/targets/alternatives/tasks/main.yml, tests/integration/targets/alternatives/tasks/setup_test.yml, tests/integration/targets/alternatives/tasks/test.yml, tests/integration/targets/alternatives/tasks/tests_set_priority.yml, tests/integration/targets/filesystem/tasks/main.yml, tests/integration/targets/filesystem/tasks/setup.yml, tests/integration/targets/npm/tasks/no_bin_links.yml, tests/integration/targets/npm/tasks/test.yml, tests/integration/targets/setup_openldap/tasks/main.yml, tests/integration/targets/setup_postgresql_db/tasks/main.yml, tests/integration/targets/supervisorctl/tasks/install_Linux.yml, tests/integration/targets/supervisorctl/tasks/main.yml, tests/integration/targets/supervisorctl/tasks/start_supervisord.yml, tests/integration/targets/supervisorctl/tasks/stop_supervisord.yml, tests/integration/targets/supervisorctl/tasks/test.yml, tests/integration/targets/supervisorctl/tasks/test_start.yml, tests/integration/targets/supervisorctl/tasks/test_stop.yml, tests/integration/targets/supervisorctl/templates/supervisord.conf
While examining the integration tests for hte supervisorctl module I noticed that some of the Jinja expressions had these [NBSP] characters in it - identified by the IDE.
A quick find in the whole repository showed that a number of different files had this character - mostly in Jinja expressions inside integration tests.
plugins/modules/monitoring/stackdriver.py
tests/integration/targets/alternatives/tasks/main.yml
tests/integration/targets/alternatives/tasks/setup_test.yml
tests/integration/targets/alternatives/tasks/test.yml
tests/integration/targets/alternatives/tasks/tests_set_priority.yml
tests/integration/targets/filesystem/tasks/main.yml
tests/integration/targets/filesystem/tasks/setup.yml
tests/integration/targets/npm/tasks/no_bin_links.yml …
=> replace NBSP (non-blocking space) character with a regular SPACE char

changelogs/fragments/3034-promox-kvm-return-new-id.yaml, plugins/modules/cloud/misc/proxmox_kvm.py
return value vmid should be new vmid on successfully cloning a vm.
Fixes #1713
and my own issue which isn't described within Issues.
proxmox_kvm
```paste below
TASK [debug] *********************************************************************************************************************************************
ok: [gw1.staging....] => {
"msg": {
"failed": false,
"msg": "VM gw1.staging.... with newid 162 cloned from vm with vmid 200",
"vmid": 200
}
}
```
Now becomes:
```paste below
TASK [debug] *********************************************************************************************************************************************
ok: [gw1.staging....] => {
"msg": {
"failed": false,
"msg": "VM gw1.staging.... with newid 162 …
```
=> Succesful clone from proxmox_kvm should return new vm id, not id from cloned vm.

changelogs/fragments/3080-java_cert-2460-import_private_key.yml, plugins/modules/system/java_cert.py, tests/integration/targets/java_cert/defaults/main.yml, tests/integration/targets/java_cert/tasks/main.yml, tests/integration/targets/java_cert/tasks/state_change.yml
When importing a certificate from a PKCS#12 keystore, import the private key as well (if it is bundled in the source keystore). Fix a regression from #2008. Also clarify documentation about PKCS#12 as source of import.
Fixes #2460 
java_cert
none
=> java_cert: import certificate+key bundle from pkcs12

changelogs/fragments/3098-django_manage-cmd-list.yaml, plugins/modules/web_infrastructure/django_manage.py
The django_manage module was calling `run_command()` using a `str` command. We should use a list instead, to avoid
=> django_manage - using list instead of string in run_command()

tests/integration/targets/apache2_module/meta/main.yml, tests/integration/targets/archive/meta/main.yml, tests/integration/targets/deploy_helper/meta/main.yml, tests/integration/targets/flatpak/meta/main.yml, tests/integration/targets/flatpak_remote/meta/main.yml, tests/integration/targets/gem/meta/main.yml, tests/integration/targets/hg/meta/main.yml, tests/integration/targets/iso_create/meta/main.yml, tests/integration/targets/iso_extract/meta/main.yml, tests/integration/targets/launchd/meta/main.yml, tests/integration/targets/locale_gen/meta/main.yml, tests/integration/targets/zypper/meta/main.yml, tests/integration/targets/zypper_repository/meta/main.yml
References to no longer used things.
tests/integration/targets/apache2_module/meta/main.yml
tests/integration/targets/archive/meta/main.yml
tests/integration/targets/deploy_helper/meta/main.yml
tests/integration/targets/flatpak/meta/main.yml
tests/integration/targets/flatpak_remote/meta/main.yml
tests/integration/targets/gem/meta/main.yml
tests/integration/targets/hg/meta/main.yml
tests/integration/targets/iso_create/meta/main.yml
tests/integration/targets/iso_extract/meta/main.yml
tests/integration/targets/launchd/meta/main.yml
tests/integration/targets/locale_gen/meta/main.yml
tests/integration/targets/zypper/meta/main.yml
tests/integration/targets/zypper_repository/meta/main.yml
=> removed extraneous dependency in integration test

.github/BOTMETA.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/identity/keycloak/keycloak_client_rolemapping.py, plugins/modules/keycloak_client_rolemapping.py, tests/unit/plugins/modules/identity/keycloak/test_keycloak_client_rolemapping.py
This PR add a module to manage keycloak client_rolemapping, like keycloak_client manage clients
`keycloak_client_rolemapping.py`
=> Keycloak: add client_rolemapping management

plugins/modules/files/filesize.py
Overwrite default `unsafe_writes` documentation to say that it does nothing here since the module modifies files in-place.
Fixes #2589 
filesize
=> filesize: overwrite default `unsafe_writes` documentation

changelogs/fragments/3081-add-wifi-option-to-nmcli-module.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Maintaining an `ap` mode or mode other than `infrastructure` wifi connection is not supported with the `nmcli` module. This is because the only arguments currently available for configuring `wifi` type connections are `wifi_sec` and `ssid`. Adding an additional argument, `wifi`, allows all available `802-11-wireless` (A.K.A. `wifi`) options to be managed.
I.E.:
```shell
$ nmcli connection show WLAN | grep '^802-11-wireless\.' | awk '{print $1}' | cut -d: -f1
802-11-wireless.ssid
802-11-wireless.mode
802-11-wireless.band
802-11-wireless.channel
802-11-wireless.bssid
802-11-wireless.rate
802-11-wireless.tx-power
802-11-wireless.mac-address
802-11-wireless.cloned-mac-address
802-11-wireless.generate-mac-address-mask
802-11-wireless.mac-address-blacklist …
```
=> nmcli: Add support for additional Wi-Fi network options

changelogs/fragments/3135-add-redfish_command-bootoverridemode.yaml, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/redfish/redfish_command.py
Expose BootOverrideMode parameter to redfish_command to allow setting by user during run.
Fixes #3134
redfish_utils
It's now possible to do the following:
```
tasks:
- name: Set Pxe Boot 
community.general.redfish_command:
command: SetOneTimeBoot 
boot_override_mode: Legacy
bootdevice: Pxe
```
This allows choosing the boot mode used for the override target, if different from the current running state of the machine.
=> redfish_command: allow setting the BootSourceOverrideMode property

changelogs/fragments/3132-nmcli-dummy.yaml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Add ability to manage dummy interfaces using the `nmcli` module
Fixes https://github.com/ansible-collections/community.general/issues/724
nmcli
- add ability to manage dummy interfaces
=> nmcli: manage dummy connections

changelogs/fragments/3139-tss-lookup-plugin-update-to-make-compatible-with-sdk-v1.yml, plugins/lookup/tss.py
This PR updates the plugin to bring it in line with the current `python-tss-sdk` version, which added breaking changes in v1.0.0. The plugin is now compatible with the latest SDK version.  
This also fixes #3057. 
`tss` lookup plugin
No changes are needed to current playbooks, as inputs have stayed the same. Users will be encouraged to update their `python-tss-sdk` version to >1.0.0.
=> Updated the tss lookup plugin to reflect breaking changes introduced in the underpinning SDK

changelogs/fragments/3125-hana-query-userstore.yaml, plugins/modules/database/saphana/hana_query.py, tests/unit/plugins/modules/database/saphana/test_hana_query.py
This PR add the ability to use the userstore instead of username and password
hana_query
```
The hdbuserstore is a secretstore where the connection string and the credentials for a specific user is stored.
```
=> Hana query userstore

changelogs/fragments/3136-add-wifi-sec-change-detection-to-nmcli-module.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Fixed issue in which modifying the value of `wifi_sec` would not produce any change.
Also: Removed extraneous `appends` to `cmd` in `connection_update`. These really should have only been added to `connection_options` whose return values get `extended` onto `cmd`.
`net_tools/nmcli.py`
I.E. Changing from this:
```YAML
type: wifi
ifname: wlp4s0
ssid: Brittany
wifi_sec:
key-mgmt: wpa-psk
psk: crash-landing
```
To this:
```YAML
type: wifi
ifname: wlp4s0
ssid: Brittany
wifi_sec:
key-mgmt: sae
psk: pefect-landing
```
You would expect something like this, but instead get nothing.
```diff
--- before
+++ after
{
...
-    "802-11-wireless-security.key-mgmt": "wpa-psk",
-    "802-11-wireless-security.psk": "crash-landing",
+ …
```
=> nmcli: Fix change detection for Wi-Fi security options

CONTRIBUTING.md
reformulate the preference of not having squashed commits clearer,
shorter and more precise.
When I read these two list items in the contributing guide, I interpreted them differently than what was said in https://github.com/ansible-collections/community.general/pull/3164#discussion_r684644504
I tried to reformulate them to make it clearer what is the preferred way. The original sentence did not clearly say that squashing is discouraged, but the reason was given in the line below that one.
=> contributing: make expected behavior clearer

changelogs/fragments/3160-pass-wifi-secrets-via-stdin-to-nmcli-module.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Since #2220, adding WiFi secrets via the `wifi_sec` option would cause those secrets to be appended to the `cmd` [here](https://github.com/ansible-collections/community.general/blob/6a8eb7b388c53acce4d8d701bda86fc9382df7b9/plugins/modules/net_tools/nmcli.py#L960). The best practice for `secrets` input is to reduce their exposure and pass them in via `stdin`.
Fixes #3145
`net_tools/nmcli.py`
In order to resolve this, I used the [data argument](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L1860) of `run_command` to call `nmcli con edit` with the proper `set` commands containing any potential "`secrets`" passed in via `stdin` after completing a `nmcli con add` or `nmcli con modify`.
There are no changes visible to the user.
=> nmcli: writing secrets to command line is a security hole

changelogs/fragments/3074-ini_file-3031-empty-value-inconsistency.yml, plugins/modules/files/ini_file.py, tests/integration/targets/ini_file/tasks/main.yml
**This is a backport of PR #3074 as merged into main (2831bc4).**
Fix inconsistencies between _empty value_ and _no value at all_: both are falsey but should behave differently.
Fixes #3031
ini_file
https://github.com/ansible-collections/community.general/issues/3031#issuecomment-886198695
=> [PR #3074/2831bc45 backport][stable-2] ini_file: fix empty-value vs. no-value inconsistency

.gitignore
When using PyCharm the IDE by default uses 'venv' as venv directory. Hereby ignore it.
.gitignore
```paste below
```
=> Update .gitignore to latest version which includes ignoring Python development environments

changelogs/fragments/3161-openbsd-pkg-fix-regexp-matching-crash.yml, plugins/modules/packaging/os/openbsd_pkg.py
Fix regexp crash caused by missing escaping of package name.
openbsd_pkg
When a package name contains special characters (e.g. "g++"), they are
interpreted as part of the regexp.
This can lead to a crash with an error in the python re module, for
instance with "g++":
sre_constants.error: multiple repeat
Fix this by escaping the package name.
=> openbsd_pkg: Fix regexp matching crash

changelogs/fragments/2808-pids-older-psutil.yml, plugins/modules/system/pids.py
The pids module does not work out of the box on RHEL6 and RHEL7, with the system python-psutil module.
Fixes ansible/ansible#61922
pids
The psutil python module is a true mess, they changed the API twice. The function arguments, as well as the objects that are returned. The documentation does not make it clear which version supports what so the safest implementation is this waterfall approach.
A better approach would be to inspect the returned information, rather than trust a version, but that would not be any more efficient. In the end it is better to have something that at least works out-of-the-box on all platforms than something that requires custom updates to system packages before it works as expected. Especially for something as basic as `pids`.
=> Support older version of psutil (RHEL7 and RHEL6)

changelogs/fragments/3075-archive-idempotency-enhancements.yml, plugins/modules/files/archive.py, tests/integration/targets/archive/tests/idempotency.yml
Fixes `archive` to retrieve the existing archived files and checksums if possible and compare against the resulting archive to better identify for changes in content or metadata.
Fixes #1043
- Treats the existing archive contents as empty if the existing file is not valid.
- Defaults to a size comparison if the existing file is not readable.
- For single file compression with `gz, bz2, xz` changes to the original file name cannot be detected so idempotency is only based on content in this case.
=> archive - idempotency enhancement for 4.0.0

plugins/inventory/linode.py
Adds an additional line to the Linode dynamic inventory plugin to help users understand how they might actually reach one of the nodes it discovers.
Does not make any changes to code, simply enhances the docs with a one-liner.
- Linode inventory plugin
By default, the Linode ansible plugin sets the `ansible_ssh_host` to the `label` of the Linode instance. This not useful; the label is not a DNS record (like AWS, for example) and it is completely unreachable.
The [Linode docs](https://www.linode.com/docs/guides/deploy-linodes-using-ansible/) state that you must add entries to `/etc/hosts` that match these labels. It also references a closed PR (https://github.com/ansible/ansible/pull/51196) to suggest that this `/etc/hosts` requirement will be resolved. Needing to …
=> Add ipv4 example to linode inventory docs

plugins/inventory/linode.py, tests/unit/plugins/inventory/test_linode.py
- Fix a typo in the Linode inventory plugin unit tests
- Fix some style issues in descriptions where punctuation was missing
Signed-off-by: Kellin <kellin@retromud.org>
While working on https://github.com/ansible-collections/community.general/pull/3203, the near example I saw for writing descriptions was missing a period. During review, it came up that this is actually incorrect style.
This merge request fixes that style issue and a typo in the unit test file.
Linode Dynamic Inventory Plugin
=> Linode inventory plugin typo fixes

changelogs/fragments/3206-mh-classmethod.yaml, plugins/module_utils/mh/base.py, plugins/module_utils/mh/module_helper.py, plugins/modules/packaging/language/cpanm.py, plugins/modules/system/xfconf.py
I had second thoughts about that discussion in https://github.com/ansible-collections/community.general/pull/2933#pullrequestreview-711513025 and I thought it would be OK to have a classmethod to trigger the module. (Cc: @webknjaz )
plugins/module_utils/mh/module_helper.py
plugins/modules/packaging/language/cpanm.py
=> module_helper - implemented classmethod to start the module

changelogs/fragments/3228-tss-domain-authorization.yml, plugins/lookup/tss.py
Use DomainPasswordGrantAuthorizer if parameter `domain` is used.
It's not possible to use this plugin when Thycotic uses domain authorization.
New parameter `domain` is introduced to enable this and different authorization class is used for this.
Otherwise everything stays the same.
Original behavior for domain authorizing Thycotic:
```
- debug:
msg: "{{
lookup(
'community.general.tss',
secret_id,
base_url=server,
username=username,
password=password
)
}}"
---
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'community.general.tss'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Secret Server lookup failure: Login Failed"}
```
New behavior:
```
- debug:
msg: "{{ …
```
=> tss: add option for domain authorization

changelogs/fragments/3141-disallow-options-unsupported-by-nmcli.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Since both the `wifi` & `wifi_sec` options do not have a static list of suboptions (it depends on `nmcli's` version), we should query `nmcli` to determine which options are available on the client. Currently, when applying changes containing invalid/unsupported options, only the first option will be shown, show all of them instead. Also added new option to allow the play to display a warning and continue when invalid/unsupported options are present, the default is to fail.
`net_tools/nmcli.py`
When specifying invalid/unsupported Wi-Fi options in the `wifi` and/or `wifi_sec` dict.
* **`ssid` was specified via `wifi.ssid`:**
```YAML
type: wifi
ssid: SSID_SHOULD_BE_SPECIFIED_HERE
wifi:
ssid: SSID_SHOULD_NOT_BE_SPECIFIED_HERE
```
* Before:
* No error message is given, …
=> nmcli: Disallow Wi-Fi options not supported by nmcli

changelogs/fragments/3239-nmcli-sit-ip-config-bugfix.yaml, changelogs/fragments/3239-nmcli-sit-ipip-config-bugfix.yaml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Add connection type "sit" to the allowed connection types which allows configuring IPv4/IPv6 settings.
Fixes #3238 
nmcli
```paste below
nmcli:
type: sit
conn_name: sit_tb
autoconnect: yes
ip_tunnel_remote: 94.44.44.44
ip6: 2:1:1:171::2/64
gw6: 2:1:1:171::1
method4: disabled
state: present
```
```
[connection]
id=sit_tb
uuid=dcae0d3a-9703-48c2-89c6-2a0f7881fe00
type=ip-tunnel
interface-name=sit_tb
permissions=
[ip-tunnel]
mode=3
remote=94.44.44.44
[ipv4]
dns-search=
method=auto
[ipv6]
addr-gen-mode=stable-privacy
dns-search=
method=auto
[proxy]
```
```
[connection]
id=sit_tb
uuid=7a21ffc6-0d31-40c1-bcef-825ce506a136
type=ip-tunnel
interface-name=sit_tb
permissions=
timestamp=1629390525
[ip-tunnel]
mode=3
remote=94.44.44.44
[ipv4]
dns-search=
method=disabled
[ipv6] …
```
=> nmcli: allow IPv4/IPv6 configuration on ipip and sit devices

changelogs/fragments/3258-apache2_module.yml, plugins/modules/web_infrastructure/apache2_module.py
Fixes #3253 and a bug introduced in #3106.
apache2_module
=> apache2_module: fix a2enmod/a2dismod detection and error message if not found

changelogs/fragments/3290-mh-cmd-boolean-not.yaml, plugins/module_utils/mh/mixins/cmd.py, tests/unit/plugins/module_utils/test_module_helper.py
Added the negation of the usual `ArgFormat.BOOLEAN` logic: if the boolean parameter is not there or it's `False`, add the command argument in the CLI.
=> mh CmdMixin - added ArgFormat.BOOLEAN_NOT and logic

changelogs/fragments/3267-dnsimple1-deprecation.yml, plugins/modules/net_tools/dnsimple.py
This is a followup PR to https://github.com/ansible-collections/community.general/pull/2946 to add a deprecation warning for `python-dnsimple < 2` in `community.general >= 4.0.0` 
dnsimple
- add deprecation warning if `python-dnsimple < 2` is used
=> add deprecation warning for python-dnsimple 1

changelogs/fragments/3256-fix-ptr-handling-in-udm_dns_record.yml, plugins/modules/cloud/univention/udm_dns_record.py
Before, it was not possible to manage PTR records in Univention DNS,
due to broken zone lookups and improper used parameters of the object.
This patch fixes the PTR handling, allowing both v4 and v6 entries.
Fixes #3244
udm_dns_record
=> udm_dns_record: Fix handling of PTR records (#3244)

.github/BOTMETA.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/identity/keycloak/keycloak_identity_provider.py, plugins/modules/keycloak_identity_provider.py, tests/integration/targets/keycloak_identity_provider/aliases, tests/integration/targets/keycloak_identity_provider/tasks/main.yml, tests/integration/targets/keycloak_identity_provider/vars/main.yml, tests/unit/plugins/modules/identity/keycloak/test_keycloak_identity_provider.py
Add a new module to manage Keycloak Identity Providers.
keycloak_identity_provider
=> Keycloak: add identity providers management

plugins/modules/cloud/misc/proxmox.py
Updating `disk` option documentation to provide a complete description of the values which can be passed to describe the root mount point.
Reported as a [comment](https://github.com/ansible-collections/community.general/issues/3243#issuecomment-902656973) in #3243
N/A
=> proxmox - Update documentation for the disk option

changelogs/fragments/502-zfs_bugfix_and_diff_mode_support.yaml, plugins/modules/storage/zfs/zfs.py
If you use "zfs set" to explicitly set ZFS properties, they are marked as from source "local". If ZFS properties are implicitly set by using "zfs send" and "zfs receive", for example as part of a template based installation, they are marked as from source "received". But as there is no technical difference between both types of them, the “received” ZFS properties should also be considered “local”. Otherwise Ansible would detect changes, which aren’t actual changes. Therefore I changed line 202/207 to reflect this.
For us it’s quite important, that Ansible modules support the diff mode in order to qualify changes. Therefore I added some code lines to address this.
```paste below
```
=> zfs.py: treated received properties as local and added diff mode support

changelogs/fragments/3285-pamd-updated-with-empty-args.yaml, plugins/modules/system/pamd.py, tests/integration/targets/pamd/tasks/main.yml, tests/unit/plugins/modules/system/test_pamd.py
The code for `state=updated` made no distinction between `None` and an empty list. Changing that ensured that updating to an empty list of arguments works.
An integration testcase was added to cover for this case.
Fixes #3260 
plugins/modules/system/pamd.py
tests/integration/targets/pamd/tasks/main.yml
=> pamd - fixed issue+minor refactorings

.github/BOTMETA.yml
I have neither maintained nor contributed to this module for years, nor has my alter-ego tastychutney.
Note: tastychutney is another github account of mine that was also added as a maintainer.
=> django_manage: Remove scottanderson42 and tastychutney as maintainers.

changelogs/fragments/3296-clean-etag.yaml, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/redfish/redfish_command.py, plugins/modules/remote_management/redfish/redfish_config.py
Some vendors surround header etag with quotes, which need to be cleaned before sending a patch
Module_utils: redfish_utils
Example response data that causes the issue.
Response data with clean etag:
{…"@odata.etag":"143417f8d77c4e179cfdf8edb1cbb921"}
Response header with double quoted etag:
{'Etag': '"143417f8d77c4e179cfdf8edb1cbb921"', …}
This MR simply cleans the etag of surrounding quotes prior to patching.
=> redfish: clean etag of quotes before patch

changelogs/fragments/3313-nmcli-add_gsm_support.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Add gsm connection support.
I prepared the unit test (oriented myself at the latest GRE tunnel update), but unfortunately could not run it in lack of a propper up-to-date test-environment.
This is my first pull-request ever, so please be patient. 😉 
nmcli
```yaml
---
- name: Test
hosts: roadwarriors
tasks:
- name: Test GSM IPv4
become: true
type: gsm
conn_name: gsm_test
ifname: gsm_test
gsm:
apn: internet.telekom
username: t-mobile
password: tm
pin: 1234
method4: auto
state: present
- name: Test GSM IPv6
become: true
type: gsm
conn_name: gsm_test
ifname: gsm_test
gsm:
apn: internet.v6.telekom
username: t-mobile
password: tm
pin: 1234
method6: auto
state: present
- name: Test GSM auto-config
become: true …
```
=> nmcli: Support GSM connections

changelogs/fragments/3334-django_manage-split-params.yaml, plugins/modules/web_infrastructure/django_manage.py
Splits module parameters `fixtures` and `apps` when passing to the command line.
Fixes #3333 
=> django_manage - split params

changelogs/fragments/3248-adds-few-more-gitlab-group-options.yml, plugins/modules/source_control/gitlab/gitlab_group.py, tests/integration/targets/gitlab_group/tasks/main.yml, tests/unit/plugins/modules/source_control/gitlab/gitlab.py, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_group.py
SUMMARY
Enhanced existing community.general.gitlab_group to handle additional gitlab properties:
project_creation_level
auto_devops_enabled
subgroup_creation_level
ISSUE TYPE
COMPONENT NAME
gitlab_group
Just adding few more options to configure a GitLab group properly. Has been tested on a local instance.
Follow-up on closed PR #3043
=> Adds few more gitlab group options

changelogs/fragments/3178-add-ipaselinuxusermaporder-to-ipa-config-module.yml, plugins/modules/identity/ipa/ipa_config.py
This adds a new `ipaselinuxusermaporder` option to the ipa_config module to set the SELinux user map order.
ipa_config
See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/linux_domain_identity_authentication_and_policy_guide/config-selinux
=> Add ipaselinuxusermaporder option to the ipa_config module

changelogs/fragments/634-gitlab_project_runners.yaml, plugins/modules/source_control/gitlab/gitlab_runner.py
support project-scoped gitlab.com runners registration
Reroll of https://github.com/ansible/ansible/pull/58840 (Jul 8, 2019)
Reroll of https://github.com/ansible-collections/community.general/pull/634 (Jul 9, 2020)
gitlab_runner
The current module register runners on global scope (in particular, trying to fetch instance-wide listing of runners) what GitLab.com obviously forbids.
But runners can be registered by-project (and by-group although GitLab API does not support it yet).
By opting for project-scope, then listing and idempotent registration are allowed.
Using a (existing) project is also a convenient way to register a group runner (by providing a group registration token). This avoid the failure of requesting instance-wide runners at GitLab.com
This PR also …
=> gitlab_runner: Support project-scoped runners registration

changelogs/fragments/3315-pids-refactor.yml, plugins/modules/system/pids.py, tests/integration/targets/pids/tasks/main.yml
Cleaning up the `pids` module to ensure version specific operations are consistent across the module.
plugins/modules/system/pids.py
- Decouples `psutil` via an adapter with overridable behavior based on the package version
- Added the version based logic for the `pattern` execution path
- Tested locally with `psutils` versions `<2.0.0`, `>=2.0.0,<5.3.0`, and `>=5.3.0`
=> pids - refactor module to make version-based behavior consistent

.github/BOTMETA.yml
Added an additional maintainer to both the `tss` and `dsv` lookup plugins to help monitor PR/Issues and comment/reply sooner. 
tss lookup plugin
dsv lookup plugin
``
=> Added additional maintainer for the dsv and tss lookup plugins

changelogs/fragments/3327-tss-token-authorization.yml, plugins/lookup/tss.py
Use `AccessTokenAuthorizer` if parameter `token` is used.
Thycotic and hvac library also support authorizing with access token. It is useful when you already have such a token so you can seamlessly use it.
Parameters username and password are optional now because of this.
Playbook example:
```
tasks:
- name: Get the password
debug:
msg: "{{ ((lookup(
'community.general.tss',
tss_secret_id,
base_url=tss_server,
token=tss_token,
) | from_json).get('items') | items2dict(key_name='slug', value_name='itemValue'))['password']
}}"
run_once: True
```
Output:
```
PLAY [localhost] *****************************************************************************************************
TASK [Get the password] …
```
=> tss: add option for token authorization

.github/BOTMETA.yml, plugins/callback/opentelemetry.py, tests/unit/plugins/callback/test_opentelemetry.py, tests/unit/requirements.txt
Send distributed traces for the ansible runs with OpenTelemetry
You can configure this plugin and then run your playbook with the below environment variables. Those environment variables are the ones defined by the opentelemetry project (see https://opentelemetry-python.readthedocs.io/en/latest/exporter/otlp/otlp.html)
In order to configure this plugins is requried to install the below python libs:
```bash
pip3 install opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp
```
Then you can start sending traces to your OTEL endpoint:
```bash
$ OTEL_SERVICE_NAME='ansible-otel' \
OTEL_EXPORTER_OTLP_ENDPOINT='<your_otlp_endpoint>' \
OTEL_EXPORTER_OTLP_HEADERS='authorization=Bearer <your_token>' \
ansible-playbook …
```
=> Add opentelemetry callback plugin

tests/integration/targets/prepare_nios_tests/tasks/main.yml
@mattclay mentioned on IRC that ansible-test will stop installing them automatically (currently the dependencies are coming from https://github.com/ansible/ansible/blob/c3fc8fb99a409d7555c1587697a3cfd78b7f3eb9/test/lib/ansible_test/_data/requirements/integration.cloud.nios.txt).
CC @anagha-infoblox
nios integration tests
=> Install nios test requirements

plugins/callback/opentelemetry.py
1) Add context propagation then it can be integrated with some other tools. 
2) Handle task failures as errors.
Reported errors:
Context propagation:
In order to test this particular plugin you could use https://github.com/jenkinsci/opentelemetry-plugin/pull/166.
**NOTE**: There is an open discussion https://github.com/open-telemetry/opentelemetry-specification/issues/740 for the traceparent standardisation.
=> opentelemetry callback: context propagation and error exception

changelogs/fragments/3343-redfish_utils-addUser-userId.yml, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/redfish/redfish_command.py
Some implementations of Redfish (e.g. the one in Cisco's CIMC) require the id of the new user for account creation.
I'm not that firm with Python but the proposed change should fix this.
redfish_utils
Some implementations of Redfish require the new users account id for the creation of a new user. If not given HTTP Error 400 will be displayed. The proposed change aims at adding "Id" as additional value for the payload if given by the user.
=> redfish_utils: adding "Id" to the add user function
