ansible-collections/community.general

changelogs/fragments/3319-gitlab_project_members_enhancement.yml, plugins/modules/source_control/gitlab/gitlab_project_members.py, tests/integration/targets/gitlab_project_members/defaults/main.yml, tests/integration/targets/gitlab_project_members/tasks/main.yml
gitlab_group_members has been enhanced to accept list of users/access levels and purge users not in list. This change does the same changes to gitlab_project_members
@felixfontein @zanssa
=> Get behavior of gitlab_project_members to the one of gitlab_group_members

changelogs/fragments/3328-interfaces_file-improvements.yaml, plugins/modules/system/interfaces_file.py, tests/integration/targets/interfaces_file/aliases, tests/integration/targets/interfaces_file/files/interfaces_ff, tests/integration/targets/interfaces_file/tasks/main.yml, tests/unit/plugins/modules/system/interfaces_file/test_interfaces_file.py
General improvements, simplifications and pythonification of the code.
plugins/modules/system/interfaces_file.py
tests/unit/plugins/modules/system/interfaces_file/test_interfaces_file.py
=> Interfaces_file - improvements

changelogs/fragments/3367-add-require_two_factor_authentication-property-to-gitlab-group.yml, plugins/modules/source_control/gitlab/gitlab_group.py, tests/integration/targets/gitlab_group/tasks/main.yml, tests/unit/plugins/modules/source_control/gitlab/gitlab.py, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_group.py
Enhance existing community.general.gitlab_group to add require_two_factor_authentication property
gitlab_group
Has been tested on a our gitlab instance.
=> Add require_two_factor_authentication property to gitlab group

changelogs/fragments/3336-openbsd_pkg-fix-KeyError.yml, plugins/modules/packaging/os/openbsd_pkg.py
If package installation has an error after the package is install (e.g.
when running tags), then there will be output on stderr and the fallback
regex will match; however, since pkg_add exited non-zero, changed is
never added as a key to the dictionary. As a result the code at the end
of main that checks if anything has changed raises a KeyError.
openbsd_pkg
```
The full traceback is:
File "/home/mark/.ansible/tmp/ansible-tmp-1630863821.4813468-24031-269464171722171/AnsiballZ_openbsd_pkg.py", line 247, in <module>
File "/home/mark/.ansible/tmp/ansible-tmp-1630863821.4813468-24031-269464171722171/AnsiballZ_openbsd_pkg.py", line 237, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File …
```
=> openbsd_pkg: Fix KeyError

changelogs/fragments/3331-do_not_ignore_volatile_configs_by_option.yml, plugins/modules/cloud/lxd/lxd_container.py
As noted by oskar456, the module ignores "volatile" options. This fix allows this behavior to be switched off. 
The new behavior should be changed to the default in the next releases. 
Therefore a corresponding deprecate warning was inserted. 
Fixes #2466
lxd_container
See #2466
=> lxd_container: do not ignore volatile configs by option

changelogs/fragments/3425-mail_add_configurable_ehlo_hostname.yml, plugins/modules/notification/mail.py, tests/integration/targets/mail/tasks/main.yml
The mail module is missing the capability to configure the hostname used for EHLO.
Being able to configure that allows for greater flexibility
mail
Currently the hostname used for EHLO is automatically deduced by smtplib.
If you have a restrictive mailsetup the mailserver may try to validate the EHLO.
Adding capability to specify the hostname used for EHLO allows for usage from behind routers/nat-gateways.
=> mail: adding capability to specify ehlo hostname

tests/unit/requirements.txt
grpcio takes 7 minutes to build on Python 3.10. Make sure it's not installed indirectly.
unit tests
=> Unit tests: grpcio takes 7 minutes to build on Python 3.10 - make sure it's not installed indirectly

tests/integration/targets/zypper/tasks/zypper.yml
See https://dev.azure.com/ansible/b24bf3ca-6168-45d7-99e2-bf8029e67c87/_apis/build/builds/25605/logs/1797 or https://dev.azure.com/ansible/b24bf3ca-6168-45d7-99e2-bf8029e67c87/_apis/build/builds/25605/logs/1806:
```
2021-09-25T14:43:55.8137737Z 17:44 TASK [zypper : ensure no previous netcat package still exists] *****************
2021-09-25T14:43:56.1423429Z 17:45 [0;32mok: [testhost] => {"changed": false, "name": ["netcat-openbsd", "gnu-netcat"], "rc": 0, "state": "absent", "update_cache": false}[0m
2021-09-25T14:43:56.1465291Z 17:45 
2021-09-25T14:43:56.1466435Z 17:45 TASK [zypper : install netcat-openbsd which conflicts with gnu-netcat] *********
2021-09-25T14:43:58.5788750Z 17:47 [0;33mchanged: [testhost] => {"changed": true, "cmd": ["/usr/bin/zypper", "--quiet", …
```
=> zypper: disable netcat conflict in tests as one package seems to be no longer available

tests/integration/targets/filesystem/tasks/create_fs.yml
See https://dev.azure.com/ansible/b24bf3ca-6168-45d7-99e2-bf8029e67c87/_apis/build/builds/25621/logs/1542
Fails because of:
```
2021-09-25T14:30:56.2332359Z 04:30 [0;31m    "msg": "Failed to find required executable \"findmnt\" in paths: /sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin"[0m
```
filesystem integration tests
=> [WIP] [stable-2] Fix filesystem tests on OpenSuSE

.azure-pipelines/azure-pipelines.yml, README.md
Replace devel with stable-2.12 in CI for the stable-2 branch. Only stable-3 and devel will keep testing devel for now.
(This is similar to what we did for stable-1 after stable-2.11 was formed, there devel was replaced by stable-2.11.)
CI
=> [stable-2] Replace devel with stable-2.12 in CI

changelogs/fragments/3330-bugfix-keycloak-authentication-flow-requirements-not-set-correctly.yml.yml, plugins/modules/identity/keycloak/keycloak_authentication.py
When a new execution is created by the keycloak_authentication module, the requirement is always on DISABLED even if ENABLED is given as argument. 
With this fix, the requirement will correspond to the requirement given in argument to the module. 
For example : 
```
- name: Create an authentication flow with 2 identical execution.
community.general.keycloak_authentication:
auth_keycloak_url: http://localhost:8080/auth
auth_username: admin
auth_password: password
realm: master
alias: "two_identical_exec"
copyFrom: "first broker login"
authenticationExecutions:
- providerId: "test-execution1"
requirement: "REQUIRED"
- displayName: "test-execution1"
requirement: "REQUIRED"
```
If the authentication flow doesn't exist already, …
=> Keycloak: Fix bug on keycloak_authentication, requirement not always updated

changelogs/fragments/3400-fix-gitLab-api-searches-always-return-first-found-match-3386.yml, plugins/modules/source_control/gitlab/gitlab_group_members.py
Fixes #3386
`get_group_id` return the group ID by matching `full_path`, `path` or `name`.
Tested with the base of our issue #3386 and our gitlab instance.
=> Fix: GitLab API searches always return first found match

changelogs/fragments/3451-gitlab-group-member-deprecate-name-and-path.yml, plugins/modules/source_control/gitlab/gitlab_group_members.py
Follow up PR on #3400 to deprecate direct usage of `name` and `path` as discussed in https://github.com/ansible-collections/community.general/pull/3400#issuecomment-927293690
Fixes #3386
https://github.com/ansible-collections/community.general/pull/3400#issuecomment-927293690
=> chore: add deprecation warning for gitlab group membership

changelogs/fragments/3429-enable_deprecaded_message_for_ignore_volatile_option.yml, plugins/modules/cloud/lxd/lxd_container.py
Enable deprecated message if ignore_volatile_options is set to true.
This patch should not be ported back to previous versions .
lxd_container
=> Enable deprecaded message for ignore_volatile_options

.github/BOTMETA.yml, plugins/inventory/opennebula.py, tests/unit/plugins/inventory/test_opennebula.py
Added new inventory plugin for use with OpenNebula based clouds
opennebula inventory plugin
REFS https://github.com/ansible/ansible/pull/66394
=> Added OpenNebula inventory plugin

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation_report.yml
Split up 'Ansible version' in issue templates into ansible-core version + community.general version. The ansible-core version which most users provide as "Ansible version" (which is also printed by the instructions provided there) isn't really helpful in most cases.
CC @gundalow @Andersson007 
issue templates
=> Split up 'Ansible version' in issue templates into ansible-core version + community.general version

.github/BOTMETA.yml
The more recent version of Ansibullbot defaults notifications to false.
We need to set it to true so it can notify contributors and maintainers.
botmeta
=> Enable ansibullbot notifications in issues and PRs

changelogs/fragments/3395-nmcli-needs-type.yml, changelogs/fragments/3401-nmcli-needs-type.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
SUMMARY
Amended the 'routing-rules4'  module argument to accept key values as list. Currently it is accepting only 'str' values. In the event of adding multiple values to be added, 'routing-rules4' key needs to accept values as list.
ISSUE TYPE
COMPONENT NAME
nmcli
In plugins/modules/net_tools/nmcli.py#L1774 - routing_rules4=dict(type='str') . For adding multiple entries to routing-rules, we need to accept values as list.
BEFORE:
fatal: [192.168.235.157]: FAILED! => {
"ageingtime": 300,
"arp_interval": null,
"arp_ip_target": null,
"autoconnect": true,
"conn_name": "ens192",
"dhcp_client_id": null,
"dns4": null,
"dns4_ignore_auto": false,
"dns4_search": null,
"dns6": null,
"dns6_ignore_auto": …
=> nmcli: amended the routing-rules4 key values as list

changelogs/fragments/3426-copy-permissions-along-with-file-for-jboss-module.yml, plugins/modules/web_infrastructure/jboss.py
The deployment file is copied with file content only. The file
permission is set to 440 and belongs to root user. When the
JBossI(Wildfly) server is running under non root account, it can't read
the deployment file.
With is fix, the correct permission can be set from previous task for JBoss
server to pickup the deployment file.
Jboss
```paste below
```
=> Copy the permissions along with file for jboss module

tests/utils/shippable/shippable.sh
community.crypto 2.0.0 requires a new enough cryptography library, which Ubuntu 16.04 does not have.
CI
=> CI: Stick to community.crypto 1.x.y for ubuntu1604

changelogs/fragments/3473-gitlab_deploy_key-fix_idempotency.yml, plugins/modules/source_control/gitlab/gitlab_deploy_key.py
Fix gitlab_deploy_key idempotency
It was not idempotent on projects with multiple keys because it was not comparing current key with all existing ones.
SEE: https://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination
=> Fix: gitlab_deploy_key idempotency

plugins/modules/source_control/gitlab/gitlab_project.py, tests/integration/targets/gitlab_project/tasks/main.yml, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_project.py
Adds `initialize_with_readme` option to `gitlab_project` module.
gitlab_project
This option is available via the API and is helpful when creating projects without having to programmatically initialize it to be able to push up to the repo.
=> gitlab_project: Add `initialize_with_readme` option

changelogs/fragments/3609-fix-keycloak-client-diff-bugs-when-sorting.yml, changelogs/fragments/3610-fix-keycloak-client-diff-bugs-when-sorting.yml, plugins/modules/identity/keycloak/keycloak_client.py, tests/integration/targets/keycloak_client/README.md, tests/integration/targets/keycloak_client/docker-compose.yml, tests/integration/targets/keycloak_client/tasks/main.yml, tests/integration/targets/keycloak_client/vars/main.yml
Fixes #3609.
* Updates the module, `keycloak_client` so that `--check` does not report differences that are the result of sorting, default values, and unique internal id's, (e.g. of each `protocol_mappers`)
* Adds a readme and description of how to perform testing using docker.
See the git history for the steps to reproduce (I used test-driven fixing):
* The first commit introduces a test that does not fail, (because it doesn't have any of the attributes that cause a difference.
* Subsequent commits update the test so that a failure is demonstrated resulting from sorting issues.
* Subsequent commits change the code to fix it.
=> Bugfix keycloak client do not report changes when there is none

tests/integration/targets/lookup_random_words/test.yml
The last test failed this night: https://dev.azure.com/ansible/community.general/_build/results?buildId=28400&view=logs&j=c7ffc934-fbed-562a-6e45-fd1f90b7af39&t=ce367ec3-f892-585f-7ff6-26f664cc2334
random_words lookup
=> Fix random_words lookup tests

plugins/modules/source_control/gitlab/gitlab_runner.py
Fixes #3623 and provides a more fitting description for the `maximum_timeout` parameter of the `community.general.gitlab_runner` module.
gitlab_runner.py
I'm happy to change the wording and simply provided a first possible improvement to discuss further.
=> provide more fitting description for runner timeout

changelogs/fragments/3626-fix-one_image-error.yml, plugins/modules/cloud/opennebula/one_image.py
While porting this module to make use of `pyone` I have overlooked one attribute.  Luckily the error only occurs while handling the error condition of trying to rename an image to a name that has already been taken.
Instead of telling the user which image ID already uses that name, the module failed with the following error (along with a huge backtrace):
```
AttributeError: 'IMAGESub' object has no attribute 'id'
```
With this PR the error message is much more obvous again, for example:
```
fatal: [localhost]: FAILED! => changed=false 
msg: Name 'cloudimg-rocky-8-but-more-awesome' is already taken by IMAGE with id=9357
```
one_image
Our team noticed this `by accident` while doing some automated base image creation using the OpenNebula modules.
<details> …
=> opennebula: fix error message when renaming an image

changelogs/fragments/2045-bitbucket_support_basic_auth.yaml, plugins/doc_fragments/bitbucket.py, plugins/module_utils/source_control/bitbucket.py, plugins/modules/source_control/bitbucket/bitbucket_access_key.py, plugins/modules/source_control/bitbucket/bitbucket_pipeline_key_pair.py, plugins/modules/source_control/bitbucket/bitbucket_pipeline_known_host.py, plugins/modules/source_control/bitbucket/bitbucket_pipeline_variable.py, tests/unit/plugins/modules/source_control/bitbucket/test_bitbucket_access_key.py, tests/unit/plugins/modules/source_control/bitbucket/test_bitbucket_pipeline_key_pair.py, tests/unit/plugins/modules/source_control/bitbucket/test_bitbucket_pipeline_known_host.py, tests/unit/plugins/modules/source_control/bitbucket/test_bitbucket_pipeline_variable.py
Support Basic Auth
TODO:
* ~Option 1. Rename current `username` to `workspace` to follow API semantic (that did confuse me at first as my company is not a username)~
* Option 2. Use `user` for Basic Auth username (risk to be confusing, deprecate current usage of `username`)
* ~Option 3. ?~
Close #2044
bitbucket_access_key
bitbucket_pipeline_key_pair
bitbucket_pipeline_known_host
bitbucket_pipeline_variable
Bitbucket API - Authentication methods:
https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication#app-pw
=> bitbucket: Support Basic Auth

changelogs/fragments/3649-proxmox_group_info_TypeError.yml, plugins/modules/cloud/misc/proxmox_group_info.py
- File proxmox_group_info.py creates the error "TypeError: 
get_group() got an unexpected keyword argument \'group\'\r\n'" if a
group parameter is used.
Issue is an argument naming conflict. After changing the argument 
name to 'groupid', as used in method ProxmoxGroupInfoAnsible::get_group,
testing a Proxmox group name is working now.
```paste below
```
=> Fixed - TypeError: unexpected keyword argument

changelogs/fragments/3648-mh-cmd-publish-cmd.yaml, plugins/module_utils/mh/mixins/cmd.py
Adds `publish_cmd` option to `run_command()`, allowing the developer to control whether the command arguments are published in the module result or not. 
=> mh/mixins/cmd - added publish_cmd parameter to CmdModuleHelper.run_command()

changelogs/fragments/3655-use-publish_cmd.yaml, plugins/modules/packaging/language/ansible_galaxy_install.py, plugins/modules/packaging/language/pipx.py, plugins/modules/packaging/os/snap_alias.py
These three modules have the same mechanics: they run a "state gathering" function before and after executing the actual command. Because we lacked the `publish_cmd` option in `MH.run_command()`, the output value `cmd_args` would always contain the arguments of the *after*-state-gathering call. Instead, what made sense was to show the command actually executed.
plugins/modules/packaging/os/snap_alias.py
=> fix modules' output by using publish_cmd

.github/BOTMETA.yml, plugins/lookup/collection_version.py, tests/integration/targets/lookup_collection_version/aliases, tests/integration/targets/lookup_collection_version/collections/ansible_collections/testns/testcoll/galaxy.yml, tests/integration/targets/lookup_collection_version/collections/ansible_collections/testns/testcoll/plugins/modules/collection_module.py, tests/integration/targets/lookup_collection_version/collections/ansible_collections/testns/testcoll_mf/FILES.json, tests/integration/targets/lookup_collection_version/collections/ansible_collections/testns/testcoll_mf/MANIFEST.json, tests/integration/targets/lookup_collection_version/collections/ansible_collections/testns/testcoll_mf/plugins/modules/collection_module.py, tests/integration/targets/lookup_collection_version/collections/ansible_collections/testns/testcoll_nothing/plugins/modules/collection_module.py, tests/integration/targets/lookup_collection_version/collections/ansible_collections/testns/testcoll_nv/galaxy.yml, tests/integration/targets/lookup_collection_version/collections/ansible_collections/testns/testcoll_nv/plugins/modules/collection_module.py, tests/integration/targets/lookup_collection_version/library/local_module.py, tests/integration/targets/lookup_collection_version/runme.sh, tests/integration/targets/lookup_collection_version/runme.yml
This lookup allows to query the version of a collection that's installed and loaded by the currently running Ansible version.
This can be useful in roles or playbooks that have to support a larger range of collection (or Ansible community package) versions, where backwards incompatible changes have been made, or where some operations can be optimized with new plugins/modules that are not available in all supported versions.
collection_version
=> Add collection_version lookup

tests/integration/targets/callback_yaml/aliases
This reverts commit 2324f350bcb257bc1ac39cee8ae734aa9acb96b9, and re-enables the yaml callback tests. This is possible since https://github.com/ansible/ansible/pull/76186 has been merged.
yaml callback tests
=> Revert "Temporarily disable yaml callback tests. (#3651)"

changelogs/fragments/3675-xattr-handle-base64-values.yml, plugins/modules/files/xattr.py
Fix an exception in xattr module when existing extended attribute's value contains non-printable characters and the base64-encoded string contains a '=' sign
xattr module tries to split the output of getfattr with the '=' sign, without taking into consideration that a base64-encoded value can have '=' sign itself. The patch introduces a maxsplit to prevent the value from being splitted.
Fixes #3673
xattr
```
=> Better handling of base64-encoded values in xattr module

.pre-commit-config.yaml, CONTRIBUTING.md, README.md
I don't know if this is something interesting to be applied to this project, please forgive me if this should be driving in a different form 🙏 
I decided to raise this PR based on my experience when contributing to the ansible collections, If some linting could be done and defined at the project level then I won't need to checkout the `ansible` repository in order to install the needed tools to validate if my contributions were healthy enough.
I didn't use the `ansible` tool chain much at the beginning, so I ended up by interacting with the CI builds to fix the existing linting errors, in addition to some other errors.
I assume this is something to be discussed broadly and maybe somewhere else, I only wanted to explain my motivation to use the pre-commit approach.
Then, what's this PR …
=> Add pre-commit for linting commits

changelogs/fragments/3625-nmcli_false_changed_mtu_fix.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
connection_options work differently when detecting changes for 802-3-ethernet.mtu parameter. It causes problems with applying mtu setting.
Fixes #3612
After little small discussion(#3615) i came out with this change. Basically it shouldn't break previous behavior, but also should fix #3612.
This how it should work: When we try to run playbook with type "dummy" and no mtu parameter setted ansible won't do any changes and also will display no diff, but after you set(any way possible) mtu to some value except 0, next time you gonna run playbook without mtu it will change it to "auto" and will also show diff.
=> Fix dummy interface returning changed

changelogs/fragments/3681-lvol-fix-create.yml, plugins/modules/system/lvol.py
Fixes #3665 - allows lvols to be created with arguments prefixed with "+", to preserve old lvol.py behaviour
plugins/modules/system/lvol.py
=> Rework safety check on size arguments for when LV doesn't exist

plugins/modules/remote_management/redfish/redfish_command.py
Example command arg `boot_next` missing the underscore.
Fixes #3710
Add the underscore to make the arg `bootnext` valid `boot_next`.
```paste below
```
=> redfish_command: example command has wrong arg

changelogs/fragments/3667-ldap_search.yml, plugins/modules/net_tools/ldap/ldap_search.py
SUMMARY
LDAP Search module would not run in check mode unless "check_mode: no" was used. A search does not change anything, therefore running in check mode causes no harm and can help with troubleshooting issues.
Fixes #3619
ISSUE TYPE
COMPONENT NAME
ldap_search.py
no changed to module options
=> Allow LDAP search to run in check mode

tests/integration/targets/setup_redis_replication/defaults/main.yml, tests/integration/targets/setup_redis_replication/meta/main.yml, tests/integration/targets/setup_redis_replication/tasks/setup_redis_cluster.yml, tests/utils/constraints.txt
Looks like the 4.0.0 release from today requires Python >= 3.6.
=> Restrict redis version in CI

changelogs/fragments/3694-gitlab-cleanup.yml, plugins/module_utils/gitlab.py, plugins/modules/source_control/gitlab/gitlab_deploy_key.py, plugins/modules/source_control/gitlab/gitlab_group.py, plugins/modules/source_control/gitlab/gitlab_group_members.py, plugins/modules/source_control/gitlab/gitlab_group_variable.py, plugins/modules/source_control/gitlab/gitlab_hook.py, plugins/modules/source_control/gitlab/gitlab_project.py, plugins/modules/source_control/gitlab/gitlab_project_members.py, plugins/modules/source_control/gitlab/gitlab_project_variable.py, plugins/modules/source_control/gitlab/gitlab_protected_branch.py, plugins/modules/source_control/gitlab/gitlab_runner.py, plugins/modules/source_control/gitlab/gitlab_user.py, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_deploy_key.py, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_group.py, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_hook.py, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_project.py, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_runner.py, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_user.py
This cleans up the gitlab modules a bit to consistently use snake_case conventions (which is used in the newer modules, core utils, and python-gitlab). No functional change, but it's a small first step toward de-duplicating some of the code in those modules. It might help with implementing things like https://github.com/ansible-collections/community.general/issues/3669 in other modules.
I'm not sure if you accept these style-only PRs but thought I'd try. In case the PR is a bit cumbersome to review I split it into these commits (I can also split the PR):
- b04c5639 gitlab: use snake_case consistently in variables
- 92e03bd5 gitlab: use snake_case consistently in methods and functions
- 10f9a127 gitlab: remove dead code in module_utils
gitlab
Not sure where the …
=> gitlab: clean up modules and utils

changelogs/fragments/3693-add-redfish-host-interface-info-support.yml, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/redfish/redfish_info.py
Adding a GetHostInterfaces command to redfish_info in order to report the
following:
- Properties about the HostInterface(s) like Status, InterfaceEnabled, etc
- ManagerEthernetInterface (info on BMC -> host NIC)
- HostEthernetInterfaces (list of NICs for host -> BMC connectivity)
fixes #3692
In retrospect, I should have added this functionality with #3631 / #3632.
redfish_info
Note that I moved some of the functionality that was previously in `get_nic_inventory()` to `get_nic()` (new) in order to DRY out some of the functionality to gather `EthernetInterface` information.
=> Add GetHostInterfaces command to redfish_info

changelogs/fragments/3708-listen_ports_facts-add-ss-support.yml, plugins/modules/system/listen_ports_facts.py, tests/integration/targets/listen_ports_facts/tasks/main.yml
This PR adds support for command `ss` to module `listen_ports_facts`.
Some distros do not include `netstat` in their base installs anymore, whereas `ss` is included.
Default behaviour is extended to try supported commands one by one until one is existing on the machine.
`netstat` is tried first, as it is the current default and `ss` returns all processes per listen address & port.
A user can override the auto-detection by passing the argument `command` for either `netstat` or `ss`.
Modified integration tests accordingly and tested with them successfully on:
* Debian 9, 10, 11
* Ubuntu 16.04, 18.04, 20.04
* CentOS 7, 8, Stream
* RedHat 7, 8
listen_ports_facts
```paste below
<no output changes>
```
=> listen_ports_facts: Added support for ss

changelogs/fragments/1088-nmcli_add_multiple_addresses_support.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
This PR adds support of multiple ipv4 addresses on one interface which was requested here #1088.
As it turns out changing type of parameter is enough to make it work.
Now list can be used in ```ip4``` parameter in playbook, but string is also working, so it's backwards compatible.
I didn't add any additional test or documentation just for now. I think such change need to be discussed first.
=> change ip4 type to list of str

.github/BOTMETA.yml, plugins/inventory/xen_orchestra.py, tests/unit/plugins/inventory/test_xen_orchestra.py
This adds an ansible inventory plugins that lists and group by types the following assets:
- Virtual machines
- Hosts
- Pools
xen_orchestra
As vm's are not guaranteed to have an ip [1], I opted to use the assets uuid's instead, as they are consistent across all asset types.
This is lacking tests, although I have a fair understanding of what kind of tests need to be added to this PR, I don't get how to run them. 😄 
Also: I will cleanup the commit history as needed.
[1] A vm without the xen tools or a vm in a `Shutdown` state will not have an ip.
=> Xen orchestra inventory plugin

changelogs/fragments/3661-lxd_container-add-vm-support.yml, plugins/modules/cloud/lxd/lxd_container.py
This MR adds support to lxd_container module to deploy either containers or virtual-machines. For that it was necessary to create two new parameters `api_endpoint` and `type`:
* `api_endpoint`: is required in order to be backwards compatible with old LXD servers, which does not support the new API endpoint `/1.0/virtual-machines` or `/1.0/instances` (implemented in [lxd 3.19](https://discuss.linuxcontainers.org/t/lxd-3-19-has-been-released/6529))
* `type`: there is two different types of instances, “container” or “virtual-machine”
It is related to:
* https://github.com/ansible-collections/community.general/pull/3519
It is a different approach of an open MR:
* https://github.com/ansible-collections/community.general/pull/3480
lxd_container
The old functionality has …
=> lxd_container: support lxd instance types

plugins/inventory/xen_orchestra.py
Currenly xen_orchestra breaks the sanity tests (https://github.com/ansible-collections/community.general/runs/4272234512) since it uses `packaging.version`, which is not available everywhere.
Replacing it by `distutils.version.LooseVersion`, which we commonly use to compare versions and which is available everywhere.
xen_orchestra
=> xen_orchestra: replace usage of packaging.version with distutils.version.LooseVersion

changelogs/fragments/2386-github_repo-fix-idempotency-issues.yml, plugins/modules/source_control/github/github_repo.py, tests/unit/plugins/modules/source_control/github/test_github_repo.py
Fixes #2376.
Module github_repo sets parameter default values when not specified in existing repos.
github_repo
Module github_repo is applying defaults when repo already exists. However, defaults must be set only when the repo is created. Otherwise, not specifying a parameter will apply default value, which is a wrong behaviour.
Also, two tests are include in order to ensure this behaviour:
* `test_create_new_org_repo_incomplete`: new repo with default values
* `test_idempotency_existing_org_private_repo`: preserve `private` and `description` on existing repos
=> Bugfix: github_repo does not apply defaults on existing repos

changelogs/fragments/3702-ipmi-encryption-key.yml, plugins/modules/remote_management/ipmi/ipmi_boot.py, plugins/modules/remote_management/ipmi/ipmi_power.py
Fixes #3698 
This is a very naive PoC on how passing an IPMI encryption key to the `ipmi_boot` module could work. Similar change is needed in the `ipmi_power` module.
I would like feedback on if this is feasible - especially on things like portability. I am not sure it works on all Python versions and so on.
ipmi_boot
```paste below
no change to output
```
=> Support IPMI encryption key parameter in ipmi_boot

changelogs/fragments/3765-extend-open_iscsi-with-rescan.yml, plugins/modules/system/open_iscsi.py
According to issue 3767, adding a session rescan flag to add and utilize mapped_luns after login into a portal and target.
open_iscsi rescan flag
``` yaml
- name: Rescan Targets
open_iscsi:
rescan: true
target: "{{ item.0 }}"
register: iscsi_rescan
loop:
- iqn.1994-05.com.redhat:8c4ea31d28e
tags:
- rescan
```
```bash
TASK [Rescan Targets] ********************************************************************************************************************************************************************
changed: [node1] => (item=['iqn.1994-05.com.redhat:8c4ea31d28e'])
changed: [node2] => (item=['iqn.1994-05.com.redhat:8c4ea31d28e'])
TASK [Output rescan output] *************************************************************************************************************** …
```
=> extend open_iscsi to allow rescanning a session to discover new mapped LUN's #3763

changelogs/fragments/3758-pacman-add-stdout-stderr.yml, plugins/modules/packaging/os/pacman.py
The pacman module, unlike the apt one, currently does not provide a way to obtain stdout and stderr. stderr is particularly useful to obtain warnings after a system upgrade, for instance.
pacman
I followed the model of ansible.builtin.apt to provide stdout and stderr in all useful cases:
- package(s) install
- package list update
- system upgrade
- package(s) removal
=> pacman: add stdout and stderr as return parameters

changelogs/fragments/3785-python_requirements_info-versionless-op.yaml, plugins/modules/system/python_requirements_info.py, tests/integration/targets/python_requirements_info/tasks/main.yml
Module does not complain when a python package requirement is passed with a version operator but no version.
plugins/modules/system/python_requirements_info.py
=> python_requirements_info - fail when version operator used without version

plugins/module_utils/mh/mixins/deprecate_attrs.py, tests/integration/targets/module_helper/library/msimpleda.py, tests/integration/targets/module_helper/tasks/main.yml, tests/integration/targets/module_helper/tasks/msimpleda.yml
Added a `DeprecateAttrsMixin` in the `ModuleHelper` toolbox, to assist module developers deprecate classes or instance attributes in their Python classes in an Ansible-friendly way.
plugins/module_utils/mh/mixins/deprecate_attrs.py
=> MH DeprecateAttrsMixin

changelogs/fragments/3768-nmcli_fix_changed_when_no_mask_set.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
This is a backport of PR #3784 as merged into main (aae3ae1).
This PR was requested in #3776. So this just fork of branch in #3776 but with bugfix(#3768)
Most of information can be find in #3776. I should mention that i forked this way because this fix depends on adding list support in ipv6 parameter. That's why diff contains diff from #3776.
- `ip4` is not a list in `stable-3` so function to enforce cidr notation was made to accept a string.
- Doc updates related to `ip4` as a list were removed.
- Testcases related to `ip4` as a list and other features introduced after `stable-3` were removed.
- Mocks related to removed testcases were removed.
=> [PR #3784/aae3ae1a backport][stable-3] Fixing ip address without mask bug

changelogs/fragments/3806-xattr-run_command-list.yaml, plugins/modules/files/xattr.py
plugins/modules/files/xattr.py
=> xattr - invoke run_command passing list

changelogs/fragments/3805-iso_extract-run_command-list.yaml, changelogs/fragments/3808-logstash_plugin-run_command-list.yaml, plugins/modules/monitoring/logstash_plugin.py
plugins/modules/monitoring/logstash_plugin.py
=> logstash_plugin - invoke run_command passing list

changelogs/fragments/3821-monit-run-list.yaml, plugins/modules/monitoring/monit.py, tests/unit/plugins/modules/monitoring/test_monit.py
plugins/modules/monitoring/monit.py
=> monit - invoke run_command passing list

changelogs/fragments/3835-java-cert-run-list.yaml, plugins/modules/system/java_cert.py
plugins/modules/system/java_cert.py
=> java_cert - invoke run_command passing list

changelogs/fragments/3357-nmcli-eui64-and-ipv6privacy.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
This PR adds ipv6.addr-gen-mode and ipv6.ip6-privacy parameters support for nmcli module. Feature was requested in #3357
=> nmcli - add support for addr-gen-mode and ip6-privacy options

changelogs/fragments/3837-opentelemetry_plugin-honour_ignore_errors.yaml, plugins/callback/opentelemetry.py
Honour the `ignore_errors` when a task has failed with that configuration.
If a task has failed and the `ignore_errors` was set then the span status will be `UNSET`.
`opentelemetry`
Given the below playbook:
```yaml
---
- name: MyPlabook
tasks:
- name: failed_and_ignore_errors
shell: "exit 1"
ignore_errors: yes
- name: success_and_ignore_errors
shell: "exit 0"
ignore_errors: yes
```
Before:
After:
=> opentelemetry: honour ignore errors

changelogs/fragments/3849-mh-check-mode-decos.yaml, plugins/module_utils/mh/deco.py, tests/integration/targets/module_helper/library/msimple.py, tests/integration/targets/module_helper/tasks/msimple.yml
Added decorators `check_mode_skip` and `check_mode_skip_returns` for skipping methods when `check_mode=True`.
plugins/module_utils/mh/deco.py
=> MH decorators - added decorators for check_mode

changelogs/fragments/3862-interfaces-file-fix-dup-option.yaml, plugins/modules/system/interfaces_file.py, tests/integration/targets/interfaces_file/files/interfaces_ff_3841, tests/integration/targets/interfaces_file/tasks/main.yml
The code that checked whether the existing option already existed was flawed. Fixed.
Fixes #3841 
plugins/modules/system/interfaces_file.py
=> interfaces_file - fixed dup options bug

changelogs/fragments/3798-fix-lxd-connection-option-vars-support.yml, plugins/connection/lxd.py
The changes below are in attempt to "fix" the mapping of the inventory vars to the LXD connection plugin documented options.
plugins/connection/lxd.py
The following example assumes there exist a VM called 'vm1' that runs LXD, also this LXD instance manages the container 'container1'.
inventory
```shell
vm1:container1 ansible_lxd_remote=x.x.x.x ansible_lxd_host=container1
[lxd_containers]
vm1:container1
[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
```
playbook
```yaml
---
- name: Check/install python on LXD container nodes
hosts: lxd_containers
connection: lxd
tasks:
- name: Check if python3 is installed in container
ansible.builtin.raw: dpkg -s python3
register: python_install_check
failed_when: …
```
=> Update lxd connection to use all documented vars for options

changelogs/fragments/3838-jira-token.yaml, plugins/modules/web_infrastructure/jira.py
* jira - Add support for Bearer token auth
* added changelog fragment
Co-authored-by: Felix Fontein <felix@fontein.de>
Allow the use of personal access tokens with JIRA
username and passwords are currently "required".
If token is set, then the Authorization header is changed
to use:
Authorization: Bearer <token>
instead of the previous:
Authorization: Basic <base64 encoding of user:pass>
If the policy of the JIRA instance prohibits the use of BasicAuth
for API calls, this would be a method to allow users to use the
ansible module.
jira
```paste below
```
=> jira - Add support for Bearer token auth

changelogs/fragments/3840-hponcfg-mh-revamp.yaml, plugins/modules/remote_management/hpilo/hponcfg.py
Revamped the module using ModuleHelper. By default that adds the improvement on calling `run_command` with a list instead of a string.
plugins/modules/remote_management/hpilo/hponcfg.py
=> hponcfg - revamped the module using ModuleHelper

changelogs/fragments/3896-nmcli_vlan_missing_options.yaml, plugins/modules/net_tools/nmcli.py
Signed-off-by: Jean-Francois Panisset <panisset@gmail.com>
When calling the `nmcli` module, forward the missing options:
- flags
- ingress
- egress
to the corresponding `nmcli` command line options instead of silently ignoring them.
Fixes #1086
`plugins/modules/net_tools/nmcli.py`
When calling:
```ansible
- name: Create VLAN network interface 200
conn_name: "enpXXsYYf0.200"
ifname: "enpXXsYYf0.200"
type: "vlan"
vlandev: "enpXXsYYf0"
vlanid: "200"
flags: "1"
ingress: "0:5"
egress: "0:5"
```
verify that the output of `nmcli conn show enpXXsYYf0.200` shows the expected values for:
```none
vlan.parent:                  enpXXsYYf0
vlan.id:                      200
vlan.flags:                   1 (REORDER_HEADERS)
vlan.ingress-priority-map:    0:5 …
```
=> Pass missing vlan-related options (flags, ingress, egress) to nmcli

changelogs/fragments/3874-proxmox-fix-onboot-param.yml, plugins/module_utils/proxmox.py, plugins/modules/cloud/misc/proxmox.py
Preventing type casting `None` to `int` for all bool options in the Proxmox module (LXC).
Fixes #3844
- Implemented conversion function in module_utils for reuse in other Proxmox modules.
=> proxmox - fixing onboot parameter causing module failure when not defined

changelogs/fragments/3909-nrdp_fix_string_args_without_encoding.yaml, plugins/callback/nrdp.py
Fixes #3903 nrdp string arguments without an encoding
nrdp callback
Uses to_bytes from ansible.module_utils.common.text.converters to convert string to bytes.
=> Fix nrdp string arguments without an encoding

changelogs/fragments/3875-icinga2-inv-fix.yml, plugins/inventory/icinga2.py, tests/unit/plugins/inventory/test_icinga2.py
Fixes #3875. 
Includes some error handling where the give filter produces no results. Instead of producing a 404, the plugin provides a more informative error message.
Previously the address field was used to populate the host's entry in the inventory as it seemed to be more value able as Icinga uses this to connect. This was short sighted. Instead, by default, the host object name will be used as the inventory object name. If the address field in Icinga is populated, it will be used as the ansible_host variable for that object to use as the connection value for Ansible/AWX/Tower. **This will break filtering for current users** If you still want to use address as the inventory entry, place `inventory_attr: address` into your config file for the module.
Icinga2 …
=> Icinga2 Inventory Plugin - Error handling and inventory name changer

changelogs/fragments/3919-xfconf-baseclass.yaml, plugins/modules/system/xfconf.py
Using `CmdStateModuleHelper` as base class, instead of explicitly importing `CmdMixin`, `StateMixin` and `ModuleHelper`.
=> xfconf - using aggregated base class

changelogs/fragments/3926-fix-gitlab-project-avatar-path.yml, plugins/modules/source_control/gitlab/gitlab_project.py
Any call to gitlab_project to create with avatar_path undefined will throw an exception
gitlab_project
=> fix gitlab_project avatar_path open when undefined bug (#3926)

changelogs/fragments/705-gitlab-auth-support.yml, plugins/doc_fragments/gitlab.py, plugins/module_utils/gitlab.py, plugins/modules/source_control/gitlab/gitlab_branch.py, plugins/modules/source_control/gitlab/gitlab_deploy_key.py, plugins/modules/source_control/gitlab/gitlab_group.py, plugins/modules/source_control/gitlab/gitlab_group_members.py, plugins/modules/source_control/gitlab/gitlab_group_variable.py, plugins/modules/source_control/gitlab/gitlab_hook.py, plugins/modules/source_control/gitlab/gitlab_project.py, plugins/modules/source_control/gitlab/gitlab_project_members.py, plugins/modules/source_control/gitlab/gitlab_project_variable.py, plugins/modules/source_control/gitlab/gitlab_protected_branch.py, plugins/modules/source_control/gitlab/gitlab_runner.py, plugins/modules/source_control/gitlab/gitlab_user.py
Add the following additional ways to authenticate:
- username/password via oauth_token
- oauth_token
- job_token
Fixes #705
Other small changes:
- removed unused imports from module_utils.gitlab
- fix bug in gitlab_project to check if avatar_path is provided
gitlab_branch
gitlab_group_variable
gitlab_runner
gitlab_group
gitlab_hook
gitlab_project
gitlab_protected_branch
gitlab_user
=> Add additional auth support to Gitlab (#705)

tests/integration/targets/filesystem/tasks/setup.yml
Right now the filesystem tests don't run on their own on OpenSuSE; they need the cloud_init_data_facts tests to run first. (These install `cloud-init`, which has `util-linux-systemd` as a dependency, and that contains the `findmnt` CLI tool which the `filesystem` tests need.)
(Fixes the issue seen here: https://github.com/ansible-collections/community.general/pull/3936#pullrequestreview-838926693)
filesystem
=> Fix filesystem tests (so they run on their own)

changelogs/fragments/3374-add-ipa-ptr-sync-support.yml, plugins/modules/identity/ipa/ipa_dnszone.py
Fixes #1687 
IPA
Allows support for the `idnsallowsyncptr` in the IPA REST API:
```
{
"id": 0, 
"method": "dnszone_mod/1", 
"params": [
[
"foo.bar"
], 
{
"idnsallowsyncptr": true, 
"version": "2.237"
}
]
}
```
=> ipa_dnszone: add PTR synchronization support for dnszones

changelogs/fragments/3940_fix_contenttype_scaleway_user_data.yml, plugins/modules/cloud/scaleway/scaleway_user_data.py
Fix the key named Content-type in Content-Type
Bug fixed:
In file who do the HTTP request  ( module_utils/scaleway.py , ligne 130 ), it's "Content-Type" ( with big T) in the key.
The send fonction ( in module_utils/scaleway.py ) found default value ( application/json )  instead of "text/plain" and do jsonify  and the cloud-init send to server is ususable.
scaleway_user_data
Reproduce:
Test to put a cloud-init value in a scaleway's server and see it on the serveur with scw-userdata cloud-init:  you will see double-quote at the begin and the end
With the fix: no unexpected "
=> fix  scaleway_user_data

tests/utils/shippable/units.sh
=> Restrict redis to < 4.1.0 for ansible-base 2.10

tests/utils/shippable/shippable.sh, tests/utils/shippable/units.sh
Backport of #3955 to stable-1.
CI
=> [stable-1] Restrict redis to < 4.1.0 for ansible-base 2.10

changelogs/fragments/3933-slack-charset-header.yaml, plugins/modules/notification/slack.py
Fixes #3932
Add `charset=UTF-8` to the `Content-type` header to avoid warnings from the Slack API.  
~~It is a naive implementation, but UTF-8 should be a pretty good/universal choice in my opinion. A more complete implementation might have a configurable charset but really shouldn't everyone be using UTF-8?~~
Edit: The Slack API only accepts UTF-8 ("all messages must use UTF-8 encoding") so there is no need for further flexibility and the hardcoding to UTF-8 should be right.
slack
Before:
```paste below
[...]
ok: true
response_metadata:
warnings:
- missing_charset
ts: '1640000150.000000'
warning: missing_charset
[...]
```
After:
```
[...]
ok: true
ts: '1640000150.000000'
[...]
```
Fixes the `missing_charset` warning.
=> slack - use UTF-8 charset in content-type header

changelogs/fragments/3946-mattermost_attachments.yml, plugins/modules/notification/mattermost.py
Add the functionality to send attachments in Mattermost.
Closes: #3944
mattermost
I needed to remove the `required=True` at the `text` element and added additional documentation.
=> Mattermost: Add sending of attachments

changelogs/fragments/3934-distutils.yml, plugins/callback/say.py, plugins/connection/jail.py, plugins/connection/lxd.py, plugins/connection/zone.py, plugins/lookup/passwordstore.py
distutils has been deprecafed and will be removed from Python's stdlib in Python 3.12 (see https://www.python.org/dev/peps/pep-0632/). Let's stop using distutils.spawn.
say callback plugin
jail connection plugin
lxd connection plugin
zone connection plugin
passwordstore lookup plugin
=> Get rid of distutils.spawn and distutils.util

changelogs/fragments/3964-scaleway_volume_add_region.yml, plugins/modules/cloud/scaleway/scaleway_volume.py
Change of organization to project, depreciated in the api.
Added missing region parameter.
This module allows to create volumes on the scw datacenter
=> [Bug] Scaleway The volume is created systematically on par1

changelogs/fragments/3936-distutils.version.yml, plugins/module_utils/_version.py, plugins/module_utils/version.py
Closes #3979. This fixes the issue the current fix (#3936) had for Ansible 2.9 before 2.9.20, and ansible-base 2.10 before 2.10.8.
plugins/module_util/version.py
=> Use vendored copy of distutils.version

changelogs/fragments/3930-proxmox-add-clone.yaml, plugins/modules/cloud/misc/proxmox.py
This PR adds a 'clone' parameter to the proxmox module to clone a container. The implementation is based on the clone option in the proxmox_kvm module.
proxmox
A small todo list of things which I already know I should do:
=> proxmox: Add clone parameter

tests/utils/shippable/units.sh
These currently fail for Python 3.6+ due to a new pynacl release (pyGithub depends on it). The problem is (again) that `enum` is installed.
CI
=> Fix 2.9 unit tests

changelogs/fragments/3985-nmcli-add-wireguard-connection-type.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Add `wireguard` connection type support to `nmcli` module
Fixes #3750  
nmcli
=> nmcli: Add wireguard connection type support

tests/utils/shippable/remote.sh
Hopefully fixes CI. The latest [PyNaCL release 1.5.0](https://github.com/pyca/pynacl/blob/main/CHANGELOG.rst#150-2022-01-07) no longer ships `manylinux1` wheels, which are the wheel type supported by pip 9.x that comes with Python 3.6 on RHEL8 (see also https://github.com/pypa/manylinux#manylinux).
CI
=> Restrict PyNaCL to 1.4.x on RHEL8 when using Python 3.6

changelogs/fragments/3968-ipmi_power-add-machine-option.yaml, plugins/modules/remote_management/ipmi/ipmi_power.py
Add bridge IPMI request to the remote target address support to community.general.ipmi_power module.
This PR allows to ensure the power state of the machine(s) which can be reached through the remote target address.
The power state is checked and changed via bridge IPMI request. The IPMI request is supported by pyghmi 1.5.30 and later.
ipmi_power module
```paste below
- name: Ensure machine of which remote target address is 48 is powered on, and 50 is powered off
community.general.ipmi_power:
name: test.testdomain.com
user: admin
password: password
machine:
- targetAddress: 48
state: on
- targetAddress: 50
state: off
```
=> ipmi_power: Add machine option to ensure the power state via the remote target address

plugins/lookup/flattened.py
The example code was broken due to missing quotes, now it works.
=> Fix example code for flattened lookup

changelogs/fragments/3980-puppet-show_diff.yml, plugins/modules/system/puppet.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.9.txt
First, I'm new to this contribution thing and although I'm trying to follow the PR quick start guide I wouldn't be surprised if I'm not doing everything according to standards, so please be forgiving :)
https://github.com/ansible-collections/community.general/pull/1927 introduced deprecation for the `show_diff` parameter on the puppet module, it seems due to it being undocumented.
Since I believe it's worthwhile for a user to have the possibility to get change details when running puppet (not by default obviously, due to potential security concerns), I'm trying here to fix the documentation for that parameter to then be able to remove the deprecation.
Worth noting I haven't been able to run the sanity check yet (as described in the quick start guide):
``` …
```
=> puppet: Add documentation and remove deprecation for show_diff, keep deprecation for alias show-diff

changelogs/fragments/3976-fix-alternatives-parsing.yml, plugins/modules/system/alternatives.py
Fixes 'alternatives --display' output parsing when an alternative is part of a group.
alternatives
When an alternative is a part of a family (a group with master and slave links), an additional piece of information is present in  'alternatives --display' output , such as:
```
java - status is auto.
link currently points to /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.x86_64/jre/bin/java
/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-3.el8_5.x86_64/bin/java - family java-11-openjdk.x86_64 priority 1
slave alt-java: /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-3.el8_5.x86_64/bin/alt-java
...
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.x86_64/jre/bin/java - family java-1.8.0-openjdk.x86_64 priority 1800312
slave alt-java: …
```
=> fix alternatives parsing when they are part of a group

.github/BOTMETA.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/identity/keycloak/keycloak_realm_info.py, plugins/modules/keycloak_realm_info.py, tests/unit/plugins/modules/identity/keycloak/test_keycloak_realm_info.py
Add `keycloak_realm_info` module to provide obtaining realm public info. It's useful for getting realm public key that provide to non-Java bearer-only client (for example, Node.js adapter).
Related document of Keycloak: https://www.keycloak.org/docs/latest/securing_apps/#usage-2
`keycloak_realm_info`
Example:
```yaml
- name: Get a Keycloak public key
community.general.keycloak_realm_info:
realm: MyCustomRealm
```
=> New Module: Keycloak Realm Info

changelogs/fragments/4030-proxmox-has-proxmoxer.yml, plugins/module_utils/proxmox.py, plugins/modules/cloud/misc/proxmox_domain_info.py, plugins/modules/cloud/misc/proxmox_group_info.py, plugins/modules/cloud/misc/proxmox_snap.py, plugins/modules/cloud/misc/proxmox_storage_info.py, plugins/modules/cloud/misc/proxmox_tasks_info.py, plugins/modules/cloud/misc/proxmox_user_info.py, tests/unit/plugins/modules/cloud/misc/test_proxmox_tasks_info.py
Simplify code by moving Proxmox `HAS_PROXMOXER` check into `module_utils`.
proxmox
Extracted from https://github.com/ansible-collections/community.general/pull/4027.
=> Move Proxmox `HAS_PROXMOXER` check into `module_utils`.

changelogs/fragments/4043-fix-no-log-opentelemetry.yml, plugins/callback/opentelemetry.py
The opentelemetry plugin crashes when generating a trace containing a task with `no_log: true` set
`opentelemetry`
Given the below playbook:
```paste below
---
- name: MyPlaybook
tasks:
- name: set non secret
set_fact:
non_secret_var: hello
- name: set secret
set_fact:
secret_var: ssshhhh
no_log: true
```
The run produces:
=> opentelemetry: no_log:true causes exception when generating trace

changelogs/fragments/4052-fix-detection-of-installed-cargo-packages-with-hyphens.yaml, plugins/modules/packaging/language/cargo.py, tests/integration/targets/cargo/tasks/test_version.yml
Per [the suggestion here](https://github.com/ansible-collections/community.general/issues/4044#issuecomment-1013936673), I included `-` in the character set detected by the regex and it in fact fixes the issue. I've also double-checked that this will cover the full character set and it is the case.
Fixes #4044 
cargo
Output before the change can be found in #4044.
Output after the change:
```paste below
$ ansible-playbook example_playbook.yaml
ansible-playbook [core 2.12.1]
configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /home/ubuntu/ans/lib/python3.8/site-packages/ansible
ansible collection location = …
```
=> Fix detection of installed cargo packages with hyphens in name

changelogs/fragments/4026-fix-mail-callback.yml, plugins/callback/mail.py
* Fixes an exception when enabling the `community.general.mail` callback plugin.
* Fixes #4025.
* ~~Add some missing standard mail headers `Date`, `Message-ID`~~ (moved to #4056).
* ~~Fixes encoding issues of non-ascii characters~~ (moved to #4061).
`community.general.mail` callback plugin
=> Fix exception in the `mail` callback plugin

changelogs/fragments/4056-add-missing-mail-headers.yml, plugins/callback/mail.py
* Fixes #4055
* Adds the [mandatory `Date:` email header](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.1)
* Adds the [recommended `Message-ID:` email header](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.4)
`community.general.mail` callback plugin
~~This PR will conflict with #4026 and will need to be re-written once #4026 will be merged.~~ PR rebased
=> `mail`: add `Date` and `Message-ID` headers

changelogs/fragments/4062-nmcli-ipv6-routes-support.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Includes `routes6` and `route_metric6` parameters for nmcli module
nmcli
PR for issue reported at: https://github.com/ansible-collections/community.general/issues/4059
The change adds support for configuring IPv6 routes and metrics via the nmcli module
Before:
```paste below
$ ansible-playbook test.yml 
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
PLAY [Test ipv6 routes set up] ****************************************************************************************************************************************************************************************************************
TASK [Gathering Facts] …
```
=> Add nmcli support for IPv6 routes

changelogs/fragments/4036-onevm-add-release-action.yaml, plugins/modules/cloud/opennebula/one_vm.py
Adds the release action for OpenNebula VMs which are in the 'HOLD' state.
opennebula
Previously you could create VMs with the `vm_start_on_hold` parameter
but then ansible couldn't release the VMs so they would be scheduled to
run. This PR adds the ability to release VMs which are in the 'HOLD'
state.
=> one_vm: add release action

plugins/modules/remote_management/manageiq/manageiq_alerts.py
Noticed while working on https://github.com/ansible-community/antsibull/pull/389.
manageiq_alerts
=> Fix missing '>'.

changelogs/fragments/4039-cluster-container-wait.yml, plugins/module_utils/lxd.py, plugins/modules/cloud/lxd/lxd_container.py
Fixes https://github.com/ansible-collections/community.general/issues/3999
In a cluster scenario where the node running the Ansible creates a container on another node in the cluster, the playbook would fail because the `Status != Success` it was equal to running because the container wasn't created yet and took a bit. This will keep checking the status while it is running and then proceed once it is no longer listed as running.
lxd module_util
If the containers are all created on the node which the Ansible is executing on, the problem will never show itself. 
See this discussion too: https://discuss.linuxcontainers.org/t/lxd-cluster-launch-command-creates-container-on-different-node-is-it-possible-to-disable-this-by-default/8389/8
Related: …
=> Adding while loop to wait for cluster container creation

changelogs/fragments/4050-properly-parse-json-lines-output-from-yarn.yaml, plugins/modules/packaging/language/yarn.py
As [explained here](https://github.com/ansible-collections/community.general/issues/4045#issuecomment-1014585718), yarn's `--json` option returns output in a JSON Lines format and the module did not handle that properly. This fixes that.
While the issue was discovered in #4045, the issue is not necessarily limited to it (though I couldn't come up with anything that would cause it in other cases).
yarn
This is not enough to address #4045 and #4048 is still needed to fix the lack of `~` expansion.
=> Properly parse JSON Lines output from yarn

changelogs/fragments/4048-expand-tilde-in-yarn-global-install-folder.yaml, plugins/modules/packaging/language/yarn.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.9.txt
As suggested [here](https://github.com/ansible-collections/community.general/issues/4045#issuecomment-1013936277), I'm making this change to fix the issue with `yarn` module ran with `global: true` always reporting its status as 'changed'
Related: #4045 
yarn
```paste below
...
```
=> Actually expand ~ in yarn global install folder

changelogs/fragments/4104-opentelemetry_plugin-enrich_docker_login.yaml, plugins/callback/opentelemetry.py
Enrich the span metadata for those ansible tasks that interact with `community.docker.docker_login`.
`callback/opentelemetry.py`
Given:
```
---
- name: Echo
tasks:
- name: Log into DockerHub
docker_login:
username: "{{ docker_user }}"
password: "{{ docker_password }}"
registry_url: https://index.docker.io/v1/
```
And the ElasticStack, then the Service Maps can see below
=> opentelemetry: enrich service for community.docker.docker_login

changelogs/fragments/4078-python_requirements_info.yaml, plugins/modules/system/python_requirements_info.py
Whichever mismatched package is evaluated last is the value stored in the
'mismatched' key. Instead, it should have a subdict for each pkg that is mismatched
to keep in line with its documented usage and how the `valid` return value is handled.
python_requirements_info
With `dependencies: ['salt==3003.3', 'jinja2<1']`:
Before:
```json
salt-master-us-east | SUCCESS => {
"mismatched": {
"desired": "jinja2>3",
"installed": "2.10"
},
}
```
After:
```json
salt-master-us-east | SUCCESS => {
"mismatched": {
"jinja2": {
"desired": "jinja2>3",
"installed": "2.10"
},
"salt": {
"desired": "salt==3003.3",
"installed": "3003"
}
},
}
```
=> python_requirements_info: don't overwrite results in 'mismatched' dict key

tests/utils/constraints.txt
Currently CI fails because of that.
CI
=> PyOpenSSL 22.0.0 no longer supports Python 2.7

changelogs/fragments/3935-use-gitlab-instance-runner-to-create-runner.yml, plugins/modules/source_control/gitlab/gitlab_runner.py
When using project it will use project level runner to create runner that based on python-gitlab it will be used for enabling runner and needs a runner_id so for creating a new runner it should use gitlab level runner
gitlab_runner
=> gitlab: use gitlab instance runner to create runner

changelogs/fragments/4092-fix_local_ports_regex_listen_ports_facts.yaml, plugins/modules/system/listen_ports_facts.py
This PR fix the bug reported in #4091 by fixing the regex used to parse ss local connection entry
listen_ports_facts
```
=> Fix local port regex in listen_ports_facts

changelogs/fragments/4088-add-constructed-interface-for-icinga2-inventory.yml, plugins/inventory/icinga2.py, tests/unit/plugins/inventory/test_icinga2.py
This change allows us to take `ansible_user` and `ansible_port` from Icinga2 Host objects if they are configured and contain the variables `vars.ansible_user` and` vars.ansible_port`.
community.general.icinga2
Example:
```
object Host "host-1" {
...
vars.ansible_user = "myuser"
vars.ansible_port = "2202"
...
}
```
=> Added new feature for ansible_user and ansible_port in Icinga2 inventory source

changelogs/fragments/4038-fix-and-rework-gitlb-project-variable.yml, plugins/modules/source_control/gitlab/gitlab_project_variable.py, tests/integration/targets/gitlab_project_variable/tasks/main.yml
Closes: #1952 
Closes: #4074
First tests looks promising.
```yml
- name: previous way. still works
community.general.gitlab_project_variable:
api_url: https://gitlab.com
api_token: "{{ some_token }}"
project: markuman/dotfiles
purge: false
vars:
ACCESS_KEY_ID: abc123
SECRET_ACCESS_KEY:
value: 3214cbad
masked: true
protected: true
variable_type: env_var
environment_scope: '*'
- name: new way, works also
community.general.gitlab_project_variable:
api_url: https://gitlab.com
api_token: "{{ some_token }}"
project: markuman/dotfiles
purge: false
variables:
- name: ACCESS_KEY_ID
value: abc123
- name: SECRET_ACCESS_KEY
value: 3214cbad
masked: true
protected: true
variable_type: env_var
environment_scope: '*'
```
What's left is
=> Fix and rework gitlab_project_variable

.azure-pipelines/azure-pipelines.yml
See https://github.com/ansible-collections/news-for-maintainers/issues/3. For our old stable branches, this looks like the easiest route. For the newer ones, we try #4132 first.
CI
=> [stable-1] Remove CentOS 8 from CI

.azure-pipelines/azure-pipelines.yml
See https://github.com/ansible-collections/news-for-maintainers/issues/3. For our old stable branches, this looks like the easiest route. For the newer ones, we try #4132 first.
CI
=> [stable-2] Remove CentOS 8 from CI

changelogs/fragments/4140-mail-callback-options.yml, plugins/callback/mail.py
See the discussions in #4061.
While right now it is not possible to specify lists in ansible.cfg except as comma-separated lists, this allows us to get rid of the `split(',')` in favor of something that's more future proof.
mail callback
=> mail callback: fully use Ansible's option handling; deprecate not specifying sender

changelogs/fragments/3703-force-install-homebrew-cask.yml, plugins/modules/packaging/os/homebrew_cask.py, tests/integration/targets/homebrew_cask/aliases, tests/integration/targets/homebrew_cask/defaults/main.yml, tests/integration/targets/homebrew_cask/tasks/main.yml
Per [suggestion](https://github.com/ansible-collections/community.general/issues/3703#issuecomment-1020909235), fixed bug that prevented force install of homebrew casks and added integration tests.
Fixes #3703 
homebrew_cask
=> homebrew_cask: reinstall when force is install option

plugins/modules/system/xfconf.py
See https://docs.ansible.com/ansible/latest/collections/community/general/xfconf_module.html#authors
antsibull accepts `any`, which ansible-test right now does not accept.
xfconf
=> xfconf: fix return value documentation to use a valid value for 'type'

changelogs/fragments/4150-gitlab-project-variable-absent-fix.yml, plugins/modules/source_control/gitlab/gitlab_project_variable.py, tests/integration/targets/gitlab_project_variable/tasks/main.yml
When delete project variables, the value is not necessary.  
It's a bug that was introduced with the new `variables` parameter in 4.4.0  
It works like this before: https://github.com/ansible-collections/community.general/blob/stable-2/plugins/modules/source_control/gitlab/gitlab_project_variable.py#L250
```paste below
```
=> gitlab_project_variable: Allow delete without value

plugins/inventory/proxmox.py
The default behavior of providing the given name from Proxmox as the connection string only works if the name in Proxmox is resolvable by system DNS, which may not be true. I'd like to do a Feature Addition to add this functionality to the actual plugin, but until one exists, having the documentation to support a workaround is much better than nothing.  
There may be occasions in which you are trying to test a playbook or role, and want to make sure that the play you are executing is running against a given inventory (e.g. static vs dynamic, or during development). Having an example of how to add a literal string to each host is helpful, since the default "expected" behavior of `my_var_name: my_var_value` doesn't work, because Jinja2 just tries to interpret my_var_value to a value. …
=> Update Proxmox Inventory Documentation with additional examples

changelogs/fragments/4029-proxmox-refactor.yml, plugins/module_utils/proxmox.py, plugins/modules/cloud/misc/proxmox.py, plugins/modules/cloud/misc/proxmox_kvm.py, plugins/modules/cloud/misc/proxmox_nic.py, plugins/modules/cloud/misc/proxmox_snap.py, plugins/modules/cloud/misc/proxmox_template.py, tests/unit/plugins/modules/cloud/misc/test_proxmox_kvm.py, tests/unit/plugins/modules/cloud/misc/test_proxmox_snap.py, tests/unit/plugins/modules/cloud/misc/test_proxmox_tasks_info.py
Use shared `module_utils` for all Proxmox modules.
proxmox*
Extracted from https://github.com/ansible-collections/community.general/pull/4027 for easier review.
=> Refactor all Proxmox modules to use shared `module_utils`.

changelogs/fragments/3916-fix-vdo-options-type.yml, plugins/modules/system/vdo.py
Per [fix](https://github.com/ansible-collections/community.general/issues/3916#issuecomment-1020812328), fix error thrown when using vdo module.
Fixes #3916 
vdo
=> vdo: Remove unused variable

changelogs/fragments/4151-dconf-catch-psutil-nosuchprocess.yaml, plugins/modules/system/dconf.py
Original code goes through all the pids for this user, tries to extract the D-Bus session bus address from environment, and ensures it is possible to connect to it.
Since time when pids were listed and a pid is being processed the pid could disappear which means we cannot get additional properties of the process like `uids()` or `environs()`. We could safely skip this process in a hope that there will be another one that still exists and we could inspect it. Similar skipping existed even before this change when one gets `AccessDenied` from `psutil`.
Fixes #4151
dconf
=> dconf: Skip processes that disappeared while we inspected them

plugins/modules/cloud/misc/proxmox_kvm.py
As discussed in PR #4106 (see https://github.com/ansible-collections/community.general/pull/4106#issuecomment-1033967040), this adds a link to the Proxmox VE Administration Guide where relevant for storage format selection, to help the user better decide a format supported by the storage backend they choose.
modules/cloud/misc/proxmox_kvm.py
While implementing PR #4106 it became clear that the documentation is somewhat lacking readability and clarity with regards to storage formats. It's been suggested that a link to the Proxmox VE Administration Guide section relative to storage be added to these options where they appear to help the user better understand the options choicces.
=> [modules/cloud/misc/proxmox_kvm] Update docs for storage format option

changelogs/fragments/4105-opentelemetry_plugin-enrich_jira_hetzner_jenkins_services.yaml, plugins/callback/opentelemetry.py
Enrich the span metadata for those ansible tasks that interact with:
- https://docs.ansible.com/ansible/latest/collections/community/general/jira_module.html#parameter-uri
- https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_server_module.html#parameter-endpoint
- https://docs.ansible.com/ansible/latest/collections/community/general/jenkins_plugin_module.html#parameter-updates_url
`callback/opentelemetry.py`
=> opentelemetry: enrich services for jenkins, hetzner or jira

changelogs/fragments/4191-proxmox-add-win11.yml, plugins/modules/cloud/misc/proxmox_kvm.py
This PR will add Windows 11/Windows server 2022 to the list of OS types in Proxmox kvm module.
Closes #4023 ([comment](https://github.com/ansible-collections/community.general/issues/4023#issuecomment-1036581772))
proxmox_kvm
=> proxmox_kvm: add win11 to ostype

changelogs/fragments/4168-add-keycloak-url-timeout.yml, plugins/doc_fragments/keycloak.py, plugins/module_utils/identity/keycloak/keycloak.py
You can find a summary along with a discussion [here](https://github.com/ansible-collections/community.general/issues/4168) 
**IMPORTANT:** This pull request adds a new parameter to the keycloak module, the `connection_timeout`. 
If provided, it propagates this value as the optional value `timeout` to the `open_url()` calls. By default (if not defined), it inherits the 10 sec default value of the underlying `timeout` parameter. 
We decided to name it `connection_timeout` instead of just `timeout`, because we didn't want to have a naming collision with the task timeout parameter or the network-specific ones, as mentioned [here](https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html#command-timeout), but we could rename it into anything else in case …
=> Updated keycloak.py to allow defining connection timeout value (#4168)

changelogs/fragments/4106-proxmox-efidisk0-support.yaml, plugins/modules/cloud/misc/proxmox_kvm.py
- Fixes #1638
- When creating OVMF UEFI VMs, a EFI disk isn't created as well, leaving the user to manually add it through other means (i.e. Proxmox VE GUI or command line). This PR aims to correct this point by adding an `efidisk0` parameter to the module.
proxmox_kvm.py
I added the `efidisk0` parameter to the module, since it is already supported by the underlying proxmoxer interface the module uses to communicate with Proxmox VE API. This change actually involves only adding the correct parameter to the module, and passing it directly to the `create_vm` method since it already handles and undefined number of arguments. The parameter is also removed when updating a VM as are other parameters that handle disks.
As per [Proxmox VE …
=> [modules/cloud/misc/proxmox_kvm] Adding EFI disk support

changelogs/fragments/4136-gitlab_runner-make-project-owned-mutually-exclusive.yml, plugins/modules/source_control/gitlab/gitlab_runner.py, tests/unit/plugins/modules/source_control/gitlab/gitlab.py, tests/unit/plugins/modules/source_control/gitlab/test_gitlab_runner.py
This PR follows previous discussion in #3965.
Currently, `project` and `owned=no` can be used together, which leads to GitLab API error response.
This PR sets `owned` and `project` parameters as `mutually_exclusive`, since the concept of `owned` runner has no meaning for project runners.
gitlab_runner
This PR also rename internal `owned` variable to `list_all_shared_runners`, for the same reason (`owned` has no meaning for project runners, which was confusing).
=> gitlab_runner: Make owned and project mutually exclusive

tests/sanity/extra/no-unwanted-files.py
Preparation for https://github.com/ansible/ansible/pull/74963. Will fix extra sanity test failures in #4203.
(I only support `.yml` and not `.yaml` so we stick to one extension in this collection :) )
CI
=> Allow YAML docs in plugins/test/ and plugins/filters/

changelogs/fragments/4192-improve-passwordstore-consistency.yml, plugins/lookup/passwordstore.py
Given a password stored in _path/to/secret_, requesting the password
_path/to_ will literally return `path/to`. This can lead to using
weak passwords by accident/mess up logic in code, based on the
state of the password store.
This is worked around by applying the same logic `pass` uses:
If a password was returned, check if there is a .gpg file it could
have come from. If not, treat it as missing.
Fixes ansible-collections/community.general#4185
passwordstore
plugins/lookup/passwordstore
See:
- ansible-collections/community.general#4185
=> passwordstore: Prevent using path as password

changelogs/fragments/4086-rework_of_gitlab_proyect_variable_over_gitlab_group_variable.yml, plugins/modules/source_control/gitlab/gitlab_group_variable.py, tests/integration/targets/gitlab_group_variable/tasks/main.yml
Rework on gitlab_project_variable #4038 copied to gitlab_group_variable
Closes: #4074
gitlab_group_variable
Change to support the two kinds of instantiation:
- name: previous way. still works
community.general.gitlab_group_variable:
api_url: https://gitlab.com
api_token: "{{ some_token }}"
project: markuman/dotfiles
purge: false
vars:
ACCESS_KEY_ID: abc123
SECRET_ACCESS_KEY:
value: 3214cbad
masked: true
protected: true
variable_type: env_var
environment_scope: '*'
- name: new way, works also
community.general.gitlab_group_variable:
api_url: https://gitlab.com
api_token: "{{ some_token }}"
project: markuman/dotfiles
purge: false
variables:
- name: ACCESS_KEY_ID
value: abc123
- name: SECRET_ACCESS_KEY
value: 3214cbad
masked: true
protected: true
variable_type: env_var …
=> Rework of gitlab_project_variable over gitlab_group_variable

changelogs/fragments/4183-fix-yum_versionlock.yaml, plugins/modules/packaging/os/yum_versionlock.py
As an input the module receives names of packages to lock.
Those never matched existing entries and therefore always reported
changes.
For compatibility yum is symlinked to dnf on newer systems,
but versionlock entries defer. Try to parse both formats.
Fixes #2998 
=> yum_versionlock: Fix entry matching

changelogs/fragments/4061-fix-mail-recipient-encoding.yml, plugins/callback/mail.py
* Fixes #4060 
`community.general.mail` callback plugin
This PR will conflict with #4026 and will need to be re-written once #4026 will be merged.
=> `mail`: fix the encoding of the mail senders and recipients name

changelogs/fragments/4179-linode-inventory-cache.yaml, plugins/inventory/linode.py
This PR adds support for caching results from the Linode dynamic inventory plugin.
Because the Linode API module uses non-serializable custom classes, I store the raw JSON response from the API in the cache and recreate the `Instance` objects when reading from cache.
linode
I've confirmed that the inventory works as expected both with cache disabled and with it enabled.
=> linode: support cache in Linode dynamic inventory

changelogs/fragments/4206-imc-rest-module.yaml, plugins/modules/remote_management/imc/imc_rest.py
Fixes #4206
imc_rest
Fixes module failure due to the usage of itertools.izip_longest which is missing in Python 3.
Used ansible.module_utils.six.moves.zip_longest which is works in both Python 2 and 3.
```paste below
```
=> Fix module failure due to itertools.izip_longest

changelogs/fragments/4225-pmem_add_namespace.yaml, plugins/modules/storage/pmem/pmem.py, tests/unit/plugins/modules/storage/pmem/test_pmem.py
Add namespace and namespace_append options to pmem module.
- namespace: Configure the namespace of PMem
- namespace_append: Enables to append the new namespaces.
pmem
```yaml
- name: Configure the two namespaces.
community.general.pmem:
namespace:
- size: 1GiB
type: pmem
mode: raw
- size: 320MiB
type: pmem
mode: sector
```
=> pmem: Add namespace and namespace_append options

changelogs/fragments/4194-configurable-passwordstore-locking.yml, plugins/lookup/passwordstore.py
Passwordstore cannot be accessed safely in parallel, which causes
various issues:
- When accessing the same path, multiple different secrets are
returned when the secret didn't exist (missing=create).
- When accessing the same _or different_ paths, multiple pinentry
dialogs will be spawned by gpg-agent sequentially, having to enter
the password for the same gpg key multiple times in a row.
- Due to issues in gpg dependencies, accessing gpg-agent in parallel
is not reliable, causing plays to fail (this can be fixed by adding
`auto-expand-secmem` to _~/.gnupg/gpg-agent.conf_ though).
These problems have been described in various github issues in the past,
e.g., https://github.com/ansible/ansible/issues/23816 and https://github.com/ansible/ansible/issues/27277.
This cannot be worked around …
=> passwordstore: Add configurable locking

changelogs/fragments/4240-ansible_galaxy_install-no_deps.yml, plugins/modules/packaging/language/ansible_galaxy_install.py
Added option `no_deps` to the module, translating into the CLI option `--no-deps`.
Fixes #4174
=> ansible_galaxy_install: added no_deps option

tests/integration/targets/ansible_galaxy_install/aliases
https://github.com/ansible/galaxy/issues/2302
CI
=> Temporarily disable ansible_galaxy_install tests due to Galaxy failures

changelogs/fragments/4212-fixes-for-keycloak-user-federation.yml, plugins/modules/identity/keycloak/keycloak_user_federation.py, tests/unit/plugins/modules/identity/keycloak/test_keycloak_user_federation.py
This PR contains two bugfixes for the module `keycloak_user_federation`:
1. creating a user federation while specifying an id (that does not exist yet) no longer fail with a 404.
2. mappers auto-created by keycloak are matched and merged by their name and no longer create duplicated entries.
please refer to commit messages:
> **keycloak: fix creating a user federation w/ idempotent id**
> 
> Creating a user federation while specifying an id (that doesn't exist
yet) will fail with a 404. This commits fix this behavior.
and:
> **keycloak: fix user federation mapper duplication**
> 
> This commit fixes a bug where mappers are duplicated instead of
configured when creating a user federation.
> 
> When creating a user federation, some mappers are …
=> Fixes for keycloak_user_federation

tests/integration/targets/setup_java_keytool/tasks/main.yml
This has been failing for some days, see for example https://dev.azure.com/ansible/community.general/_build/results?buildId=36788&view=logs&j=dbebe795-726f-5309-154b-7ec77aedbab4&t=cd9f0fd2-ffdf-5e93-4772-5c3b02ceb333.
CI
=> Temporarily disable Java keytool installation on Archlinux

changelogs/fragments/4288-fix-4259-support-busybox-dd.yml, plugins/modules/files/filesize.py, tests/integration/targets/filesize/tasks/main.yml
~~I don't know why the module fails to create sparse files on Alpine linux, so I start by re-enabling these tests, to catch the error and then fix it.~~
Update 1: Alpine linux is mainly based on busybox, and its dd applet doesn't support `conv=sparse` flag. Although this flag is not needed since a `count=0` already does the job as expected. Removing it could also extend support for sparse files to OpenBSD, Solaris and AIX (their native dd implementations don't support `conv=sparse` too)
Fixes #4259
filesize
=> filesize: fix alpine linux sparse file

changelogs/fragments/4192-zypper-add-clean-deps.yml, plugins/modules/packaging/os/zypper.py
* zypper: support automatic removal of orphaned dependencies
- Add support for --clean-deps option during package removal, which
will clean up packages that were only installed as dependencies
of the package being removed.
`zypper remove --clean-deps` allows the user to specify that any packages that were installed as dependencies of a package being removed can be removed as well if they aren't required by any other packages.  This feature addition allows the zypper plugin to access this option by defining the `clean_deps` field as `true`.
zypper
For example, on a newly installed openSUSE or SLE system, the only built-in requirement for the entire `ruby` runtime is yast. It's possible to simply remove yast via a `state: absent` rule, but that only removes yast and …
=> zypper: support automatic removal of orphaned dependencies

changelogs/fragments/4286-pacman-url-pkgs.yml, plugins/modules/packaging/os/pacman.py, tests/integration/targets/pacman/tasks/main.yml, tests/integration/targets/pacman/tasks/package_urls.yml, tests/unit/plugins/modules/packaging/os/test_pacman.py
Fixes #4285
~~consider this a draft, it still lacks test cases for URL based packages.~~
pacman
=> pacman: re-adding support for URL based pkgs

changelogs/fragments/4287-fix-proxmox-vm-chek.yml, plugins/modules/cloud/misc/proxmox_kvm.py
Fixes https://github.com/ansible-collections/community.general/issues/4278.
proxmox_kvm
Add `ignore_missing` parameter since we only use this for checking if a VM already exists.
=> Fix error when checking if Proxmox VM exists.

changelogs/fragments/4312-pacman-groups.yml, plugins/modules/packaging/os/pacman.py
As stated in https://github.com/ansible-collections/community.general/commit/1580f3c2b4876aeb06a0c785a14c5a4e057e843e#commitcomment-67899699 , the new pacman module was using a shorthand option for `--groups` which is accepted by pacman, but not by other programs which have similar CLI interfaces.
This PR uses `--groups` as it should have in the first place.
Question:  should I add a simple integration test that installs yay and proceeds to install a simple package with it using the pacman module?
If so, would it be acceptable to download a fixed version of yay from github, check its checksum and use it for the test?
@felixfontein ^
=> pacman: user --groups instead of --group

changelogs/fragments/4318-pacman-restore-old-changed-behavior.yml, plugins/modules/packaging/os/pacman.py
Restores the `changed` behavior before the recent refactoring (https://github.com/ansible-collections/community.general/pull/3907).
Allows the following to return changed only when packages were upgraded:
```
- pacman:
update_cache: yes
upgrade: yes
```
And the following to return changed only when the foo package wasn't at the latest version:
```
- pacman:
name: foo
state: latest
update_cache: yes
```
pacman
=> pacman: don't always return changed w/ update_cache

changelogs/fragments/4306-proxmox-fix-error-on-vm-clone.yml, plugins/modules/cloud/misc/proxmox_kvm.py
Incorrect parameters for `get_vmid()` and `get_vm()` caused failures when
cloning VMs.
Fixes #4278
proxmox_kvm
proxmox_kvm module failed to create or clone VMs due to incorrect function parameters.
There is already a PR (4287) for this, but it only fixes the new VM case, clone still fails. This PR fixes the clone case as well.
```
TASK [gitlab-runner-ephemeral-prepare : Clone VM] ******************************
Tuesday 01 March 2022  09:33:42 +0000 (0:00:00.029)       0:00:00.050 ********* 
fatal: [freebsd-builder01.isnic.is -> localhost]: FAILED! => changed=false 
msg: No VM with name freebsd-builder01.isnic.is-temp found
```
=> proxmox: Fix error on VM clone (#4278)

changelogs/fragments/4316-pacman-remove-nosave.yml, plugins/modules/packaging/os/pacman.py, tests/integration/targets/pacman/tasks/main.yml, tests/integration/targets/pacman/tasks/remove_nosave.yml
New parameter: `remove_nosave`
When enabled, will pass `--nosave` to pacman when removing packages.
`--nosave` cannot be used with `--print-format` and thus it couldn't be
passed via extra_args. See #4315
The code adds the option right before the actual removal of the pkgs.
(This is based on an initial diff from @MorphBonehunter)
pacman
=> pacman: add support for remove_nosave

changelogs/fragments/4299-npm-add-production-with-ci-flag.yml, plugins/modules/packaging/language/npm.py, tests/unit/plugins/modules/packaging/language/test_npm.py
npm supports using `--production` with the `npm ci` command
see [npm ci](https://docs.npmjs.com/cli/v8/commands/npm-ci) and [npm install](https://docs.npmjs.com/cli/v8/commands/npm-install) documentation
npm
```
- name: run npm ci with production flag
community.general.npm:
path: npm_with_package_json
ci: true
production: true
```
```paste below
npm ci
npm ci --production
```
=> npm: add support for `production` flag when using `ci`

changelogs/fragments/4281-terraform-complex-variables.yml, plugins/modules/cloud/misc/terraform.py
Signed-off-by: Webster Mudge <wmudge@gmail.com>
Allow complex, i.e. lists and dictionaries, values in the `variables` parameter of the `terraform` module. Without this minor patch, complex values will fail due to formatting issues, i.e. `Single quotes are not valid. Use double quotes (\") to enclose strings.`
community.general.terraform
=> Allow complex values in variables parameter of terraform module

changelogs/fragments/4330-pacman-packages-update_cache.yml, plugins/modules/packaging/os/pacman.py, tests/unit/plugins/modules/packaging/os/test_pacman.py
1. Improves documentation on return value `packages` and option `update_cache`.
2. Make sure that `packages` is always returned if `name` is specified or `upgrade=true`.
3. Deprecate that `changed` from `upgrade_cache` is ignored when `name` is specified or `upgrade=true`. Provide workaround to keep current behavior.
4. Add `cache_updated` return value (returned when `update_cache=true`).
CC @jraby @foutrelis @aminvakil @artis3n
pacman
=> pacman: improve docs, make sure that packages is always returned, deprecate update_cache behavior

plugins/lookup/tss.py
Add a reference to environment variable REQUESTS_CA_BUNDLE to enable using self signed certificates (on-prem server) in documentation.
Add a reference to environment variable REQUESTS_CA_BUNDLE to enable using self signed certificates (on-prem server) in documentation.
tss.py
```paste below
```
=> Update doc. tss.py (env REQUESTS_CA_BUNDLE)

changelogs/fragments/4304-jira-fields-in-comment.yml, plugins/modules/web_infrastructure/jira.py
The 'fields' parameter could be used to merge in any arbitrary data to a jira comment.
Enhancement of comment creation in community.general.jira.
In jira issue creation, the 'fields' parameter is used to pass in any arbitrary data.
We adopted this to work also in jira comment creation.
In our jira service desk environment, we use it to set a property to mark the comment as 'internal'. 
Look at the example I added.
(Some explanation that helped to find the correct property for this:
https://stackoverflow.com/questions/45031475/how-to-create-an-internal-comment-on-a-jira-issue-using-the-jira-cloud-rest-api )
=> jira: Use fields in comment to merge in additional data

changelogs/fragments/3295-mksysb-revamp.yaml, plugins/modules/system/mksysb.py
Revamped the module + fixed bug: option should be `-A` instead of `-a`.
plugins/modules/system/mksysb.py
=> mksysb - revamped module + fix bug in backup_dmapi_fs option

plugins/modules/monitoring/datadog/datadog_monitor.py
Add a missing property for priority in datadog monitor module
`priority=module.params['priority'],`
=> datadog: Add missing priority

changelogs/fragments/4355-ldap-recursive-delete.yml, plugins/modules/net_tools/ldap/ldap_entry.py
* Fixes #3613
* Recursive deletion can be enabled with the `recursive` option. It is disabled by default.
ldap_entry
* The initial issue is a bug report, however I filed this PR as a Feature as the LDAP delete requests actually works as intended and the PR adds a new option.
* When enabled, deletion is attempted by sending a single delete request with the Subtree Delete control (`1.2.840.113556.1.4.805`). If that request fails with the `NOT_ALLOWED_ON_NONLEAF` error, the code tries deleting the whole branch in reverse order by running a search then sending individual delete requests.
* Example usage : 
```yaml
community.general.ldap_entry:
server_uri: ldapi:///
bind_dn: ...
bind_pw: ...
dn: ou=people,dc=example,dc=org
state: absent
recursive: true
```
=> ldap_entry - Recursive deletion

changelogs/fragments/4352-proxmox-inventory-filters.yml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
This PR is an attempt at addressing issue #3553 by adding a `filters` option containing a list of Jinja expressions that must all evaluate to a truthy value for the host to be added to the inventory.
Proxmox inventory component
* While the initial issue was tagged as being a bug, I think it is in fact a new feature, hence my selecting "Feature" as the issue type here.
* The initial code added the host to the inventory, then set its variables based on what it read from the Proxmox cluster and added it to various groups as soon as the information became available. This is not possible when it is not known whether the host should be added to the inventory in the first place. The modified code gathers all data to a separate dictionary, checks the specified filters based …
=> Proxmox inventory filters

changelogs/fragments/4349-proxmox-inventory-dict-facts.yml, plugins/inventory/proxmox.py
* Fixes #4348
* Parses all strings that have the `key=value,key=value,...` form into dicts, unless they are explicitly excluded.
Proxmox inventory plugin
* Re-use the (defined but unused) `plaintext_configs` variable to list configuration entries that should be ignored by the string to dictionary conversion code. At this point, it only contains the `description` string.
* Convert to a dictionary if the all substrings obtained by splitting off the initial value with commas contain a `=` character
* Limit substring splitting to a single split, so that a substring containing `a=b=c` will generate an `a` entry with value `b=c`.
* This changes the output of the plugin in some cases, and might cause incompatibilities, as some of the facts that used to be returned as …
=> Proxmox inventory plugin - Fix string to dict conversion

changelogs/fragments/4281-terraform-complex-variables.yml, plugins/modules/cloud/misc/terraform.py
This reverts commit 4cc7f413953606cda79596c7682eac0319936199 (#4281).
First step in fixing #4367.
terraform
=> Revert "Allow complex values in variables parameter of terraform module (#4281)"

plugins/lookup/nios_next_network.py
This is currently breaking stable-3's CI.
nios_next_network lookup
=> [stable-3] nios_next_network lookup: remove default for required=true option

plugins/doc_fragments/ldap.py
The documentation for `server_uri` parameter in ldap modules describes how to use multiple URIs.
Fixes #1659 
plugins/doc_fragments/ldap.py
=> ldap: added documentation as requested

changelogs/fragments/4380-sudoers-runas-parameter.yml, plugins/modules/system/sudoers.py, tests/integration/targets/sudoers/tasks/main.yml
Adds `runas` parameter to the sudoers module. 
Also allows for clearer and more consistent sudo rule format.
Fixes https://github.com/ansible-collections/community.general/issues/4379
Adds `runas` parameter to the sudoers module. 
There are two parts to this. 
1. Add the `runas` parameter to allow commands to be run as a user other than root. 
- NOTE: This should also allow for specifying **any** string supported by sudoers  as specified in the `Runas_Spec` section of the sudoers manpage. For example `runas: ALL` to allow running as any user.
To specify a rule to allow alice to run a command as the user bob:
```
- name: Allow alice to run a command as bob
community.general.sudoers:
name: my-sudo-rule
state: present
user: alice
commands: /usr/local/bin/command
runas: …
```
=> feat: sudoers module supports runas parameter with default of root

changelogs/fragments/4393-keycloak_client_rolemapping_docs.yml, plugins/modules/identity/keycloak/keycloak_client_rolemapping.py
Fixed typo in `keycloak_client_rolemapping` examples.
The examples for `keycloak_client_rolemapping` uses a plural `keycloak_client_rolemappings`, instead of the actual name of the module which is singular.
Fixes #4392 
keycloak_client_rolemapping
=> Fixed typo in keycloak_client_rolemapping examples

changelogs/fragments/4378-proxmox-inventory-tags.yml, plugins/inventory/proxmox.py
In some cases the Proxmox API returns a tags string that consists in a single space (typically after trying to clear tags using `qm set <vmid> --tags ""`). The Proxmox inventory plugin parsed that into a single, empty tag. This PR fixes that problem.
Proxmox inventory plugin
* Strip the initial string then check whether it actually contains something before extracting it to a list of tags.
* Do not call `_to_safe` on the concatenation of a known safe string and a string that was already made safe.
* Output before changes
```
"proxmox_tags": " ",
"proxmox_tags_parsed": [          
""
],
```
* Output after changes
```paste below
"proxmox_tags": " ",
```
=> Proxmox inventory plugin - Fix tags parsing

changelogs/fragments/4385-keycloak-client-default-optional-scopes.yml, plugins/modules/identity/keycloak/keycloak_client.py
Add `default_client_scopes` and `optional_client_scopes` parameters to `keycloak_client`. Partially resolves #2763.
This PR adds the ability to set default and optional client scopes for a Keycloak client. This is useful for openid-connect clients that have requirements for specific scopes/claims.
Before:
```
failed: [localhost] ..."msg": "Unsupported parameters for (community.general.keycloak_client) module: default_client_scopes..."...
```
After:
```
ok: [localhost]
```
=> keycloak_client: add default_client_scopes and optional_client_scopes

changelogs/fragments/4382-keycloak-add-missing-validate_certs-parameters.yml, plugins/module_utils/identity/keycloak/keycloak.py
As stated in the [documentation](https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_authentication_module.html#parameter-validate_certs), the `validate_certs` parameter can be
used to verify (or not) the TLS certificates. But, for some modules (at
least for the `keycloak_authentication` module), this parameter is not
used with the `open_url` function.
Fixes #4391.
before:
```paste below
TASK [keycloak : create custom authentication flow] *******************************************************************************************************************************************************************************************
fatal: [********]: FAILED! => {"changed": false, "msg": "Unable get authentication flow …
```
=> keycloak: add missing `validate_certs` parameters for `open_url` calls

changelogs/fragments/4417-ipa_service-add-skip_host_check.yml, plugins/modules/identity/ipa/ipa_service.py
The ipa_service module missing `skip_host_check` option to force service to be created even when host object does not exist to manage it. This PR adds new boolen `skip_host_check` option, which will handle this screnario.
Fixes #4416
ipa_service
n/a
=> ipa_service: Add `skip_host_check` option

tests/integration/targets/dnf_versionlock/tasks/lock_updates.yml, tests/integration/targets/monit/tasks/check_state.yml, tests/integration/targets/monit/tasks/main.yml, tests/integration/targets/pkgng/tasks/create-outofdate-pkg.yml, tests/integration/targets/setup_cron/tasks/main.yml, tests/integration/targets/setup_postgresql_db/tasks/main.yml
See https://github.com/ansible/ansible/pull/77411.
CI
=> CI: Remove 'warn:' that's removed in ansible-core 2.14

tests/integration/targets/cronvar/tasks/main.yml
Ensure `/etc/cron.d` directory is created before running tests. 
Fixes #4258 
tests/integration/targets/cronvar/tasks/main.yml
=> cronvar: ensure creation of /etc/cron.d in test

changelogs/fragments/4421-zypper_package_version_handling_fix, changelogs/fragments/4421-zypper_package_version_handling_fix.yml, plugins/modules/packaging/os/zypper.py
zypper.py was doing nothing on state=present, when ALL requestet/checked packages had a specific version stated. This was caused by get_installed_state() being called with an empty package list, which in this case returns information about all ALL installed packages. This lead to an exessive filter list prerun_state, essentially removing all packages that are installed in ANY version on the target system from the request list.
I added an empty check to prevent get_installed_state() being called with an empty package list.
Fixes #https://github.com/ansible-collections/community.general/issues/4371
zypper
The following task ALWAYS reported [ok] if ANY version of _a-very-important-package_ was already installed on the target system.
```yaml (paste below)
- name: Install …
```
=> Bugfix: zypper issue with specified package versions

changelogs/fragments/4429-keycloak-client-add-always-display-in-console.yml, plugins/modules/identity/keycloak/keycloak_client.py
The keycloak client module missing `always_display_in_console` which is keycloak client alias `alwaysDisplayInConsole`. It is simple boolean value. This PR adds new boolean value `always_display_in_console`.
Fixes: [#4390](https://github.com/ansible-collections/community.general/issues/4390)
- keycloak_client
n/a
=> Keycloak client, Add always_display_in_console option

changelogs/fragments/4422-warn-user-if-incorrect-SDK-version-is-installed.yaml, plugins/lookup/dsv.py
This raises an error if the wrong `python-dsv-sdk` version is installed. This lookup plugin currently only supports v0.0.1 of the SDK. This is a temporary fix until full support with the latest SDK version can be developed.
(Re-submitted with clean git history)
dsv lookup plugin
Before the fix, the error presented to the user:
```
Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'community.general.dsv'. Error was a <class 'TypeError'>, original message: __init__() got an unexpected keyword argument 'tenant'"}
```
After:
```
Error was a <class 'ansible.errors.AnsibleError'>, original message: python-dsv-sdk==0.0.1 must be installed to use this plugin"}
```
=> Bug fix: Warns user if incorrect SDK version is installed

plugins/modules/system/sudoers.py
The sudoers module has a documentation bug where the examples show ANY as what should be used to allow running of any command.
The correct is ALL.
Fix the example and add ALL into the docs for commands:
sudoers.py
Took sudoer module into use, and noted that using ANY does not actually work. Checking the man page for sudoers, it should be ALL.
=> Fix documentation for sudoers module

tests/integration/targets/discord/README.md, tests/integration/targets/discord/aliases, tests/integration/targets/discord/defaults/main.yml, tests/integration/targets/discord/tasks/main.yml
Add discord integration tests
To run the tests it is necessary to created a discord server and a webhook integration.  
These tests can be executed locally with an existing discord server. 
discord
```paste below
ansible-test integration -v --color yes discord --allow-unsupported
```
=> Add discord integration tests

changelogs/fragments/4466-proxmox-ansible_host-deprecation.yml, plugins/inventory/proxmox.py
See https://github.com/ansible-collections/community.general/pull/4432#discussion_r843187850.
CC @ralgar @ilijamt 
proxmox inventory plugin
=> proxmox inventory plugin: deprecate `want_proxmox_nodes_ansible_host` option's default value

changelogs/fragments/4438-fix-error-message.yaml, plugins/modules/packaging/os/xbps.py
The previous error message was not giving the full or even correct information to the user.
community.general.xbps
=> modules/xbps: fix error message

changelogs/fragments/4084-add-redfish-system-indicator-led.yml, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/redfish/redfish_command.py
Adds support for IndicatorLED commands in the Systems category. Introduces `IndicatorLedOn`, `IndicatorLedOff`, and `IndicatorLedBlink` to be consistent with functionality in the chassis view.
Fix #4084
New command example with results. Largely leveraged existing IndicatorLED code for the chassis.
```
tasks:
- name: Turn system LED on
redfish_command:
command: IndicatorLedOn
```
```
PLAY [Set Indicator LED] ************************************************************************************************
TASK [Turn system LED on] ***********************************************************************************************
changed: …
```
=> Redfish: Added IndicatorLED commands to the Systems category

changelogs/fragments/4465-btrfs-resize.yml, plugins/modules/system/filesystem.py, tests/integration/targets/filesystem/defaults/main.yml
Implement btrfs resize support
Fixes #4083 
filesystem
I tested this locally, to make sure it works. The comment on the other filesystems made me believe, that I cannot test this with the CI, since it requires the filesystem to be mounted. Is that right?
=> Implement btrfs resize support

changelogs/fragments/4459-only-get-monitor-if-it-is-not-null-api-response.yaml, plugins/modules/net_tools/dnsmadeeasy.py
dnsmadeeasy module, fails if "monitor" key is null in the api response, this change adds a check
net_tools/dnsmadeeasy
it adds a check for "monitor" value in api response partially fixes #3620, delete should work, updates are not perfect
=> dnsmadeeasy: only get monitor if it is not null api response

changelogs/fragments/4455-terraform-provider-upgrade.yml, plugins/modules/cloud/misc/terraform.py, tests/integration/targets/terraform/.gitignore, tests/integration/targets/terraform/aliases, tests/integration/targets/terraform/meta/main.yml, tests/integration/targets/terraform/tasks/main.yml, tests/integration/targets/terraform/tasks/test_provider_upgrade.yml, tests/integration/targets/terraform/templates/provider_test/main.tf.j2, tests/integration/targets/terraform/vars/main.yml
This PR adds a new `provider_upgrade` option to the Terraform module. This is needed, so that `terraform init` can pull new provider versions when the version pinned within an existing Terraform project changes. 
This fixes #4333 
I have included a basic integration test to test this behavior. Simply set `terraform_provider_upgrade: no` in the vars to see the previous failure behavior.
Changing provider constraints is a common usage scenario in Terraform. This prevents the user from having to completely blow away their terraform project directories every time the constraints are changed.
=> Terraform init -upgrade flag

changelogs/fragments/4491-specify_all_in_list_calls.yaml, plugins/modules/source_control/gitlab/gitlab_group.py, plugins/modules/source_control/gitlab/gitlab_group_members.py, plugins/modules/source_control/gitlab/gitlab_hook.py, plugins/modules/source_control/gitlab/gitlab_project.py, plugins/modules/source_control/gitlab/gitlab_project_members.py, plugins/modules/source_control/gitlab/gitlab_user.py
Use `all=True` in most `list()` calls
* Bugfix Pull Request
If `all=True` is not set then by default only 20 records will be
returned when calling `list()`. Use `all=True` so that all records
will be returned.
For the `list()` use where do not desire to retrieve all entries then
use`all=False` to show explicityly that we don't want to get all of
the entries.
Fixes #3729, fixes #4460
=> gitlab: Use `all=True` in most `list()` calls

changelogs/fragments/4464-pacman-fix-local-remove.yaml, plugins/modules/packaging/os/pacman.py, tests/integration/targets/pacman/aliases, tests/integration/targets/pacman/tasks/locally_installed_package.yml, tests/integration/targets/pacman/tasks/main.yml
Without this, using `absent` state for a locally installed package (for example from AUR, or from a package that was dropped from repositories) would return that package is already removed, despite remaining installed
pacman
=> pacman: Fix removing locally installed packages

plugins/modules/source_control/gitlab/gitlab_user.py
See https://github.com/ansible-collections/community.general/issues/1892#issuecomment-1097818144
gitlab_user
=> gitlab_user: remove no longer true statement from documentation

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/pkgng/aliases
Looks like FreeBSD 12.2 and 12.0 packages were removed from most mirrors, which causes tests to fail. Let's drop them from testing (at least temporarily, maybe even permanently).
Fixes #4492.
CI
=> CI: remove FreeBSD 12.0 and 12.2, re-enable pkgng tests

plugins/modules/packaging/language/gem.py
Next step will be to actually deprecate this in 5.0.0.
gem
=> gem: bump version numbers for deprecation and removal since we didn't deprecate this in 4.0.0

changelogs/fragments/4492-proxmox_kvm_fix_vm_without_name.yaml, plugins/modules/cloud/misc/proxmox_kvm.py
Handle a case when proxmox didn't return the VM name, which is generally wrong behavior on proxmox side, but can happen and we shouldn't fail.
proxmox_kvm
I was running a task:
```
- name: Get VM state
community.general.proxmox_kvm:
api_host: '{{ proxmox_conf.api_host }}'
api_user: '{{ proxmox_conf.api_user }}'
api_token_id: '{{ proxmox_conf.api_token_id }}'
api_token_secret: '{{ proxmox_conf.api_token_secret }}'
proxmox_default_behavior: compatibility
state: current
vmid: '{{ item.vmid }}'
register: vmstate
with_items: '{{ clone.results }}'
loop_control:
pause: 1
```
and randomly (a frequency is 1/20, but maybe it depends on the API calls load on the backend proxmox) I get the failure like:
```
TASK [Get VM state] …
```
=> Correctly handle exception when no VM name returned by proxmox

changelogs/fragments/4530-fix-unauthorized-pritunl-request.yaml, plugins/module_utils/net_tools/pritunl/api.py
According to pritunl documentation we don't need "data" in auth_string, without data, requests work good.
Fixes: #4527 
plugin: pritunl
=> [pritunl] removed unnecessary data from auth string

.github/BOTMETA.yml
This not being the case resulted in @Lowess not being pinged by the bot in #4530.
BOTMETA
=> Add Lowess as maintainer of pritunl module utils

changelogs/fragments/4506-sudo-in-nmap-inv-plugin.yaml, plugins/inventory/nmap.py
nmap executable works well when it is issued by a privileged user, because unprivileged users lacks of network raw socket rights.
As inventory plugin, to proper use it, you have to launch `ansible-inventory` from root or  `sudo ansible-inventory nmap_scan.yaml`, that in general is not a good idea.
So I have added a boolean sudo option that if set to Yes, it executes a "sudo nmap", so it will need an unprivileged user just with sudo power on nmap command 
i.e.
```
plugin: nmap
sudo: yes          # indicates that you are running it from an unprivileged user with sudo rights on nmap 
address: 192.168.0.0/24
exclude: 192.168.0.1, server2.example.com
ports: false
strict: false
```
general/plugins/inventory/nmap.py
=> nmap inventory plugin: Add sudo nmap

changelogs/fragments/4320-nmcli-hairpin.yml, plugins/modules/net_tools/nmcli.py
Change default hairpin mode for a bridge.
Plain nmcli/bridge tools defaults to no, but for some reason ansible
defaults to yes.
nmcli
=> nmcli: Change hairpin default mode

changelogs/fragments/4526-keycloak-realm-types.yaml, plugins/modules/identity/keycloak/keycloak_realm.py
Fix the type of parameters (`defaultDefaultClientScopes` and `defaultOptionalClientScopes`), according to https://www.keycloak.org/docs-api/17.0/rest-api/index.html#_realmrepresentation
community.general.keycloak_realm
Catch bug in Keycloak 15 and 17, with dictionary in defaultDefaultClientScopes/defaultOptionalClientScopes commands failed, because expected `<string> array`
=> Fix keycloak realm parameters types

changelogs/fragments/4479-add-project-support-for-lxd_container-and-lxd_profile.yml, plugins/modules/cloud/lxd/lxd_container.py, plugins/modules/cloud/lxd/lxd_profile.py
This PR add [lxd project](https://linuxcontainers.org/lxd/docs/master/projects/) support to 'lxd_container' and 'lxd_profile' module
A new module parameter 'project' is added, if the parameter is set module will perform operations on the selected project.
This is related to:
* #4475 
* lxd_container
* lxd_profile
This change is backward compatible, if project parameter is not set,  query parameter will not be added.
Tested on Ubuntu 20.04 with LXD 4.24 including:
* instance without project
* instance with project
* profile without project
* profile with project
=> Add project support for lxd_container and lxd_profile module

changelogs/fragments/4540-proxmox-inventory-token-auth.yml, plugins/inventory/proxmox.py
Adds api token authentication as an alternative to password auth to the proxmox inventory plugin.
proxmox
I'm unsure what to set version_added to for the new environment variables; also how to correctly raise an error if neither password nor token_id + token_secret are specified (see Line 595)
=> Proxmox inventory: implement API token auth

changelogs/fragments/4377-allow-proxmox-snapshot-restoring.yml, plugins/modules/cloud/misc/proxmox_snap.py, tests/unit/plugins/modules/cloud/misc/test_proxmox_snap.py
SUMMARY
Allows the restoration of a proxmox snapshot
ISSUE TYPE
COMPONENT NAME
This Change allows restoring a snapshot in Proxmox
This is the result of [https://github.com/ansible-collections/community.general/pull/4375](https://github.com/ansible-collections/community.general/pull/4375)
I did not mark `snapname` as required, as it has a default value and the behaviour didn't change. Or should i still mark it as required?
=> Allow Proxmox Snapshot Restoring

changelogs/fragments/4555-proxmox-lxc-key.yml, plugins/inventory/proxmox.py
When configuring containers in the `/etc/pve/lxc/` file, the API
adds a 'lxc' key that caused the plugin to crash as it tried to
split a list on ','.
This commit introduces logic to convert the list of lists in the
returned data to a dict as with the other keys.
```
'lxc': [['lxc.apparmor.profile', 'unconfined'],
['lxc.cgroup.devices.allow', 'a']]
```
becomes
```
"proxmox_lxc": {
"apparmor.profile": "unconfined",
"cap.drop": "",
"cgroup.devices.allow": "a"
}
```
proxmox inventory plugin
```bash
echo lxc.apparmor.profile: unconfined >> "/etc/pve/lxc/CONTAINERID.conf"
```
Caused the module to crash and return incomplete inventories.
Should also fix: #4472
=> Parse lxc key from api data for lxc containers

changelogs/fragments/4517-gem-deprecate-norc.yml, plugins/modules/packaging/language/gem.py
~~Rebase once #4515 is merged.~~ Actually deprecates the `norc` default in c.g 5.0.0.
gem
=> [5.0.0] gem - deprecate `norc` default

.azure-pipelines/azure-pipelines.yml
~~Contains #4548, needs to be rebased once that is merged.~~
Right now, some CI groups are skipped for some Ansible / remote / docker combinations to save CI cycles. Since #4548 reduces the number of CI runs, let's undo this so that every CI group is covered by the same targets.
CI
=> Improve CI coverage

changelogs/fragments/4580-vmadm-deprecate-param-debug.yaml, plugins/modules/cloud/smartos/vmadm.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.9.txt
Parameter `debug` seems to be not used anywhere. Deprecating.
=> vmadm: deprecating unused parameter debug

plugins/modules/remote_management/hpilo/hpilo_boot.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.9.txt
Added missing types to documentation.
plugins/modules/remote_management/hpilo/hpilo_boot.py
=> hpilo_boot: added missing types in documentation

plugins/modules/remote_management/hpilo/hpilo_info.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.9.txt
Added missing types to documentation.
plugins/modules/remote_management/hpilo/hpilo_info.py
=> hpilo_info: added missing types in documentation

plugins/modules/remote_management/hpilo/hponcfg.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.9.txt
Added missing types to the documentation.
plugins/modules/remote_management/hpilo/hponcfg.py
=> hponcfg: added missing types in documentation

changelogs/fragments/4612-time_filter_zero.yml, plugins/filter/time.py, tests/integration/targets/filter_time/tasks/main.yml
time_filter should not fail for 0 even without a unit and return 0
time_filter
```paste below
```
=> time_filter: allow 0 to return 0

changelogs/fragments/4595-fix-VirtualMediaInsert-iLO4.yml, plugins/module_utils/redfish_utils.py
This resolves #4595 on my systems that have an HPE iLO 4.
~~I obviously cannot test this on all of the hardware in the world that implements Redfish. Hopefully, servers that require the `Inserted` field for VirtualMediaInsert do not claim to implement a spec where that field is read-only.~~
I have reworked this so the code will only target systems that have an HPE iLO 4.
```paste below
```
=> redfish_command: VirtualMediaInsert does not work with HPE iLO4

changelogs/fragments/4618-dig-dlv.yml, plugins/lookup/dig.py
To be merged for 5.0.0, so we can remove it (via #4613) in 6.0.0.
CC @jpmens
dig lookup plugin
=> dig lookup: deprecate DLV record type

changelogs/fragments/4623-opentelemetry_bug_fix_include_tasks.yml, plugins/callback/opentelemetry.py, tests/unit/plugins/callback/test_opentelemetry.py
Fix the `include_tasks` when accessing the `_task_fields` object. Otherwise:
```yaml
---
- name: MyPlabook
tasks:
- name: Call foo task
include_tasks: foo.yml
```
Then
```bash
OTEL_EXPORTER_OTLP_ENDPOINT=0.0.0.0:4317 \
OTEL_EXPORTER_OTLP_INSECURE=true \
ansible-playbook -i hosts include_tasks.yml
```
produced:
```
PLAY [MyPlabook] *************************************************************************************************************************************************
TASK [Gathering Facts] *******************************************************************************************************************************************
[WARNING]: Platform darwin on host localhost is using the …
```
=> [opentelemetry][callback] fix warning when using the include_tasks

changelogs/fragments/4590-consul-fix-service-checks.yaml, plugins/modules/clustering/consul/consul.py
In the class `ConsulService`, the field `checks` was being shadowed by a method `checks()`.
plugins/modules/clustering/consul/consul.py
=> consul: fixed bug in ConsulService when storing checks

changelogs/fragments/4624-opentelemetry_bug_fix_hardcoded_value.yml, plugins/callback/opentelemetry.py
Fix the value for the `ansible_task_message` attribute that was always set to `failed`
```yaml
---
- name: Echo
tasks:
- name: create the local src directory
file:
path: /tmp/local/src
state: directory
```
Then
```bash
OTEL_EXPORTER_OTLP_ENDPOINT=0.0.0.0:4317 \
OTEL_EXPORTER_OTLP_INSECURE=true \
ansible-playbook -i hosts test.yml
```
produced:
```
PLAY [Echo] ******************************************************************************************************************************************************
TASK [Gathering Facts] *******************************************************************************************************************************************
[WARNING]: Platform darwin on …
```
=> [opentelemetry][callback] fix hardcoded value for ansible_task_message

changelogs/fragments/4621-terraform-py2-compat.yml, plugins/modules/cloud/misc/terraform.py
Changes list.copy()  with list[:] for py2 compatibility.
Fixes #4531
terraform
See #4531
=> change list.copy() with list[:] for py2 compat in terraform module

changelogs/fragments/4600-mh-delegate.yaml, plugins/module_utils/mh/base.py, plugins/module_utils/mh/module_helper.py
The `ModuleHelperBase` class now delegates unknown attributes to the `AnsibleModule` instance it contains.
The purpose of this change is to provide a way for module developers to avoid using `self.module` for every little thing. 
plugins/module_utils/mh/module_helper.py
=> ModuleHelper module utils: delegates unknown attributes to AnsibleModule

changelogs/fragments/4065-onepassword-config.yml, plugins/lookup/onepassword.py, plugins/module_utils/onepassword.py, plugins/modules/identity/onepassword_info.py
Fixes #4065.
There are three [configuration file locations](https://developer.1password.com/docs/cli/about-biometric-unlock#remove-old-account-information). Use the first found valid config.
`plugins/lookup/onepassword.py`
`plugins/module_utils/onepassword.py`
`plugins/modules/identity/onepassword_info.py`
This plugin is currently broken since the 1Password v2 CLI was released. More work is needed to address that issue, but this is a first step.
=> onepassword - Get first found config file

changelogs/fragments/4535-pritunl-add-mac_addresses-parameter.yml, plugins/modules/net_tools/pritunl/pritunl_user.py
Pritunl VPN supports to limit user by his MAC addresses, added this parameter to the module
pritunl
```paste below
```
=> [pritunl] add mac_addresses parameter

changelogs/fragments/4578-ipa_dnsrecord-add_multiple_record_support.yml, plugins/modules/identity/ipa/ipa_dnsrecord.py
Add the possibility to add multiple values under the same record
fixes #4553 
ipa_dnsrecord
**Should i rename `record_value` to `record_values`?**
current i keep the state, so that it is not an breaking change - but i believe `record_values` would be more correct.
```paste below
```
=> feat(ipa_dnsrecord): add multiple record support

changelogs/fragments/4601-ansible-galaxy-install-deprecate-ansible29-and-210.yaml, plugins/modules/packaging/language/ansible_galaxy_install.py
Adding deprecation for no-longer supported ansible versions. Particularly in this context, `ansible-galaxy` changed quite a bit between those versions and the most recent ones, adding some complexity to the module.
=> ansible_galaxy_install: added deprecation for ansible 2.9 and ansible-base 2.10

.gitignore
This PR simply adds an exclusion for `.DS_Store` files to `.gitignore`. Those files are generated automatically by macOS for storing directory metadata, and end up polluting the repo's working dir.
.gitignore
`git status` before:
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
.DS_Store
tests/.DS_Store
tests/integration/.DS_Store
tests/integration/targets/.DS_Store
tests/integration/targets/alternatives/.DS_Store
tests/integration/targets/ansible_galaxy_install/.DS_Store
tests/integration/targets/archive/.DS_Store
tests/integration/targets/cargo/.DS_Store
[...]
```
`git status` after PR:
```
On branch feature/gitignore_macos
nothing to commit, working tree clean
```
Also fixes the invalid gitignore.io definition for jupyter …
=> .gitignore exclude of .DS_Store files created by macOS

changelogs/fragments/4660-mh-added-do-raise.yaml, plugins/module_utils/mh/base.py, plugins/module_utils/mh/mixins/cmd.py
Added a method `do_raise()` to MH base class, so that module developers won't have to import ModuleHelperException unless they want to subclass it.
=> ModuleHelper: added a do_raise() method to MH base class

PSF-license.txt, changelogs/fragments/psf-license.yml, plugins/module_utils/_version.py
plugins/module_utils/_version.py mentions PSF-license.txt, which doesn't exist yet.
licenses
=> [stable-4] Add PSF-license.txt file

changelogs/fragments/4651-zypper-checkmode-fix.yaml, plugins/modules/packaging/os/zypper.py
At the moment if zypper updates itself the parse_zypper_xml function
calls itself with packages not None, but in check_mode zypper still
needs to update itself again -> rc = 103 and firstrun is undefined
zypper
=> Set firstrun to avoid use before definition

changelogs/fragments/4662-yarn-emoji.yml, plugins/modules/packaging/language/yarn.py
Yarn 2 and above no longer support the `--no-emoji` flag and have stricter checks on unrecognized command-line options, causing community.general.yarn's use of `--no-emoji` to throw errors on those versions.
Yarn 1.x doesn't properly support the `--no-emoji` flag, so community.general.yarn's use of `--no-emoji` has no effect there. Yarn 1.x attempts to only use emoji for interactive terminals of specific, known terminal types, so explicitly using `--no-emoji` should be unnecessary.
Fixes #4661, #4245
yarn
See discussion at #4245 and #4661.
* Yarn 1.x claims to support the `--no-emoji` flag; see https://github.com/yarnpkg/yarn/commit/10b82bb063c2e2feee669ddb9dfaf4126b74c7a7. However, this is apparently incorrect:
* Later discussions at …
=> Remove unsupported and unnecessary --no-emoji option

changelogs/fragments/4668-gitlab_hook-use-None-for-non-existent-attr.yml, plugins/modules/source_control/gitlab/gitlab_hook.py
there is a problem when webhook token is defined with ansible, because gitlab API doesn`t return 'token' attribute
gitlab_hook
```
- name: my/project crowdin webhook
become: no
local_action:
module: community.general.gitlab_hook
api_url: "{{ gitlab__api_url }}"
api_token: "{{ vault.gitlab__api_token }}"
state: present
project: "my/project"
hook_url: "https://crowdin.com/hooks/gitlab_server"
push_events: yes
hook_validate_certs: yes
token: "{{ vault.gitlab__hook.crowdin_token }}"
```
error message
```
File \"<stdin>\", line 102, in <module>
File \"<stdin>\", line 94, in _ansiballz_main
File \"<stdin>\", line 40, in invoke_module
File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ …
```
=> gitlab_hook: use None for non-existent attr in gitlab API response

changelogs/fragments/4668-gitlab_hook-use-None-for-non-existent-attr.yml, plugins/modules/source_control/gitlab/gitlab_hook.py
Backport of #4668 to stable-4.
gitlab_hook
=> [stable-4] gitlab_hook: use None for non-existent attr in gitlab API response

changelogs/fragments/4682-compatibility-virtualmedia-resource-location.yaml, plugins/modules/remote_management/lenovoxcc/xcc_redfish_command.py, tests/unit/plugins/modules/remote_management/lenovoxcc/test_xcc_redfish_command.py
Update xcc_redfish_command module for compatibility due to redfish spec changes the virtualMedia resource location from Manager to System.
xcc_redfish_command
=> Update lenovoxcc module for compatibility with the virtualMedia resource location from Manager to System

tests/sanity/ignore-2.14.txt
Ignoring Python 3.11 import errors for two modules that import the deprecated stdlib library `crypt`.
homectl
udm_user
=> Ignore import sanity errors until the modules can be fixed

tests/integration/targets/consul/meta/main.yml, tests/integration/targets/consul/tasks/main.yml, tests/utils/constraints.txt
Add constraint so that systems with outdated pip2s don't try to install a bad version.
CI
=> certifi dropped Python 2 support

changelogs/fragments/4674-use-mh-raise.yaml, plugins/modules/packaging/language/cpanm.py, plugins/modules/packaging/language/pipx.py, plugins/modules/packaging/os/snap.py, plugins/modules/system/mksysb.py, plugins/modules/system/xfconf.py
Replaced raising exception with calling method do_raise() in MH.
Removed the importing of the exception class.
plugins/modules/packaging/language/cpanm.py
plugins/modules/system/mksysb.py
=> Multiple modules using ModuleHelper

changelogs/fragments/4712-consul-bugfix.yaml, plugins/modules/clustering/consul/consul.py
Applied the fix from the issue.
Fixes #4680 .
plugins/modules/clustering/consul/consul.py
=> consul: applied bugfix from issue

plugins/lookup/dig.py
The DLV registry was decomissioned in 2017 (https://www.isc.org/blogs/dlv/) so it's high time we remove support for DLV records.
dig
=> dig: remove support for the DLV record as the registry was decomissioned

plugins/modules/remote_management/redfish/redfish_command.py
Two simple documentation block fixes: fix typo "od" to "of" and language "the" to "to".
```paste below
```
=> redfish_command: documentation typo and language

changelogs/fragments/4726-zfs.yml, plugins/modules/storage/zfs/zfs.py
=> Fix quoting bug in zfs

plugins/modules/remote_management/redfish/ilo_redfish_config.py
Document example for setting static NTP server using `ilo_redfish_config`.
ilo_redffish_config
Tested on iLO 5 (HP Gen 10).
Command checked from iLO5 REST API reference:
https://hewlettpackard.github.io/ilo-rest-api-docs/ilo5/#configuring-network-time-protocol-ntp
=> DOC: Document setting of NTP server in examples of ilo_redfish_config

changelogs/fragments/4733-redis-fail.yml, plugins/module_utils/redis.py
Currently causes this error:
```
TypeError: AnsibleModule.fail_json() missing 1 required positional argument: 'msg'
gitlab | FAILED! => {
"discovered_interpreter_python": "/usr/bin/python3.10"
},
"module_stderr": "Shared connection to 10.0.3.100 closed.\r\n",
"module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1653579059.8318024-147674-84188943153768/AnsiballZ_redis.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1653579059.8318024-147674-84188943153768/AnsiballZ_redis.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1653579059.8318024-147674-84188943153768/AnsiballZ_redis.p …
```
=> fix invalid fail_json call

changelogs/fragments/4719-fix-keycloak-realm.yaml, plugins/modules/identity/keycloak/keycloak_realm.py
Fixes #4241  
Fixed attributes `default_roles` and `default_groups` to match [Keycloak API](https://www.keycloak.org/docs-api/18.0/javadocs/org/keycloak/representations/idm/RealmRepresentation.html)
keycloak_realm
Only checked and fixed `default_roles` and `default_groups`
=> keycloak_realm: fix default groups and roles (#4241)

plugins/modules/net_tools/nmcli.py
In documentation sometimes DNS was written in (incorrect) lower
case "dns" and sometimes in (correct) capital case "DNS". Use the
right capital case spelling in all parameter descriptions.
Also the example for `dns4` and `dns6` parameters looked like a
space-separated string while the parameter expects a list of
strings. Try to improve the example by changing the single
space-separated string to two individual code-strings.
This could probably be further improved to make it more clear
that the two IP addresses for DNS parameter should be a list of
strings and not a single space-separated string.
Or perhaps the examples in description of parameters `dns4` and
`dns6` should be dropped completely to avoid confusion.
There is already an example task "Add two IPv4 DNS server
addresses" that …
=> nmcli: use capital case "DNS" in documentation, improve examples

changelogs/fragments/4736-cmd-runner-skip-if-check.yml, plugins/module_utils/cmd_runner.py, tests/integration/targets/cmd_runner/library/cmd_echo.py, tests/integration/targets/cmd_runner/tasks/test_cmd_echo.yml, tests/integration/targets/cmd_runner/vars/main.yml
Added parameters `check_mode_skip` and `check_mode_return` to `CmdRunner.context()`, so that the command is not executed when `check_mode=True`.
=> cmd_runner: added flag check_mode_skip to context

changelogs/fragments/4752-ansible-galaxy-install-mh-updates.yml, plugins/modules/packaging/language/ansible_galaxy_install.py
Minor refactorings based on the latests updates in `ModuleHelper`.
=> ansible_galaxy_install: minor improvements based on MH updates

changelogs/fragments/4724-proxmox-qemu-extend.yaml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
Added support for missing statuses for QEMU
* prelaunch
* paused
proxmox.inventory
=> Proxmox Inventory: added new statuses for qemu

changelogs/fragments/4777-cmd-runner-deprecate-fmt.yaml, plugins/module_utils/cmd_runner.py, plugins/module_utils/gconftool2.py, tests/integration/targets/cmd_runner/library/cmd_echo.py
Deprecate `fmt` in favour of `cmd_runner_fmt` as the name of the object to be imported for formatting parameters.
plugins/module_utils/gconftool2.py
=> cmd_runner: deprecate fmt as the name for the format class

.github/BOTMETA.yml
I have not maintained either of these modules for many years nor do I have access to newrelic or flowdock anymore.
- newrelic_deployment
- flowdock
N/A
=> remove mcodd as maintainer for newrelic_deployment and flowdock modules

changelogs/fragments/4755-mhexception-improvement.yml, plugins/module_utils/mh/exceptions.py
Simplified the code for `ModuleHelperException`, and fixed missing use of  `to_native()`.
plugins/module_utils/mh/exceptions.py
=> ModuleHelperException module utils - improved exception initialization

changelogs/fragments/4740-puppet-feature.yaml, plugins/modules/system/puppet.py
Add the confdir option to the puppet plugin to configure a custom confdir location.
See [puppet documentation](https://puppet.com/docs/puppet/7/dirs_confdir.html#confdir-location)
system puppet
=> Add puppet confdir option

.github/BOTMETA.yml, changelogs/fragments/4776-xfconf-cmd-runner.yaml, plugins/module_utils/xfconf.py, plugins/modules/system/xfconf.py, plugins/modules/system/xfconf_info.py
Create a new `module_utils/xfconf.py`.
Changed `xfconf` and `xfconf_info` to use that runner instead of the features in `CmdStateModuleHelper`
plugins/module_utils/xfconf.py
plugins/modules/system/xfconf_info.py
=> xfconf module utils: providing a cmd_runner object

changelogs/fragments/4746-add-vpn-support-nmcli.yaml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Add support to `nmcli` module to manage L2TP and PPTP VPN connections.
It manages VPN connections of service types `L2TP` and `PPTP` on the host
=> add support to create L2TP and PPTP VPN connection

tests/integration/targets/zypper_repository/tasks/zypper_repository.yml
Fixes currently broken CI.
ansible-core devel bumped OpenSuSE to 15.4, which isn't properly released yet.
zypper_repository integration tests
=> CI: Disable repo URL test for OpenSuSE 15.4

changelogs/fragments/4816-proxmox-fix-extended-status.yaml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
This fixes an issue with LXC containers after #4723 was implemented. I completely missed this when reviewing it and the unit tests didn't cover it :-)
I'm not too sure however on how to update the unit tests in order to fix this (yet, but it's late, unless I come up with an idea earlier then someone else, I'll adjust the tests as well :-) )
proxmox inventory
Running the module without this task results in the errors below:
```paste below
[WARNING]:  * Failed to parse /opt/ansible/projects/element-networks/inventory/04_nc_proxmox.yml with
ansible_collections.community.general.plugins.inventory.proxmox plugin: 'qmpstatus'
File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 290, in parse_source
plugin.parse(self._inventory, self._loader, source, …
```
=> Added conditional to only collect qmpstatus on qemu VMs

changelogs/fragments/4814-sudoers-file-permissions.yml, plugins/modules/system/sudoers.py, tests/integration/targets/sudoers/tasks/main.yml
Related to #4794, this change allows files created by the sudoers module to be created with the correct permissions to pass validation by visudo.
Sudoers module
Ensures that files touched by the sudoers module have 0440 permissions as required by visudo to pass validation.
Files that already exist with other permissions (or created by the sudoers module before this update) will be updated to the correct file permissions.
=> Ensure managed sudoers config files have 0440 permissions

tests/unit/requirements.txt
Example: https://dev.azure.com/ansible/community.general/_build/results?buildId=45004&view=logs&j=602cf013-5dea-52b3-7f57-27e24552d081&t=03289533-9b66-55f1-fce2-72fef36c372f&l=525
I've seen this multiple times during the last months, so at least let's disable this for stable-3 so at least the old branch's CI status which has tests run only once per week won't waffle because of this.
CI
=> [stable-3] Disable opentelemetry unit tests since requirements have conflicts way too often

changelogs/fragments/4813-fix-nmcli-convert-list.yaml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Some parameters were changed to support lists e.g. ip4,ip6. These changes seem to cause the following error message if you only try to set specific parameters like zone or dns6.
> Error: Failed to modify connection 'ens192': ipv4.gateway: gateway cannot be set if there are no addresses configured\n
Fixes  #4373
nmcli
```
- name: Add zone
type: ethernet
conn_name: ens192
zone: external
state: present
```
> Error: Failed to modify connection 'ens192': ipv4.gateway: gateway cannot be set if there are no addresses configured\n
List parameters get converted to strings with the `list_to_string` function. If the parameter is `None`, it returns an empty string. As these options aren't None anymore, they get added as arguments to the `nmcli` command.
=> nmcli: do not convert undefined lists to empty strings

changelogs/fragments/4810-alternatives-bug.yml, plugins/modules/system/alternatives.py, tests/integration/targets/alternatives/tasks/test.yml, tests/integration/targets/alternatives/tasks/tests_set_priority.yml
If neigther the priority nor the subcommands where specified the module decided to update the priority with the default value anyway. ~~This resulted in the bug #4803 and #4804 when the subcommands have not been specified.~~
Do not set the priority if the default value if the priority is not set.
alternatives
```paste below
```
=> alternatives: Fix bug with priority default

changelogs/fragments/4809-redhat_subscription-unsubscribe.yaml, plugins/modules/packaging/os/redhat_subscription.py, tests/unit/plugins/modules/packaging/os/test_redhat_subscription.py
The `unsubscribe` command of `subscription-manager` was deprecated already in subscription-manager 1.11.3, shipped with RHEL 5.11. As it was removed in subscription-manager 1.29.x, unsubscribing from pools was thus broken.
The simple fix is to call the proper command, `remove`.
Fixes #4741.
The issue #4741 has proper instructions on how to reproduce this. In short, when trying to unregister from attached pools, or unsubscribe in general.
=> redhat_subscription: call 'remove' instead of 'unsubscribe'

changelogs/fragments/4836-alternatives.yml, plugins/modules/system/alternatives.py, tests/integration/targets/alternatives/tasks/main.yml, tests/integration/targets/alternatives/tasks/subcommands.yml, tests/integration/targets/alternatives/vars/Debian.yml, tests/integration/targets/alternatives/vars/Suse-42.3.yml, tests/integration/targets/alternatives/vars/default.yml
Fixes #4803, fixes #4804.
CC @jiuka
alternatives
=> Fix alternatives module

.azure-pipelines/scripts/aggregate-coverage.sh, .azure-pipelines/scripts/report-coverage.sh
Fixes code coverage for stable-4 runs (that still use Ansible 2.9).
CI
=> [stable-4] Skip Ansible 2.9 coverage reporting with new AZP container

changelogs/fragments/4791-cmd-runner-callable.yaml, plugins/module_utils/cmd_runner.py, plugins/modules/system/xfconf.py, tests/unit/plugins/module_utils/test_cmd_runner.py
Method `context()` renamed to `__call__()`, but retaining an alias from the old name to the new one, for compatibility.
That change will allow a more concise idiom when running the commands.
=> cmd_runner: add __call__ method to invoke context

changelogs/fragments/4852-sudoers-state-absent.yml, plugins/modules/system/sudoers.py, tests/integration/targets/sudoers/tasks/main.yml
This PR decouples the check for `state == absent` from the file existence check, so that `run` does not "fall through" into code paths intended for `state == present`.
fixes #4852
sudoers
Refer to #4852. Please ask if anything is unclear.
=> sudoers: fix handling of state: absent (#4852)

.github/BOTMETA.yml, meta/runtime.yml, plugins/modules/system/keyring.py, plugins/modules/system/keyring_info.py, tests/integration/targets/keyring/aliases, tests/integration/targets/keyring/tasks/main.yml, tests/integration/targets/keyring/vars/main.yml
The purpose of this PR is to enable setting and deleting credentials from the native OS keyring.
This PR resolves [issue 4171](https://github.com/ansible-collections/community.general/issues/4171)
keyring
keyring_info
Previously the community.general collection had a keyring lookup plugin. This was useful for very arbitrary lookups on the controller node. It quickly reaches it's limitations if you wanted to manage keyring credentials on other hosts.
This PR introduces two modules:
1. keyring
a. used to set and delete credentials from a keyring (local or remote host)
2. keyring_info
a. used to fetch a credential from a keyring (local or remote host)
b. replacement for the previous keyring lookup plugin
The below playbook can be used to install dependencies, and …
=> Add keyring and keyring_info modules

tests/integration/targets/iso_create/meta/main.yml, tests/integration/targets/iso_create/tasks/main.yml, tests/utils/constraints.txt
See https://github.com/clalancette/pycdlib/issues/95.
CI
=> Fix CI due to pycdlib dropping Python 2 support

tests/unit/requirements.txt
Regularly CI (unit tests) is breaking because Protobuf for Python that's required by opentelemetry:
```
01:16 ______ ERROR collecting tests/unit/plugins/callback/test_opentelemetry.py ______
01:16 tests/unit/plugins/callback/test_opentelemetry.py:12: in <module>
01:16     from ansible_collections.community.general.plugins.callback.opentelemetry import OpenTelemetrySource, TaskData, CallbackModule
01:16 <frozen importlib._bootstrap>:991: in _find_and_load
01:16     ???
01:16 <frozen importlib._bootstrap>:975: in _find_and_load_unlocked
01:16     ???
01:16 <frozen importlib._bootstrap>:671: in _load_unlocked
01:16     ???
01:16 /root/ansible/lib/ansible/utils/collection_loader/_collection_finder.py:434: in exec_module
01:16     exec(code_obj, module.__dict__)
01:16 …
```
=> Disable opentelemetry installation for unit tests

plugins/callback/log_plays.py, plugins/callback/selective.py, plugins/lookup/chef_databag.py
Some plugins docs are using backticks for formatting.
log_plays callback
selective callback
chef_databag lookup
=> Fix plugin docs

changelogs/fragments/4903-cmdrunner-bugfix.yaml, plugins/module_utils/cmd_runner.py
It exists a bug in CmdRunner where the wrong "command" variable is being used in order to get the binary path.
Before executing, it is ensured that the command is a list.
`self.command = _ensure_list(command)`
However, further in the code, `command[0]` is used instead of `self.command[0]`.
`self.command[0] = module.get_bin_path(command[0], opt_dirs=path_prefix, required=True)`
Because of this, if command is a string (p.e. xfconf-query), `get_bin_path` will look for "x" instead of "xfconf-query".
Right now, this is affecting the following components:
- plugins/module_utils/xfconf.py
- plugins/module_utils/gconftool2.py
=> Fix command variable usage in CmdRunner

tests/integration/targets/timezone/tasks/test.yml
It currently fails nightly CI on CentOS 8 Stream. `timedatectl` can be run, but prints `RTC time: n/a`, and then trying to set RTC time fails.
CI
=> Fix timezone test

changelogs/fragments/4901-fix-redfish-chassispower.yml, plugins/module_utils/redfish_utils.py
When multiple chassis are present, and one or more of those chassis do _not_
report power information, the GetChassisPower command will fail. To address
that, only report a failure if _all_ of the Chassis objects lack power
power reporting functionality.
Fixes #4901
redfish_info
Output from a system that has multiple chassis, but one chassis (the backplane) does _not_ report power information:
```
PLAY [all] **********************************************************************************************************************************************************************************
TASK [Gather initial BMC lan infomration] ************************************************************************************************************************************************* …
```
=> Fix GetChassisPower when multiple chassis are present

changelogs/fragments/4911-dsv-honor-tld-option.yml, plugins/lookup/dsv.py
Option defined to configure the top-level domain of the tenant was ignored.
lookup/dsv
```paste below
N/A
```
=> Do not ignore tld option in DSV lookup plugin

changelogs/fragments/4886-fix-lxd-inventory-hostname.yml, plugins/connection/lxd.py
Fixes #4886 
lxd connection plugin
`remote_addr` value was being set to literal string 'inventory_hostname' instead of value of `inventory_hostname` variable. Fix taken from ansible/ansible#77894
=> fix lxd connection plugin inventory_hostname

changelogs/fragments/4933-fix-rax-clb-nodes.yaml, plugins/modules/cloud/rackspace/rax_clb_nodes.py
Fix syntax in `rax_clb_nodes` that breaks in Python3
* Use syntax that works in both Python 2 and 3 when iterating through a
dict that's going to be mutated during iteration
* Fixes `dictionary changed size during iteration` error
* Fixes #4932
`community.general.rax_clb_nodes` defined here: https://github.com/ansible-collections/community.general/blob/main/plugins/modules/cloud/rackspace/rax_clb_nodes.py
Prior to this change, you are unable to run the `rax_clb_nodes` task against hosts that only have Python 3 installed.  You would get this error:
```console
RuntimeError: dictionary changed size during iteration
```
Now it works as expected under hosts with Python 2 or Python 3.
=> Fix code in `rax_clb_nodes` that breaks in Python3

changelogs/fragments/4916-opentelemetry-ini-options.yaml, plugins/callback/opentelemetry.py
this is especially useful for the `enable_from_environment` option, as
this allows to set a default for the whole project, instead of relying
on everyone setting the environment variable
opentelementry callback
```paste below
```
=> allow configuring opentelementry callback via config file

changelogs/fragments/4849-add-password-prompt-support-for-machinectl.yml, plugins/become/machinectl.py
This allows the use of machinectl without being root by using the polkit auth dialog. 
community.general.machinectl
Example polkit rule in comments look strange, but I found no other example on how to include a multiline code snippet.
=> added password prompt support for machinectl

.github/BOTMETA.yml, meta/runtime.yml, plugins/module_utils/wdc_redfish_utils.py, plugins/modules/remote_management/redfish/wdc_redfish_command.py, plugins/modules/remote_management/redfish/wdc_redfish_info.py, tests/unit/plugins/modules/remote_management/wdc/test_wdc_redfish_command.py, tests/unit/plugins/modules/remote_management/wdc/test_wdc_redfish_info.py
New Redfish command/info modules for WDC UltraStar Data102 storage controllers.  Currently supports operations related to firmware update.  More features will be implemented soon.
wdc_redfish_info, wdc_redfish_command
wdc_redfish_info provides:
- SimpleUpdateStatus (indicates the firmware update state for the controller)
wdc_redfish_command provides:
- UpdateAndActivate (this orchestrates the full firmware update process which is several steps)
- FWActivate (this performs a firmware activate, which is an OEM-specific Redfish command)
```paste below
```
=> Redfish modules for Western Digital UltraStar Data102 storage enclosures

changelogs/fragments/4955-fix-path-detection-for-gopass.yaml, plugins/lookup/passwordstore.py
As per https://github.com/gopasspw/gopass/blob/fc8c9a228618fa4a146a87c9027fa0434b0737fa/docs/features.md#initializing-a-password-store, gopass defaults to ~/.local/share/gopass/stores/root for its password store root location.
However, the user can also override this, and this will be stored in the gopass config file (https://github.com/gopasspw/gopass/blob/ed7451678c5e8138d5a8eaafa278d5065a9eb9fe/docs/config.md#configuration-options).
This patch ensures that the config setting in gopass is respected, falling back to the default gopass path. pass' behaviour remains unchanged.
passwordstore
I have to say I am unsure how to document this properly, especially given the weird way the `passwordstore` and `directory` settings on this module currently interact with each …
=> Fix path detection for gopass

changelogs/fragments/4945-fix-get_vm-int-parse-handling.yaml, plugins/module_utils/proxmox.py, plugins/modules/cloud/misc/proxmox.py, plugins/modules/cloud/misc/proxmox_kvm.py
When target vm is not exist and get vm by only target vm name, proxmox module raise int parse error.
This PR fix only pattern of vmid is None.
I did't implement other pattern because I guess vmid is only int or None.
Closes #4944 
proxmox
```paste below
none
```
=> proxmox module_utils: fix get_vm int parse handling

tests/integration/targets/monit/meta/main.yml, tests/integration/targets/monit/tasks/main.yml, tests/utils/constraints.txt
=> python-daemon 2.3.1 requires Python 3+

tests/integration/targets/yum_versionlock/aliases
They have been failing on CentOS 8 Stream for some days now, see for example https://dev.azure.com/ansible/community.general/_build/results?buildId=48811&view=logs&j=48a38357-c733-5270-bc9f-8b347073680c&t=f738d932-52a6-55f4-0339-9d2c3f71394b&l=7479
It seems that for some reason some packages exist multiple times (like `curl`, see the package facts) and the module only locks one of them, so the other one can still be upgraded. Someone who knows more about yum will have to debug this and determine whether this is a bug in the tests, a bug in the module, or both.
=> Temporarily disable the yum_versionlock tests

changelogs/fragments/4964-fix-keyring-info.yml, plugins/modules/system/keyring_info.py
The docs say this module works with the `keyring` library, but actually this line was clobbering any passphrase retrieved from that library, making it useless on any system without the alternate method (gnome-keyring).
After this change, it'll only use the alternate method if the first one didn't work, so the return value from the first one will actually get passed through.
keyring_info
Reproduction:
```yml
- name: Save a password to the keychain
community.general.keyring:
service: example-service
username: example-user
password: example-password
keyring_password: ""
- name: Read it back from the keychain
community.general.keyring_info:
service: example-service
username: example-user
keyring_password: ""
register: example_result
- debug:
msg: "{{ example_result }}" …
```
=> Fix keyring_info when using keyring library

changelogs/fragments/4973-introduce-dig-lookup-argument.yaml, plugins/lookup/dig.py
with default False for backwards compatibility.
Allows fail-fast behavior on lookup failures instead of returning strings and continuing.
I would like the dig lookup to offer the option to fail on lookup errors. Right now it just returns empty strings or something like 'NXDOMAIN' as string which is ugly because you notice quite late that something is wrong with your infrastructure because a dig lookup in some config template produced an unexpected result although your playbook run was clean.
dig lookup plugin
IMHO this should be the default, but for backwards compatibility I've disabled it.
=> Introduce dig lookup argument fail_on_error

changelogs/fragments/4975-xfconf-use-do-raise.yaml, plugins/modules/system/xfconf.py, plugins/modules/system/xfconf_info.py
Make both xfconf related modules use the `do_raise()` method of MH instead of defining custom exceptions.
plugins/modules/system/xfconf_info.py
=> xfconf and xfconf_info: use do_raise

changelogs/fragments/4812-expose-unredirected-headers.yml, plugins/modules/packaging/language/maven_artifact.py
Tries to fix #1171 
In some cases, when the initial request returns a redirect and we want to follow it to get the artifact, we might not want to include certain headers in the redirection request. Specially headers like
Authorization and Cookies.
Or perhaps the redirect server returns a 400 because it included some unexpected headers.
Fetch url already supports this feature, but it was being shadowed by maven_artifact. In here we just expose it, and give it a sensible default.
- New Feature
maven_artifact
Mostly related to Code Artifact. To reproduce the error (before this PR), just trying to download an artifact from code artifact would trigger a 400. That was because after the initial request, AWS responds with a S3 url, which we follow but include some extra headers (like …
=> Expose unredirected_headers on maven_artifact

changelogs/fragments/4976-apk-add-support-for-a-custom-world-file.yaml, plugins/modules/packaging/os/apk.py
This adds a new `world` parameter to the apk packaging module. This helps remove the hardcoded `/etc/apk/world` and therefore allows usage on more complex/non-standard linux systems with the `apk` package manager.
Apk custom world parameter
N/A
=> Apk: add support for a custom world file

changelogs/fragments/4968-pacman-url-integrity-test.yaml, tests/integration/targets/pacman/tasks/package_urls.yml
This PR improves the integrity test for url packages.
It requests the url from pacman and hosts the package itself, which produces additional output. Furthermore this PR adds some tests for cases when the package url is already cached. In the other cases, the cached package must be deleted before the next test runs.
pacman
=> Pacman: Improve url integrity test

changelogs/fragments/4999-xfconf-bool.yml, plugins/module_utils/xfconf.py
=> xfconf: fix setting of boolean values

tests/unit/plugins/modules/system/test_xfconf.py
Added additional test to prevent #4999 from happening again.
=> xfconf: add unit test for bool value

changelogs/fragments/4778-gconftool2-deprecate-state-get.yaml, plugins/modules/system/gconftool2.py
Deprecates `state=get` in favour of using module `gconftool2_info`.
plugins/modules/system/gconftool2.py
=> gconftool2: deprecate state get

changelogs/fragments/5027-fix-returnall-for-gopass.yaml, plugins/lookup/passwordstore.py, tests/integration/targets/lookup_passwordstore/tasks/tests.yml
Gopass was always given the --password flag, despite there being no need for this. Therefore, it only ever returned the first line, breaking returnall.
passwordstore
Create a multi-line password in gopass
```
echo -e "Multi\\nline\\ntest" | gopass insert test
```
Run the following playbook:
```
---
tasks:
- name: Print only first line
ansible.builtin.debug:
msg: "{{ lookup('community.general.passwordstore', 'test', backend='gopass') }}"
- name: Print all lines
ansible.builtin.debug:
msg: "{{ lookup('community.general.passwordstore', 'test returnall=true', backend='gopass') }}"
```
Before patch:
```
❯ ansible-playbook playbook.yml 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match …
```
=> Fix returnall for gopass

changelogs/fragments/5035-mh-base-verbosity.yaml, plugins/module_utils/mh/base.py
Add a `verbosity` property to `ModuleHelper` base class, wrapping the `AnsibleModule._verbosity` one.
=> mh base: add verbosity() property

changelogs/fragments/4996-consul-session-ttl.yml, plugins/modules/clustering/consul/consul_session.py, tests/integration/targets/consul/tasks/consul_session.yml
This pull request add the possibility to set a TTL when creating a session.
consul_session
- Consul  API: https://www.consul.io/api-docs/session#ttl
- Python consul lib already support this parameter: https://python-consul.readthedocs.io/en/latest/#consul-session
Without the PR it is not possible to set a TTL on a session.
Here is a test playbook
```yaml
- name: test module
tasks:
- name: Register basic session with consul
community.general.consul_session:
name: session-with-ttl
- name: Retrieve active sessions
community.general.consul_session:
state: list
```
The output of the run is the following where we can see the `TTL` key is an empty string where we cannot pass anything.
```
❯ ansible-playbook test.yaml
PLAY [test module] …
```
=> consul: add support for session TTL

changelogs/fragments/4956-pacman-install-reason.yaml, plugins/modules/packaging/os/pacman.py, tests/integration/targets/pacman/tasks/main.yml, tests/integration/targets/pacman/tasks/reason.yml, tests/unit/plugins/modules/packaging/os/test_pacman.py
Pacman allows setting the install reason of packages. This PR adds this feature to the pacman module.
By default, no reason is explicitly set and the default behaviour of pacman is left untouched.
`reason_for: all` sets the install reason for all packages and represents the behavior of pacman when `--asdeps` or `--asexplicit` are specified.
`reason_for: new; reason: dependency` is a combination which is, as far as I know, not possible with pacman but very useful, as this enables specifying all wanted optional dependencies of a package without setting the already explicitly installed ones to dependency.
pacman
=> Pacman: Add support for install reason

changelogs/fragments/5019-slack-support-more-groups.yml, plugins/modules/notification/slack.py
Some of the older private channels in the workspace I'm working in have channel ID's starting with `G0` and `GF` and this resulted to false positive `channel_not_found` errors.
I've added these prefixes to the list to maintain as much backwards compatibility as possible.
Ideally the auto-prefix of the channel name with `#` is dropped entirely, given the Channel ID's have become more dominant in the Slack API over the past years.
Slack notification module
This ansible task will trigger the "channel_not_found" error, because this module erroneously prefixes the channel id with `#`:
```ansible
- name: Send a message to slack
community.general.slack:
token: "{{ slack_token }}"
channel: GF123456
msg: my-message
```
=> Slack: Add support for (some) groups

changelogs/fragments/5023-http-agent-param-keycloak.yml, plugins/doc_fragments/keycloak.py, plugins/module_utils/identity/keycloak/keycloak.py
When keycloak is running behind WAF or CDN, (.e.g Cloudflare with DNS Proxy) Requests with no User-Agent get status code 403 Forbidden.
Fixes #5023
- Bugfix Pull Request 
module_utils/identity/keycloak
When Keycloak is running behind a CDN/WAF, absence of use-agent gets considered as bot request and hence return 403 Forbidden
**Before Change**
```bash
TASK [keycloakrealm : Create or update Keycloak realm (minimal example)] ****************************************************************************************************************
task path: /home/dishant/Projects/grist/keycloak-ansible/keycloakrealm/tasks/main.yml:34
redirecting (type: modules) community.general.keycloak_realm to community.general.identity.keycloak.keycloak_realm
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: …
```
=> Fix: Add user-agent header to allow request through WAF with bot protection

changelogs/fragments/5022-lastpass-lookup-cleanup.yml, plugins/lookup/lastpass.py, tests/unit/plugins/lookup/test_lastpass.py
Cleaned up LastPass lookup plug-in to meet coding standards.
Since the issues in #5012 are a result of me previously basing code off of this, by making this adhere to current standards for this repository, hopefully this will result in less work for reviewers in the future.
`lastpass`
=> lastpass lookup: use config manager, improve documentation

changelogs/fragments/5037-xfconf-add-cmd-output.yaml, plugins/modules/system/xfconf.py, tests/unit/plugins/modules/system/test_xfconf.py
Add `stdout`, `stderr` and `cmd` to the module output.
=> xfconf: add command output to results

plugins/module_utils/wdc_redfish_utils.py
Allows user to specify Basic Auth credentials for firmware update image.
wdc_redfish_command
Fix to support basic auth credentials for firmware update image.  
Example that was not working before:
```
ansible  mm4 -m community.general.wdc_redfish_command -e '{"update_creds": {"username": "user", "password": "password"}}' -a "username={{ user }} password={{ pass }} ioms={{ ioms }}  category=Update command=UpdateAndActivate update_creds={{ update_creds }} update_image_uri=http://example.com:8088/bundle4_0_10ST.tar.gz"
```
=> WDC Redfish firmware update support for update image creds

plugins/modules/system/aix_filesystem.py
aix_filesystem - Fix example tasks. Previously, the examples in the docs were erroneously using `community.general.filesystem` as an argument instead of `filesystem`.
aix_filesystem
=> aix_filesystem: Fix examples

changelogs/fragments/5059-wdc_redfish_command-indicator-leds.yml, plugins/module_utils/wdc_redfish_utils.py, plugins/modules/remote_management/redfish/wdc_redfish_command.py, tests/unit/plugins/modules/remote_management/wdc/test_wdc_redfish_command.py
WDC Enclosure support for indicator LED toggling for various chassis components, including:
- Enclosure
- I/O Modules
- Power Supplies
- External Fans
- Internal Fan
wdc_redfish_command
Sample command:
```
ansible mm4 -m community.general.wdc_redfish_command -a "username={{ user }} password={{ pass }} baseuri={{ioms[0]}} category=Chassis resource_id=FanInternalFRU command=IndicatorLedOn"
```
=> WDC Redfish support for chassis indicator LED toggling.

.github/BOTMETA.yml, changelogs/fragments/5085-pipx-use-cmd-runner.yaml, plugins/module_utils/pipx.py, plugins/modules/packaging/language/pipx.py
Use `CmdRunner` for the CLI invocation.
plugins/module_utils/pipx.py
=> pipx: use CmdRunner

changelogs/fragments/5100-pipx-req-if.yaml, plugins/modules/packaging/language/pipx.py, tests/integration/targets/pipx/tasks/main.yml
Add `required_if` clause for states `upgrade` and `reinstall`, requiring parameter `name`. That mimics the behaviour of the underlying `pipx`, effectively making the module fail faster in that situation.
pipx
=> pipx: add required_if fo upgrade and reinstall

changelogs/fragments/5108-proxmox-node-name-condition.yml, plugins/modules/cloud/misc/proxmox_kvm.py
Fix condition which is always false.
`proxmox_kvm`
`not (node, name)` is always false, the correct check is if either `node` or `name` is unspecified.
Extracted from https://github.com/ansible-collections/community.general/pull/4027.
=> Fix Proxmox `node`, `name` condition.

changelogs/fragments/5105-pipx-state-latest.yaml, plugins/modules/packaging/language/pipx.py, tests/integration/targets/pipx/tasks/main.yml
Added state `latest` to the module.
Fixes #5039 
pipx
=> pipx: add state latest

changelogs/fragments/5107-proxmox-agent-argument.yaml, plugins/modules/cloud/misc/proxmox_kvm.py
Allow specifying Proxmox `agent` argument as string.
`proxmox_kvm`
The `agent` argument can not only be `true` or `false` (or `0`/`1`) but also be a string, e.g. `enabled=1,fstrim_cloned_disks=1`.
Extracted from https://github.com/ansible-collections/community.general/pull/4027.
=> Change Proxmox `agent` argument to string.

changelogs/fragments/5112-fix-nsupdate-ns-entry.yaml, plugins/modules/net_tools/nsupdate.py
Fixed a bug where one cannot update an existing NS record.
`nsupdate`
In order to determine if any changes occurred, the `nsupdate` component queries the TTL of the resulting record. 
When querying `A`, `AAAA`, `SOA`, or `CNAME` records, one gets something like this in the ANSWER section:
```
;; ANSWER SECTION:
github.com.		60	IN	A	140.82.113.3
```
Here, we can see a TTL of 60 seconds.
However, an `NS` record and its TTL appears in the AUTHORITY section:
```
;; AUTHORITY SECTION:
github.com.		900	IN	NS	dns1.p08.nsone.net.
github.com.		900	IN	NS	dns2.p08.nsone.net.
github.com.		900	IN	NS	dns3.p08.nsone.net.
github.com.		900	IN	NS	dns4.p08.nsone.net.
```
The `nsupdate` component only searches for TTL in the ANSWER section. Thus, when updating `NS` records, the …
=> Fix nsupdate when updating NS record

tests/integration/targets/filesystem/defaults/main.yml
This seems to be new minimal size. The xfs tests on Arch no longer pass with smaller sizes: https://dev.azure.com/ansible/community.general/_build/results?buildId=51678&view=logs&j=57f52a93-2f8f-5f4a-64e7-e08c30d14461&t=639a25f5-5b1b-5d56-c79d-060a9682ed36&l=9760
filesystem
=> filesystem tests: increase xfs size to 300 MB

changelogs/fragments/5129-dig-boolean-params-fix.yml, plugins/lookup/dig.py, tests/integration/targets/lookup_dig/aliases, tests/integration/targets/lookup_dig/meta/main.yml, tests/integration/targets/lookup_dig/tasks/main.yml
Fixes evaluation of falsy boolean parameters in dig lookup plugin.
community.general.dig lookup plugin
Plugin currently uses `bool()` function to convert string boolean values to boolean type. This function in not the right one for this task as is returns `True` for every non-empty string:
```
Python 3.9.7 (default, Sep 13 2021, 08:18:39) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> bool('False')
True
>>> bool('no')
True
```
There is function in ansible.module_utils for this which correctly handles string-to-boolean conversion.
I also added tests for dig lookup and this issue specifically.
=> dig: Fix evaluation of boolean parameters

.github/workflows/docs-pr.yml
For example test-only PRs such as #5133 do not need a docs build. Since the docs build is pretty slow for community.general (5 minutes for each, i.e. 10 minutes in total), let's save some GHA time by skipping it for some paths!
CC @briantist 
docs PR workflow
=> Do not build docs for test-only, changelog-only, or meta-only changes

.github/workflows/reuse.yml, .reuse/dep5, CHANGELOG.rst.license, README.md, changelogs/changelog.yaml.license, changelogs/fragments/licenses-2.yml, tests/sanity/extra/aliases.json.license, tests/sanity/extra/botmeta.json.license, tests/sanity/extra/extra-docs.json.license, tests/sanity/extra/licenses.json.license, tests/sanity/extra/licenses.py, tests/sanity/extra/licenses.py.license, tests/sanity/extra/no-unwanted-files.json.license, tests/sanity/ignore-2.11.txt.license, tests/sanity/ignore-2.12.txt.license, tests/sanity/ignore-2.13.txt.license, tests/sanity/ignore-2.14.txt.license
Everything except changelog/fragments/ is now reuse conformant (https://reuse.software/spec/).
CC @gotmax23
licensing
=> Make reuse conformant

.github/BOTMETA.yml, plugins/filter/crc32.py, tests/unit/plugins/filter/test_crc32.py
In order to create a [subscription](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_subscription_module.html) on PostgreSQL, we have to provide a `slot_name` (by default, it's the same name as the ones in `publications`).
This name:
* can contain only lower case alphanumeric characters and the underscore sign
* is silently truncated to **63 chars**
Object names on PostgreSQL, including publications, can contain invalid characters for a replication slot name.
To solve this issue, [pglogical](https://github.com/2ndQuadrant/pglogical):
* [replaces all invalid chars with underscores](https://github.com/2ndQuadrant/pglogical/blob/REL2_4_1/pglogical_functions.c#L2386-L2394)
* [creates short hashes when size of a name is bigger than a threshold (16 …
=> feat: Add crc32 filter

changelogs/fragments/5151-add-delinea-support-tss-lookup.yml, plugins/lookup/tss.py
Thycotic has changed names to Delinea, as such the developers of the `thycotic-tss-sdk` package have updated their [library](https://github.com/DelineaXPM/python-tss-sdk). The latest version, 1.2.0, renamed the module from `thycotic` to `delinea`. This update breaks the `tss.py` lookup plugin because it no longer can import `thycotic.secrets.server`. I've added a nested `try:` block to the code to attempt to import `delinea.secrets.server` if `thycotic.secrets.server` fails. This maintains backwards compatibility with older versions on the library.
tss.py
Without this fix, the plugin would generate the following error:
```paste below
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('community.general.tss', 12345) …
```
=> adding nested try block for tss.py to import new Delinea library

changelogs/fragments/5124-compatibility-virtualmedia-resource-location.yaml, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/redfish/redfish_command.py, plugins/modules/remote_management/redfish/redfish_info.py
Update redfish module for compatibility due to redfish spec changes the virtualMedia resource location from Manager to Systems.
redfish
Virtual media resource locates on Manager or Systems category.
=> Update redfish module for compatibility with VirtualMedia resource location

tests/utils/constraints.txt
See https://dev.azure.com/ansible/community.general/_build/results?buildId=52124&view=logs&j=2af077cc-9967-5a59-41b3-7f2740d297c7&t=03acf6a6-34c4-5cf9-db61-19526b7fc7bb
```
Collecting stormssh
Using cached https://files.pythonhosted.org/packages/0a/18/85d12be676ae0c1d98173b07cc289bbf9e0c67d6c7054b8df3e1003bf992/stormssh-0.7.0.tar.gz
Collecting paramiko (from stormssh)
Using cached https://files.pythonhosted.org/packages/04/e5/39ec73dd4a8769d6759b8d6c60a1b2c9337f585407c2ae8bfb8ccb734278/paramiko-2.11.0-py2.py3-none-any.whl
Collecting termcolor (from stormssh)
Using cached https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting flask (from stormssh)
Using cached …
```
=> [TEMP] CI: Fix RHEL 8 issues by restricting bcrypt to < 4.0.0

changelogs/fragments/5194-fix-proxmox-agent-exception.yaml, plugins/modules/cloud/misc/proxmox_kvm.py
Fixes https://github.com/ansible-collections/community.general/issues/5181.
`proxmox_kvm`
=> Fix exception when `agent` argument is not specified.

tests/integration/targets/lookup_dependent/tasks/main.yml
Right now the nightly fail due to https://github.com/ansible/ansible/issues/78703.
dependent lookup
=> Fix CI failures

changelogs/fragments/5203-seport-add-local-argument.yaml, plugins/modules/system/seport.py
Using `local: true` users can enforce to work only with local policy
modifications. i.e.
$ sudo ansible -m seport -a 'ports=22 state=present setype=ssh_port_t proto=tcp' localhost
localhost | SUCCESS => {
"ports": [
"22"
],
"proto": "tcp",
"setype": "ssh_port_t",
"state": "present"
}
$ sudo semanage port -l -C
$ sudo ansible -m seport -a 'ports=22 state=present setype=ssh_port_t proto=tcp local=true' localhost
localhost | CHANGED => {
"ports": [
"22"
],
"proto": "tcp",
"setype": "ssh_port_t",
"state": "present"
}
$ sudo semanage port -l -C
SELinux Port Type              Proto    Port Number
ssh_port_t                     tcp      22
$ sudo ansible -m seport -a 'ports=22 state=absent setype=ssh_port_t proto=tcp local=true' localhost
localhost | CHANGED => …
=> seport: add `local` argument

changelogs/fragments/5126-nmcli-remove-diffs.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Follow-up https://github.com/ansible-collections/community.general/pull/4746
* `nmcli connection show` includes vpn.service-type but not vpn-type.
Switching to vpn.service-type removes unneeded diffs while keeping
the same functionality, as vpn-type is an alias of vpn.service-type
per nm-settings-nmcli(1).
NetworkManager also adds `org.freedesktop.NetworkManager.` prefix for
known VPN types [1]. The logic is non-trivial so I didn't implement it
in this commit. If a user specifies `service-type: l2tp`, changed will
be always be True:
```Diff
-    "vpn.service-type": "org.freedesktop.NetworkManager.l2tp"
+    "vpn.service-type": "l2tp"
```
* The vpn.data field from `nmcli connection show` is sorted by keys and
there are spaces around equal signs. I added codes for parsing such
data.
Tests …
=> nmcli: avoid changed status for most cases with VPN connections

changelogs/fragments/5202-bugfix-environmentError-wrong-indentation.yaml, plugins/modules/system/listen_ports_facts.py
Fixes #4953 
As part of the above merge request a minor bug was introduced. 
- The indentation of an `else` statement was one too far.  
- The purpose of the `else` statement is now handled in the function: `split_pid_name`
listen port facts
The else statement:`EnvironmentError('Could not get process information for the listening ports.')` can be removed. The purpose was to check `if conns and pids` exists and else throw the error. 
See previous usage line in older version 173 / 194: https://github.com/ansible-collections/community.general/blob/6a7811f6963ad1f5f92342b786e70a809e1c9e08/plugins/modules/system/listen_ports_facts.py
This is now handled in the `split_pid_name` function.
=> Bugfix - EnvironmentError with wrong indentation

changelogs/fragments/5193-consul-session-token.yaml, plugins/modules/clustering/consul/consul_kv.py, plugins/modules/clustering/consul/consul_session.py
This change allow to use a token when creating a session.
It also fixes the fact that session_id was taken as an argument of consul_kv but not applied when creating a new key/pair.
consul_kv
consul_session
Before
```paste below
PLAY [Example] *************************************************
TASK [Create a session with a token] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (community.general.consul_session) module: token. Supported parameters include: delay, id, node, scheme, datacenter, checks, validate_certs, behavior, name, port, host, ttl, state."}
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP …
```
=> Consul session token

changelogs/fragments/5239-nagios-refactor.yaml, plugins/modules/monitoring/nagios.py
Minor refactoring in nagios module.
nagios
=> nagios: some refactoring

changelogs/fragments/5228-nmcli-ip-options.yaml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
This can be used for split tunneling - I extended a test as an example.
nmcli
Here is a complete example. `gw4_ignore_auto` is used as VPNs often come with a default route for `0.0.0.0/0`.
```YAML
- name: >-
Create a VPN L2TP connection for ansible_user to connect on vpn.example.com
authenticating with user 'brittany' and pre-shared key as 'Brittany123'. Split tunneling
is configured and only traffic to 192.168.200.0/24 goes throught the VPN.
type: vpn
conn_name: my-vpn-connection
vpn:
permissions: "{{ ansible_user }}"
service-type: org.freedesktop.NetworkManager.l2tp
gateway: vpn.example.com
password-flags: 2
user: brittany
ipsec-enabled: true
ipsec-psk: "0s{{ 'Brittany123' | ansible.builtin.b64encode }}"
gw4_ignore_auto: true
routes4: …
```
=> nmcli: honor IP options for VPNs

changelogs/fragments/5149-nmcli-bond-option.yml, plugins/modules/net_tools/nmcli.py
Following my feature request: https://github.com/ansible-collections/community.general/issues/5148
With the nmcli you can specify the xmit_hash_policy type.
That isn't possible with the ansible module so far.
https://www.kernel.org/doc/Documentation/networking/bonding.txt
module nmcli
=> nmcli: Add xmit_hash_policy to bond options.

changelogs/fragments/5241-homebrew-add-linux-path.yaml, plugins/modules/packaging/os/homebrew.py, plugins/modules/packaging/os/homebrew_tap.py
Homebrew on Linux is by default installed in `/home/linuxbrew/.linuxbrew/bin`, so let's search for brew there too.
https://docs.brew.sh/Homebrew-on-Linux#install
homebrew
=> homebrew: add Linux brew path to defaults

changelogs/fragments/5240-unused-imports.yaml, plugins/module_utils/alicloud_ecs.py, plugins/modules/cloud/alicloud/ali_instance.py, plugins/modules/cloud/alicloud/ali_instance_info.py, plugins/modules/cloud/misc/proxmox.py, plugins/modules/cloud/misc/proxmox_domain_info.py, plugins/modules/cloud/misc/proxmox_group_info.py, plugins/modules/cloud/misc/proxmox_kvm.py, plugins/modules/cloud/misc/proxmox_nic.py, plugins/modules/cloud/misc/proxmox_snap.py, plugins/modules/cloud/misc/proxmox_storage_info.py, plugins/modules/cloud/misc/proxmox_tasks_info.py, plugins/modules/cloud/misc/proxmox_template.py, plugins/modules/cloud/misc/proxmox_user_info.py, plugins/modules/database/misc/redis.py, plugins/modules/monitoring/airbrake_deployment.py, plugins/modules/monitoring/datadog/datadog_downtime.py, plugins/modules/remote_management/imc/imc_rest.py, plugins/modules/remote_management/redfish/ilo_redfish_info.py, plugins/modules/system/sap_task_list_execute.py, plugins/modules/web_infrastructure/rundeck_job_executions_info.py, plugins/modules/web_infrastructure/rundeck_job_run.py
Removed many imports that are not used by their code.
plugins/modules/cloud/alicloud/ali_instance.py
plugins/modules/cloud/alicloud/ali_instance_info.py
plugins/modules/cloud/misc/proxmox_domain_info.py
plugins/modules/cloud/misc/proxmox_group_info.py
plugins/modules/cloud/misc/proxmox_nic.py
plugins/modules/cloud/misc/proxmox_snap.py
plugins/modules/cloud/misc/proxmox_storage_info.py
plugins/modules/cloud/misc/proxmox_tasks_info.py
plugins/modules/cloud/misc/proxmox_template.py
plugins/modules/cloud/misc/proxmox_user_info.py
plugins/modules/database/misc/redis.py
plugins/modules/monitoring/airbrake_deployment.py
plugins/modules/monitoring/datadog/datadog_downtime.py …
=> multiple modules: removed unused imports

changelogs/fragments/5224-proxmox-unprivileged-default.yaml, plugins/modules/cloud/misc/proxmox.py
Currently the default for the `unprivileged` attribute is set to false, which means all containers are created by default with root mapped to the host root - not very safe to say the least.
`proxmox` module
=> changed the default proxmox container unprivileged flag

tests/integration/targets/nomad/meta/main.yml, tests/integration/targets/nomad/tasks/main.yml
Tests currently fail on CentOS 7.
nomad integration tests
=> Restrict Python packages for nomad tests

changelogs/fragments/5271-gitlab_hook-refactor.yaml, plugins/modules/source_control/gitlab/gitlab_hook.py
Minor improvements.
gitlab_hook
=> gitlab_hook: minor refactoring

changelogs/fragments/5249-add-new-channel-prefix.yml, plugins/modules/notification/slack.py
1. For channels wich ID starts with `CP` `#` symbol is being prepended
2. docs improved for cases when `message_id` is supplied
1. `CP` string was added to the list which describes `channel_id` prefixed for which `#` symbol will be added in front of `channel_id`
2. Added notes regarding `channel_id` has to be literal Channel ID returned by previous task run.
slack
1. When `build_payload_for_slack` is called there is an `if` which prepends `#` if `channel_id` starts with a certain symbols. I've stumbled upon a channel which ID starts with `CP` but current implementation doesn't have this string in the list so I got `#CPxxxxxx` added to payload.
2. It fails when `message_id` is supplied and `channel_id` is either "mychannel_name` or `#mychannel_name` it only works. …
=> slack: add CP channel prefix

plugins/module_utils/pipx.py
Removed unused import
plugins/module_utils/pipx.py
=> pipx module utils: removed unused import

.github/BOTMETA.yml, meta/runtime.yml, plugins/modules/cloud/misc/proxmox_disk.py, tests/integration/targets/proxmox/tasks/main.yml
Add `proxmox_disk` module to provide management of virtual volumes in QEMU(KVM) virtual machines
- proxmox_disk
This module provides ability to manage disks in Proxmox VMs in such ways:
- create disk (fresh new or import from existing image);
- update disk (change some parameters, for example: iops limit, backup status);
- move disk (between storages in one VM or to another VM);
- grow size (shrinking not supported);
- detach disk (leave it `unused`);
- remove disk (permanently).
=> New module: Proxmox disk management

.github/workflows/reuse.yml
Right now we have to explicitly allow to run that workflow for new contributors. That's annoying and not really necessary.
CI
=> CI: try to run reuse workflow without explicitly allowing it for new contributors

.azure-pipelines/azure-pipelines.yml, .github/workflows/docs-pr.yml, README.md, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.15.txt.license
stable-2.14 has been branched.
CI
=> Add stable-2.14 to CI, adjust to devel version bump

.azure-pipelines/azure-pipelines.yml, README.md
Now that stable-2.14 has been branched, use that instead of devel.
CI
=> [stable-4] Replace devel with stable-2.14 in CI

changelogs/fragments/5301-netcup_dnsapi-timeout.yml, plugins/modules/net_tools/netcup_dns.py
The `netcup_dnaspi` module relies on python package `nc_dnsapi` which supports specifying a connection timeout, defaulting to 5 (see https://github.com/nbuchwitz/nc_dnsapi/blob/master/nc_dnsapi/__init__.py#L186)
Being able to specify a value higher than the default is helpful when working on an unstable or high-latency internet connection (e.g. LTE)
This change adds a timeout parameter to the `netcup_dnsapi` module.
netcup_dnsapi
none
=> netcup_dnsapi: Add timeout paramter

changelogs/fragments/5307-ini_file-lint.yaml, plugins/modules/files/ini_file.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt
Fixed lint error that was being ignored
plugins/modules/files/ini_file.py
=> ini_file: fix lint error

changelogs/fragments/5008-addSetSessionService.yml, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/redfish/redfish_config.py
adding SetSessionService command to redfish_config
to set BMC default session timeout policy.
Fixes #5008
redfish_config
=> Add SetSessionService to redfish_config

changelogs/fragments/5287-machinectl-become-success.yml, plugins/become/machinectl.py
Combines the success command when building the become command. This is consistent with other become plugins.
Was debugging an issue involving the combination of pipelining and running machinectl as sudo and came across this, though this is not the cause it seemed prudent to submit a PR for it.
machinectl
```paste below
```
=> machinectl: include the success command

changelogs/fragments/5274-proxmox-snap-container-with-mountpoints.yml, plugins/module_utils/proxmox.py, plugins/modules/cloud/misc/proxmox.py, plugins/modules/cloud/misc/proxmox_kvm.py, plugins/modules/cloud/misc/proxmox_snap.py, plugins/modules/cloud/misc/proxmox_template.py
This PR adds a new parameter `unbind` to the `proxmox_snap` module, which allows to take snapshots of containers with configured mount points, bypassing the Proxmox limit by *temporarily* disabling the configuration before the snapshot.  
There is also a small improvement in how the API tasks are checked.  
A new `api_task_ok` helper is provided in the `module_utils.proxmox.ProxmoxAnsible` class, and used across the proxmox modules to standardize how pending tasks are checked.  
community.general.proxmox_snap
`proxmox_snap`  
The mountpoint-specific config API endpoint `mp[n]` is unfortunately (from an implementation pov, of course it's only logical) restricted to `root@pam` authenticating with password. Tokens will not work, at least I couldn't get them to work. …
=> [feat] proxmox_snap: snapshot containers with configured mountpoints

changelogs/fragments/5291-fix-nmcli-error-when-setting-unset-mac-address.yaml, plugins/modules/net_tools/nmcli.py
This adds an `if` to avoid errors when setting a mac address in an existing connections that didn't have it and does the same thing for two other parameters.
Fixes #5290
nmcli
N/A
=> nmcli: fix error when setting previously unset mac address

changelogs/5147-terraform-init-no-color.yml, changelogs/fragments/5147-terraform-init-no-color.yml, plugins/modules/cloud/misc/terraform.py
When running `terraform init` fails, it would output ansi color sequences, making the output hard to read.
Maybe setting TF_IN_AUTOMATION would also be beneficial: https://www.terraform.io/cli/config/environment-variables#tf_in_automation
terraform
```paste below
```
=> terraform: run `init` with no-color, too

changelogs/fragments/5280-lxc_container-py3.yaml, plugins/modules/cloud/lxc/lxc_container.py
This change is mostly just a documentation change which will report the requirements correctly for python3-lxc. I've also removed the use of six which results in us changing `xrange` to `range`.
Fixes: https://github.com/ansible-collections/community.general/issues/5294
lxc_container
Signed-off-by: Kevin Carter <kevin.carter@figment.io>
=> chore: Update lxc_container to support py3

.github/BOTMETA.yml, meta/runtime.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/identity/keycloak/keycloak_client_rolemapping.py, plugins/modules/identity/keycloak/keycloak_user_rolemapping.py, tests/integration/targets/keycloak_user_rolemapping/aliases, tests/integration/targets/keycloak_user_rolemapping/tasks/main.yml, tests/integration/targets/keycloak_user_rolemapping/vars/main.yml, tests/unit/plugins/modules/identity/keycloak/test_keycloak_client_rolemapping.py
Add `keycloak_user_rolemapping` module to provide management of direct assignment of client/realm roles to users. Also provides user role mapping for service-account users.
`keycloak_user_rolemapping`
Example:
```
- name: Map a client role to a user, authentication with credentials
community.general.keycloak_user_rolemapping:
realm: MyCustomRealm
auth_client_id: admin-cli
auth_username: USERNAME
auth_password: PASSWORD
state: present
client_id: client1
user_id: user1Id
roles:
- name: role_name1
id: role_id1
- name: role_name2
id: role_id2
- name: Map a client role to a service account user for a client, authentication with credentials …
```
=> New Module: Keycloak User Rolemapping

changelogs/fragments/5313-fix-redhat_subscription-idempotency-pool_ids.yml, plugins/modules/packaging/os/redhat_subscription.py
This fix ensures the idempotency of the redhat_subscription module when pool_ids are used. The main problem was, that a 'None' quantity was not properly handled and that the quantity check compared a string with an integer.
Signed-off-by: Christoph Fiehe <c.fiehe@eurodata.de>
```paste below
```
=> Fix #5313: redhat_subscription module is not idempotent when pool_ids are used

changelogs/fragments/4797-terraform-complex-variables.yml, plugins/modules/cloud/misc/terraform.py, tests/integration/targets/terraform/files/complex_variables/main.tf, tests/integration/targets/terraform/files/complex_variables/variables.tf, tests/integration/targets/terraform/tasks/complex_variables.yml, tests/integration/targets/terraform/tasks/main.yml, tests/integration/targets/terraform/tasks/test_provider_upgrade.yml
* Terrform variable types are mapped to ansible veriable types
* Currently handles Dict, List, Str, Int, Bool types
* Updated the documentation accordingly
* Updated with an example.
Added the capability to specify complex variables structures in the terraform module. With this change we can specify Terraform Object / Nested type variables via ansible:
For example, in TF:
```
variable "vm_additional_disks" {
description = "Additional Disks"
type = list(object({
unit_number      = number
size             = number
label            = string
thin_provisioned = bool
}))
default = []
}
```
Would translate to:
```
vm_additional_disks:
- label: "Third Disk"
size: 40
thin_provisioned: true
unit_number: 2
- label: "Fourth Disk"
size: 22
thin_provisioned: true
unit_number: 3
```
- Feature Pull …
=> Allow terraform module to specify complex variable structures

plugins/modules/identity/keycloak/keycloak_user_federation.py
Added an example to the vendor option. The description of the option is not verbose enough and can lead to problems.
More precisely, you need to enter the "short name" of the vendor and not the full name.
For instance, you need to enter rhds for "Red Hat Directory Server". If you enter "Red Hat Directory Server" in the option, the user federation will be created but the vendor will remain blank. 
community.general.keycloak_user_federation module
vendor option
=> keycloak_user_federation: add explanation and example to vendor option

changelogs/fragments/5306-add-options-for-authentication.yml, plugins/modules/clustering/znode.py
This adds the possibility to use zookeeper ACL authentication.
Kazoo supports "digest” and “sasl”.
znode
=> znode: add options for authentication

changelogs/fragments/3671-illumos-pfexec.yml, plugins/become/pfexec.py, tests/unit/plugins/become/test_pfexec.py
Pfexec become does not work for illumos
fixes #3671
plugins/become/pfexec.py
Changed quoting and command composition in analogy to standard su become
=> Make pfexec become usable for illumos

changelogs/fragments/5358-lxc-container-refactor.yml, plugins/modules/cloud/lxc/lxc_container.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Minor refactor: mostly pythonisms, but removing the call to `os.path.expanduser()` in line 1361 (pre-change) because:
* `source_dir` is passed as a parameter to the `_create_tar()` method
* `_create_tar()` is only called in one spot in the code, in line 1568 (post-change), inside the method `_container_create_tar()` as `self._create_tar(source_dir=work_dir)`
* the variable `work_dir` is defined in lines 1498-1502 (post-change) as:
```python
temp_dir = tempfile.mkdtemp()
work_dir = os.path.join(temp_dir, self.container_name)
```
Therefore, `work_dir` will always be an absolute path, therefore `expanduser()` is redundant.
plugins/modules/cloud/lxc/lxc_container.py
=> lxc_container: minor refactor

changelogs/fragments/5349-drop-gentoolkit-more-knobs.yml, plugins/modules/packaging/os/portage.py
This solves the issue brought up in https://github.com/ansible-collections/community.general/pull/3870. The Portage Ansible module depends on an external shell command, when it could simply use the Portage module on every system that uses Portage.
Additionally, this adds support for handling the `--with-bdeps` and `--backtrack` `emerge` command line options.
Portage
Similar to the other PR, this fixes the following kind of issue when running on a system that doesn't have the requisite external shell command:
```paste below
host | FAILED! => {
"discovered_interpreter_python": "/usr/bin/python3.9"
},
"msg": "Failed to find required executable \"equery\" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin" …
```
=> portage: drop usage of gentoolkit, add knobs for --with-bdeps, --backtrack

changelogs/fragments/5342-opentelemetry_bug_fix_opentelemetry-api-1.13.yml, plugins/callback/opentelemetry.py
`opentelemetry-api 1.13` [removed](https://github.com/open-telemetry/opentelemetry-python/commit/a6324d891365f61e3631dabd68f3321482f15c51) support for `_time_ns` , this change will allow to fallback to the previous implementation of [synthetically creating a time_ns](https://github.com/open-telemetry/opentelemetry-python/commit/a6324d891365f61e3631dabd68f3321482f15c51#diff-3fd7b941cb11a39b91324ef4f9784a23dc1436c67dbf696f4356a5ff9b95f793L29) when using <= `python 3.6` with `opentelemetry-api 1.13`, if that's even possible...
Closes https://github.com/ansible-collections/community.general/issues/5315
=> [opentelemetry][callback] support opentelemetry-api 1.13

changelogs/fragments/5367-consul-refactor.yaml, plugins/modules/clustering/consul/consul.py
Minor refactor on the module.
plugins/modules/clustering/consul/consul.py
=> consul: pythonisms + a couple of required_if clauses

changelogs/fragments/5348-fix-vbox-deeply-nested-hostvars.yml, plugins/inventory/virtualbox.py
Fixes #5332 
Skip parsing values with keys that have both a value and nested data. Skip parsing values that are nested more than two keys deep.
virtualbox
Taken from the issue, calling `ansible all -i vbox.yml --list -vvv` produces an error that contains the following:
```paste below
[WARNING]: * Failed to parse /home/etienne/playbook/vbox.yml with auto plugin: 'str' object does not support item assignment
File "/home/etienne/.local/lib/python3.8/site-packages/ansible/inventory/manager.py", line 290, in parse_source
plugin.parse(self._inventory, self._loader, source, cache=cache)
File "/home/etienne/.local/lib/python3.8/site-packages/ansible/plugins/inventory/auto.py", line 59, in parse
plugin.parse(inventory, loader, path, cache=cache)
File …
```
=> virtualbox: Fix crash when handling deeply nested hostvars

plugins/modules/files/archive.py
=> archive: better expose requirements

changelogs/fragments/5400-django-manage-deprecations.yml, plugins/modules/web_infrastructure/django_manage.py
Deprecate commands from ancient Django releases.
django_manage
=> django_manage: deprecate old commands

changelogs/fragments/5361-nmcli-add-infiniband-transport-mode.yaml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
Adds transport_mode configuration for Infiniband based IPoIB devices, which is one of:
- datagram (default)
- connected
Fixes #5356
nmcli.py
For Infiniband IPoIB devices like _ib0_ there are two different transport modes that can be chosen. 
- datagram 
- connected
```
infiniband.transport-mode:datagram
/sys/class/net/ib0/mtu:2044
/sys/class/net/ib0/mode:datagram
infiniband.transport-mode:connected
/sys/class/net/ib0/mtu:65520
/sys/class/net/ib0/mode:connected
```
=> nmcli: add transport_mode configuration for Infiniband devices

changelogs/fragments/5404-django-manage-venv-deprecation.yml, plugins/modules/web_infrastructure/django_manage.py
As pointed out in https://github.com/ansible-collections/community.general/issues/5374#issuecomment-1287536369
creating the virtualenv from within `django_manage` is not only a bad design decision but it simply does not work as it is.
django_manage
=> django_manage: deprecate venv creation when missing

changelogs/fragments/5370-mh-cmdmixin-deprecation.yaml, plugins/module_utils/mh/mixins/cmd.py, plugins/module_utils/mh/module_helper.py
Since the introduction of `CmdRunner` in April 2022, it should be preferred to `CmdMixin` and the derived classes `CmdModuleHelper` and `CmdStateModuleHelper`.
This PR deprecates `CmdMixin`.
=> MH CmdModuleHelper: deprecation

changelogs/fragments/5198-proxmox.yml, plugins/modules/cloud/misc/proxmox_kvm.py
In [this commit](https://github.com/reitermarkus/community.general/commit/0be7b6e7b91bb2d7b6e16773cc9b93a655ca0dd6) the parameter sent to proxmox api has been changed from type bool to type string but instead of converting the boolean into a value that is readable by the proxmox api it just sends a string containing `'True'` or `'False'` to the pve api. According to [specification](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu) proxmox expects a `'1'` or a `'0'` as content of the `agent` parameter.
This bug resulted in failing vm creations:
```
fatal: [vm-template -> localhost]: FAILED! => {"changed": false, "msg": "creation of qemu VM test with vmid 171 failed with exception=400 Bad Request: Parameter verification failed. - {'agent': \"invalid format - format …
```
=> Send string instead of boolean to proxmox api

plugins/filter/jc.py
This PR adds a very small change to the jc filter to make it ever easier to use on your way to JC
+label: docsite_pr
I added a small change to the example, which shows how to quickly use the filter.
this is after I filed an issue regarding the jc filter not working (I added the package to the target machine and not the one that runs it.
Additionally I have `jc` installed on my machine so I was suprized I needed to use the jc python import.
related to #5390 
jc filter
see the issue with the example and solution
=> clarify jc filter usage in the example

changelogs/fragments/5385-search_s-based-_is_value_present.yaml, plugins/modules/net_tools/ldap/ldap_attrs.py
Fixes https://github.com/ansible-collections/community.general/issues/977
community.general.ldap_attrs
Instead of comparing the dn's attribute values using compare_s, I suggest using search_s plus filter, because search is X-ORDERED agnostic.
=> ldap_attrs: search_s based _is_value_present

changelogs/fragments/5439-dig-return-empty-result.yml, plugins/lookup/dig.py
This fix causes dig lookup to return an empty list instead of a list of empty strings, behaviour which was probably erroneously introduced years ago but which seems a bug.
Fixes https://github.com/ansible-collections/community.general/issues/5428
dig
```
TASK [Print retrieve NS] ************************************************************
"ns": []
}
TASK [nxdomain (real_empty==False)] *************************************************
"msg": [
"NXDOMAIN"
]
}
TASK [nxdomain (real_empty==True)] **************************************************
"msg": []
}
```
=> add option to force dig lookup to return empty list

tests/unit/requirements.txt
Nightly currently fails (ansible-base 2.10 Python 3.6 unit tests):
https://dev.azure.com/ansible/community.general/_build/results?buildId=58662&view=logs&j=e78eaf5f-f379-5300-4702-e3e77c80bf61&t=ec1d214a-386a-5c51-8b46-9fd9c5bdbf67&l=457
```
00:54 ERROR: elastic-apm 6.13.0 has requirement wrapt>=1.14.1, but you'll have wrapt 1.11.1 which is incompatible.
```
CI
=> [stable-4] Fix CI

changelogs/fragments/5438-linode.yml, plugins/inventory/linode.py, tests/unit/plugins/inventory/test_linode.py
templar is already in base class
env var is already consulted in via config resolution
inventory/linnode
=> linnode inventory, remove redundant

changelogs/fragments/5437-proxmox.yml, plugins/inventory/proxmox.py
we already have a templar from base class
loop reuses code instead of X copies of it
inventory/proxmox
=> proxmox inventory, remove redundant and simplify code

changelogs/fragments/4998-nmcli-fix-int-options-idempotence.yml, plugins/modules/net_tools/nmcli.py, tests/unit/plugins/modules/net_tools/test_nmcli.py
This PR adds fix for #4998 and test this bug.
=> fix int options idempotence bug and add new test to check it

changelogs/fragments/5377-nsupdate-ns-records-with-bind.yml, plugins/modules/net_tools/nsupdate.py
Fixes #4657
The "modify_record" method of the nsupdate module uses a delete-first approach to DNS updates.  This prevents any updates to the NS records against Bind9 DNS servers.
This MR changes this behavior where updates to NS records will insert and update existing records, then perform the deletes. 
[plugins/modules/net_tools/nsupdate.py](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/net_tools/nsupdate.py)
I have been using this patch in my infrastructure for 2 months without any side issues.
=> nsupdate: issues/4657

changelogs/fragments/5444-passwordstore-options.yml, plugins/lookup/passwordstore.py, tests/integration/targets/lookup_passwordstore/tasks/password_tests.yml, tests/integration/targets/lookup_passwordstore/tasks/tests.yml
Something which should have been done a long time ago: allow to pass in options as lookup options instead of insisting that they have to be parsed from the terms.
passwordstore lookup plugin
=> passwordstore lookup: allow to pass options as lookup options

tests/integration/targets/scaleway_function_namespace/tasks/main.yml
This PR fix assertions in the integrations tests of the `scaleway_function_namespace` module
`scaleway_function_namespace`
- Using `description` instead of `updated_description` at this stage of the test will always generate an update. What we want to check is if updating `secret_environment_variables` produce an update. This commit remove this possible false positive
- The wrong registered variable was checked when looking for `hashed_value` in the module output
=> [Scaleway] Fix function namespace integration tests assertions

README.md, changelogs/fragments/fqcn-warnings.yml
For background see https://github.com/ansible-community/community-topics/issues/147.
changelog, README
=> [stable-5] Warn about using internal FQCNs for modules and actions

changelogs/fragments/5435-escape-ldap-param.yml, plugins/modules/ldap_attrs.py
Escape ldap search parameter before passing it to `search_s`
Fixes #5434
ldap_attrs
=> ldap_attrs: escape ldap search filter

changelogs/fragments/5450-allow-for-xordered-dns.yaml, plugins/module_utils/ldap.py
Allow for DN's to have {x} prefix on first RDN.
This is an extension to https://github.com/ansible-collections/community.general/pull/5385
ldap
It turns out that in OpenLDAP's ``cn=config``, DN's can be ordered as well and configuring OpenLDAP through ansible therefor is quite cumbersome.
See the following example:
Suppose I want to enable slapd monitoring via ``cn=config``. I would need to add ``back_monitor`` to ``cn=module{0},cn=config`` which is now correctly handled by https://github.com/ansible-collections/community.general/pull/5385. However, I would also need to add a DN:
```
- name: Setup Monitor
community.general.ldap_entry:
dn: olcdatabase=monitor,cn=config
objectClass: olcDatabaseConfig
attributes:
olcRootDN: "cn=admin,cn=Monitor"
olcRootPW: "{{ '%s' | …
```
=> Allow for DN's to have {x} prefix on first RDN

.github/BOTMETA.yml, plugins/modules/scaleway_container_namespace.py, plugins/modules/scaleway_container_namespace_info.py, tests/integration/targets/scaleway_container_namespace/aliases, tests/integration/targets/scaleway_container_namespace/defaults/main.yml, tests/integration/targets/scaleway_container_namespace/tasks/main.yml, tests/integration/targets/scaleway_container_namespace_info/aliases, tests/integration/targets/scaleway_container_namespace_info/defaults/main.yml, tests/integration/targets/scaleway_container_namespace_info/tasks/main.yml
This PR add new modules to manage Scaleway container namespaces services (https://developers.scaleway.com/).
- `scaleway_container_namespace`
- `scaleway_container_namespace_info`
This PR is a part of the original PR #5359 that was too large.
This PR require evolution on Scaleway config in ansible-test : https://github.com/ansible/ansible/pull/79141
=> [Scaleway] Add module to manage container namespaces

changelogs/fragments/5475-snap-option-value-whitespace.yml, plugins/modules/snap.py, tests/integration/targets/snap/tasks/main.yml
Allow whitespaces in options' values.
Fixes #5466 
plugins/modules/snap.py
=> snap: fix regex to support option values with whitespaces

changelogs/fragments/5435-escape-ldap-param.yml, plugins/modules/net_tools/ldap/ldap_attrs.py
Backport of #5435 to stable-4.
@rekup can you quickly check whether I correctly re-applied your change? Automatic cherry-picking didn't work at all, so I basically had to redo your commit.
ldap_attrs
=> [stable-4] ldap_attrs: escape ldap search filter

changelogs/fragments/5484-mksysb-cmd-runner.yml, plugins/modules/mksysb.py
mksysb now using `CmdRunner` instead of `CmdModuleHelper`
plugins/modules/mksysb.py
=> mksysb: using CmdRunner

changelogs/fragments/5485-cpanm-cmd-runner.yml, plugins/modules/cpanm.py, tests/unit/plugins/modules/test_cpanm.py
cpanm now using `CmdRunner` instead of `CmdModuleHelper`
plugins/modules/cpanm.py
=> cpanm: using CmdRunner

plugins/module_utils/scaleway.py, plugins/modules/scaleway_container_namespace_info.py, plugins/modules/scaleway_container_registry_info.py, plugins/modules/scaleway_function_info.py
This PR remove the call to `filter_sensitive_attributes` in Scaleway modules.
Also remove the `filter_sensitive_attributes` from module utils.
- `scaleway_container_namespace_info`
- `scaleway_container_registry_info`
- `scaleway_function_info`
Since the returned values are hashed, we don't need to filter them from before return the to the user.
Also, the not `_info` modules already returns the hashed value.
Should I make a Changelog fragment for this PR ?
=> [Scaleway] Remove unused sensitive values filtering

plugins/filter/jc.py
Clarify that parser names use underscores instead of dashes.
jc
This change is in response to an issue that was opened on the jc github repo:
https://github.com/kellyjonbrazil/jc/issues/317
```paste below
```
=> Clarification to use underscores instead of dashes in parser name

tests/unit/plugins/lookup/onepassword/test_onepassword.py
I removed my more complicated fix but failed to actually put the `sorted()` call back in.
`tests/unit/plugins/lookup/onepassword/test_onepassword.py`
=> Actually sort the fixtures

changelogs/fragments/5506-onepassword_raw-missing-param.yml, plugins/lookup/onepassword.py, plugins/lookup/onepassword_raw.py
Fixes #5506 
`plugins/lookup/onepassword_raw.py`
This might fail sanity tests since the version_added is 6.0.0 which is already release. Though I'm curious how this passed sanity tests originally...
=> onepassword_raw - Add missing parameter to doc string

.github/BOTMETA.yml
Backport of #5524 to stable-5.
=> [stable-5] Ignore mpdehaan in BOTMETA

changelogs/fragments/5514-fix-logical-flaw-when-deleting-jenkins-build.yml, plugins/modules/jenkins_build.py, tests/unit/plugins/modules/test_jenkins_build.py, tests/unit/requirements.txt
At present, after deleting a Jenkins build, the code tries to get the build status of the Jenkins build then judge the success/failure of the deletion. When the Jenkins build is successfully deleted, supposedly Jenkins will throw a jenkins.JenkinsException when fetching the build status, but currently the get_build_status() function will catch the exception then directly return a failure json which is a logical flaw.
Considering that deleting an already non-existent build can throw exceptions in the absent_build() function, I plan to adjust the judging logic in the get_build_status() and the get_result() function to fix this logical flaw in identifying the result of deleting an existing Jenkins build.
jenkins_build
=> Fix a logical flaw when deleting a build in the jenkins_build module

plugins/modules/proxmox_disk.py
https://github.com/ansible-collections/community.general/issues/5492
Remove duplicated vmid reference in URI builder.
Fixes #5492
BUG: Resize disk blocking feature
=> Fix:  Duplicate vmid in proxmox_disk module #5492

changelogs/fragments/5543-dependent-template.yml, plugins/lookup/dependent.py
```
[DEPRECATION WARNING]: The `cache` option to `Templar.template` is no longer functional, and will be removed in a future release. This feature will be removed in version 2.18. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
dependent lookup
=> dependent lookup: prevent deprecation warning with ansible-core 2.14

changelogs/fragments/5538-cmd-runner-as-fixed.yml, plugins/module_utils/cmd_runner.py, tests/unit/plugins/module_utils/test_cmd_runner.py
Actually using `cmd_runner_fmt.as_fixed()` had not been tested and it failed. This PR fixes that, so that `as_fixed()` works as expected.
=> cmd_runner module utils: fix case for as_fixed() format

changelogs/fragments/5563-rax-scaling-group-sanity.yml, plugins/module_utils/rax.py, plugins/modules/rax_scaling_group.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Fix module's sanity checks.
plugins/modules/rax_scaling_group.py
=> rax_scaling_group: fix sanity check

.github/BOTMETA.yml, changelogs/fragments/5565-jenkins-plugin-sanity.yml, plugins/module_utils/jenkins.py, plugins/modules/jenkins_plugin.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Refactor code out to module util so to fix sanity check
plugins/modules/jenkins_plugin.py
=> jenkins_plugin: fix sanity checks

plugins/modules/scaleway_organization_info.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Fix sanity checks.
plugins/modules/scaleway_organization_info.py
=> scaleway_organization_info: sanity checks

plugins/modules/gitlab_project_badge.py, tests/integration/targets/gitlab_project_badge/aliases, tests/integration/targets/gitlab_project_badge/defaults/main.yml, tests/integration/targets/gitlab_project_badge/tasks/main.yml
Add a new GitLab module to manage project badges.
References : 
- [GitLab project badge feature](https://docs.gitlab.com/ee/user/project/badges.html)
- [GitLab project badge API](https://docs.gitlab.com/ee/api/project_badges.html)
- [python-gitlab library badge API](https://python-gitlab.readthedocs.io/en/stable/gl_objects/badges.html)
`gitlab_project_badge`
Resolve part of #5530
=> [GitLab] Add modules to manager project badges

changelogs/fragments/5559-udm-user-sanity.yml, plugins/modules/udm_user.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Fix sanity checks
plugins/modules/udm_user.py
=> udm_user: sanity

tests/integration/targets/copr/aliases
They are failing currently, see for example https://dev.azure.com/ansible/community.general/_build/results?buildId=61147&view=logs&j=d84fb6a4-8599-59ea-4191-10b38957e693&t=70f260b5-0083-56a9-a633-ac67c537096e:
```
01:40 TASK [copr : enable copr project] **********************************************
01:40 task path: /root/ansible_collections/community/general/tests/output/.tmp/integration/copr-h7xlk9om-ÅÑŚÌβŁÈ/tests/integration/targets/copr/tasks/main.yml:8
...
01:41 Including module_utils file ansible/module_utils/common/text/formatters.py
01:41 Including module_utils file ansible/module_utils/common/validation.py
01:41 Including module_utils file ansible/module_utils/common/warnings.py
01:41 Including module_utils file ansible/module_utils/compat/selectors.py
01:41 Including …
```
=> Temporarily disable copr tests

plugins/modules/redhat_subscription.py
Do not mention an explicit version of Satellite for an environment to use; future versions of Satellite will support that, and older versions are long EOL.
Also mention Katello next to Red Hat Satellite.
Fixes #4152
=> redhat_subscription: improve wording wrt Satellite

changelogs/fragments/5550-java_certs-not-enough-info-on-error.yml, plugins/modules/java_cert.py
Just bumped into an issue when the message was `"Internal module failure, cannot extract public certificate from pkcs12, error: "` and found it not really helpfull.
java_certs
Seems that the issue #2560 doesn't cover all cases, so to make debugging easier, I propose to add error output on json return instead of only expose standard output.
=> java_certs : Not enough info on error

changelogs/fragments/5601-unixy-callback-use-config-manager.yml, plugins/callback/unixy.py
Start using Ansible's config manager in the unixy Callback plugin.
Fixes #5600
`unixy`
=> unixy Callback: Use Ansible's config manager

changelogs/fragments/5583-redhat_subscription-subscribe-parameters.yaml, plugins/modules/redhat_subscription.py, tests/unit/plugins/modules/test_redhat_subscription.py
Stop passing all the `rhsm_`, and `server_` module arguments to `Rhsm.register()`, and thus as arguments for `subscription-manager register`:
- right before calling `Rhsm.register()`, `Rhsm.configure()` is called to configure subscription-manager with all the `rhsm_`, and `server_` arguments; hence, they are already configured
- the passed argument to `--serverurl` is partially wrong: `Rhsm.register()` passes only the hostname, whereas the other bits (port and prefix) are supported too; this "works" because port and prefix were already configured previously, and the lax parsing that subscription-manager does allows for missing bits
- the parsing done by subscription-manager for `--baseurl` strips out the URL scheme and always uses https: this means that specifying `rhsm_baseurl: …
=> redhat_subscription: drop unneeded args to `Rhsm.register()`

changelogs/fragments/5627-redhat_subscription-subscribe-parameters-2.yaml, plugins/modules/redhat_subscription.py
From the man-pages of subscription-manager, none of the parameters used is tied to `activationkey` except the two that remain in its else-clause.
Per the documentation, none of these should be tied to `activationkey`, and as such, no correct usage of the module per its documentation should be affected in a negative way.
Fixes #3486.
Notes by Pino Toscano (@ptoscano):
In reality, there are some combinations of command line options to `register` that are not accepted -- for example, when using `--activationkey` you cannot specify `--consumerid`, `--environment`, and `--auto-attach`; that said, since these things may change depending on the version of subscription-manager, then simply passing all the arguments and let subscription-manager figure it out is better than having to reimplement …
=> redhat_subscription: don't discard vars with key

changelogs/fragments/5628-fix-vmadm-off-by-one.yml, plugins/modules/vmadm.py
Method get_vm_uuid from vmadm  off-by-one error. 
vmadm
When running a playbook using the vmadm module results in:
```bash
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: Replacement index 1 out of range for positional args tuple
fatal: [192.168.1.111]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.1.111 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1669747224.152739-62818-126536782663630/AnsiballZ_vmadm.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1669747224.152739-62818-126536782663630/AnsiballZ_vmadm.py\", line 99, in _ansiballz_main\r\n …
```
=> Fix for vmadm get_vm_uuid out of range

changelogs/fragments/5632-vdo-Use-yaml-safe-load-instead-of-yaml-load.yml, plugins/modules/vdo.py
yaml.load() without specifying a Loader= is deprecated and unsafe.
For details, see
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
Fixes #5631 
vdo
=> vdo: Use yaml.safe_load() instead of yaml.load()

plugins/modules/keycloak_realm.py
Add `realm` option in `keycloak_realm` minimal example. Without this option, Keycloak (v20.0.1 at least) fail with a 500 error : 
```
2022-12-01 09:37:13,198 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-77) Uncaught server error: java.lang.NullPointerException
at org.keycloak.services.managers.RealmManager.determineDefaultRoleName(RealmManager.java:624)
at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:531)
at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:503)
at org.keycloak.services.managers.RealmManagerProviderFactory.lambda$postInit$0(RealmManagerProviderFactory.java:51)
at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:92)
at …
```
=> Fix example in keycloak_realm documentation

changelogs/fragments/5640-fix-typo-proxmox-inventory.yml, plugins/inventory/proxmox.py
Resolve issue with lookups in proxmox inventory config.
proxmox
```paste below
$ ansible-inventory -i my.proxmox.yml --graph
[WARNING]:  * Failed to parse /home/ansible/infrastructure/my.proxmox.yml with auto plugin: template() got an unexpected keyword argument 'disable_looups'
[WARNING]:  * Failed to parse /home/ansible/infrastructure/my.proxmox.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /home/ansible/infrastructure/my.proxmox.yml with ini plugin: Invalid host pattern '---' supplied, '---' is normally a sign this is a YAML file.
[WARNING]:  * Failed to parse /home/ansible/infrastructure/my.proxmox.yml with ansible_collections.community.general.plugins.inventory.proxmox plugin: template() got an unexpected …
```
=> fix typo disable_looups in inventory/proxmox

tests/integration/targets/copr/aliases, tests/integration/targets/copr/tasks/main.yml, tests/integration/targets/copr/vars/main.yml
- Switch to a new test Copr repository. @copr/integration_tests was removed which caused the tests to fail. I created a new one under my account that I'll ensure stays around.
- Add basic testing to ensure that repo files are created in the correct location and contain the correct baseurl and enabled status.
- Also run tests on Enterprise Linux.
- Test that packages from the Copr install.
Resolves: https://github.com/ansible-collections/community.general/issues/5595
copr
=> Reenable and enhance `copr` integration tests

changelogs/fragments/5602-proxmox-tags.yml, plugins/inventory/proxmox.py
Starting from Proxmox 7.3 tags are delimited by semicolon. For backward compatibility it needs to be splitted by both commas and semicolons.
Replaced commas to semicolons in the tags string, then delimited by semicolons.
```paste below
```
=> Updated tags delimiter

changelogs/fragments/5605-ssh-config-add-host-key-algorithms.yaml, plugins/modules/ssh_config.py, tests/integration/targets/ssh_config/tasks/options.yml
`host_key_algorithms` option for ssh_config module
ssh_config
Example ad hoc execution:
```bash
ansible localhost --connection=local -a \
"host=example.com ssh_config_file=/tmp/ssh_config remote_user=mariusz host_key_algorithms=+ssh-rsa" \
-m community.general.ssh_config
```
Result (content of `/tmp/ssh_config`):
```
Host example.com
user mariusz
hostkeyalgorithms +ssh-rsa
```
=> feat(ssh_config): host_key_algorithms option

changelogs/fragments/5619-keycloak-improvements.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_client_rolemapping.py
- community.general.keycloak_client_rolemapping with `state: absent` removes all
roles. The intention is to only remove those listed. 
- The diff returned by the module has a `before` and `after` list. The latter contained the 
changed roles, instead of the roles after the change.
community.general.keycloak_client_rolemapping
Fix these two issues.
=> Fix keycloak_client_rolemapping role removal and diff

tests/integration/targets/pipx_info/tasks/main.yml
They curently fail, probably since tox 4.0.2 has been released.
pipx_info tests
=> Fix pipx_info tests

changelogs/fragments/5662-redhat_subscription-server_proxy_scheme.yaml, plugins/modules/redhat_subscription.py, tests/unit/plugins/modules/test_redhat_subscription.py
Add the `server_proxy_scheme` parameter to configure the scheme used for the proxy server. This completes the configuration parameters for the proxy server.
This makes it possible to configure an https proxy server for `subscription-manager` using the `redhat_subscription` module, instead of doing it manually -- for example
```yaml
- redhat_subscription:
server_proxy_hostname: my-proxy-server
server_proxy_scheme: https
server_proxy_port: proxy-port
...
```
=> redhat_subscription: add `server_proxy_scheme` parameter

.azure-pipelines/azure-pipelines.yml
Bump CentOS Stream 8 Python from 3.8 to 3.9.
CI
=> CI: Bump CentOS Stream 8 Python from 3.8 to 3.9

changelogs/fragments/5659-fix-lxc_container-command.yml, plugins/modules/lxc_container.py
lxc_container fails when executing the lxc command (e.g. when creating a new container) because PR #5358 broke the module argument parsing. The resulting argument dict contained only the module argument name and the argument flag but not the value. E.g.
```
- lxc_container:
template: debian
```
would result in the lxc command:
* `lxc template --template` (current result)
* `lxc --template debian` (while this is the correct line)
Fixes: 6f88426cf1dc ("lxc_container: minor refactor (#5358)")
Fixes #5578
CC: @russoz
lxc_container
To reproduce the issue create a container which doesn't exist before:
```
- name: Create a started container
community.general.lxc_container:
name: some
state: started
template: template
template_options: --dist debian --release bullseye --arch …
```
=> lxc_container: fix lxc argument when executing lxc command

plugins/modules/github_release.py
As the title says, the docs were incorrect so I fixed it.
`github_release`
N/A
=> Fixed `github_release` docs: only module-specific returned key is `tag`

changelogs/fragments/5672-proxmox.yml, plugins/modules/proxmox_disk.py, plugins/modules/proxmox_nic.py
Removed redundant VMID parameter from URI builder from all functions in `proxmox_disk` and `proxmox_nic` modules.
It fixes possible issues similar to #5492.
proxmox_disk
proxmox_nic
Conversation about this fix [was here](https://github.com/ansible-collections/community.general/pull/5493#issuecomment-1312785424).
Modified functions have been tested with:
- Controller: openSUSE Tumbleweed (python 3.10)
- Target: Proxmox 7.3-3
- Ansible:
- core 2.14.1
- community-general 6.1.0
- Proxmoxer: 2.0.0
- Requests: 2.28.1
=> Bugfix: Remove redundant VMID parameters

changelogs/fragments/5705-opkg-fix-force-reinstall.yml, plugins/modules/opkg.py
opkg: fix issue that force=reinstall would not reinstall an existing package
- opkg
Tested with opkg 0.4.2 on NI Linux Real-Time 8.8
Bug noticed while working on #5688
=> opkg: fix issue that force=reinstall would not reinstall an existing package

changelogs/fragments/5703-sudoers-host-support.yml, plugins/modules/sudoers.py, tests/integration/targets/sudoers/tasks/main.yml
Implementation of my feature request: Fixes #5702 
sudoers
Adds ability to set host-based restrictions on privilege escalation managed via sudoers modules. Default behaviour (via default value to new parameter) maintains current behaviour of using the magic `ALL` value (i.e. no restriction).
=> Add support for host restriction in sudoers module

changelogs/fragments/5680-ansible_galaxy_install-fx-locale.yaml, plugins/modules/ansible_galaxy_install.py, tests/integration/targets/ansible_galaxy_install/aliases, tests/integration/targets/ansible_galaxy_install/tasks/main.yml
Tries to use locale `C.UTF-8`, if that fails then fall back to `en_US.UTF-8`.
Fixes #5661 
=> ansible_galaxy_install: use locale C tentatively, else en_US

changelogs/fragments/5688-opkg-module-install-certain-version.yml, plugins/modules/opkg.py
This extends the community.general.opkg module. It additionally allows to install a package in a certain version.
Tested with opkg 0.4.2 on NI Linux Real-Time 8.8
community.general.opkg module
opkg module: allow NAME=VERSION syntax to install a package in a certain version
example:
```
- name: Install foo in version 1.2
community.general.opkg:
name: foo=1.2
state: present
```
=> opkg module: allow installing a package in a certain version 

changelogs/fragments/5727-manageiq-tags-deprecate-list-state.yaml, plugins/modules/manageiq_tags.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Deprecate state "list" in favour of using manageiq_tags_info.
plugins/modules/manageiq_tags.py
=> manageiq_tags: deprecate list state

plugins/inventory/lxd.py
if field `project` exists in `lxd.yml`, the instances are searched in the given LXD project. if project field is not defined the default project named `default` will be used.
Signed-off-by: omani <3346207+omani@users.noreply.github.com>
plugins/inventory/lxd.py
Fixes #5657
=> Feature: Provide project field for LXD inventory plugin

changelogs/fragments/5714-proxmox-lxc-tag-support.yml, plugins/modules/proxmox.py
Added tag support for proxmox containers in PVE 7, to achieve feature parity with VMs which support tags since PVE6. Fixes #5471 
proxmox.py
I've restricted the tags feature to PVE 7, because I'm not sure if the original bug preventing tags in containers - from [proxmox forum](https://forum.proxmox.com/threads/api-parse-errors-when-lxc-tags-are-null.85197/) - has been fixed, and if yes, in which proxmox 6 version it has been fixed.
I've used the code from `proxmox_kvm.py`, so the tag separator is still a `,`. It's not an issue because on PVE 7.0-7.2, `,` is the correct separator, and on pve 7.3, it's automatically changed (by proxmox) to a `;` (and proxmox inventory plugin support both separator, see #5602)
=> feat: add tags to proxmox containers

changelogs/fragments/5744-unixy-callback-fix-config-manager-typo.yml, plugins/callback/unixy.py
Fixes typo introduced in 53da86c, thus
Fixes #5600 (again).
`unixy`
In https://github.com/ansible-collections/community.general/pull/5601#discussion_r1058867612 it was realized that the patch contained a typo.  This gets corrected with this PR.
Does it require another changelog fragment, or is it sufficient to have [changelogs/fragments/5601-unixy-callback-use-config-manager.yml](https://github.com/ansible-collections/community.general/blob/main/changelogs/fragments/5601-unixy-callback-use-config-manager.yml) ?
=> unixy Callback: Fix typo using ansibles config manager

plugins/modules/htpasswd.py
Users who are not already familiar with passlib would need to do considerable research to get the `htpasswd` module to work with anything better than the default MD5 crypto scheme. The current module documentation makes it seem like there are only obsolete options such as MD5, DES that would be compatible with Apache.  
This is not the case and passlib also provides specific meta schemes for Apache htpasswd.
With MD5, DES being so obsolete, this change makes it much easier to change to more secure schemes:
- Document the existence of passlib Apache-specific meta schemes, I chose `portable_apache22` and `host_apache24` as examples.
- Mention that supported schemes vary per passlib version and installed dependencies.
- Add link to passlib RTD site that describes the various schemes for …
=> htpasswd: improve documentation on crypt_scheme

changelogs/fragments/5761-callback-types.yml, plugins/callback/loganalytics.py, plugins/callback/logdna.py, plugins/callback/logstash.py, plugins/callback/splunk.py, plugins/callback/sumologic.py, plugins/callback/syslog_json.py
Some callback plugins were incorrectly classified as aggregate, even though they should be notification callbacks. (See https://docs.ansible.com/ansible/devel/plugins/callback.html#callback-plugins.)
loganalytics
logdna
logstash
splunk
sumologic
syslog_json
=> Fix callback plugin types

changelogs/fragments/5725-redhat_subscription-add-red-hat-api-token.yml, plugins/modules/redhat_subscription.py, tests/unit/plugins/modules/test_redhat_subscription.py
Add support using Red Hat API token
Updated redhat_subscription.py to allow using Red Hat API token.
Added support for using Red Hat API token in addition to activationkey/org ID or username/password combination.
Following this to generate an access token from the offline token.
https://access.redhat.com/articles/3626371
=> redhat_subscription: Add support for Red Hat API token

plugins/modules/consul.py
Minor fixes in docs.
plugins/modules/consul.py
=> consul: minor fixes in docs

changelogs/fragments/5773-snap-mh-execute.yml, plugins/modules/snap.py
Use `ModuleHelper.execute()` method to run module.
plugins/modules/snap.py
=> snap: use MH execute() static method

changelogs/fragments/5735-terraform-init-fix-when-default-workspace-doesnt-exists.yaml, plugins/modules/terraform.py
If the terraform config stores its state on a remote backend, it's possible that there are multiple workspaces to choose from. At the same time, remote backends (e.g. Terraform Cloud) are not required to store a `default` workspace, but one can name and create workspaces as s:he wishes. This is where the Ansible Terraform module has a problem.
**Line 331**: The `terraform init` is called but expects the `default` workspace to exist. Consequently, it should ask you which of the available workspaces you want to choose (which happens if you do `terraform init` from the CLI) - but that obviously doesn't happen in the Ansible (non-interactive) workflow since the `-input=false` flag is appended to the `terraform init` command. 
To "avoid" being prompted to choose the workspace and a consequent …
=> terraform: bugfix: init command when default workspace doesn't exists

changelogs/fragments/5694-add-custom-fields-to-bitwarden.yml, plugins/lookup/bitwarden.py
Currently the Bitwarden lookup plugin only searches for fields in the login key (password, passwordRevisionDate, totp, urs, username). It is not uncommon to create custom fields in Bitwarden, for things such as api keys, which we should also be able to look up. I tried to make the lookup work seamlessly across custom or standard fields, so it does not add complexity for the user.
bitwarden
Example code :
```yaml
- debug:
msg: |
Full record: {{ lookup('community.general.bitwarden', 'MI6 Secrets') | first | to_nice_yaml }}
Username: {{ lookup('community.general.bitwarden', 'MI6 Secrets', field="username") | first }}
Password: {{ lookup('community.general.bitwarden', 'MI6 Secrets', field="password") | first }}
Custom Field (pin_code): {{ …
```
=> Add Support to Bitwarden Lookup for Custom Fields

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/one_host/aliases, tests/integration/targets/one_template/aliases
They are needed for two integration test targets, both of them currently disabled. So avoid wasting CI cycles on these.
CI
=> Remove currently unneeded generic tests from CI

changelogs/fragments/5485-snap-alias-cmd-runner.yml, changelogs/fragments/5486-snap-alias-cmd-runner.yml, plugins/modules/snap_alias.py
snap_alias now using `CmdRunner` instead of `CmdModuleHelper`
plugins/modules/snap_alias.py
=> snap_alias: using CmdRunner

changelogs/fragments/5718-opkg-refactor.yaml, plugins/modules/opkg.py, tests/unit/plugins/modules/test_opkg.py
Refactor the module to use StateModuleHelper and CmdRunner. As a side effect, running opkg is now passing parameters in a safer way.
plugins/modules/opkg.py
=> opkg: refactor module to use StateModuleHelper and CmdRunner

plugins/modules/opkg.py
The documentation did not yet state that this module also works for opkg on OpenEmbedded/Yocto based Linux distributions.
The review of PR #5718 showed that there are differences between OpenWrt and Yocto based Linux distributions, e.g. the `PACKAGE=VERSION` syntax is working for Yocto based Linux distributions but not for OpenWrt.
- opkg
- opkg from OpenWrt is maintained here: https://git.openwrt.org/project/opkg-lede.git
- opkg from Yocto is maintained here: https://git.yoctoproject.org/opkg/
- The commit which added the `PACKAGE=VERSION` syntax is this one: [9da784d](https://git.yoctoproject.org/opkg/commit/?id=9da784d5508157cb327d53eb9abcf54e9926a5a5) -> part of release [0.3.2](https://git.yoctoproject.org/opkg/log/?h=v0.3.2)
- The [opkg …
=> opkg: extend docu about compatibilty with OpenWrt vs. Yocto based Linux distribitions

changelogs/fragments/5706-add-builds-forks-container-registry.yml, plugins/modules/gitlab_project.py
Fixes #5691
Added support for `gitlab forking_access_level`, `builds_access_level` and `container_registry_access_level` fields (see [gitlab api rest](https://docs.gitlab.com/ee/api/projects.html#create-project) for detail of these fields).
gitlab_project
Example of project creation using the new fields:
```yaml
- name: Setup gitlab project
community.general.gitlab_project:
api_url: https://gitlab.example.com/
validate_certs: true
api_username: dj-wasabi
api_password: "MySecretPassword"
name: my_project
group: ansible
builds: disabled
container_registry: disabled
forks: disabled
state: present
```
=> Fixes #5691. Support gitlab forking_access_level, builds_access_level and container_registry_access_level fields

changelogs/fragments/5772-consul-deprecate-params-when-absent.yml, plugins/modules/consul.py
Deprecate using parameters unused for state=absent.
plugins/modules/consul.py
=> consul: deprecate params incompatible with state=absent

changelogs/fragments/5793-apache2-module-npm-warnings.yml, plugins/modules/apache2_module.py, tests/integration/targets/apache2_module/tasks/635-apache2-misleading-warning.yml, tests/integration/targets/apache2_module/tasks/actualtest.yml, tests/integration/targets/apache2_module/tasks/main.yml
Fixes https://github.com/ansible-collections/community.general/issues/635
apache2_module
=> apache2_module generates false/misleading warning

changelogs/fragments/5843-terraform-validate-no-color.yml, plugins/modules/terraform.py
When terraform validation step failed, ansible produced output with ANSI escape codes due to missing `-no-color` argument
Fixes #5816 
terraform
Before: 
```paste below
{..., "msg": "\u001b[31m╷\u001b[0m\u001b[0m\n\u001b[31m│\u001b[0m \u001b[0m\u001b[1m\u001b[31mError: ...
```
After: 
```paste below
{..., "msg": "\nError: ...
```
=> Add -no-color argument to terraform validation

changelogs/fragments/5818-nsupdate-fix-zone-lookup.yml, plugins/modules/nsupdate.py
The SOA record for an existing zone is returned as an answer RR and not as an authority RR. It is returned as an authority for subdomains of a zone.
```
$ dig -t SOA example.com
;; ANSWER SECTION:
example.com.	3530	IN	SOA	ns.icann.org. noc.dns.icann.org. 2022091184 7200 3600 1209600 3600
```
```
$ dig -t SOA www.example.com
;; AUTHORITY SECTION:
example.com.	3600	IN	SOA	ns.icann.org. noc.dns.icann.org. 2022091184 7200 3600 1209600 3600
```
Fixes issue  #5817
nsupdate
=> nsupdate: fix zone lookup

changelogs/fragments/5804-minor-changes-to-hpe-ilo-collection.yml, plugins/module_utils/ilo_redfish_utils.py, plugins/modules/ilo_redfish_config.py
Minor changes in implementation of DNS and SNTP update.
Files changed - 
ilo_redfish_config.py
ilo_redfish_utils.py
=> Minor changes to HPE iLO collection

changelogs/fragments/5844-iptables-state-refactor.yml, plugins/modules/iptables_state.py
Minor pythonifications.
plugins/modules/iptables_state.py
=> iptables_state: minor pythonisms

plugins/modules/pipx.py, plugins/modules/pipx_info.py, tests/integration/targets/pipx/tasks/main.yml
Adds a testcase to demonstrate how the `pipx` module can be used with the environment variables `PIPX_*`, specifically for  site-wide installation.
Fixes #5813 
pipx
pipx_info
=> pipx: add testcase w/ env vars PIPX_xxxx

plugins/module_utils/scaleway.py
Removing it in #5497 triggered a pylint bug. This tries to at least make it private.
scaleway module utils
=> scaleway module utils: make function private that should be removed

tests/integration/targets/ssh_config/tasks/main.yml
Hopefully unbreaks CI on Fedora 33.
CI
=> stormssh tests: do not install newer cryptography

changelogs/fragments/5750-bugfixing-keycloak-usrfed-fail-when-update-default-mapper-simultaneously.yml, plugins/modules/keycloak_user_federation.py, tests/integration/targets/keycloak_user_federation/tasks/main.yml
Current implementation of `keycloak_user_federation` module fails to create a new user federation when also simultaneously updating / changing a default / standard created mapper like `username`.
The cause of this as can be seen in the diffs is simply a variable set to `None` on default forgotten to be updated to proper id value.
It seems there are currently no open issues matching this bug or at least I failed to find them.
Tested with recent keycloak (api) version: `20.0.2`.
=> bugfixing keycloak user federation failing when updating default mapper simultaneously

changelogs/fragments/5811-clarify-bitwarden-error.yml, plugins/lookup/bitwarden.py, tests/unit/plugins/lookup/test_bitwarden.py
The Error message of the Bitwarden lookup-plugin is not conclusive of what actually is the Error.
This PR adresses the issue, and tells the user to unlock the vault, instead of logging in. (Just logging in, still results in the error, because the vault is not unlocked)
bitwarden lookup plugin
You can be logged into the Bitwarden-CLI, but it will still be locked. This took me several hours to debug, since every time I ran 'bw login' it told me, that I am already logged in. If you run 'bw unlock' without being logged in, you are prompted to log in.  This clarifies the Error occurring and can drastically reduce debugging time, since you don't have to look into the source code to get an understanding of whats wrong.
=> Clarify Error message when bitwarden vault not unlocked

changelogs/fragments/5803-proxmox-read-timeout.yml, plugins/modules/proxmox_disk.py
Use asynchronous `post()` API call for _create_ actions instead of synchronous `get()`.
Fixes #5753 .
proxmox_disk
There is no user friendly method to control `requests` _timeout_ parameter from Ansible Playbook, so synchronous `get()` API call returns "read timeout" after default amount of time (it is 5 seconds now and it was enough for my servers to copy 300MB between storages).
Now the `proxmox_disk` module uses asyncronous calls and waits for tasks to finish (or reach timeout which can be controlled by the user).
Documentation has also been updated.
=> Bugfix: proxmox_disk - read time out on import

changelogs/fragments/5822-gem-uninstall-force.yml, plugins/modules/gem.py
Allow to use the `--force` flag when uninstalling gems. This is useful because when there are dependencies the gem binary will interactively ask for user confirmation and Ansible will hang forever.
Fixes #5821
gem
As can be seen on the picture below, `gem uninstall` implements the `--force` flag.
=> Gem: Support force flag when uninstalling

changelogs/fragments/5851-lookup-bitwarden-add-filter-by-collection-id-parameter.yml, plugins/lookup/bitwarden.py, tests/unit/plugins/lookup/test_bitwarden.py
Allow user to filter search results from bit warden by collection id. If collection id is not provided, bit warden cli will not use any filtering
=> Add support to Bitwarden Lookup for filtering results by collection (#5849)

changelogs/fragments/5812-implement-updateconf-api-call.yml, plugins/module_utils/opennebula.py, plugins/modules/one_vm.py, tests/unit/plugins/module_utils/test_opennebula.py, tests/unit/plugins/modules/test_one_vm.py
OpenNebula provides the [one.vm.updateconf](https://docs.opennebula.io/6.4/integration_and_development/system_interfaces/api.html#one-vm-updateconf) API call, that can be used to modify the [context of a VM](https://docs.opennebula.io/6.6/management_and_operations/references/template.html#context-section). For example `SSH_PUBLIC_KEY`, `PASSWORD` or even `START_SCRIPT` variables can be set. This PR implements exactly that, it allows for updating running VMs and setting the same parameters for freshly created ones. We believe this can prove useful for some users.
one_vm module
NA
=> OpenNebula/one_vm implement the one.vm.updateconf API call

changelogs/fragments/5897-ipa_group-add-external-users.yml, plugins/modules/ipa_group.py
ipa_group module allows declaring a group as external but doesn't allow adding external members. This pull request implements adding 
ipa_group
=> add external user support to ipa_group module

changelogs/fragments/5914-dig-dnskey.yml, plugins/lookup/dig.py
With dnspython 2.0.0+, `algorithm` of DNSKEY rdata is an enum type and no longer an int. Explicitly converting it to `int` makes sure that it is an integer.
Try `ansible localhost -m debug -a 'msg={{ q("dig", "com", qtype="DNSKEY", flat=0) }}'` with and without this PR, then you get
```
"msg": [
{
"algorithm": 8,
"class": "IN",
"flags": 257,
"key": "AQPDzldNmMvZFX4NcNJ0uEnKDg7tmv/F3MyQR0lpBmVcNcsIszxNFxsBfKNW9JYCYqpik8366LE7VbIcNRzfp2h9OO8HRl+H+E08zauK8k7evWEmu/6od+2boggPoiEfGNyvNPaSI7FOIroDsnw/taggzHRX1Z7SOiOiPWPNIwSUyWOZ79VmcQ1GLkC6NlYvG3HwYmynQv6oFwGv/KELSw7ZSdrbTQ0HXvZbqMUI7BaMskmvgm1G7oKZ1YiF7O9ioVNc0+7ASbqmZN7Z98EGU/Qh2K/BgUe8Hs0XVcdPKrtyYnoQHd2ynKPcMMlTEih2/2HDHjRPJ2aywIpKNnv4oPo/",
"owner": "com.",
"protocol": 3,
"ttl": 86362,
"type": "DNSKEY"
},
{
"algorithm": 8,
"class": "IN", …
```
=> dig lookup: fix DNSKEY's algorithm handling

changelogs/fragments/5913-dig-caa.yml, plugins/lookup/dig.py
I borrowed some code from the dig lookup in https://github.com/ansible-collections/community.dns/pull/133 and noticed that CAA records aren't supported by the dig lookup yet.
Since this is easy to fix, here we go :)
dig lookup plugin
=> dig lookup: support CAA record type

changelogs/fragments/5883-sudoers-add-support-for-setenv-parameter.yml, plugins/modules/sudoers.py, tests/integration/targets/sudoers/tasks/main.yml
During the configuration of sudo rights regarding a Python app I created, I needed to allow my user to keep their environments variables while running it. This can be done by using `sudo -E [command to run]`. 
To allow this in our sudoers files we need to pass a parameters. However while the sudoers modules allowed to pass nopasswd, it did not allowed to pass the `setenv` parameters. This PR aims to allow it. 
```
minor_changes:
- sudoers - add `setenv` parameters to support passing environments variables via sudo.
```
sudoers
```
%mygroup ALL=NOPASSWD:SETENV: /usr/local/bin/testing
```
=> Add support for setenv parameters

changelogs/fragments/5907-fix-gitlab_runner-not-idempotent.yml, plugins/modules/gitlab_runner.py
This fix introduces the new boolean option ``access_level_on_creation``. It controls, whether the value of ``access_level`` is used for runner registration or not. The option ``access_level`` has been ignored on registration so far and was only used on updates. The user is informed by a deprecation warning, if the option is unspecified. For reasons of compatibility ``false`` is assumed in that case. The option ``access_level_on_creation`` will switch to ``true`` in community.general 7.0.0.
Signed-off-by: Christoph Fiehe <c.fiehe@eurodata.de>
gitlab_runner
=> Fixes #5907: gitlab_runner is not idempotent on first run after runner creation

changelogs/fragments/5886-redfish-correct-basic-auth-usage-on-session-creation.yml, plugins/module_utils/redfish_utils.py
Redfish services do not expect authorization headers when performing a POST to the session collection. The expectation is credentials are in the request body. While the specification is silent on how services behave when authorization headers are present in this request, the guidance for clients is to not provide the header.
The change here removes the authorization header on two conditions:
* When performing a GET on the service root (/redfish/v1/): this is an unauthenticated resource and is used for discovery prior to logging into the system.
* When performing a POST on the session collection (/redfish/v1/SessionService/Sessions).
Fix #5886 
redfish_utils
On some systems, using the Redfish command "CreateSessions" will result in an error (as shown in #5886). …
=> Redfish: Removed basic auth header when performing a GET on the service root and POST to the session collection

changelogs/fragments/5933-linting.yml, plugins/modules/gconftool2.py, plugins/modules/pritunl_org.py, plugins/modules/pritunl_org_info.py, plugins/modules/pritunl_user.py, plugins/modules/pritunl_user_info.py, plugins/modules/terraform.py, plugins/modules/timezone.py, plugins/modules/xfconf.py
ansible-core devel's ansible-test is using a newer pylint, which makes CI fail. This fixes the problems it exposes.
CI
=> Fix pylint errors

changelogs/fragments/5925-align_gitlab_runner_access_level_default_with_gitlab.yml, plugins/modules/gitlab_runner.py
In order to align the module with GitLab's runner API, the option ``access_level`` will lose its default value in community.general 8.0.0. From that version on, you have set this option to ``ref_protected`` explicitly, if you want to have a protected runner, otherwise GitLab's default access level gets applied, which is ``not_protected``.
Because changing the default value requires a longer deprecation period, a deprecation message was added, that informs the user about the future change regarding module's behavior.
Signed-off-by: Christoph Fiehe <c.fiehe@eurodata.de>
gitlab_runner
=> Align 'gitlab_runner' with GitLab's default access level.

changelogs/fragments/5915-suppress-urllib3-insecure-request-warnings.yml, plugins/inventory/proxmox.py
It's clear that the user would know the possible risk when he or she chose to turn off the option, so the warning message could be ignored and make the output clean.
`community.general.proxmox`
=> Suppress urllib3 InsecureRequestWarnings when `validate_certs` option is false

.github/BOTMETA.yml
Ref: https://github.com/ansible-collections/community.general/issues/5823#issuecomment-1386718799
@skornehl if you still want to step down as a maintainer for datadog_monitor, please approve this PR.
In any case, thanks again for creating and maintaining this module for all this time! :)
BOTMETA.yml
=> Remove skornehl as maintainer for datadog_monitor

changelogs/fragments/5829-fix-yarn-global.yml, changelogs/fragments/5829-fix-yarn-latest.yml, plugins/modules/yarn.py, tests/integration/targets/yarn/tasks/run.yml, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Fixes #5712.
* Updates `_exec` to support running Yarn commands that wouldn't ordinarily be available with `yarn global` by setting the working directory to the path from `yarn global dir` instead.
* Updates `list_outdated` to use this new functionality when invoking `yarn outdated`.
* Updates `list_outdated` to check for actual errors in stderr output instead of failing on the presence of anything in stderr. This is b/c the Yarn global package.json has no license field, causing a warning to be logged to stderr when invoking `yarn outdated` in that directory.
Through testing, found a couple more related bugs to fix (see comments below):
* Replaces the hardcoded `DEFAULT_GLOBAL_INSTALLATION_PATH` with code to check the output of `yarn global dir`, as the default path may be different when …
=> yarn: Fix state=latest not working with global=true

changelogs/fragments/5927-set-user-agent-dnsimple.yml, plugins/modules/dnsimple.py
At present the default user agent is used in API requests: `dnsimple-python/*`. This makes it impossible for us at DNSimple to identify active community projects that are using our API, and how to best support them.
With this PR the user agent is changed to: `ansible dnsimple-python/*` which serves to both identify API usage from the project and also give us debugging data to assist with customer support requests.
`dnsimple`
=> Set User-Agent for API requests to DNSimple

.github/BOTMETA.yml, changelogs/fragments/5900-adding-verifybiosattribute-fucntionality-to-redfish-command.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_command.py
SUMMARY
Adding functionality to verify user provided BIOS attributes with those on the server.
ISSUE TYPE
COMPONENT NAME
=> Adding VerifyBiosAttributes functionality

changelogs/fragments/5899-adding-enablesecureboot-functionality-to-redfish-config.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_config.py
SUMMARY
Adding functionality to enable SecureBoot on a server.
ISSUE TYPE
COMPONENT NAME
=> Adding EnableSecureBoot functionality

.azure-pipelines/azure-pipelines.yml
Until https://github.com/ansible-community/images/pull/40 and https://github.com/systemd/systemd/issues/26474 are resolved.
The 'soft' option #6012 does not work, so I guess we have to take the hard option and disable the Arch Linux tests until things are resolved... :(
CI
=> Disable Arch Linux tests for now

changelogs/fragments/5866-lxd_container-diff-and-check-mode.yml, plugins/modules/lxd_container.py, plugins/modules/lxd_profile.py
lxd_container
Adds check-mode and diff-mode support to the `lxd_container` module.
Cherry-picked and rebased from an older MR of mine.
```diff
--- before
+++ after
@@ -9,7 +9,7 @@
"image.serial": "20230117_05:24",
"image.type": "squashfs",
"image.variant": "cloud",
-            "limits.memory": "3GB"
+            "limits.memory": "30GB"
},
"devices": {
"httpfwd": {
changed: [lxd-test]
```
=> `lxd_container`: add check- and diff-mode support

plugins/modules/iptables_state.py, plugins/modules/shutdown.py
This docs PR adds basic attributes (`check_mode` and `diff_mode`) and some extended attributes (`action` and `async`) to modules that come with action plugins.
various
=> Add attributes for modules with action plugin

changelogs/fragments/5942-onepassword-ignore-errors-from-op-account-get.yml, plugins/lookup/onepassword.py
When using the onepassword lookup plugin, part of the flow is to determine if you are signed in.  This is performed in an api version specific function called assert_logged_in() documented as "Check whether a login session exists" which uses the command `op account get`.  When you are not in fact signed in, this cli can return an error which is currently not ignored and can cause the lookup plugin to fail at that point rather than correctly returning the status to indicate that you are not signed in and proceed to signin using the parameters passed for that purpose.
This change passes the `ignore_errors=True` parameter to the _run function so that the return code can be used to indicate you are not signed in when an error occurs.
changelog fragment
bugfixes:
- onepassword - Changed to …
=> onepassword: ignore errors from "op account get"

changelogs/fragments/5431-nmcli-wifi.yml, plugins/modules/nmcli.py
nmcli
There are two commits in this PR, both of which are necessary to make wifi.wake-on-wlan settings work properly with this module, and one of which is necessary to make any wifi.* setting work properly. See the descriptions of the fixes in the individual commits.
=> nmcli: two fixes needed to make wifi.wake-on-wlan settings work properly

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml, README.md, tests/utils/shippable/shippable.sh
community.crypto and community.docker are having this one for some time now. Since  is coming up, we also need this for community.general.
The main disadvantage of GHA over AZP is that these tests won't run automatically for new contributors. This requires maintainer interaction. Fortunately most things are already covered with the non-EOL ansible-core tests, so this shouldn't be too problematic.
CI
=> Run tests with EOL ansible-core versions in GHA

changelogs/fragments/5615-zypper-transactional-update.yml, plugins/modules/zypper.py
Added condition to check for `/usr/sbin/transactional-update` binary, which is the way to go for openSUSE MicroOS.
Fixes #5615
plugins/modules/zypper.py
=> Added support for openSUSE MicroOS

changelogs/fragments/5863-providerType-defaulted-keycloak_userfed-mappers.yml, plugins/modules/keycloak_user_federation.py
So called "mappers" which are special subcomponents of keycloak user federations (used to manage how ldap groups/users are mapped to keycloak groups/users) have the following json structure:
```
{
"name": "...",
"providerId": "...",
"providerType": "...",
"config": {
[...]
}
}
```
From this fields the one called `providerType` has nearly always the value `org.keycloak.storage.ldap.mappers.LDAPStorageMapper`, according to current docu it is actually the only supported value here (which is a bit weird, more on this in the additional section), so it would make sense to make it a default.
Besides proposing to set a default for `providerType` I also removed the part of its docu which says the new default value is the only supported one. I would argue …
=> providerType should be defaulted for keycloak_user_federation mappers

changelogs/fragments/6011-osx-defaults-errors.yml, plugins/modules/osx_defaults.py
Previously `community.general.osx_defaults` included the stdout in error messages when `defaults` returned a non-zero exit code. This was usually blank and not helpful. This PR changes it to include the stderr.
osx_defaults
Example:
This task results in an error without `become: true`
```yaml
- name: "Disable Automatic Quote Substitution"
community.general.osx_defaults:
state: present
domain: NSGlobalDomain
key: "NSAutomaticQuoteSubstitutionEnabled"
type: bool
value: false
```
Before: no helpful information is included in the error:
```
fatal: [host]: FAILED! => {"changed": false, "msg": "An error occurred while writing value to defaults: "}
```
After: stderr is included in the error
```
TASK [Disable Automatic Quote Substitution] …
```
=> community.general.osx_defaults: Include stderr in error messages

changelogs/fragments/6048-nmcli-addres-order.yml, plugins/modules/nmcli.py
Don't sort the old and new values for ipv4.addresses and ipv6.addresses before comparing them, because order matters in these parameters: the first address specified is the default source address for outbound connections.
The `nmcli` module (before this change) treated the order of IPv4 or IPv6 addresses for an interface as insignificant, i.e., it would not consider it a change for the order of these addresses to change. This is not correct, since the first address for an interface is the default address for outbound connections, so order matters. The change in this PR continues to treat order as insignificant for other list settings, but treats order as significant for ipv4.addresses and ipv6.addresses.
nmcli
=> nmcli: Treat order as significant when comparing address lists

changelogs/fragments/6034-lxd-tls.yml, plugins/module_utils/lxd.py
Fixes #5616. See https://github.com/ansible-collections/community.general/issues/5616#issuecomment-1424849131.
lxd module utils
=> lxd plugins and modules: fix TLS/SSL context creation

changelogs/fragments/5943-zfs_delegate_admin-fix-zfs-allow-cannot-parse-unknown-uid-gid.yml, plugins/modules/zfs_delegate_admin.py
When setting allow permissions for particular users or groups there will be circumstances when that user is not known to the host system.
In that case the output of `zfs allow <pool/dataset>` looks similar to this:
$ sudo zfs allow tank/test
---- Permissions on tank/test ---------------------------------------
Local+Descendent permissions:
user (unknown: 1002) hold
user zfsuser receive
The fix in this commit removes ` (unknown: `+`)` from the output leaving only the uid/gid.
This allows the current parser to continue even if the uid/gid is not known.
This situation occurs most often when moving a zpool from one system to another that may not have the same users/groups. Simply adding permissions to a user/group and then deleting the user/group from the system will cause this situation to …
=> zfs_delegate_admin: fix: zfs allow cannot parse unknown uid/gid

changelogs/fragments/5994-github-webhook-secret.yml, plugins/modules/github_webhook.py
Currently if you don't have a secret for the hook, the module will always report `changed` status even after multiple runs. This change adds secret to the config only if user specifies it.
github_webhook
I've tested the change locally:
- if user doesn't provide secret - it doesn't report `changed` state anymore on the second run
- if user provides empty secret - it doesn't report `changed` state anymore on the second run
- if there was a secret before, and user doesn't provide a secret in the task - it will remove the secret (same as before this change)
=> github_webhook: Don't include secret in the config if it's absent

changelogs/fragments/5814-support-keycloak-subgroups.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_group.py, tests/integration/targets/keycloak_group/aliases, tests/integration/targets/keycloak_group/readme.adoc, tests/integration/targets/keycloak_group/tasks/main.yml, tests/integration/targets/keycloak_group/vars/main.yml
Keycloak allows arbitrary deep group nesting, creating groups as subgroups of other groups. The current version of the corresponding ansible module does not support this, only creating top level base groups. This feature request makes it possible for the module to handle subgroups in a optional non-breaking way by introducing a new optional module parameter `parents` to specify a list of parent groups (parent chain) to create / delete / manage subgroups.
plugins/modules/keycloak_group.py
As this module seemingly had no integration tests yet I also added some test cases to check its already existing standard behaviour.
Tested with recent keycloak (api) version: `20.0.2`.
=> keycloak_group: support keycloak subgroups

changelogs/fragments/6074-loader_in_listify.yml.yml, plugins/lookup/cartesian.py, plugins/lookup/flattened.py
remove deprecated passing of loader to `listify_lookup_plugin_terms`
- cartesian
- flattened
Passing the load was deprecated in Ansible (https://github.com/ansible/ansible/pull/78244). This PR updates the code to remove the  currently displayed deprecation warning.
Example playbook:
```yaml
gather_facts: False
tasks:
- name: test
debug:
msg: "{{ item }}"
with_community.general.flattened:
- a
- b
- c
```
which produces the output:
```
PLAY [localhost] **********************************************************************************************************************************************************************************************************************************
TASK [test] ***************************************************************** …
```
=> stop passing loader/dataloader since it has been deprecated by ansible

changelogs/fragments/5972-cloudflare-dns-srv-record.yml, plugins/modules/cloudflare_dns.py
This fixes a bug in the cloudflare_dns module where setting a root-level SRV record resulted in a `400 Bad Request`. After some debugging apparently the following line removes the zone suffix from the record:
https://github.com/ansible-collections/community.general/blob/de193ac1bf1c2336d8b9e465e28093cb20bb14c1/plugins/modules/cloudflare_dns.py#L690
Say, input data `params['record'] = example.com` and `params['zone'] = example.com` then name will be empty, which is not accepted by the Cloudflare API. Since the intention was to set a root-level entry, this PR ensures that in that specific case `name` will be equals to the zone.
cloudflare_dns
```paste below
```
=> cloudflare_dns: Fix setting SRV records with a root level entry

changelogs/fragments/5830-sefcontext-path-subs.yml, plugins/modules/sefcontext.py, tests/integration/targets/sefcontext/tasks/sefcontext.yml
Fixes #1193.
Add support for path substitution mappings in the `sefcontext` module.
I would like to get feedback on this architecture that is quite a bit different from another (dead) PR #5189:
- Don't use new functions just for adding/deleting path substitutions. Modify the existing functions.
- How deletion is done has minor change - current playbooks continue to work as before:
- Don't require the `setype` argument with `state=absent` - it is not really required for deletion and it was not even used in the old code.
- If neither `setype` or `substitute` arg passed: delete both path substitutions and regular context mappings for `target` if either was found when deletion requested.
- If `substitute` *was* passed with `state=absent` then delete only that equivalence if found (don't …
=> sefcontext: add support for path substitutions

changelogs/fragments/5985-add-new-gitlab-api-features.yml, plugins/modules/gitlab_project.py
Fixes #5985 
Added support for  `releases_access_level`, `environments_access_level`, `feature_flags_access_level`, `infrastructure_access_level`, `monitor_access_level` and `security_and_compliance_access_level` options(these are defined here in [gitlab's documentation](https://docs.gitlab.com/ee/api/projects.html#create-project))
gitlab_project
Example of project creation using new fields:
```yml
- name: Setup gitlab project
community.general.gitlab_project:
api_url: https://gitlab.example.com/
validate_certs: true
api_username: dj-wasabi
api_password: "MySecretPassword"
name: my_project
group: ansible
releases_access_level: enabled
environments_access_level: disabled
feature_flags_access_level: disabled
infrastructure_access_level: disabled
monitor_access_level: …
```
=> Add new project features to API

changelogs/fragments/4028-modprobe-persistent-option.yml, plugins/modules/modprobe.py, tests/unit/plugins/modules/test_modprobe.py
Add persistent option as was requested in #4028
plugins/modules/system/modprobe.py
If kernel module doesn't load after reboot(by PCI IDs, USB IDs, DMI IDs or similar triggers) you can use static files in /etc/modules-load.d to load this module. This is what I implemented. If you add option permanent and set it as true ansible will add module file which should enable module on startup. If you set permanent option as false then ansible will try to find line where you enabled this module previously and comment it out. Same works with kernel module options in /etc/modprobe.d directory.
Example:
```
- name: Add the dummy module
community.general.modprobe:
name: dummy
state: present
params: 'numdummies=4'
persistent: true
```
=> add persistent option for modprobe

changelogs/fragments/6100-jenkins_plugin.yml, plugins/modules/jenkins_plugin.py
Fixes #5898, which was introduced in #5565.
jenkins_plugin
=> jenkins_plugin: avoid undefined variable when updates file is not downloaded

changelogs/fragments/6045-xorder-discovery.yml, plugins/doc_fragments/ldap.py, plugins/module_utils/ldap.py, plugins/modules/ldap_search.py
This PR adds the `xorder_discovery` parameter to the ldap modules. This new parameter controls the behavior of searching for DNs with ordering information (xorder). 
Fixes https://github.com/ansible-collections/community.general/issues/6045
ldap modules
=> add xorder_discovery parameter

changelogs/fragments/6118-jail-plugin-fix-default-inventory_hostname.yml, plugins/connection/jail.py
On FreeBSD, using the jail connection plugin will print the following warning when processing each task:
`[WARNING]: The "jail" connection plugin has an improperly configured remote target value, forcing "inventory_hostname" templated value instead of the string`
This was already fixed in other plugins by including "inventory_hostname" in the documentation string.
See for example 5e5af45 and 905f9ec.
- jail.py
=> Add 'inventory_hostname' to the jail plugin documentation

changelogs/fragments/4387-nmcli-mtu-for-vlan-connection-fix.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
* Changing MTU for `vlan` interface types was impossible because this logic just was not provided. I define `vlan` type in list of mtu_interfaces.
* Fixes #4387
nmcli
One testcase updated.
=> nmcli: fixed inability to change mtu on vlan connection

changelogs/fragments/6138-fix-yarn-global.yml, plugins/modules/yarn.py, tests/integration/targets/yarn/tasks/run.yml
Fixes #6132.
PR #5829 added a call to `yarn global dir` to select the correct global directory, but this ran before the default value of the `executable` param was set from the `PATH`.
This PR moves that logic out of the `Yarn` class initializer so the executable is identified just before it's needed.
yarn
See https://github.com/ansible-collections/community.general/issues/6132 for repro.
(Also cc @JohnDaly as this probably affects y'all)
=> Fix Yarn global not working without explicit executable path

changelogs/fragments/6112-fix_key_error_in_gitlab_runner_creation_update.yml, plugins/modules/gitlab_runner.py
The fix ensures that no 'KeyError' is raised, when 'access_level' is not provided as module parameter or when 'access_level_on_creation' is false.
Signed-off-by: Christoph Fiehe <c.fiehe@eurodata.de>
gitlab_runner
=> Fixes #6112: community.general.gitlab_runner KeyError: 'access_level'

tests/integration/targets/monit/aliases
The monit integration tests fail *a lot*. This PR marks them as unstable. This makes them no longer run by default, but they still run when the module itself is modified. See https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/integration-aliases.html#unstable for details.
monit
=> Mark monit integration tests as unstable

changelogs/fragments/6117-remove-stormssh-depend.yml, plugins/module_utils/_stormssh.py, plugins/modules/ssh_config.py, tests/integration/targets/ssh_config/tasks/main.yml
Pull in StormSSH's config parser into ssh_config
Fixes #6009
ssh_config
This PR simply pulls in the config parser from the now archived StormSSH into ssh_config itself.
=> Removes dependency on StormSSH

changelogs/fragments/6160-add-command-make-output.yml, plugins/modules/make.py
It may happen operator wants to get the built command instead of all the parameters. This change injects a new entry in the dict output, showing what command way actually launched.
This change adds a new information to the community.general.make module output: the built command that way
launched by the run_command.
The goal here is to help operator debugging potential issues, or just allow them to store this information in a log, for
instance.
make
Before:
```
"make_output": {
"chdir": "/tmp/foo",
"failed": false,
"file": null,
"jobs": null,
"params": null,
"stderr": "",
"stderr_lines": [],
"stdout": "foo\ntouch /tmp/foo.done",
"stdout_lines": [
"foo",
"touch /tmp/foo.done"
],
"target": "test"
}
}
```
After:
```
ok: [localhost] …
```
=> [make] Provide built command in the module output

changelogs/fragments/6122-redhat_subscription-subscribe-via-dbus.yaml, plugins/modules/redhat_subscription.py, tests/unit/plugins/modules/test_redhat_subscription.py
subscription-manager currently does not have a way to get credentials (username, password, activation keys, organization ID) in a secure way: the existing command line parameters can be easily spotted when running a process listing while 'subscription-manager register' runs. There is a D-Bus service, which is used by e.g. cockpit and Anaconda to interface with RHSM (at least for registration and common queries).
Try to perform the registration using D-Bus, in a way very similar to the work done in convert2rhel [1] (with my help):
- try to do a simple signal test to check whether the system bus works; inspired by the login in the dconf module
- pass most of the options as registration options; for the few that are not part of the registration, execute 'subscription-manager' manually
- add …
=> redhat_subscription: use D-Bus for registration if possible

changelogs/fragments/6127-yarn-ignore-warnings.yml, plugins/modules/yarn.py
Fixes #6127 
yarn
See #6127 for details
=> Updating yarn.list to not fail when when warnings are emitted

changelogs/fragments/6149-openbsd_pkg-term.yml, plugins/modules/openbsd_pkg.py
Keeps pkg_add happy when someone running ansible is using a TERM that the managed OpenBSD host does not know about.
Fixes #5738.
Selection of specific TERM from discussion at
https://marc.info/?l=openbsd-tech&m=167290482630534&w=2
openbsd_pkg
Before change:
```paste below
$ TERM=xterm-kitty ansible -i hosts openbsd_pkg_tests -u root -m community.general.openbsd_pkg  -a 'name=jq state=present'
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
[WARNING]: packaging Python module unavailable; unable to validate collection Ansible version requirements …
```
=> openbsd_pkg: set TERM to 'dumb' in execute_command

changelogs/fragments/6154-znode-optional-tls.yml, plugins/modules/znode.py
This adds the possibility to use encrypted communication.
znode
```paste below
```
=> add optional use_tls parameter

changelogs/fragments/6165-nmap-port.yml, plugins/inventory/nmap.py
`community.general.nmap` -p option
Nmap does not scan all ports, for instance `623`.  This allows for ports to be specified.
```paste below
nmap 10.0.1.60 -p 623,22
```
=> Adding support for `-p` option to specify port(s) to scan

changelogs/fragments/6111-influxdb_user-check-mode.yaml, plugins/modules/influxdb_user.py
When running in check mode, `influxdb_user` will return error when the user doesn't exist yet, instead of reporting `changed` state.
influxdb_user
=> Fix influxdb_user grants in check mode

changelogs/fragments/6180-replace-deprecated-badzipfile.yml, plugins/modules/archive.py
`BadZipfile` (with a small `f`) has been deprecated since Python 3.2, use `BadZipFile` (big `F`) instead, added in 3.2.
* https://docs.python.org/3/library/zipfile.html#zipfile.BadZipfile
* https://github.com/python/cpython/issues/86437
archive
See also https://github.com/ansible/ansible/pull/80198.
=> Replace deprecated error with BadZipFile

changelogs/fragments/xxxx-ldap-ca-cert-file.yml, plugins/doc_fragments/ldap.py, plugins/module_utils/ldap.py
This PR adds a `ca_cert_file` option to the ldap modules. This option can be used to specify a ca certificate used to verify ldap tls connections.
ldap modules
I wasn't sure how to name the changelog fragment, since this PR does not address an existing issue
=> ldap moduls: add optional ca_cert_file option

changelogs/fragments/6211-rhsm-require-root.yml, plugins/modules/redhat_subscription.py, plugins/modules/rhsm_release.py, plugins/modules/rhsm_repository.py, tests/unit/plugins/modules/test_redhat_subscription.py, tests/unit/plugins/modules/test_rhsm_release.py
`subscription-manager` on RHEL installs a symlink in `/usr/bin` to `console-helper` (part of usermode), which triggers an interactive prompt for root credentials when run as user. It seems that `console-helper` does not handle well non-interactive contexts (e.g. without a TTY for input), and thus it will hang waiting for input when run as user in an Ansible task.
Since `subscription-manager` requires root already anyway (and it will fail when explicitly run as user), then apply the same logic locally on all the modules that interact with it: `redhat_subscription`, `rhsm_release`, and `rhsm_repository`.
Fixes #734
A simple reproducer is running any of `redhat_subscription`, `rhsm_release`, or `rhsm_repository` without any privilege escalation (i.e. …
=> rhsm modules: cleanly fail when not run as root

changelogs/fragments/5664-redhat_subscription-credentials-when-needed.yaml, plugins/modules/redhat_subscription.py, tests/unit/plugins/modules/test_redhat_subscription.py
The module currently has a static `required_if` statement for its parameters that forces any of `username` or `activationkey` in case `state=present`; while this is generally a good idea, it can be an extra requirements in some cases. In particular, if the system is already registered, there is no need for credentials -- some of the operations of the module, such as manipulating pools, can be done perfectly without credentials.
Hence:
- change the static `required_if` to require credentials only when forcing the registration
- check for credentials manually when a registration is needed, i.e. on an unregistered system; the fail message is the same as the one shown by `required_if`
Adapt the tests to this new situation:
- `test_without_required_parameters` now needs to mock an unregistered …
=> redhat_subscription: require credentials only when needed

changelogs/fragments/5974-nmcli_add_new_addr_gen_mode6_options.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
Addresses:
Fixes #5973.
Add 'default' and 'default-or-eui64' to the list of valid choices for nmcli addr_gen_mode6 parameter.
nmcli
See #5973.
```paste below
```
=> nmcli: add new addr_gen_mode6 options

changelogs/fragments/3935-add-gitlab-group-runner.yml, plugins/modules/gitlab_runner.py, tests/unit/plugins/modules/gitlab.py, tests/unit/plugins/modules/test_gitlab_runner.py
This PR adds Gitlab group runners support to `community.general.gitlab_runner` module.
This allow to register a new Gitlab Runner within group settings, its update & deletion as a non-admin user.
gitlab_runner module
This PR :
- Adds a `group` string parameter to gitlab-runner module, similar to the `project` parameter, to specify the Gitlab group on which to register the runner
- Fixes a bug on project & group runner creation/deletion, which was previously done using the project API, but needs to be done from root `/runners` API.
- Adds a check to fail when both group and project and specified
```yaml
- name: Register Gitlab Runner
community.general.gitlab_runner:
access_level: not_protected
active: yes
api_url: "{{ runner.gitlab_url }}"
api_token: "{{ …
```
=> Add Gitlab group runners support

changelogs/fragments/6158-create-proxmox-vm-from-archive.yml, plugins/modules/proxmox_kvm.py
We  add a param to allow proxmox administrator to restore VM from an archives. This new option will be useful to automate automatic creation and restore of VM.
proxmox_kvm
=> Add archive param for proxmox_kvm module

changelogs/fragments/5970-add-proxyjump-option-to-ssh-config.yml, plugins/modules/ssh_config.py, tests/integration/targets/ssh_config/tasks/main.yml, tests/integration/targets/ssh_config/tasks/options.yml
adding proxyjump option for ssh_config module
#5970
ssh_config
proxyjump is an easier and "more modern" option to proxycommand in ssh
local execution:
```
ansible localhost --connection=local -a "host=otis ssh_config_file=~/.ssh/config_ansible proxyjump=bastion" -m community.general.ssh_config
```
Contents of ssh_config_file:
```
Host otis
proxyjump bastion
```
Mutual Exclusive test: 
```
ansible localhost --connection=local -a "host=otis ssh_config_file=~/.ssh/config_ansible proxyjump=bastion proxycommand='ssh -W %h:%p -q bastion'" -m community.general.ssh_config
```
Ansible error message:
```
localhost | FAILED! => {
"msg": "parameters are mutually exclusive: proxycommand|proxyjump"
}
```
Happy to add more tests but local idempotence works fine …
=> ssh_config: add proxyjump option

changelogs/fragments/6208-hpe-thermal-fan-percent.yaml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_info.py
Added two additional functions that we use to retrieve ThermalConfiguration and FanPercentMinimum settings (via iLO) on our HPE Gen 10/10+ boxes.
```
- name: Get HPE Thermal Config
category: Chassis
command: GetHPEThermalConfig
- name: Get HPE Fan Percent Minimum
category: Chassis
command: GetHPEFanPercentMin
```
=> added hpe thermal config and fan percent min

changelogs/fragments/6198-pipx-inject-install-apps.yml, plugins/module_utils/pipx.py, plugins/modules/pipx.py, tests/integration/targets/pipx/tasks/main.yml
Add support for `pipx inject`'s `--include-apps` parameter.
Add support to the pipx module so that `state=inject` can cause pipx to include applications from the specified app into $PATH.
For instance, I currently have an ansible install with ansible-lint injected, and I want ansible-lint in $PATH.  I can achieve that manually, but I can't codify it (cleanly) in my ansible playbooks.
```
pipx install --include-deps ansible
pipx inject ansible --include-apps ansible-lint[yamllint]
```
pipx
=> pipx: Allow injected modules to add apps

changelogs/fragments/6065-nmcli-add-runner-fast-rate-option.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
This PR adds team.runner-fast-rate parameter support for nmcli module. Feature was requested in https://github.com/ansible-collections/community.general/issues/6065
=> nmcli: add runner_fast_rate option

changelogs/fragments/0000-nmcli-ipv4-mayfail-idempotency-fix.yml, changelogs/fragments/6106-nmcli-ipv4-mayfail-idempotency-fix.yml, plugins/modules/nmcli.py
If `method4` was `disabled`, this option has no effect - nmcli accepts it, but keeps it's own default value. Task marked changed always because of `diff` with default value and passed to module.
Now option `ipv4.may-fail` participate in configuration process only when user defined `method4` as non-`disabled`.
nmcli
=> nmcli: fixed idempotency issue with 'may_fail4' when 'method' is 'disabled'

changelogs/fragments/3216-nmcli-bridge-idempotency-fix.yml, plugins/modules/nmcli.py
If `bridge.stp` is set to `no` in nmcli it accepts any value of `bridge.priority` but holds it's own default value. This causes any task with defined `priority` option to be "changed" anyway.
For now, `bridge.priority` participate in configure only when user defined `stp` as `true`.
* Fixes #4683 
nmcli
=> nmcli: fixed idempotency issue when config bridge connection

changelogs/fragments/6227-xen-orchestra-check-response-id.yml, plugins/inventory/xen_orchestra.py
I ran into an issue where about 1/3 of the time, when using the XenOrchestra inventory plugin, the process would fail due to the first response from the XO server received being unrelated to the request. This can be easily fixed by checking that the response ID is the same as the request ID, which is what this change does.
xen_orchestra inventory
The messages from the server that cause the issue vary, but one that I noticed frequently is shown below:
```
{
"jsonrpc": "2.0",
"method": "all",
"params": {
"type": "exit",
"items": {
"eb859a79-1725-eecd-67e6-b9bf941205e4": 0
}
}
}
```
Before change:
```
[ansible@ansible-machine ~]$ ansible-inventory -i /etc/ansible/xen_orchestra.yml --graph
[WARNING]:  * Failed to parse /etc/ansible/xen_orchestra.yml with …
```
=> Fixed XenOrchestra inventory plugin failing due to not checking response ID.

changelogs/fragments/6200-adding-open-option-to-nmap.yml, plugins/inventory/nmap.py
This will add in the `--open` option for the `nmap` inventory plugin.  Currently the port scan (`-sP`) just scans ports and returns results from _all_ ports, regardless of if they are closed.  The `open` option will all for only open ports to be returned.  This will also clarify this by removing the "open ports" mention in the current `ports` argument.
`community.general.nmap` `--open` option
```
nmap -p 22 --open 192.160.0.0/24
```
=> Adding `open` option to nmap

.github/BOTMETA.yml, plugins/modules/kdeconfig.py, tests/integration/targets/kdeconfig/aliases, tests/integration/targets/kdeconfig/meta/main.yml, tests/integration/targets/kdeconfig/tasks/files/kwriteconf_fake, tests/integration/targets/kdeconfig/tasks/main.yml
Add a new module to manipulate KDE config files using kwriteconfig.
I'm using kwriteconfig utility instead of modifying the config file using Python code, because I don't think that there is any official and stable file format description (if it exists I couldn't find it) other then KDE source code itself.
So it seems safer (and future proof) to just use that utility.
The format itself is a sort of INI dialect.
kdeconfig
=> Add module to manipulate KDE config files using kwriteconfig

changelogs/fragments/6210-add-worklog-functionality-to-jira.yml, plugins/modules/jira.py, tests/integration/targets/jira/tasks/main.yml
This adds the functionality to jira be able to add worklog comments.
Fixes #6209
community.general.jira
```paste below
- name: Worklog on issue
community.general.jira:
uri: '{{ server }}'
username: '{{ user }}'
password: '{{ pass }}'
issue: '{{ issue.meta.key }}'
operation: worklog
comment: A worklog added by Ansible
fields:
timeSpentSeconds: 12000
```
=> Add worklog functionality to jira module

plugins/lookup/merge_variables.py
This fixes the examples for the merge_variables lookup plugin. That was missed while processing the feedback given in #5533
merge_variables
/cc @felixfontein
=> merge_variables: Fix example section

changelogs/fragments/6212-pipx-include-injected.yml, plugins/modules/pipx.py
Improve the pipx module so the documentation matches what attributes are allowed with which `state`s.
- Document which parameters are allowed with `state=latest` (everything supported with either `state=install` or `state=upgrade`)
- Fix `include_injected` so that it works with `state=upgrade` and `state=latest`
This depends on #6198. Happy to keep it as a separate PR or fold it into that one.
pipx
=> pipx: document parameters supported with state=latest, and fix include_injected parameter

changelogs/fragments/6259-redhat_subscription-fix-force.yaml, plugins/modules/redhat_subscription.py
When registering using D-Bus and using a version of subscription-manager with an unimplemented `force` option, then unregister manually the system only if it is registered. `subscription-manager unregister` errors out when trying to unregister an already unregistered system.
Fixes #6258
Easy reproducer:
- RHEL 9 older than 9.2, or RHEL 8 older than 8.8, or RHEL 7 and older
- ensure the system is unregistered, and attempt to register with `force_register=true`
```yaml
- name: ensure unregistered
redhat_subscription:
state: absent
- name: ensure registered
redhat_subscription:
state: present
force_register: true
username: "your-username"
password: "your-password"
```
=> redhat_subscription: manually unregister only when registered

.github/BOTMETA.yml
- remove Barnaby, Adrian, and Kevil from `redhat_subscription`, as they are no more working on `subscription-manager`
- create a new `team_rhsm` group to maintain `redhat_subscription`, `rhsm_release`, and `rhsm_repository` (all the modules related to `subscription-manager)`
- add myself and Chris to `team_rhsm`
=> Update maintainership of rhsm modules

changelogs/fragments/6275-redhat_subscription-fix-environments-centos.yaml, plugins/modules/redhat_subscription.py
Factorize the current logic to determine whether use `environments` as D-Bus registration option (rather than `environment`) in an own function, so it is easier to read it and maintain it.
With the small helper function in place, extend the logic to support CentOS: it is in practice the same as the RHEL one, with an additional check to support CentOS Stream 8 (which is a rolling release, and not versioned).
Register a CentOS Stream 8 system to a registration server that supports environments (typically Satellite):
```yaml
- redhat_subscription:
state: present
username: "your-username"
password: "your-password"
environment: "environment-id"
```
=> redhat_subscription: fix D-Bus option for environments on CentOS

changelogs/fragments/6277-add-topics-gitlab-project.yml, plugins/modules/gitlab_project.py
Team,
I added a support for topics in gitlab_project.py . 
To be retrocompatible with old gitlab versione ( prior 14) I also added a check on the gitlab server and if it's less than 14 I replace `topics` with `tag_list`.
Fixes: #6277
gitlab_project
=> Add support to topics on Gitlab Project module

tests/integration/targets/pids/tasks/main.yml, tests/integration/targets/pids/templates/obtainpid.sh
Currently the pids integration tests fail on FreeBSD since apparently there are more processes that contain the pattern `some-`.
Let's make the collision less likely.
pids
=> pids tests: 'some-' is not that a unique pattern.

changelogs/fragments/6308-pipx-add-system-site-packages.yml, plugins/module_utils/pipx.py, plugins/modules/pipx.py, tests/integration/targets/pipx/tasks/main.yml
- Add `system_site_packages` module parameter to pipx, which gives an application's virtual environment access to the system-wide system-site-packages.  (This just corresponds to pipx's `--system-site-packages` parameter)
pipx
Split off of #6303 per request
=> pipx: Add support for system_site_packages

tests/integration/targets/pkgng/tasks/freebsd.yml
They currently fail:
- https://dev.azure.com/ansible/community.general/_build/results?buildId=73613&view=logs&j=c12a8e90-c78d-5d96-c83c-8beac118ca9b&t=0da6623a-06d0-5789-1f6f-991060dffcb9&l=12432
- https://dev.azure.com/ansible/community.general/_build/results?buildId=73633&view=logs&j=c12a8e90-c78d-5d96-c83c-8beac118ca9b&t=0da6623a-06d0-5789-1f6f-991060dffcb9&l=12445
- https://dev.azure.com/ansible/community.general/_build/results?buildId=73634&view=logs&j=c12a8e90-c78d-5d96-c83c-8beac118ca9b&t=0da6623a-06d0-5789-1f6f-991060dffcb9&l=12443
pkgng integration tests
=> pkgng: skip jail tests also on FreeBSD 12.3

changelogs/fragments/6199-archive-generate-checksum-in-chunks.yml, plugins/modules/archive.py
Running crc32 over the whole content of the compressed file potentially requires a lot of RAM. The crc32 function in zlib allows for calculating the checksum in chunks. This changes the code to calculate the checksum over 16 MiB chunks instead. 16 MiB is the value also used by shutil.copyfileobj().
Fixes: #6272
archive
=> archive: Generate crc32 over 16MiB chunks

changelogs/fragments/6293-add-puppet-skip-tags-option.yaml, plugins/module_utils/puppet.py, plugins/modules/puppet.py, tests/unit/plugins/modules/test_puppet.py
Add a new option to `skip_tags` ([reference](https://www.puppet.com/docs/puppet/7/configuration.html#skip-tags)) to the Puppet module for Ansible to exclude certain tagged resources during a puppet agent or apply.
`community.general.puppet module`
First PR here, so hopefully I have everything in order.  Thanks in advance for your review and consideration.
=> Add skip_tags option to Puppet module

changelogs/fragments/6267-homebrew-cask-upgrade-all-greedy.yml, plugins/modules/homebrew_cask.py
The homebrew_cask upgrade_all action should respect the greedy option.
So far the greedy flag was only parsed when upgrading a given cask. With this PR it can also be used when upgrading all installed casks.
homebrew_cask
=> homebrew: respect greedy flag for cask upgrade_all

changelogs/fragments/6206-dconf-booleans.yml, plugins/modules/dconf.py
There are three commits in this PR.
The first is a minor follow-up to #6049 to handle an edge case I didn't anticipate: what happens when the user attempts to set a value which is currently completely unset in the dconf database. We need to handle this explicitly because the GVariant parser throws a TypeError if we attempt to parse None. I don't think this should have a changelog fragment because I don't believe the changes in #6049 have been released yet (please correct me if I'm wrong).
The second is a trivial improvement to an error message which I don't think deserves a changelog entry either. It's just making an error message slightly more verbose to assist in debugging failures. This is mostly of interest to developers of the module, frankly, not to end users.
The third probably …
=> dconf: three minor but useful fixes

changelogs/fragments/6319-redhat_subscription-fix-environment-parameter.yaml, plugins/modules/redhat_subscription.py
It turns out that the 'environments' that the D-Bus Register*() APIs accept are the IDs of the environments, and not the user-facing names of the environments (which is what the module has been accepting so far).
Since there is no easy way to do the mapping manually, for now use again the subscription-manager CLI for registering when environments are specified.
=> redhat_subscription: use CLI when using environments

.github/BOTMETA.yml, plugins/module_utils/ilo_redfish_utils.py, plugins/modules/ilo_redfish_command.py, tests/integration/targets/ilo_redfish_command/aliases, tests/integration/targets/ilo_redfish_command/tasks/main.yml
SUMMARY
This was previously raised as part of [5582](https://github.com/ansible-collections/community.general/pull/5582). Raising this separately as these functionalities are independent of the others in that PR and can be merged as the other functionalities still seem to have a few open questions. Will be removing this functionality from the old PR.
ISSUE TYPE
COMPONENT NAME
ilo_redfish_command.py
The respective functions for the modules have been added to ilo_redfish_utils.py
=> Adding CheckiLORebootStatus functionality to ilo_redfish_command

changelogs/fragments/6312-nmcli-add-macvlan-connection-type.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
Add `macvlan` connection type support to `nmcli` module
Fixes #5316 
nmcli
=> nmcli: Add macvlan connection type support

changelogs/fragments/6294-fix-one_vm-instantiation.yml, plugins/module_utils/opennebula.py, tests/unit/plugins/module_utils/test_opennebula.py
with more complex templates that make use of quoted strings the new `render` method fails to produce a template that is accepted by OpenNebula.  ==> escape double quotes in strings to make OpenNebula happy again.
I also tested whether newlines need to be escaped, looks like they are fine as they are.
Fixes #6225
one_vm
tested on an old opennebula 5.12 cluster, but from what I can tell the opennebula version doesn't matter here ;-)
=> one_vm: fix syntax error when creating VMs with a more complex template

changelogs/fragments/6300-rundeck-modules-fixes-and-improvements.yml, plugins/doc_fragments/rundeck.py, plugins/module_utils/rundeck.py, plugins/modules/rundeck_acl_policy.py, plugins/modules/rundeck_project.py
Following PR #5887 and issue #5742, I've made some updates and improvements to the `rundeck_acl_policy` and `rundeck_project` modules to fix the issues and make them more standard.
Fixes #5742
- rundeck_acl_policy
- rundeck_project
- Changed the modules for using `module_utils.rundeck` functions and arguments
- Fixed empty response errors in `module_utils.rundeck`
=> Rundeck modules fixes and improvements

plugins/test/a_module.py, tests/sanity/extra/extra-docs.json, tests/sanity/extra/extra-docs.py
Use `antsibull-docs lint-collection-docs --plugin-docs` to do additional documentation validation. This is important if the docs build workflow is no longer there (#6344).
This also ensures that no semantic markup is used. This should be changed in `main` once the last minor 6.x.y release is out, so that stable-7 can start using semantic markup, while the extra test ensures that semantic markup isn't accidentally backported to stable-6 or stable-5.
CI
=> Do extra docs validation; explicitly disallow semantic markup in docs

changelogs/fragments/6336-dconf-refactor.yml, plugins/modules/dconf.py
Minor refactor to use `module_utils.deps` and `required_if`.
dconf
=> dconf: minor refactor

.github/BOTMETA.yml
revert of https://github.com/ansible-collections/community.general/pull/6354
BOTMETA.yml
=> BOTMETA.yml: put the label redhat_subscription back

changelogs/fragments/5603-redfish-idrac-job-id-in-response.yml, plugins/modules/idrac_redfish_command.py
Added `job_id` (and `return_values`) to idrac_redfish_command. This allows a user to perform follow-up tasks on the job that was created by the CreateBiosConfigJob command, and potentially other commands in the future.
Fix #5603 
idrac_redfish_command
Sample playbook:
```
---
- hosts: all
vars:
username: <REDACTED>
password: <REDACTED>
baseuri: <REDACTED>
default_uri_timeout: 5
default_uri_retries: 5
tasks:
- name: BIOS Job
community.general.idrac_redfish_command:
command: CreateBiosConfigJob
retries: "{{ default_uri_retries }}"
register: redfish_results
- debug:
var: redfish_results
```
New `return_values` with `job_id` is in the output.
```paste …
```
=> Redfish iDRAC: Added job_id to response for CreateBiosConfigJob

changelogs/fragments/6286-icinga2_host-template-and-template-vars.yml, plugins/modules/icinga2_host.py
Currently, the `template` parameter of the icinga2_host module is not sent correctly to Icinga, which results in the impossibility to use host templates when using this module.
This is due to an incorrect data structure, see [this example with curl](https://icinga.com/blog/2020/07/02/creating-a-host-through-the-icinga-2-api/) for the correct data structure.
This PR fixes it by submitting the correct data structure to the Icinga API.
This PR also enables inheritance of the template vars to the created host. In the current code, the whole `vars` array is sent to Icinga, which causes Icinga to ignore vars declared in the template. In this PR's code, the `vars` array is not redefined, each variable is send to Icinga as `vars.key = value`:
Current code : `vars = { distro = Debian } // …
=> icinga2_host: make use of templates and template vars

.github/BOTMETA.yml, changelogs/fragments/5832-btrfs-subvolume-info-new-modules.yml, plugins/module_utils/btrfs.py, plugins/modules/btrfs_info.py, plugins/modules/btrfs_subvolume.py, tests/integration/targets/btrfs_subvolume/aliases, tests/integration/targets/btrfs_subvolume/defaults/main.yml, tests/integration/targets/btrfs_subvolume/tasks/main.yml, tests/integration/targets/btrfs_subvolume/tasks/run_common_tests.yml, tests/integration/targets/btrfs_subvolume/tasks/run_filesystem_tests.yml, tests/integration/targets/btrfs_subvolume/tasks/setup.yml, tests/integration/targets/btrfs_subvolume/tasks/test_filesystem_matching.yml, tests/integration/targets/btrfs_subvolume/tasks/test_snapshot_clobber.yml, tests/integration/targets/btrfs_subvolume/tasks/test_snapshot_error.yml, tests/integration/targets/btrfs_subvolume/tasks/test_snapshot_skip.yml, tests/integration/targets/btrfs_subvolume/tasks/test_subvolume_default.yml, tests/integration/targets/btrfs_subvolume/tasks/test_subvolume_nested.yml, tests/integration/targets/btrfs_subvolume/tasks/test_subvolume_recursive.yml, tests/integration/targets/btrfs_subvolume/tasks/test_subvolume_simple.yml, tests/integration/targets/btrfs_subvolume/tasks/test_subvolume_whitespace.yml
Adds two new modules providing support for the btrfs fileystem:
- **btrfs_info**: Provides summary of the currently available btrfs fileystems including, uuid, label and devices. If the fileystem is currently mounted, all available subvolumes and the filesystem's default subvolume will also be available
- **btrfs_subvolume**: Provides the ability to create/delete btrfs subvolumes and snapshots and update the filesystem's default subvolume.
community.general.btrfs_info
community.general.btrfs_subvolume
I'm interested in any feedback, but I'm actively looking for feedback on a couple points below. See the current documentation and tests for examples of usage.
Currently, the two parameters that indicate a specific subvolume (_name_ / _snapshot_source_) are paths …
=> New modules btrfs_subvolume / btrfs_info

changelogs/fragments/6303-pipx-fix-state-latest-and-add-system-site-packages.yml, plugins/modules/pipx.py, plugins/modules/pipx_info.py, tests/integration/targets/pipx/tasks/main.yml
- Document the minimum version of pipx (0.16.2.1) that works with both pipx and pipx_info modules.  I'm not changing the status quo; just documenting a preexisting limit since the pipx module was first introduced in f1807d3323f63b929bee6aa8f3eebfe614f83029, where (as today) the module relies on "pipx list --json --include-injected".  The same limitation applies to the pipx_info module since its introduction in 7ffe6539c0ba3a3c43c49ae8bfbb37213c9e95a1
- Fix a bug that prevents `state=latest` and `install_deps=true` from working, because the `pipx upgrade` command doesn't accept a `--include-deps` parameter, and hasn't since pipx 0.15. (It's safe to remove this since, per above, the module requires pipx 0.16.2.1).
pipx
The failure that occurs with …
=> pipx: fix state=latest w/ install_deps=true

changelogs/fragments/6361-snap-alias-regex-bugfix.yml, plugins/modules/snap_alias.py, tests/integration/targets/snap_alias/aliases
While testing integration tests for ubuntu bumped into an error because the regular expression expected snap names to match `[\w-]+` but in Ubuntu there comes one named `lxd.lxc`. Replacing with `\S+`.
snap_alias
=> snap_alias: fix regex expression when listing aliases

changelogs/fragments/2090-idrac-redfish-resource-id-fix.yml, plugins/modules/idrac_redfish_command.py
'CreateBiosConfigJob' is unique in that it relies on discovering systems and managers. All other commands so far rely on one or the other. So, when a user specifies a 'resource_id' in which to perform the operation, it will always fail one of the checks for a matching system or manager. Since CreateBiosConfigJob only relies on operating upon the first system in the system collection (and not an exact system matching 'resource_id'), the change will only perform 'resource_id' matching on the manager.
Fix #2090 
idrac_redfish_command
Sample playbook:
```
---
- hosts: all
vars:
username: <REDACTED>
password: <REDACTED>
baseuri: <REDACTED>
default_uri_timeout: 5
default_uri_retries: 5
tasks:
- name: BIOS Job
community.general.idrac_redfish_command: …
```
=> Redfish iDRAC: Allow for specifying an exact manager with 'resource_id' for CreateBiosConfigJob

changelogs/fragments/6203-add-append-option-to-ipa-hostgroup.yml, plugins/modules/ipa_hostgroup.py
Add `append` option to ipa_hostgroup module which allow to add new hosts to existing hostgroup without deleting existing hostgroup members.
Fixes: #6187 
`community.general.ipa_hostgroup`
=> Add append option to ipa_hostgroup module

.github/BOTMETA.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_clientscope_type.py, tests/integration/targets/keycloak_clientscope_type/README.md, tests/integration/targets/keycloak_clientscope_type/docker-compose.yml, tests/integration/targets/keycloak_clientscope_type/tasks/main.yml, tests/integration/targets/keycloak_clientscope_type/vars/main.yml
The module keycloak_clientscope_type allows to set the client scope types (optional/default) either on realm or client level.
This module allows to set the default_default_client_scopes/default_optional_client_scopes of a realm or default_client_scopes/optional_client_scopes of a client. Though this properties can be sent in the realm or client payload, they are ignored.
keycloak_clientscope_type
=> Add a module to set the keycloak client scope type

changelogs/fragments/6318-add-form-flow.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_authentication.py
To create something like keycloak's built-in registration flow,
we need to create a subflow with the type 'form-flow'.
Additionally, this adds some detail to the error message created on keycloak API exceptions, i.e.
fields from the HTTPError exception. This is optional.
Another patch fixes an Exception when formatting an error message.
```paste below
```
=> keycloak: Add option to create authentication sub-flow of type 'form flow'

changelogs/fragments/6383-deps-failed.yml, plugins/module_utils/deps.py
Add function `failed()` to module `deps`, providing the ability to check the dependency check result without triggering an exception.
plugins/module_utils/deps.py
=> deps module utils: add function failed() to retrieve dependencies check result

.github/BOTMETA.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_authz_authorization_scope.py, tests/integration/targets/keycloak_authz_authorization_scope/aliases, tests/integration/targets/keycloak_authz_authorization_scope/readme.adoc, tests/integration/targets/keycloak_authz_authorization_scope/tasks/main.yml, tests/integration/targets/keycloak_authz_authorization_scope/vars/main.yml
This module allows managing Keycloak client authorization scopes through the Admin REST API. The client has to have authorization enable for this to work.
- keycloak_authz_authorization_scope
This module enabled modifying authorization settings for Keycloak clients, in particular "Authorization Scopes". The paths and payloads have not been officially documented by the Keycloak project, so I had to do that first: 
* https://www.puppeteers.net/blog/keycloak-authorization-services-rest-api-paths-and-payload
This is my first PR to Ansible community.general collection. I tried to keep the same coding conventions as in the other keycloak modules, but may have missed something. In particular I'm not sure if the module documentation needs some work or not. 
I was …
=> Add keycloak_authz_authorization scope module

tests/integration/targets/iso_create/tasks/main.yml, tests/integration/targets/iso_customize/tasks/iso_customize_exception.yml
Passing `null` is no longer valid for random parameters.
iso_customize
=> iso_customize: fix integration test

tests/integration/targets/pkgng/tasks/freebsd.yml
Skip jail tests also on FreeBSD 12.3.
Backport of #6313.
pkgng
=> [stable-4] pkgng: skip jail tests also on FreeBSD 12.3

changelogs/fragments/6401-rhsm_release-required.yml, plugins/modules/rhsm_release.py
Apparently `null`/`None` was always a valid parameter. ansible-core only allowed this due to a bug that got fixed, so specifying `release: null` no longer works with that fix (https://github.com/ansible/ansible/pull/79677).
(This also breaks nightly CI.)
rhsm_release
=> rhsm_release: removing required=true for 'release' option

changelogs/fragments/6404-ini_file-section.yml, plugins/modules/ini_file.py
Apparently `null`/`None` was always a valid parameter. ansible-core only allowed this due to a bug that got fixed, so specifying `release: null` no longer works with that fix (https://github.com/ansible/ansible/pull/79677).
(This also breaks nightly CI.)
ini_file
=> ini_file: removing required=true for 'section' option

tests/integration/targets/sysrc/tasks/main.yml
Setting up the jail fails for some FreeBSD versions.
sysrc tests
=> Restrict jail tests for sysrc to certain FreeBSD versions

tests/integration/targets/zypper_repository/tasks/zypper_repository.yml
https://dev.azure.com/ansible/community.general/_build/results?buildId=75137&view=logs&j=de3da64c-23eb-5657-cf0b-8258f71f384d&t=17914e40-7f52-54e0-8625-5c8000e4ff00&l=9713
```
10:45 fatal: [testhost]: FAILED! => {
10:45     "changed": false,
10:45     "cmd": "/usr/bin/zypper --quiet --non-interactive --gpg-auto-import-keys refresh --force -r Apache_PHP_Modules",
10:45     "invocation": {
10:45         "module_args": {
10:45             "auto_import_keys": true,
10:45             "autorefresh": true,
10:45             "description": null,
10:45             "disable_gpg_check": false,
10:45             "enabled": true,
10:45             "name": "Apache_PHP_Modules",
10:45             "overwrite_multiple": false,
10:45             "priority": 100,
10:45             "repo": …
```
=> zypper_repository: disable failing repository

tests/unit/requirements.txt
Try to fix failures such as https://github.com/ansible-collections/community.general/actions/runs/4779405242/jobs/8497139464
unit tests
=> [stable-4] Unit tests: restrict requirements to avoid bad PyOpenSSL + cryptography version collision for ansible-core 2.11

changelogs/fragments/6441-snap_alias-refactor.yml, plugins/module_utils/snap.py, plugins/modules/snap_alias.py
Minor refactor in `snap_alias`, moving the `CmdRunner` object creation to module utils. This will later be reused by the `snap` module and the upcoming `snap_info` one.
snap_alias
=> snap_alias: refactor code out to module utils

tests/unit/plugins/modules/test_dnsimple_info.py
Unit test for `dnsimple_info` was trying to import (or otherwise skip the test) the python package `dnsimple`, but that was never actually used.
dnsimple_info
=> dnsimple_info: remove extraneous importorskip from test

changelogs/fragments/passwordstore-lock.yml, plugins/lookup/passwordstore.py, plugins/module_utils/_filelock.py
https://github.com/ansible/ansible/pull/80438 removed functionality that the passwordstore plugin was still using.
passwordstore lookup
=> passwordstore plugin: vendor FileLock that was removed from ansible-core devel

tests/unit/plugins/modules/conftest.py
Fixes the problem where dependencies leak between modules.
Ref: https://github.com/ansible-collections/community.general/pull/6439#issuecomment-1527239948
Ref: https://github.com/ansible-collections/community.general/pull/6453
unit test global fixtures
=> Make sure that plugins/module_utils/deps.py is cleaned up before every test

changelogs/fragments/6465-mh-deps-deprecation.yml, plugins/module_utils/mh/mixins/deps.py
Deprecate the dependency mixin for MH in favour of using `module_utils.deps`
plugins/module_utils/mh/mixins/deps.py
=> MH mh/mixins/deps.py: deprecation

changelogs/fragments/6440-dnsimple-info-refactor.yml, plugins/modules/dnsimple_info.py
Minor refactor in module.
dnsimple_info
=> dnsimple_info: minor refactor

changelogs/fragments/6456-fix-portage-withbdeps-false.yml, plugins/modules/portage.py
Using ``withbdeps: false`` was causing the underlying emerge command to fail due to not passing an argument to the ``--with-bdeps`` flag.  Fix by updating the logic for generating the emerge command arguments to ensure that ``withbdeps: false`` results in a passing an ``n`` argument with the ``--with-bdeps`` emerge flag.
Fixes #6451.
portage
=> modules/portage: fix usage with withbdeps: false

changelogs/fragments/6458-puppet-noop.yml, plugins/module_utils/puppet.py, tests/unit/plugins/modules/test_puppet.py
Simplified the handling of the `noop` parameter, solving the reported error.
Also revamped the unit test a bit, adding two test cases to prove the fix.
Fixes #6452 
puppet
=> puppet: fix noop parameter error

changelogs/fragments/6473-ldap_search.yml, plugins/modules/ldap_search.py
Fixes #5704.
This contains a breaking change: it force-converts all output to UTF-8. That's why I don't want to backport this (as a bugfix).
It also allows to specify a list of attributes whose values will be Base64 encoded. This should be used if a caller actually relies on some binary values.
ldap_search
=> ldap_search: make sure output is always UTF-8 (by allowing to Base64 encode specific values, and force-converting everything else)

changelogs/fragments/5143-fix-xfs-quota-project-init.yml, plugins/modules/xfs_quota.py, tests/integration/targets/xfs_quota/tasks/pquota.yml
This fix ensures that in case of a project quota, the corresponding project gets initialized, if required.
xfs_quota
This is an attempt to re-submit and improve [#5144](https://github.com/ansible-collections/community.general/pull/5144), in order to get this issue finally fixed.
=> Fixes #5143: xfs_quota fails to initialize new project quotas

changelogs/fragments/6448-proxmox-kvm-migration-support.yml, plugins/modules/proxmox_kvm.py
I found myself wanting to use the `proxmox_kvm`module to migrate VM on different hosts, so I propose this change to do that by adding the `migrate` option, which is `False`by default (to prevent any breaking of existing playbooks).
proxmox_kvm
=> modules/proxmox_kvm: initial support for online migrations

changelogs/fragments/6192-allow-empty-resultsets.yml, plugins/modules/mssql_script.py, tests/integration/targets/mssql_script/tasks/main.yml
- The current implementation fails out when certain statements or batches do not have resultsets - this limits the usefulness of the module
- Instead, it is known that statements without resultsets return then OperationalError exception with text "Statement not executed or executed statement has no resultset". We will utilize these facts to accept these statements
- The implementation also assumes that users will always use best- practices for the script syntax; that is, "GO" will always be capitalized but this is not strictly required -- update to allow "GO" to be any mixed-case
- Fixes #6192
=> mssql_script: allow non-returning SQL statements

changelogs/fragments/6384-gitlab-refactor.yml, plugins/module_utils/gitlab.py, plugins/modules/gitlab_group_variable.py, plugins/modules/gitlab_project_variable.py
Refactor function `vars_to_variables` used in both modules `gitlab_group_variable` and `gitlab_project_variable` to the `gitlab` module utils.
plugins/module_utils/gitlab.py
plugins/modules/gitlab_group_variable.py
plugins/modules/gitlab_project_variable.py
=> gitlab modules: minor refactor

changelogs/fragments/6491-dconf-respawn.yml, plugins/modules/dconf.py
If we're invoked in a Python interpreter that doesn't have access to `gi.repository.GLib`, try to find one that does and respawn the task in that interpreter.
dconf
As suggested by @felixfontein in https://github.com/ansible-collections/community.general/pull/6049#issuecomment-1454676802 .
=> dconf - Try to find a Python interpreter that has gi.repository.GLib

changelogs/fragments/473-nmcli-slave-type-implemented.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
* Adding `slave_type` option have discussed in several issues:
* #2943 
* Fixes #473 
Without it module makes impossible to create non-ethernet interfaces (eg bond, vlan) attached to bridges. From nmcli side this options already deprecated.
nmcli
* argspecs updated
* docs updated
* tests updated
* added several examples
* added warning message in case of using `type` = `bridge-slave`. In my opinion this `type` is very problematic due to it has non-obviousness results.
=> nmcli: added new module option 'slave_type' to allow create non-ethernet slave connections

plugins/modules/terraform.py
The [Docs](https://docs.ansible.com/ansible/latest/collections/community/general/terraform_module.html) have a typo in the examples. `camplex_vars` should be spelled `complex_vars`. 
Since many people are copy-and-pasting from docs and modify them to their needs this typo is an annoyance for users.
trivial:
- terraform - fix typo in docs `camplex_vars` -> `complex_vars`
community.general.terraform
just fixing a typo in docs
=> fix typo in `terraform` docs

.github/BOTMETA.yml, plugins/modules/ipbase_facts.py, plugins/modules/ipbase_info.py, tests/unit/plugins/modules/test_ipbase.py
I added a module to get geolocation data for the host IP from ipbase.com. 
Additional to the geolocation data, it also returns data about the AS, timezone, and a flag if the server is in the European Union which is quit useful.
ipbase_fact
```paste below
"msg": {
"as_name": "T-Mobile Austria GmbH",
"as_number": 8412,
"city": "Vienna",
"continent": "Europe",
"continent_code": "EU",
"country": "Austria",
"country_code": "AT",
"hostname": "81-223-100-100.static.upcbusiness.at",
"ip": "81.223.100.100",
"is_in_european_union": true,
"latitude": 48.1861686706543,
"longitude": 16.403240203857422,
"region": "Vienna",
"region_code": "AT-9",
"timezone": "Europe/Vienna",
"zip": "1030"
},
"failed": false
}
} …
```
=> Add ipbase_info module

changelogs/fragments/6171-shutdown-using-systemd.yml, plugins/action/shutdown.py, plugins/modules/shutdown.py, tests/integration/targets/shutdown/aliases, tests/integration/targets/shutdown/tasks/main.yml
This PR fixes #4269, allowing Linux systems without shutdown commands to be shutdown using systemd directly.
shutdown
I've added a conditional that sets `systemd poweroff` with no arguments to be the shutdown command only if there are are no matching `search_paths`. Note that I used `systemd poweroff` not `systemctl isolate poweroff.target` as mentioned in the [relevant manual page](https://www.freedesktop.org/software/systemd/man/systemd-halt.service.html). The only risk introduced by this change is that a user expects the system to shut down with a message or at a future time, but the system does not have the required command, it will shut down immediately (ignoring the arguments). I believe that this is acceptable, as this behavior is already present in Alpine. …
=> Shutdown systemd without sysv

tests/integration/targets/apache2_module/tasks/main.yml, tests/integration/targets/influxdb_user/tasks/main.yml, tests/integration/targets/locale_gen/tasks/main.yml, tests/integration/targets/mqtt/tasks/main.yml, tests/integration/targets/pacman/tasks/main.yml, tests/integration/targets/pkgng/tasks/freebsd.yml, tests/integration/targets/sefcontext/tasks/main.yml, tests/integration/targets/sensu_handler/tasks/main.yml, tests/integration/targets/setup_influxdb/tasks/main.yml, tests/integration/targets/setup_mosquitto/tasks/main.yml, tests/integration/targets/setup_pkg_mgr/tasks/main.yml, tests/integration/targets/ssh_config/tasks/main.yml, tests/integration/targets/sysrc/tasks/main.yml, tests/integration/targets/xattr/tasks/main.yml, tests/integration/targets/yarn/tasks/main.yml, tests/integration/targets/zypper/tasks/main.yml, tests/integration/targets/zypper_repository/tasks/main.yml, tests/integration/targets/zypper_repository/tasks/test.yml
It's still used in integration tests. Let's get rid of it.
=> CI: include has finally been removed in ansible-core devel

changelogs/fragments/6539-semantic-markup.yml, tests/sanity/extra/extra-docs.py
Enable using semantic markup. (Without actually starting to do so.)
This is needed to correctly fix #6538.
sanity tests
changelog
=> Enable using semantic markup

plugins/modules/dconf.py
Here https://docs.ansible.com/ansible/latest/collections/community/general/dconf_module.html incorrect `:code:` syntax was used to enclose code snippets, which resulted in rendering issues.
community.general.dconf module
=> Fix code formatting in documentation of dconf.py

changelogs/fragments/6527-nmcli-bond-fix-xmit_hash_policy.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
There is no alias option for configure `xmit_hash_policy` param for bond interface, we need to set it via `+bond.option` key.
Fixes: #5861
nmcli
=> nmcli: Fix bond option xmit_hash_policy

changelogs/fragments/6548-portage-changed_use-newuse.yml, plugins/modules/portage.py
This PR provides a fix for the options `changed_use` and `newuse` of the `portage` module.
fixes #6008
portage
The `changed_use` and `newuse` options did not trigger rebuilds of packages, since the `portage` module did not take them into account when deciding whether to call `emerge` or not.
I simply added both options to the conditional.
Another approach would be to simply remove the conditional and *always* run `emerge`.
This would avoid further issues with similar options (if there are any) and result in more consistent output, at the expense of performance.
Before:
```
ansible -m portage -a 'package=installkernel-gentoo state=present changed_use=true' gentoo-test
gentoo-test | SUCCESS => {
"discovered_interpreter_python": "/usr/sbin/python3.11" …
```
=> portage: fix changed_use and newuse not triggering rebuilds (#6008)

changelogs/fragments/6534-zypper-exitcode-102-handled.yaml, plugins/modules/zypper.py
added handling of zypper exitcode 102: ZYPPER_EXIT_INF_REBOOT_NEEDED - Returned after a successful installation of a patch which requires reboot of computer.
This code was not treated at all by the module and therefore considered a faillure and the changed status was never set.
After my fix the exitcode 102 will be treated exactly like 0 by the module internally, and the changed status will be reported correctly.
However, since I preserve the rc 102 in the retvals to allow the playbook to react to the requested reboot, the task must still include a "register" and a "failed_when" property to pass as OK in this event.
Example:
```
tasks:
- name: Apply patches on OpenSUSE/SUSE Linux
zypper:
name: '*'
state: latest
type: patch
extra_args_precommand: '--non-interactive-include-reboot-patches' …
```
=> added handling of zypper exitcode 102: ZYPPER_EXIT_INF_REBOOT_NEEDED

changelogs/fragments/6554-proxmox-tasks-info-fix-required-password.yaml, plugins/modules/proxmox_tasks_info.py
Fixes #6201.
As `api_user` is always required then using it in required_together constraint leads to unwanted behavior when `api_password` is also always needed.
proxmox_tasks_info
Output Before the change
```
"api_host": "localhost",
"api_password": null,
"api_token_id": "root-token",
"api_token_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"api_user": "root@pam",
"node": "pve",
"task": null,
"validate_certs": false
}
},
"msg": "parameters are required together: api_user, api_password"
}
```
Output After
```
"api_host": "localhost",
"api_password": null,
"api_token_id": "root-token",
"api_token_secret": …
```
=> Don't require api_password when api_token_id is used in proxmox_tasks_info

tests/utils/constraints.txt
=> CI: restrict to python-nomad < 2.0.0 for Python < 3.7

changelogs/fragments/6568-fix-get-user-by-username-in-keycloak-module-utils.yml, plugins/module_utils/identity/keycloak/keycloak.py
Method get_user_by_username in keycloak.py module_utils return a list of users but ion the documentation the method must return a user representation if found or None otherwise.
Thit PR fix this issue.
keycloak.py in module_utils
=> Fix get_user_by_username in keycloak library

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml
ansible-core 2.12 is EOL since the release of ansible-core 2.15.0.
CI
=> Move ansible-core 2.12 to EOL CI

changelogs/fragments/6512-cpanm-default-mode.yml, plugins/modules/cpanm.py
Deprecate value `compatibility` as the default for parameter `mode`.
cpanm
=> cpanm: deprecate default mode

changelogs/fragments/6513-opkg-default-force.yml, plugins/modules/opkg.py
This module has a legacy value `""` for the `force` parameter. When `force=""` the module does not pass any CLI "force" option to the underlying `opkg` command. The same happens if `force=null`. 
So, the option `""` and it being marked as default value is something that was arguably created to artificially indicate that the parameter is optional.
This PR removes the default, and given that both values `""` and `null` will trigger the same behaviour in the module, this change is completely transparent to users.
A follow-up PR will then deprecate the option `""`, on the account that some users may be calling the module explicitly passing the empty string as parameter.
opkg
=> opkg: remove useless default value for force

changelogs/fragments/6522-copr-respawn.yaml, plugins/modules/copr.py, tests/integration/targets/copr/tasks/main.yml
copr - respawn module to use the system python interpreter when the ``dnf`` python module is not available in ``ansible_python_interpreter``
copr
Fixes downstream bug https://bugzilla.redhat.com/2203513
Can we backport this to stable-6 and stable-7 so it shows up in ansible 7 and 8? I plan to backport this to the EPEL 8 and 9 ansible-collection-community-general RPM packages that currently contain upstream EOL versions[^1].
[^1]: We're updating to upstream supported versions prior to the next RHEL minor release.
=> respawn copr module when dnf is missing

changelogs/fragments/6520-mas-disable-signin.yaml, plugins/modules/mas.py
Feature Implementation of Issue - https://github.com/ansible-collections/community.general/issues/6519
Fixes #6519 
mas
Disabling the sign-in check when trying to install or upgrade an app via mas via Ansible for anyone using Mac 12.0+. More details can be found in the issue
=> mas: disable sign-in check for macOS 12+

changelogs/fragments/6502-cobbler-inventory_hostname.yml, plugins/inventory/cobbler.py
hostname (#6492)
Add warning for systems with empty profiles
Fixes: #6492
To use cobbler system names in the inventory, in your cobbler.yml use:
```paste below
plugin: cobbler
url: https://cobbler/cobbler_api
inventory_hostname: system
```
=> plugins/inventory/cobbler: Add option to use system name for inventory

.github/BOTMETA.yml, plugins/modules/gitlab_instance_variable.py, tests/integration/targets/gitlab_instance_variable/aliases, tests/integration/targets/gitlab_instance_variable/tasks/main.yml
This add a new module to use the Gitlab Instance Variables API to set/edit instance wide variables (https://docs.gitlab.com/ee/api/instance_level_ci_variables.html).
This module is based on the code of the already existing `gitlab_group_variable` module (https://github.com/ansible-collections/community.general/blob/main/plugins/modules/gitlab_group_variable.py).
gitlab_instance_variable
=> gitlab modules: added instance variable

changelogs/fragments/ini_file-preserve-symlink.yml, plugins/modules/ini_file.py, tests/integration/targets/ini_file/tasks/tests/04-symlink.yml
This is a bug fix that address a situation where `community.general.ini_file` was destroying symlinks instead of updating of updating their targets.
If `poth` points on a symlink and `follow` is true, the `ini_file` plugin will preserve the symlink and modify the target file.
Closes: #6470
ini_file
=> ini_file: Don't creates new file instead of following symlink

changelogs/fragments/6570-handle-shutdown-timeout.yaml, plugins/modules/proxmox_kvm.py
Forcefully stop virtual machine using timeout param for proxmox vm
shutdown api call.
Fixes #6257.
proxmox_kvm
Before fix(default timeout 30 seconds)
```
"acpi": null,
"agent": null,
"api_host": "localhost",
"api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"api_token_id": null,
"api_token_secret": null,
"api_user": "root@pam",
"archive": null,
"args": null,
"autostart": null,
"balloon": null,
"bios": null,
"boot": null,
"bootdisk": null,
"cicustom": null,
"cipassword": null,
"citype": null,
"ciuser": null,
"clone": null,
"cores": null,
"cpu": null,
"cpulimit": null,
"cpuunits": null,
"delete": null,
"description": null,
"digest": null,
"efidisk0": null,
"force": true,
"format": …
```
=> proxmox_kvm | Expose timeout param to stopped state

changelogs/fragments/6533-proxmox_kvm-tpmstate0-support.yaml, galaxy.yml, plugins/modules/proxmox_kvm.py
Adds the tpmstate0 parameter, which is a hash containing two options (storage and version) to configure the TPM state disk. The TPM (Trusted Platform Module) is required for Windows 11 installations.
proxmox_kvm
Before
```
changed: [localhost] => {
"devices": {
"sata0": "STOR1:253/vm-253-disk-1.qcow2",
"sata1": "local:iso/Win11_22H2_English_x64v1_UEFI.iso"
},
"acpi": null,
"agent": "True",
"api_host": "pve1.domain.com",
"api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"api_token_id": null,
"api_token_secret": null,
"api_user": "root@pam",
"archive": null,
"args": null,
"autostart": true,
"balloon": 8192,
"bios": "ovmf",
"boot": "cdn",
"bootdisk": "sata0",
"cicustom": null,
"cipassword": null,
"citype": null, …
```
=> proxmox_kvm: support for tpmstate0 parameter

changelogs/fragments/6601-cmdrunner-deprecate-default-type.yml, plugins/module_utils/cmd_runner.py
Deprecate `cmd_runner_fmt.as_default_type()`
=> CmdRunner module utils: deprecate format method `as_default_type()`

changelogs/fragments/6602-vardict-as-dict.yml, plugins/module_utils/vardict.py, tests/unit/plugins/module_utils/test_vardict.py
Add method `as_dict()` to `VarDict`.
plugins/module_utils/vardict.py
=> VarDict module utils: add `as_dict()` method

plugins/lookup/bitwarden.py
The Bitwarden CLI requires a `login` followed by an `unlock` operation. The later will display a message regarding setting (and exporting) the `$BW_SESSION` env. var. When using the `bitwarden` lookup plugin, having the env. var. set and available (exported) to Ansible is critical. Without it, the plugin will simply return the error:
`Bitwarden Vault locked. Run 'bw unlock'.`
Make this clearer in the requirement documentation.
bitwarden
Example error with vault unlocked (`bw unlock`) but doing a `unset BW_SESSION` before running the playbook.
```paste below
TASK [debug] ************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin …
```
=> Minor bitwarden plugin req. docs addition

plugins/modules/ipa_dnsrecord.py
Just fixing a typo in the `record_values` field of the `ipa_dnsrecord` module's documentation.
ipa_dnsrecord
=> Fixed typo in record_values documentation

changelogs/fragments/6531-opentelemetry-add-event-attributes.yml, plugins/callback/opentelemetry.py
Enable populating span attributes to event attributes with OpenTelemetry in order to allow logs correlations with traces.
This is quite handy when the OTEL ventor does not show those details in the UI directly.
`opentelemetry`
https://github.com/ansible-collections/community.general/pull/4175 was the original implementation.
Closes https://github.com/ansible-collections/community.general/issues/6526
Given
```yaml
---
- name: MyPlabook
roles:
- role: myrole
tasks:
- name: MyTask2
uri:
url: https://www.elastic.co
return_content: no
register: webpage
```
And if I run with the logs:
```bash
OTEL_SERVICE_NAME=test-ansible \
OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317 \
OTEL_EXPORTER_OTLP_INSECURE=true \
ansible-playbook -i hosts …
```
=> opentelemetry: add span event attributes

changelogs/fragments/6644-dependencymixin-fix.yml, plugins/module_utils/mh/mixins/deps.py, tests/integration/targets/kernel_blacklist/tasks/main.yml
Add test to deprecated `DependencyMixin` so that the deprecation warning only pops up when dependencies are actually specified.
Fixes #6639 
plugins/module_utils/mh/mixins/deps.py
=> MH mh/mixins/deps.py: prevent deprecation warning when no deps are specified

changelogs/fragments/6646-redhat_subscription-deprecate-autosubscribe.yml, plugins/modules/redhat_subscription.py
The `autosubscribe` alias for the `auto_attach` option has been deprecated for many years, although only in the documentation. Officially mark it as deprecated also in the module parameters spec, slating it for removal in 9.0.0.
The short deprecation time is because of the following reasons:
- `auto_attach` was introduced many years ago, so even if you rely on e.g. Ansible 2.9, that option is there already
- migrating from `autosubscribe` to `auto_attach` is very easy 
=> redhat_subscription: officially deprecate "autosubscribe"

changelogs/fragments/6649-varsmixin-deprecation.yml, plugins/module_utils/mh/mixins/vars.py
Deprecate the classes `VarsMixin`, `VarDict` and `VarMeta` from the file `plugins/module_utils/mh/mixins/vars.py`.
plugins/module_utils/mh/mixins/vars.py
=> MH VarsMixin deprecation

changelogs/fragments/6650-redhat_subscription-deprecate-pool.yml, plugins/modules/redhat_subscription.py
The `pool` option is slower to use, and the regexp may expand to broader results than wanted. Because of that, deprecate it in favour of the `pool_ids` options (which is much better), slating it for removal in community.general 10.0.0.
=> redhat_subscription: deprecate "pool"

changelogs/fragments/6663-deprecate-module_utils-redhat.yml, plugins/module_utils/redhat.py
This module contains bits that are either unused (the `Rhsm*` classes), or used only by deprecated modules (the `RegistrationBase` class). Considering that the bits here have not seen updates in years, it is unlikely that anyone is actually using them as "library".
Hence, deprecate the whole module altogether:
- the `Rhsm*` classes, as not used by anything, are slated for removal in 9.0.0
- the `RegistrationBase` class is slated for removal in 10.0.0, together with its only user (i.e. the `rhn_register` module)
plugins/module_utils/redhat.py
=> Deprecate module_utils.redhat

changelogs/fragments/6658-redhat_subscription-internal-rhsm-refactor.yml, plugins/modules/redhat_subscription.py, tests/unit/plugins/modules/test_redhat_subscription.py
The two `RegistrationBase` & `Rhsm` classes were copied from the ones in the shared `module_utils.redhat` module; that said:
- the versions here got improvements over the years
- the `RegistrationBase` in `module_utils.redhat` is used only by the RHN modules, which are deprecated and slated for removal
Hence, the classes here can be kept and simplified a bit:
- fold the non-dummy content of `RegistrationBase` into `Rhsm`: there is no more need for the separate `RegistrationBase` base class
- drop the init arguments `username`, `password`, and `token`: the instance variables of them are not used anywhere, as the needed credentials (together with other variables) are passed to the `register()` method
- create the `Rhsm` object later in `main()`, after the `AnsibleModule` creation and the …
=> redhat_subscription: refactor of internal Rhsm class

changelogs/fragments/6647-vardict-methods.yml, plugins/module_utils/vardict.py, tests/unit/plugins/module_utils/test_vardict.py
Add convenience methods for variables and the `VarDict` class.
plugins/module_utils/vardict.py
=> VarDict: convenience methods

changelogs/fragments/6669-rhsm_release-internal-sub-man-exec.yml, plugins/modules/rhsm_release.py, tests/unit/plugins/modules/test_rhsm_release.py
- pass the arguments to `run_command()` directly as list, rather than joining the arguments to string, which `run_command()` will need to split again
- disable the expansions of variables, as there are none
Adapt the unit test to the different way `run_command()` is called, factorizing the kwargs for `run_command()` so there is less repetition.
There should be no behaviour changes.
rhsm_release
=> rhsm_release: improve the execution of subscription-manager

changelogs/fragments/6673-rhsm_repository-deprecate-present-absent.yml, plugins/modules/rhsm_repository.py
`state=present` is broken, and acts like `disabled`; also, the subscription repositories cannot be really "added" or "removed", which is what `present` and `absent` would imply, but only enabled or disabled. Hence, deprecate both these states, slating them for removal in community.general 10.0.0.
=> rhsm_repository: deprecate "state=present" and "state=absent"

.github/BOTMETA.yml, plugins/modules/gitlab_merge_request.py, tests/integration/targets/gitlab_merge_request/aliases, tests/integration/targets/gitlab_merge_request/defaults/main.yml, tests/integration/targets/gitlab_merge_request/files/description.md, tests/integration/targets/gitlab_merge_request/tasks/main.yml
A new Ansible module `gitlab_merge_request` for creating, updating, or deleting GitLab's merge requests.
`gitlab_merge_request`
A new Ansible module `gitlab_merge_request` for creating, updating, or deleting GitLab's merge request resources utilizing [python-gitlab](https://python-gitlab.readthedocs.io/en/stable/) library. This work is based on previously available GitLab-related modules in the collection. To the best of my knowledge, a similar module for manipulating Gitlab's merge requests is missing from the collection.
=> New module: gitlab_merge_request.py

changelogs/fragments/6469-add-composites-support-for-keycloak-role.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_role.py, tests/integration/targets/keycloak_role/README.md, tests/integration/targets/keycloak_role/tasks/main.yml, tests/integration/targets/keycloak_role/vars/main.yml, tests/unit/plugins/module_utils/identity/keycloak/test_keycloak_module_utils.py, tests/unit/plugins/modules/test_keycloak_role.py
Add support for composites roles for Keycloak. 
Composites can be managed for realm and client roles through the keycloak_role module.
keycloak_role.py
=> Inspq keycloak role composites

changelogs/fragments/6662-csv-bom.yml, plugins/module_utils/csv.py, tests/integration/targets/read_csv/meta/main.yml, tests/integration/targets/read_csv/tasks/main.yml
If CSV content contains a BOM marker then remove it from the content
Fixes #544 
plugins/module_utils/csv.py
=> csv module utils: detect unicode BOM in content

changelogs/fragments/6668-ldap-client-cert.yml, plugins/doc_fragments/ldap.py, plugins/module_utils/ldap.py, plugins/modules/ldap_attrs.py, plugins/modules/ldap_entry.py, plugins/modules/ldap_passwd.py, plugins/modules/ldap_search.py, tests/integration/targets/ldap_search/tasks/tests/auth.yml, tests/integration/targets/setup_openldap/files/cert_cnconfig.ldif, tests/integration/targets/setup_openldap/files/cert_cnconfig.ldif.license, tests/integration/targets/setup_openldap/files/initial_config.ldif, tests/integration/targets/setup_openldap/tasks/main.yml
Add new arguments ``client_cert`` and ``client_key`` to the ldap modules in order to allow certificate authentication.
Fixes #4066
plugins/module_utils/ldap.py
The functional part of the code is copied from work by @andrewshulgin with tests added by myself.
=> ldap: Add client certificate support

changelogs/fragments/6648_ldap_search_page_size.yml, plugins/modules/ldap_search.py, tests/integration/targets/ldap_search/tasks/tests/pages.yml, tests/integration/targets/ldap_search/tasks/tests/schema.yml, tests/integration/targets/setup_openldap/files/initial_config.ldif
Add a new ``page_size`` option to ldap_search to enable paged searches.
plugins/modules/ldap_search.py
=> plugins/modules/ldap_search: Add support for multipage searches

plugins/doc_fragments/alicloud.py, plugins/doc_fragments/bitbucket.py, plugins/doc_fragments/dimensiondata.py, plugins/doc_fragments/hwc.py, plugins/doc_fragments/influxdb.py, plugins/doc_fragments/ipa.py, plugins/doc_fragments/manageiq.py, plugins/doc_fragments/online.py, plugins/doc_fragments/opennebula.py, plugins/doc_fragments/openswitch.py, plugins/doc_fragments/oracle.py, plugins/doc_fragments/proxmox.py, plugins/doc_fragments/purestorage.py, plugins/doc_fragments/rackspace.py, plugins/doc_fragments/scaleway.py, plugins/doc_fragments/xenserver.py, plugins/inventory/lxd.py, plugins/lookup/bitwarden.py, plugins/lookup/etcd.py
With antsibull-docs 2.1.0 we can finally use `E(...)` as intended.
various
=> Semantic markup: use E() in more places

changelogs/fragments/ini_file-use-inactive-options-when-possible.yml, plugins/modules/ini_file.py, tests/integration/targets/ini_file/tasks/tests/02-values.yml
Not sure if this is a bug or not, but it definitely impacts specific scenarios. 
Code change updates the behavior of attempting to utilize already existing options that are commented out (i.e. inactive) by making them active with the new value, before creating a new option which leads to having both inactive and active options. 
It is considered a bug fix because of the default `php-fpm.conf` configuration which looks like this:
```ini
[global]
...
; Time limit for child processes to wait for a reaction on signals from master.
; Available units: s(econds), m(inutes), h(ours), or d(ays)
; Default Unit: seconds
; Default Value: 0
;process_control_timeout = 0
; ...
include=/etc/php/8.1/fpm/pool.d/*.conf
```
where the `pool.d/*.conf` is introducing a new section called `[www]` after the …
=> ini_file: try using inactive option before creating a new one

changelogs/fragments/6709-proxmox-create-vm-with-existing-name.yml, plugins/module_utils/proxmox.py, plugins/modules/proxmox_kvm.py, tests/unit/plugins/modules/test_proxmox_kvm.py
Fixes #6155.
Allow to create a VM if vmid is provided and it doesn't exist in the cluster, but name for that VM already exists.
proxmox_kvm
=> proxmox_kvm - Allow creation of VM with existing name but new vmid

changelogs/fragments/6680-filesystem-uuid-change.yml, plugins/modules/filesystem.py, tests/integration/targets/filesystem/defaults/main.yml, tests/integration/targets/filesystem/tasks/main.yml, tests/integration/targets/filesystem/tasks/reset_fs_uuid.yml, tests/integration/targets/filesystem/tasks/set_fs_uuid_on_creation.yml, tests/integration/targets/filesystem/tasks/set_fs_uuid_on_creation_with_opts.yml
Add a new feature to the filesystem module for managing UUID.
The feature does not break backward compatibility. It introduces an optional ``uuid`` parameter.
Rationale:
During disk cloning / lvm snapshot creation, the filesystem uuid remains the same. This new feature manages the filesystem UUID in an automated fashion.
filesystem
The ``version_added`` entry in the ``uuid`` parameter's documentation needs to be set.
=> filesystem: add UUID change feature

.github/BOTMETA.yml, plugins/modules/lvg_rename.py, tests/integration/targets/lvg_rename/aliases, tests/integration/targets/lvg_rename/meta/main.yml, tests/integration/targets/lvg_rename/tasks/main.yml, tests/integration/targets/lvg_rename/tasks/setup.yml, tests/integration/targets/lvg_rename/tasks/teardown.yml, tests/integration/targets/lvg_rename/tasks/test.yml, tests/unit/plugins/modules/test_lvg_rename.py
A new module to support Linux VG renaming.
The `lvg` module does not support VG renaming. An initial implementation was created for the #6682 PR, although it was too complicated. During the PR review process with @felixfontein, we agreed to separate the rename functionality to a dedicated `lvg_rename` module.
The module implementation wraps the `vgrename` command and is idempotent. 
Both unit and integration tests are available.
Rationale: 
During disk cloning, the VG and PV attributes remain the same. This new module supports the VG renaming in an automated, idempotent way.
lvg_rename
=> lvg_rename: New module to support VG renaming

plugins/modules/datadog_downtime.py
Datadog URL downtime api is invalid due to an extra 's' at the end. 
community.general.datadog_downtime module
=> Update Datadog downtime URL

changelogs/fragments/6676-rhsm_repository-fix-returned-repositories-with-purge.yml, plugins/modules/rhsm_repository.py
In case the `purge` option was enabled, the `repositories` element in the returned JSON was not updated with the repositories disabled by that option.
=> rhsm_repository: update returned "repositories" when using "purge=true"

.azure-pipelines/azure-pipelines.yml, README.md
The stable-5 branch should have been changed from devel to stable-2.15, instead of adding stable-2.15.
CI
=> [stable-5] CI: Remove ansible-core devel tests; should have stopped with stable-2.15

changelogs/fragments/6720-tss-fix-fetch-attachments.yml, plugins/lookup/tss.py
There are multiple issues present in the TSS lookup plugin when the recently added `fetch_attachments` is set to `True`:
- All files are written as text with UTF-8 encoding - this does not work for PFX files which have to be written in binary format
- An `AttributeError` is raised (`'str' object has no attribute 'text'`) when some attachments are missing from a secret. This is an issue, as some attachments may be optional (e.g. a secret can hold both a PFX and PEM format certificate in separate fields)
- Empty files get created for missing attachments, so an empty certificate may be uploaded to a target server if we are only checking for the file being present
tss
1. An `AttributeError` is raised when attachments are missing:
Before this PR (files get created for …
=> Fix multiple issues with the TSS lookup plugin when using fetch_attachments

tests/integration/targets/ipify_facts/aliases
Needs some special requirements on Python 2.6 so that it can contact the server.
These seem to be installed when running all tests. I don't want to figure out what exactly is missing, so let's just skip the tests on Python 2.6 for now.
ipify_facts integration tests
=> ipify_facts: skip tests on Python 2.6

tests/unit/plugins/modules/test_rhsm_repository.py
So far there are no tests for the `rhsm_repository` module, which makes it difficult to do even basic changes. Hence, add an initial version of unit tests, heavily based on the approach of the `redhat_subscription` unit tests.
=> rhsm_repository: add an initial unit test

changelogs/fragments/6719-redfish-utils-fix-for-get-volume-inventory.yml, plugins/module_utils/redfish_utils.py
SUMMARY
Fixing issues found in GetVolumeInventory. The issues are as below:
- Controller name can be found directly under each member of the storage API -> /redfish/v1/Systems/1/Storage/<ID>/. With the existing code the controller is not being populated as expected.
- The volumes collected are repeated in the subsequent controllers i.e., if Controller 1 has 2 volumes, the same 2 volumes are also displayed under Controller 2 along with any volumes in Controller 2.
ISSUE TYPE
COMPONENT NAME
Sample .yaml used
```
---
tasks:
- name: Get Volume Inventory
command: GetVolumeInventory
baseuri: "10.131.0.209"
username: "admin"
password: "HP1nvent"
- …
```
=> Fixing bug in get_volume_inventory

changelogs/fragments/6771-redfish-filter-empty-account-slots.yml, plugins/module_utils/redfish_utils.py
Fixes the output for the ListUsers command in redfish.info to suppress empty account slots for services that do not support POST/DELETE to add/remove users.
Fixex #6771 
redfish_info.py, redfish_utils.py
Sample playbook; requires a Redfish service that shows empty account slots (like an iDRAC on a Dell PowerEdge server)
```
---
- hosts: all
vars:
username: <REDACTED>
password: <REDACTED>
baseuri: <REDACTED>
default_uri_timeout: 5
default_uri_retries: 5
tasks:
- name: Get users
category: Accounts
command: ListUsers
retries: "{{ default_uri_retries }}"
register: redfish_results
- debug:
var: redfish_results
```
Before:
```paste below
ok: …
```
=> Redfish: Filter empty account slots from ListUsers

changelogs/fragments/6770-proxmox_disk_create_cdrom.yml, plugins/modules/proxmox_disk.py
proxmox_disk was always specifying the size when formatting the configuration string, which doesn't work when the `media` param is `cdrom`.
Fixes #6765.
proxmox_disk
=> proxmox_disk: fix failure to create cdrom

changelogs/fragments/6773-proxmox_kvm-restarted-state-bug-fix.yaml, plugins/modules/proxmox_kvm.py
Previously, the `restarted` state used both stop and start vm functions to restart a vm. In some cases, the start_vm function starts before the vm on Proxmox finishes shutting down. This causes the start_vm function to return saying that the vm is already running. The vm ends up in the `stopped` state and the output will wrongly display that the restart was successful. 
This change introduces the a new function that utilizes the Proxmox reboot endpoint instead for a more reliable method of restarting a vm.
proxmox_kvm
To reproduce this bug, have a running vm on Proxmox with these parameters set for High Availability:
Then run an Ansible playbook with the state set to `restarted`.
There may be other vm configurations in which the restart fails but this is the one I …
=> Module `proxmox_kvm` `restarted` state bug fix

changelogs/fragments/6763-keycloak-auth-provider-choices.yml, plugins/modules/keycloak_authentication.py
The provider ID according to Keycloak can only be basic-flow or client-flow, so I introduced choices for it.
This is a separate PR for minor changes I introduced in #6734. I did so, in order to have the bugfix backported.
=> Keycloak authentication provider ID choices

changelogs/fragments/6774-locale-gen-fix.yml, plugins/modules/locale_gen.py, tests/integration/targets/locale_gen/aliases, tests/integration/targets/locale_gen/tasks/basic.yml, tests/integration/targets/locale_gen/tasks/main.yml, tests/integration/targets/locale_gen/vars/main.yml
Fixed the regexp used to parse the available locales.
Fixes #5142 
Fixes #4305
locale_gen
=> locale_gen: works with C.UTF-8

changelogs/fragments/6783-rhsm_repository-internal-refactor.yml, plugins/modules/rhsm_repository.py, tests/unit/plugins/modules/test_rhsm_repository.py
Create a small helper class `Rhsm`, so all the logic related to the interaction with subscription-manager is grouped there:
- create the `Rhsm` object in `main()`, once the initial checks are done
- search `subscription-manager` as required (so there is no need to manually check it), and store its path for reuse
- store the common arguments for running `subscription-manager`
- move `run_subscription_manager()` to `Rhsm` as `run_repos()`
- get rid of the different list parameters: we list only all the repositories, so the other cases are not needed (and can be added easily, if needed)
- move `get_repository_list()` to `Rhsm` as `list_repositories()`
The execution of `subscription-manager` is improved as well:
- pass the arguments to `run_command()` directly as list, rather than joining the …
=> rhsm_repository: refactor handling of subscription-manager

changelogs/fragments/6757-proxmox-template-fix-upload-error.yml, plugins/module_utils/proxmox.py, plugins/modules/proxmox_template.py, tests/integration/targets/proxmox_template/aliases, tests/integration/targets/proxmox_template/tasks/main.yml, tests/unit/plugins/modules/test_proxmox_kvm.py, tests/unit/plugins/modules/test_proxmox_snap.py, tests/unit/plugins/modules/test_proxmox_tasks_info.py, tests/unit/plugins/modules/test_proxmox_template.py, tests/unit/requirements.txt, tests/utils/constraints.txt
Fixes #5579.
As per documentation from [proxmoxer](https://proxmoxer.github.io/docs/2.0/examples/files/) `requests_toolbelt` is required to upload large files.
Can't find the exact size of that **large file** definition, but from my personal testing on Darwin x86_64 it is around 260/261MB. Not sure where it is coming from, so can't explain it.
proxmox_template
Integration test output with updated module:
```
❯ ansible-test integration --allow-unsupported --local proxmox_template
Running proxmox_template integration test role
PLAY [testhost] ****************************************************************
TASK [Gathering Facts] *********************************************************
ok: [testhost]
TASK [proxmox_template : Create dummy ISO file] …
```
=> [proxmox_template] Fix error while uploading big ISO to Proxmox VE cluster

changelogs/fragments/6839-promoxer-tokens.yml, plugins/doc_fragments/proxmox.py, plugins/module_utils/proxmox.py
Add logic to detect whether an old Promoxer complains about the `token_name` and `token_value` parameters and provide a better error message when that happens.
Fixes #5371
plugins/module_utils/proxmox.py
=> proxmox module utils: better error msg when token fails with old proxmoxer

changelogs/fragments/6836-proxmox-deprecate-compatibility.yml, plugins/modules/proxmox.py
Deprecate parameter `proxmox_default_behavior` added in version 1.3.0.
plugins/modules/proxmox.py
=> proxmox: deprecate old compatibility feature flag

changelogs/fragments/6841-htpasswd-crypt-scheme.yml, plugins/modules/htpasswd.py
Technical nit-picking. What `htpasswd` does with the `.htpasswd` fiels used by Apache httpd is _hashing_, not _encrypting_. This PR renames the parameter `crypt_scheme` to `hash_scheme`, and add `crypt_scheme` as a deprecated alias of that option. It also updates the docs.
htpasswd
=> htpasswd: deprecate crypt_scheme

changelogs/fragments/6827-proxmox_kvm-force-delete-bug-fix.yaml, plugins/modules/proxmox_kvm.py
When attempting to force delete a VM, the module fails with the following error:
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "deletion of VM 102 failed with exception: ProxmoxKvmAnsible.stop_vm() missing 1 required positional argument: 'timeout'"}`
proxmox_kvm
This is caused by `proxmox_kvm` not passing the module's timeout argument to the `stop_vm()` method. This PR adds the passing of said timeout value.
Example task:
```yaml
- name: Force delete VM
community.general.proxmox_kvm:
name: "{{ vm_name }}"
state: absent
force: true
timeout: 60
```
=> proxmox_kvm: Add required timeout arg when force deleting

changelogs/fragments/6820-locale-gen-cmdrunner.yml, plugins/module_utils/locale_gen.py, plugins/modules/locale_gen.py
Refactor module to use `CmdRunner`.
locale_gen
=> locale_gen: refactor module to use CmdRunner

changelogs/fragments/6769-nmcli-fix-empty-list.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
Fixes #6574
nmcli
```paste below
```
=> nmcli: fix empty list to replace / remove values
