ansible-collections/community.general

changelogs/fragments/4650-zfs-improvements.yaml, plugins/modules/storage/zfs/zfs.py
Minor refactorings.
plugins/modules/storage/zfs/zfs.py
=> zfs: refactoring

changelogs/fragments/4649-rax-files-objects-improvements.yaml, plugins/modules/cloud/rackspace/rax_files_objects.py
- simplifications
- use of comprehensions
- better use of exceptions
- improvements on the documentation blob
- src and dest mutually exclusive in module definition
plugins/modules/cloud/rackspace/rax_files_objects.py
=> rax_files_objects: refactoring

changelogs/fragments/4648-vmadm-improvements-2.yaml, plugins/modules/cloud/smartos/vmadm.py
Mostly:
- simplifications
- adjusting comments
- minor changes
=> vmadm: minor refactoring

changelogs/fragments/4647-gconftool2-command-arg.yaml, plugins/modules/system/gconftool2.py
Changed the command parameter in `run_command()` from `str` to a `list`.
plugins/modules/system/gconftool2.py
=> gconftool2: improvements

PSF-license.txt
Follow-up to #4675. See https://github.com/ansible-collections/community.general/pull/4675#issuecomment-1127245658.
PSF-license.txt
=> [stable-4] Update with actual CPython 3.9.5 license

.azure-pipelines/azure-pipelines.yml, changelogs/fragments/4700-code-changes.yml, plugins/modules/system/filesystem.py, tests/integration/targets/cargo/tasks/setup.yml, tests/integration/targets/django_manage/aliases, tests/integration/targets/filesystem/tasks/main.yml, tests/integration/targets/homectl/aliases, tests/integration/targets/homectl/tasks/main.yml, tests/integration/targets/iso_extract/aliases, tests/integration/targets/iso_extract/meta/main.yml, tests/integration/targets/iso_extract/tasks/main.yml, tests/integration/targets/monit/tasks/main.yml, tests/integration/targets/mqtt/tasks/main.yml, tests/integration/targets/odbc/aliases, tests/integration/targets/pkgng/tasks/freebsd.yml, tests/integration/targets/setup_epel/tasks/main.yml, tests/integration/targets/setup_openssl/vars/RedHat-9.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-22-py3.yml, tests/integration/targets/setup_snap/aliases, tests/integration/targets/setup_snap/meta/main.yml, tests/integration/targets/setup_snap/tasks/D-RedHat-9.0.yml, tests/integration/targets/setup_snap/tasks/main.yml, tests/integration/targets/ufw/aliases, tests/integration/targets/ufw/tasks/main.yml
See https://github.com/ansible/ansible/pull/77851
CI
=> Add RHEL 9.0, FreeBSD 13.1, Ubuntu 22.04 and Fedora 36 to CI, fix bug in filesystem module

plugins/modules/remote_management/redfish/idrac_redfish_command.py, plugins/modules/remote_management/redfish/idrac_redfish_config.py, plugins/modules/remote_management/redfish/idrac_redfish_info.py, plugins/modules/remote_management/redfish/ilo_redfish_config.py, plugins/modules/remote_management/redfish/ilo_redfish_info.py, plugins/modules/remote_management/redfish/redfish_command.py, plugins/modules/remote_management/redfish/redfish_config.py, plugins/modules/remote_management/redfish/redfish_info.py
Update the documentation block with more English language
more consistent with other modules; finish each description
with a full stop and start with capital case letter.
Use consistent language and terminology within each module/group
of modules.
all remote_management/redfish plugins
```paste below
```
=> redfish modules: documentation language and formatting

.github/BOTMETA.yml, meta/runtime.yml, plugins/module_utils/gconftool2.py, plugins/modules/system/gconftool2_info.py, tests/unit/plugins/modules/system/test_gconftool2_info.py
New module to retrieve information from `gconftool-2`.
plugins/modules/system/gconftool2_info.py
=> gconftool2_info: new module

tests/utils/constraints.txt
CI is failling because of this.
CI
=> requests drops support for older Python

.azure-pipelines/azure-pipelines.yml
See https://github.com/ansible-collections/news-for-maintainers/issues/18
CI
=> Bump AZP container version

plugins/modules/cloud/misc/proxmox_kvm.py
=> proxmox_kvm: fix typos

.github/BOTMETA.yml, meta/runtime.yml, plugins/modules/cloud/scaleway/scaleway_compute_private_network.py, plugins/modules/scaleway_compute_private_network.py, tests/unit/plugins/modules/cloud/scaleway/test_scaleway_compute_private_network.py
Add  module scaleway_compute_private_network.
scaleway_compute_private_network
Module toadd or remove a private network  to a compute ( ~ a VM )  in scaleay provider
=> Add scw_compute_private_network

.github/BOTMETA.yml
I do not use `zypper` anymore and can thus not help with issues regarding the zypper module.
=> Remove myself from team_suse

.github/workflows/docs-pr.yml
Allows to add actual content in follow-up PRs so that the content is already executed. Or at least I hope so :)
CI
=> Add empty PR docs workflow

.github/workflows/docs-pr.yml
CC @briantist
Try 2, branch in the repo, let's see whether the actions run here then :)
bot_skip
CI
=> [WIP] Add PR docs workflow

plugins/modules/cloud/lxd/lxd_container.py, plugins/modules/cloud/misc/serverless.py, plugins/modules/cloud/misc/terraform.py, plugins/modules/cloud/rackspace/rax_mon_check.py, plugins/modules/cloud/scaleway/scaleway_user_data.py, plugins/modules/clustering/consul/consul_kv.py, plugins/modules/monitoring/datadog/datadog_event.py, plugins/modules/net_tools/haproxy.py, plugins/modules/packaging/language/pip_package_info.py, plugins/modules/packaging/os/apk.py, plugins/modules/packaging/os/homebrew.py, plugins/modules/packaging/os/openbsd_pkg.py, plugins/modules/packaging/os/pkgng.py, plugins/modules/packaging/os/pulp_repo.py, plugins/modules/packaging/os/zypper.py, plugins/modules/remote_management/hpilo/hponcfg.py, plugins/modules/source_control/hg.py, plugins/modules/storage/zfs/zfs_delegate_admin.py, plugins/modules/system/nosh.py, plugins/modules/web_infrastructure/jira.py
Should allow #4880 to pass. (CI for this one should pass due to https://github.com/ansible-community/github-docs-build/pull/48.)
various modules
=> Fix various module docs

plugins/modules/cloud/lxd/lxd_container.py, plugins/modules/cloud/misc/serverless.py, plugins/modules/cloud/misc/terraform.py, plugins/modules/cloud/rackspace/rax_mon_check.py, plugins/modules/cloud/scaleway/scaleway_user_data.py, plugins/modules/clustering/consul/consul_kv.py, plugins/modules/monitoring/datadog/datadog_event.py, plugins/modules/net_tools/haproxy.py, plugins/modules/packaging/language/pip_package_info.py, plugins/modules/packaging/os/apk.py, plugins/modules/packaging/os/homebrew.py, plugins/modules/packaging/os/openbsd_pkg.py, plugins/modules/packaging/os/pkgng.py, plugins/modules/packaging/os/pulp_repo.py, plugins/modules/packaging/os/zypper.py, plugins/modules/remote_management/hpilo/hponcfg.py, plugins/modules/source_control/hg.py, plugins/modules/storage/zfs/zfs_delegate_admin.py, plugins/modules/system/nosh.py, plugins/modules/web_infrastructure/jira.py
Manual backport of #4887 to stable-4.
various modules
=> [stable-4] Fix various module docs

plugins/modules/cloud/lxd/lxd_container.py, plugins/modules/cloud/misc/serverless.py, plugins/modules/cloud/misc/terraform.py, plugins/modules/cloud/rackspace/rax_mon_check.py, plugins/modules/cloud/scaleway/scaleway_user_data.py, plugins/modules/clustering/consul/consul_kv.py, plugins/modules/monitoring/datadog/datadog_event.py, plugins/modules/net_tools/haproxy.py, plugins/modules/packaging/language/pip_package_info.py, plugins/modules/packaging/os/apk.py, plugins/modules/packaging/os/homebrew.py, plugins/modules/packaging/os/openbsd_pkg.py, plugins/modules/packaging/os/pkgng.py, plugins/modules/packaging/os/pulp_repo.py, plugins/modules/packaging/os/zypper.py, plugins/modules/remote_management/hpilo/hponcfg.py, plugins/modules/source_control/hg.py, plugins/modules/storage/zfs/zfs_delegate_admin.py, plugins/modules/system/nosh.py, plugins/modules/web_infrastructure/jira.py
Manual backport of #4887 to stable-3.
various modules
=> [stable-3] Fix various module docs

plugins/module_utils/ilo_redfish_utils.py, plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/lenovoxcc/xcc_redfish_command.py, plugins/modules/remote_management/redfish/idrac_redfish_command.py, plugins/modules/remote_management/redfish/idrac_redfish_config.py, plugins/modules/remote_management/redfish/idrac_redfish_info.py, plugins/modules/remote_management/redfish/ilo_redfish_config.py, plugins/modules/remote_management/redfish/ilo_redfish_info.py, plugins/modules/remote_management/redfish/redfish_command.py, plugins/modules/remote_management/redfish/redfish_config.py, plugins/modules/remote_management/redfish/redfish_info.py
The file is called `COPYING`, not `LICENSE`.
various files
=> Fix license filenames

plugins/module_utils/redfish_utils.py, plugins/modules/remote_management/lenovoxcc/xcc_redfish_command.py, plugins/modules/remote_management/redfish/idrac_redfish_command.py, plugins/modules/remote_management/redfish/idrac_redfish_config.py, plugins/modules/remote_management/redfish/idrac_redfish_info.py, plugins/modules/remote_management/redfish/redfish_command.py, plugins/modules/remote_management/redfish/redfish_config.py, plugins/modules/remote_management/redfish/redfish_info.py
Backport of #4923 to stable-3.
various files
=> [stable-3] Fix license filenames

tests/integration/targets/connection/test.sh
Try to fix some of the current CI issues.
CI
=> Fix connection integration tests

.github/BOTMETA.yml, plugins/modules/packaging/os/yum_versionlock.py
Updating my authors name to my new account (for notifications regarding this module). Keeping this account for security reasons. 
```paste below
```
=> Update to new Github account for notifications

plugins/become/sudosu.py
This PR fixes some minor documentation issues found in the sudosu become plugin.
plugin become sudosu
Simply aligning/updating the style of the documentation.
=> fixing minor documentation flaws

tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt
Add comment to the sanity test ignore files for `vmadm`.
vmadm
=> vmadm: add comment to ignore file

.github/BOTMETA.yml, plugins/lookup/bitwarden.py, tests/unit/plugins/lookup/test_bitwarden.py
Support for looking up information on Bitwarden-compatible servers.
`bitwarden`
Largely based on the existing LastPass lookup which uses invocations of the LastPass CLI.
=> New lookup plug-in: bitwarden

tests/integration/targets/cargo/tasks/main.yml
Works around failing CI; see https://github.com/rust-lang/cargo/issues/10230#issuecomment-1201662729 for details.
cargo
=> cargo: set CARGO_NET_GIT_FETCH_WITH_CLI=true on Alpine in CI

MIT-license.txt, changelogs/fragments/licenses.yml, tests/unit/plugins/modules/packaging/language/test_gem.py
Partial backport of #5065 to stable-4.
MIT-license.txt
=> [stable-4] Add MIT-license.txt

tests/integration/targets/ldap_search/tasks/run-test.yml
As pointed out by @gotmax in https://github.com/ansible-collections/community.general/pull/5074#discussion_r938747537.
ldap_search integration tests
=> Remove superfluous empty file

.azure-pipelines/azure-pipelines.yml
See https://github.com/ansible-collections/news-for-maintainers/issues/21.
CI
=> CI: Remove Fedora 35 from devel CI runs

plugins/doc_fragments/auth_basic.py, plugins/doc_fragments/dimensiondata.py, plugins/doc_fragments/dimensiondata_wait.py, plugins/doc_fragments/influxdb.py, plugins/doc_fragments/ipa.py, plugins/doc_fragments/keycloak.py, plugins/doc_fragments/ldap.py, plugins/doc_fragments/manageiq.py, plugins/doc_fragments/oneview.py, plugins/doc_fragments/online.py, plugins/doc_fragments/opennebula.py, plugins/doc_fragments/openswitch.py, plugins/doc_fragments/oracle_wait_options.py, plugins/doc_fragments/proxmox.py, plugins/doc_fragments/scaleway.py, plugins/doc_fragments/utm.py, plugins/doc_fragments/vexata.py, plugins/doc_fragments/xenserver.py
=> Adjust booleans in doc fragments

plugins/modules/monitoring/airbrake_deployment.py, plugins/modules/monitoring/bigpanda.py, plugins/modules/monitoring/datadog/datadog_event.py, plugins/modules/monitoring/datadog/datadog_monitor.py, plugins/modules/monitoring/honeybadger_deployment.py, plugins/modules/monitoring/icinga2_host.py, plugins/modules/monitoring/newrelic_deployment.py, plugins/modules/monitoring/pagerduty.py, plugins/modules/monitoring/pagerduty_change.py, plugins/modules/monitoring/rollbar_deployment.py, plugins/modules/monitoring/sensu/sensu_check.py, plugins/modules/monitoring/sensu/sensu_client.py, plugins/modules/monitoring/sensu/sensu_handler.py, plugins/modules/monitoring/sensu/sensu_subscription.py, plugins/modules/monitoring/spectrum_device.py, plugins/modules/monitoring/spectrum_model_attrs.py, plugins/modules/monitoring/statusio_maintenance.py
=> Adjust booleans in monitoring modules

plugins/modules/notification/bearychat.py, plugins/modules/notification/cisco_webex.py, plugins/modules/notification/discord.py, plugins/modules/notification/flowdock.py, plugins/modules/notification/grove.py, plugins/modules/notification/hipchat.py, plugins/modules/notification/irc.py, plugins/modules/notification/mail.py, plugins/modules/notification/mattermost.py, plugins/modules/notification/mqtt.py, plugins/modules/notification/nexmo.py, plugins/modules/notification/rocketchat.py, plugins/modules/notification/sendgrid.py, plugins/modules/notification/slack.py
=> Adjust booleans in notification modules

plugins/modules/source_control/bitbucket/bitbucket_pipeline_variable.py, plugins/modules/source_control/bzr.py, plugins/modules/source_control/git_config.py, plugins/modules/source_control/github/github_deploy_key.py, plugins/modules/source_control/github/github_key.py, plugins/modules/source_control/github/github_release.py, plugins/modules/source_control/github/github_repo.py, plugins/modules/source_control/gitlab/gitlab_deploy_key.py, plugins/modules/source_control/gitlab/gitlab_hook.py, plugins/modules/source_control/gitlab/gitlab_project.py, plugins/modules/source_control/gitlab/gitlab_project_variable.py, plugins/modules/source_control/gitlab/gitlab_runner.py, plugins/modules/source_control/gitlab/gitlab_user.py, plugins/modules/source_control/hg.py
=> Adjust booleans in source control modules

plugins/modules/clustering/consul/consul.py, plugins/modules/clustering/consul/consul_kv.py, plugins/modules/clustering/pacemaker_cluster.py, plugins/modules/clustering/znode.py, plugins/modules/net_tools/cloudflare_dns.py, plugins/modules/net_tools/dnsimple.py, plugins/modules/net_tools/dnsmadeeasy.py, plugins/modules/net_tools/haproxy.py, plugins/modules/net_tools/ipify_facts.py, plugins/modules/net_tools/ldap/ldap_attrs.py, plugins/modules/net_tools/nmcli.py, plugins/modules/net_tools/omapi_host.py, plugins/modules/net_tools/pritunl/pritunl_user.py, plugins/modules/web_infrastructure/apache2_mod_proxy.py, plugins/modules/web_infrastructure/deploy_helper.py, plugins/modules/web_infrastructure/django_manage.py, plugins/modules/web_infrastructure/htpasswd.py, plugins/modules/web_infrastructure/jenkins_job.py, plugins/modules/web_infrastructure/jenkins_plugin.py, plugins/modules/web_infrastructure/jenkins_script.py
=> Adjust booleans in net tools, web infrastructure, and clustering modules

plugins/modules/database/influxdb/influxdb_database.py, plugins/modules/database/influxdb/influxdb_retention_policy.py, plugins/modules/database/influxdb/influxdb_user.py, plugins/modules/database/misc/elasticsearch_plugin.py, plugins/modules/database/misc/odbc.py, plugins/modules/database/misc/riak.py, plugins/modules/database/mssql/mssql_db.py, plugins/modules/files/archive.py, plugins/modules/files/ini_file.py, plugins/modules/files/iso_create.py, plugins/modules/files/iso_extract.py, plugins/modules/files/read_csv.py, plugins/modules/files/xml.py, plugins/modules/identity/ipa/ipa_group.py, plugins/modules/identity/keycloak/keycloak_client.py, plugins/modules/identity/keycloak/keycloak_realm_info.py, plugins/modules/remote_management/cobbler/cobbler_sync.py, plugins/modules/remote_management/cobbler/cobbler_system.py, plugins/modules/remote_management/hpilo/hpilo_boot.py, plugins/modules/remote_management/hpilo/hponcfg.py, plugins/modules/remote_management/imc/imc_rest.py, plugins/modules/remote_management/ipmi/ipmi_boot.py, plugins/modules/remote_management/manageiq/manageiq_provider.py, plugins/modules/remote_management/stacki/stacki_host.py, plugins/modules/storage/hpe3par/ss_3par_cpg.py, plugins/modules/storage/zfs/zfs_delegate_admin.py, plugins/modules/storage/zfs/zfs_facts.py
=> Adjust booleans in misc modules

plugins/modules/packaging/os/xbps.py
One change that I forgot to push during the true/false cleanups.
xbps
=> Fix indent

tests/integration/targets/setup_remote_tmp_dir_outside_tmp/handlers/main.yml, tests/integration/targets/setup_remote_tmp_dir_outside_tmp/tasks/default-cleanup.yml, tests/integration/targets/setup_remote_tmp_dir_outside_tmp/tasks/default.yml, tests/integration/targets/setup_remote_tmp_dir_outside_tmp/tasks/main.yml
Fixes some CI issues due to https://github.com/ansible/ansible/commit/4187707f035a5dde9d02e99e5dec40d71b06d5d1.
filesystem integration tests
=> CI: filesystem: create temp directory outside /tmp to avoid problems with tmpfs

.github/BOTMETA.yml, meta/runtime.yml, plugins/modules/packaging/language/pipx_info.py, tests/integration/targets/pipx_info/aliases, tests/integration/targets/pipx_info/tasks/main.yml
Adds the module `pipx_info`
plugins/modules/packaging/language/pipx_info.py
=> New module: pipx_info

plugins/modules/net_tools/ipwcli_dns.py
Fixed references from C(param=value) to I(param=value).
ipwcli_dns
=> ipwcli_dns: fixed markups in doc

plugins/modules/cloud/alicloud/ali_instance.py
Fixed references from C(param=value) to I(param=value).
ali_instance
=> ali_instance: fixed markups in doc

plugins/modules/packaging/language/composer.py, plugins/modules/packaging/os/layman.py, plugins/modules/packaging/os/pacman.py, plugins/modules/packaging/os/pkgng.py, plugins/modules/packaging/os/pkgutil.py, plugins/modules/packaging/os/sorcery.py, plugins/modules/packaging/os/svr4pkg.py, plugins/modules/packaging/os/zypper.py, plugins/modules/remote_management/cobbler/cobbler_system.py, plugins/modules/source_control/github/github_key.py, plugins/modules/system/dconf.py, plugins/modules/system/open_iscsi.py, plugins/modules/system/osx_defaults.py, plugins/modules/web_infrastructure/htpasswd.py
Fixed references from C(param=value) to I(param=value).
plugins/modules/packaging/language/composer.py
plugins/modules/packaging/os/layman.py
plugins/modules/packaging/os/pacman.py
plugins/modules/packaging/os/pkgng.py
plugins/modules/packaging/os/pkgutil.py
plugins/modules/packaging/os/sorcery.py
plugins/modules/packaging/os/svr4pkg.py
plugins/modules/packaging/os/zypper.py
plugins/modules/remote_management/cobbler/cobbler_system.py
plugins/modules/source_control/github/github_key.py
plugins/modules/system/dconf.py
plugins/modules/system/open_iscsi.py
plugins/modules/system/osx_defaults.py
plugins/modules/web_infrastructure/htpasswd.py
=> multiple modules: fixed markups in doc

plugins/modules/cloud/misc/proxmox_template.py, plugins/modules/cloud/opennebula/one_service.py, plugins/modules/cloud/rackspace/rax_cbs.py, plugins/modules/net_tools/haproxy.py, plugins/modules/net_tools/netcup_dns.py, plugins/modules/system/cronvar.py, plugins/modules/system/filesystem.py, plugins/modules/web_infrastructure/deploy_helper.py, plugins/modules/web_infrastructure/jenkins_job.py
Fixed references from C(param=value) to I(param=value), plus a couple of extra docs adjustments.
plugins/modules/cloud/misc/proxmox_template.py
plugins/modules/cloud/opennebula/one_service.py
plugins/modules/cloud/rackspace/rax_cbs.py
plugins/modules/net_tools/haproxy.py
plugins/modules/net_tools/netcup_dns.py
plugins/modules/system/cronvar.py
plugins/modules/system/filesystem.py
plugins/modules/web_infrastructure/deploy_helper.py
plugins/modules/web_infrastructure/jenkins_job.py
=> multiple modules 2: fixed markups in doc

plugins/modules/cloud/misc/proxmox_template.py, plugins/modules/cloud/opennebula/one_service.py, plugins/modules/cloud/rackspace/rax_cbs.py, plugins/modules/cloud/univention/udm_dns_record.py, plugins/modules/cloud/univention/udm_dns_zone.py, plugins/modules/cloud/univention/udm_share.py, plugins/modules/cloud/univention/udm_user.py, plugins/modules/cloud/webfaction/webfaction_domain.py, plugins/modules/files/ini_file.py, plugins/modules/files/iso_extract.py, plugins/modules/files/xml.py, plugins/modules/monitoring/nagios.py, plugins/modules/monitoring/spectrum_device.py, plugins/modules/net_tools/cloudflare_dns.py, plugins/modules/net_tools/haproxy.py, plugins/modules/net_tools/netcup_dns.py, plugins/modules/system/cronvar.py, plugins/modules/system/filesystem.py, plugins/modules/web_infrastructure/deploy_helper.py, plugins/modules/web_infrastructure/jenkins_job.py
Fixed references from C(param=value) to I(param=value), plus a couple of extra docs adjustments.
plugins/modules/cloud/univention/udm_dns_record.py
plugins/modules/cloud/univention/udm_dns_zone.py
plugins/modules/cloud/univention/udm_share.py
plugins/modules/cloud/univention/udm_user.py
plugins/modules/cloud/webfaction/webfaction_domain.py
plugins/modules/files/ini_file.py
plugins/modules/files/iso_extract.py
plugins/modules/files/xml.py
plugins/modules/monitoring/nagios.py
plugins/modules/monitoring/spectrum_device.py
plugins/modules/net_tools/cloudflare_dns.py
=> Multiple doc fix 3

changelogs/fragments/5243-osx-defaults-expand-user-flags.yml, plugins/modules/system/osx_defaults.py
Fixes #5234
osx defaults
cf #5234
=> osx_defaults: add expand_user_and_vars flag to write

tests/integration/targets/pkgng/tasks/freebsd.yml
Now there are problems with FreeBSD 13.0.
pkgng
=> Fix pkgng tests

changelogs/fragments/5202-bugfix-environmentError-wrong-indentation.yaml, changelogs/fragments/5239-nagios-refactor.yaml
The suggestions feature sometimes multilates URLs. Fixing the ones we didn't spot in time.
changelog fragments
=> Fix changelog fragments mutilated by GitHub

changelogs/fragments/5259-gitlab-imports.yaml, plugins/module_utils/gitlab.py, plugins/modules/source_control/gitlab/gitlab_branch.py, plugins/modules/source_control/gitlab/gitlab_deploy_key.py, plugins/modules/source_control/gitlab/gitlab_group.py, plugins/modules/source_control/gitlab/gitlab_group_members.py, plugins/modules/source_control/gitlab/gitlab_group_variable.py, plugins/modules/source_control/gitlab/gitlab_hook.py, plugins/modules/source_control/gitlab/gitlab_project.py, plugins/modules/source_control/gitlab/gitlab_project_members.py, plugins/modules/source_control/gitlab/gitlab_project_variable.py, plugins/modules/source_control/gitlab/gitlab_protected_branch.py, plugins/modules/source_control/gitlab/gitlab_runner.py, plugins/modules/source_control/gitlab/gitlab_user.py
Improved imports on  the gitlab modules
plugins/module_utils/gitlab.py
plugins/modules/source_control/gitlab/gitlab_branch.py
plugins/modules/source_control/gitlab/gitlab_deploy_key.py
plugins/modules/source_control/gitlab/gitlab_group.py
plugins/modules/source_control/gitlab/gitlab_group_members.py
plugins/modules/source_control/gitlab/gitlab_group_variable.py
plugins/modules/source_control/gitlab/gitlab_hook.py
plugins/modules/source_control/gitlab/gitlab_project.py
plugins/modules/source_control/gitlab/gitlab_project_members.py
plugins/modules/source_control/gitlab/gitlab_project_variable.py
plugins/modules/source_control/gitlab/gitlab_protected_branch.py
plugins/modules/source_control/gitlab/gitlab_runner.py
plugins/modules/source_control/gitlab/gitlab_user.py
=> gitlab modules: improved imports

.azure-pipelines/azure-pipelines.yml, README.md, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.15.txt.license
Backport of #5298 to stable-5.
CI
=> [stable-5] Add stable-2.14 to CI, adjust to devel version bump

changelogs/fragments/5281-locale_gen.yaml, changelogs/fragments/5282-locale_gen.yaml, plugins/modules/system/locale_gen.py
When I tried to use locales_gen module in my playbook to manage locales in Ubuntu 22.04 it did nothing.
Now it works properly.
#5281
locale_gen module
```paste below
```
=> locale_gen: fix UbuntuMode

.github/BOTMETA.yml, meta/runtime.yml, plugins/module_utils/manageiq.py, plugins/modules/remote_management/manageiq/manageiq_policies_info.py, plugins/modules/remote_management/manageiq/manageiq_provider.py
Refactoring out the `list` part of `manageiq_provider`.
plugins/modules/remote_management/manageiq/manageiq_policies_info.py
=> manageiq_policies_info: new module

plugins/modules/remote_management/manageiq/manageiq_provider.py
Added missing aliases to docs.
plugins/modules/remote_management/manageiq/manageiq_provider.py
=> manageiq_provider: added missing aliases to documentation

changelogs/fragments/5383-xenserver_facts.yml, plugins/modules/cloud/misc/xenserver_facts.py
=> fix xenserver_facts module

changelogs/fragments/5393-archive.yml, plugins/modules/files/archive.py, tests/integration/targets/archive/tasks/main.yml
=> archive: do not crash when lzma is not around

plugins/modules/packaging/os/portage.py
I'm not sure if this could be considered a bug, it's just a couple misc fixes that should've made it into the other PR. No code changes, so no command output relevant.
=> portage: update comment, drop gentoolkit requirement

.github/BOTMETA.yml, meta/runtime.yml, plugins/module_utils/manageiq.py, plugins/modules/remote_management/manageiq/manageiq_tags.py, plugins/modules/remote_management/manageiq/manageiq_tags_info.py
Refactored the `list` behaviour out of `manageiq_tags` into utils and create a new module `manageiq_tags_info` that does the same thing.
plugins/modules/remote_management/manageiq/manageiq_tags_info.py
=> manageiq_tags_info: new module

changelogs/fragments/5369-pkgng-fix-update-all.yaml, plugins/modules/packaging/os/pkgng.py, tests/integration/targets/pkgng/tasks/freebsd.yml
The return code of the command was being ignored when upgrading all packages.
Fixes #5363 
pkgng
=> pkgng: fix error-handling when upgrading all

tests/integration/targets/iso_customize/meta/main.yml, tests/integration/targets/iso_customize/tasks/prepare.yml
They won't run on its own.
iso_customize
=> Fix iso_customize tests

changelogs/fragments/5457-dnstxt-empty.yml, plugins/lookup/dnstxt.py
Analogue of #5439 for dnstxt: completes #5428.
dnstxt lookup
=> dnstxt lookup - add option to return empty list

.github/BOTMETA.yml, meta/runtime.yml, plugins/module_utils/scaleway.py, plugins/modules/cloud/scaleway/scaleway_function_namespace.py, plugins/modules/cloud/scaleway/scaleway_function_namespace_info.py, tests/integration/targets/scaleway_function_namespace/aliases, tests/integration/targets/scaleway_function_namespace/defaults/main.yml, tests/integration/targets/scaleway_function_namespace/tasks/main.yml, tests/integration/targets/scaleway_function_namespace_info/aliases, tests/integration/targets/scaleway_function_namespace_info/defaults/main.yml, tests/integration/targets/scaleway_function_namespace_info/tasks/main.yml, tests/unit/plugins/module_utils/cloud/test_scaleway.py, tests/unit/requirements.txt
This PR add new modules to manage Scaleway function namespaces services (https://developers.scaleway.com/).
- `scaleway_function_namespace`
- `scaleway_function_namespace_info`
This PR is a part of the original PR #5359 that was too large.
This PR require evolution on Scaleway config in ansible-test : https://github.com/ansible/ansible/pull/79141
=> [Scaleway] Add module to manage function namespaces

tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
After the flattening of the modules' directories, the ignore files became unsorted.
=> sorted content of sanity/ignore-*.txt files

.github/BOTMETA.yml, plugins/modules/scaleway_function.py, plugins/modules/scaleway_function_info.py, tests/integration/targets/scaleway_function/aliases, tests/integration/targets/scaleway_function/defaults/main.yml, tests/integration/targets/scaleway_function/tasks/main.yml, tests/integration/targets/scaleway_function_info/aliases, tests/integration/targets/scaleway_function_info/defaults/main.yml, tests/integration/targets/scaleway_function_info/tasks/main.yml
This PR add new modules to manage Scaleway functions services (https://developers.scaleway.com/).
- `scaleway_function`
- `scaleway_function_info`
This PR is a part of the original PR #5359 that was too large.
This PR require evolution on Scaleway config in ansible-test : https://github.com/ansible/ansible/pull/79141
=> [Scaleway] Add module to manage functions

.github/BOTMETA.yml
After directory structure was removed, it's time to re-sort.
CC @russoz
=> Sort BOTMETA

tests/integration/targets/django_manage/files/base_test/simple_project/p1/p1/settings.py, tests/integration/targets/django_manage/tasks/main.yaml
Add an extra test to prove the case of #5374 .
django_manage
=> django_manage: add extra tests

changelogs/fragments/5477-ansible-galaxy-install-cmd-runner.yml, plugins/modules/ansible_galaxy_install.py
Refactored module to use `CmdRunner` instead of `CmdMixin` from `ModuleHelper`.
plugins/modules/ansible_galaxy_install.py
=> ansible_galaxy_install: using CmdRunner

.azure-pipelines/azure-pipelines.yml, plugins/modules/one_image.py, plugins/modules/one_image_info.py, plugins/modules/one_service.py, plugins/modules/one_vm.py
These were so unexpected that I completely missed them :)
one_image
one_image_info
one_service
one_vm
=> Convert copyright docstings to proper copyright comments

changelogs/fragments/5483-hponcfg-cmd-runner.yml, plugins/modules/hponcfg.py
hponcfg now using `CmdRunner` instead of `CmdModuleHelper` 
plugins/modules/hponcfg.py
=> hponcfg: using CmdRunner

.github/BOTMETA.yml
See https://github.com/ansible-collections/community.general/pull/5521#issuecomment-1308772643.
=> Ignore mpdehaan in BOTMETA

.github/workflows/codeql-analysis.yml
Maybe this gets it working again.
Would be help if GHA would be more helpful at informing maintainers about broken actions...
.github/workflows/codeql-analysis.yml
=> Clean up code-scanning workflow

changelogs/fragments/5549-lxd-project-sanity.yml, plugins/module_utils/lxd.py, plugins/modules/lxd_project.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Refactored code to remove sanity ignore line.
plugins/modules/lxd_project.py
=> lxd_project: refactored os.path.expanduser() to module utils

changelogs/fragments/5553-spotinst-aws-elasticgroup-sanity.yml, plugins/modules/spotinst_aws_elastigroup.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Fixed sanity checks for module.
plugins/modules/spotinst_aws_elastigroup.py
=> spotinst_aws_elasticgroup: sanity checks

plugins/modules/redhat_subscription.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Fix sanity check on return docs.
plugins/modules/redhat_subscription.py
=> redhat_subscription: fix sanity check

.github/BOTMETA.yml, plugins/module_utils/deps.py, plugins/modules/dnsimple_info.py, plugins/modules/iso_customize.py, plugins/modules/pagerduty_user.py, plugins/modules/pids.py, plugins/modules/snmp_facts.py
Add a dependency context manager.
plugins/module_utils/deps.py
plugins/modules/dnsimple_info.py
plugins/modules/iso_customize.py
plugins/modules/pagerduty_user.py
plugins/modules/pids.py
plugins/modules/snmp_facts.py
=> add dependency manager

.github/workflows/codeql-analysis.yml
Let's try this before #5586.
CI
=> Failing CodeQL workflow: another try: fix languages to check

changelogs/fragments/3910-redfish-add-operation-apply-time-to-simple-update.yml, changelogs/fragments/4276-redfish-command-updates-for-full-simple-update-workflow.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_command.py, plugins/modules/redfish_info.py
The Redfish Forum published a firmware update white paper last year that walked through a standard end-to-end workflow for performing firmware updates. This change expands the Redfish module in a few areas:
* Allows an "operation apply time" parameter to be specified as part of the SimpleUpdate command
* Adds response data to the SimpleUpdate command
* The response data contains a "handle" used by a user to monitor the progress of the update
* It also contains other status information about the update itself
* Adds a GetUpdateStatus command to check the progress of an update request
* The "handle" obtained from the SimpleUpdate request or the previous GetUpdateStatus command is passed in
* The response contains the same status structure returned from SimpleUpdate; it's possible the handle …
=> Redfish: Expanded SimpleUpdate command to allow for users to monitor the progress of an update and perform follow-up operations

changelogs/fragments/5557-udm-share-sanity.yml, plugins/modules/udm_share.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Fix sanity check in the module by adding `elements` to the `list` parameters.
plugins/modules/udm_share.py
=> udm_share: fix sanity checks

changelogs/fragments/sap-removal.yml
Announce #5592 in the 6.x.y changelog.
changelog
=> [stable-6] Announce removal of sap modules

changelogs/fragments/5490-adding-put-functionality.yml, plugins/module_utils/redfish_utils.py
SUMMARY
Adding PUT functionality to redfish_utils.py
ISSUE TYPE
COMPONENT NAME
This was raised as part of PR https://github.com/ansible-collections/community.general/pull/5328, but raising it here to allow for easy merge. Will remove it from the old PR.
The old PR was closed because of deleting the branch [5490](https://github.com/ansible-collections/community.general/pull/5490). Apologies for the inconvenience.
=> Adding PUT functionality to redfish_utils (Updated)

changelogs/fragments/5687-gconftool2.yml, plugins/modules/system/gconftool2.py
=> [stable-5] gconftool2: fix index error

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/filesize/aliases, tests/integration/targets/filesystem/aliases, tests/integration/targets/filesystem/tasks/create_device.yml, tests/integration/targets/iptables_state/aliases, tests/integration/targets/iptables_state/tasks/tests/01-tables.yml, tests/integration/targets/lvg/aliases, tests/integration/targets/lvg/tasks/setup.yml, tests/integration/targets/lvg/tasks/teardown.yml, tests/integration/targets/lvg/tasks/test_grow_reduce.yml, tests/integration/targets/lvg/tasks/test_indempotency.yml, tests/integration/targets/lvg/tasks/test_pvresize.yml, tests/integration/targets/snap/aliases, tests/integration/targets/snap_alias/aliases, tests/integration/targets/ufw/aliases, tests/integration/targets/xattr/aliases, tests/integration/targets/xfs_quota/aliases, tests/utils/shippable/alpine.sh, tests/utils/shippable/fedora.sh, tests/utils/shippable/ubuntu.sh
Everything that tests filesystem things, or things that cannot be tested in containers.
CI
=> CI: add extra VMs for certain tests

changelogs/fragments/5721-manageiq-policies-deprecate-list-state.yaml, plugins/modules/manageiq_policies.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Deprecate state "list" in favour of using maangeiq_policies_info.
plugins/modules/manageiq_policies.py
=> manageiq_policies: deprecate list state

.github/BOTMETA.yml, changelogs/fragments/5720-ssh_config-plugin-sanity.yml, plugins/module_utils/ssh.py, plugins/modules/ssh_config.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Refactored the module to remove sanity check offending code from module,  moving that over to module utils.
plugins/modules/ssh_config.py
=> ssh_config: fixed sanity

plugins/modules/manageiq_policies.py
Remove the example for the deprecated case.
plugins/modules/manageiq_policies.py
=> manageiq_policies: remove doc example for deprecated case

plugins/callback/cgroup_memory_recap.py, plugins/callback/context_demo.py, plugins/callback/counter_enabled.py, plugins/callback/dense.py, plugins/callback/jabber.py, plugins/callback/log_plays.py, plugins/callback/logdna.py, plugins/callback/logentries.py, plugins/callback/logstash.py, plugins/callback/null.py, plugins/callback/say.py, plugins/callback/selective.py, plugins/callback/slack.py, plugins/callback/splunk.py, plugins/callback/sumologic.py, plugins/callback/syslog_json.py, plugins/callback/yaml.py
Improve docs formatting.
various callbacks
=> Improve callback docs

changelogs/fragments/5794-alternatives-fedora37.yml, plugins/modules/alternatives.py
Will get tested in CI in #5782.
alternatives
=> alternatives: make work with Fedora 37

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/cloud_init_data_facts/tasks/main.yml, tests/integration/targets/django_manage/aliases, tests/integration/targets/homectl/aliases, tests/integration/targets/iso_extract/aliases, tests/integration/targets/odbc/aliases, tests/integration/targets/pkgng/tasks/freebsd.yml, tests/integration/targets/setup_snap/tasks/D-RedHat-9.1.yml, tests/integration/targets/ufw/aliases
See https://github.com/ansible-collections/news-for-maintainers/issues/31.
CI
=> Update CI matrix

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/cloud_init_data_facts/tasks/main.yml, tests/integration/targets/django_manage/aliases, tests/integration/targets/homectl/aliases, tests/integration/targets/odbc/aliases, tests/integration/targets/pkgng/tasks/freebsd.yml, tests/integration/targets/setup_snap/tasks/D-RedHat-9.1.yml, tests/integration/targets/ufw/aliases
Backport of #5782 to stable-5. (See https://github.com/ansible-collections/news-for-maintainers/issues/31.)
CI
=> [stable-5] Update CI matrix

plugins/modules/scaleway_compute_private_network.py, plugins/modules/scaleway_database_backup.py, plugins/modules/scaleway_image_info.py, plugins/modules/scaleway_ip.py, plugins/modules/scaleway_lb.py, plugins/modules/scaleway_organization_info.py, plugins/modules/scaleway_private_network.py, plugins/modules/scaleway_security_group.py, plugins/modules/scaleway_security_group_rule.py, plugins/modules/scaleway_sshkey.py, plugins/modules/scaleway_user_data.py, plugins/modules/scaleway_volume.py
Fix minor documentation mistakes in scaleway_* modules.
plugins/modules/scaleway_compute_private_network.py
plugins/modules/scaleway_database_backup.py
plugins/modules/scaleway_ip.py
plugins/modules/scaleway_private_network.py
plugins/modules/scaleway_security_group.py
plugins/modules/scaleway_security_group_rule.py
plugins/modules/scaleway_sshkey.py
plugins/modules/scaleway_volume.py
=> multiple scaleway modules: fixed markups in doc

plugins/doc_fragments/ldap.py
A very simple patch to start the sentence with a capital case letter so that
it is consistent with all the other documentation descriptions in the file.
ldap.py
```paste below
```
=> ldap.py: capitalize one letter

changelogs/fragments/5808-xml-children-parameter-does-not-exist.yml, changelogs/fragments/xxxx-xml-children-parameter-does-not-exist.yml, plugins/modules/xml.py, tests/integration/targets/xml/results/test-set-children-elements-empty-list.xml, tests/integration/targets/xml/results/test-set-children-elements-empty-list.xml.license, tests/integration/targets/xml/tasks/test-set-children-elements.yml
Fixes https://github.com/ansible-collections/community.general/issues/4166
xml
=> xml children module parameter does not exist

plugins/doc_fragments/attributes.py
Allow to document the platforms a module supports.
attributes docs fragment
=> Add PLATFORM docs fragment

.github/BOTMETA.yml, meta/runtime.yml, plugins/module_utils/ocapi_utils.py, plugins/modules/ocapi_command.py, plugins/modules/ocapi_info.py, tests/unit/plugins/module_utils/test_ocapi_utils.py, tests/unit/plugins/modules/test_ocapi_command.py, tests/unit/plugins/modules/test_ocapi_info.py
Open Composable API (OCAPI) is a REST-based API designed for data center composability. For more information, see https://www.opencompute.org/documents/open-composable-api-for-ocp-2019-06-24-pdf
This PR introduces ocapi_command and ocapi_info modules.  These are based on the existing redfish_command and redfish_info modules and follow similar patterns.  This initial implementation includes support for the folowing operations:
- Indicator LED toggling
- Power state toggling
- Enclosure reset (reboot)
- Firmware upload
- Firmware update
- Firmware activate
- Job deletion
- Job status
These modules have been tested against Western Digital OpenFlex(tm) Data24 storage enclosures. API reference is at https://documents.westerndigital.com/content/dam/doc-library/en_us/assets/public/western-digital …
=> Remote management modules for OCAPI-based devices.

plugins/doc_fragments/attributes.py
Fixes the problem mentioned in https://github.com/ansible-collections/community.general/pull/5830#issuecomment-1407766810...
attributes docs fragment
=> Fix PLATFORM attributes docs fragment

changelogs/fragments/5933-linting.yml, plugins/modules/cloud/misc/terraform.py, plugins/modules/net_tools/pritunl/pritunl_org.py, plugins/modules/net_tools/pritunl/pritunl_org_info.py, plugins/modules/net_tools/pritunl/pritunl_user.py, plugins/modules/net_tools/pritunl/pritunl_user_info.py, plugins/modules/system/timezone.py, plugins/modules/system/xfconf.py
Backport of #5933 to stable-5.
various
=> [stable-5] Fix pylint errors

changelogs/fragments/5933-linting.yml, plugins/modules/cloud/misc/terraform.py, plugins/modules/net_tools/pritunl/pritunl_org.py, plugins/modules/net_tools/pritunl/pritunl_org_info.py, plugins/modules/net_tools/pritunl/pritunl_user.py, plugins/modules/net_tools/pritunl/pritunl_user_info.py, plugins/modules/system/timezone.py, plugins/modules/system/xfconf.py
Backport of #5933 to stable-5.
various
=> [stable-4] Fix pylint errors

plugins/module_utils/mh/module_helper.py, plugins/module_utils/module_helper.py, plugins/modules/pubnub_blocks.py
=> Ignore more unnecessary import warnings

plugins/modules/gitlab_project_members.py
=> Update gitlab_project_members.py - typo fix

plugins/modules/git_config.py, plugins/modules/github_deploy_key.py, plugins/modules/github_issue.py, plugins/modules/github_key.py, plugins/modules/github_release.py, plugins/modules/github_repo.py, plugins/modules/github_webhook.py, plugins/modules/gitlab_branch.py, plugins/modules/gitlab_deploy_key.py, plugins/modules/gitlab_group.py, plugins/modules/gitlab_group_members.py, plugins/modules/gitlab_group_variable.py, plugins/modules/gitlab_hook.py, plugins/modules/gitlab_project.py, plugins/modules/gitlab_project_members.py, plugins/modules/gitlab_project_variable.py, plugins/modules/gitlab_protected_branch.py, plugins/modules/gitlab_runner.py, plugins/modules/gitlab_user.py
=> Add attributes to git* modules

plugins/modules/hpilo_boot.py, plugins/modules/idrac_redfish_command.py, plugins/modules/idrac_redfish_config.py, plugins/modules/ilo_redfish_config.py, plugins/modules/ipmi_boot.py, plugins/modules/ipmi_power.py, plugins/modules/ocapi_command.py, plugins/modules/redfish_command.py, plugins/modules/redfish_config.py, plugins/modules/wdc_redfish_command.py, plugins/modules/xcc_redfish_command.py
=> Add attributes to remove management modules

plugins/modules/mas.py, plugins/modules/maven_artifact.py, plugins/modules/monit.py, plugins/modules/mqtt.py, plugins/modules/nagios.py, plugins/modules/newrelic_deployment.py, plugins/modules/nexmo.py, plugins/modules/nictagadm.py, plugins/modules/nomad_job.py, plugins/modules/nosh.py, plugins/modules/nsupdate.py, plugins/modules/oci_vcn.py, plugins/modules/office_365_connector_card.py, plugins/modules/pids.py, plugins/modules/pingdom.py, plugins/modules/redhat_subscription.py, plugins/modules/rhevm.py, plugins/modules/rhn_channel.py, plugins/modules/rhn_register.py, plugins/modules/rhsm_release.py, plugins/modules/rhsm_repository.py, plugins/modules/rollbar_deployment.py, plugins/modules/runit.py
=> Add attributes to more modules (3/4)

plugins/modules/solaris_zone.py, plugins/modules/sorcery.py, plugins/modules/spotinst_aws_elastigroup.py, plugins/modules/stackdriver.py, plugins/modules/stacki_host.py, plugins/modules/statsd.py, plugins/modules/statusio_maintenance.py, plugins/modules/supervisorctl.py, plugins/modules/svc.py, plugins/modules/swdepot.py, plugins/modules/swupd.py, plugins/modules/terraform.py, plugins/modules/uptimerobot.py, plugins/modules/urpmi.py, plugins/modules/vmadm.py
=> Add attributes to more modules (4/4)

plugins/modules/ali_instance_info.py, plugins/modules/idrac_redfish_info.py, plugins/modules/memset_memstore_info.py, plugins/modules/memset_server_info.py, plugins/modules/oneview_datacenter_info.py, plugins/modules/oneview_enclosure_info.py, plugins/modules/oneview_ethernet_network_info.py, plugins/modules/oneview_fc_network_info.py, plugins/modules/oneview_fcoe_network_info.py, plugins/modules/oneview_logical_interconnect_group_info.py, plugins/modules/oneview_network_set_info.py, plugins/modules/oneview_san_manager_info.py, plugins/modules/rax_facts.py, plugins/modules/redfish_info.py, plugins/modules/smartos_image_info.py, plugins/modules/snmp_facts.py, plugins/modules/utm_aaa_group_info.py, plugins/modules/utm_ca_host_key_cert_info.py, plugins/modules/utm_network_interface_address_info.py, plugins/modules/utm_proxy_frontend_info.py, plugins/modules/utm_proxy_location_info.py, plugins/modules/xenserver_facts.py, plugins/modules/xfconf_info.py
Document the version when check mode was added for these modules (was done in #3084).
some _info and _facts modules
=> Check mode has only been added for some _info and _facts modules in a bugfix

plugins/modules/ali_instance_info.py, plugins/modules/idrac_redfish_info.py, plugins/modules/memset_memstore_info.py, plugins/modules/memset_server_info.py, plugins/modules/oneview_datacenter_info.py, plugins/modules/oneview_enclosure_info.py, plugins/modules/oneview_ethernet_network_info.py, plugins/modules/oneview_fc_network_info.py, plugins/modules/oneview_fcoe_network_info.py, plugins/modules/oneview_logical_interconnect_group_info.py, plugins/modules/oneview_network_set_info.py, plugins/modules/oneview_san_manager_info.py, plugins/modules/rax_facts.py, plugins/modules/redfish_info.py, plugins/modules/smartos_image_info.py, plugins/modules/snmp_facts.py, plugins/modules/utm_aaa_group_info.py, plugins/modules/utm_ca_host_key_cert_info.py, plugins/modules/utm_network_interface_address_info.py, plugins/modules/utm_proxy_frontend_info.py, plugins/modules/utm_proxy_location_info.py, plugins/modules/xenserver_facts.py, plugins/modules/xfconf_info.py
Backport of #5969 to stable-6.
some _info and _facts modules
=> [stable-6] Check mode has only been added for some _info and _facts modules in a bugfix

tests/unit/plugins/lookup/onepassword/test_onepassword_cli_v2.py
Adjust tests for #5942.
onepassword lookup plugin unit tests
=> onepassword lookup: fix unit tests

plugins/modules/profitbricks.py, plugins/modules/profitbricks_datacenter.py, plugins/modules/profitbricks_nic.py, plugins/modules/profitbricks_volume.py, plugins/modules/profitbricks_volume_attachments.py, plugins/modules/scaleway_compute.py, plugins/modules/scaleway_compute_private_network.py, plugins/modules/scaleway_container.py, plugins/modules/scaleway_container_info.py, plugins/modules/scaleway_container_namespace.py, plugins/modules/scaleway_container_registry.py, plugins/modules/scaleway_database_backup.py, plugins/modules/scaleway_function.py, plugins/modules/scaleway_function_namespace.py, plugins/modules/scaleway_ip.py, plugins/modules/scaleway_lb.py, plugins/modules/scaleway_private_network.py, plugins/modules/scaleway_security_group.py, plugins/modules/scaleway_security_group_rule.py, plugins/modules/scaleway_sshkey.py, plugins/modules/scaleway_user_data.py, plugins/modules/scaleway_volume.py
=> Add attributes to scaleway and profitbricks modules

plugins/modules/clc_aa_policy.py, plugins/modules/clc_alert_policy.py, plugins/modules/clc_blueprint_package.py, plugins/modules/clc_firewall_policy.py, plugins/modules/clc_group.py, plugins/modules/clc_loadbalancer.py, plugins/modules/clc_modify_server.py, plugins/modules/clc_publicip.py, plugins/modules/clc_server.py, plugins/modules/clc_server_snapshot.py, plugins/modules/hwc_ecs_instance.py, plugins/modules/hwc_evs_disk.py, plugins/modules/hwc_network_vpc.py, plugins/modules/hwc_smn_topic.py, plugins/modules/hwc_vpc_eip.py, plugins/modules/hwc_vpc_peering_connect.py, plugins/modules/hwc_vpc_port.py, plugins/modules/hwc_vpc_private_ip.py, plugins/modules/hwc_vpc_route.py, plugins/modules/hwc_vpc_security_group.py, plugins/modules/hwc_vpc_security_group_rule.py, plugins/modules/hwc_vpc_subnet.py, plugins/modules/lxd_container.py, plugins/modules/lxd_profile.py, plugins/modules/lxd_project.py
=> Add attributes to clc, hwc, and lxd modules

plugins/modules/etcd3.py, plugins/modules/influxdb_database.py, plugins/modules/influxdb_query.py, plugins/modules/influxdb_retention_policy.py, plugins/modules/influxdb_user.py, plugins/modules/influxdb_write.py, plugins/modules/ldap_attrs.py, plugins/modules/ldap_entry.py, plugins/modules/ldap_passwd.py, plugins/modules/ldap_search.py, plugins/modules/mssql_db.py, plugins/modules/mssql_script.py, plugins/modules/odbc.py, plugins/modules/redis.py, plugins/modules/redis_data.py, plugins/modules/redis_data_incr.py, plugins/modules/riak.py, plugins/modules/vertica_configuration.py, plugins/modules/vertica_role.py, plugins/modules/vertica_schema.py, plugins/modules/vertica_user.py
=> Add attributes to some database modules

plugins/modules/manageiq_alert_profiles.py, plugins/modules/manageiq_alerts.py, plugins/modules/manageiq_group.py, plugins/modules/manageiq_policies.py, plugins/modules/manageiq_provider.py, plugins/modules/manageiq_tags.py, plugins/modules/manageiq_tenant.py, plugins/modules/manageiq_user.py, plugins/modules/udm_dns_record.py, plugins/modules/udm_dns_zone.py, plugins/modules/udm_group.py, plugins/modules/udm_share.py, plugins/modules/udm_user.py, plugins/modules/utm_aaa_group.py, plugins/modules/utm_ca_host_key_cert.py, plugins/modules/utm_dns_host.py, plugins/modules/utm_network_interface_address.py, plugins/modules/utm_proxy_auth_profile.py, plugins/modules/utm_proxy_exception.py, plugins/modules/utm_proxy_frontend.py, plugins/modules/utm_proxy_location.py, plugins/modules/webfaction_app.py, plugins/modules/webfaction_db.py, plugins/modules/webfaction_domain.py, plugins/modules/webfaction_mailbox.py, plugins/modules/webfaction_site.py
=> Add attributes to manageiq, udm, utm, and webfaction modules

plugins/modules/bitbucket_access_key.py, plugins/modules/bitbucket_pipeline_key_pair.py, plugins/modules/bitbucket_pipeline_known_host.py, plugins/modules/bitbucket_pipeline_variable.py, plugins/modules/bzr.py, plugins/modules/hg.py
=> Add attributes to source control modules

plugins/modules/consul.py, plugins/modules/consul_acl.py, plugins/modules/consul_kv.py, plugins/modules/consul_session.py, plugins/modules/datadog_downtime.py, plugins/modules/datadog_event.py, plugins/modules/datadog_monitor.py, plugins/modules/jenkins_build.py, plugins/modules/jenkins_job.py, plugins/modules/jenkins_plugin.py, plugins/modules/jenkins_script.py, plugins/modules/pagerduty.py, plugins/modules/pagerduty_alert.py, plugins/modules/pagerduty_change.py, plugins/modules/pagerduty_user.py, plugins/modules/rundeck_acl_policy.py, plugins/modules/rundeck_job_run.py, plugins/modules/rundeck_project.py, plugins/modules/sensu_check.py, plugins/modules/sensu_client.py, plugins/modules/sensu_handler.py, plugins/modules/sensu_silence.py, plugins/modules/sensu_subscription.py
=> Add attributes to consul, datadog, jenkins, pagerduty, rundeck, and sensu modules

plugins/modules/aix_devices.py, plugins/modules/aix_filesystem.py, plugins/modules/aix_inittab.py, plugins/modules/aix_lvg.py, plugins/modules/aix_lvol.py, plugins/modules/ibm_sa_domain.py, plugins/modules/ibm_sa_host.py, plugins/modules/ibm_sa_host_ports.py, plugins/modules/ibm_sa_pool.py, plugins/modules/ibm_sa_vol.py, plugins/modules/ibm_sa_vol_map.py
=> Add attributes to aix and ibm modules

plugins/modules/apache2_mod_proxy.py, plugins/modules/apache2_module.py, plugins/modules/cobbler_sync.py, plugins/modules/cobbler_system.py, plugins/modules/dimensiondata_network.py, plugins/modules/dimensiondata_vlan.py, plugins/modules/icinga2_feature.py, plugins/modules/icinga2_host.py, plugins/modules/lxca_cmms.py, plugins/modules/lxca_nodes.py, plugins/modules/pritunl_org.py, plugins/modules/pritunl_user.py, plugins/modules/spectrum_device.py, plugins/modules/spectrum_model_attrs.py
=> Add attributes to apache2, cobbler, dimensiondata, icinga2, lxca, pritunl, and spectrum modules

plugins/modules/campfire.py, plugins/modules/cisco_webex.py, plugins/modules/discord.py, plugins/modules/hipchat.py, plugins/modules/irc.py, plugins/modules/jabber.py, plugins/modules/librato_annotation.py, plugins/modules/logentries.py, plugins/modules/logentries_msg.py, plugins/modules/mail.py, plugins/modules/matrix.py, plugins/modules/mattermost.py, plugins/modules/rocketchat.py, plugins/modules/say.py, plugins/modules/sendgrid.py, plugins/modules/slack.py, plugins/modules/syslogger.py, plugins/modules/taiga_issue.py, plugins/modules/telegram.py, plugins/modules/twilio.py, plugins/modules/typetalk.py
=> Add attributes to some messaging modules

plugins/modules/beadm.py, plugins/modules/filesize.py, plugins/modules/filesystem.py, plugins/modules/lvg.py, plugins/modules/lvol.py, plugins/modules/parted.py, plugins/modules/xfs_quota.py, plugins/modules/zfs.py, plugins/modules/zfs_delegate_admin.py
=> Add attributes to some filesystem modules

plugins/modules/ipa_config.py, plugins/modules/ipa_dnsrecord.py, plugins/modules/ipa_dnszone.py, plugins/modules/ipa_group.py, plugins/modules/ipa_hbacrule.py, plugins/modules/ipa_host.py, plugins/modules/ipa_hostgroup.py, plugins/modules/ipa_otpconfig.py, plugins/modules/ipa_otptoken.py, plugins/modules/ipa_pwpolicy.py, plugins/modules/ipa_role.py, plugins/modules/ipa_service.py, plugins/modules/ipa_subca.py, plugins/modules/ipa_sudocmd.py, plugins/modules/ipa_sudocmdgroup.py, plugins/modules/ipa_sudorule.py, plugins/modules/ipa_user.py, plugins/modules/ipa_vault.py, plugins/modules/keycloak_authentication.py, plugins/modules/keycloak_client.py, plugins/modules/keycloak_client_rolemapping.py, plugins/modules/keycloak_clientscope.py, plugins/modules/keycloak_clientsecret_regenerate.py, plugins/modules/keycloak_clienttemplate.py, plugins/modules/keycloak_group.py, plugins/modules/keycloak_identity_provider.py, plugins/modules/keycloak_realm.py, plugins/modules/keycloak_role.py, plugins/modules/keycloak_user_federation.py, plugins/modules/keycloak_user_rolemapping.py
=> Add attributes to ipa and keycloak modules

plugins/modules/ocapi_info.py
These were missed earlier on.
ocapi_info
=> Add attributes to ocapi_info

plugins/modules/hana_query.py, plugins/modules/sap_task_list_execute.py, plugins/modules/sapcar_extract.py
These modules have been removed in `main`.
SAP modules
=> [stable-6] Add attributes to SAP modules

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml, README.md, tests/utils/shippable/shippable.sh
Backport of #6044 to stable-6.
CI
=> [stable-6] Run tests with EOL ansible-core versions in GHA

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml, README.md, tests/utils/shippable/shippable.sh
Backport of #6044 to stable-5.
CI
=> [stable-5] Run tests with EOL ansible-core versions in GHA

.github/BOTMETA.yml
Spoke with @jyundt on a call recently and he agreed it would be good to have him on the maintainer list to help with reviews.
N/A
=> Adding jyundt to Redfish maintainers

changelogs/fragments/5926-flatpak-remote-enabled.yml, plugins/modules/flatpak_remote.py, tests/integration/targets/flatpak_remote/tasks/check_mode.yml, tests/integration/targets/flatpak_remote/tasks/setup.yml, tests/integration/targets/flatpak_remote/tasks/test.yml
Fixes #4730 and ands an option to enable or disable flatpak remotes.
flatpak_remote
=> Add `enabled` parameter to `flatpak_remote`

.github/BOTMETA.yml
@glitchcrab please approve this PR if you really want to be removed as a maintainer. Thanks :)
Ref: https://github.com/ansible-collections/news-for-maintainers/discussions/37
BOTMETA
=> Remove glitchcrab as maintainer for memset modules and module utils

changelogs/fragments/6119-opkg-update.yaml, plugins/modules/opkg.py, tests/unit/plugins/modules/test_opkg.py
Testing wrong element of the tuple returned by `run()`.
Fixes #6004 
plugins/modules/opkg.py
=> opkg: fix bug when update_cache=true

plugins/modules/yum_versionlock.py
Fixing typo in documentation, we need to use name parameter instead of package.
+label: docsite_pr
```paste below
```
=> Documentation: yum_versionlock typo fix

plugins/modules/make.py
This change reorder the parameters so that we get the mandatory one at the top, then alphabetically order the other bellow.
It also adds the returned values.
make
=> [make] Improve module doc

.azure-pipelines/azure-pipelines.yml
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/38
CI
=> Add macOS 13.2 to CI

.github/BOTMETA.yml
Removes @verkaufer as a maintainer of the yarn module. 
I haven't kept up with the development for a while now, and I'm not able to provide any support for this module. 
n/a
n/a
n/a
=> Remove verkaufer as maintainer for yarn module

changelogs/fragments/5867-apt_rpm-add-clean-and-upgrade.yml, plugins/modules/apt_rpm.py
* clean performs apt-get clean.
* upgrade performs apt-get dist-upgrade.
* update_cache, clean and upgrade can be used with and without specified packages.
=> apt_rpm: add clean, dist_upgrade and update_kernel

changelogs/fragments/6269-mksysb-output.yml, plugins/modules/mksysb.py
Improves the module output
mksysb
=> mksysb: improve visibility on the output

tests/integration/targets/setup_snap/tasks/D-Ubuntu.yml, tests/integration/targets/snap/aliases, tests/integration/targets/snap/tasks/main.yml
Enable Ubuntu as a valid target for the integration tests of the `snap` module.
snap
=> snap: enable ubuntu in integration tests

tests/integration/targets/xfs_quota/aliases, tests/integration/targets/xfs_quota/handlers/main.yml, tests/integration/targets/xfs_quota/tasks/gquota.yml, tests/integration/targets/xfs_quota/tasks/main.yml, tests/integration/targets/xfs_quota/tasks/pquota.yml, tests/integration/targets/xfs_quota/tasks/uquota.yml
Adjusted tests to support Alpine Linux
xfs_quota
=> xfs_quota: fix integration tests for Alpine Linux

.github/BOTMETA.yml
Sorry! I haven't had time to work on this in a while. Cheers!
```paste below
```
=> Remove nibalizer from puppet module

changelogs/fragments/6334-dig-support-multiple-domains.yml, plugins/lookup/dig.py
The docs for this plugin indicated that multiple domains could be specified at once, but the code did not support multiple domains.
Fixes #861.
dig
=> dig: Support multiple domains in a single lookup

tests/integration/targets/parted/aliases, tests/integration/targets/parted/handlers/main.yml, tests/integration/targets/parted/tasks/main.yml
Add some initial integration tests for parted.
parted
=> parted: add integration test

.github/BOTMETA.yml
BOTMETA.yml: remove possibly not supported label
To check why the bot works wrong in https://github.com/ansible-collections/community.general/issues/6335
BOTMETA.yml
=> BOTMETA.yml: remove possibly not supported label

.github/BOTMETA.yml
Reverts changes made in https://github.com/ansible-collections/community.general/pull/6357
BOTMETA.yml
=> BOTMETA.yml: put the label redhat_subscription back

tests/integration/targets/snap/aliases, tests/integration/targets/snap_alias/aliases
Enable integration tests in Fedora for both `snap` and `snap_alias`
snap
snap_alias
=> snap & snap_alias: enable integration tests on Fedora

plugins/modules/redhat_subscription.py
Be a bit more explicit in how the module does the registration.
=> redhat_subscription: document the security of the registration

plugins/modules/parted.py
Docs review in module parted.
parted
=> parted: improve docs

tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt
Add comment on the iptables_state line in the ignore files for sanity tests.
iptables_state
=> iptables_state: add comment sanity ignore files

changelogs/fragments/6385-cpan-mh-feat.yml, plugins/modules/cpanm.py
Use MH feature instead of indirect reference.
cpanm
=> cpanm: apply MH feature

changelogs/fragments/6382-udm-dns-record-refactor.yml, plugins/modules/udm_dns_record.py
Minor refactors to the module.
udm_dns_record
=> udm_dns_record: minor refactor

plugins/modules/office_365_connector_card.py
Remove references to the deprecated dev.outlook.com and update them to the relevant learn.microsoft.com links.
Fixes #6262
office_365_connector_card
```paste below
N/A
```
=> office_365_connector_card: Remove references to dev.outlook.com

tests/integration/targets/kdeconfig/tasks/main.yml
More CI problems due to https://github.com/ansible/ansible/pull/79677.
kdeconfig
=> Fix kdeconfig tests

changelogs/fragments/6428-removals.yml, galaxy.yml, plugins/module_utils/cmd_runner.py, plugins/modules/gitlab_runner.py, plugins/modules/newrelic_deployment.py, plugins/modules/nmcli.py, plugins/modules/proxmox.py, plugins/modules/puppet.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/unit/plugins/module_utils/test_cmd_runner.py, tests/unit/plugins/modules/test_nmcli.py
Bump version to 7.0.0.
collection
=> Prepare main for 7.0.0

plugins/modules/awall.py
Minor improvements/fixes in the doc block.
awall
=> awall: improve docs

tests/integration/targets/keycloak_group/meta/main.yml, tests/integration/targets/keycloak_group/tasks/main.yml, tests/integration/targets/mssql_script/defaults/main.yml, tests/integration/targets/mssql_script/meta/main.yml, tests/integration/targets/mssql_script/tasks/main.yml, tests/integration/targets/setup_docker/README.md, tests/integration/targets/setup_docker/aliases, tests/integration/targets/setup_docker/defaults/main.yml, tests/integration/targets/setup_docker/handlers/main.yml, tests/integration/targets/setup_docker/meta/main.yml, tests/integration/targets/setup_docker/tasks/D-Fedora.yml, tests/integration/targets/setup_docker/tasks/default.yml, tests/integration/targets/setup_docker/tasks/main.yml, tests/integration/targets/setup_docker/tasks/nothing.yml, tests/integration/targets/setup_docker/vars/D-Fedora.yml, tests/integration/targets/setup_docker/vars/D-Ubuntu.yml, tests/requirements.yml, tests/utils/shippable/shippable.sh
Add `setup_docker` role for integration tests.
mssql_script
keycloak_group
=> Setup docker

.azure-pipelines/azure-pipelines.yml
@mattclay reported the mismatching entries in #ansible-community.
AZP config
=> CI: Fix matrix entries

changelogs/fragments/6464-mh-imports.yml, plugins/module_utils/mh/module_helper.py, plugins/module_utils/module_helper.py
The file `module_utils/module_helper.py` needed some updating in its imports.
=> ModuleHelper: updated/fixed imports in module_utils/module_helper.py

changelogs/fragments/6270-gconftool2-changed.yml, plugins/modules/gconftool2.py, tests/unit/plugins/modules/test_gconftool2.py
Fix the `changed` output of the module.
Fixes #6028 
plugins/modules/gconftool2.py
=> gconftool2: fix change output

changelogs/fragments/6468-snap-cmdrunner.yml, plugins/module_utils/snap.py, plugins/modules/snap.py
Refactor `snap` module to use `CmdRunner`.
snap
=> snap: now using CmdRunner

changelogs/fragments/6497-terraform-fix.yml, plugins/modules/terraform.py
Ref: https://github.com/ansible-collections/community.general/pull/6296#issuecomment-1536047197
CC @kemopq
terraform
=> terraform: fix warn() call

plugins/modules/proxmox_kvm.py
=> proxmox_kvm: remove non-working example

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/iso_extract/aliases, tests/integration/targets/pkgng/tasks/freebsd.yml
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/42
CI
=> CI: Add FreeBSD 13.2

tests/integration/targets/apache2_module/tasks/main.yml, tests/integration/targets/influxdb_user/tasks/main.yml, tests/integration/targets/locale_gen/tasks/main.yml, tests/integration/targets/mqtt/tasks/main.yml, tests/integration/targets/pacman/tasks/main.yml, tests/integration/targets/pkgng/tasks/freebsd.yml, tests/integration/targets/sefcontext/tasks/main.yml, tests/integration/targets/sensu_handler/tasks/main.yml, tests/integration/targets/setup_influxdb/tasks/main.yml, tests/integration/targets/setup_mosquitto/tasks/main.yml, tests/integration/targets/setup_pkg_mgr/tasks/main.yml, tests/integration/targets/ssh_config/tasks/main.yml, tests/integration/targets/sysrc/tasks/main.yml, tests/integration/targets/xattr/tasks/main.yml, tests/integration/targets/yarn/tasks/main.yml, tests/integration/targets/zypper/tasks/main.yml, tests/integration/targets/zypper_repository/tasks/main.yml, tests/integration/targets/zypper_repository/tasks/test.yml
Backport of #6535 to stable-5.
=> [stable-5] CI: include has finally been removed in ansible-core devel

tests/integration/requirements.yml, tests/unit/requirements.yml
Backport of #6549 to stable-5.
test requirements
=> [stable-5] Switch to Ansible Galaxy compatible requirements files for tests

changelogs/fragments/6523-datadog-monitor-notification-preset-name-and-renotify.yaml, plugins/modules/datadog_monitor.py
Added notification preset name to fix this issue: https://github.com/ansible-collections/community.general/issues/6521
and added renotify options for this issue: https://github.com/ansible-collections/community.general/issues/5823
=> datadog_monitor: Added notification preset name and renotify options

.github/BOTMETA.yml, plugins/module_utils/vardict.py, tests/unit/plugins/module_utils/test_vardict.py
Refactor `VarDict` out of the `ModuleHelper` umbrella, making it simpler and easier to integrate without any dependencies to MH itself.
plugins/module_utils/vardict.py
=> VarDict module utils

changelogs/fragments/6525-sorcery-import.yaml, plugins/modules/sorcery.py
Moved import stmt from bottom to the top-ish of the file
sorcery
=> sorcery: moved import to top

changelogs/fragments/6510-proxmox-create-support_timezone.yaml, plugins/modules/proxmox.py
Support param `timezone` at container creation
proxmox
=> proxmox: support param `timezone` when creating container

.github/BOTMETA.yml, plugins/module_utils/proxmox.py, plugins/modules/proxmox_pool.py, plugins/modules/proxmox_pool_member.py, tests/integration/targets/proxmox_pool/aliases, tests/integration/targets/proxmox_pool/defaults/main.yml, tests/integration/targets/proxmox_pool/tasks/main.yml
New modules to:
- Create or delete resource pools
- Remove or add members of resource pools
proxmox_pool
proxmox_pool_member
Integration tests output
```
ansible-test integration --allow-unsupported --local proxmox_pool
Running proxmox_pool integration test role
PLAY [testhost] ****************************************************************
TASK [Gathering Facts] *********************************************************
ok: [testhost]
TASK [proxmox_pool : Make sure poolid parameter is not missing] ****************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "missing required arguments: poolid"}
...ignoring
TASK [proxmox_pool : assert] ***************************************************
ok: [testhost] => {
"msg": "All …
```
=> New Proxmox VE modules to handle pools and their membership

.azure-pipelines/azure-pipelines.yml
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/46
CI
=> CI: ansible-core devel drops support for Python 3.5

changelogs/fragments/6576-proxmox-snap-allow-to-remove-old-snapshots.yml, changelogs/fragments/6576-proxmox-snap-allow-trimming.yml, plugins/modules/proxmox_snap.py
Add a trim option to delete older snapshots
Fixes #6576
proxmox_snap
```paste below
output stays the same
```
=> proxmox_snap: allow set retention for snapshots

changelogs/fragments/6223-get-secret-ids-by-folderid.yml, plugins/lookup/tss.py
Added support to fetch secret id's which are in folder by folder id
Continues #6637 and #6651.
=> Fetch secret id's which are in folder by folder id

changelogs/fragments/6640-proxmox-composite-variables-support.yml, plugins/inventory/proxmox.py
Fixes 6640: https://github.com/ansible-collections/community.general/issues/6640
proxmox
```paste below
```
=> Proxmox inventory plugin: support composite variables

plugins/modules/haproxy.py, plugins/modules/heroku_collaborator.py, plugins/modules/homebrew.py, plugins/modules/homebrew_tap.py, plugins/modules/homectl.py, plugins/modules/htpasswd.py, plugins/modules/hwc_vpc_private_ip.py, plugins/modules/hwc_vpc_route.py, plugins/modules/hwc_vpc_security_group.py, plugins/modules/hwc_vpc_security_group_rule.py, plugins/modules/icinga2_host.py, plugins/modules/idrac_redfish_config.py, plugins/modules/influxdb_retention_policy.py, plugins/modules/ini_file.py, plugins/modules/interfaces_file.py, plugins/modules/ipa_dnsrecord.py, plugins/modules/ipa_group.py, plugins/modules/ipa_hostgroup.py, plugins/modules/ipa_user.py, plugins/modules/ipmi_power.py, plugins/modules/iptables_state.py, plugins/modules/ipwcli_dns.py, plugins/modules/iso_customize.py, plugins/modules/iso_extract.py, plugins/modules/java_keystore.py, plugins/modules/jboss.py, plugins/modules/jenkins_job.py, plugins/modules/jenkins_job_info.py, plugins/modules/jenkins_plugin.py, plugins/modules/jira.py
For information on semantic markup, see https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#semantic-markup-within-module-documentation.
Ref: #6627
(Note: I'm only considering modules containing `I(` for now.)
modules starting with h-j
=> Use semantic markup (modules h-j)

plugins/modules/kdeconfig.py, plugins/modules/keycloak_authentication.py, plugins/modules/keycloak_authz_authorization_scope.py, plugins/modules/keycloak_client.py, plugins/modules/keycloak_client_rolemapping.py, plugins/modules/keycloak_clientscope.py, plugins/modules/keycloak_clientscope_type.py, plugins/modules/keycloak_clientsecret_info.py, plugins/modules/keycloak_clienttemplate.py, plugins/modules/keycloak_group.py, plugins/modules/keycloak_identity_provider.py, plugins/modules/keycloak_realm.py, plugins/modules/keycloak_role.py, plugins/modules/keycloak_user.py, plugins/modules/keycloak_user_federation.py, plugins/modules/keycloak_user_rolemapping.py, plugins/modules/layman.py, plugins/modules/ldap_attrs.py, plugins/modules/ldap_entry.py, plugins/modules/ldap_passwd.py, plugins/modules/ldap_search.py, plugins/modules/listen_ports_facts.py, plugins/modules/lvg.py, plugins/modules/lxc_container.py, plugins/modules/lxd_container.py, plugins/modules/lxd_project.py
For information on semantic markup, see https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#semantic-markup-within-module-documentation.
Ref: #6627
(Note: I'm only considering modules containing `I(` for now.)
modules starting with k-l
=> Use semantic markup (modules k-l)

plugins/modules/macports.py, plugins/modules/make.py, plugins/modules/manageiq_policies.py, plugins/modules/manageiq_policies_info.py, plugins/modules/manageiq_tags.py, plugins/modules/manageiq_tags_info.py, plugins/modules/mattermost.py, plugins/modules/maven_artifact.py, plugins/modules/memset_dns_reload.py, plugins/modules/memset_memstore_info.py, plugins/modules/memset_server_info.py, plugins/modules/memset_zone.py, plugins/modules/memset_zone_domain.py, plugins/modules/memset_zone_record.py, plugins/modules/monit.py, plugins/modules/mqtt.py, plugins/modules/mssql_script.py, plugins/modules/nagios.py, plugins/modules/netcup_dns.py, plugins/modules/newrelic_deployment.py, plugins/modules/nictagadm.py, plugins/modules/nmcli.py, plugins/modules/nomad_job.py, plugins/modules/nosh.py
For information on semantic markup, see https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#semantic-markup-within-module-documentation.
Ref: #6627
(Note: I'm only considering modules containing `I(` for now.)
modules starting with m-n
=> Use semantic markup (modules m-n)

plugins/modules/cobbler_system.py, plugins/modules/mattermost.py, plugins/modules/maven_artifact.py, plugins/modules/read_csv.py, plugins/modules/telegram.py, plugins/modules/terraform.py, plugins/modules/udm_dns_record.py, plugins/modules/udm_dns_zone.py, plugins/modules/udm_share.py, plugins/modules/udm_user.py, plugins/modules/urpmi.py, plugins/modules/vertica_user.py, plugins/modules/vmadm.py, plugins/modules/wdc_redfish_command.py, plugins/modules/wdc_redfish_info.py, plugins/modules/webfaction_app.py, plugins/modules/webfaction_db.py, plugins/modules/webfaction_domain.py, plugins/modules/webfaction_mailbox.py, plugins/modules/webfaction_site.py, plugins/modules/xattr.py, plugins/modules/xenserver_guest.py, plugins/modules/xfconf.py, plugins/modules/xfconf_info.py, plugins/modules/xml.py, plugins/modules/zfs_delegate_admin.py, plugins/modules/znode.py, plugins/modules/zypper.py, plugins/modules/zypper_repository.py
For information on semantic markup, see https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#semantic-markup-within-module-documentation.
Ref: #6627
(Note: I'm only considering modules containing `I(` for now.)
modules starting with t-z
=> Use semantic markup (modules t-z)

.github/BOTMETA.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_authentication_required_actions.py, tests/unit/plugins/modules/test_keycloak_authentication_required_actions.py
This module introduces management for the authentication required actions. With this new module you can:
- Register, update and delete required actions.
keycloak_authentication_required_actions
Since my last PR won't be accepted due to breaking changes, I at least separated the required actions from it, and made it as a standalone module.
=> Keycloak: Authentication required actions management

plugins/lookup/etcd.py, plugins/lookup/etcd3.py, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt
We can now reference plugins directly.
various
=> Improve seealso

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/listen_ports_facts/tasks/main.yml, tests/integration/targets/setup_postgresql_db/vars/Debian-12-py3.yml
=> Add Debian Bookworm to CI

plugins/lookup/random_string.py
Fixes #6571 
random_string
I'm not sure if my formatting is correct.
I'm not sure if the changelog fragment type is correct.
=> random_string docs to say it's cryptographically secure

changelogs/fragments/6826-snap-out-strip.yml, plugins/modules/snap.py, tests/unit/plugins/modules/test_snap.py
Strip the commands output when running snap. Add unit test to assert issue 6803 is addressed.
Fixes #6803 
snap
=> snap: fix bug when processing output

plugins/modules/proxmox_kvm.py
This reverts commit 61a0dc43700d7c6d8dcf0e24b82bacfe1902a288.
See https://github.com/ansible-collections/community.general/issues/6484#issuecomment-1616410152.
proxmox_kvm
=> Revert "proxmox_kvm: remove non-working example (#6498)"

plugins/modules/htpasswd.py
Minor adjustments in the docs.
htpasswd
=> htpasswd: minor updates in the docs

tests/integration/targets/htpasswd/aliases, tests/integration/targets/htpasswd/handlers/main.yml, tests/integration/targets/htpasswd/meta/main.yml, tests/integration/targets/htpasswd/tasks/main.yml, tests/integration/targets/htpasswd/vars/main.yml
Add integration tests for htpasswd.
htpasswd
=> htpasswd: add integration tests

changelogs/fragments/6848-npm-required-if.yml, plugins/modules/npm.py, tests/integration/targets/npm/tasks/test.yml
Use `required_if` in the module definition instead of coding the test.
npm
=> npm: replace test with required_if

plugins/modules/github_key.py
Add example for github_key in a single task
github_key
=> Add example for github_key in a single task

changelogs/fragments/6873-proxmox-imports.yml, plugins/module_utils/proxmox.py
Remove unused imports from proxmox module.
proxmox
=> proxmox: remove unused imports

plugins/module_utils/proxmox.py, plugins/modules/proxmox.py, plugins/modules/proxmox_kvm.py, plugins/modules/proxmox_vm_info.py, tests/unit/plugins/modules/test_proxmox_vm_info.py
Module retrieves information about Proxmox VE virtual machines.
proxmox_vm_info
=> [proxmox_vm_info] New module to retrieve virtual machines information from Proxmox VE API

plugins/connection/chroot.py
Added a simple example of chroot connection plugin
Fixes: #6365
=> chroot: added an example

plugins/modules/bigpanda.py
quotes around value containing `:`
bigpanda
=> minor quoting fix in doc

changelogs/fragments/6901-htpasswd-refactor.yml, plugins/modules/htpasswd.py
A bit refactor on the module.
htpasswd
=> htpasswd: refactor

.github/BOTMETA.yml
Hello,
I am stepping down as a reviewer for the proxmox modules as I do not work with proxmox anymore and thus can't really test or review properly.
Regards.
=> Remove tleguern from team_virt

changelogs/fragments/6927-pylint-comments.yml, plugins/modules/copr.py, plugins/modules/gitlab_runner.py, plugins/modules/keyring.py
Removed inline comments with pylint exceptions.
plugins/modules/copr.py
plugins/modules/gitlab_runner.py
plugins/modules/keyring.py
=> remove pylint exceptions

changelogs/fragments/get-secret-by-path.yml, plugins/lookup/tss.py
Added support to fetch secret from secret server by path
=> tss lookup plugin - Fetch secret by path

changelogs/fragments/6930-deprecate-flowdock.yml, meta/runtime.yml, plugins/modules/flowdock.py
The module relies entirely on API endpoints that seems to be no longer responsive.
flowdock
=> flowdock module: deprecation

changelogs/fragments/6935-machinectl-become.yml, plugins/become/machinectl.py
Fixes #6932.
machinectl become plugin
=> machinectl become plugin: mark as require_tty

changelogs/fragments/6903-locale-gen-refactor.yml, plugins/modules/locale_gen.py
Big refactor on the module.
locale_gen
=> locale_gen: refactor

plugins/lookup/onepassword.py
Add missing commas to documentation examples.
`community.general.onepassword`
=> 📝 Add missing commas to documentation

.github/BOTMETA.yml
Removal of myself as a maintainer for gitlab related modules.
```paste below
```
=> Removal of myself as maintainer

plugins/modules/keycloak_authz_permission.py, plugins/modules/keycloak_authz_permission_info.py
Replace `I(...)` and `C(...)` when appropriate.
keycloak_authz_permission
keycloak_authz_permission_info
=> keycloak_authz_permission*: adjust to semantic markup

.azure-pipelines/azure-pipelines.yml
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/53
CI
=> CI: move FreeBSD 12.4 from ansible-core devel to stable-2.15

.github/BOTMETA.yml
Add `tarka` to bot ignore list.
jira.py
=> Add tarka to ignore list.

changelogs/fragments/6914-proxmox_kvm-enable-force-restart.yml, changelogs/fragments/6976-proxmox-vm-info-not-require-node.yml, changelogs/fragments/7020-redfish-utils-pagination.yml, plugins/module_utils/redfish_utils.py, plugins/modules/proxmox_kvm.py, plugins/modules/proxmox_vm_info.py, tests/unit/plugins/modules/test_proxmox_vm_info.py
Revert features temporarily so we can re-revert them after the 7.2.1 bugfix release (https://github.com/ansible-collections/community.general/issues/6974#issuecomment-1656198535).
Commits reverted:
- 1dad95370eb861cb460d1d52355909dbfd339cb0
- 7d68af57af0e43509f08c8243b4acc4c1d09b8f3
- fb3768aada66e459d24c7225532deb36ab8c3ed1
various
=> [stable-7] Revert new features to be able to do 7.2.1 release

tests/integration/targets/snap/tasks/main.yml, tests/integration/targets/snap/tasks/test_3dash.yml
Add test safeguarding the module from the case described in #7046 
snap
=> Snap add test

changelogs/fragments/6814-redfish-config-add-delete-all-volumes.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_config.py
SUMMARY
Adding functionality to delete volumes on Gen11 servers.
ISSUE TYPE
COMPONENT NAME
=> Adding DeleteVolumes functionality

changelogs/fragments/7051-ipa-config-new-choice-idp-to-ipauserauthtype.yml, plugins/modules/ipa_config.py
I have added idp choice into ipauserauthtype.
Fixes #7050
ipa_config
```paste below
```
=> ipa_config: add idp choice to ipauserauthtype

changelogs/fragments/7085-sanity.yml, plugins/module_utils/oracle/oci_utils.py, plugins/modules/proxmox_user_info.py, tests/unit/mock/loader.py, tests/unit/plugins/modules/test_keycloak_user.py
Fixes nightly CI failure.
plugins/module_utils/oracle/oci_utils.py
plugins/modules/proxmox_user_info.py
tests/unit/mock/loader.py
tests/unit/plugins/modules/test_keycloak_user.py
=> Avoid direct type comparisons

changelogs/fragments/7085-sanity.yml, plugins/module_utils/oracle/oci_utils.py, plugins/modules/proxmox_user_info.py, tests/unit/mock/loader.py
Backport of #7085 to stable-6.
plugins/module_utils/oracle/oci_utils.py
plugins/modules/proxmox_user_info.py
tests/unit/mock/loader.py
=> [stable-6] Avoid direct type comparisons

plugins/modules/sorcery.py
This is a minor follow-up fix for #7012 making sure that only specified repositories are updated when requested.
`sorcery`
N/A
=> sorcery: update only specified grimoires

changelogs/fragments/6989-npm-cmdrunner.yml, plugins/modules/npm.py, tests/unit/plugins/modules/test_npm.py
Changed the running of external command to use `CmdRunner`. 
npm
=> npm: changed to cmdrunner

plugins/connection/chroot.py
Better informations about sudo and env.
```paste below
```
=> Update chroot.py - better documentation

changelogs/fragments/7075-ejabberd-user-cmdrunner.yml, plugins/modules/ejabberd_user.py
Use `CmdRunner` to execute the `ejabberdctl` command.
ejabberd_user
=> ejabberd_user: use CmdRunner

changelogs/fragments/6819-redfish-utils-add-links-parameter-for-get_disk_inventory.yml, plugins/module_utils/redfish_utils.py
SUMMARY
Adding 'Links' to the parameter list for data retrieved from get_disk_inventory
ISSUE TYPE
COMPONENT NAME
=> Adding 'Links' to the parameter list for data retrieved from get_disk_inventory

plugins/modules/proxmox_kvm.py
Fixing a minor typo on proxmox_kvm documentation.
proxmox_kvm
No modification on code, only a typo on documentation.
=> minor typo on proxmox_kvm module documentation

plugins/modules/keycloak_clientscope_type.py
Fixed module name in examples.
Fixes #7157
keycloak_clientscope_type
=> keycloak_clientscope_type: fixed example

tests/unit/plugins/modules/cmd_runner_test_utils.py, tests/unit/plugins/modules/test_opkg.py, tests/unit/plugins/modules/test_xfconf.py, tests/unit/plugins/modules/test_xfconf_info.py
Improve the helper class, refraining from the need of passing the command name.
tests/unit/plugins/modules/cmd_runner_test_utils.py
=> cmd tests improvement

tests/unit/plugins/modules/test_snap.py
Use the new helper class for testing.
test_snap
=> snap: using yaml-specified unit tests

tests/unit/plugins/modules/cmd_runner_test_utils.py, tests/unit/plugins/modules/test_opkg.py, tests/unit/plugins/modules/test_snap.py, tests/unit/plugins/modules/test_xfconf.py, tests/unit/plugins/modules/test_xfconf_info.py
Further simplification of the test helper logic.
tests/unit/plugins/modules/cmd_runner_test_utils.py
=> further improvements

tests/unit/plugins/modules/test_puppet.py, tests/unit/plugins/modules/test_puppet.yaml
Use help tester to run YAML-specified testcases
tests/unit/plugins/modules/test_puppet.yaml
=> puppet: using yaml-specified unit tests

tests/unit/plugins/modules/cmd_runner_test_utils.py, tests/unit/plugins/modules/test_gconftool2.py, tests/unit/plugins/modules/test_gconftool2.yaml, tests/unit/plugins/modules/test_gconftool2_info.py, tests/unit/plugins/modules/test_gconftool2_info.yaml, tests/unit/plugins/modules/test_snap.py
Use help tester to run YAML-specified testcases
tests/unit/plugins/modules/cmd_runner_test_utils.py
tests/unit/plugins/modules/test_gconftool2.yaml
=> gconftool2: using yaml-specified unit tests

plugins/modules/apache2_module.py
=> plugins/modules/apache2_module: fix typo

plugins/modules/proxmox_kvm.py
More detailed description smbios option
community.general.proxmox_kvm
=> smbios option description

tests/unit/plugins/modules/helper.py, tests/unit/plugins/modules/test_cpanm.py, tests/unit/plugins/modules/test_gconftool2.py, tests/unit/plugins/modules/test_gconftool2_info.py, tests/unit/plugins/modules/test_opkg.py, tests/unit/plugins/modules/test_puppet.py, tests/unit/plugins/modules/test_snap.py, tests/unit/plugins/modules/test_xfconf.py, tests/unit/plugins/modules/test_xfconf_info.py
Refactored the test function into the Helper class
=> encapsulate test function in the helper class

tests/unit/plugins/modules/test_cpanm.yaml, tests/unit/plugins/modules/test_gconftool2.yaml, tests/unit/plugins/modules/test_gconftool2_info.yaml, tests/unit/plugins/modules/test_opkg.yaml, tests/unit/plugins/modules/test_puppet.yaml, tests/unit/plugins/modules/test_xfconf.yaml, tests/unit/plugins/modules/test_xfconf_info.yaml
Using YAML anchors and aliases.
tests/unit/plugins/modules/test_cpanm.yaml
tests/unit/plugins/modules/test_gconftool2.yaml
tests/unit/plugins/modules/test_gconftool2_info.yaml
tests/unit/plugins/modules/test_opkg.yaml
tests/unit/plugins/modules/test_puppet.yaml
tests/unit/plugins/modules/test_xfconf.yaml
tests/unit/plugins/modules/test_xfconf_info.yaml
=> DRY: using YAML anchors and aliases

tests/unit/plugins/modules/helper.py
Refactoring classes in anticipation for future improvements.
=> refactor test helper context class

.github/BOTMETA.yml
Being doing that in practice anyways.
=> add russoz as maintainer of modules/snap and module_utils/snap

plugins/modules/ipa_user.py
Fixes #7037
ipa_user
```paste below
```
=> ipa_user documentation: givenname and sn are required when user doesn't exist

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml
=> [stable-5] Move stable-2.13 to EOL CI

.github/BOTMETA.yml, plugins/module_utils/gio_mime.py, plugins/modules/gio_mime.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/unit/plugins/modules/helper.py, tests/unit/plugins/modules/test_gio_mime.py, tests/unit/plugins/modules/test_gio_mime.yaml
New module to control MIME type handlers in the context of Gnome desktop environment.
plugins/module_utils/gio_mime.py
plugins/modules/gio_mime.py
tests/unit/plugins/modules/test_gio_mime.py
tests/unit/plugins/modules/test_gio_mime.yaml
=> New Module: gio_mime

plugins/filter/from_csv.py
Typo fix
There's a typo on https://docs.ansible.com/ansible/latest/collections/community/general/from_csv_filter.html
```paste below
```
=> Update from_csv.py docs

changelogs/fragments/7323-nmap.yml, plugins/inventory/nmap.py
=> nmap: fix get_option calls

README.md
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/59
README
=> Fix Galaxy URLs

.azure-pipelines/azure-pipelines.yml
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/60
CI
=> CI: ansible-core devel drops support for Python 2.7 and 3.6

changelogs/fragments/7343-dig-tcp-option.yml, plugins/lookup/dig.py
Add TCP option for dig plugin.
dig plugin
=> Add TCP option for dig plugin.

.azure-pipelines/azure-pipelines.yml, tests/unit/plugins/callback/test_loganalytics.py, tests/unit/plugins/module_utils/hwc/test_hwc_utils.py, tests/unit/plugins/modules/test_dnsimple.py, tests/unit/plugins/modules/test_jenkins_build_info.py, tests/unit/plugins/modules/test_pagerduty.py, tests/unit/plugins/modules/test_pagerduty_alert.py, tests/unit/plugins/modules/test_pkgin.py, tests/unit/plugins/modules/test_slack.py
=> Fix Python 3.12 unit tests

changelogs/fragments/7352-add-executable-option-for-cargo.yml, plugins/modules/cargo.py, tests/integration/targets/cargo/tasks/main.yml, tests/integration/targets/cargo/tasks/setup.yml, tests/integration/targets/cargo/tasks/test_rustup_cargo.yml
Add `executable` option to cargo to make the module easier to use with cargo installed by rustup.
Fixes #4407.
cargo
=> Add `executable` option to cargo

changelogs/fragments/7379-url.yml, plugins/module_utils/memset.py
Ref: https://github.com/ansible/ansible/commit/92d2c66db2eecd0f5e26e6f49589dbcdb4612618
memset module utils
=> Make compatible with current ansible-core devel

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml, README.md, changelogs/fragments/ansible-core-2.11-2.12.yml, meta/runtime.yml, plugins/callback/selective.py, plugins/lookup/collection_version.py, plugins/module_utils/version.py
Implement https://github.com/ansible-community/community-topics/discussions/271.
various
=> Drop support for ansible-core 2.11 and 2.12

changelogs/fragments/7377-proxmox-kvm-deprecate-flag.yml, plugins/modules/proxmox_kvm.py
Feature flag was added long time ago, it is time to 
proxmox_kvm
=> proxmox_kvm: deprecate option proxmox_default_behavior

changelogs/fragments/7382-kernel-blacklist-bugfix.yml, plugins/modules/kernel_blacklist.py, tests/integration/targets/kernel_blacklist/aliases, tests/integration/targets/kernel_blacklist/handlers/main.yml, tests/integration/targets/kernel_blacklist/tasks/main.yml
Simplify the way the file is updated, preventing the errors with attributes.
Fixes #7362 .
kernel_blacklist
=> kernel_blacklist: bugfix

plugins/modules/gitlab_group_variable.py, plugins/modules/gitlab_instance_variable.py, plugins/modules/gitlab_project_variable.py
Fix a typo: `s/Wether/Whether/`
plugins/modules/gitlab_group_variable
plugins/modules/gitlab_instance_variable
plugins/modules/gitlab_project_variable
=> plugins/modules/gitlab: typo fix: s/Wether/Whether/

.azure-pipelines/azure-pipelines.yml
Manual backport of #7419 to stable-7.
CI
=> [stable-7] CI: remove macOS 12.0 from CI

plugins/modules/nmcli.py
I had some trouble initially getting this to work as I wasn't very clear on what was required, to that end I have added an example task and fixed what I suspect is a typo in the description.
- nmcli
N/A
=> nmcli: add additional documentation for routing_rules4 option

changelogs/fragments/7396-fix-apt_rpm-local-rpm-installation.yml, plugins/modules/apt_rpm.py
Fix local RPM installation, see [this comment](https://github.com/ansible-collections/community.general/issues/6488#issuecomment-1763121046) for issue details
Fixes #6488
apt_rpm
Now the following task succeeds:
```paste below
- name: Install RPM package from file
become: true
block:
- name: Deliver RPM file
ansible.builtin.copy:
src: 'files/whatever.rpm'
dest: '{{ ansible_env.HOME }}/whatever.rpm'
mode: '640'
- name: Install RPM file
community.general.apt_rpm:
pkg: '{{ ansible_env.HOME }}/whatever.rpm'
state: present
```
=> apt_rpm module: fix local RPM installation

docs/docsite/rst/filter_guide_abstract_informations_counting_elements_in_sequence.rst, docs/docsite/rst/filter_guide_abstract_informations_dictionaries.rst, docs/docsite/rst/filter_guide_abstract_informations_grouping.rst, docs/docsite/rst/filter_guide_abstract_informations_merging_lists_of_dictionaries.rst, docs/docsite/rst/filter_guide_conversions.rst, docs/docsite/rst/filter_guide_creating_identifiers.rst, docs/docsite/rst/filter_guide_paths.rst, docs/docsite/rst/filter_guide_selecting_json_data.rst, docs/docsite/rst/filter_guide_working_with_times.rst, docs/docsite/rst/filter_guide_working_with_unicode.rst, docs/docsite/rst/filter_guide_working_with_versions.rst, docs/docsite/rst/test_guide.rst
- Improve markup.
- Improve filter and test guides by linking to plugins and using FQCNs more consistently.
docsite extra docs
=> Improve docsite extra docs

changelogs/fragments/7506-pipx-pipargs.yml, plugins/module_utils/pipx.py, tests/integration/targets/pipx/tasks/main.yml
Format the `pip_args` parameter in the form `--pip_args=<value>`.
Fixes #7497 
plugins/module_utils/pipx.py
=> pipx: change parameter formatter for pip_args

changelogs/fragments/5588-support-1password-connect.yml, plugins/lookup/onepassword.py, plugins/lookup/onepassword_raw.py, tests/unit/plugins/lookup/test_onepassword.py
- Support 1Password Connect with the opv2 client
Support 1Password Connect with the opv2 client. Closes #5588.
onepassword
=> Support 1Password Connect (#5588)

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/java_cert/files/setupSSLServer.py, tests/integration/targets/mail/tasks/main.yml
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/63
CI
=> CI: devel supports Fedora 39, and no longer Fedora 38

tests/unit/plugins/modules/helper.py, tests/unit/plugins/modules/test_cpanm.py, tests/unit/plugins/modules/test_facter_facts.py, tests/unit/plugins/modules/test_gconftool2.py, tests/unit/plugins/modules/test_gconftool2_info.py, tests/unit/plugins/modules/test_gio_mime.py, tests/unit/plugins/modules/test_opkg.py, tests/unit/plugins/modules/test_puppet.py, tests/unit/plugins/modules/test_xfconf.py, tests/unit/plugins/modules/test_xfconf_info.py
The `Helper.from_module()` method now receives the test module name and injects the needed functions in the module by that name.
tests/unit/plugins/modules/test_facter_facts.py
tests/unit/plugins/modules/test_gio_mime.py
=> test helper: Helper.from_module() injects test function into test module

galaxy.yml
The description so far was `null`. Replace it with an adjusted text from the README.
Also remove no longer relevant comments, especially the `type: flatmap`. We no longer need flatmapping anymore anyway.
galaxy.yml
=> galaxy.yml: improve description, improve YAML, remove not really relevant comments

plugins/callback/logentries.py
Found some markup and boolean value issues in the logentries documentation.
Also changed `use_tls` in example to `true` instead of `false` (let's give secure examples!).
logentries callback
=> logentries: docs improvements

plugins/modules/interfaces_file.py
Adjust to our docs standards.
interfaces_file
=> Improve interfaces_file documentation

changelogs/fragments/7612-interface_file-method.yml, plugins/modules/interfaces_file.py, tests/integration/targets/interfaces_file/tasks/main.yml
=> interfaces_file: filter by address_familiy when updating method

plugins/doc_fragments/onepassword.py, plugins/lookup/onepassword.py, plugins/lookup/onepassword_doc.py, plugins/lookup/onepassword_raw.py, tests/unit/plugins/lookup/conftest.py, tests/unit/plugins/lookup/onepassword_conftest.py, tests/unit/plugins/lookup/test_onepassword.py
Add `onepassword_doc` lookup plugin.
Fixes #7246.
- `plugins/lookup/onepassword.py`
- `plugins/lookup/onepassword_doc.py`
=> Add onepassword_doc lookup plugin

plugins/inventory/icinga2.py, plugins/inventory/proxmox.py, plugins/modules/gitlab_group.py, plugins/modules/gitlab_hook.py, plugins/modules/gitlab_project.py, plugins/modules/gitlab_project_members.py, plugins/modules/gitlab_user.py, plugins/modules/imc_rest.py, plugins/modules/influxdb_retention_policy.py, plugins/modules/ipa_host.py, plugins/modules/ipa_vault.py, plugins/modules/jenkins_job_info.py, plugins/modules/jenkins_script.py, plugins/modules/manageiq_alert_profiles.py, plugins/modules/manageiq_alerts.py, plugins/modules/manageiq_group.py, plugins/modules/manageiq_policies.py, plugins/modules/manageiq_provider.py, plugins/modules/manageiq_tags.py, plugins/modules/manageiq_tenant.py, plugins/modules/manageiq_user.py, plugins/modules/xenserver_guest.py
Make examples more secure.
various
=> Only disable cert validation in examples for local network access

tests/integration/targets/alternatives/tasks/tests_set_priority.yml, tests/integration/targets/archive/tests/core.yml, tests/integration/targets/archive/tests/remove.yml, tests/integration/targets/cmd_runner/aliases, tests/integration/targets/deploy_helper/tasks/main.yml, tests/integration/targets/ini_file/tasks/tests/00-basic.yml, tests/integration/targets/lvg/tasks/test_active_change.yml
Currently CI fails due to bad expressions. These were legal before, but are now forbidden. (Finally.)
various
=> Fix bad expressions in tests

tests/integration/targets/osx_defaults/tasks/main.yml
For some reason this didn't show up in #7625.
osx_defaults
=> Fix osx_defaults tests

tests/integration/targets/alternatives/tasks/tests_set_priority.yml, tests/integration/targets/archive/tests/core.yml, tests/integration/targets/archive/tests/remove.yml, tests/integration/targets/cmd_runner/aliases, tests/integration/targets/deploy_helper/tasks/main.yml, tests/integration/targets/ini_file/tasks/tests/00-basic.yml, tests/integration/targets/osx_defaults/tasks/main.yml
Backport of #7625 to stable-6.
various
=> [stable-6] Fix bad expressions in tests

.github/BOTMETA.yml, plugins/modules/gitlab_issue.py, tests/integration/targets/gitlab_issue/aliases, tests/integration/targets/gitlab_issue/defaults/main.yml, tests/integration/targets/gitlab_issue/files/description.md, tests/integration/targets/gitlab_issue/tasks/main.yml
A new Ansible module gitlab_issue for creating, updating, or deleting GitLab issues.
`gitlab_issue`
A new Ansible module `gitlab_issue` for creating, updating, or deleting GitLab issue resources utilizing [python-gitlab](https://python-gitlab.readthedocs.io/en/stable/) library. This work is based on previously available GitLab-related modules in the collection. To the best of my knowledge, a similar module for manipulating Gitlab issues is missing from the collection.
=> New module: gitlab_issue.py

changelogs/fragments/7577-fix-apt_rpm-module.yml, plugins/modules/apt_rpm.py
Added function to compare version between installed package and candidate. 
Package will be installed if the candidate is newer than the existing.
Fixes https://github.com/ansible-collections/community.general/issues/7414.
plugins/modules/apt_rpm.py
=> apt_rpm: add check if package version is upgradable (ansible-collections#7414)

changelogs/fragments/7577-fix-apt_rpm-module.yml, plugins/modules/apt_rpm.py
Backport of #7577 to stable-8.
apt_rpm
=> [stable-8] apt_rpm: add check if package version is upgradable (ansible-collections#7414)

changelogs/fragments/7601-lvol-fix.yml, plugins/modules/lvol.py
=> lvol: check return message in both stderr and stdout

changelogs/fragments/7645-Keycloak-print-error-msg-from-server.yml, plugins/module_utils/identity/keycloak/keycloak.py
Backport of #7645 to stable-8.
keycloak module utils
=> [stable-8] Keycloak print error msg from server (#7645)

tests/integration/targets/ejabberd_user/tasks/main.yml, tests/integration/targets/setup_postgresql_db/tasks/main.yml
Nightlies have been failing.
ejabberd_user
odbc
=> Fix integration tests on Arch

tests/integration/targets/setup_java_keytool/tasks/main.yml, tests/integration/targets/setup_java_keytool/vars/Alpine.yml, tests/integration/targets/setup_java_keytool/vars/Archlinux.yml, tests/integration/targets/setup_java_keytool/vars/Debian-12.yml, tests/integration/targets/setup_java_keytool/vars/Debian.yml, tests/integration/targets/setup_java_keytool/vars/Suse.yml
Currently these fail.
java keytool setup
=> Fix keytool setup on Debian Bookworm

plugins/modules/mail.py
* using timeout parameter within community.general.mail module
* consolidated time-out example within an existing playbook
* consolidated time-out example within an existing playbook
* Update plugins/modules/mail.py
Co-authored-by: Felix Fontein <felix@fontein.de>
---------
Co-authored-by: Felix Fontein <felix@fontein.de>
(cherry picked from commit 916f6f7c878bbf093f3d118a212985105597e317)
```paste below
```
=> [stable-8] using timeout parameter within community.general.mail module (#7731)

plugins/lookup/bitwarden.py
=> Improve docs of bitwarden lookup

.github/BOTMETA.yml, plugins/connection/incus.py, tests/integration/targets/connection_incus/aliases, tests/integration/targets/connection_incus/runme.sh, tests/integration/targets/connection_incus/test_connection.inventory
This introduces a new connection plugin for Incus.
This is extremely heavily based on the great work of @mattclay with the LXD plugin.
On top of a general rename of anything LXD to Incus, this also cleans up a bunch of the wording to be inclusive of virtual machines. It also now uses the `--quiet` flag to avoid weird artifacts during file transfers.
Closes #7376 
plugins/connection/incus
=> Introduce an Incus connection plugin

plugins/modules/cloudflare_dns.py
=> cloudflare_dns: announce removal of SPF support

.github/BOTMETA.yml
I no longer have the free time to help maintain the IPA module. Removing myself.
IPA
=> Update BOTMETA.yml - Remove fxfitz as maintainer of IPA

.github/BOTMETA.yml
Manual backport of #7767 to stable-7.
BOTMETA
=> [stable-7] Update BOTMETA.yml - Remove fxfitz as maintainer of IPA (#7767)

.github/BOTMETA.yml, plugins/module_utils/proxmox.py, plugins/modules/proxmox_storage_contents_info.py, tests/integration/targets/proxmox/tasks/main.yml, tests/unit/plugins/modules/test_proxmox_storage_contents_info.py
Add  new module to list content of proxmox storage attached to a node
Fixes #7724 
new module: proxmox_storage_list
=> Proxmox add storage content listing

.github/BOTMETA.yml, plugins/module_utils/proxmox.py, plugins/modules/proxmox_storage_contents_info.py, tests/integration/targets/proxmox/tasks/main.yml, tests/unit/plugins/modules/test_proxmox_storage_contents_info.py
Backport of #7725 to stable-8.
proxmox_storage_contents_info
=> [stable-8] Proxmox add storage content listing (#7725)

tests/integration/targets/xml/tasks/main.yml
Nightly tests fail because of this on RHEL 8.7 and 8.8.
xml
=> CI: fix xml tests on RHEL 8

changelogs/fragments/7782-cloudflare_dns-spf.yml, plugins/modules/cloudflare_dns.py
=> cloudflare_dns: remove support for SPF records

.github/workflows/import-galaxy.yml
Backport of #7839 to stable-7.
CI
=> [stable-7] Use import galaxy workflow from ansible-collections/community.docker#754

.github/workflows/import-galaxy.yml
Backport of #7839 to stable-8.
CI
=> [stable-8] Use import galaxy workflow from ansible-collections/community.docker#754

tests/integration/targets/setup_tls/files/ca_certificate.pem, tests/integration/targets/setup_tls/files/ca_certificate.pem.license, tests/integration/targets/setup_tls/files/ca_key.pem, tests/integration/targets/setup_tls/files/ca_key.pem.license, tests/integration/targets/setup_tls/files/client_certificate.pem, tests/integration/targets/setup_tls/files/client_certificate.pem.license, tests/integration/targets/setup_tls/files/client_key.pem, tests/integration/targets/setup_tls/files/client_key.pem.license, tests/integration/targets/setup_tls/files/server_certificate.pem, tests/integration/targets/setup_tls/files/server_certificate.pem.license, tests/integration/targets/setup_tls/files/server_key.pem, tests/integration/targets/setup_tls/files/server_key.pem.license
Backport of #7858 to stable-6.
reuse test
=> [stable-6] Make compatible with newer reuse versions

changelogs/fragments/7882-add-redfish-get-service-identification.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_info.py
Proposed changes for https://github.com/ansible-collections/community.general/issues/7882
=> Add redfish_info command to get service identification

changelogs/fragments/7882-add-redfish-get-service-identification.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_info.py
Backport of #7883 to stable-8.
redfish_info
=> [stable-8] Add redfish_info command to get service identification (#7883)

changelogs/fragments/7872-proxmox_fix update if setting doesnt exist.yaml, plugins/modules/proxmox.py
Fixes #7871
proxmox
```paste below
```
=> fix proxmox update when setting does not already exist

.github/BOTMETA.yml, plugins/module_utils/gitlab.py, plugins/modules/gitlab_label.py, tests/integration/targets/gitlab_label/README.md, tests/integration/targets/gitlab_label/aliases, tests/integration/targets/gitlab_label/defaults/main.yml, tests/integration/targets/gitlab_label/tasks/main.yml
Backport of #7657 to stable-8.
gitlab_label
=> [stable-8] New module: gitlab_label (#7657)

changelogs/fragments/7901-consul-acl-deprecation.yaml, meta/runtime.yml, plugins/modules/consul_acl.py
Deprecate `consul_acl` in favor of `consul_token` and `consul_policy`
consul_acl
=> Consul acl deprecation

changelogs/fragments/7896-add-terraform-diff-mode.yml, plugins/modules/terraform.py
Addition diff_mode to community.general.terraform module
community.general.terraform
=> terraform: support diff for resource_changes

changelogs/fragments/7896-add-terraform-diff-mode.yml, plugins/modules/terraform.py
Backport of #7896 to stable-8.
terraform
=> [stable-8] terraform: support diff for resource_changes (#7896)

plugins/modules/apk.py
=> fix typo: it's own -> its own

plugins/modules/apk.py
Backport of #7923 to stable-7.
apk
=> [stable-7] fix typo: it's own -> its own (#7923)

plugins/modules/apk.py
Backport of #7923 to stable-8.
apk
=> [stable-8] fix typo: it's own -> its own (#7923)

plugins/modules/iso_customize.py
Backport of #7927 to stable-7.
iso_customize
=> [stable-7] Update iso_customize.py notes section (#7927)

changelogs/fragments/7843-proxmox_kvm-update_unsafe.yml, plugins/modules/proxmox_kvm.py
Backport of #7843.
proxmox_kvm
=> [stable-8] proxmox_kvm - new param to support unsafe updates (#7843)

changelogs/fragments/7916-add-redfish-set-service-identification.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_config.py
Backport of #7917.
redfish_config
=> [stable-8] Add redfish_config command to set service identification (#7917)

.github/BOTMETA.yml
Ref: https://github.com/ansible-collections/overview/issues/232#issuecomment-1941665071
CC @krauthosting
BOTMETA
=> Add krauthosting as proxmox maintainer

.github/BOTMETA.yml, plugins/callback/default_without_diff.py, tests/integration/targets/callback_default_without_diff/aliases, tests/integration/targets/callback_default_without_diff/tasks/main.yml
Backport of #7949.
default_without_diff callback
=> [stable-8] Add default_without_diff callback (#7949)

tests/integration/targets/apk/aliases, tests/integration/targets/apk/tasks/main.yml
Implements integration tests for apk to test for the bug described in https://github.com/ansible-collections/community.general/issues/7990
apk
I was unable to reproduce the error in https://github.com/ansible-collections/community.general/issues/7990 and wanted to persist this through tests.
=> Implement integration tests for apk

changelogs/fragments/8003-redfish-get-update-status-empty-response.yml, plugins/module_utils/redfish_utils.py
Added an optional parameter to the GET method for Redfish to allow for the possibility of an empty response. Every GET operation in Redfish is expected to return 200 OK in the success case, but task monitors are a bit odd in that it's a GET request that will contain the result of a long running operation. For example, a POST to an action can sometimes take a long time, and clients poll the task monitor with GET requests until complete. In simplistic services, a 204 No Content is a possibility.
Fix #8003 
redfish_utils
Note, this requires a system that returns 204 as the final response when querying the handle referenced by the "update_handle" parameter
```paste below
---
- hosts: all
vars:
username: REDACTED
password: REDACTED
baseuri: REDACTED …
```
=> Redfish: Enhanced GetUpdateStatus to allow for empty responses to accomodate possible usage of 204 No Content

changelogs/fragments/7983-sudoers-add-support-noexec.yml, plugins/modules/sudoers.py, tests/integration/targets/sudoers/tasks/main.yml
This adds support for the NOEXEC tag in the sudoers module
sudoers
This add support to the NOEXEC tag of the sudoers configuration file to, which prevents an executable from running another command itself.
https://www.sudo.ws/docs/man/1.8.32/sudoers.man/#NOEXEC
```
- name: Create rule with default parameters
community.general.sudoers:
name: my-sudo-rule-default
state: present
user: alice
commands: /usr/bin/less
- name: Create rule with noexec parameters
community.general.sudoers:
name: my-sudo-rule-noexec
state: present
user: alice
commands: /usr/bin/less
noexec: true
TASK [sudoers : Create rule with default parameters] ***************************
changed: [testhost] => {"changed": true}
TASK [sudoers : Create rule with noexec parameters] …
```
=> Add noexec support to sudoers

.github/BOTMETA.yml, plugins/modules/gitlab_group_access_token.py, plugins/modules/gitlab_project_access_token.py, tests/integration/targets/gitlab_group_access_token/aliases, tests/integration/targets/gitlab_group_access_token/defaults/main.yml, tests/integration/targets/gitlab_group_access_token/tasks/main.yml, tests/integration/targets/gitlab_project_access_token/aliases, tests/integration/targets/gitlab_project_access_token/defaults/main.yml, tests/integration/targets/gitlab_project_access_token/tasks/main.yml, tests/unit/plugins/modules/gitlab.py, tests/unit/plugins/modules/test_gitlab_group_access_token.py, tests/unit/plugins/modules/test_gitlab_project_access_token.py
Modules for creating, revoking and updating GitLab access tokens on group and project levels.
gitlab_group_access_token
gitlab_project_access_token
=> GitLab group and project access token modules

plugins/modules/proxmox.py
Fixed missing apostrophes at proxmox.py examples.
plugins/modules/proxmox.py
=> Fix missing apostrophes at proxmox.py examples

plugins/modules/htpasswd.py
Add the exact package name for debian and Ubuntu
htpasswd
```paste below
```
First time pull requests here, Do I need to edit something ?
=> Fix instruction for distro Ubuntu and Debian for htpasswd depends

tests/unit/plugins/module_utils/test_module_helper.py
Small function in test code seems to be no longer used.
=> remove code no longer used

changelogs/fragments/pacemaker-cluster.yml, plugins/modules/pacemaker_cluster.py
The module claims to support check mode, but in fact it does not care about `module.check_mode`.
Fixes #8062.
pacemaker_cluster
=> pacemaker_cluster: implement check mode

tests/integration/targets/cloud_init_data_facts/tasks/main.yml
Ref: https://dev.azure.com/ansible/community.general/_build/results?buildId=106709&view=logs&j=75a4a549-a18e-57a9-f076-358e970062f4&t=41b9ae62-16dc-5c19-21c5-ada4f13e9f56
cloud_init_data_facts integration tests
=> Skip cloud_init_data_facts tests on OpenSuSE Leap 15

plugins/lookup/github_app_access_token.py
The name of the plugin in the example isn't correct (anymore).
community.general.github_app_access_token
```paste below
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('community.general.github_app_token', key_path='<redacted>',  app_id='<redacted>', installation_id='<redacted>') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: lookup plugin (community.general.github_app_token) not found"}
```
=> Fix plugin call in example

changelogs/fragments/7880-ipa-fix-sudo-and-hbcalrule-idempotence.yml, plugins/modules/ipa_hbacrule.py, plugins/modules/ipa_sudorule.py
freeipa changed the type of ipaenabledflag to bool with commit https://pagure.io/freeipa/c/6c5f2bcb301187f9844985ffe309c7d2262e16f3
- ipa_sudorule
- ipa_hbacrule
=> ipa_sudorule, ipa_hbacrule: change ipaenabledflag type to bool

tests/integration/targets/snap/tasks/main.yml, tests/integration/targets/snap/tasks/test_channel.yml, tests/integration/targets/snap/tasks/test_dangerous.yml
=> snap: disable some tests that take way too long

changelogs/fragments/8163-redfish-implementing-reset-to-defaults.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_command.py
Fixing #8163
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>
```paste below
```
=> Redfish: implementing ResetToDefaults

changelogs/fragments/hipchat.yml, meta/runtime.yml, plugins/callback/hipchat.py
=> Deprecate hipchat callback

changelogs/fragments/8263-apt_rpm-install-check.yml, plugins/modules/apt_rpm.py
Backport of #8263 to stable-7.
apt_rpm
=> [stable-2.7] apt_rpm: fix package install check (#8263)

changelogs/fragments/8280-mh-deprecations.yml, plugins/module_utils/mh/mixins/deps.py, plugins/module_utils/module_helper.py
This a complement to the PR #8226 , in which a number of MH features are deprecated.
plugins/module_utils/mh/mixins/deps.py
=> MH: deprecate features

tests/integration/targets/cpanm/tasks/main.yml
They currently fail, and the situation hasn't improved after waiting a bit.
Related: https://github.com/ansible-collections/community.general/pull/8290
cpanm
=> Disable cpanm tests for RHEL 7 and CentOS 7

tests/integration/targets/django_manage/tasks/main.yaml
They currently fail: https://dev.azure.com/ansible/community.general/_build/results?buildId=111297&view=logs&j=2b5d596d-4bb1-593c-90b4-8359a37489dc&t=614ffdb6-961e-57b2-def6-b0123a0aa0d7
django_manage
=> Fix django_manage tests

plugins/modules/gitlab_runner.py
This PR improves `gitlab_runner` module docs and examples.
Fixes #8186 
gitlab_runner
N/A
=> docs(gitlab_runner): improve docs and add examples

changelogs/fragments/8323-refactor-homebrew-logic-module-utils.yml, plugins/module_utils/homebrew.py, plugins/modules/homebrew.py, plugins/modules/homebrew_cask.py, tests/unit/plugins/modules/test_homebrew.py
Fixes #8323.
There is some validation logic across the homebrew modules that has been copy-pasted. This should be moved to module_utils to promote code re-use and maintainability.
Fixes #8323.
homebrew
=> homebrew: Move repeated logic from homebrew modules into module_utils

changelogs/fragments/8334-proxmox-action-group.yml, meta/runtime.yml, plugins/doc_fragments/proxmox.py, plugins/modules/proxmox.py, plugins/modules/proxmox_disk.py, plugins/modules/proxmox_domain_info.py, plugins/modules/proxmox_group_info.py, plugins/modules/proxmox_kvm.py, plugins/modules/proxmox_nic.py, plugins/modules/proxmox_node_info.py, plugins/modules/proxmox_pool.py, plugins/modules/proxmox_pool_member.py, plugins/modules/proxmox_snap.py, plugins/modules/proxmox_storage_contents_info.py, plugins/modules/proxmox_storage_info.py, plugins/modules/proxmox_tasks_info.py, plugins/modules/proxmox_template.py, plugins/modules/proxmox_user_info.py, plugins/modules/proxmox_vm_info.py
Adds a community.general.proxmox module defaults group (action group).
Ref: #8074
proxmox modules
=> Add proxmox action group

.github/BOTMETA.yml, plugins/doc_fragments/django.py, plugins/module_utils/django.py, plugins/modules/django_command.py, tests/unit/plugins/modules/helper.py, tests/unit/plugins/modules/test_django_command.py, tests/unit/plugins/modules/test_django_command.yaml
New, revamped, module utils and a simple `django_command` module to replace `django_manage` in the future.
plugins/module_utils/django.py
plugins/modules/django_command.py
=> Initial commit for django modutils and django_command module

plugins/modules/ldap_search.py
Fixes #8358
ldap_search
See #8358 for info/discussion
=> add clarifying notes to scope description

plugins/callback/yaml.py, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt
Manual backport of #8396.
yaml callback
=> [stable-8] docs: add seealso and notes for yaml callback plugin (#8396)

plugins/callback/yaml.py, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt
Manual backport of #8396.
yaml callback
=> [stable-7] docs: add seealso and notes for yaml callback plugin (#8396)

tests/sanity/ignore-2.17.txt, tests/sanity/ignore-2.18.txt, tests/unit/plugins/modules/helper.py, tests/unit/plugins/modules/test_django_command.yaml
Handle rc != 0 when check_rc = True
```paste below
```
=> fix test helper handling of rc

changelogs/fragments/8413-galaxy-refactor.yml, plugins/modules/ansible_galaxy_install.py
=> ansible_galaxy_install: minor refactor

changelogs/fragments/8406-fix-homebrew-cask-warning.yaml, plugins/modules/homebrew.py
Manual backport of #8406 to stable-8.
homebrew
=> [stable-8] Fix the homebrew module failing because of warnings (#8406)

changelogs/fragments/8415-cmd-runner-stack.yml, plugins/module_utils/cmd_runner.py, tests/unit/plugins/module_utils/test_cmd_runner.py
Add a `stack` decorator to replicate some format over
=> add cmd_runner_fmt.stack decorator

changelogs/fragments/8430-fix-opentelemetry-when-using-logs-with-uri-or-slurp-tasks.yaml, plugins/callback/opentelemetry.py
Backport of #8430 to stable-8.
opentelemetry callback plugin
=> [stable-8] fix(opentelemetry): remove request from the logs (#8430)

changelogs/fragments/8452-git_config-absent.yml, plugins/modules/git_config.py, tests/integration/targets/git_config/tasks/unset_value.yml
=> git_config: fix state=absent if value is present

.github/BOTMETA.yml, docs/docsite/extra-docs.yml, docs/docsite/rst/guide_deps.rst, docs/docsite/rst/guide_vardict.rst
Add documentation for the `VarDict` module util.
=> add docs for the vardict module utils

.github/BOTMETA.yml, plugins/modules/django_check.py, tests/unit/plugins/modules/test_django_check.py, tests/unit/plugins/modules/test_django_check.yaml
Creates module `django_check`
django_check
=> django_check: new module

plugins/filter/lists_mergeby.py
Fix #8474
community.general.lists_mergeby
NA
=> Update docs lists_mergeby

changelogs/fragments/8479-cmdrunner-improvements.yml, plugins/module_utils/cmd_runner.py
=> cmd_runner mod util: improvements

docs/docsite/rst/guide_vardict.rst
Fix the version in which `vardict` was addded in the documentation guide.
=> fix version vardict was introduced

.github/BOTMETA.yml, meta/runtime.yml, plugins/module_utils/consul.py, plugins/modules/consul_agent_check.py, plugins/modules/consul_agent_service.py, plugins/modules/consul_auth_method.py, plugins/modules/consul_binding_rule.py, plugins/modules/consul_policy.py, plugins/modules/consul_role.py, plugins/modules/consul_token.py, tests/integration/targets/consul/tasks/consul_agent_check.yml, tests/integration/targets/consul/tasks/consul_agent_service.yml, tests/integration/targets/consul/tasks/main.yml
Implement new modules consul_agent_service and consul_agent_check based on the _ConsulModule class from @apollo13.
Add implementation tests from consul_agent_service and consul_agent_check.
community.general.consul_agent_service
community.general.consul_agent_check
```paste below
```
=> Consul implement agent service and check

changelogs/fragments/8512-as-bool-not.yml, plugins/module_utils/cmd_runner.py
Simplify implementation of the function.
=> simplify cmd_runner_fmt.as_bool_not()

.azure-pipelines/azure-pipelines.yml
Ref: https://github.com/ansible/ansible/commit/dad6f077319d993c0fa440dd426174a54f034c53
CI
=> Update CI for ansible-core devel

tests/unit/plugins/module_utils/test_cmd_runner.py
=> add test case for cmd_runner_fmt.as_list()

changelogs/fragments/8533-add-ciphers-option.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_command.py, plugins/modules/redfish_config.py, plugins/modules/redfish_info.py
Adds an option for ciphers to the redfish modules and aligns with the ciphers option of the ansible.builtin.uri and community.crypto.get_certificate modules.
- redfish_command
- redfish_config
- redfish_info
I use Ansible to manage various device types (e.g. PDU's, BMC's, etc) that only support legacy ciphers and/or do not support >2048 bit certificates. For some of these devices, depending on the Ansible controller, the redfish modules were experiencing a handshake failure, though I could still interact them with CLI or GUI web browsers (curl, Chrome, Firefox).
Without manually setting ciphers (example endpoint uses 2048 bit cert, TLSv1.2 / ECDHE-RSA-AES256-SHA, cannot be changed):
```
TASK [community.general.redfish_info] …
```
=> Enable Custom Cipher Selection for Redfish Modules

changelogs/fragments/8516-proxmox-template-refactor.yml, plugins/modules/proxmox_template.py
Small improvement on the logic for determining whether a template exists.
proxmox_template
=> proxmox_template: small refactor in get_template()

changelogs/fragments/8557-fix-bug-with-bitwarden.yml, plugins/lookup/bitwarden.py
Fix the KeyError in #8549.
(no changelog fragment needed for this, right?)
bitwarden
=> bitwarden: Fix KeyError in search_field (#8549)

plugins/modules/rpm_ostree_pkg.py
expand examples list with 'until' example
Adding example to docs.
rpm_ostree_pkg.py
=> Add example to rpm_ostree_pkg

CHANGELOG.md, CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/8214-sudosu-not-working-on-some-BSD-machines.yml, changelogs/fragments/8444-fix-redfish-gen2-upgrade.yaml, changelogs/fragments/8508-virtualbox-inventory.yml, changelogs/fragments/8516-proxmox-template-refactor.yml, changelogs/fragments/8517-cmd-runner-lang-auto.yml, changelogs/fragments/8533-add-ciphers-option.yml, changelogs/fragments/8542-fix-proxmox-volume-handling.yml, changelogs/fragments/8545-keycloak-clientscope-remove-id-on-compare.yml, changelogs/fragments/8557-fix-bug-with-bitwarden.yml, changelogs/fragments/8613-redfish_utils-language.yaml, changelogs/fragments/8614-nsupdate-index-out-of-range.yml, changelogs/fragments/9.2.0.yml
=> Release 9.2.0 commit

galaxy.yml
Bump next expected version after release
galaxy.yml
=> Bump next expected version after release

changelogs/fragments/8625-inventory-types.yml, plugins/inventory/cobbler.py, plugins/inventory/linode.py, plugins/inventory/lxd.py, plugins/inventory/nmap.py, plugins/inventory/online.py, plugins/inventory/scaleway.py, plugins/inventory/stackpath_compute.py, plugins/inventory/virtualbox.py
=> Type options of inventory plugins

changelogs/fragments/8627-connection-types.yml, plugins/connection/chroot.py, plugins/connection/funcd.py, plugins/connection/incus.py, plugins/connection/iocage.py, plugins/connection/jail.py, plugins/connection/lxc.py, plugins/connection/lxd.py, plugins/connection/qubes.py, plugins/connection/zone.py
=> Type options of connection plugins

changelogs/fragments/8628-callback-types.yml, plugins/callback/cgroup_memory_recap.py, plugins/callback/hipchat.py, plugins/callback/jabber.py, plugins/callback/log_plays.py, plugins/callback/loganalytics.py, plugins/callback/logentries.py, plugins/callback/logstash.py, plugins/callback/slack.py, plugins/callback/splunk.py, plugins/callback/sumologic.py, plugins/callback/syslog_json.py
=> Type options of callback plugins

tests/integration/targets/pipx/aliases, tests/integration/targets/pipx/tasks/main.yml, tests/integration/targets/pipx_info/aliases, tests/integration/targets/pipx_info/tasks/main.yml
Fixes some issues in pipx tests
- inject httpx instead of black in ansible-lint (int tests)
Fixes #6878 
pipx
=> Fix pipx tests

.github/BOTMETA.yml, plugins/modules/bootc_manage.py, tests/unit/plugins/modules/test_bootc_manage.py
Introduction of functionality to manage bootc systems through switching or updating
bootc-manage 
Open to any feedback but this functionality will be incredibly helpful for those folks wanting to use bootc especially with ansible
=> Introduce bootc functionality

plugins/modules/timezone.py, tests/integration/targets/timezone/tasks/main.yml
Following the findings in #8692 , this PR updates the integration tests so that it no longer fails in Ubuntu 24.04
timezone
=> ensure util-linux-extra is installed in Ubuntu 24.04

changelogs/fragments/8711-gconftool2-refactor.yml, plugins/modules/gconftool2.py
Use some features from MH to simplify the code a bit.
gconftool2
=> gconftool2: minor refactor

changelogs/fragments/8675-pipx-install-suffix.yml, plugins/module_utils/pipx.py, plugins/modules/pipx.py, tests/integration/targets/pipx/tasks/main.yml
Add parameter `suffix` to module.
Fixes #8656 
pipx
=> pipx - add suffix parameter

plugins/action/iptables_state.py, plugins/callback/opentelemetry.py, plugins/module_utils/ilo_redfish_utils.py, plugins/modules/aix_inittab.py, plugins/modules/cronvar.py, plugins/modules/iptables_state.py, plugins/modules/memset_zone_record.py, plugins/modules/proxmox.py, plugins/modules/proxmox_disk.py, plugins/modules/snmp_facts.py, tests/unit/plugins/inventory/test_xen_orchestra.py
ansible-core devel updated some of it sanity tests.
various
=> Fix pylint and pep8 issues exposed by latest ansible-core's ansible-test sanity checks

tests/integration/targets/gandi_livedns/aliases
Ref: https://github.com/ansible-collections/community.general/pull/8718#discussion_r1707086942
gandi_livedns integration tests
=> Remove invalid cloud/gandi entry

CONTRIBUTING.md
Fixes #8683
Relates to https://github.com/ansible/ansible/pull/83610, https://github.com/ansible/ansible/pull/83677
Clarifies the contribution guide on running integration tests.
=> Clarify contribution guide on integration tests

tests/integration/targets/django_manage/meta/main.yml, tests/integration/targets/django_manage/tasks/main.yaml, tests/integration/targets/setup_os_pkg_name/tasks/alpine.yml, tests/integration/targets/setup_os_pkg_name/tasks/archlinux.yml, tests/integration/targets/setup_os_pkg_name/tasks/debian.yml, tests/integration/targets/setup_os_pkg_name/tasks/default.yml, tests/integration/targets/setup_os_pkg_name/tasks/main.yml, tests/integration/targets/setup_os_pkg_name/tasks/redhat.yml, tests/integration/targets/setup_os_pkg_name/tasks/suse.yml
The test failed using the default container in my local test. Trying to make it more generic.
django_manage
=> django_manage: rely on package idempotency to install virtualenv

changelogs/fragments/8673-add-gitlab-project-cleanup-policy.yml, changelogs/fragments/8674-add-gitlab-project-cleanup-policy.yml, plugins/modules/gitlab_project.py
Add two new attributes for `gitlab_project`.
`repository_access_level` allows disabling project repository
`container_expiration_policy` allows setting container registry [cleanup policy](https://docs.gitlab.com/ee/development/packages/cleanup_policies.html)
gitlab_project
```paste below
```
=> Gitlab_project: add options for repository_access_level and container_expiration_policy

docs/docsite/links.yml
Improve communication info.
docs/docsite/links.yml
=> Improve communication info

plugins/modules/one_template.py
i finally got it changed this year :)
don't think this warrants a changelog fragment, so i skipped that.
one_template
n/a
=> one_template: update name in copyright

changelogs/fragments/8776-mute-vardict-deprecation.yml, plugins/modules/gio_mime.py, plugins/modules/jira.py
Setting the variable to mute the deprecation warning, that will help locate and update them in the future as well.
jira
gio_mime
=> MH: use mute_vardict_deprecation

.github/BOTMETA.yml, docs/docsite/extra-docs.yml, docs/docsite/rst/guide_modulehelper.rst
Add a guide to `ModuleHelper` and associated features.
=> ModuleHelper guide

plugins/modules/pipx.py
Add example to documentation
Fixes #7666 
pipx
=> pipx: add doc example

changelogs/fragments/8791-mh-cause-changes-param-depr.yml, plugins/module_utils/mh/deco.py, plugins/modules/jira.py, tests/unit/plugins/module_utils/test_module_helper.py
Deprecate params and use new one in jira module.
plugins/module_utils/mh/deco.py
plugins/modules/jira.py
=> MH cause_changes: deprecate params

tests/unit/plugins/modules/test_datadog_downtime.py
The test has been disabled because it started to fail after an update of the Datadog API client. The issue itself (id cannot be set in constructor) and other issues (module name, additional attribute in API responses) are now fixed. The test runs successfully again.
Fixes #3219.
datadog_downtime
=> Fix and enable test for datadog_downtime

changelogs/fragments/8814-dict-comprehension.yml, plugins/filter/hashids.py, plugins/filter/keep_keys.py, plugins/filter/remove_keys.py, plugins/filter/replace_keys.py, plugins/module_utils/csv.py, plugins/module_utils/mh/mixins/vars.py, plugins/module_utils/vardict.py, plugins/modules/apache2_mod_proxy.py, plugins/modules/gitlab_group.py, plugins/modules/keycloak_client.py, plugins/modules/keycloak_clientscope.py, plugins/modules/keycloak_identity_provider.py, plugins/modules/keycloak_user_federation.py, plugins/modules/linode.py, plugins/modules/lxd_container.py, plugins/modules/manageiq_provider.py, plugins/modules/one_service.py, plugins/modules/one_vm.py, plugins/modules/proxmox.py, plugins/modules/proxmox_disk.py, plugins/modules/proxmox_kvm.py, plugins/plugin_utils/unsafe.py, tests/sanity/extra/botmeta.py
This is PR mass-replace the construct `dict((k, v) for k, v in d if condition)` with dict comprehensions: `{k: v for k, v in d if condition}`
plugins/filter/hashids.py
plugins/filter/keep_keys.py
plugins/filter/remove_keys.py
plugins/filter/replace_keys.py
plugins/module_utils/csv.py
plugins/module_utils/mh/mixins/vars.py
plugins/module_utils/vardict.py
plugins/modules/apache2_mod_proxy.py
plugins/modules/gitlab_group.py
plugins/modules/keycloak_client.py
plugins/modules/keycloak_clientscope.py
plugins/modules/keycloak_identity_provider.py
plugins/modules/linode.py
plugins/modules/lxd_container.py
plugins/modules/manageiq_provider.py
plugins/modules/one_service.py
plugins/modules/one_vm.py
plugins/modules/proxmox.py …
=> Use dict comprehension in plugins

changelogs/fragments/8822-dict-comprehension.yml, plugins/lookup/credstash.py, plugins/module_utils/identity/keycloak/keycloak.py, plugins/module_utils/mh/deco.py, plugins/module_utils/redfish_utils.py, plugins/module_utils/scaleway.py, plugins/modules/etcd3.py, plugins/modules/gitlab_project.py, plugins/modules/hwc_ecs_instance.py, plugins/modules/hwc_evs_disk.py, plugins/modules/hwc_vpc_eip.py, plugins/modules/hwc_vpc_peering_connect.py, plugins/modules/hwc_vpc_port.py, plugins/modules/hwc_vpc_subnet.py, plugins/modules/ipa_otptoken.py, plugins/modules/keycloak_user_federation.py, plugins/modules/lxc_container.py, plugins/modules/proxmox_kvm.py, plugins/modules/scaleway_security_group.py, plugins/modules/ufw.py, plugins/modules/vmadm.py
Another PR to mass-replace the construct `dict((k, v) for k, v in d if condition)` with dict comprehensions: `{k: v for k, v in d if condition}`
plugins/lookup/credstash.py
plugins/module_utils/identity/keycloak/keycloak.py
plugins/module_utils/mh/deco.py
plugins/module_utils/scaleway.py
plugins/modules/etcd3.py
plugins/modules/gitlab_project.py
plugins/modules/hwc_ecs_instance.py
plugins/modules/hwc_evs_disk.py
plugins/modules/hwc_vpc_eip.py
plugins/modules/hwc_vpc_peering_connect.py
plugins/modules/hwc_vpc_port.py
plugins/modules/hwc_vpc_subnet.py
plugins/modules/ipa_otptoken.py
plugins/modules/lxc_container.py
plugins/modules/proxmox_kvm.py …
=> use dict comprehension in plugins, part 2

changelogs/fragments/8855-gio_mime_vardict.yml, plugins/modules/gio_mime.py
Adjust module to use the new VarDict class.
gio_mime
=> gio_mime: adjust module for old vardict deprecation

changelogs/fragments/8856-jira_vardict.yml, plugins/modules/jira.py
Adjust module to use the new VarDict class.
jira
=> jira: adjust module for old vardict deprecation

tests/integration/targets/snap/tasks/main.yml, tests/integration/targets/snap/tasks/test_dangerous.yml
Replace cider snap with bpytop.
Fixes #8123 
snap
=> snap tests: re-enable test for --dangerous using smaller snap

.github/BOTMETA.yml, plugins/doc_fragments/pipx.py, plugins/module_utils/pipx.py, plugins/modules/pipx.py, plugins/modules/pipx_info.py
Refactor common documentation from modules into a doc fragment. 
Also improved wording for params `name` and `source`.
pipx
pipx_info
=> pipx/pipx_info: refactor doc fragment

plugins/modules/xfconf.py, plugins/modules/xfconf_info.py
Reformat YAML content.
xfconf
xfconf_info
=> reformat module docs

plugins/modules/gitlab_runner.py
Be specific related requirements for package version. This difference change the whole dependency chain for playbook.
`community.general.gitlab_runner module` documentation.
Sorry if I left something important for the PR. It is really just a document change / clarification.
=> gitlab_runner: update requirements in docs

plugins/modules/homebrew_services.py
The examples on the documentation page are wrong.
community.general.homebrew_services
```paste below
```
=> Update example for community.general.homebrew_services

changelogs/fragments/8895-fix-comprehension.yaml, plugins/modules/lxd_container.py
Fix error introduced in commit ecc048bc12b5235247aecbc7c113029a4d3a517c
Fixes #8888 
lxd_container
=> fix comprehension

.azure-pipelines/azure-pipelines.yml, README.md, tests/sanity/ignore-2.19.txt, tests/sanity/ignore-2.19.txt.license
ansible-core's stable-2.18 branch has been created this night.
Ref: https://forum.ansible.com/t/8723
CI
=> Add stable-2.18 to CI

.azure-pipelines/azure-pipelines.yml, README.md
Ref: https://forum.ansible.com/t/8723
CI
=> [stable-8] Replace devel with stable-2.18 in CI

changelogs/fragments/deprecate-hipchat.yml, meta/runtime.yml, plugins/modules/hipchat.py
When we deprecated the hipchat callback plugin (#8184) we forgot that there's also a hipchat module...
hipchat
=> Deprecate hipchat module

plugins/modules/gitlab_group.py
Sort parameters in gitlab_group to aid in adding more params.
No changes to code.
gitlab_group
=> Sort parameters in gitlab_group to aid in adding more params

changelogs/fragments/8925-atomic.yml, plugins/modules/ini_file.py, plugins/modules/java_keystore.py, plugins/modules/jenkins_plugin.py, plugins/modules/kdeconfig.py, plugins/modules/pam_limits.py
Ref: https://github.com/ansible/ansible/issues/83950
Ref: https://github.com/ansible/ansible/pull/83951/files
various
=> Pass absolute paths to atomic_move()

docs/docsite/rst/guide_cmdrunner.rst
Some improvements in the docs after feedback.
docs/docsite/rst/guide_cmdrunner.rst
=> cmd_runner_guide: docs improvements

docs/docsite/rst/guide_cmdrunner.rst
Fix documentation for `as_bool()`
=> fix doc for cmd_runner_fmt.as_bool()

plugins/doc_fragments/pipx.py, plugins/modules/ansible_galaxy_install.py, plugins/modules/cpanm.py, plugins/modules/gconftool2.py, plugins/modules/gconftool2_info.py, plugins/modules/gio_mime.py, plugins/modules/mksysb.py, plugins/modules/pipx.py, plugins/modules/pipx_info.py, plugins/modules/xfconf.py
Add references to man pages of commands
plugins/doc_fragments/pipx.py
plugins/modules/ansible_galaxy_install.py
plugins/modules/cpanm.py
plugins/modules/gconftool2.py
plugins/modules/gio_mime.py
plugins/modules/mksysb.py
plugins/modules/xfconf.py
=> Update docs with references to man pages

plugins/filter/groupby_as_dict.py
=> groupby_as_dict: mention Jinja2's groupby filter

plugins/modules/apk.py
Update documentation for the apk module
Fixes issue #9017 
apk
The `apk` module has a `world` parameter where you can specify a path to a custom world file. However, the documentation does not mention that the file is used only under certain conditions. I have added those details to the documentation, under the description for the `world` parameter.
```paste below
```
=> Update documentation in apk.py

changelogs/fragments/9060-ansible-galaxy-install-version.yml, plugins/modules/ansible_galaxy_install.py
=> ansible_galaxy_install: add return value version

changelogs/fragments/9063-django-version.yml, plugins/module_utils/django.py, plugins/modules/django_check.py, plugins/modules/django_command.py, plugins/modules/django_createcachetable.py, tests/unit/plugins/modules/test_django_check.yaml, tests/unit/plugins/modules/test_django_command.yaml, tests/unit/plugins/modules/test_django_createcachetable.yaml
plugins/module_utils/django.py
plugins/modules/django_check.py
plugins/modules/django_command.py
plugins/modules/django_createcachetable.py
=> django_command/django_check/django_createcachetable: add return value version

changelogs/fragments/9064-gconftool2-version.yml, plugins/module_utils/gconftool2.py, plugins/modules/gconftool2.py, plugins/modules/gconftool2_info.py, tests/unit/plugins/modules/test_gconftool2.yaml, tests/unit/plugins/modules/test_gconftool2_info.yaml
plugins/module_utils/gconftool2.py
plugins/modules/gconftool2.py
plugins/modules/gconftool2_info.py
=> gconftool2/gconftool2_info: add return value version

changelogs/fragments/9067-gio-mime-version.yml, plugins/module_utils/gio_mime.py, plugins/modules/gio_mime.py, tests/unit/plugins/modules/test_gio_mime.yaml
=> gio_mime: add return value version

changelogs/fragments/9061-cpanm-version.yml, plugins/modules/cpanm.py, tests/unit/plugins/modules/test_cpanm.yaml
Add RV `cpanm_version` to module.
cpanm
=> cpanm: add return value cpanm_version

changelogs/fragments/9086-gio-mime-version.yml, plugins/modules/opkg.py, tests/unit/plugins/modules/test_opkg.yaml
=> opkg: add return value version

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/iso_extract/aliases, tests/integration/targets/pkgng/tasks/freebsd.yml
Add FreeBSD 13.4 to CI.
Ref: https://github.com/ansible/ansible/pull/84236
CI
=> Add FreeBSD 13.4 to CI

tests/integration/targets/pipx/tasks/main.yml, tests/integration/targets/pipx/tasks/testcase-8793-global.yml, tests/integration/targets/pipx/tasks/testcase-9103-upgrade-global.yml
Add test case to prove that `state=upgrade`, `global=true` generate the correct command line.
pipx
=> pipx: add testcase for upgrade --global

tests/integration/targets/locale_gen/vars/main.yml
Add test case related to #9131 
locale_gen
=> locale_gen: add testcase for de_CH.utf8

changelogs/fragments/9179-deps-tests.yml, plugins/module_utils/deps.py, tests/unit/plugins/module_utils/test_deps.py, tests/unit/plugins/module_utils/test_module_helper.py, tests/unit/plugins/modules/conftest.py
Add unit tests for deps module utils.
Add function `clear()` to clear out previously declared dependencies. Useful for testing.
plugins/module_utils/deps.py
=> deps module utils: unit tests + minor improvement

plugins/modules/ufw.py
Add note to the docs warning about concurrency
Fixes #4769 
ufw
=> ufw: add note to docs about concurrency

changelogs/fragments/9187-flatpak-lang.yml, plugins/modules/flatpak.py
Force the locale to C when running the flatpak command.
Fixes #8883 
flatpak
=> flatpak: force locale language to be C

changelogs/fragments/9167-rpm_ostree_pkg-apply_live.yml, plugins/modules/rpm_ostree_pkg.py
Feature request for #8950 #3670 
rpm_ostree_pkg
=> Add the options apply_live to rpm_ostree_pkg

changelogs/fragments/9159-iso-extract_add_password.yml, plugins/modules/iso_extract.py
Add the `password` argument to the `iso_extract` module.
iso_extract
=> iso_extract: Add password argument

changelogs/fragments/9190-redfish-utils-unused-code.yml, plugins/module_utils/redfish_utils.py
=> redfish_utils module utils: remove redundant code

changelogs/fragments/ssh_config_add_dynamicforward_option.yml, plugins/modules/ssh_config.py, tests/integration/targets/ssh_config/tasks/options.yml
Add dynamicforward option to ssh_config module.
ssh_config
```paste below
```
=> Add dynamicforward option

tests/unit/plugins/modules/helper.py, tests/unit/plugins/modules/test_snap.py, tests/unit/plugins/modules/test_xfconf_info.py, tests/unit/plugins/modules/test_xfconf_info.yaml
- additional YAML file data structure (old one will be removed later)
- TestCaseMock classes may be passed to Helper.from_module()
- rename some variables/parameters
cpanm
django_check
django_command
django_createcachetable
facter_facts
gconftool2
gconftool2_info
gio_mime
krb_ticket
opkg
puppet
xfconf
xfconf_info
snap
=> test helper improvements

.github/workflows/codeql-analysis.yml, .github/workflows/reuse.yml
Fix some issues in GHA workflows pointed out by zizmor (https://github.com/woodruffw/zizmor).
CI
=> CI: Fix some issues pointed out by zizmor

.github/BOTMETA.yml
I no longer work with ansible and/or SUSE so drop me from the team.
=> Drop myself from team_suse

tests/integration/targets/lookup_random_words/test.yml
Ref: https://dev.azure.com/ansible/community.general/_build/results?buildId=131309&view=logs&j=3003b408-b9fe-596a-96f2-5e7ceff036e9&t=56b2609e-07cd-5ad6-4fcb-fd5688a4c442&l=7682
random_words integration test
=> random_words integration tests: avoid test failure due to valid result

docs/docsite/rst/guide_modulehelper.rst
Better explain about the `ModuleHelperException` and extending it.
docs/docsite/rst/guide_modulehelper.rst
=> mh guide: update exception handling

tests/sanity/extra/botmeta.py
=> Polish botmeta extra sanity test and make it work without warnings on Python 3.13

plugins/modules/yarn.py
Fix indentation for the EXAMPLES doc block
yarn
=> fix examples indentation

plugins/modules/yum_versionlock.py
Adjustments to the module documentation
=> yum_versionlock: adjust docs

plugins/modules/zfs.py, plugins/modules/zfs_delegate_admin.py, plugins/modules/zfs_facts.py
Adjustments to the module documentation
zfs
zfs_delegate_admin
zfs_facts
=> zfs modules: adjust docs

plugins/modules/vdo.py, plugins/modules/vertica_configuration.py, plugins/modules/vertica_info.py, plugins/modules/vertica_role.py, plugins/modules/vertica_schema.py, plugins/modules/vertica_user.py, plugins/modules/vexata_eg.py, plugins/modules/vexata_volume.py, plugins/modules/vmadm.py, plugins/modules/wakeonlan.py, plugins/modules/wdc_redfish_command.py, plugins/modules/wdc_redfish_info.py
Adjust docs
plugins/modules/vdo.py
plugins/modules/vertica_configuration.py
plugins/modules/vertica_info.py
plugins/modules/vertica_role.py
plugins/modules/vertica_schema.py
plugins/modules/vertica_user.py
plugins/modules/vexata_eg.py
plugins/modules/vexata_volume.py
plugins/modules/vmadm.py
plugins/modules/wakeonlan.py
plugins/modules/wdc_redfish_command.py
plugins/modules/wdc_redfish_info.py
=> [vw]*: adjust docs

plugins/modules/zfs_facts.py, plugins/modules/znode.py, plugins/modules/zpool_facts.py
plugins/modules/zfs_delegate_admin.py
plugins/modules/zfs_facts.py
plugins/modules/znode.py
plugins/modules/zpool_facts.py
=> z mods adjust docs

changelogs/fragments/9323-fstr-inventory-plugins.yml, plugins/inventory/cobbler.py, plugins/inventory/gitlab_runners.py, plugins/inventory/icinga2.py, plugins/inventory/linode.py, plugins/inventory/lxd.py, plugins/inventory/nmap.py, plugins/inventory/online.py, plugins/inventory/opennebula.py, plugins/inventory/proxmox.py, plugins/inventory/scaleway.py, plugins/inventory/stackpath_compute.py, plugins/inventory/virtualbox.py, plugins/inventory/xen_orchestra.py
plugins/inventory/gitlab_runners.py
plugins/inventory/icinga2.py
plugins/inventory/linode.py
plugins/inventory/lxd.py
plugins/inventory/nmap.py
plugins/inventory/online.py
plugins/inventory/opennebula.py
plugins/inventory/stackpath_compute.py
plugins/inventory/virtualbox.py
plugins/inventory/xen_orchestra.py
=> inventory plugins: use f-strings

changelogs/fragments/9239-proxmox-backup-refactor.yml, plugins/modules/proxmox_backup.py
Create a generic function to check permissions and simplify the module logic by calling it.
proxmox_backup
=> proxmox_backup: refactor permission checking

plugins/modules/taiga_issue.py, plugins/modules/telegram.py, plugins/modules/terraform.py, plugins/modules/timezone.py, plugins/modules/twilio.py, plugins/modules/typetalk.py
plugins/modules/taiga_issue.py
plugins/modules/telegram.py
plugins/modules/terraform.py
plugins/modules/timezone.py
plugins/modules/twilio.py
plugins/modules/typetalk.py
=> t*: normalize docs

plugins/modules/udm_dns_record.py, plugins/modules/udm_dns_zone.py, plugins/modules/udm_group.py, plugins/modules/udm_share.py, plugins/modules/udm_user.py, plugins/modules/ufw.py, plugins/modules/uptimerobot.py, plugins/modules/urpmi.py, plugins/modules/usb_facts.py
plugins/modules/udm_dns_record.py
plugins/modules/udm_dns_zone.py
plugins/modules/udm_group.py
plugins/modules/udm_share.py
plugins/modules/udm_user.py
plugins/modules/ufw.py
plugins/modules/uptimerobot.py
plugins/modules/urpmi.py
plugins/modules/usb_facts.py
=> u[a-s]*: normalize docs

plugins/modules/solaris_zone.py, plugins/modules/sorcery.py, plugins/modules/spectrum_device.py, plugins/modules/spectrum_model_attrs.py, plugins/modules/spotinst_aws_elastigroup.py, plugins/modules/ss_3par_cpg.py, plugins/modules/ssh_config.py, plugins/modules/stacki_host.py, plugins/modules/statsd.py, plugins/modules/statusio_maintenance.py, plugins/modules/sudoers.py, plugins/modules/supervisorctl.py, plugins/modules/svc.py, plugins/modules/svr4pkg.py, plugins/modules/swdepot.py, plugins/modules/swupd.py, plugins/modules/syslogger.py, plugins/modules/syspatch.py, plugins/modules/sysrc.py, plugins/modules/sysupgrade.py
plugins/modules/solaris_zone.py
plugins/modules/sorcery.py
plugins/modules/spectrum_device.py
plugins/modules/spectrum_model_attrs.py
plugins/modules/spotinst_aws_elastigroup.py
plugins/modules/ss_3par_cpg.py
plugins/modules/ssh_config.py
plugins/modules/stacki_host.py
plugins/modules/statsd.py
plugins/modules/statusio_maintenance.py
plugins/modules/sudoers.py
plugins/modules/supervisorctl.py
plugins/modules/svc.py
plugins/modules/svr4pkg.py
plugins/modules/swdepot.py
plugins/modules/swupd.py
plugins/modules/syslogger.py
plugins/modules/syspatch.py
plugins/modules/sysrc.py
plugins/modules/sysupgrade.py
=> s[o-y]*: normalize docs

plugins/modules/say.py, plugins/modules/scaleway_compute.py, plugins/modules/scaleway_compute_private_network.py, plugins/modules/scaleway_container.py, plugins/modules/scaleway_container_info.py, plugins/modules/scaleway_container_namespace.py, plugins/modules/scaleway_container_namespace_info.py, plugins/modules/scaleway_container_registry.py, plugins/modules/scaleway_container_registry_info.py, plugins/modules/scaleway_database_backup.py, plugins/modules/scaleway_function.py, plugins/modules/scaleway_function_info.py, plugins/modules/scaleway_function_namespace.py, plugins/modules/scaleway_function_namespace_info.py, plugins/modules/scaleway_image_info.py, plugins/modules/scaleway_ip.py, plugins/modules/scaleway_ip_info.py, plugins/modules/scaleway_lb.py, plugins/modules/scaleway_organization_info.py, plugins/modules/scaleway_private_network.py, plugins/modules/scaleway_security_group.py, plugins/modules/scaleway_security_group_info.py, plugins/modules/scaleway_security_group_rule.py, plugins/modules/scaleway_server_info.py, plugins/modules/scaleway_snapshot_info.py, plugins/modules/scaleway_sshkey.py, plugins/modules/scaleway_user_data.py, plugins/modules/scaleway_volume.py, plugins/modules/scaleway_volume_info.py
plugins/modules/say.py
plugins/modules/scaleway_compute.py
plugins/modules/scaleway_compute_private_network.py
plugins/modules/scaleway_container.py
plugins/modules/scaleway_container_info.py
plugins/modules/scaleway_container_namespace.py
plugins/modules/scaleway_container_namespace_info.py
plugins/modules/scaleway_container_registry.py
plugins/modules/scaleway_container_registry_info.py
plugins/modules/scaleway_database_backup.py
plugins/modules/scaleway_function.py
plugins/modules/scaleway_function_info.py
plugins/modules/scaleway_function_namespace.py
plugins/modules/scaleway_function_namespace_info.py
plugins/modules/scaleway_image_info.py
plugins/modules/scaleway_ip.py
plugins/modules/scaleway_ip_info.py
plugins/modules/scaleway_lb.py …
=> s[a-c]*: normalize docs

plugins/modules/pids.py, plugins/modules/pingdom.py, plugins/modules/pip_package_info.py, plugins/modules/pipx.py, plugins/modules/pipx_info.py, plugins/modules/pkg5.py, plugins/modules/pkg5_publisher.py, plugins/modules/pkgin.py, plugins/modules/pkgng.py, plugins/modules/pkgutil.py, plugins/modules/pmem.py, plugins/modules/pnpm.py, plugins/modules/portage.py, plugins/modules/portinstall.py, plugins/modules/pritunl_org.py, plugins/modules/pritunl_org_info.py, plugins/modules/pritunl_user.py, plugins/modules/pritunl_user_info.py, plugins/modules/profitbricks.py, plugins/modules/profitbricks_datacenter.py, plugins/modules/profitbricks_nic.py, plugins/modules/profitbricks_volume.py, plugins/modules/profitbricks_volume_attachments.py
plugins/modules/pids.py
plugins/modules/pingdom.py
plugins/modules/pip_package_info.py
plugins/modules/pipx.py
plugins/modules/pipx_info.py
plugins/modules/pkg5.py
plugins/modules/pkg5_publisher.py
plugins/modules/pkgin.py
plugins/modules/pkgng.py
plugins/modules/pkgutil.py
plugins/modules/pmem.py
plugins/modules/pnpm.py
plugins/modules/portage.py
plugins/modules/portinstall.py
plugins/modules/pritunl_org.py
plugins/modules/pritunl_org_info.py
plugins/modules/pritunl_user.py
plugins/modules/pritunl_user_info.py
plugins/modules/profitbricks.py
plugins/modules/profitbricks_datacenter.py
plugins/modules/profitbricks_nic.py
plugins/modules/profitbricks_volume.py
plugins/modules/profitbricks_volume_attachments.py
=> [pi ... prof]*: normalize docs

plugins/modules/oneview_datacenter_info.py, plugins/modules/oneview_enclosure_info.py, plugins/modules/oneview_ethernet_network.py, plugins/modules/oneview_ethernet_network_info.py, plugins/modules/oneview_fc_network.py, plugins/modules/oneview_fc_network_info.py, plugins/modules/oneview_fcoe_network.py, plugins/modules/oneview_fcoe_network_info.py, plugins/modules/oneview_logical_interconnect_group.py, plugins/modules/oneview_logical_interconnect_group_info.py, plugins/modules/oneview_network_set.py, plugins/modules/oneview_network_set_info.py, plugins/modules/oneview_san_manager.py, plugins/modules/oneview_san_manager_info.py, plugins/modules/online_server_info.py, plugins/modules/online_user_info.py, plugins/modules/open_iscsi.py, plugins/modules/openbsd_pkg.py, plugins/modules/opendj_backendprop.py, plugins/modules/openwrt_init.py, plugins/modules/opkg.py, plugins/modules/osx_defaults.py, plugins/modules/ovh_ip_failover.py, plugins/modules/ovh_ip_loadbalancing_backend.py, plugins/modules/ovh_monthly_billing.py
plugins/modules/oneview_datacenter_info.py
plugins/modules/oneview_enclosure_info.py
plugins/modules/oneview_ethernet_network.py
plugins/modules/oneview_ethernet_network_info.py
plugins/modules/oneview_fc_network.py
plugins/modules/oneview_fc_network_info.py
plugins/modules/oneview_fcoe_network.py
plugins/modules/oneview_fcoe_network_info.py
plugins/modules/oneview_logical_interconnect_group.py
plugins/modules/oneview_logical_interconnect_group_info.py
plugins/modules/oneview_network_set.py
plugins/modules/oneview_network_set_info.py
plugins/modules/oneview_san_manager.py
plugins/modules/oneview_san_manager_info.py
plugins/modules/online_server_info.py
plugins/modules/online_user_info.py
plugins/modules/open_iscsi.py
plugins/modules/openbsd_pkg.py …
=> [onev ... ovh]*.py: normalize docs

plugins/modules/sefcontext.py, plugins/modules/selinux_permissive.py, plugins/modules/selogin.py, plugins/modules/sendgrid.py, plugins/modules/sensu_check.py, plugins/modules/sensu_client.py, plugins/modules/sensu_handler.py, plugins/modules/sensu_silence.py, plugins/modules/sensu_subscription.py, plugins/modules/seport.py, plugins/modules/serverless.py, plugins/modules/shutdown.py, plugins/modules/simpleinit_msb.py, plugins/modules/sl_vm.py, plugins/modules/slack.py, plugins/modules/slackpkg.py, plugins/modules/smartos_image_info.py, plugins/modules/snap.py, plugins/modules/snap_alias.py, plugins/modules/snmp_facts.py
plugins/modules/sefcontext.py
plugins/modules/selinux_permissive.py
plugins/modules/selogin.py
plugins/modules/sendgrid.py
plugins/modules/sensu_check.py
plugins/modules/sensu_client.py
plugins/modules/sensu_handler.py
plugins/modules/sensu_silence.py
plugins/modules/sensu_subscription.py
plugins/modules/seport.py
plugins/modules/serverless.py
plugins/modules/shutdown.py
plugins/modules/simpleinit_msb.py
plugins/modules/sl_vm.py
plugins/modules/slack.py
plugins/modules/slackpkg.py
plugins/modules/smartos_image_info.py
plugins/modules/snap.py
plugins/modules/snap_alias.py
plugins/modules/snmp_facts.py
=> s[e-n]*: normalize docs

plugins/modules/launchd.py, plugins/modules/layman.py, plugins/modules/lbu.py, plugins/modules/ldap_attrs.py, plugins/modules/ldap_entry.py, plugins/modules/ldap_passwd.py, plugins/modules/ldap_search.py, plugins/modules/librato_annotation.py, plugins/modules/linode.py, plugins/modules/linode_v4.py, plugins/modules/listen_ports_facts.py, plugins/modules/lldp.py, plugins/modules/locale_gen.py, plugins/modules/logentries.py, plugins/modules/logentries_msg.py, plugins/modules/logstash_plugin.py, plugins/modules/lvg.py, plugins/modules/lvg_rename.py, plugins/modules/lvol.py, plugins/modules/lxc_container.py, plugins/modules/lxca_cmms.py, plugins/modules/lxca_nodes.py, plugins/modules/lxd_container.py, plugins/modules/lxd_profile.py, plugins/modules/lxd_project.py
plugins/modules/launchd.py
plugins/modules/layman.py
plugins/modules/lbu.py
plugins/modules/ldap_attrs.py
plugins/modules/ldap_entry.py
plugins/modules/ldap_passwd.py
plugins/modules/ldap_search.py
plugins/modules/librato_annotation.py
plugins/modules/linode.py
plugins/modules/linode_v4.py
plugins/modules/listen_ports_facts.py
plugins/modules/lldp.py
plugins/modules/locale_gen.py
plugins/modules/logentries.py
plugins/modules/logentries_msg.py
plugins/modules/logstash_plugin.py
plugins/modules/lvg.py
plugins/modules/lvg_rename.py
plugins/modules/lvol.py
plugins/modules/lxc_container.py
plugins/modules/lxca_cmms.py
plugins/modules/lxca_nodes.py
plugins/modules/lxd_container.py
plugins/modules/lxd_profile.py
plugins/modules/lxd_project.py
=> l*.py: normalize docs

plugins/modules/macports.py, plugins/modules/mail.py, plugins/modules/make.py, plugins/modules/manageiq_alert_profiles.py, plugins/modules/manageiq_alerts.py, plugins/modules/manageiq_group.py, plugins/modules/manageiq_policies.py, plugins/modules/manageiq_policies_info.py, plugins/modules/manageiq_provider.py, plugins/modules/manageiq_tags.py, plugins/modules/manageiq_tags_info.py, plugins/modules/manageiq_tenant.py, plugins/modules/manageiq_user.py, plugins/modules/mas.py, plugins/modules/matrix.py, plugins/modules/mattermost.py, plugins/modules/maven_artifact.py
plugins/modules/macports.py
plugins/modules/mail.py
plugins/modules/make.py
plugins/modules/manageiq_alert_profiles.py
plugins/modules/manageiq_alerts.py
plugins/modules/manageiq_group.py
plugins/modules/manageiq_policies.py
plugins/modules/manageiq_policies_info.py
plugins/modules/manageiq_provider.py
plugins/modules/manageiq_tags.py
plugins/modules/manageiq_tags_info.py
plugins/modules/manageiq_tenant.py
plugins/modules/manageiq_user.py
plugins/modules/mas.py
plugins/modules/matrix.py
plugins/modules/mattermost.py
plugins/modules/maven_artifact.py
=> ma*.py: normalize docs

plugins/modules/memset_dns_reload.py, plugins/modules/memset_memstore_info.py, plugins/modules/memset_server_info.py, plugins/modules/memset_zone.py, plugins/modules/memset_zone_domain.py, plugins/modules/memset_zone_record.py, plugins/modules/mksysb.py, plugins/modules/modprobe.py, plugins/modules/monit.py, plugins/modules/mqtt.py, plugins/modules/mssql_db.py, plugins/modules/mssql_script.py, plugins/modules/nagios.py, plugins/modules/netcup_dns.py, plugins/modules/newrelic_deployment.py, plugins/modules/nexmo.py, plugins/modules/nginx_status_info.py, plugins/modules/nictagadm.py, plugins/modules/nmcli.py, plugins/modules/nomad_job.py, plugins/modules/nomad_job_info.py, plugins/modules/nomad_token.py, plugins/modules/nosh.py, plugins/modules/npm.py, plugins/modules/nsupdate.py
plugins/modules/memset_dns_reload.py
plugins/modules/memset_memstore_info.py
plugins/modules/memset_server_info.py
plugins/modules/memset_zone.py
plugins/modules/memset_zone_domain.py
plugins/modules/memset_zone_record.py
plugins/modules/mksysb.py
plugins/modules/modprobe.py
plugins/modules/monit.py
plugins/modules/mqtt.py
plugins/modules/mssql_db.py
plugins/modules/mssql_script.py
plugins/modules/nagios.py
plugins/modules/netcup_dns.py
plugins/modules/newrelic_deployment.py
plugins/modules/nexmo.py
plugins/modules/nginx_status_info.py
plugins/modules/nictagadm.py
plugins/modules/nomad_job.py
plugins/modules/nomad_job_info.py
plugins/modules/nomad_token.py
plugins/modules/nosh.py
plugins/modules/npm.py …
=> [mem ... n]*.py: normalize docs

changelogs/fragments/9363-dig-nonameservers.yml, plugins/lookup/dig.py
=> dig: handle NoNameservers exception

changelogs/fragments/9363-dig-nonameservers.yml, plugins/lookup/dig.py
Backport of #9363 to stable-9.
dig lookup
=> [stable-9] dig: handle NoNameservers exception (#9363)

plugins/modules/ibm_sa_domain.py, plugins/modules/ibm_sa_host.py, plugins/modules/ibm_sa_host_ports.py, plugins/modules/ibm_sa_pool.py, plugins/modules/ibm_sa_vol.py, plugins/modules/ibm_sa_vol_map.py, plugins/modules/icinga2_feature.py, plugins/modules/icinga2_host.py, plugins/modules/idrac_redfish_command.py, plugins/modules/idrac_redfish_config.py, plugins/modules/idrac_redfish_info.py, plugins/modules/ilo_redfish_command.py, plugins/modules/ilo_redfish_config.py, plugins/modules/ilo_redfish_info.py, plugins/modules/imc_rest.py, plugins/modules/imgadm.py, plugins/modules/infinity.py, plugins/modules/influxdb_database.py, plugins/modules/influxdb_query.py, plugins/modules/influxdb_retention_policy.py, plugins/modules/influxdb_user.py, plugins/modules/influxdb_write.py, plugins/modules/ini_file.py, plugins/modules/installp.py, plugins/modules/interfaces_file.py
plugins/modules/ibm_sa_domain.py
plugins/modules/ibm_sa_host.py
plugins/modules/ibm_sa_host_ports.py
plugins/modules/ibm_sa_pool.py
plugins/modules/ibm_sa_vol.py
plugins/modules/ibm_sa_vol_map.py
plugins/modules/icinga2_feature.py
plugins/modules/icinga2_host.py
plugins/modules/idrac_redfish_command.py
plugins/modules/idrac_redfish_config.py
plugins/modules/idrac_redfish_info.py
plugins/modules/ilo_redfish_command.py
plugins/modules/ilo_redfish_config.py
plugins/modules/ilo_redfish_info.py
plugins/modules/imc_rest.py
plugins/modules/imgadm.py
plugins/modules/infinity.py
plugins/modules/influxdb_database.py
plugins/modules/influxdb_query.py
plugins/modules/influxdb_retention_policy.py
plugins/modules/influxdb_user.py …
=> i[b-n]*.py: normalize docs

plugins/modules/datadog_downtime.py, plugins/modules/datadog_event.py, plugins/modules/datadog_monitor.py, plugins/modules/dconf.py, plugins/modules/decompress.py, plugins/modules/deploy_helper.py, plugins/modules/dimensiondata_network.py, plugins/modules/dimensiondata_vlan.py, plugins/modules/discord.py, plugins/modules/django_check.py, plugins/modules/django_command.py, plugins/modules/django_createcachetable.py, plugins/modules/django_manage.py, plugins/modules/dnf_config_manager.py, plugins/modules/dnf_versionlock.py, plugins/modules/dnsimple.py, plugins/modules/dnsimple_info.py, plugins/modules/dnsmadeeasy.py, plugins/modules/dpkg_divert.py, plugins/modules/easy_install.py, plugins/modules/ejabberd_user.py, plugins/modules/elasticsearch_plugin.py, plugins/modules/emc_vnx_sg_member.py, plugins/modules/etcd3.py, plugins/modules/facter.py, plugins/modules/facter_facts.py, plugins/modules/filesize.py, plugins/modules/filesystem.py, plugins/modules/flatpak.py, plugins/modules/flatpak_remote.py
plugins/modules/datadog_downtime.py
plugins/modules/datadog_event.py
plugins/modules/datadog_monitor.py
plugins/modules/dconf.py
plugins/modules/decompress.py
plugins/modules/deploy_helper.py
plugins/modules/dimensiondata_network.py
plugins/modules/dimensiondata_vlan.py
plugins/modules/discord.py
plugins/modules/django_check.py
plugins/modules/django_command.py
plugins/modules/django_createcachetable.py
plugins/modules/django_manage.py
plugins/modules/dnf_config_manager.py
plugins/modules/dnf_versionlock.py
plugins/modules/dnsimple.py
plugins/modules/dnsimple_info.py
plugins/modules/dnsmadeeasy.py
plugins/modules/dpkg_divert.py
plugins/modules/easy_install.py
plugins/modules/ejabberd_user.py
plugins/modules/elasticsearch_plugin.py …
=> [def]*.py: normalize docs

plugins/modules/haproxy.py, plugins/modules/heroku_collaborator.py, plugins/modules/hg.py, plugins/modules/hipchat.py, plugins/modules/homebrew.py, plugins/modules/homebrew_cask.py, plugins/modules/homebrew_services.py, plugins/modules/homebrew_tap.py, plugins/modules/homectl.py, plugins/modules/honeybadger_deployment.py, plugins/modules/hpilo_boot.py, plugins/modules/hpilo_info.py, plugins/modules/hponcfg.py, plugins/modules/htpasswd.py, plugins/modules/hwc_ecs_instance.py, plugins/modules/hwc_evs_disk.py, plugins/modules/hwc_network_vpc.py, plugins/modules/hwc_smn_topic.py, plugins/modules/hwc_vpc_eip.py, plugins/modules/hwc_vpc_peering_connect.py, plugins/modules/hwc_vpc_port.py, plugins/modules/hwc_vpc_private_ip.py, plugins/modules/hwc_vpc_route.py, plugins/modules/hwc_vpc_security_group.py, plugins/modules/hwc_vpc_security_group_rule.py, plugins/modules/hwc_vpc_subnet.py
plugins/modules/haproxy.py
plugins/modules/heroku_collaborator.py
plugins/modules/hg.py
plugins/modules/hipchat.py
plugins/modules/homebrew.py
plugins/modules/homebrew_cask.py
plugins/modules/homebrew_services.py
plugins/modules/homebrew_tap.py
plugins/modules/homectl.py
plugins/modules/honeybadger_deployment.py
plugins/modules/hpilo_boot.py
plugins/modules/hpilo_info.py
plugins/modules/hponcfg.py
plugins/modules/htpasswd.py
plugins/modules/hwc_ecs_instance.py
plugins/modules/hwc_evs_disk.py
plugins/modules/hwc_network_vpc.py
plugins/modules/hwc_smn_topic.py
plugins/modules/hwc_vpc_eip.py
plugins/modules/hwc_vpc_peering_connect.py
plugins/modules/hwc_vpc_port.py
plugins/modules/hwc_vpc_private_ip.py
plugins/modules/hwc_vpc_route.py …
=> h*.py: normalize docs

plugins/doc_fragments/manageiq.py, plugins/doc_fragments/nomad.py, plugins/doc_fragments/onepassword.py, plugins/doc_fragments/oneview.py, plugins/doc_fragments/online.py, plugins/doc_fragments/opennebula.py, plugins/doc_fragments/openswitch.py, plugins/doc_fragments/oracle.py, plugins/doc_fragments/oracle_creatable_resource.py, plugins/doc_fragments/oracle_display_name_option.py, plugins/doc_fragments/oracle_name_option.py, plugins/doc_fragments/oracle_tags.py, plugins/doc_fragments/oracle_wait_options.py, plugins/doc_fragments/pipx.py, plugins/doc_fragments/pritunl.py, plugins/doc_fragments/proxmox.py, plugins/doc_fragments/purestorage.py, plugins/doc_fragments/redis.py, plugins/doc_fragments/rundeck.py, plugins/doc_fragments/scaleway.py, plugins/doc_fragments/scaleway_waitable_resource.py, plugins/doc_fragments/utm.py, plugins/doc_fragments/vexata.py, plugins/doc_fragments/xenserver.py
Normalize doc blocks in `doc_fragments`.
plugins/doc_fragments/manageiq.py
plugins/doc_fragments/nomad.py
plugins/doc_fragments/onepassword.py
plugins/doc_fragments/oneview.py
plugins/doc_fragments/online.py
plugins/doc_fragments/opennebula.py
plugins/doc_fragments/openswitch.py
plugins/doc_fragments/oracle.py
plugins/doc_fragments/oracle_creatable_resource.py
plugins/doc_fragments/oracle_display_name_option.py
plugins/doc_fragments/oracle_name_option.py
plugins/doc_fragments/oracle_tags.py
plugins/doc_fragments/oracle_wait_options.py
plugins/doc_fragments/pipx.py
plugins/doc_fragments/pritunl.py
plugins/doc_fragments/proxmox.py
plugins/doc_fragments/purestorage.py
plugins/doc_fragments/redis.py
plugins/doc_fragments/rundeck.py
plugins/doc_fragments/scaleway.py …
=> [m-z]*.py: normalize doc_fragments

plugins/modules/rpm_ostree_pkg.py
Fixing the module name for one example in rpm_ostree_pkg
rpm_ostree_pkg
N/A
=> chore(docs): rpm_ostree_pkg fix examples

plugins/modules/sensu_check.py, plugins/modules/sensu_client.py, plugins/modules/sensu_handler.py, plugins/modules/sensu_silence.py, plugins/modules/sensu_subscription.py, plugins/modules/slack.py, plugins/modules/spotinst_aws_elastigroup.py, plugins/modules/stacki_host.py, plugins/modules/sudoers.py, plugins/modules/supervisorctl.py, plugins/modules/svr4pkg.py, plugins/modules/swupd.py, plugins/modules/telegram.py, plugins/modules/terraform.py, plugins/modules/twilio.py, plugins/modules/udm_dns_record.py, plugins/modules/udm_dns_zone.py, plugins/modules/utm_dns_host.py, plugins/modules/vdo.py, plugins/modules/vertica_user.py, plugins/modules/vmadm.py, plugins/modules/wakeonlan.py, plugins/modules/xcc_redfish_command.py, plugins/modules/xenserver_guest.py
Adjust doc style, largely based on https://docs.ansible.com/ansible/latest/dev_guide/style_guide/index.html
plugins/modules/sensu_check.py
plugins/modules/sensu_client.py
plugins/modules/sensu_handler.py
plugins/modules/sensu_silence.py
plugins/modules/sensu_subscription.py
plugins/modules/slack.py
plugins/modules/spotinst_aws_elastigroup.py
plugins/modules/stacki_host.py
plugins/modules/sudoers.py
plugins/modules/supervisorctl.py
plugins/modules/svr4pkg.py
plugins/modules/swupd.py
plugins/modules/telegram.py
plugins/modules/terraform.py
plugins/modules/twilio.py
plugins/modules/udm_dns_record.py
plugins/modules/udm_dns_zone.py
plugins/modules/utm_dns_host.py
plugins/modules/vdo.py
plugins/modules/vertica_user.py
plugins/modules/vmadm.py
plugins/modules/wakeonlan.py …
=> Adjust doc style

changelogs/fragments/9451-facter-deprecation.yml, meta/runtime.yml, plugins/modules/facter.py
Per https://github.com/ansible-collections/community.general/pull/7356#issuecomment-1752460442 it has been agreed that this module would be replaced with the better named `facter_facts`.
facter
=> facter: deprecation

plugins/modules/dnsmadeeasy.py
Minor adjustments in the docs.
dnsmadeeasy
=> dnsmadeeasy: doc-adjustments

plugins/cache/memcached.py, plugins/cache/pickle.py, plugins/cache/redis.py, plugins/cache/yaml.py, plugins/connection/chroot.py, plugins/connection/funcd.py, plugins/connection/incus.py, plugins/connection/iocage.py, plugins/connection/jail.py, plugins/connection/lxc.py, plugins/connection/lxd.py, plugins/connection/qubes.py, plugins/connection/saltstack.py, plugins/connection/zone.py
Normalize doc blocks for plugins
plugins/cache/memcached.py
plugins/cache/pickle.py
plugins/cache/redis.py
plugins/cache/yaml.py
plugins/connection/funcd.py
plugins/connection/incus.py
plugins/connection/iocage.py
plugins/connection/jail.py
plugins/connection/lxd.py
plugins/connection/qubes.py
plugins/connection/saltstack.py
plugins/connection/zone.py
=> normalize docs in cache/connection plugins

plugins/modules/clc_publicip.py, plugins/modules/clc_server.py, plugins/modules/cloudflare_dns.py, plugins/modules/etcd3.py, plugins/modules/gitlab_hook.py, plugins/modules/homectl.py, plugins/modules/infinity.py, plugins/modules/ipinfoio_facts.py, plugins/modules/ipmi_boot.py, plugins/modules/ipmi_power.py, plugins/modules/jenkins_plugin.py, plugins/modules/librato_annotation.py, plugins/modules/lxc_container.py, plugins/modules/mattermost.py, plugins/modules/oneandone_public_ip.py, plugins/modules/ovh_ip_loadbalancing_backend.py, plugins/modules/packet_project.py, plugins/modules/proxmox_kvm.py, plugins/modules/riak.py, plugins/modules/scaleway_ip_info.py, plugins/modules/sendgrid.py
Adjust doc style, largely based on https://docs.ansible.com/ansible/latest/dev_guide/style_guide/index.html
plugins/modules/clc_publicip.py
plugins/modules/clc_server.py
plugins/modules/cloudflare_dns.py
plugins/modules/etcd3.py
plugins/modules/gitlab_hook.py
plugins/modules/homectl.py
plugins/modules/infinity.py
plugins/modules/ipinfoio_facts.py
plugins/modules/ipmi_boot.py
plugins/modules/ipmi_power.py
plugins/modules/jenkins_plugin.py
plugins/modules/librato_annotation.py
plugins/modules/lxc_container.py
plugins/modules/mattermost.py
plugins/modules/oneandone_public_ip.py
plugins/modules/ovh_ip_loadbalancing_backend.py
plugins/modules/packet_project.py
plugins/modules/proxmox_kvm.py
plugins/modules/riak.py
plugins/modules/scaleway_ip_info.py …
=> adjust doc style - batch 2

plugins/become/doas.py, plugins/become/dzdo.py, plugins/become/ksu.py, plugins/become/machinectl.py, plugins/become/pbrun.py, plugins/become/pfexec.py, plugins/become/pmrun.py, plugins/become/run0.py, plugins/become/sesu.py, plugins/become/sudosu.py
Normalize doc blocks for plugins
plugins/become/doas.py
plugins/become/dzdo.py
plugins/become/ksu.py
plugins/become/machinectl.py
plugins/become/pbrun.py
plugins/become/pfexec.py
plugins/become/pmrun.py
plugins/become/run0.py
plugins/become/sesu.py
plugins/become/sudosu.py
=> normalize docs in become plugins

plugins/callback/cgroup_memory_recap.py, plugins/callback/context_demo.py, plugins/callback/counter_enabled.py, plugins/callback/default_without_diff.py, plugins/callback/dense.py, plugins/callback/diy.py, plugins/callback/elastic.py, plugins/callback/jabber.py, plugins/callback/log_plays.py, plugins/callback/loganalytics.py, plugins/callback/logdna.py, plugins/callback/logentries.py, plugins/callback/logstash.py, plugins/callback/mail.py, plugins/callback/nrdp.py, plugins/callback/null.py, plugins/callback/opentelemetry.py, plugins/callback/say.py, plugins/callback/selective.py, plugins/callback/slack.py, plugins/callback/splunk.py, plugins/callback/sumologic.py, plugins/callback/syslog_json.py, plugins/callback/timestamp.py, plugins/callback/unixy.py, plugins/callback/yaml.py
Normalize doc blocks for plugins
plugins/callback/cgroup_memory_recap.py
plugins/callback/context_demo.py
plugins/callback/counter_enabled.py
plugins/callback/default_without_diff.py
plugins/callback/dense.py
plugins/callback/diy.py
plugins/callback/elastic.py
plugins/callback/jabber.py
plugins/callback/log_plays.py
plugins/callback/logdna.py
plugins/callback/logentries.py
plugins/callback/logstash.py
plugins/callback/mail.py
plugins/callback/nrdp.py
plugins/callback/null.py
plugins/callback/say.py
plugins/callback/slack.py
plugins/callback/splunk.py
plugins/callback/sumologic.py
plugins/callback/syslog_json.py
plugins/callback/timestamp.py
plugins/callback/unixy.py …
=> normalize docs in callback plugins

plugins/modules/svc.py
Small improvements to the docs, mostly adding markup.
Fixes #9365 
svc
=> svc: adjustments to docs

changelogs/fragments/9482-opentelemetry-python-37.yml, plugins/callback/opentelemetry.py
=> opentelemetry callback plugin: remove code for Python < 3.7

plugins/doc_fragments/ldap.py, plugins/modules/ldap_attrs.py, plugins/modules/ldap_entry.py, plugins/modules/ldap_inc.py, plugins/modules/ldap_passwd.py, plugins/modules/ldap_search.py
This PR to propose to optimize ldap_xxx modules documentation for authentication in document fragment. 
No issue
ldap_attrs
ldap_entry
ldap_inc
ldap_passwd
ldap_search
=> Optimize ldap modules auth note in a doc fragment

changelogs/fragments/9490-htpasswd-permissions.yml, plugins/modules/htpasswd.py, tests/integration/targets/htpasswd/tasks/main.yml
=> htpasswd: let changed reflect updated permissions

.github/BOTMETA.yml, plugins/doc_fragments/clc.py, plugins/modules/clc_aa_policy.py, plugins/modules/clc_alert_policy.py, plugins/modules/clc_blueprint_package.py, plugins/modules/clc_firewall_policy.py, plugins/modules/clc_group.py, plugins/modules/clc_loadbalancer.py, plugins/modules/clc_modify_server.py, plugins/modules/clc_publicip.py, plugins/modules/clc_server.py, plugins/modules/clc_server_snapshot.py
Create doc fragment for `clc_*` modules.
plugins/doc_fragments/clc.py
plugins/modules/clc_aa_policy.py
plugins/modules/clc_alert_policy.py
plugins/modules/clc_blueprint_package.py
plugins/modules/clc_firewall_policy.py
plugins/modules/clc_group.py
plugins/modules/clc_loadbalancer.py
plugins/modules/clc_modify_server.py
plugins/modules/clc_publicip.py
plugins/modules/clc_server.py
plugins/modules/clc_server_snapshot.py
=> clc_*: create doc fragment

meta/runtime.yml
=> meta/runtime.yml: sort keys for modules

meta/runtime.yml
Two entreies were spotted still out of alphabetical order.
=> runtime/modules ordering: missed two modules before

plugins/modules/shutdown.py, plugins/modules/simpleinit_msb.py, plugins/modules/sl_vm.py, plugins/modules/slack.py, plugins/modules/smartos_image_info.py, plugins/modules/snap.py, plugins/modules/snmp_facts.py, plugins/modules/solaris_zone.py, plugins/modules/sorcery.py, plugins/modules/spectrum_device.py, plugins/modules/spectrum_model_attrs.py, plugins/modules/spotinst_aws_elastigroup.py, plugins/modules/ssh_config.py, plugins/modules/stacki_host.py, plugins/modules/statusio_maintenance.py, plugins/modules/supervisorctl.py, plugins/modules/svc.py, plugins/modules/svr4pkg.py, plugins/modules/swupd.py, plugins/modules/syslogger.py, plugins/modules/systemd_creds_decrypt.py, plugins/modules/systemd_creds_encrypt.py, plugins/modules/sysupgrade.py, plugins/modules/taiga_issue.py, plugins/modules/terraform.py, plugins/modules/timezone.py, plugins/modules/twilio.py, plugins/modules/typetalk.py
Second round of doc adjustments. Output width has been slightly reduced in andebox, and a couple of other style improvements have been added (like replacing id with ID)
plugins/modules/shutdown.py
plugins/modules/simpleinit_msb.py
plugins/modules/sl_vm.py
plugins/modules/slack.py
plugins/modules/smartos_image_info.py
plugins/modules/snap.py
plugins/modules/snmp_facts.py
plugins/modules/solaris_zone.py
plugins/modules/sorcery.py
plugins/modules/spectrum_device.py
plugins/modules/spectrum_model_attrs.py
plugins/modules/spotinst_aws_elastigroup.py
plugins/modules/ssh_config.py
plugins/modules/stacki_host.py
plugins/modules/statusio_maintenance.py
plugins/modules/supervisorctl.py
plugins/modules/svc.py
plugins/modules/svr4pkg.py
plugins/modules/swupd.py …
=> st*: style adjustments

plugins/modules/scaleway_container.py, plugins/modules/scaleway_container_info.py, plugins/modules/scaleway_function.py, plugins/modules/scaleway_ip.py, plugins/modules/scaleway_ip_info.py, plugins/modules/scaleway_lb.py, plugins/modules/sefcontext.py, plugins/modules/sendgrid.py, plugins/modules/sensu_check.py, plugins/modules/sensu_client.py, plugins/modules/sensu_handler.py, plugins/modules/sensu_silence.py, plugins/modules/sensu_subscription.py
Second round of doc adjustments. Output width has been slightly reduced in andebox, and a couple of other style improvements have been added (like replacing id with ID)
plugins/modules/scaleway_container.py
plugins/modules/scaleway_container_info.py
plugins/modules/scaleway_function.py
plugins/modules/scaleway_ip.py
plugins/modules/scaleway_ip_info.py
plugins/modules/scaleway_lb.py
plugins/modules/sefcontext.py
plugins/modules/sendgrid.py
plugins/modules/sensu_check.py
plugins/modules/sensu_client.py
plugins/modules/sensu_handler.py
plugins/modules/sensu_silence.py
plugins/modules/sensu_subscription.py
=> s*: style adjustments

plugins/modules/xattr.py, plugins/modules/xbps.py, plugins/modules/xcc_redfish_command.py, plugins/modules/xenserver_guest.py, plugins/modules/xenserver_guest_info.py, plugins/modules/xenserver_guest_powerstate.py, plugins/modules/xfconf.py, plugins/modules/xfconf_info.py, plugins/modules/xml.py, plugins/modules/yarn.py, plugins/modules/yum_versionlock.py, plugins/modules/zfs.py, plugins/modules/zfs_delegate_admin.py, plugins/modules/zfs_facts.py, plugins/modules/znode.py, plugins/modules/zpool_facts.py, plugins/modules/zypper.py, plugins/modules/zypper_repository.py, plugins/modules/zypper_repository_info.py
Second round of doc adjustments. Output width has been slightly reduced in andebox, and a couple of other style improvements have been added (like replacing id with ID)
plugins/modules/xattr.py
plugins/modules/xbps.py
plugins/modules/xcc_redfish_command.py
plugins/modules/xenserver_guest.py
plugins/modules/xenserver_guest_info.py
plugins/modules/xenserver_guest_powerstate.py
plugins/modules/xfconf.py
plugins/modules/xfconf_info.py
plugins/modules/xml.py
plugins/modules/yarn.py
plugins/modules/yum_versionlock.py
plugins/modules/zfs.py
plugins/modules/zfs_delegate_admin.py
plugins/modules/zfs_facts.py
plugins/modules/znode.py
plugins/modules/zpool_facts.py
plugins/modules/zypper.py
plugins/modules/zypper_repository.py
plugins/modules/zypper_repository_info.py
=> xyz*: style adjustments

.github/BOTMETA.yml
Stop sending me notifications about the big panda module as I no longer work there
Botmeta
```paste below
```
=> Add hkariti to notifications ignore list

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/django_command/aliases, tests/integration/targets/django_manage/aliases, tests/integration/targets/dnf_versionlock/tasks/main.yml, tests/integration/targets/filter_jc/aliases, tests/integration/targets/gem/tasks/main.yml, tests/integration/targets/gem/vars/Ubuntu.yml, tests/integration/targets/homectl/aliases, tests/integration/targets/iso_extract/aliases, tests/integration/targets/odbc/aliases, tests/integration/targets/pkgng/tasks/freebsd.yml, tests/integration/targets/setup_redis_replication/defaults/main.yml, tests/integration/targets/setup_redis_replication/tasks/setup_redis_cluster.yml, tests/integration/targets/setup_snap/tasks/D-RedHat-9.5.yml, tests/integration/targets/ufw/aliases, tests/integration/targets/yum_versionlock/tasks/main.yml
Ref: https://github.com/ansible/ansible/pull/84281
Ref: https://github.com/ansible/ansible/pull/84525
Ref: https://github.com/ansible/ansible/pull/84526
Ref: https://github.com/ansible/ansible/pull/84527
CI
=> CI: Add Fedora 41, Alpine 3.21, RHEL 9.5, FreeBSD 14.2 to CI for devel

changelogs/fragments/9598-snap-version.yml, plugins/module_utils/snap.py, plugins/modules/snap.py, plugins/modules/snap_alias.py, tests/unit/plugins/modules/test_snap.py
Add RV `version` to the modules `snap` and `snap_alias`
snap
snap_alias
=> snap: add RV version

changelogs/fragments/9599-apache2-mod-proxy-revamp1.yml, plugins/modules/apache2_mod_proxy.py
Create method for common code.
=> apache2-mod-proxy: refactor BalancerMember serialization

plugins/modules/apache2_mod_proxy.py
Reformatted the YAML blocks using `andebox`.
=> apache2-mod-proxy: reformatted YAML blocks

changelogs/fragments/9612-apache2-mod-proxy-revamp5.yml, plugins/modules/apache2_mod_proxy.py
Use `deps` to manage dependencies.
=> apache2-mod-proxy: use deps to handle dependencies

changelogs/fragments/9614-apache2-mod-proxy-revamp7.yml, plugins/modules/apache2_mod_proxy.py
Remove a number of redundant calls to `str()`, improved some string manipulations using `format()`.
=> apache2-mod-proxy: simplified/improved string manipulation

tests/unit/plugins/modules/test_cpanm.yaml, tests/unit/plugins/modules/test_django_check.yaml, tests/unit/plugins/modules/test_django_command.yaml, tests/unit/plugins/modules/test_django_createcachetable.yaml, tests/unit/plugins/modules/test_facter_facts.yaml, tests/unit/plugins/modules/test_gconftool2.yaml, tests/unit/plugins/modules/test_gconftool2_info.yaml, tests/unit/plugins/modules/test_gio_mime.yaml, tests/unit/plugins/modules/test_krb_ticket.yaml, tests/unit/plugins/modules/test_opkg.yaml, tests/unit/plugins/modules/test_puppet.yaml, tests/unit/plugins/modules/test_xfconf.yaml, tests/unit/plugins/modules/test_xfconf_info.yaml
Reformat YAML used by unit tests based in test helper.
tests/unit/plugins/modules/test_cpanm.yaml
tests/unit/plugins/modules/test_django_check.yaml
tests/unit/plugins/modules/test_django_command.yaml
tests/unit/plugins/modules/test_django_createcachetable.yaml
tests/unit/plugins/modules/test_facter_facts.yaml
tests/unit/plugins/modules/test_gconftool2.yaml
tests/unit/plugins/modules/test_gconftool2_info.yaml
tests/unit/plugins/modules/test_gio_mime.yaml
tests/unit/plugins/modules/test_krb_ticket.yaml
tests/unit/plugins/modules/test_opkg.yaml
tests/unit/plugins/modules/test_puppet.yaml
tests/unit/plugins/modules/test_xfconf.yaml
tests/unit/plugins/modules/test_xfconf_info.yaml
=> test helper unit tests: reformat YAML files

tests/integration/targets/snap_alias/aliases
Follow-up to #9679.
Ref: #9656.
snap_alias
=> Also disable snap_alias tests for RHEL 8.8

changelogs/fragments/9695-xml-close-file.yml, plugins/modules/xml.py
Ensure the file is closed with a `try/finally` block.
xml
=> xml: ensure the stream object is closed in main()

.azure-pipelines/azure-pipelines.yml, .azure-pipelines/templates/coverage.yml
Ref: https://github.com/ansible/ansible/commit/a926b1dbab536655ce1807aadffa26750170b86f
AZP CI
=> CI: Cleanup AZP config similarly to ansible-core did some years ago

changelogs/fragments/9733-profitbrick-deprecation.yml, meta/runtime.yml, plugins/modules/profitbricks.py, plugins/modules/profitbricks_datacenter.py, plugins/modules/profitbricks_nic.py, plugins/modules/profitbricks_volume.py, plugins/modules/profitbricks_volume_attachments.py
Deprecate modules `profitbricks*`
plugins/modules/profitbricks.py
plugins/modules/profitbricks_datacenter.py
plugins/modules/profitbricks_nic.py
plugins/modules/profitbricks_volume.py
plugins/modules/profitbricks_volume_attachments.py
=> profitbricks: deprecation

tests/sanity/ignore-2.17.txt, tests/sanity/ignore-2.18.txt, tests/sanity/ignore-2.19.txt, tests/unit/plugins/modules/test_cpanm.py, tests/unit/plugins/modules/test_django_check.py, tests/unit/plugins/modules/test_django_command.py, tests/unit/plugins/modules/test_django_createcachetable.py, tests/unit/plugins/modules/test_facter_facts.py, tests/unit/plugins/modules/test_gconftool2.py, tests/unit/plugins/modules/test_gconftool2_info.py, tests/unit/plugins/modules/test_gio_mime.py, tests/unit/plugins/modules/test_krb_ticket.py, tests/unit/plugins/modules/test_opkg.py, tests/unit/plugins/modules/test_puppet.py, tests/unit/plugins/modules/test_snap.py, tests/unit/plugins/modules/test_xfconf.py, tests/unit/plugins/modules/test_xfconf_info.py, tests/unit/plugins/modules/uthelper.py
Rename test helper file and class to `uthelper.UTHelper`.
tests/unit/plugins/modules/test_django_check.py
tests/unit/plugins/modules/test_django_command.py
tests/unit/plugins/modules/test_django_createcachetable.py
tests/unit/plugins/modules/test_facter_facts.py
tests/unit/plugins/modules/test_gio_mime.py
tests/unit/plugins/modules/test_krb_ticket.py
tests/unit/plugins/modules/uthelper.py
=> rename test helper

.github/BOTMETA.yml, docs/docsite/extra-docs.yml, docs/docsite/rst/guide_test_helper.rst, docs/docsite/rst/guide_uthelper.rst
docs/docsite/extra-docs.yml
docs/docsite/rst/guide_uthelper.rst
=> Test helper guide

plugins/modules/profitbricks.py, plugins/modules/profitbricks_datacenter.py, plugins/modules/profitbricks_nic.py, plugins/modules/profitbricks_volume.py, plugins/modules/profitbricks_volume_attachments.py
Fix typo.
plugins/modules/profitbricks.py
plugins/modules/profitbricks_datacenter.py
plugins/modules/profitbricks_nic.py
plugins/modules/profitbricks_volume.py
plugins/modules/profitbricks_volume_attachments.py
=> profitbricks: fix typo in deprecation text

meta/runtime.yml, plugins/modules/clc_alert_policy.py, plugins/modules/clc_blueprint_package.py, plugins/modules/clc_firewall_policy.py, plugins/modules/clc_group.py, plugins/modules/clc_loadbalancer.py, plugins/modules/clc_modify_server.py, plugins/modules/clc_publicip.py, plugins/modules/clc_server.py, plugins/modules/clc_server_snapshot.py
The CenturyLink Cloud wen EOL in Sep 2023.
See more at: https://www.ctl.io/knowledge-base/release-notes/2023/lumen-public-cloud-platform-end-of-life-notice/?
plugins/modules/clc_alert_policy.py
plugins/modules/clc_blueprint_package.py
plugins/modules/clc_firewall_policy.py
plugins/modules/clc_group.py
plugins/modules/clc_loadbalancer.py
plugins/modules/clc_modify_server.py
plugins/modules/clc_publicip.py
plugins/modules/clc_server.py
plugins/modules/clc_server_snapshot.py
=> clc_*: deprecation

plugins/filter/to_days.yml, plugins/filter/to_hours.yml, plugins/filter/to_milliseconds.yml, plugins/filter/to_minutes.yml, plugins/filter/to_months.yml, plugins/filter/to_seconds.yml, plugins/filter/to_time_unit.yml, plugins/filter/to_weeks.yml, plugins/filter/to_years.yml
=> misc typo fix

changelogs/fragments/9777-homebrew-fix-crash-when-packages-include-tap.yml, plugins/modules/homebrew.py, tests/integration/targets/homebrew/tasks/casks.yml
Fixes #9777.
community.general.homebrew
Includes test that failed pre-commit and passes post-commit.
=> homebrew:  Do not crash when package names include tap prefix.

tests/integration/targets/callback/filter_plugins/helper.py, tests/integration/targets/callback/tasks/main.yml, tests/integration/targets/consul/tasks/consul_binding_rule.yml, tests/integration/targets/consul/tasks/consul_token.yml, tests/integration/targets/deploy_helper/tasks/main.yml, tests/integration/targets/filter_counter/tasks/main.yml, tests/integration/targets/filter_from_csv/tasks/main.yml, tests/integration/targets/filter_groupby_as_dict/tasks/main.yml, tests/integration/targets/filter_hashids/tasks/main.yml, tests/integration/targets/filter_keep_keys/tasks/tests.yml, tests/integration/targets/filter_lists_mergeby/tasks/lists_mergeby_2-10.yml, tests/integration/targets/filter_lists_mergeby/tasks/lists_mergeby_default.yml, tests/integration/targets/filter_random_mac/tasks/main.yml, tests/integration/targets/filter_remove_keys/tasks/tests.yml, tests/integration/targets/filter_replace_keys/tasks/tests.yml, tests/integration/targets/filter_reveal_ansible_type/tasks/tasks.yml, tests/integration/targets/ini_file/tasks/tests/01-value.yml, tests/integration/targets/iptables_state/tasks/tests/10-rollback.yml, tests/integration/targets/java_keystore/tasks/tests.yml, tests/integration/targets/kernel_blacklist/tasks/main.yml, tests/integration/targets/keycloak_realm_key/tasks/main.yml, tests/integration/targets/lookup_dependent/tasks/main.yml, tests/integration/targets/pkgng/tasks/freebsd.yml, tests/integration/targets/setup_cron/tasks/main.yml, tests/integration/targets/test_ansible_type/tasks/tasks.yml, tests/integration/targets/test_fqdn_valid/tasks/fqdn_valid_1.yml
Backport of #9859 to stable-9.
various integration tests
=> [stable-9] Fix/improve tests

changelogs/fragments/dnf_versionlock.yml, plugins/modules/dnf_versionlock.py, tests/integration/targets/dnf_versionlock/tasks/main.yml
=> dnf_versionlock: add support for Fedora 41 and dnf5

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/iso_extract/aliases, tests/integration/targets/pkgng/tasks/freebsd.yml
Ref: https://github.com/ansible/ansible/issues/84224
Ref: https://forum.ansible.com/t/ansible-test-devel-freebsd-13-4-replaced-by-13-5/40967
CI
=> CI: Add FreeBSD 13.5

changelogs/fragments/sudoers.yml, plugins/modules/sudoers.py, tests/integration/targets/sudoers/tasks/main.yml
* Print stdout and stderr raised from sudoers validation
Fixes: #9674
=> sudoers: display stderr raised while validation

plugins/modules/yarn.py
=> The yarn module is Yarn Classic only at the moment

tests/integration/targets/copr/aliases
=> tests: enable copr tests

plugins/modules/yarn.py
Backport of #9926 to stable-9.
yarn
=> [stable-9] The yarn module is Yarn Classic only at the moment

changelogs/fragments/9963-proxmox_disk-storage.yml, plugins/modules/proxmox_disk.py
=> proxmox_disk: fail gracefully if storage hasn't been provided by the user

changelogs/fragments/9992-filtertypeerror.yml, plugins/filter/hashids.py, plugins/filter/unicode_normalize.py
Ref: https://forum.ansible.com/t/41654
two filter plugins
=> Avoid deprecated AnsibleFilterTypeError

changelogs/fragments/9833-data-tagging.yml, plugins/callback/diy.py, plugins/callback/yaml.py, plugins/filter/reveal_ansible_type.py, plugins/lookup/dependent.py, plugins/plugin_utils/ansible_type.py, plugins/test/ansible_type.py, tests/integration/targets/callback_log_plays/runme.sh, tests/integration/targets/cmd_runner/action_plugins/_unsafe_assert.py, tests/integration/targets/filter_reveal_ansible_type/tasks/tasks.yml, tests/integration/targets/module_helper/tasks/mdepfail.yml, tests/integration/targets/module_helper/tasks/msimpleda.yml, tests/integration/targets/test_ansible_type/tasks/tasks.yml
Manual backport of #9833 to stable-9.
various
=> [stable-9] Make ready for data tagging

changelogs/fragments/9972-zypper-skip-post-errors.yml, plugins/modules/zypper.py, tests/integration/targets/zypper/files/post_error.spec, tests/integration/targets/zypper/files/post_error.spec.license, tests/integration/targets/zypper/tasks/zypper.yml
- Add feature to handle zypper return code 107 with skip_post_errors (default: false).
- Add integration test to verify the skip_post_errors flag.
Issue: #9972
Issue-Ref: https://github.com/ansible-collections/community.general/issues/9972
```paste below
```
=> Add zypper skip post errors feature

changelogs/fragments/10014-puppet-improve-param.yml, plugins/module_utils/puppet.py
Better handling of the boolean parameter.
puppet
=> puppet: use better CmdRunner param formatting

plugins/modules/btrfs_subvolume.py, plugins/modules/htpasswd.py, plugins/modules/irc.py, plugins/modules/lxd_container.py, plugins/modules/nmcli.py
The test results in #10022 exposed (to me at least) some warnings coming out from the extra tests in the collection.
plugins/modules/btrfs_subvolume.py
plugins/modules/htpasswd.py
plugins/modules/irc.py
plugins/modules/lxd_container.py
=> fixed hidden warnings from extra tests - batch 3

plugins/modules/crypttab.py
Backport of #10079 to stable-9.
crypttab
=> [stable-9] crypttab: removes jijna delimiters from example using when (#10079)

plugins/modules/nmcli.py
Ref: https://github.com/ansible-collections/community.general/issues/9789#issuecomment-2824441950
nmcli
=> nmcli: fix misspelled option in example

plugins/modules/nmcli.py
Backport of #10075 to stable-9.
nmcli
=> [stable-9] nmcli: fix misspelled option in example (#10075)

changelogs/fragments/10075-keycloak_user_rolemapping-diff.yml, plugins/modules/keycloak_user_rolemapping.py
Fixes #10067.
keycloak_user_rolemapping
=> keycloak_user_rolemapping: fix diff mode

plugins/modules/pipx_info.py, tests/integration/targets/pipx_info/tasks/main.yml
Fix the failing scheduled tests.
pipx
pipx_info
=> pipx/pipx_info: fix scheduled tests

changelogs/fragments/10121-sysrc-fix-split-first-separator.yml, plugins/modules/sysrc.py
Fixes #10120
community.general.sysrc
Split on the first separator only.
=> Fix #10120. Split key=value where value may comprise =

changelogs/fragments/10136-cache-pickle-json.yml, plugins/cache/pickle.py
Avoid extra json serialization in pickle cache plugin in 2.19
change is backwards compatible as earlier versions ignore the property
plugins/cache/pickle
=> pickle cache plugin, avoid extra steps in DT

changelogs/fragments/10128-mark-end-of-options.yml, plugins/modules/kdeconfig.py
Closes #10127
kdeconfig
```paste below
```
=> kdeconfig: mark end of options before sending value

changelogs/fragments/proxmox-deprecation.yml
Ref: https://github.com/ansible-collections/community.proxmox/issues/10
This should only be merged once community.proxmox 1.0.0 is out (or almost out).
changelog
=> [stable-10] Announce deprecation of proxmox content

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/android_sdk/tasks/setup.yml, tests/integration/targets/android_sdk/vars/RedHat-10.yml, tests/integration/targets/copr/aliases, tests/integration/targets/django_command/aliases, tests/integration/targets/django_manage/aliases, tests/integration/targets/homectl/aliases, tests/integration/targets/iptables_state/aliases, tests/integration/targets/iso_extract/aliases, tests/integration/targets/setup_openssl/vars/RedHat-10.yml, tests/integration/targets/setup_snap/tasks/D-RedHat-10.yml, tests/integration/targets/ufw/aliases
Ref: https://github.com/ansible/ansible/pull/85189
Ref: https://forum.ansible.com/t/ansible-test-devel-rhel-10-0-added/42892
CI
=> Add RHEL 10.0 to CI

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/copr/aliases, tests/integration/targets/django_command/aliases, tests/integration/targets/django_manage/aliases, tests/integration/targets/homectl/aliases, tests/integration/targets/iptables_state/aliases, tests/integration/targets/iso_extract/aliases, tests/integration/targets/setup_openssl/vars/RedHat-10.yml, tests/integration/targets/setup_snap/tasks/D-RedHat-10.yml, tests/integration/targets/ufw/aliases
Backport of #10164 to stable-9.
CI
=> [stable-9] Add RHEL 10.0 to CI

plugins/modules/apache2_mod_proxy.py
=> apache2_mod_proxy: adjust docs

plugins/modules/apache2_mod_proxy.py
=> apache2_mod_proxy: adjust docs (fix)

changelogs/fragments/10137-pipx-cg11.yml, changelogs/fragments/deprecations.yml, plugins/doc_fragments/pipx.py, plugins/modules/pipx.py, plugins/modules/pipx_info.py, tests/integration/targets/pipx/tasks/main.yml, tests/integration/targets/pipx_info/tasks/main.yml
`pipx`/`pipx_info` changes for community.general 11.0.0.
pipx
pipx_info
=> Prepare for version 11: pipx/pipx_info

changelogs/fragments/10212-yaml.yml, plugins/callback/yaml.py
The YAML callback was broken by the latest changes in ansible-core devel:
- https://github.com/ansible/ansible/commit/1c06c46cc14324df35ac4f39a45fb3ccd602195d
- https://github.com/ansible/ansible/commit/2b7204527b0906172e5ba719f1a0fb64070c7b5e
I updated the vendored code so that it should work both with stable-2.19 / the currently published ansible-core 2.19 betas and with the latest `devel` branch.
yaml callback
=> Fix YAML callback

.gitignore
Use the latest https://www.toptal.com/developers/gitignore/api/vim,git,macos,linux,pydev,emacs,dotenv,python,windows,webstorm,pycharm+all,jupyternotebooks version.
.gitignore
=> Update auto-generated .gitignore parts

changelogs/fragments/10242-yaml.yml, plugins/callback/yaml.py, tests/integration/targets/callback/tasks/main.yml, tests/integration/targets/callback_yaml/meta/main.yml, tests/integration/targets/callback_yaml/tasks/main.yml
Backport of #10242 to stable-9.
yaml callback
=> [stable-9] yaml callback: use new util introduced in ansible-core 2.19.0b2 (#10242)

changelogs/fragments/10267-add-cloudflare-ptr-record-support.yml, plugins/modules/cloudflare_dns.py
Adds PTR record support
cloudflare_dns
=> cloudflare_dns: Add PTR record support

plugins/modules/sl_vm.py
Add notes about Python requirements for the underlying package.
sl_vm
=> sl_vm: update docs about requirements

plugins/become/pfexec.py, plugins/callback/context_demo.py, plugins/callback/counter_enabled.py, plugins/callback/dense.py, plugins/callback/diy.py, plugins/callback/jabber.py, plugins/callback/log_plays.py, plugins/callback/null.py, plugins/callback/print_task.py, plugins/callback/say.py, plugins/callback/selective.py, plugins/callback/syslog_json.py, plugins/callback/unixy.py, plugins/connection/wsl.py, plugins/filter/to_prettytable.py, plugins/inventory/cobbler.py, plugins/inventory/gitlab_runners.py, plugins/inventory/icinga2.py, plugins/inventory/iocage.py, plugins/inventory/linode.py, plugins/inventory/nmap.py, plugins/inventory/online.py, plugins/inventory/opennebula.py, plugins/inventory/scaleway.py, plugins/inventory/virtualbox.py, plugins/inventory/xen_orchestra.py
plugins/become/pfexec.py
plugins/callback/context_demo.py
plugins/callback/counter_enabled.py
plugins/callback/dense.py
plugins/callback/diy.py
plugins/callback/jabber.py
plugins/callback/log_plays.py
plugins/callback/null.py
plugins/callback/print_task.py
plugins/callback/say.py
plugins/callback/syslog_json.py
plugins/callback/unixy.py
plugins/connection/wsl.py
plugins/filter/to_prettytable.py
plugins/inventory/gitlab_runners.py
plugins/inventory/icinga2.py
plugins/inventory/iocage.py
plugins/inventory/linode.py
plugins/inventory/nmap.py
plugins/inventory/online.py
plugins/inventory/opennebula.py
plugins/inventory/virtualbox.py
plugins/inventory/xen_orchestra.py
=> fix YAML docs in multiple plugins

changelogs/fragments/10269-cloudflare-dns-refactor.yml, plugins/modules/cloudflare_dns.py
The purpose of the removed validation `if` block is defeated by the `required_if` clause in line 949.
Either the `if` block was wrong and should be removed - in which case this is a refactoring PR, or the `required_if` was wrong, then the `if` block should be restored and the `required_if` clause should be removed, in which case this is a bug fix PR.
There are no tests for this module. 
cloudflare_dns
=> cloudflare_dns: some refactoring

changelogs/fragments/10311-xfconf-refactor.yml, plugins/modules/xfconf.py
Minor code improvements
xfconf
=> xfconf: small refactor

plugins/modules/htpasswd.py
Add note to the hash_scheme parameter.
Fixes #9267 
htpasswd
=> htpasswd: doc adjustment

.azure-pipelines/azure-pipelines.yml, tests/sanity/ignore-2.20.txt, tests/sanity/ignore-2.20.txt.license
devel was bumped to 2.20.0.dev0.
CI
=> CI: Add stable-2.19

tests/unit/plugins/inventory/test_linode.py, tests/unit/plugins/modules/test_github_repo.py, tests/unit/plugins/modules/test_linode_v4.py, tests/unit/plugins/modules/test_modprobe.py
tests/unit/plugins/inventory/test_linode.py
tests/unit/plugins/modules/test_github_repo.py
tests/unit/plugins/modules/test_linode_v4.py
tests/unit/plugins/modules/test_modprobe.py
=> remove unnecessary checks for unsupported python versions

changelogs/fragments/10329-catapult-deprecation.yml, meta/runtime.yml, plugins/modules/catapult.py
Deprecates the `catapult` module.
catapult
=> catapult: deprecation

changelogs/fragments/10323-nmcli-improvements.yml, plugins/modules/nmcli.py
=> nmcli: improvements

changelogs/fragments/10349-incus_connection-error-handling.yml, plugins/connection/incus.py
Related to #10344
This tweaks the error handling logic to work with more versions of Incus as well as catching some of the project and instance access errors.
The full context (instance name, project name and remote name) is now included so that the user can easily diagnose access problems.
incus_connection
=> incus_connection: Improve error handling

changelogs/fragments/logstash.yml, plugins/callback/logstash.py
=> logstash: Remove reference to Python 2 library

plugins/modules/lvg.py
Ref: https://github.com/ansible-collections/community.general/pull/10336#discussion_r2188196407
lvg
=> lvg examples: use YAML lists

tests/integration/targets/hg/tasks/install.yml, tests/integration/targets/hg/tasks/main.yml, tests/integration/targets/hg/tasks/run-tests.yml, tests/integration/targets/hg/tasks/uninstall.yml
Fixes: #10044
tests/integration/targets/hg/tasks/install.yml
tests/integration/targets/hg/tasks/main.yml
tests/integration/targets/hg/tasks/run-tests.yml
tests/integration/targets/hg/tasks/uninstall.yml
=> Enable hg integration test

plugins/modules/manageiq_provider.py
Noticed and fixed this while searching for something else...
=> manageiq_provider: fix docs markup

.azure-pipelines/azure-pipelines.yml
https://forum.ansible.com/t/ansible-test-in-ansible-core-2-17-and-2-18-freebsd-13-3-replaced-with-13-5/44070
CI
=> CI: Replace FreeBSD 13.3 with 13.5

plugins/modules/yum_versionlock.py, plugins/modules/zpool.py
Doc style adjustments
```paste below
```
=> doc style adjustments: modules [yz]*

.azure-pipelines/azure-pipelines.yml
Ref: https://github.com/ansible/ansible/pull/85576
Ref: https://github.com/ansible/ansible/pull/85578
CI
=> Update Python versions for CI

.azure-pipelines/azure-pipelines.yml, tests/unit/plugins/connection/test_wsl.py, tests/unit/plugins/modules/test_github_repo.py
=> CI: Add Python 3.14 unit tests

.azure-pipelines/azure-pipelines.yml, tests/unit/plugins/connection/test_proxmox_pct_remote.py, tests/unit/plugins/connection/test_wsl.py, tests/unit/plugins/modules/test_github_repo.py
Backport of #10511 to stable-10.
CI
some unit tests
=> [stable-10] CI: Add Python 3.14 unit tests (#10511)

changelogs/fragments/10531-wsl-paramiko.yml, plugins/connection/wsl.py, tests/unit/plugins/connection/test_wsl.py
=> wsl connection: import paramiko directly

tests/integration/targets/apache2_module/tasks/actualtest.yml, tests/integration/targets/ldap_search/tasks/tests/schema.yml
Backport of #10543 to stable-9.
=> [stable-9] Fix no longer valid constructs in tests (#10543)

tests/integration/targets/callback_diy/tasks/main.yml
=> diy callback: add test for on_any_msg

changelogs/fragments/10532-apk.yml, plugins/modules/apk.py, tests/integration/targets/apk/tasks/main.yml
Ref: https://github.com/ansible-collections/community.general/pull/10442#issuecomment-3140551919
apk
=> apk: fix empty/whitespace-only package name check

changelogs/fragments/10539-json_query.yml, plugins/filter/json_query.py, tests/integration/targets/filter_json_query/tasks/main.yml
Fixes https://github.com/ansible/ansible/issues/85600.
json_query filter
=> json_query: extend list of type aliases for compatibility with ansible-core 2.19

tests/integration/targets/callback_diy/tasks/main.yml
Backport of #10550 to stable-9.
diy callback
=> [stable-9] diy callback: add test for on_any_msg (#10550)

changelogs/fragments/10424-scaleway-update-zones.yml, plugins/inventory/scaleway.py, plugins/module_utils/scaleway.py, plugins/modules/scaleway_compute.py, plugins/modules/scaleway_compute_private_network.py, plugins/modules/scaleway_image_info.py, plugins/modules/scaleway_ip.py, plugins/modules/scaleway_ip_info.py, plugins/modules/scaleway_private_network.py, plugins/modules/scaleway_security_group.py, plugins/modules/scaleway_security_group_info.py, plugins/modules/scaleway_security_group_rule.py, plugins/modules/scaleway_server_info.py, plugins/modules/scaleway_snapshot_info.py, plugins/modules/scaleway_user_data.py, plugins/modules/scaleway_volume.py, plugins/modules/scaleway_volume_info.py
=> scaleway: update zone list

.github/BOTMETA.yml, .gitignore, plugins/modules/lvm_pv_move_data.py, tests/integration/targets/lvm_pv_move_data/aliases, tests/integration/targets/lvm_pv_move_data/meta/main.yml, tests/integration/targets/lvm_pv_move_data/tasks/cleanup.yml, tests/integration/targets/lvm_pv_move_data/tasks/creation.yml, tests/integration/targets/lvm_pv_move_data/tasks/main.yml, tests/integration/targets/lvm_pv_move_data/tasks/moving.yml, tests/integration/targets/lvm_pv_move_data/tasks/prepare.yml
Introduce the lvm_pv_move_data module to facilitate data movement between physical volumes in the same volume group. Include integration tests to ensure functionality and proper cleanup.
lvm_pv_move_data
=> lvm_pv_move_data: new module

changelogs/fragments/10520-arg-runcommand-list.yml, plugins/modules/apk.py, tests/unit/plugins/modules/test_apk.py
=> apk: command args as list rather than string

changelogs/fragments/10523-bzr-cmd-list.yml, plugins/modules/bzr.py
=> bzr: command args as list rather than string

changelogs/fragments/10525-composer-cmd-list.yml, plugins/modules/composer.py
=> composer: command args as list rather than string

changelogs/fragments/10435-github-repo-deprecate-force-defaults.yml, plugins/modules/github_repo.py
Deprecate the parameter value.
github_repo
=> github_repo: deprecate force_defaults=true

changelogs/fragments/10606-urpmi-cmd-list.yml, plugins/modules/urpmi.py
=> urpmi: command args as list rather than string

changelogs/fragments/10605-swupd-cmd-list.yml, plugins/modules/swupd.py
=> swupd: command args as list rather than string

changelogs/fragments/10604-solaris-zone-cmd-list.yml, plugins/modules/solaris_zone.py
=> solaris_zone: command args as list rather than string

changelogs/fragments/10603-riak-cmd-list.yml, plugins/modules/riak.py
=> riak: command args as list rather than string

changelogs/fragments/10599-open-iscsi-cmd-list.yml, plugins/modules/open_iscsi.py
=> open_iscsi: command args as list rather than string

changelogs/fragments/10601-pear-cmd-list.yml, plugins/modules/pear.py
=> pear: command args as list rather than string

changelogs/fragments/10608-xbps-cmd-list.yml, plugins/modules/xbps.py
=> xbps: command args as list rather than string

plugins/modules/pipx.py, tests/integration/targets/pipx/tasks/main.yml
Ref: https://github.com/ansible-collections/community.general/pull/10189#discussion_r2266547146
pipx
=> pipx examples and tests: fix terminology

tests/unit/requirements.txt
Requirements for Python prior to 2.7 are no longer support.
tests/unit/requirements.txt
=> update requirements for Python versions currently used

tests/integration/targets/pacman/tasks/main.yml, tests/integration/targets/pacman/tasks/yay-become.yml
Fixes #10675.
pacman integration tests
=> pacman: re-enable yay test

changelogs/fragments/10684-django-improvements.yml, plugins/module_utils/django.py, plugins/modules/django_check.py, plugins/modules/django_createcachetable.py
Some adjustments/simplifications.
plugins/module_utils/django.py
plugins/modules/django_createcachetable.py
=> django module, module_utils: adjustments

changelogs/fragments/10741-pacemaker-cluster-cleanup-deprecate.yml, plugins/modules/pacemaker_cluster.py
Add removal message for cleanup state as this will be added for `pacemaker_resource` module.
pacemaker_cluster
```paste below
```
=> pacemaker_cluster: deprecate cleanup state

changelogs/fragments/10642-parted-cmd-list.yml, plugins/modules/parted.py, tests/unit/plugins/modules/test_parted.py
=> parted: command args as list rather than string

plugins/modules/dnf_versionlock.py
Minor improvements in the module, code and docs.
dnf_versionlock
=> dnf_versionlock: minor refactor

.github/BOTMETA.yml, plugins/doc_fragments/django.py, plugins/module_utils/django.py, plugins/modules/django_check.py, plugins/modules/django_dumpdata.py, plugins/modules/django_loaddata.py, tests/unit/plugins/modules/test_django_dumpdata.py, tests/unit/plugins/modules/test_django_dumpdata.yaml, tests/unit/plugins/modules/test_django_loaddata.py, tests/unit/plugins/modules/test_django_loaddata.yaml
New modules `django_dumpdata` and its counterpart `django_loaddata`
plugins/modules/django_dumpdata.py
plugins/modules/django_loaddata.py
=> django_dumpdata, django_loaddata: new modules

changelogs/fragments/10665-pacemaker-resource-clone.yml, plugins/module_utils/pacemaker.py, plugins/modules/pacemaker_resource.py, tests/unit/plugins/modules/test_pacemaker_resource.yaml
Adds resource cloning capabilities in pacemaker_resource.
Fixes #10322
pacemaker_resource
```paste below
```
=> pacemaker_resource: Add cloning support for resources and groups

tests/integration/targets/pipx/tasks/main.yml, tests/integration/targets/pipx/tasks/testcase-7497.yml, tests/integration/targets/pipx/tasks/testcase-8809-pin.yml, tests/integration/targets/pipx/tasks/testcase-8809-uninjectpkg.yml, tests/integration/targets/pipx/tasks/testcase-9009-fixglobal.yml, tests/integration/targets/pipx/tasks/testcase-9103-upgrade-global.yml, tests/integration/targets/pipx/tasks/testcase-9619-latest-global.yml
Make adjustments in the `pipx` tests to reduce the test time.
In local tests, time went down from 6:38 to 5:50 and 5:30.
pipx
=> pipx: review tests

changelogs/fragments/10810-github_app_access_token-jwt.yml, plugins/lookup/github_app_access_token.py
Fixes #10807.
github_app_access_token lookup
=> github_app_access_token: fix compatibility import of jwt

plugins/modules/timezone.py
Mentioned by @aminvakli on IRC.
Thanks @aminvakil!
timezone
=> timezone: mention that Debian 13 also needs util-linux-extra

changelogs/fragments/10852-yaml.yml, plugins/cache/yaml.py
Fixes #10849.
yaml cache plugin
=> yaml cache plugin: make compatible with ansible-core 2.19

docs/docsite/rst/guide_uthelper.rst
Fix warnings when generating docsite.
Fixes #10850 
=> docs: fix sphinx warnings in uthelper guide

meta/runtime.yml, plugins/callback/opentelemetry.py, plugins/doc_fragments/django.py, plugins/modules/jira.py, plugins/modules/krb_ticket.py, plugins/modules/redfish_command.py, plugins/modules/redhat_subscription.py
Backport of #10867 to stable-10.
various
=> [stable-10] Fix typos: s/the the/the/ (#10867)

changelogs/fragments/10874-pipx-180.yml, plugins/doc_fragments/pipx.py, plugins/module_utils/pipx.py
Adjustments after the release of `pipx` 1.8.0.
plugins/module_utils/pipx.py
=> pipx: adjustments for pipx 1.8.0
