ansible-collections/community.general

changelogs/fragments/6862-opkg-exec.yml, plugins/modules/opkg.py
Add `executable` parameter to opkg module.
Fixes #5236 
opkg
=> opkg: add executable parameter

tests/integration/targets/pipx/aliases, tests/integration/targets/pipx_info/aliases
The pipx/pipx_info tests are failing, see for example:
- https://github.com/ansible-collections/community.general/actions/runs/5479206977
- https://github.com/ansible-collections/community.general/actions/runs/5479468549
- https://github.com/ansible-collections/community.general/actions/runs/5479458376
- https://dev.azure.com/ansible/community.general/_build/results?buildId=82747&view=results
All failed tests in these runs are due to pipx trying to install ansible-lint, and failing.
Since the pipx/pipx_info tests do something more with ansible-lint than just installing, I disabled the tests for now.
pipx
pipx_info
=> Temporarily disable pipx tests

.github/BOTMETA.yml, changelogs/fragments/6755-refactor-consul-session-to-use-requests-lib-instead-of-consul.yml, plugins/modules/consul_session.py, tests/integration/targets/consul/tasks/consul_session.yml, tests/integration/targets/consul/tasks/main.yml, tests/integration/targets/consul/templates/consul_config.hcl.j2
Split from #6715 as per PR comments. This was originally part of  #5320 by @Hakon.
Refactor consul_session module to use requests and the HTTP API due to an issue in a 3rd party lib.
consul_session
=> Refactor consul_session to support authentication with tokens

changelogs/fragments/6838-proxmox-dict-template.yml, plugins/modules/proxmox.py
Use `dict.get()` to return default value if `template` does not exist.
Fixes #5372
proxmox
=> proxmox: default value when checking for dict key

changelogs/fragments/6864-redfish-utils-fix-for-processorarchitecture-in-cpu-inventory.yaml, plugins/module_utils/redfish_utils.py
This update adds ProcessorArchitecture to redfish CPU inventory 
Fixes #6863
community.general.redfish_info
=> Add redfish processor architecture to Redfish CPU inventory

.github/BOTMETA.yml, plugins/lookup/bitwarden_secrets_manager.py, tests/unit/plugins/lookup/test_bitwarden_secrets_manager.py
Support for looking up a secret by ID on Bitwarden Secrets Manager (https://bitwarden.com/de-DE/products/secrets-manager/).
`bitwarden_secrets_manager`
BWS is a more automation-oriented product from Bitwarden. It is currently in beta and is not yet available for self-hosting. Therefore there is no ability to specify a custom server URL in this lookup plugin (initially). This lookup has been tested to work. All secret IDs and access tokens in the examples are dummys.
Also of note, technically there is an SDK for Bitwarden Secrets Manager:
https://bitwarden.com/help/secrets-manager-sdk/ and https://github.com/bitwarden/sdk
using this would be more robust instead of calling the CLI, but there are no Python bindings for the SDK yet. This lookup plugin could be …
=> New lookup plug-in: Bitwarden Secrets Manager

changelogs/fragments/6811-datadog-downtime-rrule-type.yaml, plugins/modules/datadog_downtime.py
The `datadog_downtime` module includes the optional `rrule` parameter to provide the recurrence for a downtime in the [rrule-format](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html). The datadog api client that the module is based on [requires that the recurrence type is set as "rrule"](https://datadoghq.dev/datadog-api-client-python/datadog_api_client.v1.model.html#datadog_api_client.v1.model.downtime_recurrence.DowntimeRecurrence:~:text=The%20RRULE%20standard%20for%20defining%20recurring%20events%20(%20requires%20to%20set%20%E2%80%9Ctype%E2%80%9D%20to%20rrule%20)), which was not done in the module thus far. Whenever the `rrule` param was populated, the API would return a `Bad Request` with the response `{'errors': ['Invalid recurrence type']}`. 
This change simply …
=> [datadog_downtime] - added 'type' to recurrence object when rrule param is present

changelogs/fragments/6785-openbsd_pkg_pkg_info_handling.yml, plugins/modules/openbsd_pkg.py
**OpenBSD pkg_info(1) behavior change.**
As we can see pkg_info behaves different between OpenBSD -current (>7.3) and OpenBSD <= 7.3.
It prints "Can't find inst:PKGNAME" if the package is not present. This has to be handled in the module otherwise we see
```
failed: [dev] (item=ranger) => {"ansible_loop_var": "item", "changed": false, "item": "ranger", "msg": "failed in get_package_state(): Can't find inst:ranger\n"}
```
**Example pkg_info(1) call on OpenBSD 7.3 -stable**
```
$ dmesg | head
OpenBSD 7.3 (RAMDISK_CD) #1063: Sat Mar 25 10:41:49 MDT 2023
deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/RAMDISK_CD
$ pkg_info -Iq inst:abook
abook-0.6.1p3
triangle$ echo $?
0
$ pkg_info -Iq inst:NOTINSTALLED
$ echo $?
1
```
**Example pkg_info(1) call on OpenBSD -current**
```
$ dmesg | …
```
=> Handle pkg_info(1) error message "Can't find"

changelogs/fragments/6713-yay-become.yml, plugins/modules/pacman.py, tests/integration/targets/pacman/handlers/main.yml, tests/integration/targets/pacman/tasks/main.yml, tests/integration/targets/pacman/tasks/yay-become.yml
Add additional parsing to support `yay` running as root, as the tool will **always** print a warning about the fact.
It must be noted, however, that for some reason I haven't identified (nor planning to invest so much time to do that), whenever `yay` is executed on a remote node (tested on a local VM with vagrant), it will not install AUR packages, only stable repositories are read.
Fixes #6184 
pacman
=> pacman: support yay as root

changelogs/fragments/6909-deprecate-webfaction.yml, meta/runtime.yml, plugins/modules/webfaction_app.py, plugins/modules/webfaction_db.py, plugins/modules/webfaction_domain.py, plugins/modules/webfaction_mailbox.py, plugins/modules/webfaction_site.py
The URLs used by the webfaction modules do not resolve DNS anymore. It seems that webfaction.com has been swallowed by  tsohost.com in 2020, but there is no clear indication of any API compatibility.
Ref: https://www.sebomarketing.com/webfaction-migrates-to-tsohost/
plugins/modules/webfaction_app.py
plugins/modules/webfaction_db.py
plugins/modules/webfaction_domain.py
plugins/modules/webfaction_mailbox.py
plugins/modules/webfaction_site.py
=> webfaction modules: deprecation

plugins/modules/consul_policy.py, tests/integration/targets/consul/tasks/consul_policy.yml, tests/integration/targets/consul/tasks/main.yml
Resubmitting parts of #5320 originally from Hakon, as per PR comments. 
Fixes: #1749 
consul_policy
=> Add consul_policy module from dormant PR

changelogs/fragments/6882-make-multiple-targets.yml, plugins/modules/make.py
Change `target` parameter to a list of strings, pass them all to `make`.
Fixes #4919
make
=> make: allow multiple targets to be specified

changelogs/fragments/6823-redfish-add-account-type-management.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_command.py
Redfish allows for clients to specify what a user account is allowed to access on a device with the `AccountTypes` and `OEMAccountTypes` properties. This pull request adds support for setting and displaying the account types (and OEM account types) for Redfish user accounts when invoking AddUser and ListUsers. These are optional parameters; users can still provide the simple "UserName, Password, RoleId" combination when creating user accounts.
Fixes #6823 
redfish_utils.py, redfish_info.py, redfish_command.py
Playbook with new options when making a new user account
```
---
- hosts: all
vars:
username: REDACTED
password: REDACTED
baseuri: REDACTED
default_uri_timeout: 5
default_uri_retries: 5
tasks:
- name: Set add new account …
```
=> Redfish: Added support for displaying and setting account types

changelogs/fragments/6861-yum_versionlock_minor_change_add-pinning-specific-versions.yml, plugins/modules/yum_versionlock.py
feature(yum_versionlock): add support to pin specific package versions
Adjusted `yum_versionlock` (as requested in #4470) to handle version suffixes in a correct way to avoid wrong change results. This will validate and handle the following cases:
- package name like:             httpd
- package name and version like: httpd-0:2.4.57-3.el9
Fixes #4470
@tedgin & @matt-horwood-mayden as you requested this change, please feel free to test.
Before:
```
[gyptazy@localhost ansible]# ansible-playbook playbooks/yum_versionlock.yml 
PLAY [yum versionlock] ***************************************************************************************************************************************************************************************************************** …
```
=> feature(yum_versionlock): add support to pin specific package versions

changelogs/fragments/6887-deprecate-stackdrive.yml, meta/runtime.yml, plugins/modules/stackdriver.py
The module relies entirely on API endpoints on a hostname that no longer resolves in DNS, hence the module is now utterly useless. Example: https://event-gateway.stackdriver.com/v1/annotationevent
stackdriver
=> stackdriver: deprecate module

changelogs/fragments/6925-cobbler-inventory-bugfix.yml, plugins/inventory/cobbler.py
This fixes the recently added cobbler_ip_address calculation.
inventory/cobbler.py
=> cobbler: Properly determine cobbler_ip_address

changelogs/fragments/6928-noqa-comments.yml, plugins/modules/gitlab_project_variable.py, plugins/modules/pubnub_blocks.py, plugins/modules/scaleway_security_group_rule.py, plugins/modules/xenserver_guest_info.py, plugins/modules/xenserver_guest_powerstate.py
Removed inline comments with noqa exceptions.
plugins/modules/gitlab_project_variable.py
plugins/modules/pubnub_blocks.py
plugins/modules/scaleway_security_group_rule.py
plugins/modules/xenserver_guest_info.py
plugins/modules/xenserver_guest_powerstate.py
=> remove noqa exceptions

changelogs/fragments/6908-snap-dangerous.yml, plugins/module_utils/snap.py, plugins/modules/snap.py, tests/integration/targets/snap/meta/main.yml, tests/integration/targets/snap/tasks/main.yml, tests/integration/targets/snap/tasks/test_dangerous.yml, tests/unit/plugins/modules/test_snap.py
Add `dangerous` parameter to module, mapping to CLI parameter `--dangerous`.
Because of explicitly considering named snap files in the `name` parameter, more logic was required to ensure the idempotency of the module.
Fixes #5715 
snap
=> snap: add param "dangerous"

changelogs/fragments/6783-6837-rhsm_repository-internal-refactor.yml, changelogs/fragments/6783-rhsm_repository-internal-refactor.yml, plugins/modules/rhsm_repository.py
Simplify a bit (and possibly speed it up a little) the parsing of the output of `subscription-manager repos --list`:
- simplify skipping the lines that are not interesting: check the first character only, as it is enough to determine whether it contains repository data or not
- check the start of each line manually, rather than with regexp: a simple slice + `lstrip()` gives the same result
=> rhsm_repository: refactor parsing of "subscription-manager repos" output

changelogs/fragments/6883-redfish-utils-changing-variable-names-in-get-volume-inventory.yml, plugins/module_utils/redfish_utils.py
SUMMARY
Fixing an issue caused due to PR [6719](https://github.com/ansible-collections/community.general/pull/6719). The "data" variable was getting replaced in the elif block on line 915 and was causing an issue on line 937 when getting the Volumes url.
ISSUE TYPE
COMPONENT NAME
=> Fix for get_volume_inventory

changelogs/fragments/6905-ipa_dnszone-key-error-fix.yml, plugins/modules/ipa_dnszone.py
Checking if 'idnsallowsyncptr' key exists in Freeipa response, before using this key 
Fixes #6905 
bugfixes:
- ipa_dnszone - fix 'idnsallowsyncptr' key error for reverse zone (https://github.com/ansible-collections/community.general/issues/6905).
ipa_dnszone
```paste below
```
=> Fix key error for reverse zone (#6905)

changelogs/fragments/6923-cobbler-inventory_unicode.yml, plugins/inventory/cobbler.py
Explicitly convert AnsibleUnicode to str() before passing it to xmlrpc client
Fixes #6922 
community.general.cobbler
```paste below
```
=> cobbler inventory plugin: Convert unicode to str

tests/utils/constraints.txt
This breaks CI for latest dnspython. (https://dev.azure.com/ansible/community.general/_build/results?buildId=83843&view=logs&j=89290267-74d5-5b3e-330d-ba0f2945add4&t=0ecc9edb-08fd-5c6e-50b9-4c9e0e2c0b70&l=6613)
constraints file
=> CI: Stop restricting idna

.github/BOTMETA.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_authz_permission.py, plugins/modules/keycloak_authz_permission_info.py, tests/integration/targets/keycloak_authz_permission/aliases, tests/integration/targets/keycloak_authz_permission/readme.adoc, tests/integration/targets/keycloak_authz_permission/tasks/main.yml, tests/integration/targets/keycloak_authz_permission/vars/main.yml
This new module can be used to create, update and remove Keycloak client authorization permissions. The client needs to have authorization enabled for this module to make sense. Both resource- and scope-based authorization permission are supported.
There are some peculiarities with the JSON payloads and endpoints:
* GET requests must be pointed to the "policy" endpoint. The returned data is in "policy" format and lacks information about attached resources, scopes and policies and includes an empty "config" parameter.
* POST and PUT requests must be pointed to the "permission" endpoints. The JSON payload must contain resource, scope and policy information.
The  end result is that it is not possible to query the current state of resources, scopes or policies attached to a permission. This …
=> Add keycloak_authz_permission module

changelogs/fragments/6968-cmdrunner-implicit-type.yml, plugins/module_utils/cmd_runner.py, tests/integration/targets/cmd_runner/library/cmd_echo.py, tests/integration/targets/cmd_runner/vars/main.yml
When a parameter in `argument_spec` has no type, meaning it is implicitly a `str`, `CmdRunner` would fail trying to find the `type` key in that dictionary.
=> cmd_runner module utils: fix bug when argument spec has implicit type

changelogs/fragments/6980-proxmox-fix-token-auth.yml, plugins/module_utils/proxmox.py
Fixes authorization via tokens. Check for the version is done against `proxmoxer`, not the API itself.
Fixes https://github.com/ansible-collections/community.general/issues/6975, https://github.com/ansible-collections/community.general/issues/6974.
module_utils/proxmox
=> [proxmox] Use proxmoxer_version instead of server API version

changelogs/fragments/6980-proxmox-fix-token-auth.yml, plugins/module_utils/proxmox.py, tests/unit/plugins/modules/test_proxmox_snap.py, tests/unit/plugins/modules/test_proxmox_tasks_info.py, tests/unit/requirements.txt
This is a backport of PR #6980 as merged into main.
- Use proxmoxer_version instead of server API version
- Add changelog fragment
(cherry picked from commit 796ad3565eab36a0146c3f3d084306969a5e51ee)
Fixes authorization via tokens. Check for the version is done against proxmoxer, not the API itself.
Fixes #6975, #6974.
=> [PR #6980/796ad356 backport][stable-6] [proxmox] Use proxmoxer_version instead of server API version

changelogs/fragments/6981-proxmox-fix-vm-creation-when-only-name-provided.yml, plugins/modules/proxmox_kvm.py, tests/unit/plugins/modules/test_proxmox_kvm.py
Fixes #6911
While creating VM by using name only we check if VM with that name already exist and cluster and do nothing in that case.
proxmox_kvm
=> [proxmox_kvm] Don't create VM if name is used without vmid

changelogs/fragments/6976-proxmox-vm-info-not-require-node.yml, plugins/modules/proxmox_vm_info.py, tests/unit/plugins/modules/test_proxmox_vm_info.py
As requested in [comment](https://github.com/ansible-collections/community.general/issues/5819#issuecomment-1627596541) module can re-use cluster/resources API to get first information about VMs. Then that info is enriched from lxc/qemu API responses.
In that case we can retrieve VM(s) info without requiring node parameter.
proxmox_vm_info
```paste below
```
=> [proxmox_vm_info] Re-use cluster resources API to use module without requiring node param

changelogs/fragments/6914-proxmox_kvm-enable-force-restart.yml, plugins/modules/proxmox_kvm.py
The documentation states the follow for the the `force` parameter:
> Can be used with states stopped, restarted, and absent.
Despite that, `force` is not actually used when `state=restarted`, this PR aims to fix that by executing a VM "reset" when force is `True`, and a "restart" otherwise.
proxmox_kvm
N/A
=> proxmox_kvm: enable 'force' restart of vm (as documented)

tests/integration/targets/java_cert/aliases, tests/integration/targets/java_keystore/aliases
For some reason keytool seems to be broken on newer RHELs (the timezone database for Java is not available). Disable the tests on RHEL for now.
java_cert
java_keystore
=> Skip java_cert and java_keystore tests on RHEL

tests/sanity/ignore-2.16.txt
Ref: #4690
Ref: #4691
Ref: https://docs.python.org/3.12/library/crypt.html#module-crypt
sanity tests
=> crypt is still deprecated in Python 3.12

changelogs/fragments/6981-proxmox-fix-vm-creation-when-only-name-provided.yml, plugins/modules/proxmox_kvm.py
This is a backport of PR #6981 as merged into main.
(cherry picked from commit f9448574bd43611d71932f0d88bc67585d528f2f)
Fixes #6911
While creating VM by using name only we check if VM with that name already exist and cluster and do nothing in that case.
proxmox_kvm
=> [PR #6981/f9448574 backport][stable-6] [proxmox_kvm] Don't create VM if name is used without vmid

plugins/modules/jenkins_plugin.py
Since ECS Fargate is serverless, one cannot access its jenkins_home other than from a machine (EC2 instance for example) that actually mounts and owns its EFS storage.
That way we can provide uid/gid 1000 (the same as for the default jenkins user inside the container) and authenticate at Jenkins URL.
jenkins_plugin
I feel this is not as straightforward from the docs and someone might benefit from such an example being present
=> Add example for ECS Fargate/EFS Jenkins authentication

tests/integration/targets/setup_docker/handlers/main.yml, tests/integration/targets/setup_docker/tasks/main.yml
Add handlers to stop the docker service and remove the `requests` Python package.
tests/integration/targets/setup_docker/
=> setup_docker: handlers to stop service and remove requests

changelogs/fragments/7020-redfish-utils-pagination.yml, plugins/module_utils/redfish_utils.py
Add support for paginated responses in the _software_inventory method
Fixes https://github.com/ansible-collections/community.general/issues/7011
redfish_utils
Redfish supports a property in responses `@odata.nextLink` which indicates a partial set of data is returned (paginated response). The existing method would truncate the returned data with no indication items were missing from the response.
Running a normal firmware inventory task:
```
- name: Collect Firmware Inventory
category: Update
command: GetFirmwareInventory
baseuri: "{{ bmc_address }}"
username: "{{ bmc_username }}"
password: "{{ bmc_password }}"
register: redfish_fw_inventory
- debug:
msg: "{{ redfish_fw_inventory.redfish_facts.firmware.entries | …
```
=> redfish_utils: Add support for "nextLink" property tag pagination

changelogs/fragments/6949-ejabberdctl-error.yml, plugins/modules/ejabberd_user.py
When the `ejabberdctl` command is not found, throws a more meaningful error message indicating so. Previously the message made no mention to the root of the problem.
Fixes #6949 
plugins/modules/ejabberd_user.py
=> ejabberd_user: better error when command not installed

changelogs/fragments/6983-rundeck-fix-typerrror-on-404-api-response.yml, plugins/module_utils/rundeck.py
Hello dear Ansible community :)
This is my first contribution, feel free to express any kind of criticism, be it on the content or the format.
I found a bug when using `community.general.rundeck_acl_policy`.
While creating a new ACL, I was greeted by the following trace:
```
File "/.../community/general/plugins/modules/rundeck_acl_policy.py", line 239, in <module>
File "/.../community/general/plugins/modules/rundeck_acl_policy.py", line 233, in main
File "/.../community/general/plugins/modules/rundeck_acl_policy.py", line 143, in create_or_update_acl
File "/.../community/general/plugins/modules/rundeck_acl_policy.py", line 137, in get_acl
File "/.../community/general/plugins/module_utils/rundeck.py", line 83, in api_request
TypeError: 'NoneType' object is not callable
```
- Bugfix Pull …
=> Rundeck - fix TypeError on 404 api response

changelogs/fragments/7046-snap-newline-before-separator.yml, plugins/modules/snap.py
The code for splitting the output of `snap info` for multiple snaps can't assume that `---` separates snaps any time it appears in the output; it needs to treat that as the separator only when it's at the start of a line. Otherwise it breaks if any snap uses `---` in its description text, which, e.g., the `bw` snap does as of the date of this commit.
Fixes #7045.
snap
```paste below
```
=> snap: Only treat `---` as an info separator when it's preceded by newline

plugins/modules/proxmox_kvm.py
Added a line of documentation to reflect boot order string format for Proxmox.
Fixes #7035
proxmox_kvm
The new documentation reflects the boot order string from the [official Proxmox VE documentation](https://pve.proxmox.com/wiki/Qemu/KVM_Virtual_Machines). I am unsure if the old documentation reflected an older version of Proxmox, so I phrased the documentation to indicate that newer Proxmox VE versions would require the string as described in the official documentation.
=> Documentation to reflect newer Proxmox VE boot string format

changelogs/fragments/7033-ejabberd-user-bugs.yml, plugins/modules/ejabberd_user.py, tests/integration/targets/ejabberd_user/aliases, tests/integration/targets/ejabberd_user/handlers/main.yml, tests/integration/targets/ejabberd_user/meta/main.yml, tests/integration/targets/ejabberd_user/tasks/main.yml
Add two bugfixes to ejabberd_user module:
* the `EjabberdUser.exist` should return `True` or `False`, but it was returning the tuple from a command execution (always `True` in `bool` context)
* the `EjabberdUser.changed` should return `True` or `False`, but it was returning the tuple from a command execution (always `True` in `bool` context)
Added integration tests.
ejabberd_user
=> ejabberd_user: bug fixes + tests

changelogs/fragments/6931-keycloak_client-inventory-bugfix.yml, plugins/modules/keycloak_client.py
Fixe new client created without secret when "protocol" is omited and publicClient is False
Keycloak version 18.0.2
keycloak_client.py
```
- name: Create Keycloak confidential client 
community.general.keycloak_client:
auth_username: USENAME
auth_password: PASSWORD
client_id: test
publicClient: False
state: present
```
=> Keycloak client secret

changelogs/fragments/7067-keycloak-api-paramerter-fix.yml, plugins/module_utils/identity/keycloak/keycloak.py
Added `http_agent`, `timeout`, and `validate_certs` to `open_url()` calls where they were missing in the KeycloakAPI module util
`keycloak` API module util
Copied the same argument structure as all other `open_url()` calls in the same Python file.
An example issue was using `community.general.keycloak_user` to create a user, which would complain about SSL verification eventhough `validate_certs` was set to `false`
=> Fix KeycloakAPI's missing http_agent, timeout, and validate_certs open_url() parameters

changelogs/fragments/7061-fix-bitwarden-get_field.yml, plugins/lookup/bitwarden.py
A bitwarden record without any custom fields will throw a `KeyError` when you try to search with `field='notes'`. The code here tries to open `match['fields']` without first checking if the key `fields` exists in `match`.
It turns out that with the current logic you can't get the `notes` field. It's either the login fields or custom fields. The new logic looks for your key in custom fields, then in login fields, then in the general fields for that record.
Fixes #6617
bitwarden
Here's the structure of a bitwarden record json object:
```
{
"collectionIds": null,
"creationDate": null,
"deletedDate": null,
"favorite": false,
"fields": [
{
"linkedId": null,
"name": "custom-field1",
"type": null,
"value": null
}
{
"linkedId": null,
"name": "custom-field2",
"type": null, …
```
=> bitwarden lookup fix `get_field`

changelogs/fragments/7081-redfish-utils-fix-for-storagecontrollers-deprecated-key.yaml, plugins/module_utils/redfish_utils.py
Get controller information from "Controllers" field instead of "StorageControllers" which is deprecated
cf. page 9 of  https://www.dmtf.org/sites/default/files/Redfish_Release_2022.1_Overview.pdf
get_storage_controller_inventory now use _Controllers_ field as main key to obtain storage controllers properties. And if _Controllers_ is not available , get_storage_controller_inventory will use the deprecated key _StorageControllers_
Fixes #7080 
redfish_utils
On the same HPe server, i had empty array:
```
TASK [ansible.builtin.debug] ***********************************************************************************************************************************
ok: [localhost] => {                                                            
"controllers_inventory": { …
```
=> Follow DMTF redfish deprecation on StorageControllers

changelogs/fragments/lvol-pct-of-origin.yml, plugins/modules/lvol.py, tests/integration/targets/lvg/tasks/setup.yml, tests/integration/targets/lvg/tasks/test_active_change.yml, tests/integration/targets/lvg/tasks/test_pvresize.yml
The `size` parameter of the `lvol` module did not support percentage of origin size specification when creating a snapshot volume. This is valid according to lvcreate(8). This PR addresses the issue. 
I increased the size of the loop devices in the test playbook to accommodate creating test snapshot LVs. The modified tests worked for me locally. Fingers crossed for the CI workflow. 
Fixes #1630 
`lvol` module
My first PR to the community.general collection. Kindly guide me if I've done anything wrong. Thanks!
=> lvol: Fix pct of origin

.azure-pipelines/azure-pipelines.yml
Ref: https://github.com/ansible/ansible/pull/81498
Ref: https://github.com/ansible/ansible/pull/81497
CI
=> CI: FreeBSD 13.0 and 12.3 are no longer availabe, bump versions and disable since these versions are already tested with stable-2.15

changelogs/fragments/7104_fix_lxc_remoteaddr_default.yml, plugins/connection/lxc.py
Ansible currently prints a warning when not explicitly defining one of the lxc `remote_addr` parameter variables and the fallback to `inventory_hostname` is used.
```
[WARNING]: The "lxc" connection plugin has an improperly configured remote target value, forcing "inventory_hostname" templated value instead of the string
```
This PR implements the same solution as ansible/ansible#77844, defining `inventory_hostname` as the lowest-priority variable for the `remote_addr` parameter.
lxc
Encountered, fixed and tested with:
```
$ ansible --version
ansible [core 2.14.3]
configured module search path = ['/home/corubba/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3/dist-packages/ansible …
```
=> lxc: fix remote_addr default to inventory_hostname

changelogs/fragments/7099-chroot-disable-root-check-option.yml, plugins/connection/chroot.py
Some chroot executables, like `arch-chroot`, support unshare mode (-N), which does not require root. This PR adds an option to disable the root check in the chroot connection plugin.
`plugins/connection/chroot.py`
=> chroot: add `disable_root_check` option

changelogs/fragments/7102-freebsd-shutdown-p.yml, plugins/action/shutdown.py, tests/integration/targets/shutdown/tasks/main.yml
* Use shutdown -p ... on FreeBSD such that the machine is halted and
powered off (-p) otherwise the machine is halted (-h) but remains on.
To follow suit with the other shutdown commands that also power off the machine freebsd shutdown should also power off the machine.  In that case -p should be used that will halt and power off vs -h that will just halt the machine leave it powered on with a prompt to power off and/or any key to reboot.
community.general.shutdown
```paste below
```
=> freebsd: shutdown -p ... on freebsd to power off machine

changelogs/fragments/7113-redfish-utils-power-cycle.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_command.py
Adds support for the `PowerCycle` Redfish reset type
Fixes #7083
redfish_utils
Used like the other Redfish power command options:
```
tasks:
- name: Power Cycle System
community.general.redfish_command:
command: PowerCycle
baseuri: "{{ bmc_address }}"
username: "{{ bmc_username }}"
password: "{{ bmc_password }}"
delegate_to: 127.0.0.1
register: power
- debug:
var: power
- name: Wait for node to reboot
ansible.builtin.wait_for_connection:
delay: 300
sleep: 10
timeout: 8000
```
Which results in a system power cycle as expected:
```
PLAY [test power cycle] *************************************************************************************************************************************************************************************** …
```
=> Add support for Redfish PowerCycle reset type

changelogs/fragments/7124-snap-empty-list.yml, plugins/modules/snap.py, tests/integration/targets/snap/tasks/main.yml, tests/integration/targets/snap/tasks/test_empty_list.yml
Exception was being raised when snap list was empty.
Fixes #7120 
snap
=> snap: fix case when snap list is empty

changelogs/fragments/7118-nmap_inv_plugin_no_arp_option.yml, plugins/inventory/nmap.py
Also ensured all options correctly use `get_option` .
fixes #7118
plugins/inventory/nmap
=> nmap inventory plugin, add use_arp_ping option

changelogs/fragments/7140-id-getmanagerinv-output.yml, plugins/module_utils/redfish_utils.py
Add Id to the output of GetManagerInventory. This is to make it easier to filter down the list of results for servers with multiple managers.
redfish_info
Prior to this change, it was not have been possible to filter down a list of multiple managers in the way shown below (by id).
```paste below
- name: Get BMC info
category: Manager
command: GetManagerInventory
baseuri: "{{ bmc_address }}"
username: "{{ bmc_username }}"
password: "{{ bmc_password }}"
register: redfish_bmc_info
- debug:
var: redfish_bmc_info.redfish_facts.manager.entries | map('last') | selectattr('Id', '==', '$ID_MANAGER_OF_INTEREST')
```
=> redfish_info: Report Id in GetManagerInventory output

changelogs/fragments/7132-gitlab-raw-variables.yml, plugins/module_utils/gitlab.py, plugins/modules/gitlab_group_variable.py, plugins/modules/gitlab_project_variable.py
This PR adds support for `raw` suboption in `gitlab_group_variable` and `gitlab_project_variable` modules.
Fixes #5685 
- New option for existing modules
- gitlab_group_variable
- gitlab_project_variable
This PR includes 2 modules changes since the added feature is exactly the same.
=> gitlab_project_variable/gitlab_group_variable: Add support for 'raw' option

tests/integration/targets/setup_pkg_mgr/tasks/archlinux.yml
Arch Linux tests are currently failing in CI once they try to install something with `pip`.
CI
=> CI: make sure EXTERNALLY-MANAGED is absent on Arch Linux

tests/unit/plugins/modules/test_opkg.py, tests/unit/plugins/modules/test_xfconf.py, tests/unit/plugins/modules/test_xfconf.yaml, tests/unit/plugins/modules/test_xfconf_info.py, tests/unit/plugins/modules/test_xfconf_info.yaml
Using the new YAML-spec for CmdRunner tests from #7154 for unit tests of `xfconf` and `xfconf_info`.
xfconf
xfconf_info
=> xfconf*: using yaml-specified unit tests

tests/unit/plugins/modules/test_cpanm.py, tests/unit/plugins/modules/test_gconftool2.py, tests/unit/plugins/modules/test_gconftool2_info.py, tests/unit/plugins/modules/test_opkg.py, tests/unit/plugins/modules/test_puppet.py, tests/unit/plugins/modules/test_snap.py, tests/unit/plugins/modules/test_xfconf.py, tests/unit/plugins/modules/test_xfconf_info.py
The constant `TESTED_MODULE` was copied from a previously existing test module, and it has been replicated over and over in these other tests. however, it is apparently not really used, so this PR trims the extra baggage.
=> remove extraneous unused constant

changelogs/fragments/7179-unixy-support-checkmode-markers.yml, plugins/callback/unixy.py
Modifies output on playbook start, task start, and handler start when playbook runs in check mode.
unixy.py
```
Executing playbook test.yml
- localhost on hosts: localhost -
Gathering Facts...
localhost ok
debug...
localhost ok: {
"ansible_default_ipv4": {
"address": "192.168.1.113",
"alias": "enp4s0",
"broadcast": "192.168.1.255",
"gateway": "192.168.0.1",
"interface": "enp4s0",
"macaddress": "d8:bb:c1:dc:29:c7",
"mtu": 1500,
"netmask": "255.255.254.0",
"network": "192.168.0.0",
"prefix": "23",
"type": "ether"
},
"changed": false
}
dnf...
localhost failed | msg: Failed to install some of the specified packages
wait_for...
command...
command...
- ganymede on hosts: ganymede -
ERROR! Attempting to decrypt but no vault secrets found
Executing playbook test.yml in …
```
=> Add unixy support for check_mode_markers

changelogs/fragments/7184-cobbler-mgmt-classes.yml, plugins/inventory/cobbler.py
Add exclude/include_mgmt_classes options to be able to include or exclude hosts based on their management class.
=> plugins/inventory/cobbler: Add exclude/include_mgmt_classes

changelogs/fragments/7161-fix-incorrect-post-parameter.yml, plugins/module_utils/net_tools/pritunl/api.py
Fix Pritunl API incorrect URL parameters.
community.general.pritunl_org
BEFORE
```console
TASK [pritunl-server-ubuntu : Install Pritunl | Create Organisation]
fatal: [server01-vm_8aac]: FAILED! => {
"discovered_interpreter_python": "/usr/bin/python3"
},
"force": false,
"name": "orgName",
"pritunl_api_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"pritunl_api_token": "HIDDEN",
"pritunl_url": "https://HIDDEN",
"state": "present",
"validate_certs": false
}
},
"msg": "HTTP Error 307: Temporary Redirect"
}
```
AFTER
```console
TASK [pritunl-server-ubuntu : Install Pritunl | Create Organisation]
ok: [server01-vm_8aac]
```
=> Update incorrect path for pritunl organization post

changelogs/fragments/7158-gitlab-project-default-branch-update.yml, plugins/modules/gitlab_project.py
This PR allow gitlab_project module to update a GitLab project's default branch.
gitlab_project module
Fixes #5995
=> feat: gitlab_project module - Allow to update project default branch

changelogs/fragments/7180-make_params_without_value.yml, plugins/modules/make.py
allows to use parameters with empty value in community.general.make.
Currently, params with empty value get set as None, which is not useful and can lead to unexpected behavior.
fixes #7178
make
Currently this code, used to build freebsd from sources:
```
community.general.make:
target: buildworld
chdir: "{{ freebsd_src_dir }}"
params:
-DWITH_FDT:
TARGET: arm64
```
produces `make -DWITH_FDT=None TARGET=arm64`  while `make -DWITH_FDT TARGET=arm64` is expected. 
Note the absence of "=None" for -DWITH_FDT.
```paste below
```
=> community.general.make:

.github/BOTMETA.yml, changelogs/fragments/improvements-to-jenkins-build-module.yml, plugins/modules/jenkins_build.py, plugins/modules/jenkins_build_info.py, plugins/modules/jenkins_job_info.py, tests/unit/plugins/modules/test_jenkins_build.py, tests/unit/plugins/modules/test_jenkins_build_info.py
Note: This PR actually includes three separate changes, if you prefer to have them in separate PRs just ask!
Due to some special requirements on our part, we needed (and added) the following:
- New option "detach" for the "jenkins_build" module, which allows the module to exit successfully as long as the build is created (default functionality is still waiting for the build to end before exiting).
- New option "time_between_checks" for the "jenkins_build" module,  which allows to configure the wait time between requests to the Jenkins server (this value has to be higher that the quiet time for the Jenkins job, so if it was higher than 10 it will always fail).
- New module "jenkins_build_info" to get information about a specific Jenkins build (or the last one of a job).
Tested with Jenkins …
=> Improvements to the jenkins_build module and new jenkins_build_info module

changelogs/fragments/7219-fix-nsupdate-cname.yaml, plugins/modules/nsupdate.py
Fix a possible `list index out of range` when no answer is returned in the `ttl_changed` method by applying the existing workaround for NS records to all record types.
Resolves #836
nsupdate
See #836
=> nsupdate: fix 'index out of range' error when no TTL answer is given

tests/unit/plugins/modules/helper.py, tests/unit/plugins/modules/test_cpanm.py, tests/unit/plugins/modules/test_gconftool2.py, tests/unit/plugins/modules/test_gconftool2_info.py, tests/unit/plugins/modules/test_opkg.py, tests/unit/plugins/modules/test_puppet.py, tests/unit/plugins/modules/test_snap.py, tests/unit/plugins/modules/test_xfconf.py, tests/unit/plugins/modules/test_xfconf_info.py
Create static methods `CmdRunnerTestHelper.from_file()` and `CmdRunnerTestHelper.from_list()`, and rename the module to `helper`.
=> test helper: create static methods .from_file() and .from_list()

.github/BOTMETA.yml, plugins/lookup/onepassword.py
I am no longer using Ansible regularly, so I don't want to receive notifications about changes. (I could also simply remove myself as a maintainer entirely if that's preferable.)
It doesn't likely matter much, but the email in my copyright line is also defunct, so I fixed that.
(not sure which issue type was right here)
onepassword
=> Update my maintainer status for 1PW plugin

changelogs/fragments/7241-prevent-key-error-when-value-does-not-exist.yml, plugins/lookup/onepassword.py, tests/unit/plugins/lookup/onepassword_common.py, tests/unit/plugins/lookup/onepassword_fixtures/v2_out_04.json, tests/unit/plugins/lookup/onepassword_fixtures/v2_out_04.json.license
A OnePassword field item might not have a value (property) when the user has omitted it (on purpose).
- Bugfix Pull Request (fixes #7240 )
OnePassword
```paste below
```
=> Use `get(..)` instead of [..] for safe lookup of value (Fixes #7240)

changelogs/fragments/deprecate-ansible-core-2.11-2.12.yml
As decided in https://github.com/ansible-community/community-topics/discussions/271 (**TODO** still needs to be confirmed! https://github.com/ansible-community/community-topics/issues/245#issuecomment-1718170163), we want to drop support for ansible-core 2.11 and 2.12 in the next major release.
This announces it in the changelog.
changelog
=> [stable-7] Deprecate support for ansible-core 2.11 and 2.12

changelogs/fragments/7264-ldap_search-strings.yml, plugins/modules/ldap_search.py
Fixes #5704
Fixes #7262
Updates #6475
ldap_search
=> ldap_search: make sure to also handle binary strings in Python 3

changelogs/fragments/7273-ini_file_ignore_spaces.yml, plugins/modules/ini_file.py, tests/integration/targets/ini_file/tasks/main.yml, tests/integration/targets/ini_file/tasks/tests/00-basic.yml, tests/integration/targets/ini_file/tasks/tests/04-symlink.yml, tests/integration/targets/ini_file/tasks/tests/05-ignore_spaces.yml, tests/unit/plugins/modules/test_ini_file.py
Add a new `ignore_spaces` option to the `ini_file` module which, if true, prevents the module from changing a line in a file if the only thing that would change by doing so is whitespace before or after the `=`.
Also add  unit and integration test cases for this new functionality.
Also fixes two bugs in the recently added tests for symlinked ini files: they weren't being executed at all, and they were creating their temporary files in the wrong place.
Fixes #7202
ini_file
=> Add `ignore_spaces` option to `ini_file` to ignore spacing changes

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml, README.md
ansible-core stable-2.16 has been branched.
CI
=> [stable-6] CI: devel → stable-2.16, move stable-2.13 to EOL CI

changelogs/fragments/7251-gitlab-variables-deleteing-all-variables.yml, plugins/module_utils/gitlab.py, plugins/modules/gitlab_group_variable.py, plugins/modules/gitlab_project_variable.py
Hotfix to 7.4 release deleting all GitLab variables
Fixes #7250 
affected modules are:
- gitlab_group_variable
- gitlab_project_variable
```paste below
```
=> Fixed gitlab_*_variable when using purge

changelogs/fragments/7129-adding_set_secure_boot_command_to_redfish_config.yml, changelogs/fragments/7129-changing_enable_secure_boot_to_set_secure_boot.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_config.py
SUMMARY
Changing EnableSecureBoot command to SetSecureBoot to facilitate both enabling and disabling of secure boot.
ISSUE TYPE
COMPONENT NAME
=> Adding SetSecureBoot to redfish_config

changelogs/fragments/7303-mail-incorrect-header-parsing.yml, plugins/modules/mail.py
Fix mail header parsing that skip headers containing equals characters due to missing maxsplit on header key/value parsing.
mail module
For example, the following mail module invocation trigger the bug:
```paste below
- name: Send email
mail:
host: "{{ smtp.host }}"
port: "{{ smtp.port }}"
secure: "{{ smtp.secure }}"
username: "{{ smtp.username }}"
password: "{{ smtp.password }}"
subtype: "html"
from: "{{ email.from }}"
to: "{{ to }}"
subject: "{{ subject }}"
body: "{{ body }}"
attach: "{{ email.attach | default(omit) }}"
headers:
- X-Protective-Marking="VER=2005.6, NS=2020.1.example.com, SEC=xfkrf, ORIGIN=noreply@example.com"
```
The `split("=")` function applied to split the header key and value generate an error because there are multiples `=` characters, but only …
=> Fix incorrect parsing of headers containing equal character

changelogs/fragments/6134-add-locked-option-for-cargo.yml, plugins/modules/cargo.py
This PR introduces `locked` option to cargo module, allowing user to install with locked dependency.
Equivalent to `--locked` flag of `cargo install` command
The flag was already suggested at the original issue description: #3975
plugins/modules/cargo.py
=> feat(cargo): add locked option

tests/integration/targets/pacman/tasks/remove_nosave.yml
xintd is no longer a package in Arch; use mdadm instead.
(Failing nightlies: https://dev.azure.com/ansible/community.general/_build/results?buildId=90587&view=logs&j=89290267-74d5-5b3e-330d-ba0f2945add4&t=0ecc9edb-08fd-5c6e-50b9-4c9e0e2c0b70&l=9348)
pacman
=> xinetd no longer exists; use mdadm instead

changelogs/fragments/7301-fix-backend-config-string-encapsulation.yml, plugins/modules/terraform.py
Removing shlex_quote.
This FIX solves the following issues:
- https://github.com/ansible-collections/community.general/issues/5016
- https://github.com/ansible-collections/community.general/issues/6517
terraform
Removed the `shlex_quote` from the backend-config command line argument.
```paste below
```
=>  Fixing incorrect string encapsulation for -backend-config.

changelogs/fragments/7318-add-linkstatus-attribute-to-nic-inventory.yml, plugins/module_utils/redfish_utils.py
Add `LinkStatus` attribute to Ethernet Interface description.
Fixes #7317 
redfish_utils
Before:
```
"redfish_facts": {                                                          
"nic": {                       
"entries": [                                                        
[                                                               
{                  
"resource_uri": "/redfish/v1/Systems/1/"
},                                                          
[        
{ 
"IPv4Addresses": [],
"IPv6Addresses": [],
"Id": "1",
"MACAddress": "ff:ff:ff:ff:ff:ff",
"Name": "",                                                                                                                         
"NameServers": [], …
```
=> Add LinkStatus to Ethernet Interface attribute list

changelogs/fragments/7284-supervisorctl-stop-before-remove.yaml, plugins/modules/supervisorctl.py
Stop the processes before removing them.
This is needed to create a idempotent playbook. You should not have to explicitly stop a supervisor process before removing it. If you would, then the stop action on all subsequent calls will fail since the process does not exists on supervisor since you removed it at the first call.
It's like any process manager. If you `apt remove <some-daemon>`, you don't have to stop explicitly stop the deamon before.
This way, even with a running process, you just have to mark it `absent` to stop/remove it. 
supervisorctl
Before:
```
TASK [Delete supervisor process] *************************************************************************************************************************************************************
fatal: …
```
=> supervisorctl: stop process before removing it

changelogs/fragments/7267-redis_info.yml, plugins/modules/redis_info.py, tests/unit/plugins/modules/test_redis_info.py
Refactor the redis_info module to use the redis module_utils enabling to pass TLS parameters to the Redis client.
redis_info
Usage:
```
community.general.redis_info:
login_host: "localhost"
login_port: 6379
login_password: "PASS"
tls: true
ca_certs: "/etc/ssl/ca.pem"
```
=> feat(redis_info): use module_utils redis to support TLS

changelogs/fragments/7295-adding_deprecation_for_timeout_in_redfish_info_config_command.yml, plugins/modules/redfish_command.py, plugins/modules/redfish_config.py, plugins/modules/redfish_info.py
SUMMARY
Adding deprecation notice for timeout parameter.
Old value was 10. Proposed new value is 60.
Suggesting an increase in the timeout since we observed delayed responses from Gen11 servers while testing.
ISSUE TYPE
COMPONENT NAME
=> Adding deprecation for timeout parameter from 10 to 60 for redfish_info, redfish_config and redfish_command

changelogs/fragments/7308-onepassword-multi-acc.yml, plugins/lookup/onepassword.py, plugins/lookup/onepassword_raw.py
Add support for multiple 1Password accounts.
Currently, when 1password is logged into multiple accounts, `community.general.onepassword` always defaults to the first account in the list and there is no way to select any other account. This PR introduces a new option `account_id` which allow specifying which account to use.
`community.general.onepassword`
=> allow specifying a 1Password account ID

changelogs/fragments/7330-redfish-utils-oem-params.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_command.py
Possible resolution to https://github.com/ansible-collections/community.general/issues/7331
Add support for Oem parameters in the MultipartHTTPPushUpdate command of `redfish_command`
=> Add support for Oem params

.github/BOTMETA.yml, plugins/modules/simpleinit_msb.py, tests/unit/plugins/modules/test_simpleinit_msb.py
This is a backport of https://github.com/ansible/ansible/pull/19231, support for `simpleinit-msb` -- an init system used in [Source Mage GNU/Linux](https://sourcemage.org/). GitHub mirror [here](https://github.com/sourcemage).
The fact part submitted in https://github.com/ansible/ansible/pull/80963.
`community.general.simpleinit_msb`
N/A
=> Support for simpleinit-msb init system

changelogs/fragments/7339-pnpm-correct-version-when-state-latest.yml, plugins/modules/pnpm.py, tests/integration/targets/pnpm/tasks/main.yml, tests/integration/targets/pnpm/tasks/run.yml
If version is forcefully set at latest when state is latest, the package will always be changed, as there is no version "latest" will ever be detected. It is better to keep it None.
Fixes the idempotency problem when state is latest, Previously, version was set at latest when state was latest, so the package was updated every time. This should be fixed now.
```paste below
```
=> pnpm: version should not be latest when state is latest

plugins/inventory/lxd.py, plugins/modules/lxd_container.py, plugins/modules/lxd_profile.py, plugins/modules/lxd_project.py
Update links to LXD docs since it moved from linuxcontainers.org to Canonical. See the official announcement: https://discourse.ubuntu.com/t/faq-lxd-has-been-moved-to-canonical/36709
Update links to LXD docs in the LXD inventory plugin and the `lxd_{container,profile,project}` modules.
=> LXD moved to Canonical

changelogs/fragments/7304-prevent-parted-warnings.yml, plugins/modules/parted.py
Add automatic answer "fix" when script mode -s is used with parted version >= 3.4.64
Comments from the project parted :
automatically answer exceptions with "fix" in script mode, which is useful for:
GPT header not including full disk size;
moving the backup GPT table to the end of the disk;
MAC fix missing partition map entry;
etc.
see: https://www.mail-archive.com/parted-devel@alioth-lists.debian.net/msg00369.html
Fixes #1653 #1461
minor_changes:
- parted - on resize, use ``--fix`` option if available
parted
just use -f with -s and resizepart in the same command.
```paste below
Before:
When you enhance the drive on the vcenter, and refresh in the OS, the community.general.parted with resize=true hang like that:
Warning: Not all of the space available to /dev/sdx …
```
=> Prevent parted warnings in script mode

changelogs/fragments/7340-snap-fix.yml, plugins/modules/snap.py, tests/unit/plugins/modules/test_snap.py
Change the change detection mechanism from "parsing installation" to "comparing end state with initial state".
Fixes #7265 
snap
```paste below
```
=> snap: detect change by checking final state

changelogs/fragments/7364-add-option-force-gitlab-group.yml, plugins/modules/gitlab_group.py
- Add option force (default value: false) to delete group even if projects exists in it.
gitlab_group
=> Add option force_delete module gitlab_group

changelogs/fragments/7369-fix-lxc-options.yml, plugins/connection/lxc.py, tests/unit/plugins/connection/test_lxc.py
Because the lxc plugin was only using `PlayContext` properties, using host vars like `ansible_lxc_host` didn't work. This is fixed by instead using the `get_option` method inherited from `AnsiblePlugin`. The options are not yet available in the `__init__` function, so the determination of the container name is moved to the `_connect` method, which is the first time it is actually needed. The default for the `remote_addr` option is removed, because the string `inventory_hostname` is not very useful. At all. This seams to have been spread with copy&paste and a bit of cargo culting. The variable priority already takes care of setting the value.
Add a fixture to allow testing the lxc connection plugin both with and without liblxc being present. Also change the test from unittest to pytest, …
=> Fix lxc plugin options

changelogs/fragments/7144-add-getbiosregistry-command-to-redfish-info.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_info.py
SUMMARY
Adding GetBiosRegistries command to redfish_info module.
ISSUE TYPE
COMPONENT NAME
=> Adding bios registries command to redfish_info

changelogs/fragments/7378-redhat_subscription-dbus-consumer-type.yaml, plugins/modules/redhat_subscription.py
subscription-manager 1.29.32 renames the `type` D-Bus registration option to `consumer_type`; this means that the right option must be passed according to the distro type & version.
Copy the same approach done for environments, tweaking the version needed: this change is found in RHEL 9.2+ and supported Fedora versions.
=> redhat_subscription: fix D-Bus option for consumer type on older distros

tests/integration/targets/odbc/aliases, tests/integration/targets/odbc/tasks/main.yml
=> Skip odbc tests on Python 2.6 and CentOS 7

changelogs/fragments/7374-fix-selective-callback-taskname-length.yml, plugins/callback/selective.py
When printing the task name section of command output, previously the line was always 3 chars longer than `line_length` which is meant to limit width. This was due to the length check simply looking at the `task_name`, and not including the 3 formatting characters added in the string directly (`# {0} `). 
To fix this, I pulled these characters out into a separate variable then did the length check on that.
bugfixes:
- selective - fix task name output using improper length check and going over the defined width limit
selective
Note that there are many other checks in this plugin that also do not properly follow the `line_length` variable for one reason or another. I will submit fixes for those later in a separate PR as they are not as trivial to resolve.
=> Fix callback/selective task print being long

changelogs/fragments/7375-fix-github-deploy-key-pagination.yml, plugins/modules/github_deploy_key.py
Fixes #5929. 
I also encountered this error, though unrelated to the use of `force`. The bug is caused by the pagination code in the module. If Deploy Keys exist, but not enough to paginate, the pagination check would raise a `KeyError`. Setting a default value for the lookup is sufficient to fix the module.
github_deploy_key
See issue #5929 for a discussion of how to trigger the bug.
Before:
```
TASK [(Locally) Push the deploy key to jupiler] *****************************************************************************************************************************************************
task path: /Users/padraic/Documents/bitbucket_to_github/migrate_machines/migrate_repos.yaml:62
The full traceback is:
File …
```
=> Fix  pagination issue in community.general.github_deploy_key

changelogs/fragments/7373-lxc-remote-addr-change.yml, plugins/connection/lxc.py, tests/unit/plugins/connection/test_lxc.py
Detect if the `remote_addr` option changed, and properly "reconnect" aka update the internal state of the plugin instance.
This implements a suggestion from [#7369](https://github.com/ansible-collections/community.general/pull/7369/files#r1349765954).
Also add a test for the stopped container error, including some minor modification to the fixture. I didn't want to open a separate PR just for this, hence it is included here.
lxc
=> Handle remote_addr change in lxc connection plugin

.azure-pipelines/azure-pipelines.yml
stable-2.14's macOS 12.0 seems to be dead, or at least very unreliable.
CI
=> CI: remove macOS 12.0 from CI

changelogs/fragments/7360-lxd-remote-addr-host.yml, plugins/connection/lxd.py
This allows to use FQDNs in the inventory and have the connection driver do the translation when talking to LXD that uses hostnames (no ".") for instance names. Those are either globally unique or unique per network/ project in LXD.
```
all:
children:
lxd_dmz:
vars:
ansible_lxd_project: dmz
hosts:
www01.dmz.example.com:
www02.dmz.example.com:
```
```
$ lxc list --project dmz
+---------+---------+----------------+------+-----------+-----------+----------+
|  NAME |  STATE  |        IPV4      | IPV6 |   TYPE    | SNAPSHOTS | LOCATION |
+-------+---------+------------------+------+-----------+-----------+----------+
| www01 | RUNNING | 192.0.2.1 (eth0) |      | CONTAINER | 0         | t1       |
+-------+---------+------------------+------+-----------+-----------+----------+
| www02 | …
```
=> plugins/connection/lxd: convert FQDN to instance name

changelogs/fragments/7392-lxd-inventory-server-cert.yml, plugins/inventory/lxd.py, plugins/module_utils/lxd.py
It is common for lxd servers to use self-signed certificates. Providing the server
certificate allows to do verification of the HTTPS connection. When this option is
used, the hostname part of the url doesn't need to match one of the Subject Alternate
Names (SANs) of the certificate. This is essentially certificate pinning.
plugins/inventory/lxd
If you interact with remote LXD servers, you will often run into servers using self-signed certificate as that's how LXD creates it's own certificate by default (see https://github.com/canonical/lxd/blob/main/lxd/util/encryption.go#L41-L57 and https://github.com/canonical/lxd/blob/main/shared/cert.go#L308-L383).
When using the CLI client `lxc`, the server certificate is essentially saved on disk and used as CA for the given …
=> plugins/inventory/lxd: add server_cert option

changelogs/fragments/7412-add-port-for-nomad-connection.yaml, plugins/doc_fragments/nomad.py, plugins/modules/nomad_job.py, plugins/modules/nomad_job_info.py
Add port parameter to connect to nomad server
Fixes #7411
nomad_job
=> Add nomad_job port parameter 

changelogs/fragments/7401-ini-file-modify-inactive-option.yaml, plugins/modules/ini_file.py, tests/integration/targets/ini_file/tasks/main.yml, tests/integration/targets/ini_file/tasks/tests/06-modify_inactive_option.yml
Add new `modify_inactive_option` option to the `ini_file` module which, when set to false, will not modify a matching commented-out (inactive) option, and will instead add a new line for the given `option: value`. 
For example, with the `file.ini` that looks like this
```ini
[section]
```
The following task
```yaml
ini_file:
path: file.ini
section: section
option: foo
value: bar
modify_inactive_option: true
```
will produce the following output
```ini
[section]
foo = bar
```
Whereas
```yaml
ini_file:
path: file.ini
section: section
option: foo
value: bar
modify_inactive_option: false
```
Will produce this
```ini
[section]
foo = bar
```
Fixes https://github.com/ansible-collections/community.general/issues/7297
ini_file
=> Add `modify_inactive_option` option to `ini_file` module to ignore matching commented key:value pairs

tests/integration/targets/ansible_galaxy_install/aliases
https://forum.ansible.com/t/cannot-install-some-roles-anymore-tries-to-import-from-github-user-none/2018
=> Disable ansible_galaxy_install tests until Galaxy is fixed

tests/integration/targets/ansible_galaxy_install/aliases
This reverts commit f7532c7d9dea16e81f2f5535504951d819a52e51.
Undoes #7440.
=> Revert "Disable ansible_galaxy_install tests until Galaxy is fixed (#7440)"

.azure-pipelines/azure-pipelines.yml
Currently they only run with GHA.
Ref: https://github.com/ansible-collections/community.general/pull/7418#issuecomment-1785975830
CI
=> CI: make sure that Python 2.7 unit tests also run with AZP

changelogs/fragments/7452-fix-icinga2_host-requiring-ip-key.yml, plugins/modules/icinga2_host.py
This PR allows `icinga2_host` to create hosts without having to provide an `ip` address.  
This is in line with what Icinga 2 allows you to do. Even though useful, no address is strictly necessary. 
Fixes #5248
icinga2_host
=> Fix icinga2_host requiring ip key.

changelogs/fragments/3787-pass-composer-working-dir.yml, plugins/modules/composer.py
When the composer plugin runs a command, it searches for the command available options using `composer help`.
However, some composer commands are not available globally, but only in a given working directory. Therefore, it is required to pass the `working_dir` parameter to all composer command invocation that is not a global command.
Fixes #3787 
composer module
Before this change, the execution of:
```yaml
- name: Compile the .env.local file to PHP
community.general.composer:
command: symfony:dump-env
working_dir: "/path/to/my/directory"
arguments: prod
```
was throwing an error:
```
fatal: FAILED! => {"changed": false, "msg": "There are no commands defined in the \"symfony\" namespace. help [--format FORMAT] [--raw] [--] [<command_name>]"}
```
=> Fix the ability to run Composer "working_dir" dependent commands

changelogs/fragments/7467-fix-gitlab-constants-calls.yml, plugins/modules/gitlab_group_members.py, plugins/modules/gitlab_project_members.py, plugins/modules/gitlab_protected_branch.py, plugins/modules/gitlab_user.py
docs(gitlab_user.py): Specify the version constraint for python-gitlab module
Fix gitlab constants call from python-gitlab library
#7466
gitlab_user
gitlab_protected_branch
```paste below
```
=> [gitlab] Fix gitlab constants calls

tests/integration/targets/timezone/tasks/main.yml
In some cases, such as the OpenSuSE tests, this always causes the timezone tests to be run twice because the first run fails when it tries to "restore" a time zone called `n/a`.
timezone
=> timezone tests: do not restore original timezone if it wasn't known (value 'n/a')

tests/integration/targets/nomad/aliases
The nomad tests fail quite a lot. Disable them until someone can make them more stable.
nomad_job
nomad_job_info
=> Disable nomad tests

changelogs/fragments/7472-gitlab-add-ca-path-option.yml, plugins/doc_fragments/gitlab.py, plugins/module_utils/gitlab.py
This PR adds a `ca_path` option to gitlab modules. This new option allows to use a custom CA certificates bundle to verify GitLab server certificate.
all gitlab modules
N/A
Fixes #3007
=> feature(gitlab): add 'ca_path' option

changelogs/fragments/7143-proxmox-template.yml, plugins/modules/proxmox.py, plugins/modules/proxmox_kvm.py
Adds an option for converting LXC containers and KVM VMs to templates with the proxmox and proxmox_kvm modules.
proxmox and proxmox_kvm
```paste below
```
=> add template option to proxmox and proxmox_kvm

changelogs/fragments/7465-redfish-firmware-update-message-id-hardening.yml, plugins/module_utils/redfish_utils.py
Updated message handling for update operations to skip message objects with missing MessageId properties. While this is invalid, it's easy to handle and just move on to other messages to surface to the user.
Fix #7465
redfish_utils, redfish_command
Output after change.
```paste below
"redfish_results": {
"discovered_interpreter_python": "/usr/bin/python3"
},
"failed": false,
"msg": "Action was successful",
"return_values": {
"update_status": {
"handle": <REDACTED>,
"messages": [],
"resets_requested": [],
"ret": true,
"status": "New"
}
},
"session": {}
}
}
```
=> Redfish: Updated message handling for update operations to skip message objects with missing MessageId properties

changelogs/fragments/7464-fix-vm-removal-in-proxmox_pool_member.py, changelogs/fragments/7464-fix-vm-removal-in-proxmox_pool_member.yml, plugins/modules/proxmox_pool_member.py
Fix non working feature of the module
community.general.proxmox_pool_member
In the original version the vm doesn't get removed from the proxmox pool when "state: absent" is set in the task, it always errors with "'Failed to delete a member (12345) from the pool TestPool: list.remove(x): x not in list'"
Try the example in the documentation for "Remove VM from the Proxmox VE pool using VM name" 
https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_pool_member_module.html#examples
Before:
```
invocation:
module_args:
api_host: localhost
api_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
api_token_id: null
api_token_secret: null
member: '12345'
poolid: TestPool
state: absent
type: vm
validate_certs: false
msg: 'Failed to delete …
```
=> fix vm removal in proxmox_pool_member.py

changelogs/fragments/7501-type.yml, plugins/module_utils/ocapi_utils.py, plugins/module_utils/oracle/oci_utils.py, plugins/module_utils/redfish_utils.py
Fix sanity tests.
Ref: https://dev.azure.com/ansible/community.general/_build/results?buildId=95127&view=logs&j=989d489a-4f0d-5fce-ef97-861a3aa8f466&t=7f12bb05-38e3-5790-48be-85ee2e060d6b
several module utils
=> Use isinstance() instead of type()

changelogs/fragments/7462-Add-ostype-parameter-in-LXC-container-clone-of-ProxmoxVE.yaml, plugins/modules/proxmox.py
When creating an LXC container for Proxmox VE, containers such as openwrt could not be created because the ostype parameter could not be specified.
To deal with this, we added some notes so that the ostype parameter can be handled by Ansible.
```paste below
```
=> Add ostype parameter in LXC container clone of Proxmox VE

changelogs/fragments/7456-add-ssh-control-master.yml, plugins/modules/ssh_config.py, tests/integration/targets/ssh_config/tasks/options.yml
Add support for [`ControlMaster`](https://man.openbsd.org/ssh_config.5#ControlMaster) (with [`ControlPath`](https://man.openbsd.org/ssh_config.5#ControlPath), [`ControlPersist`](https://man.openbsd.org/ssh_config.5#ControlPersist)) SSH config options.
Second commit also converts `bool` to `str` correctly for options which allow `yes` / `no` in addition to other values as YAML `yes` / `no` is parsed as `True` / `False` but `ssh_config` needs `"yes"` / `"no"`.
ssh_config
_None_
=> [ssh_config] Add support for ControlMaster

changelogs/fragments/bitwarden-lookup-performance.yaml, plugins/lookup/bitwarden.py
The bitwarden lookup plugin searches through all items using `bw list items --search`, which takes a lot of time. However, when looking for an item using the item id, there is a much faster way: `bw get item  <itemid>`. This PR introduces this method for every lookup that uses the item's id, while keeping backwards compatibility.
This work is based on #6619. The open review comment there has been addressed.
- Feature / Performance Pull Request
bitwarden
_None_
=> Improve performance of the bitwarden lookup plugin

changelogs/fragments/7199-gitlab-runner-new-creation-workflow.yml, plugins/modules/gitlab_runner.py
This PR adds support  for the new GitLab Runner creation workflow.
See docs here : https://docs.gitlab.com/ee/ci/runners/new_creation_workflow.html
gitlab_runner module
In GitLab's new API endpoint, `active` option is not supported any more (deprecated since 14.8, latest version is 16.4), and replaced with `paused`.
Both options are here handled (mutually exclusive) to keep backward compatibility. Another PR will be necessary to deprecate `active` option following GitLab evolution.
Fixes #3742
**NB :** This PR will keep Draft status until `python-gitlab` next release including the new API endpoint.
=> feat(gitlab_runner module): Add support for the new runner creation workflow

changelogs/fragments/7486-gitlab-refactor-package-check.yml, plugins/module_utils/gitlab.py, plugins/modules/gitlab_branch.py, plugins/modules/gitlab_deploy_key.py, plugins/modules/gitlab_group.py, plugins/modules/gitlab_group_members.py, plugins/modules/gitlab_group_variable.py, plugins/modules/gitlab_hook.py, plugins/modules/gitlab_instance_variable.py, plugins/modules/gitlab_merge_request.py, plugins/modules/gitlab_project.py, plugins/modules/gitlab_project_badge.py, plugins/modules/gitlab_project_members.py, plugins/modules/gitlab_project_variable.py, plugins/modules/gitlab_protected_branch.py, plugins/modules/gitlab_runner.py, plugins/modules/gitlab_user.py
This PR removes useless `ensure_gitlab_package(module)` checks in gitlab modules, since this check is already called by generic `gitlab_authentication(module)` method.
all gitlab modules
N/A
=> refactor(gitlab modules): remove duplicate gitlab package check

changelogs/fragments/7489-netcup-dns-record-types.yml, plugins/modules/netcup_dns.py
The provider API for Netcup DNS has added support for additional DNS record types: OPENPGPKEY, SMIMEA and SSHFP.
This PR covers a trivial change to add these types to the list of choices.
The upstream library also already added that support (https://github.com/nbuchwitz/nc_dnsapi/pull/4 and https://github.com/nbuchwitz/nc_dnsapi/pull/8).
netcup_dns
=> Netcup DNS: Add support for additional record types

changelogs/fragments/add-ipa-sudorule-deny-cmd.yml, plugins/modules/ipa_sudorule.py
Introduces new options for `deny_cmd` and `deny_cmdgroup` to the ipa_sudorule module.
This allows the user to specify options to allow commands to be added to the 'disallow' section of a sudorule
ipa_sudorule
```paste below
```
=> Ipa sudorule/add deny options

changelogs/fragments/7499-allow-mtu-setting-on-bond-and-infiniband-interfaces.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
Infiniband and bond interface types can also receive MTU settings
Changelog:
Enabling setting of MTU on bond and Infiniband interfaces
nmcli
I think this is pretty straight-forward... I don't know what else to add.
=> infiniband and bond interfaces can receive MTU settings too

changelogs/fragments/7517-elastic-close-client.yaml, plugins/callback/elastic.py
Close elastic-apm client to not leak urllib3 connections.
Fix #7518 and is related to https://github.com/elastic/apm-agent-python/issues/1912
Review with "hide whitespaces" enabled.
`community.general.plugins.callback.elastic`
Running anything with elastic source can cause a `Closing the transport connection timed out.`, because elastic client is not closed.
A small example can trigger the issue.
```python
from ansible_collections.community.general.plugins.callback.elastic import ElasticSource
source = ElasticSource("")
apm_cli = source.init_apm_client("http://localhost:8200", "service", None, None, None)
```
```console
$ python -Wd unclosed.py
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, …
```
=> Close elastic APM client to release connections

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/django_manage/aliases, tests/integration/targets/homectl/aliases, tests/integration/targets/iso_extract/aliases, tests/integration/targets/odbc/aliases, tests/integration/targets/setup_snap/tasks/D-RedHat-9.3.yml, tests/integration/targets/ufw/aliases
Ref: https://forum.ansible.com/t/ansible-test-added-rhel-9-3-and-deprecated-rhel-9-2/2336
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/62
CI
=> CI: Add rhel/9.3 for devel, remove rhel/9.2

tests/integration/targets/sysrc/tasks/main.yml
https://dev.azure.com/ansible/community.general/_build/results?buildId=96107&view=logs&j=489c5a82-e9cd-5bc3-857e-065b97d45876&t=11e2531d-7868-57c8-064b-fb71affce1d8&l=7824
sysrc
=> sysrc: FreeBSD jail test no longer works with FreeBSD 13.1

changelogs/fragments/7495-proxmox_disk-manipulate-cdrom.yml, plugins/modules/proxmox_disk.py
Added ability to manipulate CD-ROM drive:
- create drive;
- mount and unmount ISO image on it;
- use physical drive.
proxmox_disk
=> [proxmox_disk]: Add ability to manipulate CD-ROM drive

changelogs/fragments/7542-irc-logentries-ssl.yml, plugins/callback/logentries.py, plugins/modules/irc.py
The irc module and the log_entries callback were still using it.
irc module
log_entries callback
=> ssl.wrap_socket() was removed in Python 3.12

plugins/modules/ansible_galaxy_install.py
Forgot to remove mentions of the no longer supported Ansible 2.9 in the docs.
=> ansible_galaxy_install: forgot to remove mentions of the no longer supported Ansible 2.9 in the docs

changelogs/fragments/6572-nmcli-add-support-loopback-type.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
This PR adds support for device type ``loopback`` in nmcli module, as it was requested in #6572
With new devices type you should be able to add new ip addresses and dns entries to lo interface. There no way to change mtu since loopback connection doesn't have ``802-3-ethernet.mtu`` parameter yet.
=> Add support for loopback type in nmcli module

plugins/doc_fragments/alicloud.py, plugins/doc_fragments/auth_basic.py, plugins/doc_fragments/dimensiondata.py, plugins/doc_fragments/dimensiondata_wait.py, plugins/doc_fragments/emc.py, plugins/doc_fragments/hwc.py, plugins/doc_fragments/ibm_storage.py, plugins/doc_fragments/influxdb.py, plugins/doc_fragments/ipa.py, plugins/doc_fragments/keycloak.py, plugins/doc_fragments/lxca_common.py, plugins/doc_fragments/oneview.py, plugins/doc_fragments/online.py, plugins/doc_fragments/openswitch.py, plugins/doc_fragments/oracle.py, plugins/doc_fragments/oracle_wait_options.py, plugins/doc_fragments/purestorage.py, plugins/doc_fragments/rackspace.py, plugins/doc_fragments/scaleway.py, plugins/doc_fragments/utm.py, plugins/doc_fragments/vexata.py
Adhere to full sentences, spelling acronyms uppercase, etc.
Also remove obvious things like "Python >= 2.6" or "Python >= 2.7" (the collection requires Python 2.7+ anyway), and remove references to ancient Ansible versions like Ansible 2.5 for some changes.
doc fragments
=> Clean up doc fragments a bit

changelogs/fragments/7151-fix-keycloak_authz_permission-incorrect-resource-payload.yml, plugins/modules/keycloak_authz_permission.py
Fixes #7151 
keycloak_authz_permission
Before change, debug message was:
```
"msg": "Could not create update permission view.members.permission.group.f90a06ec-3d04-4e2e-8e43-e4faec6dc4a8 for client fc7011b1-ec2d-4e94-a53b-9f0a76b292c3 in realm testrealm: HTTP Error 500: Internal Server Error"
```
After change, task completes successfully:
```
PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
=> Set resources payload as a list

changelogs/fragments/7550-irc-use_tls-validate_certs.yml, plugins/modules/irc.py
This PR currently contains #7542, I will rebase once that's merged.
Right now the `irc` module does **not** validate TLS certificates. This adds an option which allows to change that behavior.
Also the `use_ssl` option should rather be called `use_tls`. I've renamed it and added the old name `use_ssl` as an alias.
irc
=> irc module: add validate_certs, rename use_ssl to use_tls (keeping use_ssl as an alias)

plugins/modules/ini_file.py
Fixes #6708.
(Originally `section` was required and `null`/`none` had to be passed to tell the module not to use a section. This stopped working with ansible-core 2.15.0 since then `null`/`none` are no longer accepted for `str` options; see #6404.)
ini_file
=> ini_file: documentation for 'section' to stop mentioning that null can be passed

changelogs/fragments/7535-terraform-fix-multiline-string-handling-in-complex-variables.yml, plugins/modules/terraform.py
Terraform needs newlines to be replaced with `\\n` when passing multiline strings inside complex variables.
terraform
When passing a multiline string inside a complex variable, like the `ca_certificate` in the example playbook below, Terraform complains.
```
- name: "Terraform
hosts: "localhost"
tasks:
- name: "Run Terraform apply"
community.general.terraform:
project_path: "terraform"
variables:
postgresql:
host: "{{ hostvars['db'].ansible_fqdn }}"
port: 5432
ca_certificate: "{{ hostvars['db'].postgresql_tls_cert }}"
state: "present"
complex_vars: true
```
Before the change, the approximate command run by the module is:
```paste below
terraform -var 'postgresql={host=\"hostname.test\",port=5432,ca_certificate=\"-----BEGIN CERTIFICATE-----\n[…]\n-----END …
```
=> fix(modules/terraform): handle multiline strings correctly in complex variables

tests/integration/targets/lookup_passwordstore/tasks/main.yml
Currently the Debian package is broken, see https://github.com/gopasspw/gopass/issues/2728
passwordstore lookup
=> CI: temporarily skip passwordstore tests on Debian/Ubuntu

changelogs/fragments/7538-add-krbprincipalattribute-option.yml, plugins/modules/keycloak_user_federation.py, tests/unit/plugins/modules/test_keycloak_user_federation.py
Adding option for krbPrincipalAttribute in `keycloak_user_federation`
Partially because we might need to change it, but also this is needed for idempotency
modules/keycloak_user_federation
=> [keycloak_user_federation]: Adding option krbPrincipalAttribute

changelogs/fragments/7437-proxmox-inventory-add-exclude-nodes.yaml, changelogs/fragments/7461-proxmox-inventory-add-exclude-nodes.yaml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
This pull request enables users of the proxmox inventory source to exclude the proxmox-nodes from the ansible-host list at will. The default of the new setting `exclude_nodes` is to include nodes, so it it should stay compatible to the current usage. If `exclude_node` is true, nodes will not be added at all to the inventory. This option is implicitly mutually exclusive with composite-vars for nodes, since, well if you exclude nodes, you don't need composite vars for them.
**TODO**: I could only test this implementation on my single-node proxmox cluster, I'd be glad if someone else could verify this implementation on a multi-node-cluster.
This PR fixes #6714 .
!component =plugins/inventory/proxmox.py
before:
```
ubuntu@adm: ansible-inventory -i test.proxmox.yaml …
```
=> Add option to proxmox dynamic inventory to exclude nodes

changelogs/fragments/7569-infiniband-slave-support.yml, plugins/modules/nmcli.py
Infiniband can be a slave too
- nmcli.py
Without this change, attempting to enslave an infiniband interface "pretends" to do something, but never actually works.
=> infiniband can be a slave too

changelogs/fragments/7588-ipa-config-new-choice-passkey-to-ipauserauthtype.yml, plugins/modules/ipa_config.py
I have added passkey choice into ipauserauthtype.
Fixes #7580 
ipa_config
```paste below
```
=> ipa_config: add passkey choice to ipauserauthtype

changelogs/fragments/7589-ipa-config-new-choices-idp-and-passkey-to-ipauserauthtype.yml, plugins/modules/ipa_user.py
I have added idp and passkey choices into ipauserauthtype.
Fixes #7581 
ipa_user
```paste below
```
=> ipa_user: add idp and passkey choices to ipauserauthtype

.github/BOTMETA.yml, plugins/modules/git_config.py, plugins/modules/git_config_info.py, tests/integration/targets/git_config_info/aliases, tests/integration/targets/git_config_info/files/gitconfig, tests/integration/targets/git_config_info/meta/main.yml, tests/integration/targets/git_config_info/tasks/error_handling.yml, tests/integration/targets/git_config_info/tasks/get_all_values.yml, tests/integration/targets/git_config_info/tasks/get_multi_value.yml, tests/integration/targets/git_config_info/tasks/get_simple_value.yml, tests/integration/targets/git_config_info/tasks/main.yml, tests/integration/targets/git_config_info/tasks/setup.yml, tests/integration/targets/git_config_info/tasks/setup_file.yml, tests/integration/targets/git_config_info/tasks/setup_global.yml, tests/integration/targets/git_config_info/vars/main.yml
Based on this discussion https://github.com/ansible-collections/community.general/pull/7260#discussion_r1403314182
this  new module for only reading out git configs is now created.
git_config_info
The new module is only here to read out git configs and deprecate those functionalities in the `git_config` module
=> New module git config info

changelogs/fragments/000-redhat_subscription-dbus-on-7.4-plus.yaml, plugins/modules/redhat_subscription.py, tests/unit/plugins/modules/test_redhat_subscription.py
subscription-manager does not provide a D-Bus interface in versions of RHEL 7 older than 7.4.
Fixes #7622
=> redhat_subscription: use D-Bus registration on RHEL 7 only on 7.4+

changelogs/fragments/7540-proxmox-update config.yml, plugins/modules/proxmox.py
Add an update parameter to the proxmox module allowing you to update the configuration of an already created container. This was already possible for VMs in the proxmox_kvm module.
Fixes #7145 
proxmox
```paste below
```
=> Allow update of proxmox container configuration

changelogs/fragments/7600-proxmox_kvm-hookscript.yml, plugins/modules/proxmox_kvm.py
Fixes #7600 add hookscript parameter to proxmox_kvm module.
proxmox_kvm
The parameter was present in PROXMOX VE as early as [April 2019](https://forum.proxmox.com/threads/how-to-use-new-hookscript-feature.53388/).
It had been added to the `proxmox.py` module in #245 on May 18, 2020 but not to `proxmox_kvm.py`.
This PR adds it.
=> fix #7600 add hookscript parameter to proxmox_kvm

tests/integration/targets/cmd_runner/action_plugins/_unsafe_assert.py, tests/integration/targets/cmd_runner/aliases, tests/integration/targets/cmd_runner/tasks/test_cmd_echo.yml
Follow-up to #7625. This was more complex than I hoped for, since passing in evaluated things to `assert` always triggers the error. So I had to replace assert by a simplified version of it that "makes safe" the conditions passed. Making an `AnsibleUnsafeText` safe is a bit tricky, the easiest way I found was splitting it into chars, converting each char to an integer with `ord()`, and converting it back with `chr()`. Not very elegant, but works (at least for the texts that this test has to handle).
cmd_runner
=> Fix and re-enable cmd_runner tests

tests/integration/targets/lookup_passwordstore/tasks/main.yml
Ref: https://github.com/gopasspw/gopass/issues/2728
Ref: https://github.com/gopasspw/gopass/releases/tag/v1.15.11
passwordstore lookup tests
=> passwordstore tests: re-enable gopass on Debian-like systems

changelogs/fragments/7564-onepassword-lookup-case-insensitive.yaml, plugins/lookup/onepassword.py, tests/unit/plugins/lookup/onepassword_common.py, tests/unit/plugins/lookup/onepassword_fixtures/v2_out_01.json
This was a regression in behavior when adding support for op v2.
Fixes #6000 
`plugins/lookup/onepassword.py`
=> onepassword lookup - Make section and field case insensitive

changelogs/fragments/7641-fix-keycloak-api-client-to-quote-properly.yml, plugins/module_utils/identity/keycloak/keycloak.py
fix: #6515 
Currently, Keycloak API client uses [urllib.parse.quote](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) when building URLs with path parameters, but it does not handle '/' (slash) by default. This PR makes it handle properly.
keycloak_*
=> Fix Keycloak API client to quote '/' properly

changelogs/fragments/7626-redfish-info-add-boot-progress-property.yml, plugins/module_utils/redfish_utils.py
Adding the BootProgress field to redfish_info systems properties. This should expose things like LastState to determine if the host reported booting into OS OR if there were boot failures/issues. This will be available on hosts running Redfish 1.13+ based on the DMTF documentation and should prove useful for checking the boot state/status of hosts post-reboot/reset.
redfish_info
```paste below
"BootProgress": {
"LastState": "OSRunning"
},
```
=> add BootProgress property to redfish_info

changelogs/fragments/lxd-instance-not-found-avoid-false-positives.yml, plugins/connection/lxd.py
lxd: avoid false positives in "instance not found" detection in the lxd connection plugin
lxd connection plugin
before:
```
fatal: [my-rpi-399]: UNREACHABLE! => {
"msg": "instance not found: my-rpi-399",
"unreachable": true
}
```
after:
```
fatal: [my-rpi-399]: FAILED! => {
"ansible_facts": {},
"failed_modules": {
"ansible.legacy.setup": {
"failed": true,
"module_stderr": "/bin/sh: 1: /usr/bin/python3: not found\nError: Command not found\n",
"module_stdout": "",
"msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
"rc": 127
}
},
"msg": "The following modules failed to execute: ansible.legacy.setup\n"
}
```
=> Lxd instance not found fix false positives

changelogs/fragments/7645-Keycloak-print-error-msg-from-server.yml, plugins/module_utils/identity/keycloak/keycloak.py
Print error message from keycloak following a HttpError
keycloak_user
keycloak_role
```
- name: add user
community.general.keycloak_user:
auth_keycloak_url: "http://localhost:8080/auth"
auth_username: "admin"
auth_password: "secret"
realm: "externe"
username: "sx5admin"
first_name: "sx5admin"
last_name: "sx5admin"
credentials:
- type: password
value: "weak"
groups:
- name: "SX5DepotUtilisateurs"
```
```
TASK [sx5-depot : add user] *******************************************************************************************************************************************************************************************
failed: [localhost] (item={'keycloak_url': 'http://localhost:8080', 'keycloak_user': 'admin', 'keycloak_password': 'secret', 'keycloak_realm': 'master', …
```
=> Keycloak print error msg from server

changelogs/fragments/7653-fix-cloudflare-lookup.yml, plugins/modules/cloudflare_dns.py
Cloudflare uses space and not tab when you search for SSHFP records
Fixes: #7652 
Cloudflare does not use tabs but space in SSHFP records when you search for them
cloudflare_dns
```paste below
```
=> Change tab to space in SSHFP requests

changelogs/fragments/7676-lvol-pvs-as-list.yml, plugins/modules/lvol.py, tests/integration/targets/lvol/aliases, tests/integration/targets/lvol/meta/main.yml, tests/integration/targets/lvol/tasks/main.yml, tests/integration/targets/lvol/tasks/setup.yml, tests/integration/targets/lvol/tasks/teardown.yml, tests/integration/targets/lvol/tasks/test_pvs.yml
I've modified the ``pvs`` argument's type to list (of str) of the ``lvol`` module to provide a consistent interface with the ``lvg`` module.
I consider this as a minor change as the current playbooks are not affected by this change due to the nature of the list type handling in the core ``AnsibleModule``.
Fixes #7504
``lvol``
=> lvol: Change ``pvs`` argument type to list (of str)

.azure-pipelines/azure-pipelines.yml
For some reason FreeBSD 13.1 is failing in CI.
https://dev.azure.com/ansible/community.general/_build/results?buildId=97978&view=logs&j=1bf9ea86-1ae4-50f8-a658-c30224b24a2f&t=5ef134f3-dd8b-5e8c-c39d-91226d8bb08d
CI
=> Deactivate FreeBSD 13.1 in CI

.github/BOTMETA.yml, docs/docsite/extra-docs.yml, docs/docsite/rst/guide_alicloud.rst, docs/docsite/rst/guide_online.rst, docs/docsite/rst/guide_packet.rst, docs/docsite/rst/guide_scaleway.rst, tests/sanity/extra/botmeta.py
These were taken from https://github.com/ansible/ansible-documentation/tree/3f12228c79f2e1aafd52e3f9be15444a4746ec3e/docs/docsite/rst/scenario_guides and adjusted to reality.
I deleted the parts about the Alicloud modules that do not exist in community.general (I guess they exist in https://github.com/alibaba/alibaba.alicloud/, but since that collection was never published to Galaxy, I do not see a reason to reference it) and the Packet dynamic inventory script (that lives here: https://github.com/ansible-community/contrib-scripts/blob/main/inventory/packet_net.py).
scenario guides
=> Add Alicloud, Online, Packet, and Scaleway scenario guides

changelogs/fragments/7703-ssh_config_add_keys_to_agent_option.yml, plugins/modules/ssh_config.py, tests/integration/targets/ssh_config/tasks/options.yml
New feature to set AddKeysToAgent option via ssh_config module.
Fixes #4802 
ssh_config
The change allows to set AddKeysToAgent option to either yes or no.
```paste below
```
=> ssh_config: Add add_keys_to_agent option

changelogs/fragments/7704-ssh_config_identities_only_option.yml, plugins/modules/ssh_config.py, tests/integration/targets/ssh_config/tasks/options.yml
New feature to set IdentitiesOnly option via ssh_config module.
Fixes #4801
ssh_config
The change allows to set IdentitiesOnly option to either yes or no.
=> Add ssh_config module option for identities_only

changelogs/fragments/7577-irc-tls.yml, changelogs/fragments/7578-irc-tls.yml, plugins/modules/irc.py
Ref: https://github.com/ansible-collections/community.general/pull/7575#discussion_r1402534853
Ref: https://github.com/ansible-collections/community.general/pull/7542#issuecomment-1817513525
I'm not sure whether this should be backported to stable-8 or not. If it is backported, that should only be done some time after the 8.1.0 release, so that the chance that users can use both `use_tls` and `validate_certs` is higher.
irc
=> irc: deprecate default 'false' for validate_certs and use_tls

plugins/modules/proxmox.py
Per issue [6027](https://github.com/ansible-collections/community.general/issues/6027), disk and storage should not be used together, and changes to the API make it so "disk" should be formatted like "<storage>:<size in gb>".
Documentation edited to reflect this new behavior.
```paste below
```
=> Updated documentation to reflect new behaviour

plugins/modules/consul.py, plugins/modules/manageiq_provider.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.17.txt
The consul and the manageiq_provider modules have a bunch of undocumented module options. Make sure that they at least show up in the documentation, and that it's clear they need more docs.
consul
=> Add documentation stubs for undocumented module options

plugins/modules/mail.py
In this playbook, the timeout parameter is set to 10 seconds, which will make Ansible attempt to establish a connection to the mail server, and if it takes longer than 10 seconds, the operation will time out.
community.general.mail
=> using timeout parameter within community.general.mail module

plugins/doc_fragments/onepassword.py, plugins/lookup/onepassword.py
Use `OP_SERVICE_ACCOUNT_TOKEN` environment variable as the default `service_account_token` when available.
This allows for a more concise developer experience:
```yaml
tasks:
- debug: msg={{ lookup('community.general.onepassword', 'secret', field='username', vault='my-vault', service_account_token=...) }}
- debug: msg={{ lookup('community.general.onepassword', 'secret', field='username', vault='my-vault') }}
```
- `plugins/lookup/onepassword.py`
=> 🔐 Load `OP_SERVICE_ACCOUNT_TOKEN` from ENVs

changelogs/fragments/7754-fixed-payload-format.yml, plugins/modules/statusio_maintenance.py
Changes the REST API Payload format to work with the current status.io API
There was no known bugfix issue for this. I discovered it this week and found a fix.
bugfixes:
- community.general.statusio_maintenance - fix error caused by incorrectly formed api data payload. was raising ``Failed to create maintenance: HTTP Error 400: Bad Request`` caused by bad data type for date/time and deprecated dict keys.
community.general.statusio_maintenance
- API dates and times are expecting string but original module provided list type.  Author added a step to turn the  list of strings into a list of list items, containing one string each.  I removed that step and correctly parse the strings into the payload.
The current status.io API requires a combined infrastructure ID, in the …
=> Fixed payload format

changelogs/fragments/7740-add-message-id-header-to-mail-module.yml, plugins/modules/mail.py
Add Message-ID header to emails sent with the mail module (mandatory to be accepted by some mail servers; such as Gmail)
=> mail module: add Message-ID header

changelogs/fragments/7698-improvements-to-keycloak_realm_key.yml, plugins/modules/keycloak_realm_key.py
This PR makes the following improvements to the `keycloak_realm_key` module:
- adds support for RSA enc key usage `rsa-enc`
- adds support for an additional 8 key algorithms
- fixes a bug where the user must specify a certificate (no longer required)
- removes `no_log` for certificate since this is not sensitive information
module: `keycloak_realm_key`
Tested against Keycloak `v22.0.4` API.
=> improvements to the keycloak_realm_key module

.github/BOTMETA.yml, plugins/filter/from_ini.py, tests/integration/targets/filter_from_ini/tasks/main.yml, tests/integration/targets/filter_from_ini/vars/main.yml
Adding a new filter: `from_ini`, which allows conversion of INI content to a dictionary.
This comes in handy when reading an INI file on a managed node is required without using `ansible.builtin.fetch` (which would be required when using the lookup `ansible.builtin.ini`), which would in most cases return a `changed` status (without `changed_when` of course`).
Fixes #4107
`from_ini`
First time contribution, please go easy on me! 🙂
I didn't see any unit tests for other filters, and therefore I didn't add any. I oriented myself on other filters with regards to documentation, copyright and license strings.
Please let me know if something is missing!
=> Adding a new filter: from_ini, which allows conversion of INI content to a dictionary

tests/unit/requirements.txt
It uses type hinting.
(The failures only happen on stable-6 and stable-7.)
unit tests
=> CI: python-memcached 1.60 needs Python 3.6+

plugins/modules/cloudflare_dns.py
Manual backport of #7773 to stable-7.
cloudflare_dns
=> [stable-7] cloudflare_dns: announce removal of SPF support (#7773)

.github/BOTMETA.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_realm_rolemapping.py, tests/integration/targets/keycloak_group_rolemapping/README.md, tests/integration/targets/keycloak_group_rolemapping/aliases, tests/integration/targets/keycloak_group_rolemapping/tasks/main.yml, tests/integration/targets/keycloak_group_rolemapping/vars/main.yml
For my Keycloak setup I need to be able to map realm roles into groups. Until now this collection does not support this.
`keycloak_realm_rolemapping`
This is a continuation of #5384 which unfortunately was not merged.
=> Add keycloak_realm_rolemapping module to map realm roles to groups

changelogs/fragments/7746-raw_post-without-actions.yml, plugins/modules/xcc_redfish_command.py
Implemented support for resource post without specifying any actions.
This change is useful for adding users, alert recipients, etc, using raw_post.
The behavior of the module is not affected by the changes made. 
xcc_redfish_command
This has been tested on Lenovo ThinkSystem SR630 V2 BMC Version: 3.81 and Lenovo ThinkSystem SR650 BMC Version: 9.87
See the following example:
INVENTORY:
```
all:
hosts:
xzansible-test:
ansible_host: 1.2.3.4
ansible_user: USERID
ansible_password: PASSW0RD
post task for poweron server(with action in resource_uri):
- name: PowerOn server
community.general.xcc_redfish_command:
category: Raw
command: PostResource
baseuri: "1.2.3.4"
username: "USERID"
password: "PASSW0RD"
resource_uri: …
```
=> Implemented raw_post without actions

.github/BOTMETA.yml, plugins/modules/proxmox_node_info.py, tests/integration/targets/proxmox/tasks/main.yml
Restarted PR due to erroneous update/p…
Adds a module to retrieve basic information about Proxmox nodes. Design is based on existing proxmox_domain_info module
Fixes #7686 
proxmox_node_info
```paste below
```
=> Add proxmox_node_info module

.github/BOTMETA.yml, plugins/modules/dnf_config_manager.py, tests/unit/plugins/modules/test_dnf_config_manager.py
This enables Ansible to enable and disable repos with `dnf config-manager` using the repo IDs.
There has been community discussion surrounding this gap (the config-manager plugin won't be supported by the `ansible.builtin.dnf` module):
- https://github.com/ansible/ansible/issues/46963#issuecomment-1320976197
- https://www.reddit.com/r/ansible/comments/10muq0k/please_help_me_with_best_practices_in_my_first/
The Ansible [yum_repository](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html) module does not cover this use case since you are required to provide a repository URL. However, `dnf config-manager` only requires a repository ID to function.
`dnf_config_manager`
I believe that the `community.general` collection …
=> Add dnf_config_manager module

.azure-pipelines/azure-pipelines.yml
Looks like it was removed from FreeBSD's side.
CI
=> Remove FreeBSD 12.4 from CI

.github/BOTMETA.yml, plugins/lookup/github_app_access_token.py, tests/unit/plugins/lookup/test_github_app_access_token.py, tests/unit/requirements.txt
This enable us to use github app to generate github access token. This access token can be used for regular git commands as shown in the examples
Using github app to authenticate instead of a private key that is tied to a user provides a lot of flexibility to an organisation
- free up a paid seat for deployment user
- better control around user depature events
`github_app_access_token`
=> Add github_app_access_token lookup plugin

changelogs/fragments/7723-ipa-pwpolicy-update-pwpolicy-module.yml, plugins/modules/ipa_pwpolicy.py, tests/unit/plugins/modules/test_ipa_pwpolicy.py
Freeipa 4 add support more options in password policies `maxrepeat`, `maxsequence`, `dictcheck`, `usercheck`, `gracelimit`
With this feature we can set these options for our password policies.
- Refactoring
ipa_pwpolicy
[link to freeipa document about pwpolicy options](https://freeipa.readthedocs.io/en/ipa-4-9/api/pwpolicy_add.html)
=> ipa: ipa_pwpolicy update pwpolicy module

changelogs/fragments/7789-keycloak-user-federation-custom-provider-type.yml, changelogs/fragments/keycloak-user-federation-custom-provider-type.yml, plugins/modules/keycloak_user_federation.py
Removes the restriction from the `keycloak_user_federation` module that `providerId` can only be `ldap`, `kerberos`, or `sssd`.
`keycloak_user_federation`
Restricting the options for this fields prevents being able to manage custom federation adapters.
=> Allow custom providerId in keycloak_user_federation

changelogs/fragments/7765-mail-message-id.yml, plugins/callback/mail.py, plugins/modules/mail.py
Follow-up to #7740.
CC @sbocahu @parsa97
mail module
mail callback
=> mail module/callback: allow to configure the Message-ID header's domain name

changelogs/fragments/7791-proxmox_kvm-state-template-will-check-status-first.yaml, plugins/modules/proxmox_kvm.py
=> proxmox_kvm - state:template will check if template exists first (#7791)

tests/unit/requirements.txt
This makes the redis Python library fail. Happens only on devel though...
unit tests
=> CI: for some reason async-timeout doesn't seem to get installed on Python 3.11

tests/unit/requirements.txt
Backport of #7811 to stable-8.
unit tests
=> [stable-8] CI: for some reason async-timeout doesn't seem to get installed on Python 3.11

tests/unit/requirements.txt
Backport of #7811 to stable-7.
unit tests
=> [stable-7] CI: for some reason async-timeout doesn't seem to get installed on Python 3.11

tests/integration/targets/timezone/tasks/main.yml
They currently fail:
https://dev.azure.com/ansible/community.general/_build/results?buildId=101086&view=logs&j=89290267-74d5-5b3e-330d-ba0f2945add4&t=0ecc9edb-08fd-5c6e-50b9-4c9e0e2c0b70
Might be related to the dbus related changes.
timezone
=> Disable timezone tests on Arch Linux

changelogs/fragments/7797-ipa-fix-otp-idempotency.yml, plugins/modules/ipa_otptoken.py, tests/unit/plugins/modules/test_ipa_otptoken.py
ipa_data is return `ipatokendisable` in `boolean` format and the module expects it as a string
this behavior causes a lack of idempotency and the `get_diff` module will fail in the second run.
`ipa_otptoken`
=> ipa_otptoken: fix wrong return value string to bool

tests/integration/targets/setup_tls/files/ca_certificate.pem, tests/integration/targets/setup_tls/files/ca_certificate.pem.license, tests/integration/targets/setup_tls/files/ca_key.pem, tests/integration/targets/setup_tls/files/ca_key.pem.license, tests/integration/targets/setup_tls/files/client_certificate.pem, tests/integration/targets/setup_tls/files/client_certificate.pem.license, tests/integration/targets/setup_tls/files/client_key.pem, tests/integration/targets/setup_tls/files/client_key.pem.license, tests/integration/targets/setup_tls/files/server_certificate.pem, tests/integration/targets/setup_tls/files/server_certificate.pem.license, tests/integration/targets/setup_tls/files/server_key.pem, tests/integration/targets/setup_tls/files/server_key.pem.license
Currently the reuse tests fail. Apparently `.pem` files are no longer scanned for copyright/license info.
reuse test
=> Make compatible with newer reuse versions

changelogs/fragments/7821-mssql_script-py2.yml, plugins/modules/mssql_script.py
`splitlines()` does not accept kwargs on Python 2, only positional parameters.
Fixes #7818.
mssql_script
=> mssql_script: make module Python 2 compatible

plugins/modules/pacman_key.py
Key ID is a mandatory parameter, and the examples which miss it are incorrect.
The documentation for pacman_key module includes incorrect examples which miss key ID. Given that key ID is a mandatory parameter (and the documentation clearly states this), the examples missing the key need to be fixed.
`modules/pacman_key`
=> Add missing `id` parameter into pacman_key documentation examples.

changelogs/fragments/7874-incus_connection_treats_inventory_hostname_as_literal_in_remotes.yml, plugins/connection/incus.py
Fixes #7874 
incus connection plugin
similar to the LXD plugin Fix.  https://github.com/ansible-collections/community.general/pull/4912
=> Fix: incus connection plugin treats inventory_hostname incorrectly in remote config

plugins/connection/lxd.py, plugins/inventory/lxd.py
It's been a long while that LXD knows how to manage VMs in addition to containers. Since it grew support for VMs, the more generic term of `instance` is used throughout the LXD documentation (https://documentation.ubuntu.com/lxd/en/latest/explanation/containers_and_vms/).
This PR updates the remaining occurrences of container to replace them with instance for clarity.
plugins/connection/lxd
plugins/inventory/lxd
=> Refer to LXD containers/VMs as instances

.github/BOTMETA.yml, plugins/modules/gitlab_milestone.py, tests/integration/targets/gitlab_milestone/README.md, tests/integration/targets/gitlab_milestone/aliases, tests/integration/targets/gitlab_milestone/defaults/main.yml, tests/integration/targets/gitlab_milestone/tasks/main.yml
A new Ansible module gitlab_milestone for creating, updating or deleting Gitlab project's and group's milestones.
`gitlab_milestone`
A new Ansible module `gitlab_milestone` for creating, updating or deleting GitLab project's and group's milestone resources utilizing [python-gitlab](https://python-gitlab.readthedocs.io/en/stable/) library. 
This work is based on previously available GitLab-related modules in the collection. 
Looking at the entire Ansible collection, there's no module that manipulates Gitlab project's and group's milestones.
=> New module: gitlab_milestone

changelogs/fragments/7870-homebrew-cask-installed-detection.yml, plugins/modules/homebrew.py, tests/integration/targets/homebrew/tasks/casks.yml, tests/integration/targets/homebrew/tasks/formulae.yml, tests/integration/targets/homebrew/tasks/main.yml
Use json output v2 to check if formulae and casks are installed
Fixes #864 
modules/homebrew
The current method to check if a cask or formulae is installed tries to detect a string (`Built from source` or `Poured from bottle`) piece in the output, but for casks the strings aren't present anymore (example below). The suggested solution for it is use the json output of the command to check the `installed` field that contains a list of installed versions for formulae or a installed string version for casks.
`brew info firefox` output
```
==> firefox: 121.0.1 (auto_updates)
https://www.mozilla.org/firefox/
/usr/local/Caskroom/firefox/121.0.1 (226B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/f/firefox.rb
==> Name
Mozilla Firefox
==> Description
Web …
```
=> Detection of already installed homebrew cask

tests/galaxy-importer.cfg
Disable the ansible-doc part of the galaxy-importer run of Zuul's third-party-check.
Should stop the constant failing of it.
CI
=> Zuul third-party-check: disable ansible-doc part of galaxy-importer

changelogs/fragments/7389-nmcli-issue-with-creating-a-wifi-bridge-slave.yml, plugins/modules/nmcli.py
Fixes #7389 
Hi, I've solved the problem from the issue #7389 changing the value of the 'connection.slave-type' in case of a 'wifi' type connection.
The parameter is now wired to 'slave_type' parameter from task, instead of 'bond'
in nmcli.py
```python
elif self.type == 'wifi':
options.update({
'802-11-wireless.ssid': self.ssid,
'connection.slave-type': self.slave_type if self.master else None,
})
```
nmcli module
```paste below
```
=> Fixes #7389 - NMCLI issue with creating a wifi bridge-slave

changelogs/fragments/7646-fix-order-number-detection-in-dn.yml, plugins/module_utils/ldap.py
Assume that if a string of digits occurs between curly braces anywhere in the DN, that this is an order number. The sequence does not necessarily have to occur after an equals sign. Fixes #7646.
module_utils/ldap.py
This fixes behaviour when the `xorder_discovery` parameter is set to `auto` (default).
=> Simplify regex for identifying order number in DN (#7646)

tests/integration/targets/filesize/tasks/sparse.yml
4 TB does not work on the Alpine VMs for some reason (File too large / cannot seek: Invalid argument). This causes nightly tests to fail for some days now.
filesize
=> filesize: use 2 TB instead of 4 TB in sparse file tests

tests/integration/targets/filesize/tasks/sparse.yml
=> [stable-7] filesize: use 2 TB instead of 4 TB in sparse file tests (#7935)

tests/integration/targets/filesize/tasks/sparse.yml
=> [stable-8] filesize: use 2 TB instead of 4 TB in sparse file tests (#7935)

tests/integration/targets/filesize/tasks/sparse.yml
=> [stable-6] filesize: use 2 TB instead of 4 TB in sparse file tests (#7935)

changelogs/fragments/7843-proxmox_kvm-update_unsafe.yml, plugins/modules/proxmox_kvm.py
Add parameter `update_unsafe` to avoid limitations when updating dangerous values.
proxmox_kvm
This simply allows to override the limits present on specific config options during `update`.
=> proxmox_kvm - new param to support unsafe updates

CHANGELOG.md, CHANGELOG.md.license, README.md, changelogs/config.yaml
Uses https://github.com/ansible-community/antsibull-changelog/pull/139 to render the changelog both as RST and MarkDown. References the MarkDown version from README since GitHub stopped rendering the RST version.
changelog
=> [stable-8] Add MarkDown changelog and use it by default

CHANGELOG.md, CHANGELOG.md.license, CHANGELOG.rst, README.md, changelogs/config.yaml
Uses https://github.com/ansible-community/antsibull-changelog/pull/139 to render the changelog both as RST and MarkDown. References the MarkDown version from README since GitHub stopped rendering the RST version.
changelog
=> [stable-7] Add MarkDown changelog and use it by default

CHANGELOG.md, CHANGELOG.md.license, CHANGELOG.rst, README.md, changelogs/config.yaml
Uses https://github.com/ansible-community/antsibull-changelog/pull/139 to render the changelog both as RST and MarkDown. References the MarkDown version from README since GitHub stopped rendering the RST version.
changelog
=> [stable-6] Add MarkDown changelog and use it by default

CHANGELOG.md, CHANGELOG.md.license, README.md, changelogs/config.yaml
Uses https://github.com/ansible-community/antsibull-changelog/pull/139 to render the changelog both as RST and MarkDown. References the MarkDown version from README since GitHub stopped rendering the RST version.
changelog
=> Add MarkDown changelog and use it by default

.github/BOTMETA.yml, plugins/callback/default_without_diff.py, tests/integration/targets/callback_default_without_diff/aliases, tests/integration/targets/callback_default_without_diff/tasks/main.yml
Helps with https://github.com/ansible-community/ara/issues/535.
default_without_diff
=> Add default_without_diff callback

changelogs/fragments/7963-fix-terraform-diff-absent.yml, plugins/modules/terraform.py
We used `terraform plan` to get the diff outputs, but it seems the module doesn't create a plan when the state is `absent`. Therefore, in this change, we will create a Terraform plan if the state is `absent` and `diff_mode` or `check_mode` is `True`.
Additionally, we will ignore the diff if there are no `resource_changes` in the TF plan. This is necessary when the state is absent and there are no resources to destroy.
Fix #7958 
terraform
=> terraform: fix diff when state is absent

changelogs/fragments/7919-onepassword-fieldname-casing.yaml, plugins/lookup/onepassword.py, tests/unit/plugins/lookup/onepassword_common.py, tests/unit/plugins/lookup/onepassword_fixtures/v2_out_05.json, tests/unit/plugins/lookup/onepassword_fixtures/v2_out_05.json.license
fixes #7918
community.general.onepassword lookup plugin
=> fixes #7918 - onepassword lookup fails if field name contains uppercase letters and section is specified

changelogs/fragments/7847-gitlab-issue-title.yml, plugins/modules/gitlab_issue.py
Title is an absent filter into python-gitlab library.
Fixes #7846 
`gitlab_issue`
=> gitlab_issue: use search instead of title

changelogs/fragments/7956-adding-releases_events-option-to-gitlab_hook-module.yaml, plugins/modules/gitlab_hook.py
Adding support for Release Events trigger on gitlab_hook module.
Release Events trigger is defined in GitLab documentation https://docs.gitlab.com/ee/api/projects.html#hooks
gitlab_hook
=> Adding releases events option to gitlab_hook module

changelogs/fragments/pkgin.yml, plugins/modules/pkgin.py
pkgin module raises sporadic exceptions and spurious "changed" status instead of "ok".
The reason is that modern "pkgin" can produce extra text lines beside the final "nothing to do.". We ignore those extra lines.
pkgin
```paste below
```
=> Pkgin fixes

changelogs/fragments/7976-add-mssql_script-transactional-support.yml, plugins/modules/mssql_script.py
Added transactional(rollback/commit) support to mssql_script module via optional boolean param 'transaction'
community.general.mssql_script
- Added optional Boolean parameter 'transaction' to set the transactional mode. Since it's an optional parameter, no impact on existing users of this module.
- If transactional mode is requested, start a transaction and commit the change only if the script succeed else rollback the transaction.
- If transactional mode is not requested (default behavior of module), automatically commit the change.
- It is a non-breaking change and very helpful in case we run multiple UPDATE/INSERT queries for different tables in a single script. This ensures data consistency and reduce data cleanup in case our script fails.
=> Added transactional(rollback/commit) support to mssql_script module

changelogs/fragments/7970-fix-cargo-path-idempotency.yaml, plugins/modules/cargo.py
There is a problem when using the optional 'path' parameter. The initial installation works fine, but when running the module again the get_installed function, which is supposed to check the installation state does not use the parameter, thus a new installation is attempted, this again is registered by cargo install itself, but leads to a false 'changed' status, breaking ansibles' idempotency.
A similar problem occurs when removing packages.
This fix makes the get_installed function aware of the optional 'path' parameter.
cargo
=> cargo: use the correct path when checking installation status fixing idempotency issue.

changelogs/fragments/7951-fix-redfish_info-exception.yml, plugins/module_utils/redfish_utils.py
While using the `redfish_info` module against some HPE hardware I encountered a variety of uncaught exceptions. After tracing it back I found these two methods to be the culprit. As they have a variety of syntax and logical errors.
redfish
It is worth noting that these methods and their inclusion in the `all` `commands` to the `Chassis` `category` of the `redfish_info` module does result in attempting to get information from OEM/Vendor specific extensions in a module which seems to otherwise attempt to only cover the generic redfish interface.
Additionally, due to the way these methods have been implemented, they both return a single value even when multiple chassis uris have a matching api command to return min fan speed and thermal configuration. I've left that …
=> Fix errors in hpe specific get methods

plugins/modules/apk.py
Fixes https://github.com/ansible-collections/community.general/issues/7990
apk
https://github.com/ansible-collections/community.general/issues/7990 encountered behavior, where apk was not idempotent. This was because they specified the packages to install as
```
name: "ca-certificates, less, ncurses-terminfo-base, krb5-libs, libgcc, libintl, libssl1.1, libstdc++, tzdata, userspace-rcu, zlib, icu-libs, tar"
```
which got parsed as:
```
"available": false,
"name": [
"ca-certificates",
" less",
" ncurses-terminfo-base",
" krb5-libs",
" libgcc",
" libintl",
" libssl1.1",
" libstdc++",
" tzdata",
" userspace-rcu",
" zlib",
" icu-libs",
" tar"
],
"no_cache": true,
"repository": null,
"state": "present",
"update_cache": false,
"upgrade": …
```
=> Correct apk docu to not include spaces in package name

changelogs/fragments/7996-Add templating support to Icinga2 Inventory.yml, plugins/inventory/icinga2.py
This PR adds templating support to Icinga2 inventory plugin.
Fixes #7074 
icinga2.py inventory
With this pr, the url, user and password parameters support Jinja2 templating.
```YAML
plugin: community.general.icinga2
url: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=path/to/my/secret:endpoint') }}"
user: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=path/to/my/secret:user') }}"
password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=path/to/my/secret:password') }}"
host_filter: \"linux\" in host.groups
validate_certs: false  # only do this when connecting to localhost!
inventory_attr: display_name
```
=> Add templating support to Icinga2 Inventory

changelogs/fragments/7717-prevent-modprobe-error.yml, plugins/modules/modprobe.py
Fixes #7717.
The error reported is as follows:
```
failed: [k8s07] (item=ip_vs_lc) => {"ansible_loop_var": "item", "changed": false, "item": "ip_vs_lc", "module_stderr": "Traceback (most recent call last):
File \"<stdin>\", line 107, in <module>
File \"<stdin>\", line 99, in _ansiballz_main
File \"<stdin>\", line 47, in invoke_module
File \"/opt/bin/pypy3/lib/pypy3.9/runpy.py\", line 213, in run_module
return _run_module_code(code, init_globals, run_name, mod_spec)
File \"/opt/bin/pypy3/lib/pypy3.9/runpy.py\", line 97, in _run_module_code
_run_code(code, mod_globals, init_globals,
File \"/opt/bin/pypy3/lib/pypy3.9/runpy.py\", line 87, in _run_code
exec(code, run_globals)
File \"/tmp/ansible_community.general.modprobe_payload_nper0d8d/ansible_community.general.modprobe_payload.zip/ansible_c …
```
=> modprobe: Avoid FileNotFoundError when directories don't exist.

changelogs/fragments/7994-bitwarden-session-arg.yaml, plugins/lookup/bitwarden.py, tests/unit/plugins/lookup/test_bitwarden.py
At the moment, the bitwarden lookup plugins requires that BW_SESSION env var is defined.
`bw` cli allows to pass that key via an argument: `--session <session>    Pass session key instead of reading from env.`
This PR add the support to provides the key from an option and provide it to the cli args.
community.general.bitwarden - lookup
```paste below
```
=> feat(lookup/bitwarden): add support for "session" arg

changelogs/fragments/7790-gitlab-runner-api-pagination.yml, plugins/module_utils/gitlab.py, plugins/modules/gitlab_deploy_key.py, plugins/modules/gitlab_group_members.py, plugins/modules/gitlab_group_variable.py, plugins/modules/gitlab_hook.py, plugins/modules/gitlab_instance_variable.py, plugins/modules/gitlab_project_badge.py, plugins/modules/gitlab_project_variable.py, plugins/modules/gitlab_runner.py, plugins/modules/gitlab_user.py
python-gitlab 4.0.0 removed support for the `as_list=False` parameter. This functionality is now available as `iterator=True`.
Without this change, the module actually only retrieves the first 20 results, which can lead to non-idempotent behavior, such as registering a runner again.
gitlab_runner
I am using community.general 8.1.0, python-gitlab 4.2.0 and a self-hosted instance of GitLab,
and was trying to register a new instance runner. Initial registration was successful, but if I run the playbook again,
a new runner (with the same description value) would be registered.
When I ran again using `--check`, I get `AttributeError: 'bool' object has no attribute '_attrs'`
(which is a separate bug that I will write up), but `module_stderr` also includes:
UserWarning: …
=> fix(modules/gitlab_runner): Use correct argument to list all runners

changelogs/fragments/7953-proxmox_kvm-fix_status_check.yml, plugins/modules/proxmox_kvm.py
Following up on https://github.com/ansible-collections/community.general/issues/7817 and the changes suggested by OP.
Fixes #7817
proxmox_kvm
Simply implemented changes suggested by OP, for more details see original issue #7817
=> [FIX] proxmox_kvm: fetch vm status from node-specific API endpoint to ensure fresh state

changelogs/fragments/lxd-instances-api-endpoint-added.yml, plugins/modules/lxd_container.py
Updates the `lxd_container` module to work with the new LXD API which deprecates `/1.0/containers` and `/1.0/virtual-machines` and adds `/1.0/instances`. It tries to keep backwards compatibility with a try and catch compared to detecting the API version then determining which API endpoint to use.
> It also adds support for Incus
Fixes  #7853
`lxd_container`
=> Updates `lxd_container` to support new LXD API

plugins/modules/ejabberd_user.py
This replaces the wrong command of `ejabberdctl deregister` with the proper command `ejabberdctl unregister`.
The proper command is [used within the code](https://github.com/ansible-collections/community.general/blob/74c15c12418bf2f7e1dcac1a88657c8aefaeeb6d/plugins/modules/ejabberd_user.py#L162). Only the class documentation was incorrect.
ejabberd_user
=> ejabberd_user: Fix class documentation

changelogs/fragments/8048-fix-homebrew-module-error-reporting-on-become-true.yaml, plugins/modules/homebrew.py
Fixes #8047, where using `become: true` with homebrew would not give a useful error message, by raising the error thrown by brew command.
homebrew
```yaml
become: true
tasks:
- name: Install Git
community.general.homebrew:
name: git
state: present
- name: Install ZSH
community.general.homebrew:
name: zsh
state: present
```
```console
% sudo ansible-playbook dev.yaml -e 'ansible_python_interpreter=/opt/homebrew/bin/python3.10'
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
PLAY [localhost] ******************************************************************************************************************* …
```
=> fix(homebrew): give correct error message when become true used

.github/BOTMETA.yml, plugins/lookup/merge_variables.py, tests/integration/targets/lookup_merge_variables/runme.sh, tests/integration/targets/lookup_merge_variables/test_all_hosts.yml, tests/integration/targets/lookup_merge_variables/test_inventory_all_hosts.yml, tests/unit/plugins/lookup/test_merge_variables.py
This modifies the lookup plugin merge_variables. It's adding an all_hosts mode which allows to merge variables which have their pieces distributed across multiple hosts.  
I would like to give an example where this is useful. Lets start with:
* A generic database host without any further database/user configuration deployed via a role that is also able to maintain databases, users etc.
* Another host running a web service which is using the database service running on the remote host
How could you provide the configuration for the service to the database? The current merge_variables lookup plugin does not help here, because it's limited to the variables of the same host.
* You could add the configuration directly to the database host.
* Either as host_vars or via a custom group
* You may …
=> feat(lookup/merge_variables): Add all hosts mode to collect configuration across multiple hosts

changelogs/fragments/8057-pam_limits-check-mode.yml, plugins/modules/pam_limits.py
=> pam_limits: do not create file in check mode when it does not exist

.azure-pipelines/azure-pipelines.yml
Ref: https://forum.ansible.com/t/ansible-test-added-macos-14-3-and-deprecated-macos-13-2/4330
CI
=> CI: add macOS 14.3 for devel, move 13.2 to stable-2.16

changelogs/fragments/8091-consul-token-fixes.yaml, plugins/module_utils/consul.py, plugins/modules/consul_token.py, tests/integration/targets/consul/tasks/consul_token.yml
Fixes #8089
consul_token
```paste below
```
=> Fix consul_token usage without accessor_id.

changelogs/fragments/8073-ldap-attrs-diff.yml, plugins/modules/ldap_attrs.py
This adds support for the  `--diff` mode for the `ldap_attrs` module. For the other `ldap` modules this does not really make sense, as `ldap_search` is read-only and for `ldap_entry` there is only a change if the entry is not there at all (so the state is quite clear).
We would like to use this kind of feature for internal use of the module.
`ldap_attrs`
Right now, the module does not search for all available attributes at the same time. The `--diff` mode therefore has difficulties if we are only adding/deleting single values of a multi value attribute to detect what was there before and what would be the final state.
With `--exact`, we're replacing everything, therefore this issue is not present there. 
I'm not sure about the policy on this repo, whether a …
=> Add --diff support for ldap_attrs module

tests/integration/targets/pacman/tasks/locally_installed_package.yml
Make sure the `debugedit` package is installed for building a package.
Ref: https://dev.azure.com/ansible/community.general/_build/results?buildId=106709&view=logs&j=89290267-74d5-5b3e-330d-ba0f2945add4&t=0ecc9edb-08fd-5c6e-50b9-4c9e0e2c0b70
pacman integration tests
=> Fix pacman tests in CI

changelogs/fragments/aix_filesystem-crfs-issue.yml, plugins/modules/aix_filesystem.py
Change the crfs logic and fields, since empty options and order seem to be an issue.
this quick fix seems to solve it
Empty fields seem to cause an issue with the crfs command. Also the -d device tag needs to be the second flag.
aix_filesystem
The aix_filesystem crfs was giving this error:
``` json
"stderr": "Usage: crfs -v Vfs {-g Volumegroup | -d Device} -m Mountpoint\n\t[-u Mountgroup] [-A {yes|no}] [-t {yes|no}] [-p {ro|rw}]\n \t[-l Logpartitions] [-n nodename] [-a Attribute=Value]",
"stderr_lines": [
"Usage: crfs -v Vfs {-g Volumegroup | -d Device} -m Mountpoint",
"\t[-u Mountgroup] [-A {yes|no}] [-t {yes|no}] [-p {ro|rw}]",
" \t[-l Logpartitions] [-n nodename] [-a Attribute=Value]"
],
```
=> Aix filesystem crfs issue

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/filter_jc/aliases, tests/integration/targets/iso_extract/aliases, tests/integration/targets/pkgng/tasks/freebsd.yml
Ref: https://forum.ansible.com/t/ansible-test-added-freebsd-13-3-14-0-and-deprecated-13-2/4503
CI
=> CI: Add FreeBSD 13.3 and 14.0 for devel, move FreeBSD 13.2 to stable-2.16

.azure-pipelines/azure-pipelines.yml
Ref: https://forum.ansible.com/t/ansible-test-added-alpine-3-19-and-deprecated-3-18/4508
CI
=> CI: Move Alpine 3.18 docker to stable-2.16, add Alpine 3.19 docker, bump Alpine VM to 3.19

changelogs/fragments/8075-optional-space-around-section-names.yaml, plugins/modules/ini_file.py, tests/integration/targets/ini_file/tasks/main.yml, tests/integration/targets/ini_file/tasks/tests/07-section_name_spaces.yml
ini_file - Support optional spaces between section names and their surrounding brackets
Some ini files have spaces between some of their section names and the brackets that enclose them. This is documented in the `openssl.cnf(5)` man page. In order to manage files such as `openssl.cnf` with ini_file before now, one would have to include spaces in the section name like this:
```yaml
section: ' crypto_policy '
option: Options
value: UnsafeLegacyRenegotiation
```
This change implements matching section headers with such optional spaces, removing the need to include those spaces in the task's `section:` parameter. Existing tasks using the workaround above will continue to work, even in cases where spaces in section headers are subsequently removed.
ini_file
Here's an …
=> ini_file - support optional spaces around section names

changelogs/fragments/8029-iptables-state-restore-check-mode.yml, plugins/modules/iptables_state.py, tests/integration/targets/iptables_state/tasks/main.yml, tests/integration/targets/iptables_state/tasks/tests/02-partial-restore.yml
Fixes https://github.com/ansible-collections/community.general/issues/7463
iptables_state
This PR first attempted to reproduce the behavior observed in https://github.com/ansible-collections/community.general/issues/7463 through integration tests. iptables-save doesn't work in docker, so this was tested against the azure pipeline through this PR, please excuse the commit spam.
https://github.com/ansible-collections/community.general/commit/a58bc16f2fb9ef4e5e60346abad4474db6d4933a was able reproduce the issue in https://github.com/ansible-collections/community.general/issues/7463 based on incomplete iptables-save files. Initially, all tables are empty and uninitialized, which will make iptables-save return nothing for them.
For example when …
=> Fix check mode in iptables_state for incomplete iptables-save files along with integration tests

changelogs/fragments/8013-bitwarden-full-collection-item-list.yaml, plugins/lookup/bitwarden.py, tests/unit/plugins/lookup/test_bitwarden.py
At the moment the lookup plugin allows to fetch items matching a mandatory search value.
It will be useful to retrieve the full item list for a given collection.
This PR allows to fetch all items of a given collection id, by letting `search_value` optional when `collection_id` is provided.
community.general.bitwarden - lookup
- `bw` cli documentation: https://bitwarden.com/help/cli/#list
=> feat(lookup/bitwarden): add support for fetching all items from a collection

changelogs/fragments/8118-fix-bond-slave-honoring-mtu.yml, plugins/modules/nmcli.py
The bond-slave type should honor the request
MTU value.
It's not possible to set MTU on bond-slave today
```paste below
```
=> Fix bond-slave honoring MTU

changelogs/fragments/8038-proxmox-startup.yml, plugins/modules/proxmox.py
Currently all containers that are created using this module start at the same time at system boot. In order to be able to reflect service dependencies and spread initial startup load proxmox supports the configuration of a startup parameter. This pull request adds the option to configure startup behavior of lxc containers. It works well in conjunction with onboot and allows to set startup order, startup delay and shutdown delay.
Changelog Fragment
- proxmox - adds ``startup`` parameters for configuring startup order, startup delay and shutdown delay.
proxmox
```
sample usage:
startup: 
- order=10
- up=50
- down=20
```
=> Added startup configuration option

changelogs/fragments/inventory-rce.yml, plugins/inventory/cobbler.py, plugins/inventory/gitlab_runners.py, plugins/inventory/icinga2.py, plugins/inventory/linode.py, plugins/inventory/lxd.py, plugins/inventory/nmap.py, plugins/inventory/online.py, plugins/inventory/opennebula.py, plugins/inventory/proxmox.py, plugins/inventory/scaleway.py, plugins/inventory/stackpath_compute.py, plugins/inventory/virtualbox.py, plugins/inventory/xen_orchestra.py
This PR marks (almost) all data set by inventory plugins as unsafe to avoid potential remote code executions on the controller.
Ref: https://www.die-welt.net/2024/03/remote-code-execution-in-ansible-dynamic-inventory-plugins/
Ref: https://forum.ansible.com/t/remote-code-execution-in-ansible-dynamic-inventory-plugins/4332
=> inventory plugins: make data obtained from remote unsafe

changelogs/fragments/inventory-rce.yml, plugins/inventory/cobbler.py, plugins/inventory/gitlab_runners.py, plugins/inventory/icinga2.py, plugins/inventory/linode.py, plugins/inventory/lxd.py, plugins/inventory/nmap.py, plugins/inventory/online.py, plugins/inventory/opennebula.py, plugins/inventory/proxmox.py, plugins/inventory/scaleway.py, plugins/inventory/stackpath_compute.py, plugins/inventory/virtualbox.py, plugins/inventory/xen_orchestra.py
Manual backport of #8098 to stable-6.
There have been some conflicts in plugins/inventory/cobbler.py, the version in stable-6 had a lot less options and set a lot less host vars. The changes for the remaining code were applicable without conflicts.
=> [stable-6] inventory plugins: make data obtained from remote unsafe

changelogs/fragments/8158-gitlab-version-check.yml, plugins/module_utils/gitlab.py, plugins/modules/gitlab_issue.py, plugins/modules/gitlab_label.py, plugins/modules/gitlab_milestone.py
Some GitLab modules crash if python-gitlab isn't installed since they access `gitlab.__version__` before checking whether python-gitlab is there.
This PR adds a generic method to check for a minimal version that is always run after checking the presence of python-version and uses it in these modules.
Ref: https://forum.ansible.com/t/attributeerror-nonetype-object-has-no-attribute-version/4611
gitlab_issue
gitlab_label
gitlab_milestone
=> gitlab modules: do not crash if python-gitlab isn't there

changelogs/fragments/8169-lxml.yml, plugins/modules/xml.py
lxml 5.1.1 includes https://github.com/lxml/lxml/commit/eba79343d0e7ad1ce40169f60460cdd4caa29eb3, which breaks the xml module since it assumes that `etree._ElementStringResult` exists.
On platforms that install lxml via pip, like macOS and RHEL 9, this was breaking the nightly tests (https://dev.azure.com/ansible/community.general/_build/results?buildId=107937&view=results).
xml
=> xml: make module work with lxml 5.1.1

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml, README.md, tests/sanity/ignore-2.18.txt, tests/sanity/ignore-2.18.txt.license
Ref: https://forum.ansible.com/t/ansible-core-devel-bumped-to-2-18-0-dev0-stable-2-17-branch-created/4695
CI
=> CI: add stable-2.17, bump devel to 2.18, move stable-2.14 from AZP to GHA

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml, README.md
Ref: https://forum.ansible.com/t/ansible-core-devel-bumped-to-2-18-0-dev0-stable-2-17-branch-created/4695
CI
=> CI: rename devel to stable-2.17, move stable-2.14 from AZP to GHA

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/lookup_lmdb_kv/test.yml
Ref: https://forum.ansible.com/t/ansible-core-devel-drops-support-for-python-3-7/4736
CI
=> CI: ansible-core devel removed Python 3.7 support, no longer allows 'vars:' with lists

plugins/modules/lxd_container.py
linuxcontainers.org has phased out LXC/LXD support. This edit reflects part of it in the docs.
This is related to #8161 
lxd_containers
=> updated lxd_container.py docs

changelogs/fragments/8175-get_ipa_version_regex.yml, plugins/module_utils/ipa.py
Fix module_utils/ipa.py regex to parsing freeipa version
module_utils/ipa.py
Right regex for parsing
https://regex101.com/r/s2ecr6/1
=> module_utils/ipa.py: fix regex when parsing version

changelogs/fragments/8154-add-ovs-commands-to-nmcli-module.yml, plugins/modules/nmcli.py
Adding OpenvSwitch command support and documentation to the nmcli module
nmcli
```paste below
OpenvSwitch commands are supported by nmcli once the "NetworkManager-ovs" package is installed (included within the AppStream repo). Tested with OpenvSwitch version 3.3.0.
Added documentation in the header of the file. May or may not match the version release if the pull request is merged in - This may have to be manually changed.
```
=> Update nmcli.py to support OVS commands

changelogs/fragments/8194-redfish-add-multipart-to-capabilities.yml, plugins/module_utils/redfish_utils.py
Fixed #8194
```paste below
```
=> Redfish: add `Multipart` bool return value to `FirmwareUpdateCapabilities`

changelogs/fragments/8211-riak-admin-sub-command-support.yml, plugins/modules/riak.py
Newer riak kv  versions don't provide the riak-admin command anymore but use the 'admin' as an sub-command to the 'riak' command.
Example: 
```
||/ Name           Version       Architecture Description
+++-==============-=============-============-=================================
ii  riak           3.0.8-OTP22.3 amd64        Riak KV Database
dpkg -L riak|fgrep sbin
/usr/sbin
/usr/sbin/riak
```
riak
=> Support newer 'riak admin' sub-command beside legacy 'riak-admin' command

changelogs/fragments/8215-add-docker-v2-protocol.yml, plugins/modules/keycloak_client.py, plugins/modules/keycloak_clientscope.py, plugins/modules/keycloak_clienttemplate.py
This pull request introduces the addition of the "docker-v2" protocol support to the `keycloak_client`, `keycloak_clientscope`, and `keycloak_clienttemplate` modules within the community.general collection. The "docker-v2" protocol is a valid and supported option in Keycloak, which is crucial for configurations involving Docker registry authentication, among others. Fixes #8215.
- `keycloak_client`
- `keycloak_clientscope`
- `keycloak_clienttemplate` 
I have enhanced the `protocol` parameter across the `keycloak_client`, `keycloak_clientscope`, and `keycloak_clienttemplate` modules to include the "docker-v2" option. It's important to note that the existing protocol choices varied across different modules — some were limited to `['openid-connect', 'saml']`, while …
=> Add support for docker-v2 protocol in Keycloak modules

changelogs/fragments/puppet_lang_force.yml, plugins/module_utils/puppet.py, plugins/modules/puppet.py
The shell environment used forces by default the lang to be "C". This can result that puppet fails with the error message `invalid byte sequence in US-ASCII`.
Fixes #8000
puppet
=> puppet_utils: Do not force lang for cmd

changelogs/fragments/8222-datetime.yml, plugins/callback/loganalytics.py, plugins/callback/logstash.py, plugins/callback/splunk.py, plugins/callback/sumologic.py, plugins/module_utils/datetime.py, plugins/module_utils/scaleway.py, plugins/modules/cobbler_sync.py, plugins/modules/cobbler_system.py, plugins/modules/github_key.py, plugins/modules/imc_rest.py, plugins/modules/pagerduty.py, plugins/modules/pagerduty_change.py, plugins/modules/scaleway_compute.py, plugins/modules/scaleway_database_backup.py, plugins/modules/scaleway_lb.py, plugins/modules/statusio_maintenance.py, tests/unit/plugins/callback/test_loganalytics.py, tests/unit/plugins/callback/test_splunk.py
Python 3.12 deprecated `utcnow()` and `utcfromtimestamp()`.
various
=> Avoid deprecated utcnow()

.github/BOTMETA.yml, changelogs/fragments/8225-unsafe.yml, plugins/inventory/cobbler.py, plugins/inventory/gitlab_runners.py, plugins/inventory/icinga2.py, plugins/inventory/linode.py, plugins/inventory/lxd.py, plugins/inventory/nmap.py, plugins/inventory/online.py, plugins/inventory/opennebula.py, plugins/inventory/proxmox.py, plugins/inventory/scaleway.py, plugins/inventory/stackpath_compute.py, plugins/inventory/virtualbox.py, plugins/inventory/xen_orchestra.py, plugins/plugin_utils/unsafe.py
Ref: https://github.com/ansible-collections/community.general/issues/8212.
Closes #8212.
=> inventory plugins: make wrapping variables as unsafe smarter to avoid triggering an AWX bug

changelogs/fragments/8188-bitwarden-add-organization_id.yml, plugins/lookup/bitwarden.py, tests/unit/plugins/lookup/test_bitwarden.py
Currently, there is support to filter lookup results via `collection_id`, but not by `organization_id`.  
As both filter-options work the same, this was added.
bitwarden
Since the `bitwarden` lookup wraps the `bw` command line interface and this tool cannot filter by `organization_id` and `collection_id` simultaneously, this filter logic is implemented in this lookup instead.
=> bitwarden - add support for filtering by organization_id

changelogs/fragments/8126-filesystem-bcachefs-support.yaml, plugins/modules/filesystem.py, tests/integration/targets/filesystem/defaults/main.yml, tests/integration/targets/filesystem/tasks/main.yml, tests/integration/targets/filesystem/tasks/setup.yml
Add support for bcachefs to the filesystem module.
filesystem
Test playbook:
```yaml
---
vars:
img_file: /tmp/bcachefs.img
tasks:
- name: create 1GiB file
community.general.filesize:
path: "{{ img_file }}"
size: 1GiB
- name: create bcachefs filesystem on file
ansible.legacy.filesystem:
dev: "{{ img_file }}"
fstype: bcachefs
uuid: bfe441c5-93da-440b-8c9a-e807bc538abb
- name: create bcachefs filesystem on file (no changes)
ansible.legacy.filesystem:
dev: "{{ img_file }}"
force: False
fstype: bcachefs
- name: create bcachefs filesystem on file (force)
ansible.legacy.filesystem:
dev: "{{ img_file }}"
force: True
fstype: bcachefs
- name: resize 1GiB file to 2GiB
community.general.filesize:
path: "{{ img_file }}"
size: 2GiB
- name: resize bcachefs …
```
=> filesystem: add bcachefs support

changelogs/fragments/8223-keycloak_client-additional-normalizations.yaml, plugins/modules/keycloak_client.py
keycloak_client: Add sorted `defaultClientScopes` and `optionalClientScopes` to normalizations.
Without this code, `ansible-playbook --check --diff`will show changes because a unsorted list is diffed.
=> keycloak_client: add sorted defaultClientScopes and optionalClientScopes to normalizations

changelogs/fragments/8224-keycloak_realm-add-normalizations.yaml, plugins/modules/keycloak_realm.py
keycloak_realm: Add sorted `defaultClientScopes` and `optionalClientScopes` to normalizations.
keycloak_realm
Without this code, `ansible-playbook --check --diff`will show changes because a unsorted list is diffed.
It uses the same approach as for `keycloak_client` in https://github.com/ansible-collections/community.general/blob/6c8f949ba950309931d8931f4820b99707898850/plugins/modules/keycloak_client.py#L730
=> keycloak_realm: add normalizations for enabledEventTypes, and supportedLocales

changelogs/fragments/8236-portage-select-feature.yml, plugins/modules/portage.py
This patch permits to explicitly pass `--select=y` to portage, in order to tell it to write to world file. This is useful for users who setup Gentoo in a way that `oneshot` is the default (see original linked issue).
Fixes #6226
portage
One can setup Portage with `EMERGE_DEFAULT_OPTS="--oneshot"` to reproduce. Not passing `select` option to the module in a task will keep the default behavior (nothing is passed to portage, so whatever the user have set in their default Portage options, the behavior is the same). Passing `select:true` as module option will allow users to make portage write to world file if oneshot is the default for them in Portage (and does not break users where it's not the default). The new option is of course exclusive with `oneshot` module …
=> Add an explicit `select` option to `portage` module

changelogs/fragments/8153-java_cert-add-cert_content-arg.yml, plugins/modules/java_cert.py
Adding the ability to create a keystore using a certificate stored in the `cert_content` variable. 
Fixes #8034.
community.general.java_cert
=> java_cert: add cert_content argument

plugins/modules/flatpak.py, tests/integration/targets/flatpak/tasks/check_mode.yml, tests/integration/targets/flatpak/tasks/test.yml
Fixes #6563 by extending the allowed values of the `state` parameter to include `latest`. To do this, the `update_flat()` function is introduced which borrows the majority of its implementation from both the existing `install_flat()` and `remove_flat()` functions. The documentation and examples have been expanded describing what to expect when using `state=latest`.
=> Add support for state=latest to flatpak module

.github/BOTMETA.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_client_rolescope.py, tests/integration/targets/keycloak_client_rolescope/README.md, tests/integration/targets/keycloak_client_rolescope/aliases, tests/integration/targets/keycloak_client_rolescope/tasks/main.yml, tests/integration/targets/keycloak_client_rolescope/vars/main.yml
New Keycloak module for client roles scope administration
New Module/Plugin Pull Request
keycloak_client_rolescope
Role scope is used to control access to other clients' roles instead of using the 'Full scope allowed'. It's more secure to only send resource roles relevant to the current application and as the number of clients with their roles increases, some users might begin to have a problem with access tokens that are too large to be used as Bearer tokens.
=> Keycloak client role scope

changelogs/fragments/8257-ssh-config-hostkey-support-accept-new.yaml, plugins/modules/ssh_config.py
Fixes https://github.com/ansible-collections/community.general/issues/8177
ssh_config
As described in https://github.com/ansible-collections/community.general/issues/8177
> [OpenSSH 7.6](https://www.openssh.com/txt/release-7.6) introduced a new value accept-new for StrictHostKeyChecking which allows for automatically adding fingerprints for new hosts in ~/.ssh/know_hosts but still block the connection attempt if the fingerprint changes (eg. MITM attack).
This PR adds this value to the valid settings for `strict_host_key_checking`
=> Add accept-new as valid option for ssh_config host key checking

changelogs/fragments/8247-apt_rpm-latest.yml, plugins/modules/apt_rpm.py
Right now `state=present` acts like `state=latest`, which is not a great idea. This PR starts improving on the situation by adding two new states, `latest` and `present_not_latest`. The former is currently equivalent to `latest`, while the latter does what most users expect `present` to do: only install a package, but do not upgrade it.
The next step will be to deprecate `present`'s behavior, and then eventually change it to the one of `present_not_latest`.
Ref: #8217
apt_rpm
=> apt_rpm: add new states 'latest' and 'present_not_latest'

changelogs/fragments/8263-apt_rpm-install-check.yml, plugins/modules/apt_rpm.py
The for loop variable is `packages`, but the loop body uses `package`. This is obviously a typo, causing the loop to check the same package (from a previous `for` loop) multiple times.
apt_rpm
=> apt_rpm: fix package install check

changelogs/fragments/8226-mh-vardict.yml, plugins/module_utils/mh/mixins/vars.py, plugins/module_utils/mh/module_helper.py, plugins/modules/gconftool2.py, plugins/modules/kernel_blacklist.py, plugins/modules/opkg.py, plugins/modules/pipx.py, plugins/modules/xfconf.py, plugins/modules/xfconf_info.py, tests/integration/targets/module_helper/library/mstate.py
The objects in `plugins/module_utils/mh/mixins/vars.py` are set to be removed in community.general 10.0.0, and  the `ModuleHelper` class still depends on it.
This PR severs that dependency by making use of the more generic code in `plugins/module_utils/vardict.py`.
While this make look simple, there are many modules depending on `ModuleHelper` today, so we must be careful with the impact of this change.
plugins/module_utils/mh/module_helper.py
=> Change MH to use the module_utils.vardict.VarDict

tests/integration/targets/snap/aliases, tests/integration/targets/snap/tasks/main.yml, tests/integration/targets/snap/tasks/test_channel.yml
Testing `snap` is intrinsically heavier loaded than testing other "regular" modules. Thus, adding the `disabled` tag to its `aliases` file.
We can still run the test when needed.
snap
=> use smaller snap, add disabled to aliases

.github/BOTMETA.yml, changelogs/fragments/8289-python-runner.yml, plugins/module_utils/python_runner.py, tests/unit/plugins/module_utils/test_python_runner.py
`PythonRunner` is based on `CmdRunner` and it is designed to run `python` commands. It transparently handles virtualenvs.
plugins/module_utils/python_runner.py
=> PythonRunner: a command runner for python

changelogs/fragments/8285-apt_rpm-state-deprecate.yml, plugins/modules/apt_rpm.py
Second step for #8217.
apt_rpm
=> apt_rpm: deprecate behavior of state=present and state=installed

changelogs/fragments/8274-homebrew-force-formula.yml, plugins/modules/homebrew.py, tests/integration/targets/docker/handlers/main.yml, tests/integration/targets/docker/tasks/main.yml
Fixes #8274.
Some formulas have names that are also cask formulas (e.g. docker). When trying to install such a formula, brew prints a warning and returns a non-zero exit code. This causes Ansible to halt and report the failure. By allowing the task to set force_formula, we can sidestep this problem.
homebrew
=> homebrew: Add force_formula parameter to pass --formula to brew command

changelogs/fragments/8281-puppet-waitforlock.yaml, plugins/module_utils/puppet.py, plugins/modules/puppet.py, tests/unit/plugins/modules/test_puppet.yaml
Add support for the [waitforlock](https://www.puppet.com/docs/puppet/8/configuration#maxwaitforlock) puppet argument
Often the puppet module can fail on puppet runs if puppet is already running. Puppet has the option `--waitforlock` which ensures puppet will wait a specific amount of time for the lock to free before throwing an error. This PR adds support for this argument
Fixes #8281 
puppet
=> 8281: puppet waitforlock

tests/integration/targets/ejabberd_user/tasks/main.yml
They currently fail since one of the packages that `ejabberd` depends on has been removed from the Arch package repositories.
ejabberd
=> Disable ejabberd tests on Arch Linux

changelogs/fragments/7790-gitlab-runner-api-pagination.yml, plugins/module_utils/gitlab.py, plugins/modules/gitlab_deploy_key.py, plugins/modules/gitlab_group_members.py, plugins/modules/gitlab_group_variable.py, plugins/modules/gitlab_hook.py, plugins/modules/gitlab_instance_variable.py, plugins/modules/gitlab_project_badge.py, plugins/modules/gitlab_project_variable.py, plugins/modules/gitlab_runner.py, plugins/modules/gitlab_user.py
**This is a backport of PR https://github.com/ansible-collections/community.general/pull/7790 as merged into main (https://github.com/ansible-collections/community.general/commit/787fa4621763879dae26c57aaf0028941dcaaefc).**
python-gitlab 4.0.0 removed support for the as_list=False parameter. This functionality is now available as iterator=True.
Without this change, the module actually only retrieves the first 20 results, which can lead to non-idempotent behavior, such as registering a runner again.
gitlab_runner
I am using community.general 8.1.0, python-gitlab 4.2.0 and a self-hosted instance of GitLab,
and was trying to register a new instance runner. Initial registration was successful, but if I run the playbook again,
a new runner (with the same description …
=> [PR #7790/787fa462 backport][stable-7] fix(modules/gitlab_runner): Use correct argument to list all runners

changelogs/fragments/8303-fix-rendering-foreign-variables.yaml, plugins/lookup/merge_variables.py, tests/integration/targets/lookup_merge_variables/runme.sh, tests/integration/targets/lookup_merge_variables/test_cross_host_merge_inventory.yml, tests/integration/targets/lookup_merge_variables/test_cross_host_merge_play.yml, tests/unit/plugins/lookup/test_merge_variables.py
The changes in this MR address an issue when using the merge_variables lookup with the `groups` parameter to merge variables across different hosts.
In the current implementation there are two issues left:
1. It isn`t possible to use the `hostvars` Variable using `ansible -m debug` or the ansible-console whenever there was a merge_variable usage with filled `groups` parameter in the used inventory. The result is an exception.
2. When using merge_variables with the `groups` parameter filled it isn`t possible to use variables from other hosts that are unknown (not set, not derived from a group membership) to the host which is invoking merge_variables. The reason is that the context of the Jinja Wrapper is bound the host that is executing the lookup.
I have created an small [example …
=> bug(lookup/merge_variables): Fix rendering foreign variables

.github/BOTMETA.yml, changelogs/fragments/add-run0-become-method.yml, plugins/become/run0.py, tests/unit/plugins/become/test_run0.py
This PR adds support for `run0` as a become method.
`run0` will be available in [systemd 256](https://github.com/systemd/systemd/releases/tag/v256-rc1), see https://mastodon.social/@pid_eins/112353324518585654  
`community.general.run0`
=> add systemd run0 as a become method

changelogs/fragments/8320-keycloak_user_federation-fix-diff-krbPrincipalAttribute.yaml, plugins/modules/keycloak_user_federation.py
`krbPrincipalAttribute` is supposed to have an empty string as a valid value.
https://github.com/ansible-collections/community.general/blob/bc609d74a023e3ea3b2c5621c1ea8de2b5d3ee17/plugins/modules/keycloak_user_federation.py#L346
Without this bugfix, an `ansible-playbook ... --check --diff`run will always show an empty string in the diff if you pass en empty string to `config.krbPrincipalAttribute`.
```
TASK [kc1 - realm-1 - test-2 - Create or update a Keycloak kerberos enabled user_federation] ********************************************************************************************************************************************
--- before
+++ after
@@ -17,6 +17,7 @@
"importEnabled": "false",
"kerberosRealm": "EXAMPLE.NET",
"keyTab": "/mnt/ad2",
+        "krbPrincipalAttribute": "", …
```
=> keycloak_user_federation: fix diff of empty `krbPrincipalAttribute`

plugins/doc_fragments/consul.py, plugins/modules/consul_policy.py, plugins/modules/consul_role.py, plugins/modules/consul_session.py, plugins/modules/consul_token.py
Subset of #8334 that's not related to proxmox.
Simply removes the `version_added` from the consul docs fragment, since that docs fragment should rather be used by modules which later on add the docs fragment.
consul docs fragment
=> Move version_added for consul docs fragment to modules

changelogs/fragments/8355-keycloak-idp-sanitize.yaml, plugins/modules/keycloak_identity_provider.py, tests/integration/targets/keycloak_identity_provider/tasks/main.yml
The sanitize function did not properly sanitize the client secret.
keycloak_identity_provider
```paste below
```
=> Fix sanitize for keycloak_identitiy_provider.

.github/BOTMETA.yml, plugins/callback/timestamp.py, tests/integration/targets/callback_timestamp/aliases, tests/integration/targets/callback_timestamp/tasks/main.yml, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt
This PR introduce new callback plugin to show simple timestamp for each header line.
This plugin reduces the number of `*`'s in the header by the number of characters in the timestamp, and display the timestamp on the far right.
On the output screen of an AWX job, a timestamp appears in each header by default. This PR implements this timestamp idea as a callback plugin.
There is a plugin that can be used for a similar purpose, [`ansible.posix.profile_tasks`](https://docs.ansible.com/ansible/latest/collections/ansible/posix/profile_tasks_callback.html), but it adds a new line for displaying the timestamps, which complicates the output.
The plugin in this PR is as simple as possible and provides only minimal information, so it is not at all obtrusive to keep it enabled at all times. …
=> feat: implement timestamp callback plugin to show simple timestamp for each header

changelogs/fragments/8290-gandi-livedns-personal-access-token.yml, plugins/module_utils/gandi_livedns_api.py, plugins/modules/gandi_livedns.py, tests/integration/targets/gandi_livedns/tasks/create_record.yml, tests/integration/targets/gandi_livedns/tasks/update_record.yml
- feat(gandi_livedns): support personal access tokens (fixes #7639)
- fix(gandi_livedns): fix unsafe conditionals in tests
gandi_livedns
Should be self-explanatory.
=> feat(gandi_livedns): support personal access tokens

changelogs/fragments/8383-deprecate-gitlab-basic-auth.yml, plugins/module_utils/gitlab.py
This PR deprecates basic auth for GitLab modules, since this auth method has been removed from GitLab a **long** time ago (in GitLab 9.5, released in August 2017, if I'm right).
It will allow to remove some specific code from `module_utils/gitlab.py` and enhance maintainability.
gitlab_project_badge
gitlab_hook
gitlab_label
gitlab_instance_variable
gitlab_project_access_token
gitlab_group_access_token
gitlab_merge_request
gitlab_branch
gitlab_project
gitlab_milestone
gitlab_runner
gitlab_protected_branch
gitlab_group_variable
gitlab_user
gitlab_group
gitlab_issue
Another PR will follow to remove this code in `community.general` v9.0.0
=> gitlab modules: deprecate basic auth method

changelogs/fragments/8363-opentelemetry-export-to-a-file.yml, plugins/callback/opentelemetry.py
Added support to store the exported spans in a file.
This is useful for adding UTs, as explained in https://github.com/open-telemetry/opentelemetry-python/blob/eef2015edd0d7c0a85840fd7bd1c7d57f1a8c2ee/opentelemetry-sdk/src/opentelemetry/sdk/trace/export/in_memory_span_exporter.py#L23-L27
For instance, I can now configure this plugin to run in isolation and validate it works as expected:
- https://github.com/v1v/otel-ansible-callback-plugin/blob/main/test_pytest.py
I don't know whether we could revisit https://github.com/ansible-collections/community.general/pull/4871 so I could try to add the UTs to this project, rather than using my proposal in https://github.com/v1v/otel-ansible-callback-plugin.
`plugins/callback/opentelemetry`
```paste below
```
=> feat(opentelemetry): support flag to export spans in a given file

changelogs/fragments/8373-honour-disable-logs.yaml, plugins/callback/opentelemetry.py
Workaround for https://github.com/ansible-collections/community.general/issues/8353
Let's skip storing large datasets if the logs are disabled. This should help with the existing memory issues, so users can disable the logs. While we can figure out how to fix the underlying issue with storing large datasets.
`plugins/callback/opentelemetry`
```paste below
```
=> fix(opentelemetry): avoid storing inmemory if logs are disabled

changelogs/fragments/8367-fix-close-span-if-no-logs.yaml, plugins/callback/opentelemetry.py
Fixes a regression caused by https://github.com/ansible-collections/community.general/pull/6531
So spans were not closed when sending logs were disabled.
`opentelemetry`
```paste below
```
=> fix(opentelemetry): close span even if no logs are sent

changelogs/fragments/polkit-become.yml, plugins/become/machinectl.py, plugins/become/run0.py
This PR:
- lints the `polkit` rule examples in the `machinectl` and `run0` become modules (https://standardjs.com/rules.html#rules)
- fixes the `polkit` rule example for the `run0` become module (missing `&&`) 
`machinectl`
`run0`
=> lint and fix polkit examples

changelogs/fragments/8373-honour-disable-logs.yaml, plugins/callback/opentelemetry.py
Manual backport of #8373 to stable-8.
=> [stabe-8] fix(opentelemetry): avoid storing inmemory if logs are disabled (#8373)

changelogs/fragments/8373-honour-disable-logs.yaml, plugins/callback/opentelemetry.py
Manual backport of #8373 to stable-7.
=> [stable-7] fix(opentelemetry): avoid storing inmemory if logs are disabled (#8373)

changelogs/fragments/8379-verbose-mode-pkg5.yml, plugins/modules/pkg5.py
Updated params for community.general.pkg5 with 'verbose' mode (defaults to False, which is existing silent execution behavior) to allow users to toggle verbose to True, which disables the '-q' flag that was hardcoded in the original module
Fixes: #8379
Add a simple boolean to enable the user of the pkg5 module to enable verbose mode, which removes the previously hardcoded -q flag from the command string.
pkg5
The existing module.run_command included the arguments -q hardcoded. I added a user-driven boolean that removes the '-q' if the user sets the flag to true
```
BEFORE:
"results": [
"\nA clone of SRU-11.4.45.0.1 exists and has been updated and activated.\nOn the next boot the Boot Environment be://rpool/11.4.68.0.1.164.2 will be\nmounted on '/'. Reboot when ready …
```
=> Add toggle for verbose logging to pkg5.py

changelogs/fragments/8199-added-usb-support-to-proxmox-module.yml, plugins/modules/proxmox_kvm.py
added usb support when managing proxmox kvm vms
proxmox_kvm
=> added usb support to proxmox module

changelogs/config.yaml
Use https://github.com/ansible-community/antsibull-changelog/pull/162.
Also harmonize changelog config, which means enabling FQCNs for new plugin/module mentions.
changelog
=> From now on automatically add period to new plugins in changelog, and use FQCNs

plugins/callback/yaml.py, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt
This PR adds `seealso` and `notes` for `community.general.yaml` callback plugin.
Since the new built-in parameter `result_format = yaml` for `ansible.builtin.default` callback plugin was introduced in ansible-core 2.13, most users now can get YAML output with the built-in functionality without having to use `community.general.yaml`.
This PR does not contain any changelog fragmen since this is a doc-only change.
yaml
Tested locally with:
```paste below
ansible-test sanity --docker -v plugins/callback/yaml.py
ansible-test integration --docker -v callback_yaml
```
=> docs: add seealso and notes for yaml callback plugin

changelogs/fragments/8411-locale-gen-vardict.yml, plugins/module_utils/django.py, plugins/module_utils/vardict.py, plugins/modules/cpanm.py, plugins/modules/gconftool2_info.py, plugins/modules/hponcfg.py, plugins/modules/kernel_blacklist.py, plugins/modules/locale_gen.py, plugins/modules/mksysb.py, plugins/modules/pipx_info.py, plugins/modules/snap.py, plugins/modules/snap_alias.py
Add
```
use_old_vardict = False
```
to the module.
Fixes #8410 
locale_gen
=> multiple modules: use new vardict in module

plugins/modules/lxd_container.py
Two small changes:
-  use APT module. The previous example would always return 'modified' 
- Remove Debian example. The example does not work anymore after https://linuxcontainers.org/ did drop LXD support.
trivial:
- Fix LXD container documentation after https://linuxcontainers.org/ did drop LXD support.
lxd_container
none
=> Update lxd_container.py documentation.

changelogs/fragments/8406-fix-homebrew-cask-warning.yaml, plugins/modules/homebrew.py, tests/integration/targets/homebrew/tasks/docker.yml
Instead of checking if there is an error message, which can also be a warning, we now check the return code.
This commit fixes #8229 #7044
Fixes #8229
Fixes #7044
homebrew
=> Fix the homebrew module failing because of warnings

changelogs/fragments/8403-fix-typeerror-in-keycloak-client.yaml, plugins/modules/keycloak_client.py
This fixes a TypeError in the keycloak_client module.
Longer description:
As `sanitize_cr` might be executed after `normalise_cr`, `result['attributes']` can be of type list and we run into:
> TypeError: list indices must be integers or slices, not str
`keycloak_client`
Full stack trace (keycloak_client.py got renamed to `mdz_keycloak_client.py`):
```
File "/root/.ansible/tmp/ansible-tmp-1716369175.8611605-165495-177683398669149/AnsiballZ_mdz_keycloak_client.py", line 107, in <module>
File "/root/.ansible/tmp/ansible-tmp-1716369175.8611605-165495-177683398669149/AnsiballZ_mdz_keycloak_client.py", line 99, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File …
```
=> keycloak_client: avoid TypeError if `result["attributes"]` is a list

changelogs/fragments/8402-add-diif-mode-openbsd-pkg.yml, plugins/modules/openbsd_pkg.py
Support diff-mode so we can see what changed.
openbsd_pkg
```
Supporting diff mode with check mode would be a bit more complicated so I left this alone for now.
```
=> Add partial diff support, not in check mode to openbsd_pkg

.github/BOTMETA.yml, plugins/doc_fragments/django.py, plugins/module_utils/django.py, plugins/modules/django_createcachetable.py, tests/unit/plugins/modules/test_django_createcachetable.py, tests/unit/plugins/modules/test_django_createcachetable.yaml
New module
django_createcachetable
=> django_createcachetable: new module

changelogs/fragments/8405-gitlab-remove-basic-auth.yml, plugins/module_utils/gitlab.py
This PR removes ability to authenticate against GitLab API using Basic Auth (deprecated in #8383).
**Note : This is a breaking change.**
gitlab_project_badge
gitlab_hook
gitlab_label
gitlab_instance_variable
gitlab_project_access_token
gitlab_group_access_token
gitlab_merge_request
gitlab_branch
gitlab_project
gitlab_milestone
gitlab_runner
gitlab_protected_branch
gitlab_group_variable
gitlab_user
gitlab_group
gitlab_issue
N/A
=> feat(gitlab modules): remove basic auth

changelogs/fragments/8431-galaxy-upgrade.yml, plugins/modules/ansible_galaxy_install.py, tests/integration/targets/ansible_galaxy_install/tasks/main.yml
Add upgrade feature.
Fixes #8351 
=> ansible_galaxy_install: add upgrade feature

changelogs/fragments/8051-Redfish-Wait-For-Service.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_command.py, plugins/modules/redfish_info.py
* Adds new command to check if a Redfish service is available
* Adds new option to manager reset operations to wait for the service to become available again after the reset
Fix #8051
~~I did not add a changelog fragment yet; will do that once I get some eyes on the design.~~
redfish_info, redfish_command
New "service available" command
```paste below
---
- hosts: all
vars:
baseuri: REDACTED
username: REDACTED
password: REDACTED
tasks:
- name: Check service availability
category: Service
command: CheckAvailability
register: redfish_results
- debug:
var: redfish_results
```
```
TASK [debug] …
```
=> Redfish: Add options to check the availability of the service

.github/BOTMETA.yml, plugins/filter/keep_keys.py, plugins/plugin_utils/keys_filter.py, tests/integration/targets/filter_keep_keys/aliases, tests/integration/targets/filter_keep_keys/tasks/keep_keys.yml, tests/integration/targets/filter_keep_keys/tasks/main.yml, tests/integration/targets/filter_keep_keys/vars/main.yml
SUMMARY
ansible.utils.keep_keys does not work properly. Fixing is not efficient.
ISSUE TYPE
New Module/Plugin Pull Request
COMPONENT NAME
community.general.keep_keys
This PR implements #8438
=> Feature filter keep_keys

changelogs/fragments/8453-git_config-deprecate-read.yml, plugins/modules/git_config.py
git_config_info has been added in community.general 8.1.0. It's time to disallow reading operations from git_config.
git_config
=> git_config: deprecate reading values

changelogs/fragments/8404-ipa_dnsrecord_sshfp.yml, plugins/modules/ipa_dnsrecord.py
Adds record-type 'SSHFP' support to the ipa_dnsrecord module
Since I need the PR number for the changelog fragment, I'll have to add it later
ipa_dnsrecord
```paste below
```
=> Add support for SSHFP records to ipa_dnsrecord module

changelogs/fragments/8440-allow-api-port-specification.yaml, plugins/doc_fragments/proxmox.py, plugins/module_utils/proxmox.py
Implements #8440 
modules_utils/proxmox.py
N/A -- see #8440
=> #8440 Allow for API Port to be specified when using proxmox_kvm

docs/docsite/helper/lists_mergeby/default-common.yml, docs/docsite/helper/lists_mergeby/default-recursive-true.yml, docs/docsite/helper/lists_mergeby/example-001.yml, docs/docsite/helper/lists_mergeby/example-001_vars/list3.yml, docs/docsite/helper/lists_mergeby/example-002.yml, docs/docsite/helper/lists_mergeby/example-002_vars/list3.yml, docs/docsite/helper/lists_mergeby/example-003.yml, docs/docsite/helper/lists_mergeby/example-004.yml, docs/docsite/helper/lists_mergeby/example-004_vars/list3.yml, docs/docsite/helper/lists_mergeby/example-005.yml, docs/docsite/helper/lists_mergeby/example-005_vars/list3.yml, docs/docsite/helper/lists_mergeby/example-006_vars/list3.yml, docs/docsite/helper/lists_mergeby/example-007.yml, docs/docsite/helper/lists_mergeby/example-007_vars/list3.yml, docs/docsite/helper/lists_mergeby/example-008.yml, docs/docsite/helper/lists_mergeby/example-008_vars/list3.yml, docs/docsite/helper/lists_mergeby/example-009.yml, docs/docsite/helper/lists_mergeby/example-009_vars/default-common.yml, docs/docsite/helper/lists_mergeby/example-009_vars/default-recursive-true.yml, docs/docsite/helper/lists_mergeby/example-009_vars/list3.yml, docs/docsite/helper/lists_mergeby/examples.yml, docs/docsite/helper/lists_mergeby/examples_all.rst.j2, docs/docsite/helper/lists_mergeby/extra-vars.yml, docs/docsite/helper/lists_mergeby/filter_guide_abstract_informations_merging_lists_of_dictionaries.rst.j2, docs/docsite/helper/lists_mergeby/list3.out.j2, docs/docsite/helper/lists_mergeby/playbook.yml, docs/docsite/rst/filter_guide_abstract_informations_merging_lists_of_dictionaries.rst
* Add subsections and improve formatting.
* Add example-009 'Merge single list'
* Adding links to module and plugin options in docs/docsite/helper/lists_mergeby
docs/docsite/rst/filter_guide_abstract_informations_merging_lists_of_dictionaries.rst
The commands created the RST file:
```bash
(env) > cd docs/docsite/helper/lists_mergeby
(env) > ansible-playbook playbook.yml -e @extra-vars.yml
```
=> Update docsite chapter "Merging lists of dictionaries"

changelogs/fragments/8464-redis-add-cluster-info.yml, plugins/modules/redis_info.py
Adds support for getting cluster information. It does not use, redis-py's [cluster_info()](https://redis-py.readthedocs.io/en/stable/commands.html#redis.commands.cluster.RedisClusterCommands.cluster_info) because I couldn't get it to work when the cluster is yet to be configured. Hence the `execute_command` which works in that case.
It's optional and can be invoked with adding `cluster: true` to the task:
```yaml
- name: Get server cluster information
community.general.redis_info:
cluster: true
```
And returns the additionnal data in the `cluster_info` variable alongside `info`.
- redis_info
=> feat(redis_info): add option to fetch cluster info

changelogs/fragments/8497-crypt.yml, plugins/modules/homectl.py, plugins/modules/udm_user.py
Now that ansible-core devel's ansible-test also tests with Python 3.13, in which the crypt standard library module has been removed, we have to do something about these two modules using that part of the standard library.
This PR makes the crypt import guarded and lets the module fail with an expressive error message. It would be better to get rid of the crypt usages, but that's for someone else...
Ref: https://github.com/ansible-collections/community.general/issues/4691
Ref: https://github.com/ansible-collections/community.general/issues/4690
homectl
udm_user
=> homectl, udm_user: guard crypt imports

.azure-pipelines/azure-pipelines.yml
It needs to be explicitly added for unit tests and for generic CI (that's currently disabled though).
CI
=> Add Python 3.13 to CI

changelogs/fragments/8471-proxmox-vm-info-network.yml, plugins/modules/proxmox_vm_info.py
Information of guests should include current network settings to support waiting on network settings when provisioning new machines. The methods for accessing the information are already present in the API and only need to be called.
The retrieval of network information can be enabled/disabled via new bool param network (default=false)
For qemu vms, agent must be enabled and running. Otherwise, a clear error message from the API is shown: 
`"msg": "Failed to retrieve QEMU VMs information: 500 Internal Server Error: QEMU guest agent is not running"`
For lxc containers, the information is always there.
proxmox_vm_info
Information of guests should include current network settings to support waiting on network settings when provisioning new machines. The methods for …
=> feat: proxmox_vm_info - add network information for guests

.github/BOTMETA.yml, changelogs/fragments/8445-feature-replace_keys.yml, plugins/filter/keep_keys.py, plugins/filter/remove_keys.py, plugins/filter/replace_keys.py, plugins/plugin_utils/keys_filter.py, tests/integration/targets/filter_replace_keys/aliases, tests/integration/targets/filter_replace_keys/tasks/fn-test-replace_keys.yml, tests/integration/targets/filter_replace_keys/tasks/main.yml, tests/integration/targets/filter_replace_keys/tasks/replace_keys.yml, tests/integration/targets/filter_replace_keys/vars/main.yml
Implement #8445
community.general.replace_keys
See related feature requests  #8438, #8442, and PR #8456, #8443
=> Feature filter replace_keys

changelogs/fragments/8489-fix-opennebula-inventory-crash-when-nic-has-no-ip.yml, plugins/inventory/opennebula.py
Fix OpenNebula inventory crash when NIC does not have IP.
Now matches IPv6 behaviour.
community.general.opennebula
When a NIC does not have an IP:
```shell
File "ansible/inventory/manager.py", line 292, in parse_source
plugin.parse(self._inventory, self._loader, source, cache=cache)
File "ansible-cm/plugins/inventory/opennebula.py", line 263, in parse
self._populate()
File "ansible-cm/plugins/inventory/opennebula.py", line 226, in _populate
servers = self._retrieve_servers(filter_by_label)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "ansible-cm/plugins/inventory/opennebula.py", line 210, in _retrieve_servers
server['v4_first_ip'] = self._get_vm_ipv4(vm)
^^^^^^^^^^^^^^^^^^^^^
File "ansible-cm/plugins/inventory/opennebula.py", line 154, in _get_vm_ipv4
return net['IP']
```
```paste below …
```
=> Fix OpenNebula inventory crash when NIC does not have IP

changelogs/fragments/8496-keycloak_clientscope-add-normalizations.yaml, plugins/modules/keycloak_clientscope.py
keycloak_clientscope: Add sorted `attributes` and `protocol_mappers` to normalizations.
keycloak_clientscope
Without this code, `ansible-playbook --check --diff`will show changes because a unsorted list is diffed.
It uses the same approach as for `keycloak_client` in https://github.com/ansible-collections/community.general/blob/6c8f949ba950309931d8931f4820b99707898850/plugins/modules/keycloak_client.py#L730
=> keycloak_clientscope: add normalizations for attributes and protocol_mappers

changelogs/fragments/8514-pacman-empty.yml, plugins/modules/pacman.py
=> pacman: do not fail if there is nothing to do

plugins/modules/proxmox_kvm.py
As per `qm(1)`, the force option requires `archive`. Add this information in the `proxmox_kvm` module so one will know they have to define `archive` when using `force`.
proxmox_kvm
=> proxmox_kvm: document that force requires archive

changelogs/fragments/8476-launchd-check-mode-changed.yaml, plugins/modules/launchd.py
`launchd` module always reported `changed: true` in check-mode. This PR fixes that problem.
`launchd`
=> Fix launchd check-mode to report changed correctly

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/django_manage/aliases, tests/integration/targets/ejabberd_user/tasks/main.yml, tests/integration/targets/homectl/aliases, tests/integration/targets/iptables_state/aliases, tests/integration/targets/iso_extract/aliases, tests/integration/targets/mqtt/tasks/main.yml, tests/integration/targets/odbc/aliases, tests/integration/targets/setup_java_keytool/vars/Ubuntu-24.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-24-py3.yml, tests/integration/targets/setup_snap/tasks/D-RedHat-9.4.yml, tests/integration/targets/ufw/aliases
Remaining parts excluded from #8534.
CI
=> Finish updating CI

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/filter_jc/aliases, tests/integration/targets/iso_extract/aliases, tests/integration/targets/pkgng/tasks/freebsd.yml
Ref: https://forum.ansible.com/t/ansible-test-devel-freebsd-14-0-remote-replaced-with-freebsd-14-1/6714
CI
=> CI: Replace FreeBSD 14.0 with 14.1; add 14.0 for stable-2.17

changelogs/fragments/8545-keycloak-clientscope-remove-id-on-compare.yml, plugins/modules/keycloak_clientscope.py
Stumbled upon this when using an older version of the plugin.
Originally had the issue with `consentRequired` which was fixed by Merge #8496 .
If the user supplies no `id` either in the `module.params.get('id')` or in one of the `module.params.get('protocol_mappers')`, the comparison will result in a diff detected, even though all other params might be identical.
Running a task multiple times with no `id`s set (Keycloak API then creates one) will now result in no change detected, improving idempotence checks.
commnity.general.keycloak_clientscope.py
The check on wether the task `changed` now normalizes the dicts `desired_clientscope` and `before_clientscope` to ignore all `id` fields on all levels, as they are not required to be set if a `name` has been set instead. …
=> keycloak_clientscope: ignore ids on diff check

changelogs/fragments/8517-cmd-runner-lang-auto.yml, plugins/module_utils/cmd_runner.py, plugins/modules/puppet.py
Supplying the special value `auto` to the `force_lang` parameter now has the effect of determining the locale to be used in the command execution by calling `ansible.module_utils.common.locale.get_best_parsable_locale()`.
=> cmd_runner - handle special value "auto" in param force_lang

plugins/lookup/merge_variables.py
The short description makes it sound like the plugin would only support matching a given suffix, while the actual description clarifies the actual matching capabilities (suffix, prefix or regular expression).
Update the short description accordingly.
merge_variables
=> merge_variables: correct misleading short description

changelogs/fragments/8444-fix-redfish-gen2-upgrade.yaml, plugins/module_utils/wdc_redfish_utils.py, tests/unit/plugins/modules/test_wdc_redfish_command.py
Fix to enable firmware upgrade on our Gen2 redfish based UltraStar Data102 platform.
wdc_redfish_command module
Firmware upgrade in case of Gen2 UltraStar Data102 platform is handled with the new firmware bundle format.
=> Fix to handle Redfish Gen2 Firmware upgrade

.azure-pipelines/azure-pipelines.yml
Apparently the packages are no longer available.
CI
=> Remove EOL'ed FreeBSD 13.2 from CI

changelogs/fragments/8613-redfish_utils-language.yaml, plugins/module_utils/redfish_utils.py
Fixes bug when Language is not exactly `en`
```
command: GetBiosRegistries
```
incorrectly returns 
```
if not rsp_uri:
msg = "Language 'en' not found in BIOS Attribute Registries location, URI: %s, response: %s"
```
example:
```
"bios_registries": {
"msg": "Language 'en' not found in BIOS Attribute Registries location, <snip>
"ret": false
}
```
Reproduce the issue:
bios_registry.yaml:
```
tasks:    
- delegate_to: localhost    
block:    
- name: Get Bios Registries    
community.general.redfish_info:    
<<: *redfish    
category: Systems    
command: GetBiosRegistries    
register: bios_data    
- ansible.builtin.debug: var=bios_data    
```
`ansible-playbook --inventory …
=> redfish_utils: fix language check

changelogs/fragments/8508-virtualbox-inventory.yml, plugins/inventory/virtualbox.py
Previously, we could separate the group string on the `/` char and consider each element to be distinct, top-level groups. This change implements the notion of nested groups and the use of the `,` char to split multiple groups.
Fixes #8508 
Update the parsing algorithm in the VirtualBox dynamic inventory. The update changes how groups are formed when considering VirtualBox VMs.
virtualbox inventory plugin
Before, we would split groups based only on the `/` characters to form top-level groups. This was problematic for users (like me) who want to use nested groups for better variable management.
This change introduces the ability to use nested groups using `/`, and different groups using `,`. This approach more closely aligns with the official VirtualBox …
=> Update VirtualBox Group parsing to align with documentation.

changelogs/fragments/8542-fix-proxmox-volume-handling.yml, plugins/modules/proxmox.py
Fixes #8407
Makes the creation of new volumes idempotent and adds new keys with better readability.
proxmox
Here is a sample playbook to test the new features/bug fixes:
```yaml
---
- name: Create LXC
become: false
vars_files:
- proxmox_credentials.yml
tasks:
- name: Create LXC
community.general.proxmox:
api_host: "{{ api_host }}"
api_user: "{{ api_user }}"
api_password: "{{ api_password }}"
node: "{{ node }}"
hostname: test-node
ostemplate: local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst
disk: local-lvm:8
register: create_res
- name: Update LXC config [new - create volumes]
community.general.proxmox:
api_host: "{{ api_host }}"
api_user: "{{ api_user }}"
api_password: "{{ api_password }}"
node: "{{ node …
```
=> Improve Proxmox volume handling

changelogs/fragments/8614-nsupdate-index-out-of-range.yml, plugins/modules/nsupdate.py
fallback to authority section of the response if there is no authoritative answer, instead of crashing
fixes #8612
nsupdate
```paste below
```
=> nsupdate: fix 'index out of range' error when changing NS records

plugins/modules/pip_package_info.py
Fixes #8572 (include pip >= 20.3b1 requirement in docs)
pip_package_info
See #8572 for the problem
=> #8572 - Updated docs to include pip >= 20.3b1 requirement

changelogs/fragments/8623-become-types.yml, plugins/become/doas.py, plugins/become/dzdo.py, plugins/become/ksu.py, plugins/become/machinectl.py, plugins/become/pbrun.py, plugins/become/pfexec.py, plugins/become/pmrun.py, plugins/become/sesu.py, plugins/become/sudosu.py
=> Type options of become plugins

changelogs/fragments/8626-lookup-types.yml, plugins/lookup/chef_databag.py, plugins/lookup/consul_kv.py, plugins/lookup/cyberarkpassword.py, plugins/lookup/dsv.py, plugins/lookup/etcd.py, plugins/lookup/filetree.py, plugins/lookup/hiera.py, plugins/lookup/onepassword.py, plugins/lookup/onepassword_doc.py, plugins/lookup/onepassword_raw.py, plugins/lookup/passwordstore.py, plugins/lookup/redis.py, plugins/lookup/shelvefile.py, plugins/lookup/tss.py
=> Type options of lookup plugins

changelogs/fragments/8646-fix-bug-in-proxmox-volumes.yml, plugins/modules/proxmox.py
This fixes two issues with the [new proxmox volume handling](https://github.com/ansible-collections/community.general/pull/8542) (`disk_volume` and `mount_volumes`):
1. In the plugin, a string conversion was previously forced that clashed with the documentation and incorrectly converted `None`-type values into `"None"` strings.
2. In the `build_volume()` method of the plugin, half of the built string was accidentally discarded.
proxmox
Here is a sample playbook to test the validity:
```yaml
---
- name: Create LXC
become: false
vars_files:
- proxmox_credentials.yml
tasks:
- name: Create LXC
community.general.proxmox:
api_host: "{{ api_host }}"
api_user: "{{ api_user }}"
api_password: "{{ api_password }}"
node: "{{ node }}" …
```
=> Fix new Proxmox Volume handling

changelogs/fragments/8632-pkgng-add-option-use_globs.yml, plugins/modules/pkgng.py, tests/integration/targets/pkgng/tasks/install_single_package.yml
Implement feature request  #8632
community.general.pkgng
* Add option
```yaml
+    use_globs:
+        description:
+            - Treat the package names as shell glob patterns.
+        required: false
+        type: bool
+        default: true
+        version_added: 9.2.0
```
* Remove all hard coded options *-g*, e.g.
```python
-    rc, out, err = run_pkgng('info', '-g', '-e', name)
+    rc, out, err = run_pkgng('info', '-e', name)
```
* Apply the option -g conditionally
```python
def run_pkgng(action, *args, **kwargs):
cmd = [pkgng_path, dir_arg, action]
+        if p["use_globs"] and action in ('info', 'install', 'upgrade',):
+            args = ('-g',) + args
```
* Add example. This allows the upgrade packages by pkg-origin (foo/bar). See …
=> pkgng - add option use_globs (default=true)

changelogs/fragments/8624-cache-types.yml, plugins/cache/memcached.py, plugins/cache/pickle.py, plugins/cache/redis.py, plugins/cache/yaml.py
=> Type options of cache plugins

.github/BOTMETA.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_realm_keys_metadata_info.py, tests/unit/plugins/modules/test_keycloak_realm_keys_metadata_info.py
When setting up Nextcloud integration to Keycloak we have to ship the metadata of a realm to Nextcloud. With the current modules it is not possible to extract the metadata. This PR adds a module `keycloak.keycloak_realm_keys_metadata` which makes it possible to query the metadata and pass it on:
```yaml
- name: Fetch Keys metadata
community.general.keycloak_realm_keys_metadata:
auth_username: USERNAME
auth_password: PASSWORD
realm: MyCustomRealm
register: keys_metadata
- name: Write the Keycloak keys certificate into a file
ansible.builtin.copy:
dest: /tmp/keycloak.cert
content: |
{{ keys_metadata['keys_metadata']['keys']
| selectattr('algorithm', 'equalto', 'RS256')
| map(attribute='certificate')
| …
```
=> Add a keycloak module to query keys metadata

changelogs/fragments/8648-fix-gitlab-runner-paused.yaml, plugins/modules/gitlab_runner.py
The paused module parameter needs to passed to the create_or_update method to work.
As of now (gitlab 17.1.0) `active: False` is still working. But the gitlab_runner module silently ignored `paused: True` and always responded with `No need to update the runner ...` if a runner was updated with a changed paused attribute. Creating a runner with `paused: True` also did not create a runner in paused state.
gitlab_runner
* Create a runner with `paused: True` has the runner not paused in gitlab after creation
Or
* Create a runner
* Updated the runner with `paused: True` states: `No need to update the runner ...`
* The runner is not paused in gitlab
Info @wt-io-it
=> fix(modules/gitlab_runners): pass paused to gitlab

changelogs/fragments/8688-gitlab_project-add-new-params.yml, plugins/modules/gitlab_project.py
gitlab_project:
- add option ``pages_access_level``
- add option ``service_desk_enabled``
- add option ``model_registry_access_level``
gitlab_project
Might require rebasing with https://github.com/ansible-collections/community.general/pull/8674
=> gitlab_project: Add some missing params

changelogs/fragments/8735-keycloak_identity_provider-get-cleartext-secret-from-realm-info.yml, plugins/modules/keycloak_identity_provider.py, tests/unit/plugins/modules/test_keycloak_identity_provider.py
The keycloak IDP endpoints 
``/admin/realms/{realm}/identity-provider/instances/{idp}``
and 
``/admin/realms/{realm}/identity-provider/instances?first=0&max=11``
return ``**********`` for the ``clientSecret``s. To detect changes to the secret, the cleartext ``clientSecret`` is retrieved from the full realm info (``/admin/realms/{realm}``).
Fixes 1. of [8294](https://github.com/ansible-collections/community.general/issues/8294)
keycloak_identity_provider
=> keycloak_identity_provider: get cleartext clientsecret

changelogs/fragments/8689-passwordstore-lock-naming.yml, plugins/lookup/passwordstore.py
When passwordstore needs to grab a lock, it creates a statically named file (within /tmp, typically). It also leaves that lock file around after it is done with it. This is unfortunate as there might be more than one user using the passwordstore functionality on a single machine, even if they aren't using it contemporaneously. Prepend the username to the filename so that the lock file is unique per user.
passwordstore
1.  run a playbook that will lookup from a passwordstore
2. login as another user
3. run the same or another playbook that will lookup from a passwordstore
4. it errors out because the lockfile exists and cannot be removed (due to not being the owner of the file)
=> Namespace the passwordstore lockfile

changelogs/fragments/8682-locale-gen-multiple.yaml, plugins/modules/locale_gen.py, tests/integration/targets/locale_gen/vars/main.yml
locale_gen can now take multiple locales at the same time.
This should speed it up compared to using loop.
Fixes #8677 
locale_gen
This change is **not** breaking.
```yaml
- name: Ensure locales exist # Previous (still possible)
community.general.locale_gen:
name: "{{ item }}"
state: present
loop:
- en_GB.UTF-8
- nl_NL.UTF-8
- name: Ensure locales exist # Current
community.general.locale_gen:
name:
- en_GB.UTF-8
- nl_NL.UTF-8
state: present
```
=> Add support for multiple locales in locale_gen

changelogs/fragments/8708-homebrew_cask-fix-upgrade-all.yml, plugins/modules/homebrew_cask.py
Fixes bug with homebrew_cask upgrade_all where the module always returns 'changed' due to change in output behavior of the `brew` command.
Fixes #8707 
homebrew_cask
=> homebrew_cask: fix upgrade_all changed when nothing upgraded

changelogs/fragments/8713-proxmox_lxc_interfaces.yml, plugins/inventory/proxmox.py, tests/unit/plugins/inventory/test_proxmox.py
- Add fact for [proxmox lxc interfaces](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/interfaces)
proxmox
Useful for setting the ansible_host variable for lxc containers interfaces using dhcp.
Fact example:
```json
"proxmox_lxc_interfaces": [
{
"hwaddr": "00:00:00:00:00:00",
"inet": "127.0.0.1/8",
"inet6": "::1/128",
"name": "lo"
},
{
"hwaddr": "00:00:5e:00:53:a1",
"inet": "192.0.2.12/24",
"inet6": "2001:db8:3c4d:0015:0000:0000:1a2f:1a2b/48",
"name": "eth0"
}
]
```
=> Get interfaces for Proxmox LXC containers

changelogs/fragments/8741-fix-opentelemetry-callback.yml, plugins/callback/opentelemetry.py
The commit 5f481939d introduced `store_spans_in_file` with the default
value `None` as a string. This causes the value of `store_spans_in_file`
to be a not empty string, value=None as a string and not a null value.
The rest of the code check if the store_spans_in_file is not null which
squeezes the rest of the code. The following commit set the default
value as an empty string.
Fixes (hopefully) #8566
community.general.opentelemetry
I've used the same reproducer as #8321 with `git bisect`
```
5f481939d4558e1ae61459cee2a4aecb2f8a7207 is the first bad commit
commit 5f481939d4558e1ae61459cee2a4aecb2f8a7207 (HEAD)
Author: Victor Martinez <victormartinezrubio@gmail.com>
Date:   Sun May 19 20:48:49 2024 +0200
feat(opentelemetry): support flag to export spans in a given …
```
=> fix(opentelemetry): adjust default value for `store_spans_in_file` causing traces to be produced to a file named `None`

changelogs/fragments/8695-keycloak_user_federation-mapper-removal.yml, plugins/modules/keycloak_user_federation.py, tests/unit/plugins/modules/test_keycloak_user_federation.py
Remove existing mappers that are not present in desired configuration for a user federation. This includes removing unwanted default mappers created on user federation creation.
Should partially fix [7169](https://github.com/ansible-collections/community.general/issues/7169)
=> keycloak_user_federation: add mapper removal

README.md, changelogs/fragments/0-readme.yml, docs/docsite/links.yml
Dear maintainers,
As a part of the [Consolidating Ansible discussion platforms initiative](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812), this PR adds the communication section template defined by the community to the README. Similar PRs are being raised across all included collections under the ansible-collection org for now.
- If you have your forum group and/or tags related to the collection, please update corresponding lines by suggesting changes to the PR.
- If the collection is not present on the Ansible forum yet, please check out the existing [tags](https://forum.ansible.com/tags) and [groups](https://forum.ansible.com/g) - use what suits your collection. If there is no appropritate tag and group yet, please [request …
=> README: Add Communication section with Forum information

changelogs/fragments/8759-gitlab_project-sort-params.yml, plugins/modules/gitlab_project.py
As briefly evoked on [this comment](https://github.com/ansible-collections/community.general/pull/8688#issuecomment-2282866565), sorting the params can avoid future conflicts if two users add new GitLab parameters.
- gitlab_project
Since I'm currently working on a [GitLab playbook](https://gitlab.com/cappysan/ansible/gitlab) that uses a copy of this plugin (to avoid having to wait for new releases), I have a stake in this MR as I'll be contributing back all additions I make.
=> gitlab_project: sort parameters in order to avoid futur merge conflicts

changelogs/fragments/8766-mh-deco-improve.yml, plugins/module_utils/mh/deco.py, tests/unit/plugins/module_utils/test_module_helper.py
Minor improvements in the decorators
plugins/module_utils/mh/deco.py
=> MH deco: minor refactor

changelogs/fragments/8762-keycloac_user_federation-fix-key-error-when-updating.yml, plugins/modules/keycloak_user_federation.py
The module throws a key error in update code path if there is a new mapper specified in the module arguments. 
The desired mapper list https://github.com/ansible-collections/community.general/blob/34519a5ecbac2c7a29486584f2d9ca9fd7b71eb0/plugins/modules/keycloak_user_federation.py#L1007 contains the existing mappers we want to keep, the existing ones that will be updated and the mappers that will be newly created. Since we want to remove unwanted *existing* mappers, we can exclude the new mappers that dont have an id yet when checking if we want to keep an existing mapper.
Fixes key error when updating and a new mapper is specified in the module arguments.
Add a new mapper to the module arguments before running a user federation update. …
=> keycloak_user_federation: fix key error when removing mappers in update

changelogs/fragments/8760-gitlab_project-add-issues-access-level.yml, plugins/modules/gitlab_project.py
There already is `issues_enabled`, but this seems to be the old name. `issues_access_level` seems to be the new name.
The first one is a bool, and the second one has the usual ["private", "disabled", "enabled"] values.
There are currently no handling of parameters depending on the gitlab version, and thus no code of such sort has been added to handle old (very old?) versions of gitlab. Nevertheless, new versions of gitlab don't seem bothered with obsolete values such as `issues_enabled`
- gitlab_project
This pull request is a commit above the one in https://github.com/ansible-collections/community.general/pull/8759
For this reason, it is expected that https://github.com/ansible-collections/community.general/pull/8759 be merged before this one being merged.
=> gitlab_project: add param "issues_access_level"

changelogs/fragments/8764-keycloak_user_federation-make-mapper-removal-optout.yml, plugins/modules/keycloak_user_federation.py
The `keycloak_user_federation` module removes mappers that are not specified/listed in the module arguments. In order to keep the default mappers created by keycloak, they have to be specified in the module arguments. This could break something silently if keycloak changes the default mappers in the future and adds an mapper thats important. 
The argument `removeUnspecifiedMappers` added by the changes would allow users to disable or enable the removal of unspecified mappers, picking the desired behavior.
The default is to enable the removal for now. But I'm not sure whether that's the right way and need some input.
=> keycloak_user_federation: add module arg to make mapper removal optout

changelogs/fragments/8790-gitlab_project-fix-cleanup-policy-on-project-create.yml, plugins/modules/gitlab_project.py
Fix behaviour for attribute container_expiration_policy in two scenarios.
1. Creating a new project - was using incorrect attribute name for writing
2. Updating an old project - some projects created with older versions of gitlab don't have the attribute by default which causes a AttributeError crash when trying to read it with getattr
gitlab_project
```paste below
```
=> Fix gitlab_project container_expiration_policy for project create

changelogs/fragments/8793-pipx-global.yml, plugins/module_utils/pipx.py, plugins/modules/pipx.py, plugins/modules/pipx_info.py, tests/integration/targets/pipx/tasks/main.yml, tests/integration/targets/pipx/tasks/testcase-7497.yml, tests/integration/targets/pipx/tasks/testcase-8656.yml, tests/integration/targets/pipx/tasks/testcase-8793-global.yml, tests/integration/targets/pipx/tasks/testcase-injectpkg.yml, tests/integration/targets/pipx/tasks/testcase-jupyter.yml, tests/integration/targets/pipx/tasks/testcase-oldsitewide.yml
Add new `global` parameter to both `pipx` and `pipx_info` modules.
Fixes #8705 
pipx
pipx_info
=> pipx/pipx_info: add parameter `global`

changelogs/fragments/8796-gitlab-access-token-check-mode.yml, plugins/modules/gitlab_group_access_token.py, plugins/modules/gitlab_project_access_token.py
The modules attempt to return newly created access token. In check mode if an access token with the same name did not exists beforehand, accessing _attrs would crash.
gitlab_project_access_token
gitlab_group_access_token
```paste below
```
=> Fix gitlab access token crash in check mode for new tokens

changelogs/fragments/8794-Fixing-possible-concatination-error.yaml, plugins/inventory/proxmox.py
When starting to use the proxmox inventory plugin with my 4 node setup, the plugin failed creating the inventory from the proxmox api. Some debugging led to the changed area, where it may happen that API calls return an empty result, leading to `json["data"]` being `None` and the list concatenation failing. 
Fixes https://github.com/ansible-collections/community.general/issues/8798
inventory: community.general.proxmox
```paste below
```
=> proxmox inventory: fixing possible concatenation error

changelogs/fragments/8809-pipx-new-params.yml, plugins/module_utils/pipx.py, plugins/modules/pipx.py, tests/integration/targets/pipx/files/spec.json, tests/integration/targets/pipx/files/spec.json.license, tests/integration/targets/pipx/tasks/main.yml, tests/integration/targets/pipx/tasks/testcase-8793-global.yml, tests/integration/targets/pipx/tasks/testcase-8809-installall.yml, tests/integration/targets/pipx/tasks/testcase-8809-pin.yml, tests/integration/targets/pipx/tasks/testcase-8809-uninjectpkg.yml, tests/integration/targets/pipx/tasks/testcase-injectpkg.yml
=> pipx: add new states

changelogs/fragments/8833-dict-comprehension.yml, plugins/cache/redis.py, plugins/lookup/onepassword.py, plugins/module_utils/ocapi_utils.py, plugins/module_utils/redfish_utils.py, plugins/module_utils/scaleway.py, plugins/modules/alternatives.py, plugins/modules/apache2_mod_proxy.py, plugins/modules/consul_acl.py, plugins/modules/imc_rest.py, plugins/modules/keycloak_user_federation.py, plugins/modules/pids.py, plugins/modules/pipx.py, plugins/modules/pipx_info.py, plugins/modules/pkg5_publisher.py, plugins/modules/scaleway_compute.py, plugins/modules/scaleway_ip.py, plugins/modules/scaleway_lb.py, plugins/modules/scaleway_security_group.py, plugins/modules/scaleway_user_data.py, plugins/modules/sensu_silence.py, plugins/modules/snmp_facts.py, plugins/modules/sorcery.py, tests/unit/plugins/module_utils/test_cmd_runner.py, tests/unit/plugins/module_utils/test_python_runner.py
Another PR to mass-replace the construct `dict((k, v) for k, v in d if condition)` with dict comprehensions: `{k: v for k, v in d if condition}`
plugins/cache/redis.py
plugins/lookup/onepassword.py
plugins/module_utils/ocapi_utils.py
plugins/module_utils/scaleway.py
plugins/modules/alternatives.py
plugins/modules/apache2_mod_proxy.py
plugins/modules/consul_acl.py
plugins/modules/imc_rest.py
plugins/modules/pids.py
plugins/modules/pipx.py
plugins/modules/pipx_info.py
plugins/modules/pkg5_publisher.py
plugins/modules/scaleway_compute.py
plugins/modules/scaleway_ip.py
plugins/modules/scaleway_lb.py
plugins/modules/scaleway_security_group.py
plugins/modules/scaleway_user_data.py …
=> use dict comprehension in plugins, part 3

changelogs/fragments/8761-keycloak_user_federation-sort-desired-and-after-mappers-by-name.yml, plugins/modules/keycloak_user_federation.py
The module inconsistently sorts the mappers.
The module sorts the mappers fetched for the before state by name. The desired mappers and the mappers fetched after an update are not sorted. When comparing the desired mappers with the before mappers, changes are detected even if the mappers in both lists are the same except for the order. When diffing before with after mappers, differences are shown when the mappers are the same except for the order. 
The changes add sorting by name for the desired mappers and the mappers fetched after an update, analog to the existing sorting for the before mappers. This minimizes the diff and makes the change detection more accurate.
=> keycloak_user_federation: sort desired and after mappers by name

.github/BOTMETA.yml, plugins/modules/one_vnet.py, tests/integration/targets/one_vnet/aliases, tests/integration/targets/one_vnet/tasks/main.yml
- `one_vnet` module to manage networks in OpenNebula
one_vnet
There were no option to configure network using modules which is important
I used other `one_*` modules to make it similar, especially `one_template` which i used as a base
xml-rpc schemes:
https://github.com/privazio/pyone/blob/master/pyone/xsd/vnet.xsd
https://github.com/privazio/pyone/blob/master/pyone/xsd/vnet_pool.xsd
opennebula docs:
https://docs.opennebula.io/6.8/integration_and_development/system_interfaces/api.html
```yaml
- name: Make sure the network is present by ID
community.general.one_vnet:
id: 0
state: present
- name: Create a new or update an existing NETWORK
community.general.one_vnet:
name: bridge-network
template: |
VN_MAD  = "bridge"
BRIDGE  = "br0" …
```
=> Add one_vnet module

changelogs/fragments/8823-keycloak-realm-key.yml, plugins/modules/keycloak_realm_key.py, tests/unit/plugins/modules/test_keycloak_realm_keys.py
This fixes #7850. Realm key creation on keycloak side needs the parent_id to be either the ID of the realm or to be omitted. The modules mixed up the realm name - as used in the url - with the id, leading to invalid created entities. In addition the get_components request for getting the current state filtered with the same invalid value. 
community.general.keycloak_realm_key
=> bugfix(keycloak): fix parameters for realm key creation

plugins/lookup/random_string.py
[The doc for random_string lookup](https://docs.ansible.com/ansible/latest/collections/community/general/random_string_lookup.html) include examples with `lookup` and `query`. While `lookup` returns a string and `query` returns an array of one element, the examples say that both calls return an array.
random_string lookup
I've also replaced `debug` calls by `ansible.builtin.debug` (in this example, both forms where used).
Sample playbook file :
```
tasks:
- name: Generate random string
ansible.builtin.debug:
var: lookup('community.general.random_string')
- name: Generate random string with length 12
ansible.builtin.debug:
var: lookup('community.general.random_string', length=12)
- name: Generate base64 encoded random string …
```
=> (doc) random_string lookup: fix examples

.github/BOTMETA.yml, plugins/modules/keycloak_userprofile.py, tests/integration/targets/keycloak_group/tasks/main.yml, tests/integration/targets/keycloak_userprofile/aliases, tests/integration/targets/keycloak_userprofile/meta/main.yml, tests/integration/targets/keycloak_userprofile/readme.adoc, tests/integration/targets/keycloak_userprofile/tasks/main.yml, tests/integration/targets/keycloak_userprofile/vars/main.yml, tests/unit/plugins/modules/test_keycloak_userprofile.py
This adds a new keycloak module to manage user profiles.
See Keycloak documentation :
https://www.keycloak.org/docs/latest/upgrading/index.html#user-profile-changes
https://www.keycloak.org/docs/latest/server_admin/#_understanding-managed-and-unmanaged-attributes
https://www.keycloak.org/docs/latest/server_admin/#_user-profile-json-configuration
Fixes #8573 and #8579
keycloak_userprofile
This is heavily based on `keycloak_realm_key` and `keycloak_user_federation`.
=> keycloak_userprofile: new module

changelogs/fragments/8831-fix-error-when-mapper-id-is-provided.yml, plugins/modules/keycloak_user_federation.py
The module crashes if an id is provided for a mapper, see https://github.com/ansible-collections/community.general/pull/8695#issuecomment-2331251238.
The before mappers should be retrieved from the `before_comp` not `before_mapper`.
community.general.keycloak_user_federation
1. create a mapper without providing an id:
```
mappers:
- name: "first name"
providerId: "user-attribute-ldap-mapper"
providerType: "org.keycloak.storage.ldap.mappers.LDAPStorageMapper"
config:
ldap.attribute: givenName
read.only: true
write.only: false
attribute.force.default: true
is.mandatory.in.ldap: true
is.binary.attribute: false
user.model.attribute: firstName
```
2. copy id from keycloak and update mapper:
```
mappers:
- name: "first name"
id: f2d82dec-923c-40da-a9f7-0fe83ca8c009 …
```
=> keycloak_user_federation: get the before mappers from `before_comp` to fix `UnboundLocalError`

changelogs/fragments/8858-dict-comprehension.yml, plugins/modules/scaleway_container.py, plugins/modules/scaleway_container_info.py, plugins/modules/scaleway_container_namespace.py, plugins/modules/scaleway_container_namespace_info.py, plugins/modules/scaleway_container_registry.py, plugins/modules/scaleway_container_registry_info.py, plugins/modules/scaleway_function.py, plugins/modules/scaleway_function_info.py, plugins/modules/scaleway_function_namespace.py, plugins/modules/scaleway_function_namespace_info.py
Another PR to mass-replace the construct `dict((k, v) for k, v in d if condition)` with dict comprehensions: `{k: v for k, v in d if condition}`
plugins/modules/scaleway_container.py
plugins/modules/scaleway_container_info.py
plugins/modules/scaleway_container_namespace.py
plugins/modules/scaleway_container_namespace_info.py
plugins/modules/scaleway_container_registry.py
plugins/modules/scaleway_container_registry_info.py
plugins/modules/scaleway_function.py
plugins/modules/scaleway_function_info.py
plugins/modules/scaleway_function_namespace.py
plugins/modules/scaleway_function_namespace_info.py
=> use dict comprehension in plugins, part 4

changelogs/fragments/8876-dict-items-loop.yml, plugins/modules/gitlab_deploy_key.py, plugins/modules/gitlab_group.py, plugins/modules/gitlab_issue.py, plugins/modules/gitlab_merge_request.py, plugins/modules/gitlab_runner.py, plugins/modules/icinga2_host.py, plugins/modules/memset_dns_reload.py, plugins/modules/memset_memstore_info.py, plugins/modules/memset_server_info.py, plugins/modules/memset_zone.py, plugins/modules/memset_zone_domain.py, plugins/modules/memset_zone_record.py, plugins/modules/nmcli.py, plugins/modules/scaleway_user_data.py, plugins/modules/udm_dns_record.py
plugins/modules/gitlab_deploy_key.py
plugins/modules/gitlab_group.py
plugins/modules/gitlab_issue.py
plugins/modules/gitlab_merge_request.py
plugins/modules/gitlab_runner.py
plugins/modules/icinga2_host.py
plugins/modules/memset_dns_reload.py
plugins/modules/memset_memstore_info.py
plugins/modules/memset_server_info.py
plugins/modules/memset_zone.py
plugins/modules/memset_zone_domain.py
plugins/modules/memset_zone_record.py
plugins/modules/scaleway_user_data.py
plugins/modules/udm_dns_record.py
=> multiple modules: improve dict.items() loops

changelogs/fragments/8785-keycloak_user_federation-set-krbPrincipalAttribute-to-empty-string-if-missing.yaml, plugins/modules/keycloak_user_federation.py
Issue: 
The `keycloak_user_federation` module always detects a change in check mode if the parameter `krbPrincipalAttribute` is set to `''`. The empty string is a valid value: https://github.com/ansible-collections/community.general/blob/96d5e6e50e972ae1bfc61cf1fb71c0738230c213/plugins/modules/keycloak_user_federation.py#L354
Keycloak completely removes the parameter `krbPrincipalAttribute` if it is set to `''`. So subsequent check runs always detect a change. In a normal run the module would always make an update (its the same change check), but compare the before and after responses afterwards, in both of which the parameter is not present. In the check diff this is already fixed by setting `''` in the sanitize function if the parameter is not present (see …
=> keycloak_user_federation: set `krbPrincipalAttribute` to `''` if unset in kc responses

changelogs/fragments/8885-add-force-flag-for-nmp.yml, plugins/modules/npm.py
Add `--force` flag for nmp module
Fixes #8678
nmp
It seemed easy to implement without breaking backward compatibility
```yaml
- name: Force Install "coffee-script" node.js package.
community.general.npm:
name: coffee-script
force: true
```
=> npm: Add force flag

changelogs/fragments/8877-keycloak_realm-sort-lists-before-change-detection.yaml, plugins/modules/keycloak_realm.py
The lists `enabledEventTypes`, `otpSupportedApplications` and `supportedLocales` are sorted (in the normalize function) for the diff but not when comparing realms for the `changed` parameter. So the module always detects a change in check mode but shows an empty diff:
```
TASK [kc1 - realm-1 - Update Keycloak realm] ************************************************************************************************************************************************************************
changed: [kc1]
```
To minimize the changes, the lists should be sorted before comparing the realms as well.
keycloak_realm
1. create minimal realm:
```
- name: Create or update Keycloak realm (minimal example)
community.general.keycloak_realm:
auth_client_id: admin-cli
auth_keycloak_url: …
```
=> keycloak_realm: fix change detection in check mode by normalizing realms beforehand

changelogs/fragments/8900-ipa-hostgroup-fix-states.yml, plugins/modules/ipa_hostgroup.py
Fix state `enabled` and `disabled` params
Fixes #8408
`ipa_hostgroup`
As it was mentioned in a related issue these values for `state:` are useless and because of else statement the lead to `absent` result. It is not clear if these values should be kept because they do not work as intented so maybe we should just remove or deprecate them? For now i made it so 'absent'/'disabled' and 'present'/'enabled' are the same thing
```yaml
- ipa_hostgroup:
state: 'enabled'
name:  'testhostgroup'
- ipa_hostgroup:
state: enabled
name:  'testhostgroup'
- ipa_hostgroup:
state: disabled
name:  'testhostgroup'
```
=> ipa_hostgroup: fix state params

changelogs/fragments/8929-cmd_runner-bugfix.yml, plugins/module_utils/cmd_runner.py
Function call was missing a parameter
=> CmdRunner: missing parameter for get_best_parsable_locale()

changelogs/fragments/8887-fix-one_service-unique.yml, plugins/modules/one_service.py
After some investigation i concluded that the problem described in the related issue can be fixed by changing one if-statement 
Fixes #3137
one_service
I also deleted a space between a function and a body because in all other functions there is no
```yaml
- name: Instantiating OpenNebula service
ansible.community.one_service:
template_id: "{{ one_template_id }}"
service_name: "{{ deployment_name }}"
unique: true
wait: true
```
=> one_service: fix recreation

changelogs/fragments/8928-cmd-runner-10.0.0.yml, plugins/module_utils/cmd_runner.py, tests/integration/targets/cmd_runner/tasks/test_cmd_echo.yml, tests/integration/targets/cmd_runner/vars/main.yml, tests/unit/plugins/module_utils/test_cmd_runner.py
Remove deprecated feature from CmdRunner
=> 10.0.0: CmdRunner: remove deprecated feature

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml
2.15 is only EOL in November, but I want to remove 2.13 and 2.14 from CI, which would leave the EOL tests empty :)
CI
=> Move ansible-core 2.15 tests to EOL tests

changelogs/fragments/8923-keycloak_userprofile-fix-empty-response-when-fetching-userprofile.yml, plugins/modules/keycloak_userprofile.py
The module filters the components by `parent=parent_id` (and `type`). The same variable `parent_id` is also used as the `realm` argument for the `get_components` call. 
https://github.com/ansible-collections/community.general/blob/89ad40db4181d88dd4c8e7d68237f7a4a7e61bb4/plugins/modules/keycloak_userprofile.py#L644
https://github.com/ansible-collections/community.general/blob/89ad40db4181d88dd4c8e7d68237f7a4a7e61bb4/plugins/module_utils/identity/keycloak/keycloak.py#L2612
The `parent` filter expects the ID of the parent realm (usually a uuid) whereas the `realm` argument requires the name of a realm ('master' for example). So unless the ID and the name of realm are identical the returned list is empty.
```
--- before
+++ after
@@ -1 +1,9 @@
-{}
+{
+    "config": {
+ …
```
=> keycloak_userprofile: fix empty response by removing `parent` filter when fetching userprofile component

changelogs/fragments/8909-flatpak-improve-name-parsing.yaml, plugins/modules/flatpak.py
This pull request updates the Flatpak name parsing functionality to handle additional valid cases for Flatpak identifiers.
flatpak
While trying to install `com.chatterino.chatterino` from Flathub, I encountered a problem with the multiple versions of this package available: `stable` and `nightly`. To install it properly, it has to be the full name: `app/com.chatterino.chatterino/x86_64/stable` or `com.chatterino.chatterino/x86_64/stable`. But the module doesn't handle those names very well and tries to install the package even if it's already installed, returning `changed` instead of `ok`.
```yaml
- name: Install applications from flathub
community.general.flatpak:
name:
- app/com.brave.Browser
- app/com.google.Chrome/
- org.mozilla.firefox/
- …
```
=> flatpak: improve flatpak name parsing in `_parse_flatpak_name`

plugins/modules/pipx.py
Remove unused param from the `CmdRunner` context run. It is guaranteed to be unused because the param `name_source` is not used in the context, as defined in the previous line. 
pipx
=> pipx: remove unused param from the runner ctx.run() call

.github/BOTMETA.yml, changelogs/fragments/8964-cmd-runner-argformat-refactor.yml, plugins/module_utils/cmd_runner.py, plugins/module_utils/cmd_runner_fmt.py
Refactored the argument formatting code from the cmd_runner.py file.
The rationale behind it is:
- unclutter the cmd_runner.py file
- create a clear boundary between those components
- in anticipation of writing docstrings in both files, so that the Command Runner Guide can make use of them
=> cmd_runner_fmt: refactor out to its own file

changelogs/fragments/8897-nmcli-add-reload-and-up-down.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
Add `conn_reload` option to perform `nmcli connection reload` if set to true
Add `up` and `down` states to perform `nmcli up`/`nmcli down` commands
Fixes #3752
Fixes #8704
Fixes #7152
`nmcli`
I am not completely sure how to make applying changes correctly as there is no distinct difference between 4 different variants in a related issue (see https://github.com/ansible-collections/community.general/issues/3752#issuecomment-1714459183) so if you have some ideas I would be glad to get comments from you :)
```yaml
- name: Change the property of a setting e.g. MTU and reload connection
conn_name: my-eth1
mtu: 1500
type: ethernet
state: present
conn_reload: true
- name: Disable connection
conn_name: my-eth1
state: down
- …
```
=> nmcli: conn_reload param and up/down states

changelogs/fragments/8812-keycloak-user-federation-remove-lastSync-param-from-kc-responses.yml, plugins/modules/keycloak_user_federation.py
Keycloak stores a timestamp of the last ldap sync in the parameter `lastSync`. Once the parameter is set after a sync (periodic or manual), the module always detects a change and shows a diff similar to the one below.
```
--- before
+++ after
@@ -18,7 +18,6 @@
"kerberosRealm": "EXAMPLE.NET",
"keyTab": "/mnt/ad2",
"krbPrincipalAttribute": "test",
-        "lastSync": "1724663435",
"pagination": "false",
"priority": "0",
"rdnLDAPAttribute": "sAMAccountName",
changed: [kc1]
```
The parameter seems to be used to time the periodic syncs, so i don't think changing it is good idea. The API does allow changing it though. But I did not find a way to view or change the parameter in the web GUI.
It looks like the parameter is only used by kc internally, so it should be safe to ignore it and remove …
=> keycloak_user_federation: remove `lastSync` param from kc API responses

changelogs/fragments/8719-openiscsi-add-multiple-targets.yaml, plugins/modules/open_iscsi.py
- open_iscsi now can login to a portal with multiple targets available
open_iscsi
There was no option to login into multiple targets (luns) of a portal
Also as there no longer need to warn about this problem, i deleted a note not to confuse anyone with a wrong information
```yaml
- name: Discover targets on portal and login to the one available
community.general.open_iscsi:
portal: '{{ iscsi_target }}'
login: true
discover: true
- name: Discover targets on portal and login to the one available
community.general.open_iscsi:
portal: '{{ iscsi_target }}'
login: true
discover: true
```
=> open_iscsi: Make targets optional for a portal login

changelogs/fragments/8889-refactor-one-image-modules.yml, plugins/module_utils/opennebula.py, plugins/modules/one_image.py, plugins/modules/one_image_info.py, tests/integration/targets/one_image/aliases, tests/integration/targets/one_image/tasks/main.yml, tests/integration/targets/one_image_info/aliases, tests/integration/targets/one_image_info/tasks/main.yml
Refactor `one_image` and `one_image_info` modules to support more parameters and make it more simillar to `one_vnet` and `one_template` to reuse already existing OpenNebula class from `module_utils`
Fixes #3578
`one_image`
`one_image_info`
As i already mention the goal is to make these 2 modules use already existing OpenNebula class from `module_utils` to reuse already existing methods, i also added fully extended parameters that these 2 modules in return (using xsd scheme from https://github.com/privazio/pyone/blob/master/pyone/xsd/image.xsd)
There were also some problems with images that have `id=0` because of incorrect if statements so i fixed them in process
I also added `persistent` to images (see related issue) and tested all of these on my OpenNebula …
=> one_image/one_image_info: refactor

changelogs/fragments/8970-fix-dig-multi-nameservers.yml, plugins/lookup/dig.py
Currently, when specifying multiple nameservers, only the very last one is actually used. Fix that by collecting all specified nameservers and passing them to the Resolver after the argument processing is done.
`dig`
Currently, when specifying multiple nameservers either using multiple `@ns.example.com` arguments or by specifying multiple nameservers in a single argument (`@ns1.example.com,ns2.example.com`), due to a bug only the very last nameserver that is specified is actually used.
This is because for every iteration of the `for ns in nsset` loop, the local list of nameservers is cleared and after adding the currently processed nameserver entry, the whole `nameservers` list of the Resolver instance is overridden with that new list with just one element. And as …
=> dig lookup plugin: Fix using only last nameserver specified

changelogs/fragments/8987-legacycrypt.yml, plugins/modules/homectl.py, plugins/modules/udm_user.py, tests/integration/targets/homectl/tasks/main.yml
On Python 3.13, crypt has been removed from the standard library. There's now a [PyPI package legacycrypt](https://pypi.org/project/legacycrypt/) which contains the removed module. Use that one if available.
Ref: #4690
Ref: #4691
udm_user
homectl
=> udm_user, homectl: use legacycrypt on Python 3.13+

.github/BOTMETA.yml, plugins/modules/ipa_getkeytab.py, tests/unit/plugins/modules/test_ipa_getkeytab.py
`ipa_getkeytab` as a fancy wrapper around `ipa-getkeytab` command
`ipa_getkeytab`
Pretty much a simple wrapper around a `ipa-getkeytab` using `cmd_runner`
I tested this module by my hands and it seems to work as intended
I don't know how to write unit tests because for integration test I would need FreeIPA server and client installed so i wrote something up using `test_npm` as a source
```yaml
- name: Create keytab
ansible.builtin.shell: ipa-getkeytab -s <ipa_server> -p <some_principal> -k <some_path>
- name: Create keytab
community.general.ipa_getkeytab:
path: <some_path>
principal: <some_principal>
ipa_server:  <ipa_server>
```
=> ipa_getkeytab: Create module

changelogs/fragments/8952-password-store-lookup-create-subkey-support.yml, plugins/lookup/passwordstore.py
passwordstore lookup - Add the ability to create and update subkeys in password files.
passwordstore lookup
Here some command lines to  illustrate the feature:
```
❯ ansible -m debug -i localhost, -a "msg={{ lookup('community.general.passwordstore', 'example/test', create=true, subkey='foo') }}" localhost
localhost | SUCCESS => {
"msg": "u6V31gj3d0i3lLbO"
}
❯ ansible -m debug -i localhost, -a "msg={{ lookup('community.general.passwordstore', 'example/test', create=true, subkey='foo', overwrite=true, backup=true) }}
" localhost
localhost | SUCCESS => {
"msg": "8jRMhmn9bE-Ra:Yh"
}
❯ ansible -m debug -i localhost, -a "msg={{ lookup('community.general.passwordstore', 'example/test', create=true, overwrite=true) }}" localhost
localhost | SUCCESS => {
"msg": …
```
=> passwordstore: Support subkey creation and update

changelogs/fragments/8954-keycloak-user-federation-add-referral-parameter.yml, plugins/modules/keycloak_user_federation.py
The module is missing support for the `config.referral` parameter. The PR adds the parameter to the user federation config.
Module args:
```
community.general.keycloak_user_federation:
[...]
state: present
config:
referral: "follow"
[...]
```
Not supported response:
```
fatal: [kc1]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (community.general.keycloak_user_federation) module: config.referral. Supported parameters include: allowKerberosAuthentication, allowPasswordAuthentication, authType, batchSizeForSync, bindCredential, bindDn, cachePolicy, changedSyncPeriod, connectionPooling, connectionPoolingAuthentication, connectionPoolingDebug, connectionPoolingInitSize, connectionPoolingMaxSize, connectionPoolingPrefSize, connectionPoolingProtocol, …
```
=> keycloak_user_federation: add user federation config parameter `referral` to module args

changelogs/fragments/8679-fix-cloudflare-srv.yml, plugins/modules/cloudflare_dns.py
Brings SRV API up to date with the changes from here: https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#2024-05-31
Fixes #8679
cloudflare_dns
```paste below
- name: Create an SRV record _foo._tcp.example.net
community.general.cloudflare_dns:
domain: example.net
service: foo
proto: tcp
port: 3500
priority: 10
weight: 20
type: SRV
value: fooserver.example.net
```
=> cloudflare_dns: Update SRV record handling for Cloudflare API changes

changelogs/fragments/8940-keycloak_userprofile-improve-diff.yml, plugins/modules/keycloak_userprofile.py, tests/unit/plugins/modules/test_keycloak_userprofile.py
Keycloak returns a single JSON formatted string for the `kc.user.profile.config` which cant be diffed properly.
```
--- before
+++ after
@@ -1,7 +1,7 @@
{
"config": {
"kc.user.profile.config": [
-            "{\"attributes\": [{\"name\": \"username\", \"displayName\": \"${username}\", \"validations\": {\"length\": {\"min\": 3, \"max\": 255}, \"username-prohibited-characters\": {}, \"up-username-not-idn-homograph\": {}}, \"annotations\": {}, \"permissions\": {\"view\": [\"********\", \"user\"], \"edit\": []}, \"multivalued\": false}, {\"name\": \"email\", \"displayName\": \"${email}\", \"validations\": {\"email\": {}, \"length\": {\"max\": 255}}, \"annotations\": {}, \"required\": {\"roles\": [\"user\"]}, \"permissions\": {\"view\": [\"********\", \"user\"], \"edit\": []}, \"multivalued\": …
```
=> keycloak_userprofile: improve diff by deserializing fetched `kc.user.profile.config` and serializing it before sending

changelogs/fragments/8532-expand-opennuebula-inventory-data.yml, plugins/inventory/opennebula.py, tests/unit/plugins/inventory/test_opennebula.py
To enable greater use of the inventory, add the ID of the VM, and the hostname of the host the VM is running on to the inventory output
opennebula.py
```paste below
"host": "foo23.host",
"id": 1234,
```
=> opennebula inventory: add VM ID and VM host to data

changelogs/fragments/8973-keycloak_client-add-x509-auth.yml, plugins/modules/keycloak_client.py
keycloak_client is missing support for x509 client authentication,   
this PR updates `client_authenticator_type` with the choice `client-x509`
modules/keycloak_client
Below is steps to test the result with this PR applied.
```
cat ~/keycloak/certs/start.sh  
export KEYCLOAK_ADMIN=admin
export KEYCLOAK_ADMIN_PASSWORD=admin
cd /opt/keycloak
bin/kc.sh start-dev --https-certificate-key-file=/certs/certificate.key --https-certificate-file=/certs/certificate.crt --https-trust-store-file=/certs/truststore.jks --https-trust-store-password=password --https-client-auth=request --log-level=trace
```
Start Keycloak
`docker run --rm -it -p 8080:8080 -p 8443:8443 -v ~/keycloak/certs:/certs --entrypoint=/bin/bash keycloak/keycloak:25.0 bash /certs/start.sh`
Apply config
``` …
```
=> keycloak_client add option to support client-x509 authentication

changelogs/fragments/8956-remove-capacitybytes-from-the-required-parameters_list.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_config.py
Make `CapacityBytes` an allowed parameter and not a required one.
Fixes #8955 
redfish_config
```paste below
```
=> Remove 'CapacityBytes' from list of required parameters

changelogs/fragments/8990.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_config.py
Fixes #8962
redfish_config will no longer delete 'None' type volumes by default when trying to create a new volume.
User will now have to ask for this automatic deletion with the 'storage_none_volume_deletion' boolean parameter.  
redfish_config
=> redfish_config new bool parameter to automatically delete 'None' type volumes.

changelogs/fragments/8907-fix-one-host-id.yml, plugins/modules/one_host.py
Fix if statements when ID equals to 0
Fixes #1199
`one_host`
So I tested all of the `one.` commands and It seem to be returning ID (integer) of created/updated host or cluster
So using simple `if some_variable:` will not work if ID=0 because bool(0) = False and since and since OpenNebula starts ID counter from zero thats a big problem 
```yaml
- name: Add host to OpenNebula
community.general.one_host:
api_url: "{{ one_api_url }}"
api_username: "{{ one_api_username }}"
api_password: "{{ one_api_password }}"
name: "{{ one_host }}"
im_mad_name: kvm
vmm_mad_name: kvm
template:
TYPE: "testing"
state: present
```
=> one_host: Fix ID logic

changelogs/fragments/9012-dell-pwrbutton-requires-a-job-initiated-at-reboot.yml, plugins/module_utils/redfish_utils.py
Dell systems do not change the bios setting PwrButton right away. The command will return changed=true all the time, but it is not applied. Also no job is scheduled at next reboot for the change to take place. This patch aims to fix this issue.
redfish_utils / refish_config
1. Use curl to verify the current configuration:
```
curl -u foobar:foobar https://my.host/redfish/v1/Systems/System.Embedded.1/Bios -k -s | jq '.Attributes.PwrButton'
"Enabled"
```
2. Run `community.general.redfish_config` with params:
```
community.general.redfish_config:
category: 'Systems'
command: 'SetBiosAttributes'
bios_attributes:
PwrButton: 'Disabled'
baseuri: 'my.host.com'
username: 'foobar'
password: 'foobar'
```
3. The output will always return `{"changed": true, "msg": "Modified BIOS …
=> Dell PwrButton requires a job initated at reboot

plugins/modules/snap.py
Improve snap module documentation.
module: community.general.snap
=> snap: improve documentation

changelogs/fragments/9010-edit-gitlab-label-color.yaml, plugins/modules/gitlab_label.py
Set Gitlab label's color when updating a label.
Fail if both `new_name` and `color` are missing when updating a label, one of them is required as described into [Gitlab API docs](https://docs.gitlab.com/ee/api/labels.html).
Fixes #8991 
Gitlab Label
=> update gitlab label's color

changelogs/fragments/9026-consul_kv-datacenter.yml, plugins/modules/consul_kv.py
consul_kv
Consul supports a `datacenter` feature allowing to use a consul agent to connect to a different consul datacenter.
Here is the [consul CLI documentation](https://developer.hashicorp.com/consul/commands/kv/put#datacenter).
Here is the [python-consul documentation](https://python-consul.readthedocs.io/en/latest/#consul).
=> consul_kv: add argument for the datacenter option on consul api

changelogs/fragments/9028-bitwarden-secrets-manager-syntax-fix.yml, plugins/lookup/bitwarden_secrets_manager.py, tests/unit/plugins/lookup/test_bitwarden_secrets_manager.py
[Bitwarden Secrets Manager v0.3.0 introduced a breaking change](https://github.com/bitwarden/sdk/releases/tag/bws-v0.3.0), swapping the noun and verb in the CLI. This change adds a version check to the BWS lookup and uses the correct command syntax for the version you have installed.
bitwarden_secrets_manager
=> bitwarden_secrets_manager lookup plugin: support more current versions of BWS CLI

changelogs/fragments/9022-improve-homebrew-perf.yml, plugins/modules/homebrew.py
I noticed while working with the homebrew module that it was quite slow, even when doing noops so I instrumented the code a bit to understand why.  
For the following  task:
```yaml
- name: Install brew packages
community.general.homebrew:
name: "{{ thibaut_brew_packages }}"
state: latest
update_homebrew: true
```
I got the following logs:
```
_run starting ...'
_update_homebrew starting ...'
_update_homebrew took 992.34 ms'
_upgrade_packages starting ...'
_upgrade_current_package starting ...' (ALREADY INSTALLED CASE)
_current_package_is_installed starting ...'
_current_package_is_installed took 780.45 ms'
_current_package_is_installed starting ...'
_current_package_is_installed took 738.39 ms'
_current_package_is_outdated starting ...'
_current_package_is_outdated took 750.32 ms' …
```
=> Speed up brew module package install & upgrade

.github/BOTMETA.yml, plugins/modules/jenkins_node.py, tests/unit/plugins/modules/test_jenkins_node.py, tests/unit/requirements.txt
A while back l proposed PR https://github.com/ansible-collections/community.general/pull/7160 for new module: Jenkins node management.
It was closed before I could complete it - reviewer was largely satisfied but I didn't want to submit without completing the unit tests.
This PR is a scaled back version of the original - fewer features (to be added incrementally later) but unit tests completed.
Implemented and tested:
- Present, absent, enabled, disabled Jenkins node.
- Set node # executors.
- Set node labels.
Tested against latest Jenkins LTS at time of writing.
Included workaround for `python-jerkins` redirect authentication error present in some versions of this dependency.
jenkins_node
=> New module: Jenkins node management

tests/integration/targets/timezone/aliases
On the RHEL 7.9 VMs, `/bin/timedatectl set-local-rtc no` fails with `Failed to set local RTC: Failed to set RTC to local/UTC: Input/output error`.
timezone
=> Skip timezone test on RHEL 7.9 VMs

changelogs/fragments/8979-keycloak_group-fix-subgroups.yml, plugins/module_utils/identity/keycloak/keycloak.py
In Keycloak versions 23 and later, GroupRepresentation.subGroups has been replaced by GroupRepresentation.subGroupCount and another endpoint to get subgroups.
This caused community.general.keycloak_group to fail when creating a group with a parent.
We now execute this second request if needed.
Fixes ansible-collections/community.general#8788
See https://www.keycloak.org/docs/latest/upgrading/#grouprepresentation-changes
keycloak_group
Related issue : ansible-collections/community.general#8788
Tested on Keycloak versions (Docker images) :
- 17.0.0
- 21.1.2
- 22.0.5
- 23.0.4
- 23.0.7
- 24.0.5
- 25.0.6
=> keycloak_group: fix subgroup creation in Keycloak ≥23

changelogs/fragments/9019-onevnet-bugfix.yml, plugins/modules/one_vnet.py
Thats a hotfix for a one_vnet module
one_vnet
1) VN_MAD instead of VM_MAD (https://github.com/privazio/pyone/blob/master/pyone/xsd/vnet_pool.xsd#L69) - typo
2) VNET insead of VMTEMPLATE (https://github.com/privazio/pyone/blob/master/pyone/xsd/vnet_pool.xsd#L8) - typo
3) Fix loop for `.AR_POOL.AR`, I'm as confused as you are but apparently using simple `for in` doesn't work as `.AR_POOL.AR` without specifying index ([0]) will return first ID but not the full list
4) -1 (https://github.com/acidburn0zzz/docs-2/blob/23f0ac32b5bb11caa8a180977a423076dc577cce/source/integration/system_interfaces/api.rst#onevnallocate) - lack of parameter
I'm really sorry for not testing manually these before as I thought it would be similar to a template (OpenNebula API is so weird tbh)
I …
=> one_vnet: Fix module

.github/BOTMETA.yml, changelogs/fragments/8826-keycloak-component.yml, plugins/modules/keycloak_component.py, tests/unit/plugins/modules/test_keycloak_component.py
This MR adds a new plugin for generic management of keycloak components. It is derived from the keycloak_realm_keys plugin, but omits the key-specific handling of secrets and certs. Instead it is possible to manage any component.
Possible examples are ThemeSelector, LocaleSelector, UserStorageProvider. 
see the official docs for more information:
https://www.keycloak.org/docs/latest/server_development/index.html#_providers
keycloak_component
=> add plugin for generic keycloak component

changelogs/fragments/9027-support-organizations-in-keycloak-realm.yml, plugins/modules/keycloak_realm.py
Add boolean parameter to enable organizations (still an experimental keycloak feature) feature toggling for keycloak
community.general.keycloak_realm
=> Update keycloak_realm, add organizations_enabled

changelogs/fragments/9066-proxmox-kvm-ciupgrade.yml, plugins/modules/proxmox_kvm.py
This PR implements the `ciupgrade` parameter of the proxmox API in the `proxmox_kvm` module to allow opting out of package upgrades at first boot when using cloud-init.
I'm not super familiar with the module's code so I had a quick read, looked into how the other cloud-init parameters were handled and took clues from that, in particular Proxmox version handling (according to their [roadmap page](https://pve.proxmox.com/wiki/Roadmap#Proxmox_VE_8.0), it was introduced in version 8.0). So essentially, this PR just adds the new parameter and drops it from the arguments if `pve_major_version < 8`. I've set the `version_added` doc attribute to `10.0.0` as this seems to be the next planned release.
Fixes #8119 
proxmox_kvm
=> proxmox_kvm: add support for ciupgrade parameter

changelogs/fragments/9047-redfish-uri-parsing.yml, plugins/module_utils/redfish_utils.py
Some implementations have trailing slashes in their URIs. While most of this module's code does not rely on exact URIs, some places will take the last URI segment using the `split` function when determining identifiers for collection members. In these cases, it'll be an empty string. Specifically for volume management, the `split` function was assuming trailing slashes were always present.
The change here always removes trailing slashes before trying to extract member identifiers.
Fix #9047 
redfish_utils
=> Redfish: Added handling for trailing slashes in URIs when extracting member identifiers

changelogs/fragments/9084-collection_version-importlib.yml, plugins/lookup/collection_version.py
This makes sanity tests (and potentially also other tests) fail right now.
Ref: https://github.com/ansible/ansible/pull/84161
collection_version lookup plugin
=> Stop using ansible.module_utils.compat.importlib

changelogs/fragments/9075-add-creation-oneimage.yml, plugins/modules/one_image.py
Add image creation and adjustable timeout (if image is quite big)
`one_image`
I made it quite simple: 
1) If there are no images with specified name It would create it, wait for it to be READY and then return the template
2) After it was created It works as before (no update option for now)
And I also fixed some tabs in a doc section
**I tested these changes on my server an it seems to be working as intended** :)
```yml
- name: Create image for virtual machine
ansible.builtin.command:
cmd: >
oneimage create
--datastore {{ nebula_ds_img_id }}
--path {{ item.path }}
--name {{ item.name }}
--type {{ item.type }}
--format {{ item.format }}
--prefix {{ item.prefix }}
--size {{ item.size }}
{% if item.persistent %}--persistent{% endif %}
loop: "{{ nebula_vm_image }}" …
```
=> one_image: Add image creation and timeout

changelogs/fragments/9092-keycloak-clientscope-type-fix-check-mode.yml, plugins/modules/keycloak_clientscope_type.py
Exit json with `result` only after evaluating `default_clientscopes_add`, `optional_clientscopes_add`, `default_clientscopes_delete`, `optional_clientscopes_delete` and after updating `result["changed"]`. Otherwise, `keycloak_clientscope_type` will not detect changes in **check mode**.
Fixes #9092 
`keycloak_clientscope_type`
Before fix (check mode)
After fix (check mode)
=> keycloak_clientscope_type fix checkmode

changelogs/fragments/9084-jenkins_node-add-offline-message.yml, plugins/modules/jenkins_node.py, tests/unit/plugins/modules/test_jenkins_node.py
* Implement offline_message parameter for updating a Jenkins node offline cause reason when the state is "disabled" (offline).
* Fix enabled, disable and absent node state redirect authorization issues, same as was present for present.
* Add unit tests for redirect authorization workarounds.
Add the ability to set the offline cause reason message when setting the node offline.
Caveat: can't update offline message when node is already offline - is documented and warning is emitted if this condition occurs.
Fixed some redirect auth. errors present in the original module PR.
jenkins_node
```paste below
```
=> jenkins_node: Add set offline message

changelogs/fragments/9087-mattermost-priority.yaml, plugins/modules/mattermost.py
Add support for module parameter `priority` that is passed to Mattermost server for Message Priority feature.
Fixes #9068 
Also add a missing closing parenthesis to docs.
mattermost
```paste below
```
=> mattermost: add support for message priority

changelogs/fragments/9099-proxmox-fix-insecure.yml, plugins/inventory/proxmox.py
Currently, InsecureRequestWarnings are suppressed only when using password authorization. This PR fixes that issue.
`community.general.proxmox`
=> proxmox inventory: fix urllib3 InsecureRequestWarnings not suppressing when a token is used

changelogs/fragments/9077-keycloak_client-fix-attributes-dict-turned-into-list.yml, plugins/modules/keycloak_client.py
The `attribute` config item contains a dict with additional settings. The module turns the dict into a list before storing it for the diff/end_state, which turns it into a list of just the keys:
```
+    "attributes": [
+        "backchannel.logout.revoke.offline.tokens",
+        "backchannel.logout.session.required",
+        "frontchannel.logout.url"
+    ],
+    "baseUrl": "https://www.example.com/",
```
The actual data sent to the API is not changed, so only `--diff`/`end_state` is affected.
Create a client with the module with any of the `attributes` settings from above set and `--diff`.
=> keycloak_client: remove code that turns attributes dict into list

changelogs/fragments/9082-keycloak_clientscope-fix-attributes-dict-turned-into-list.yml, plugins/modules/keycloak_clientscope.py
Same issue as in the keycloak_client module (https://github.com/ansible-collections/community.general/pull/9077).
The module turns the attributes dict into a list when storing the config for diff and end_state. This turns the dict into a list of just the keys:
```
+    "attributes": [
+        "consent.screen.text",
+        "display.on.consent.screen",
+        "gui.order",
+        "include.in.token.scope"
+    ],
+    "description": "sAMAccountName",
```
The changes remove the code turning the dict into a list, so that the diff looks like this:
```
+    "attributes": {
+        "consent.screen.text": "",
+        "display.on.consent.screen": "true",
+        "gui.order": "",
+        "include.in.token.scope": "true"
+    },
+    "description": "sAMAccountName",
```
The actual data sent …
=> keycloak_clientscope: remove code turning attributes dict into list

changelogs/fragments/9114-redfish-utils-update-remove-default-applytime.yml, plugins/module_utils/redfish_utils.py
The `@Redfish.OperationApplyTime` parameter is optional as per Redfish
spec version 1.21.0, paragraph 7.11 [1]. Some systems reject the
request rather than ignore it, causing failures that can not be
workarounded.
Removing this default resolves compatibility issues.
[1] https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.21.0.html
redfish_utils
```paste below
```
=> redfish_utils: remove undocumented default applytime

changelogs/fragments/9123-redfish-command-custom-oem-params.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_command.py
The Multipart HTTP push update implementation allows OEM specific parts that are not part of the `UpdateParameters` body part, but a separate one. This OEM part shall start with `Oem` and is optional. The OEM part implementation is specified in the Redfish spec point 12.6.2.2 [1].
Right now, the implementation will only support JSON as MIME Type, although it is not limited to JSON.
[1] https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.21.0.html#oem
=> redfish_command: add update_custom_oem options

changelogs/fragments/5932-launchd-plist.yml, plugins/modules/launchd.py
This allows the module to be used with services such as com.openssh.sshd, when the name of the plist file doesn't match the service name.
fixes #5932
launchd
Before
```console
$ ansible -m community.general.launchd -a "name=org.openssh.sshd state=stopped" localhost 
localhost | FAILED! => {
"msg": "Unable to infer the path of org.openssh.sshd service plist file"
}
$ echo $?
2
```
After
```console
$ ansible -m community.general.launchd -a "name=org.openssh.sshd plist=ssh.plist state=stopped" localhost
localhost | SUCCESS => {
"name": "org.openssh.sshd",
"status": {
"current_pid": "-",
"current_state": "unloaded",
"error": "",
"previous_pid": "-",
"previous_state": "unloaded",
"status_code": null
}
}
```
=> launchd: Add plist option

changelogs/fragments/9076-remove-duplicated-homebrew-package-name-validation.yml, plugins/modules/homebrew.py
Followup to #9022. This removes duplicated calls to the `HomebrewValidate.valid_package` responsible of validating homebrew package names provided.
Because the validation logic is already present in the `current_package` property setter, any call like `HomebrewValidate.valid_package(self.current_package)` is redundant. For `self.current_package` to exist, it must have been set (hence going throw the setter validation logic).
Here is a before/after using the same instrumentation used in the linked PR. The duplicated validation calls are removed correctly:
```diff
_run starting ...
_upgrade_packages starting ...
HomebrewValidate.valid_package(btop)
_upgrade_current_package starting ...
HomebrewValidate.valid_package(btop)
_current_package_is_installed starting ...
- …
```
=> Remove redundant `HomebrewValidate.valid_package` calls in homebrew module.

changelogs/fragments/9124-dnf_config_manager.yml, plugins/modules/dnf_config_manager.py, tests/unit/plugins/modules/test_dnf_config_manager.py
Runs `dnf config-manager` with `--assumeyes` to automatically import GPG keys instead of hanging at y/N prompt.
Fixes #8830 
dnf_config_manager
=> dnf_config_manager: use --assumeyes when changing state

plugins/modules/modprobe.py
Add version_added for the `persistent` option in modprobe. 
This is based on git tag --contains 29f5033737a7fd86349ff3daab7d7ee7db66ad00.
modprobe
N/A
=> modprobe: document when 'persistent' was added.

plugins/lookup/github_app_access_token.py
updating docs - github_token missing {{ }}
Example code for github_app_access_token is missing the {{ }} around the lookup to make the variable run
github_app_access_token
Using the example as it comes will give an error of:
"msg": "fatal: unable to access 'https://x-access-token:lookup(community.general.github_app_access_token,/': URL rejected: Port number was not a decimal number between 0 and 65535", "rc": 128, "stderr": "fatal: unable to access 'https://x-access-token:lookup(community.general.github_app_access_token,/': URL rejected: Port number was not a decimal number between 0 and 65535\n", "stderr_lines": ["fatal: unable to access 'https://x-access-token:lookup(community.general.github_app_access_token,/': URL rejected: Port number was not a decimal number …
=> Update docs for github_app_access_token.py

changelogs/fragments/9157-fix-dnf_config_manager-locale.yml, plugins/modules/dnf_config_manager.py
Fixes https://github.com/ansible-collections/community.general/issues/9046
dnf_config_manager
```paste below
```
=> dnf_config_manager: fix parsing for non-english locales

changelogs/fragments/9171-gio-mime-fix-version.yml, plugins/module_utils/gio_mime.py, plugins/modules/gio_mime.py, tests/unit/plugins/modules/test_gio_mime.yaml
Fix the command line for `gio_mime` when determining version
Fixes #9158 
gio_mime
=> gio_mime: fix bug when looking for version

changelogs/fragments/9132-cloudflare_dns-comment-and-tags.yml, plugins/modules/cloudflare_dns.py
Add support for `comment` and `tags` fields to Cloudflare DNS module as it's allowed by their API https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-create-dns-record
cloudflare_dns
```paste below
```
=> `cloudflare_dns`: add support for `comment` and `tags`

changelogs/fragments/9186-fix-broken-check-mode-in-github-key.yml, plugins/modules/github_key.py
Fixes #9185 (broken check mode in the github_key.py module) 
github_key
It looks as if this is a recent regression caused by #8222 
The change in the previous PR makes sense but it was missing the datetime class 
ie, datetime.strftime(...) instead of datetime.datetime.strftime(...)
=> fixing broken check mode in the github_key

changelogs/fragments/9181-improve-homebrew-module-performance.yml, plugins/modules/homebrew.py, tests/integration/targets/homebrew/tasks/formulae.yml
This is a rather big refactoring pull request but with rather big performance improvements.
**This makes this simple brew task 5-15x faster on my machine** by leveraging brew ability to work with multiple packages at a time.  Only 1 brew call is made to install N packages instead of N brew calls previously, greatly reducing the overall runtime.
```yml
- name: Install & upgrade brew packages
community.general.homebrew:
name: "{{ thibaut_brew_packages }}"
state: latest
update_homebrew: true
```
**Review commit per commit is highly recommended.** 
The first commit adds a few tests to increase coverage and validate more strictly the outputs. 
Then I tried to keep the commits contained and made sure tests are passing for each one of them.
homebrew …
=> Greatly speed up homebrew module when multiple packages are passed in the `name` key 

changelogs/fragments/9168-nmcli-add-sriov-parameter.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
Allow the SR-IOV settings documented here to be configured via Ansible nmcli module: https://networkmanager.pages.freedesktop.org/NetworkManager/NetworkManager/settings-sriov.html
Closes #9122 
nmcli
```paste below
```
=> Add SR-IOV support to nmcli module

changelogs/fragments/9172-opkg-deprecate-force-none.yml, plugins/modules/opkg.py
Deprecate value `""` for param `force`
opkg
=> opkg: deprecate value "" for force

.github/BOTMETA.yml, plugins/filter/accumulate.py, tests/integration/targets/filter_accumulate/aliases, tests/integration/targets/filter_accumulate/tasks/main.yml
Add the accumulate filter, a passthrough to python itertools.accumulate
See the below issue for motivation. 
Fixes #9129
filter/accumulate
N/A
=> Add the accumulate filter

changelogs/fragments/9202-keycloak_clientscope_type-sort-lists.yml, plugins/modules/keycloak_clientscope_type.py
The change sorts the default and optional clientscope lists before the diff, to make the diff more accurate.
Before:
```
{
"default_clientscopes": [
+        "email",
+        "web-origins",
"acr",
-        "profile",
-        "roles",
-        "basic",
-        "email"
+        "profile"
],
"optional_clientscopes": [
-        "web-origins",
"address",
-        "sAMAccountName",
+        "microprofile-jwt",
+        "organization",
"offline_access",
-        "microprofile-jwt"
+        "phone"
]
}
```
After:
```
{
"default_clientscopes": [
"acr",
-        "basic",
"email",
"profile",
-        "roles"
+        "web-origins"
],
"optional_clientscopes": [
"address",
"microprofile-jwt",
"offline_access",
-        "sAMAccountName",
-        "web-origins"
+        "organization",
+ …
```
=> keycloak_clientscope_type: sort default and optional clientscope lists before diff

changelogs/fragments/9223-proxmox-backup-bugfixes.yml, plugins/modules/proxmox_backup.py
Fixes a key lookup bug in modules/proxmox_backup. May be extended with further fixes, when encountered in upcoming usage.
Currently, if the permission tree for vms does not include "/" and at the same time does contain "/vms", the module fails.
proxmox_backup
=> Fix incorrect key lookup

tests/integration/targets/sysrc/tasks/main.yml
Nightly tests fail because ezjail can no longer be installed on FreeBSD 14.0.
sysrc integration tests
=> sysrc: add another exclusion for ezjail

changelogs/fragments/9234-fix-verify-bios-attributes-multi-system.yml, plugins/module_utils/redfish_utils.py
Fixes #9230
redfish_utils
Previously, this command was working on single system resource systems due to `get_multi_bios_attributes()` returning a consistent response. When running on a system with multiple system resources the response from `get_multi_bios_attributes()` includes additional output structure that was not being accounted for in the method.
Due to this command being part of the `redfish_command` the `data_modification=True` attribute is set which requires passing in `resource_id` on nodes with multiple managers/systems/chassis. We can switch to using the singular `get_bios_attributes` method and eliminate the extra parsing as we will never have multiple system entries worth of data to handle.
Before this change on a system with multiple system entries: …
=> Fix VerifyBiosAttributes command on Systems with multiple entries

plugins/modules/yarn.py
Adjustments to the module documentation
yarn
=> yarn: adjust docs

changelogs/fragments/9255-fix-handling-of-aliased-homebrew-packages.yml, plugins/modules/homebrew.py, tests/integration/targets/homebrew/tasks/casks.yml, tests/integration/targets/homebrew/tasks/formulae.yml
=> homebrew: fix incorrect handling of aliases

changelogs/fragments/9263-kc_authentication-api-priority.yaml, plugins/modules/keycloak_authentication.py
The module doesn't pass the required `priority` attribute back to the server during updates resulting in broken authentication flows
```paste below
```
=> keycloak_authentication: Fix priority attribute during execution updates

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/lookup_lmdb_kv/runme.sh
Arch Linux updated to Python 3.13. See also https://github.com/ansible-community/images/pull/108.
CI
=> CI: Arch Linux updated to Python 3.13

changelogs/fragments/9320-fstr-cache-plugins.yml, plugins/cache/memcached.py, plugins/cache/redis.py
plugins/cache/memcached.py
plugins/cache/redis.py
=> cache plugins: use f-strings

changelogs/fragments/9318-fstr-actionplugins.yml, plugins/action/iptables_state.py, plugins/action/shutdown.py
plugins/action/iptables_state.py
plugins/action/shutdown.py
=> action plugins: use f-strings

changelogs/fragments/9334-qubes-conn.yml, plugins/connection/qubes.py
The debug statement clearly means to print stdout and stderr, but stderr is printed twice.
qubes.py
=> qubes connection plugin: fix display stmt

plugins/modules/xattr.py, plugins/modules/xbps.py, plugins/modules/xcc_redfish_command.py, plugins/modules/xenserver_facts.py, plugins/modules/xenserver_guest.py, plugins/modules/xenserver_guest_info.py, plugins/modules/xenserver_guest_powerstate.py, plugins/modules/xfconf.py, plugins/modules/xfconf_info.py, plugins/modules/xfs_quota.py, plugins/modules/xml.py
Adjust documentation blocks.
plugins/modules/xattr.py
plugins/modules/xbps.py
plugins/modules/xcc_redfish_command.py
plugins/modules/xenserver_facts.py
plugins/modules/xenserver_guest.py
plugins/modules/xenserver_guest_info.py
plugins/modules/xenserver_guest_powerstate.py
plugins/modules/xfconf.py
plugins/modules/xfconf_info.py
plugins/modules/xfs_quota.py
plugins/modules/xml.py
=> x*: adjust docs

tests/sanity/extra/action-group.json, tests/sanity/extra/action-group.json.license, tests/sanity/extra/action-group.py
Adjusted from the one in community.docker.
This avoids forgetting to add modules to the action group, or forgetting to document membership. Since a new action group is coming up (#9284) this is definitely useful.
action-groups extra sanity test
=> Add sanity test for action groups

plugins/modules/utm_aaa_group.py, plugins/modules/utm_aaa_group_info.py, plugins/modules/utm_ca_host_key_cert.py, plugins/modules/utm_ca_host_key_cert_info.py, plugins/modules/utm_dns_host.py, plugins/modules/utm_network_interface_address.py, plugins/modules/utm_network_interface_address_info.py, plugins/modules/utm_proxy_auth_profile.py, plugins/modules/utm_proxy_exception.py, plugins/modules/utm_proxy_frontend.py, plugins/modules/utm_proxy_frontend_info.py, plugins/modules/utm_proxy_location.py, plugins/modules/utm_proxy_location_info.py
plugins/modules/utm_aaa_group.py
plugins/modules/utm_aaa_group_info.py
plugins/modules/utm_ca_host_key_cert.py
plugins/modules/utm_ca_host_key_cert_info.py
plugins/modules/utm_dns_host.py
plugins/modules/utm_network_interface_address.py
plugins/modules/utm_network_interface_address_info.py
plugins/modules/utm_proxy_auth_profile.py
plugins/modules/utm_proxy_exception.py
plugins/modules/utm_proxy_frontend.py
plugins/modules/utm_proxy_frontend_info.py
plugins/modules/utm_proxy_location.py
plugins/modules/utm_proxy_location_info.py
=> utm*: normalize docs

changelogs/fragments/9321-fstr-callback-plugins.yml, plugins/callback/cgroup_memory_recap.py, plugins/callback/context_demo.py, plugins/callback/counter_enabled.py, plugins/callback/dense.py, plugins/callback/diy.py, plugins/callback/elastic.py, plugins/callback/jabber.py, plugins/callback/log_plays.py, plugins/callback/loganalytics.py, plugins/callback/logdna.py, plugins/callback/logentries.py, plugins/callback/mail.py, plugins/callback/nrdp.py, plugins/callback/opentelemetry.py, plugins/callback/say.py, plugins/callback/selective.py, plugins/callback/slack.py, plugins/callback/splunk.py, plugins/callback/timestamp.py, plugins/callback/unixy.py, plugins/callback/yaml.py
plugins/callback/cgroup_memory_recap.py
plugins/callback/context_demo.py
plugins/callback/counter_enabled.py
plugins/callback/dense.py
plugins/callback/diy.py
plugins/callback/elastic.py
plugins/callback/jabber.py
plugins/callback/log_plays.py
plugins/callback/logdna.py
plugins/callback/logentries.py
plugins/callback/mail.py
plugins/callback/nrdp.py
plugins/callback/say.py
plugins/callback/slack.py
plugins/callback/splunk.py
plugins/callback/timestamp.py
plugins/callback/unixy.py
plugins/callback/yaml.py
=> callback plugins: use f-strings

changelogs/fragments/9322-fstr-connection-plugins.yml, plugins/connection/chroot.py, plugins/connection/funcd.py, plugins/connection/incus.py, plugins/connection/iocage.py, plugins/connection/jail.py, plugins/connection/lxc.py, plugins/connection/lxd.py, plugins/connection/qubes.py, plugins/connection/saltstack.py, plugins/connection/zone.py
plugins/connection/funcd.py
plugins/connection/incus.py
plugins/connection/iocage.py
plugins/connection/jail.py
plugins/connection/lxd.py
plugins/connection/qubes.py
plugins/connection/saltstack.py
plugins/connection/zone.py
=> connection plugins: use f-strings

changelogs/fragments/9270-zypper-add-simple_errors.yaml, plugins/modules/zypper.py
This fixes #8416 
It adds a `simple_errors` option for the zypper module which can be used to simplify or reduce the error output of the zypper module during package installs/updates so that only the content of `<message>` tags are displayed.  (Default is `false` so the default behavior is unaffected)
It also adds a `quiet` option for the zypper module to allow for the option to disable the `--quiet` parameter from being passed to the zypper command. (Default is `true` so the default behavior is unaffected.
zypper module
=> zypper: add simple_errors option - fixes #8416

plugins/modules/read_csv.py, plugins/modules/redfish_command.py, plugins/modules/redfish_config.py, plugins/modules/redfish_info.py, plugins/modules/redhat_subscription.py, plugins/modules/redis.py, plugins/modules/redis_data.py, plugins/modules/redis_data_incr.py, plugins/modules/redis_data_info.py, plugins/modules/redis_info.py, plugins/modules/rhevm.py, plugins/modules/rhsm_release.py, plugins/modules/rhsm_repository.py, plugins/modules/riak.py, plugins/modules/rocketchat.py, plugins/modules/rollbar_deployment.py, plugins/modules/rpm_ostree_pkg.py, plugins/modules/rundeck_acl_policy.py, plugins/modules/rundeck_job_executions_info.py, plugins/modules/rundeck_job_run.py, plugins/modules/rundeck_project.py, plugins/modules/runit.py
plugins/modules/read_csv.py
plugins/modules/redfish_command.py
plugins/modules/redfish_config.py
plugins/modules/redfish_info.py
plugins/modules/redhat_subscription.py
plugins/modules/redis.py
plugins/modules/redis_data.py
plugins/modules/redis_data_incr.py
plugins/modules/redis_data_info.py
plugins/modules/redis_info.py
plugins/modules/rhevm.py
plugins/modules/rhsm_release.py
plugins/modules/rhsm_repository.py
plugins/modules/riak.py
plugins/modules/rocketchat.py
plugins/modules/rollbar_deployment.py
plugins/modules/rpm_ostree_pkg.py
plugins/modules/rundeck_acl_policy.py
plugins/modules/rundeck_job_executions_info.py
plugins/modules/rundeck_job_run.py
plugins/modules/rundeck_project.py
plugins/modules/runit.py
=> r*: normalize docs

plugins/modules/proxmox.py, plugins/modules/proxmox_backup.py, plugins/modules/proxmox_disk.py, plugins/modules/proxmox_domain_info.py, plugins/modules/proxmox_group_info.py, plugins/modules/proxmox_kvm.py, plugins/modules/proxmox_nic.py, plugins/modules/proxmox_node_info.py, plugins/modules/proxmox_pool.py, plugins/modules/proxmox_pool_member.py, plugins/modules/proxmox_snap.py, plugins/modules/proxmox_storage_contents_info.py, plugins/modules/proxmox_storage_info.py, plugins/modules/proxmox_tasks_info.py, plugins/modules/proxmox_template.py, plugins/modules/proxmox_user_info.py, plugins/modules/proxmox_vm_info.py, plugins/modules/pubnub_blocks.py, plugins/modules/pulp_repo.py, plugins/modules/puppet.py, plugins/modules/pushbullet.py, plugins/modules/pushover.py, plugins/modules/python_requirements_info.py
plugins/modules/proxmox.py
plugins/modules/proxmox_backup.py
plugins/modules/proxmox_disk.py
plugins/modules/proxmox_domain_info.py
plugins/modules/proxmox_group_info.py
plugins/modules/proxmox_kvm.py
plugins/modules/proxmox_nic.py
plugins/modules/proxmox_node_info.py
plugins/modules/proxmox_pool.py
plugins/modules/proxmox_pool_member.py
plugins/modules/proxmox_snap.py
plugins/modules/proxmox_storage_contents_info.py
plugins/modules/proxmox_storage_info.py
plugins/modules/proxmox_tasks_info.py
plugins/modules/proxmox_template.py
plugins/modules/proxmox_user_info.py
plugins/modules/proxmox_vm_info.py
plugins/modules/pubnub_blocks.py
plugins/modules/pulp_repo.py
plugins/modules/puppet.py
plugins/modules/pushbullet.py
plugins/modules/pushover.py …
=> [prox ... pyth]*: normalize docs

plugins/modules/ocapi_command.py, plugins/modules/ocapi_info.py, plugins/modules/oci_vcn.py, plugins/modules/odbc.py, plugins/modules/office_365_connector_card.py, plugins/modules/ohai.py, plugins/modules/omapi_host.py, plugins/modules/one_host.py, plugins/modules/one_image.py, plugins/modules/one_image_info.py, plugins/modules/one_service.py, plugins/modules/one_template.py, plugins/modules/one_vm.py, plugins/modules/one_vnet.py, plugins/modules/oneandone_firewall_policy.py, plugins/modules/oneandone_load_balancer.py, plugins/modules/oneandone_monitoring_policy.py, plugins/modules/oneandone_private_network.py, plugins/modules/oneandone_public_ip.py, plugins/modules/oneandone_server.py, plugins/modules/onepassword_info.py
plugins/modules/ocapi_command.py
plugins/modules/ocapi_info.py
plugins/modules/oci_vcn.py
plugins/modules/odbc.py
plugins/modules/office_365_connector_card.py
plugins/modules/ohai.py
plugins/modules/omapi_host.py
plugins/modules/one_host.py
plugins/modules/one_image.py
plugins/modules/one_image_info.py
plugins/modules/one_service.py
plugins/modules/one_template.py
plugins/modules/one_vm.py
plugins/modules/one_vnet.py
plugins/modules/oneandone_firewall_policy.py
plugins/modules/oneandone_load_balancer.py
plugins/modules/oneandone_monitoring_policy.py
plugins/modules/oneandone_private_network.py
plugins/modules/oneandone_public_ip.py
plugins/modules/oneandone_server.py
plugins/modules/onepassword_info.py
=> [oc ... onep]*.py: normalize docs

plugins/doc_fragments/alicloud.py, plugins/doc_fragments/attributes.py, plugins/doc_fragments/auth_basic.py, plugins/doc_fragments/bitbucket.py, plugins/doc_fragments/consul.py, plugins/doc_fragments/dimensiondata.py, plugins/doc_fragments/dimensiondata_wait.py, plugins/doc_fragments/django.py, plugins/doc_fragments/emc.py, plugins/doc_fragments/gitlab.py, plugins/doc_fragments/hpe3par.py, plugins/doc_fragments/hwc.py, plugins/doc_fragments/ibm_storage.py, plugins/doc_fragments/influxdb.py, plugins/doc_fragments/ipa.py, plugins/doc_fragments/keycloak.py, plugins/doc_fragments/ldap.py, plugins/doc_fragments/lxca_common.py, plugins/doc_fragments/manageiq.py, plugins/doc_fragments/nomad.py
Normalize doc blocks in `doc_fragments`.
plugins/doc_fragments/alicloud.py
plugins/doc_fragments/attributes.py
plugins/doc_fragments/auth_basic.py
plugins/doc_fragments/bitbucket.py
plugins/doc_fragments/consul.py
plugins/doc_fragments/dimensiondata.py
plugins/doc_fragments/dimensiondata_wait.py
plugins/doc_fragments/django.py
plugins/doc_fragments/emc.py
plugins/doc_fragments/gitlab.py
plugins/doc_fragments/hpe3par.py
plugins/doc_fragments/hwc.py
plugins/doc_fragments/ibm_storage.py
plugins/doc_fragments/influxdb.py
plugins/doc_fragments/ipa.py
plugins/doc_fragments/keycloak.py
plugins/doc_fragments/ldap.py
plugins/doc_fragments/lxca_common.py
plugins/doc_fragments/manageiq.py
plugins/doc_fragments/nomad.py
=> [a-n]*.py: normalize doc_fragments

plugins/doc_fragments/emc.py, plugins/doc_fragments/purestorage.py, plugins/doc_fragments/vexata.py
plugins/doc_fragments/emc.py
plugins/doc_fragments/purestorage.py
plugins/doc_fragments/vexata.py
=> remove extraneous doc fragments

changelogs/fragments/9256-proxmox_disk-fix-async-method-of-resize_disk.yml, plugins/module_utils/proxmox.py, plugins/modules/proxmox_disk.py
This PR closes issue #9254 which was based on PR #7969.
Method for resizing disk is now aware of using asyncronous API `PUT` endpoint and correctly handles messages about errors.
> ***Note***: *compatibility with Proxmox VE version < 8.0.0 was broken since the API was changed upstream.*
Additionally, I made a brief refactoring of methods in `proxmox_disk` module and added one new method to the `proxmox` module utility (`api_task_complete`). This method expands the `api_task_ok` method in terms of errors and timeout handling - it waits for task to complete and returns an error message if task was completed but not succesful.
proxmox_disk
```paste below
```
=> proxmox_disk: fix async method of resize_disk

changelogs/fragments/9432-deprecate-pure.yml, meta/runtime.yml
Modules supporting purestorage were removed from the collection in version 3.0.0 but the module utils and a doc fragment were left behind. This PR deprecates them.
(Additionally, this PR fixes the ordering for the old rackspace removal in those two sections of runtime.yml)
plugins/doc_fragments/purestorage.py
plugins/module_utils/pure.py
=> purestorage: deprecate leftovers

changelogs/fragments/9443-slack-prepend_hash.yml, plugins/modules/slack.py
Ref: https://github.com/ansible-collections/community.general/issues/9269#issuecomment-2549384975
slack
=> slack: deprecate current default `auto` for `prepend_hash`

changelogs/fragments/9449-manageiq-alert-profiles-reqs.yml, plugins/modules/manageiq_alert_profiles.py
Basically two changes:
* `name` is already required when state is either present or absent, and there are no other states, so making it fully required and removing the conditional
* `alerts` is documented as required when state=present, this has been verified in the code, so added that parameter to the existing `required_if` spec.
manageiq_alert_profiles
=> manageiq_alert_profiles: improve handling param requirements

changelogs/fragments/9456-yaml-callback-deprecation.yml, meta/runtime.yml, plugins/callback/yaml.py
The plugin itself has a note stating that since ansible-core 2.13 (as of Dec '24 the minimum verison of ansible-core supported by community.general) has the functionality implemented within its default callback plugin.
plugins/callback/yaml.py
=> yaml callback plugin: deprecation

changelogs/fragments/9387-pacemaker-cluster-cmd.yml, plugins/modules/pacemaker_cluster.py
While working on the doc normalization I noticed this module still used `run_command()` with a string argument, rather than a list one.
While working to fix that, I bumped into an unreported bug in the `set_node()` function. **Update:** and as it turns out, that function was not being used at all, so removing it entirely.
pacemaker_cluster
=> pacemaker_cluster: fix run_command() calls

changelogs/fragments/9425-gitlab-instance-raw-variable.yml, plugins/modules/gitlab_instance_variable.py
Adds support for the "raw" property on CI variables, which also makes the module idempotent when used against GitLab versions that support this property. Fixes #9424 
gitlab_instance_variable
=> gitlab_instance_variable: Add support for 'raw' property

.github/BOTMETA.yml, plugins/modules/ldap_inc.py, tests/integration/targets/ldap_inc/aliases, tests/integration/targets/ldap_inc/meta/main.yml, tests/integration/targets/ldap_inc/tasks/main.yml, tests/integration/targets/ldap_inc/tasks/tests/basic.yml, tests/integration/targets/setup_openldap/files/inc_schema_cnconfig.ldif, tests/integration/targets/setup_openldap/files/inc_schema_cnconfig.ldif.license, tests/integration/targets/setup_openldap/files/ldap_inc_config.ldif, tests/integration/targets/setup_openldap/files/ldap_inc_config.ldif.license, tests/integration/targets/setup_openldap/tasks/main.yml
This contribution propose to adds a module that use the ‘modify-increment’ capability corresponding to the extension implemented by OpenLdap described in RFC-4525. It can be used to increment an integer attribute and read it atomically. It is an help for managing posix userId while relying only on the directory server.
Not an issue
ldap_inc
The module uses the DN of the entry containing the "_sequence_", the attribute to increment and the increment to apply. The result of the module is the new value of "_sequence_".
=> Add module ldap inc

changelogs/fragments/9131-locale-gen-rewrite.yml, changelogs/fragments/9238-locale-gen-rewrite.yml, plugins/modules/locale_gen.py, tests/integration/targets/locale_gen/tasks/main.yml
It introduces a RV `mechanism` that declares the mode in a more descriptive way:
| ubuntu_mode | mechanism |
|--------|--------|
| False | glibc |
| True | debian |
Refer to https://github.com/ansible-collections/community.general/issues/9131#issuecomment-2526423320 for a more complete rationale.
Change the logic to determine whether `ubuntu_mode` is `True` or `False`. 
Formerly it would:
1. set `ubuntu_mode=True` if `/var/lib/locales/supported.d` existed, 
2. else `False` if `/etc/locale.gen` exists,
3. else raising an error. 
With this PR it will: 
1. set `ubuntu_mode=False` is `/etc/locale.gen` is present,
2. else `True` if the `/var/lib/...` directory exists, 
3. else error.
Canonical made a deliberate decision to move towards the glibc support, so all Ubuntu versions since 16.04 have …
=> locale_gen: fix/improvements

changelogs/fragments/9483-sensu-deprecation.yml, meta/runtime.yml, plugins/modules/sensu_check.py, plugins/modules/sensu_client.py, plugins/modules/sensu_handler.py, plugins/modules/sensu_silence.py, plugins/modules/sensu_subscription.py
The five modules in community.general seem to  have been written for Sensu Core and Sensu Enterprise editions, both of them EOL since 2019/2020, replaced by Sensu Go, which has its own collection `sensu.sensu_go`.
plugins/modules/sensu_check.py
plugins/modules/sensu_client.py
plugins/modules/sensu_handler.py
plugins/modules/sensu_silence.py
plugins/modules/sensu_subscription.py
=> sensu_*: deprecation

changelogs/fragments/9487-atomic-deprecation.yml, meta/runtime.yml, plugins/modules/atomic_container.py, plugins/modules/atomic_host.py, plugins/modules/atomic_image.py
Project Atomic was sunset by the end of 2019. The alternative for that product is, allegedly Fedora CoreOS or one of the existing ¨container-oriented" distros out there. There is no specific alternative for the Ansible modules though.
plugins/modules/atomic_container.py
plugins/modules/atomic_host.py
plugins/modules/atomic_image.py
=> atomic_*: deprecation

changelogs/fragments/9503-opentelemetry-remove-unused-code.yml, plugins/callback/opentelemetry.py
Part of https://github.com/ansible-collections/community.general/issues/9454
`OTEL_LIBRARY_TIME_NS_ERROR` was introduced at https://github.com/ansible-collections/community.general/pull/5342#discussion_r989462459 and partially removed in https://github.com/ansible-collections/community.general/pull/9482
I'm testing this PR in [here](https://github.com/v1v/otel-ansible-callback-plugin/actions/runs/12558081324) - that's a basic test framework using logs validations that I built some time ago.
=> opentelemetry callback plugin: remove unused code

changelogs/fragments/9403-redfish-add-get-accountservice.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_info.py
The AccountService endpoint provides plenty of essential configuration which might be needed to e.g. backup settings or to check the right setup.
Redfish
Example result from querying OpenBMC's bmcweb Redfish server:
```
changed: false
failed: false
redfish_facts:
accountservice_config:
entries:
'@odata.id': /redfish/v1/AccountService
'@odata.type': '#AccountService.v1_15_0.AccountService'
AccountLockoutDuration: 0
AccountLockoutThreshold: 0
Accounts:
'@odata.id': /redfish/v1/AccountService/Accounts
ActiveDirectory:
Authentication:
AuthenticationType: UsernameAndPassword
Password: null
Username: ''
LDAPService:
SearchSettings:
BaseDistinguishedNames:
- ''
GroupsAttribute: ''
UsernameAttribute: ''
RemoteRoleMapping: []
ServiceAddresses:
- ''
ServiceEnabled: false …
```
=> Redfish: implement obtaining AccountService config

.github/BOTMETA.yml
As I do not work with Sophos UTMs anymore I am no longer able to test/maintain and therfor removed 'stearz' as maintainer. I added team_e_spirit as maintainer as I think they are still using and willing to support the modules.
plugins/utm_*
n/a
=> remove stearz as maintainer

tests/unit/plugins/modules/test_cpanm.py, tests/unit/plugins/modules/test_cpanm.yaml, tests/unit/plugins/modules/test_django_check.py, tests/unit/plugins/modules/test_django_check.yaml, tests/unit/plugins/modules/test_django_command.py, tests/unit/plugins/modules/test_django_command.yaml, tests/unit/plugins/modules/test_django_createcachetable.py, tests/unit/plugins/modules/test_django_createcachetable.yaml, tests/unit/plugins/modules/test_facter_facts.py, tests/unit/plugins/modules/test_facter_facts.yaml, tests/unit/plugins/modules/test_gconftool2.py, tests/unit/plugins/modules/test_gconftool2.yaml, tests/unit/plugins/modules/test_gconftool2_info.py, tests/unit/plugins/modules/test_gconftool2_info.yaml, tests/unit/plugins/modules/test_gio_mime.py, tests/unit/plugins/modules/test_gio_mime.yaml, tests/unit/plugins/modules/test_krb_ticket.py, tests/unit/plugins/modules/test_krb_ticket.yaml, tests/unit/plugins/modules/test_opkg.py, tests/unit/plugins/modules/test_opkg.yaml, tests/unit/plugins/modules/test_puppet.py, tests/unit/plugins/modules/test_puppet.yaml, tests/unit/plugins/modules/test_snap.py, tests/unit/plugins/modules/test_xfconf.py, tests/unit/plugins/modules/test_xfconf.yaml
Applied new features of test helper to existing unit tests
tests/unit/plugins/modules/test_cpanm.yaml
tests/unit/plugins/modules/test_django_check.py
tests/unit/plugins/modules/test_django_check.yaml
tests/unit/plugins/modules/test_django_command.py
tests/unit/plugins/modules/test_django_command.yaml
tests/unit/plugins/modules/test_django_createcachetable.py
tests/unit/plugins/modules/test_django_createcachetable.yaml
tests/unit/plugins/modules/test_facter_facts.py
tests/unit/plugins/modules/test_facter_facts.yaml
tests/unit/plugins/modules/test_gconftool2.yaml
tests/unit/plugins/modules/test_gconftool2_info.yaml …
=> test helper: adjusted unit tests using new features

changelogs/fragments/9546-fix-handling-of-tap-homebrew-packages.yml, plugins/modules/homebrew.py, tests/integration/targets/homebrew/tasks/formulae.yml
=> Fix homebrew tap name handling

changelogs/fragments/9554-add-cpanm-option_with-recommands.yml, changelogs/fragments/9554-add-cpanm-option_with-recommends-and-suggests.yml, plugins/modules/cpanm.py, tests/unit/plugins/modules/test_cpanm.yaml
Fix #9554
Fixes #9554 
This PR aims to add the use of the option --with-recommands to cpanm module
```yaml
minor_changes:
- cpanm - enable usage of option --with-recommands (https://github.com/ansible-collections/community.general/issues/9554).
```
cpanm
=> Add cpanm option --with-recommends

changelogs/fragments/9547-one_template-filter.yml, plugins/modules/one_template.py
Fixes  #9278 
As discussed in the issue a filter flag was added to the `one_template` module. The default behavior is preserved by setting the `filter` option to the default value of `-3`. Users can change the behavior by using values from `-1` to `-4`.
_Edit: filter option was changed to user friendly values (user, user_groups, ...) and internally the module converts those to the integers needed for the OpenNebula API._
The description of the module was also updated with an explanation of those values.
minor_changes:
- one_template - adds ``filter`` flag for retrieving templates which are not owned by the user (https://github.com/ansible-collections/community.general/issues/9278).
one_template
See #9278 for a reproduction playbook and expected outputs.
=> add filter support for one_template module

.github/BOTMETA.yml, plugins/connection/pct_remote.py, plugins/connection/proxmox_pct_remote.py, tests/integration/targets/connection_proxmox_pct_remote/aliases, tests/integration/targets/connection_proxmox_pct_remote/dependencies.yml, tests/integration/targets/connection_proxmox_pct_remote/files/pct, tests/integration/targets/connection_proxmox_pct_remote/plugin-specific-tests.yml, tests/integration/targets/connection_proxmox_pct_remote/runme.sh, tests/integration/targets/connection_proxmox_pct_remote/test.sh, tests/integration/targets/connection_proxmox_pct_remote/test_connection.inventory, tests/unit/plugins/connection/test_proxmox_pct_remote.py, tests/unit/requirements.txt
This connection plugin uses ssh (`paramiko`) to connect to a proxmox host and then calls `pct` to connect into the LXC Proxmox container. 
I mainly inherited from `ssh_paramiko` and overwrote the main methods. 
With the new SDN functionality in proxmox we might want to  create container that are not reachable via ssh. With this plugin we can use ansible within the container without any network access to the container.
pct_remote
`pct` can only be executed as `root` this is why I put `/usr/bin/sudo` in front of it, I think this is not very clean. Is there a way to obtain the binary path from `become_method`?  Or is it possible to set `become: true` as default?
=> Proxmox remote pct connection

changelogs/fragments/9584-py3-imports-connectioninventory.yml, plugins/connection/chroot.py, plugins/connection/funcd.py, plugins/connection/incus.py, plugins/connection/iocage.py, plugins/connection/jail.py, plugins/connection/lxc.py, plugins/connection/lxd.py, plugins/connection/proxmox_pct_remote.py, plugins/connection/qubes.py, plugins/connection/saltstack.py, plugins/connection/zone.py, plugins/inventory/cobbler.py, plugins/inventory/gitlab_runners.py, plugins/inventory/icinga2.py, plugins/inventory/iocage.py, plugins/inventory/linode.py, plugins/inventory/lxd.py, plugins/inventory/nmap.py, plugins/inventory/online.py, plugins/inventory/opennebula.py, plugins/inventory/proxmox.py, plugins/inventory/scaleway.py, plugins/inventory/stackpath_compute.py, plugins/inventory/virtualbox.py, plugins/inventory/xen_orchestra.py
Change the `from __future__` imports to `annotations` only, as needed for Python 3
plugins/connection/funcd.py
plugins/connection/incus.py
plugins/connection/iocage.py
plugins/connection/jail.py
plugins/connection/lxd.py
plugins/connection/proxmox_pct_remote.py
plugins/connection/qubes.py
plugins/connection/saltstack.py
plugins/connection/zone.py
plugins/inventory/gitlab_runners.py
plugins/inventory/icinga2.py
plugins/inventory/iocage.py
plugins/inventory/linode.py
plugins/inventory/lxd.py
plugins/inventory/nmap.py
plugins/inventory/online.py
plugins/inventory/opennebula.py
plugins/inventory/stackpath_compute.py …
=> connection/inventory: adjust import __future__ for Python3

changelogs/fragments/9585-py3-imports-filter.yml, plugins/filter/counter.py, plugins/filter/crc32.py, plugins/filter/dict.py, plugins/filter/dict_kv.py, plugins/filter/from_csv.py, plugins/filter/from_ini.py, plugins/filter/groupby_as_dict.py, plugins/filter/hashids.py, plugins/filter/jc.py, plugins/filter/json_query.py, plugins/filter/keep_keys.py, plugins/filter/lists.py, plugins/filter/lists_mergeby.py, plugins/filter/random_mac.py, plugins/filter/remove_keys.py, plugins/filter/replace_keys.py, plugins/filter/reveal_ansible_type.py, plugins/filter/time.py, plugins/filter/to_ini.py, plugins/filter/unicode_normalize.py, plugins/filter/version_sort.py, tests/unit/plugins/filter/test_crc32.py
Change the `from __future__` imports to `annotations` only, remove `__metaclass__`, as needed for Python 3.
plugins/filter/counter.py
plugins/filter/crc32.py
plugins/filter/dict.py
plugins/filter/dict_kv.py
plugins/filter/from_csv.py
plugins/filter/from_ini.py
plugins/filter/groupby_as_dict.py
plugins/filter/hashids.py
plugins/filter/jc.py
plugins/filter/json_query.py
plugins/filter/keep_keys.py
plugins/filter/lists.py
plugins/filter/lists_mergeby.py
plugins/filter/random_mac.py
plugins/filter/remove_keys.py
plugins/filter/replace_keys.py
plugins/filter/reveal_ansible_type.py
plugins/filter/time.py
plugins/filter/to_ini.py
plugins/filter/unicode_normalize.py
plugins/filter/version_sort.py
tests/unit/plugins/filter/test_crc32.py
=> filter plugins: adjust import __future__ for Python3, remove __metaclass__

changelogs/fragments/9578-redhat_subscription-no-remove-on-unregister.yml, plugins/modules/redhat_subscription.py, tests/unit/plugins/modules/test_redhat_subscription.py
Unregistering a system also drops all the resources for it automatically, so there is no need to manually unsubscribing (which actually means removing all the subscriptions).
In addition to that, newer versions of subscription-manager drop all the support for entitlements, so the "remove" subcommand (used by unsubscribe()) does not exist anymore, and thus the unregistration fails with those versions.
This fixes the registration on EL 10 systems, and Fedora 41 and greater.
=> redhat_subscription: stop manual unsubscribing on unregistration

changelogs/fragments/9570-feat-nmcli-add-fail-over-mac-parameter.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
Missing fail_over_mac parameter in the module ncmli, this PR is to make this parameter available.
Fixes #9570
`nmcli`
```
#collections_paths = ./local
[defaults]
keep_remote_files = True
private_key_file = home/REDACTED/.ssh/id_ed25519
host_key_checking = False
pipelining = True
control_path = /tmp/ansible-ssh-%%h-%%p-%%r
```
```
all:
children:
blue:
hosts:
r1.incus
```
```
---
- name: Test nmcli bond configuration with fail_over_mac parameter
hosts: all
become: true
gather_facts: true
tasks:
- name: Configure bond0 interface with fail_over_mac parameter
type: bond
conn_name: bond0
ifname: bond0
ip4: 192.168.1.10/24
gw4: 192.168.1.1
mode: active-backup
miimon: 100
fail_over_mac: 1
state: present
```
```paste below
$ ANSIBLE_FORCE_COLOR=False …
```
=> feat(nmcli): support the fail_over_mac parameter

changelogs/fragments/9582-add-support-for-vrrp.yml, plugins/modules/ufw.py
Added the vrrp to list proto.
Changes made as described in #9562
Fixes #9562
plugins/modules/ufw.py
=> ufw: added support for vrrp protocol

changelogs/fragments/9573-iocage-inventory-sudo.yml, plugins/inventory/iocage.py
Implement #9572 Add parameter sudo to inventory plugin iocage.
iocage.py
Tested in Ubuntu 24.04
```bash
shell> ansible-test units --venv --python 3.12 tests/unit/plugins/inventory/test_iocage.py
Installing requirements for Python 3.12 [venv]
Unit test controller with Python 3.12
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.3.4, pluggy-1.5.0
rootdir: /export/scratch/collections/ansible_collections/community/general
configfile: ../../../../../../tmp/ansible-test-h6dmhd94/ansible_test/_data/pytest/config/default.ini
plugins: mock-3.14.0, xdist-3.6.1
created: 4/4 workers
4 workers [5 items]
.....                                                                    [100%]
- generated xml file: …
```
=> Implement #9572 Add parameter sudo to inventory plugin iocage

changelogs/fragments/9608-apache2-mod-proxy-revamp3.yml, plugins/modules/apache2_mod_proxy.py
Improve readability of code by receiving the result of `fetch_url` as a tuple of variables instead of a single variable that is used with indexes later.
=> apache2-mod-proxy: receive results from fetch_url as tuple of vars

changelogs/fragments/9600-apache2-mod-proxy-revamp2.yml, plugins/modules/apache2_mod_proxy.py
Parameter `state` is a `str`, but it is parsed for comma separated values with a fixed set of values allowed. Transforming that into a `list` of `str` elements makes the code simpler.
=> apache2-mod-proxy: make state option a list

changelogs/fragments/9621-keycloak_client-sanitize-saml-encryption-key.yml, plugins/modules/keycloak_client.py
The module sanitizes only `saml.singning.private.key`, but not `saml.encryption.private.key`. 
shortened output before PR:
```
{
"attributes": {
"saml.encrypt": "true",
"saml.encryption.certificate": "MIICoTCCAYk [...] BDJpxpqdXeRw=",
"saml.encryption.private.key": "MIIEpAIBA [...] FYUiJ8nmzMfZLGtMs3bAtDpg==",
"saml.signing.certificate": "MIICoTC [...] RT9mk1UYNU=",
"saml.signing.private.key": "no_log",
"saml_force_name_id_format": "false"
}
}
```
=> keycloak_client: sanitize `saml.encryption.private.key`

changelogs/fragments/9225-proxmox-module-refactoring.yml, plugins/module_utils/proxmox.py, plugins/modules/proxmox.py
This pull request refactors the historically grown `proxmox` module.
The control flow was very opaque with some redundant checks and - most recently - features that were only introduced in parts of the module when they intended to target the whole module (see #9065).
This refactor aims to make the module more readable and more easily extendable.
Additionally, this request contains various bug fixes:
- From #9065: The `disk_volume` key is now properly parsed and passed on to the API
- From #8982: It is now possible to add bind-only mount points again.
- From #8811: Converting an LXC to a template is now idempotent.
- From #9055: The default value of `update=False` is now deprecated and will be changed to `update=True` in version 11.0.0
- In the `proxmox` utils module: The parameter …
=> Proxmox module refactoring

changelogs/fragments/9623-pipx-global-latest.yml, plugins/modules/pipx.py, tests/integration/targets/pipx/tasks/main.yml, tests/integration/targets/pipx/tasks/testcase-9619-latest-global.yml
Honour `global` parameter when `state=latest`.
Fixes #9619
pipx
=> pipx: use global in state=latest

changelogs/fragments/9633-onepassword_ssh_key.yml, plugins/lookup/onepassword_ssh_key.py
Follow-up to #9580.
This way it's not necessary to inherit from from `OnePassCLIv2`.
@mohammedbabelly20 what do you think?
onepassword_ssh_key lookup
=> onepassword_ssh_key: avoid inheriting from OnePassCLIv2

changelogs/fragments/9645-proxmox-fix-pubkey.yml, plugins/modules/proxmox.py
proxmox
fixes https://github.com/ansible-collections/community.general/issues/9642
```paste below
```
=> proxmox: fix pubkey translation and usage in update

changelogs/fragments/9649-cloudflare_dns-fix-crash-when-deleting-record.yml, plugins/modules/cloudflare_dns.py
On 2025-01-27, Cloudflare removed the `zone_id` field from the DNS record API responses. This caused a `KeyError` in the `delete_dns_records` method, which previously relied on `rr['zone_id']`.
This commit ensures the zone ID is retrieved via `_get_zone_id()` rather than using the no-longer-provided `zone_id` field in the record response.
Reference: https://developers.cloudflare.com/dns/changelog/#2025-01-27
cloudflare_dns
before fix:
`cfdnstest.yaml`
```yaml
- name: test cloudflare_dns
vars:
cloudflare_key_path: "cloudflare-token.txt"
dns_name: cfrecordtest
proxied_dns_zone: scopeful.io
dest_1: "2a01:4f9:6b:4721::1"
dest_2: "2a01:4f9:6b:4721::2"
tasks:
- name: "Create proxied AAAA record {{ dns_name }}.{{ proxied_dns_zone }} => {{ …
```
=> cloudflare_dns: fix crash when deleting a DNS record or when updating a record with solo=true

plugins/modules/lvol.py
The second sentence to the `force` parameter's description needed some wordsmithing.
`plugins/modules/lvol.py`
=> lvol: fix the force parameter's description

tests/unit/plugins/modules/helper.py
Parameter `mocks` was not being passed from `Helper.from_module()` to `Helper.from_file()` as it should.
=> test helper: fix parameter passing in creation static method

tests/unit/plugins/modules/helper.py, tests/unit/plugins/modules/test_gio_mime.yaml
Add support for `check` and `diff` flags in test helper.
tests/unit/plugins/modules/test_gio_mime.yaml
=> test helper: add support for check and diff modes

changelogs/fragments/9644-kc_client-test-improvement-and-fix.yaml, plugins/modules/keycloak_client.py, tests/integration/targets/keycloak_client/vars/main.yml
Fix and improve existing tests for `keycloak_client` module
Run `ansible-test integration -v keycloak_client --allow-unsupported --docker fedora40 --docker-network host`
Before:
```
[...]
TASK [keycloak_client : Assert changes not detected in last two tasks (desire when same, and check)] ***
task path: /root/ansible_collections/community/general/tests/output/.tmp/integration/keycloak_client-p3ttqf7d-ÅÑŚÌβŁÈ/tests/integration/targets/keycloak_client/tasks/main.yml:79
fatal: [testhost]: FAILED! => {
"assertion": "check_client_when_present_and_same is not changed",
"evaluated_to": false,
"msg": "Assertion failed"
}
[...]
```
After:
```
[...]
TASK [keycloak_client : Assert changes not detected in last two tasks (desire when same, and …
```
=> Fb keycloak client improvement

tests/unit/plugins/modules/helper.py, tests/unit/plugins/modules/test_snap.py
changes:
- methods `from_module()`, `from_file()` and `from_spec()` now all have a similar order of parameters
- `from_module()` tries extensions `.yaml` and `.yml` before giving up
- remove redundant parameter `test_spec` from `from_module()`
- `from_file()` now receives an open, readable, file handle instead of a filename
- `Helper` no longer accepts a test specification that is a top-level list of testcases, it must be a dict containing the key `test_cases`, which will be the list.
- test_snap.py adjusted for the change in `from_spec()`
=> test helper: improvements

tests/unit/plugins/modules/helper.py
Remove unnecessary magic function to retrieve a reference to the TestCaseMock class from the test module, instead relying on the user passing that reference when instantiating ``Helper``.
=> test helper: remove magically finding the testcasemock in the test module

tests/integration/targets/snap/aliases
Tests are broken for them currently, so deactive them.
Ref: #9656
snap
=> Disable snap tests on RHEL 8.8

tests/integration/targets/filesystem/tasks/main.yml, tests/integration/targets/filesystem/tasks/setup.yml
The tests currently fail because of that.
filesystem
=> filesystem tests: reiserfsprogs is no longer available on Arch Linux

changelogs/fragments/9691-keycloak-module-utils-replace-missing-return-in-get_role_composites.yml, plugins/module_utils/identity/keycloak/keycloak.py
Fixes #9678.
Replaces a `return` accidentally removed by #9494.
module_utils/identity/keycloak
=> keycloak module utils replace missing return in `get_role_composites`

tests/integration/targets/copr/aliases
The copr tests are currently failing:
```
01:23 fatal: [testhost]: FAILED! => {
01:23     "changed": false,
01:23     "invocation": {
01:23         "module_args": {
01:23             "chroot": "epel-9-x86_64",
01:23             "excludepkgs": null,
01:23             "host": "copr.fedorainfracloud.org",
01:23             "includepkgs": null,
01:23             "name": "gotmax23/community.general.copr_integration_tests",
01:23             "protocol": "https",
01:23             "state": "enabled"
01:23         }
01:23     },
01:23     "msg": "This repository does not have any builds yet so you cannot enable it now."
01:23 }
```
copr
=> Disable failing copr tests

changelogs/fragments/9658-add-vrf-commands-to-nmcli-module.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
Adding VRF support and documentation to the nmcli module
Fixes #8014 
community.general.nmcli
```paste below
```
=> Update nmcli.py to support VRF commands

changelogs/fragments/9698-lvg-remove-extra-pvs-parameter.yml, changelogs/fragments/XXXX-lvg-remove-extra-pvs-parameter.yml, plugins/modules/lvg.py, tests/integration/targets/lvg/tasks/main.yml, tests/integration/targets/lvg/tasks/test_remove_extra_pvs.yml
Add parameter `remove_extra_pvs` to allow ansible to keep extra physical volumes on volume groups.  
Currently ansible removes all phyisical volumes that are not given in the `pvs` parameter.  
Setting `remove_extra_pvs` to `False` allows one to manage a volume group in ansible and to extend it outside of ansible with additional PVs.  
`remove_extra_pvs`  default parameter is set to `True` so it does not change current behavior.
lvg
=> lvg: Add parameter to disable removal of extra physical volumes

changelogs/fragments/6264-zfs-multiline-property-value.yml, plugins/modules/zfs.py
Fixes ZFS module which breaks if ZFS dataset property contains multi-line value.
The root cause is a bug in zfs.py that causes parsing error of 'zfs get' output. The ZFS module uses 'zfs get -H -p -o property,value,source all dataset' to retrieve from dataset list of its property names, their values and source (whether the property was set locally or inherited for example). However, the problem is the output in value field can contain control characters like \n or \t. This causes ambiguity since the same characters are used to separate properties and fields on a line. The output of 'zfs get all' is basically not parseable as it contains values of multiple properties. One needs to use 'zfs get individual_property' to get single property value to avoid ambiguity.
Test case:
```
- name: …
```
=> zfs: fix multi-line value in user-defined property

changelogs/fragments/9625-onepassword_doc.yml, plugins/lookup/onepassword.py, plugins/lookup/onepassword_doc.py
It seems that when #7116 and #7490 were merged, onepassword_doc.py ended up with the CLI parameters from `OnePassCLIv2.get_raw()` before 1Password Connect support was merged for onepassword.py. I'm not 100% sure all these parameters work with docs as well, but I think it's better to move adding these parameters to a separate function so it can be used from other derivatives of `OnePassCLIv2`.
@samdoran would be great if you could take a look :)
onepassword_doc
=> onepassword_doc: fix 1Password Connect support

changelogs/fragments/9694-ipa-host-certificate-revoked.yml, plugins/modules/ipa_host.py
Fix #9693
Before this change, existing host certificates will be revoked even if the `user_certificates` option was not given. This contradicts the module documentation.
ipa_host
Fixes #9693
=> ipa_host: Maintain the host certificates

changelogs/fragments/9729-redfish-fullpowercycle-command.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_command.py
Add support for new DMTF Redfish "FullPowerCycle" which provides the equivalent of a full A/C power pull of a server (not just restarting the system).
Fixes #9683
Running the following now works:
```
- name: Redfish FullPowerCycle
community.general.redfish_command:
command: PowerFullPowerCycle
baseuri: "{{ bmc_address }}"
resource_id: "Self"
username: "{{ bmc_username }}"
password: "{{ bmc_password }}"
register: redfish_fullcycle
until: redfish_fullcycle is successful
```
Sample task:
```
TASK [Redfish FullPowerCycle] ****************************************************************************************************************************************************************************
Tuesday 11 February 2025  15:58:27 +0000 …
```
=> Add `FullPowerCycle` to Power commands

changelogs/fragments/9727-keycloak-module-integration-tests-remove-jinja2-templating-in-conditionals.yaml, tests/integration/targets/keycloak_clientsecret_info/tasks/main.yml, tests/integration/targets/keycloak_clientsecret_regenerate/tasks/main.yml, tests/integration/targets/keycloak_role/tasks/main.yml, tests/integration/targets/keycloak_user_federation/tasks/main.yml, tests/integration/targets/keycloak_user_rolemapping/tasks/main.yml
Fix warnings and failures in keycloak module integration tests caused by use of jinja2 templating in conditionals.
Fixes #9726.
keycloak_clientsecret_info, keycloak_clientsecret_regenerate, keycloak_role, keycloak_user_federation, keycloak_user_rolemapping
To run the test, first start Keycloak:
```sh
docker run --rm --name mykeycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=password quay.io/keycloak/keycloak:latest start-dev --http-relative-path /auth
```
Then run one of the affected integration tests, e.g.,
```sh
ansible-test integration keycloak_role --allow-unsupported -vvv
```
Sample of existing test behaviour (in this case, causing a failure in the `keycloak_role` module tests):
```console
TASK [keycloak_role : Assert client role created] …
```
=> keycloak: repair integration tests by removing jinja2 templating from conditionals (#9726)

changelogs/fragments/9728-bitwarden-collection-name-filter.yml, plugins/lookup/bitwarden.py, tests/unit/plugins/lookup/test_bitwarden.py
This PR adds two new option to the bitwarden lookup:
-  collection_name: Allows to filter results by bitwarden collection name instead of ID. This is especially usefull if your bitwarden is organized similar to your inventory structure, since it enables mapping bitwarden credentials from collection to inventory without having to lookup the exact collection IDs.
- result_count: This option allows to validate the number of results in your bitwarden lookup. While this would also be possible using ansible.builtin.assert, this is way more convenient to use when integrated into the lookup directly and helps to avoid password mismatches (or to detect if a required password isn't set in bitwarden yet)
lookup / bitwarden
```paste below
```
=> bitwarden lookup: add options to filter by collection_name and validate number of results

changelogs/fragments/9739-keycloak_client-compare-before-desired-directly.yml, plugins/modules/keycloak_client.py
In check mode the keycloak_client module does not reliably detect changes to lists, because of the used `is_included_in_struct` method.
As long as all items in the desired list are in the before(existing) list no changes are detected. Even if there are additional items in the before list, the `changed` status is still `false`.
I think it would be better to directly compare the two dicts, to detect whether there are additional items in the before list that are not in the desired list. 
The issue with variables not set in the invocation, because they should not be changed in keycloak, is already addressed by copying the `before_client` and updating it with the desired changes.
Add additional URLs to the list of web origins or redirect URIs in the WebGUI …
=> keycloak_client: compare desired and before dicts directly in checkmode

changelogs/fragments/9743-incus_connection-nonroot-user.yml, plugins/connection/incus.py
Currently the incus connection only supports connecting to an instance as root. This PR extends the plugin to allow a non-root user, configurable via the ansible_user var to connect to the instance. The option incus_become_method controls the command used to switch users, (su by default but could also be sudo -u). The defaults ensure the old behavior so this should be a non-breaking change.
incus_connection
Replicates functionality from https://github.com/ansible-collections/community.general/pull/9659 for the incus plugin
=> incus_connection: Allow non-root users to connect to an instance

changelogs/fragments/9760-proxmox-inventory.yml, plugins/inventory/proxmox.py
Updated cache logic according to Anible's dynamic inventory description
Fixes #9710
bugfixes:
- proxmox inventory plugin did not update inventory correctly after meta refresh_inventory. 
proxmox inventory
Details see https://github.com/ansible-collections/community.general/issues/9710
```paste below
```
=> proxmox inventory: proposal for #9710 (caching)

changelogs/fragments/9762-apache2_mod_proxy.yml, plugins/modules/apache2_mod_proxy.py, tests/integration/targets/apache2_mod_proxy/aliases, tests/integration/targets/apache2_mod_proxy/meta/main.yml, tests/integration/targets/apache2_mod_proxy/tasks/main.yml, tests/integration/targets/apache2_module/meta/main.yml, tests/integration/targets/apache2_module/tasks/main.yml, tests/integration/targets/setup_apache2/tasks/main.yml
Right now the module needs BeautifulSoup 3, which only works on Python 3.
Fixes #4167.
Ref: #9457, #7455
=> Make apache2_mod_proxy work with Python 3, half-way modern Apache 2 versions, and add basic tests

plugins/modules/apache2_mod_proxy.py
#9772 showed that something isn't right with Python 2.7. (Apparently no Python 2.7 tests are run with `stable-10` and `main`?)
=> apache2_mod_proxy: follow-up for #9762, forgot one place with find_all/findAll

changelogs/fragments/9762-apache2_mod_proxy.yml, plugins/modules/apache2_mod_proxy.py, tests/integration/targets/apache2_mod_proxy/aliases, tests/integration/targets/apache2_mod_proxy/meta/main.yml, tests/integration/targets/apache2_mod_proxy/tasks/main.yml, tests/integration/targets/apache2_module/meta/main.yml, tests/integration/targets/apache2_module/tasks/main.yml, tests/integration/targets/setup_apache2/tasks/main.yml
Backport of #9762 to stable-9.
There was a small conflict in the documentation.
=> [stable-9] Make apache2_mod_proxy work with Python 3, half-way modern Apache 2 versions, and add basic tests

changelogs/fragments/9106-passwordstore-fix-subkey-creation-even-when-create-==-false.yml, plugins/lookup/passwordstore.py
Prevent passwordstore lookup to create subkey when create == false
Fixes #9105
passwordstore lookup
=> bugfix - Prevent passwordstore lookup to create subkey when create == false

changelogs/fragments/9778-redhat_subscription-ensure-to-enable-content.yml, plugins/modules/redhat_subscription.py
This makes sure that subscription-manager always enables the content for the system right after the registration.
This is particular important on EL 10+ and Fedora 41+.
subscription_manager
=> redhat_registration: use 'enable_content' D-Bus option when available

changelogs/fragments/9774-fix-elasticsearch_plugin-proxy-settings.yml, plugins/modules/elasticsearch_plugin.py
Fixes #9773
elasticsearch_plugin
=> Fix proxy settings for elasticsearch_plugin.py

docs/docsite/rst/filter_guide_selecting_json_data.rst
Typo: everything is cluster1 but the actual query
doc community.general.json_query
```paste below
```
=> json_query filter docs: fix typo cluster2 when cluster1 is mentioned

changelogs/fragments/ssh_config_add_other_options.yml, plugins/modules/ssh_config.py, tests/integration/targets/ssh_config/tasks/options.yml
Adds `other_options` to ssh_config module to allow arbitrary ssh config options to be added to each new entry, as per issue [8053](https://github.com/ansible-collections/community.general/issues/8053)
ssh_config
Usage example with`other_options` set shown below
```
- name: Add a host in the configuration
community.general.ssh_config:
user: akasurde
host: "example.com"
hostname: "github.com"
identity_file: "/home/akasurde/.ssh/id_rsa"
port: '2223'
state: present
other_options:
serveraliveinterval: '30'
serveralivecountmax: '10'
```
=> Ssh config other options

tests/integration/targets/locale_gen/aliases, tests/integration/targets/locale_gen/tasks/main.yml
=> locale_gen: enable tests for Arch Linux, make sure they don't even try to run on RHEL and Fedora VMs

changelogs/fragments/9657-lldp-handling-attributes-defined-multiple-times.yml, plugins/modules/lldp.py
This fixes crashes when the lldpctl output has lines for unknown tlvs that redefine a key in the middle of the nested dict data structure.
Also adds a function to handle attributes that are defined multiple times.
When the lldpctl command outputs something like the following the module crashes with the following error
**Traceback**
```
File "/home/autom8/.ansible/tmp/ansible-tmp-1738338445.7424972-37051-54323009070053/AnsiballZ_lldp.py", line 107, in <module>
File "/home/autom8/.ansible/tmp/ansible-tmp-1738338445.7424972-37051-54323009070053/AnsiballZ_lldp.py", line 99, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File "/home/autom8/.ansible/tmp/ansible-tmp-1738338445.7424972-37051-54323009070053/AnsiballZ_ll …
```
=> lldp: Handling attributes that are defined multiple times

changelogs/fragments/9769-xoa_allow_using_names_in_inventory.yml, changelogs/fragments/9787-xoa_allow_using_names_in_inventory.yml, plugins/inventory/xen_orchestra.py, tests/unit/plugins/inventory/test_xen_orchestra.py
This is a redo of a previously closed PR where I messed up git rebase and figured it would be quicker to just make a new PR with a fresh branch.
( https://github.com/ansible-collections/community.general/pull/9767 )
Currently the inventory entry names are created exclusively using UUID's as the inventory items name.
Sometimes we would prefer to use the Host/VM names in the inventory so I've added some options to allow adding Hosts/VMs using their names (name_labels) instead of their UUIDs from Xen.
By default UUID's will be used just like how it currently exists.
If you set use_vm_uuids or use_host_uuids to false then names will be used instead.
Currently since every VM is using UUIDs this means you cannot use host patterns/limits for controlling where your jobs run (as far as I know) and …
=> Allow Xen Host and/or Xen VM names instead of their UUIDs

changelogs/fragments/9457-apache2-mod-proxy-revamp.yml, plugins/modules/apache2_mod_proxy.py
Simplified the module, but keeping the exact same logic
=> apache2_mod_proxy: big revamp

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/python_requirements_info/tasks/main.yml
ansible-core devel's ansible-test replaced macOS 14.3 with 15.3.
Ref: https://github.com/ansible/ansible/pull/84665
Ref: https://forum.ansible.com/t/40650
CI
=> CI: Add macOS 15.3

changelogs/fragments/9768-keycloak_realm-remove-id-requirement.yaml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_realm.py
The keycloak_realm module requires an id when creating a new realm. I think it is better to let keycloak generate the id, like when creating a realm in the GUI. 
Using the module with older keycloak versions that require an id would still be possible, but it would also allow users to create realms with uuids generated by keycloak.
keycloak_realm
=> keycloak_realm: remove realm id requirement

changelogs/fragments/9818-cloudflare-dns-exhausted-response.yml, plugins/modules/cloudflare_dns.py
When fetch_url encouters http error, it will [exhaust the response stream](https://github.com/ansible/ansible/blob/01ca9b1d0ec882f5eea7fc42ef7f7dab9ea76d19/lib/ansible/module_utils/urls.py#L1288), and record the response body in [info['body']](https://github.com/ansible/ansible/blob/01ca9b1d0ec882f5eea7fc42ef7f7dab9ea76d19/lib/ansible/module_utils/urls.py#L1301)
Let's account for that by trying to fall back on `[info['body']` when response stream reads empty.
Related to https://github.com/ansible-collections/community.general/issues/9782
- cloudflare_dns
Before:
```text
"msg": "API bad request; Status: 400; Method: POST: Call: /zones/REDACTED/dns_records"
}
```
After:
```text …
```
=> cloudflare_dns: handle exhausted response stream in case of http error

changelogs/fragments/9824-redfish-implement-obtaining-powerrestorepolicy.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_info.py
This property ("The desired power state of the system when power is restored after a power loss.") was added in ComputerSystem.v1_6_0 which became part of 2018.3 Redfish release.
Example result from querying OpenBMC's bmcweb Redfish server:
```
entries:
-   -   system_uri: /redfish/v1/Systems/system
- AlwaysOff
ret: true
```
=> Redfish: implement obtaining PowerRestorePolicy (#9824)

plugins/modules/homebrew_services.py
Maybe this was mixed up with the _brew_service_state() function? I get this error as-written:
```
fatal: [eahmm3]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (community.general.homebrew_services) module: service
_state. Supported parameters include: name, path, state (formula)."}
```
homebrew_services
=> Example typo in homebrew_services.py

tests/integration/targets/homebrew_services/aliases
For some reason, homebrew services no longer works on these OS versions in our CI.
homebrew_services
=> homebrew_services: skip tests on macOS 13.2 and 14.3

.github/BOTMETA.yml, plugins/module_utils/pacemaker.py, plugins/modules/pacemaker_resource.py, tests/unit/plugins/modules/test_pacemaker_resource.py, tests/unit/plugins/modules/test_pacemaker_resource.yaml
Adds in pacemaker_resource plugin for managing pacemaker cluster resources.
pacemaker_resource
```paste below
```
=> add pacemaker_resource plugin

tests/integration/targets/cmd_runner/library/cmd_echo.py
Modules exiting by exception resulting in crashing the module before the data tagging PR. Unfortunately the tests relied on the old behavior.
Modules that support ansible-core before data tagging should never crash intentionally, and if they do, should not rely on anything except that the task fails.
Extracted from #9833.
cmd_runner integration tests
=> cmd_runner tests: fix reliance on unspecified behavior

changelogs/fragments/9845-consul_token_idempotency.yml, plugins/modules/consul_token.py, tests/integration/targets/consul/tasks/consul_token.yml
Fixes #9841
consul_token
```paste below
```
=> Fix roles/policies normalization in consul_token.

changelogs/fragments/9836-option-for-http-agent-for-user-to-callback-slack.yml, plugins/callback/slack.py
Adding the option for http agent for user for the slack callback. This solves the existing issue [Callback slack is not using the default ansible http agent ](https://github.com/ansible-collections/community.general/issues/9813)
Fixes #9813
plugins/callback/slack.py
Edits as [Akasurde's](https://github.com/Akasurde) suggestion. 
```
=> Adds option for http agent for user in slack callback

tests/unit/plugins/modules/test_pacemaker_resource.yaml
Circling back on the comment at:
https://github.com/ansible-collections/community.general/pull/9531#discussion_r1941499903
Trying to test passing `null` as value (instead of empty) in the YAML file used by UTHelper.
It has worked in local tests, submitting to the CI to check if it blows up in any combination of Python/Ansible.
pacemaker_resource
=> pacemaker unit test: passing null with UTHelper

changelogs/fragments/9837-redfish-implement-setting-powerrestorepolicy.yml, plugins/module_utils/redfish_utils.py, plugins/modules/redfish_config.py
This property ("The desired power state of the system when power is restored after a power loss.") was added in ComputerSystem.v1_6_0 which became part of 2018.3 Redfish release.
Tested against an OpenBMC system running bmcweb Redfish server making sure the policy is updated only when needed and that errors and messages are propogated properly.
=> Redfish: implement setting PowerRestorePolicy

.github/BOTMETA.yml, changelogs/fragments/9821-systemd_info-add-wildcards.yml, plugins/module_utils/systemd.py, plugins/module_utils/systemd_info.py, plugins/modules/systemd_info.py, tests/integration/targets/systemd_info/tasks/tests.yml
This PR adds support for wildcard expressions.
Examples:
```yaml
- name: Gather info of units that start with 'systemd-'
community.general.systemd_info:
unitname:
- 'systemd-*'
register: results
```
- Added new line in main description.
- Added new line in `unitname` description
- Added new example
- Added new integration tasks to test wildcard expressions and duplicates
systemd_info
```paste below
```
=> systemd_info - add wildcards support

changelogs/fragments/9849-nmap_dns_servers.yml, changelogs/fragments/nmap_dns_servers.yml, plugins/inventory/nmap.py
minor_changes:
- community.general.nmap - adds ``dns_servers`` option for specifying DNS servers for name resolution. Accepts hostnames or IP addresses in the same format as the ``except`` option.
nmap.yml
```command
---
plugin: community.general.nmap
address: 10.10.10.0/24
dns_servers: 10.10.10.11
```
=> NMAP Inventory Plugin: Added option for specifying DNS servers for name resolution

changelogs/fragments/9847-Adding_audio_device-support_to_proxmox_kvm.yml, plugins/modules/proxmox_kvm.py
When updating a PROXMOX VM hardware, it was not possible to add an audio device.
This patch enable to update KVM with a hardware audio device.
Feature Pull Request for "adding support for adding proxmox audio and usb ports via spice #5192"
proxmox_kvm
BEFORE : Audio device was unsupported with message :
```
FAILED! => {"changed": false, "msg": "Unsupported parameters for (community.general.proxmox_kvm) module: audio. Supported parameters include: acpi, agent, api_host, api_password, api_port, api_token_id, api_token_secret, api_user, archive, args, autostart, balloon, bios, boot, bootdisk, cicustom, cipassword, citype, ciupgrade, ciuser, clone, cores, cpu, cpulimit, cpuunits, delete, description, digest, efidisk0, force, format, freeze, full, hookscript, hostpci, hotplug, hugepages, ide, …
```
=> Adding Audio device support to proxmox_kvm

changelogs/fragments/homebrew_cask.yml, plugins/modules/homebrew_cask.py, tests/unit/plugins/modules/test_homebrew_cask.py
* Use regex to parse unusual brew version strings
Fixes: #8432
=> homebrew_cask: Handle unusual brew version strings

changelogs/fragments/9891-systemd_info-add_timer.yml, plugins/modules/systemd_info.py, tests/integration/targets/systemd_info/tasks/tests.yml
This PR extends **`systemd_info`** support to **`timer`** units. 
Example:
```yaml
- name: Gather info of systemd-tmpfiles-clean.timer and extra AccuracyUSec
community.general.systemd_info:
unitname:
- systemd-tmpfiles-clean.timer
extra_properties:
- AccuracyUSec
register: results
```
In addition, it also fulfills the requirements outlined in the description of Feature Idea #4896.
- added timers to **`determine_category()`**
- added timers to **`get_category_base_props()`**
- added timers to **`unit_types[]`**
- updated the main **`description`** and the one for **`unitname`**
- added new steps to the **`integration`** test tasks
Additionally, I wanted to update the description to clarify how the property values are collected, in order to avoid any misunderstandings for users.
Fixes #4896 …
=> systemd_info - extend support to timer unit

tests/integration/targets/sysrc/tasks/main.yml
Seems to fail on FreeBSD 13.3 now as well:
- https://dev.azure.com/ansible/community.general/_build/results?buildId=140368&view=logs&j=cca960fa-8b56-5d5b-2101-d10f9d7d8d91&t=43b0dc61-bb49-56ab-e70c-fc121671321c&l=5832
- https://dev.azure.com/ansible/community.general/_build/results?buildId=140389&view=logs&j=cca960fa-8b56-5d5b-2101-d10f9d7d8d91&t=43b0dc61-bb49-56ab-e70c-fc121671321c&l=5844
- https://dev.azure.com/ansible/community.general/_build/results?buildId=140390&view=logs&j=cca960fa-8b56-5d5b-2101-d10f9d7d8d91&t=43b0dc61-bb49-56ab-e70c-fc121671321c&l=5847
sysrc tests
=> sysrc: extend the list of FreeBSD releases where the jail test fails

changelogs/fragments/9892-vmadm-add-new-options.yml, changelogs/fragments/9892-vmadm-add-optional-options.yml, plugins/modules/vmadm.py
This PR adds 2 additional options that are available to users in `vmadm`: `flexible_disk_size` and `owner_uuid`.
plugins/modules/vmadm.py
=> vmadm - Add new options

plugins/modules/copr.py
Add an example on how to install caddy using `includepkgs`. This also serves as an example on how to mimic a dnf copr enable without a specified chroot (i.e. fedora-LATEST).
Closes #9879 
copr
=> Add caddy example to copr module

changelogs/fragments/9893-cmdrunner-as-fixed-args.yml, docs/docsite/rst/guide_cmdrunner.rst, plugins/module_utils/cmd_runner_fmt.py
The function `cmd_runner_fmt.as_fixed()` now accepts an arbitrarily sized list as argument, while retaining backward compatibility.
plugins/module_utils/cmd_runner_fmt.py
=> cmd_runner_fmt.as_fixed() now accepts list of args

changelogs/fragments/9882-fix-payload-to-match-rocketchat-740-requirement.yml, plugins/modules/rocketchat.py
This PR fixes the following error with Rocket Chat 7.4.1
```
"error":"Unexpected token \'p\\', \\\\"payload{\\\\\"t\\\\\"... is not valid JSON"
```
Closes #9869.
Rocket Chat
=> Fix payload to match Rocket Chat 7.4.1 API

changelogs/fragments/9875-proxmox-dont-expect-key-template-to-exist.yml, plugins/modules/proxmox_vm_info.py
In rare cases it can happen that the dictionary containing info's about a virtual machine doesn't contain the key `template` and therefore we would get an KeyError. Use `dict.get` to handle that case properly.
Fixes #9875
plugins/modules/proxmox_vm_info.py
=> proxmox_vm_info: don't expect key 'template' exists in dictionary

tests/integration/targets/callback_yaml/tasks/main.yml
Using `!unsafe` will also work the same way with DT.
yaml callback
=> Simplify YAML callback tests

changelogs/fragments/9965-fix-duplicate-jsonify-payload-for-rocketchat-pre740.yml, plugins/modules/rocketchat.py
This PR fix incorrect backward compatibility with RocketChat before 7.4.1 causing msg :
```
failed to send message, return status=400
```
For rocketchat < 7.4.0 payload is "jsonify" twice.
Rocket Chat
=> fix duplicate json conversion for rocketchat pre740

changelogs/fragments/9951-mod-php-identifier.yml, plugins/modules/apache2_module.py
the php apache module name has changed: https://php.watch/versions/8.0/mod_php-rename
apache_module
before:
```console
TASK [apache-server : enable modules] *******************************************************************
failed:
coldfront-dev (item=php8.3) =>
ansible_loop_var: item
changed: false
item: php8.3
msg: |-
Failed to set module php8.3 to enabled:
Considering dependency mpm_prefork for php8.3:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php8.3:
Module php8.3 already enabled
Maybe the module identifier (php8_module) was guessed incorrectly.Consider setting the "identifier" option.
rc: 0
stderr: ''
stdout: |-
Considering dependency …
```
=> update PHP apache module workaround

changelogs/fragments/9953-gitlab-project-members-support-owner-level.yml, plugins/modules/gitlab_project_members.py, tests/integration/targets/gitlab_project_members/defaults/main.yml, tests/integration/targets/gitlab_project_members/tasks/main.yml
The job of the `gitlab_project_members` is it to add / invite users to a project (git repository) giving them one of various predefined roles for this project which decides what exactly they are allowed to do on this project.
The highest of these roles / levels named `owner` is currently not yet supported by this module for some reason
and this PR wants to fix this.
The implementation changes here are rather primitive and simple, just add `owner` everywhere where the other access levels are already handled. It also can help to look the `gitlab_group_members` module which basically does the same as this module just for gitlab groups and is already supporting the `owner` level.
Considering testing. Integration tests for this module were a bit …
=> allow gitlab-project-members module to handle user level "owner"

changelogs/fragments/9646-hpilo-fix-idempotency.yml, plugins/modules/hpilo_boot.py
For this module to be idempotent, it should be successful when trying to reach a power state which is already there.
It was already the case for "poweroff", however when running the module with "boot_once" state, it was failing if the server was already powered_on, which is not an idempotent behavior
hpilo_boot.py
Before change, when running the module with state = "boot_once", the module fails :
```
Tuesday 28 January 2025  11:08:58 +0100 (0:00:00.012)       0:00:00.344 *******
"msg": "HP iLO (server) reports that the server is already powered on !"
}
PLAY RECAP ************************************************************************************************************************************************************* …
```
=> hpilo_boot: fix module failing when trying to power on an already powered-on server

changelogs/fragments/9962-nmcli-add-infiniband-mac-support.yml, plugins/modules/nmcli.py, tests/unit/plugins/modules/test_nmcli.py
Add support for `infiniband.mac-address` option, for interconnect devices.
nmcli module
This was asked at https://github.com/bluebanquise/bluebanquise/issues/1003 .
Please note that I do not have the hardware to test this feature, so I tested the python syntax and logic only, but could not make sure the nmcli execution will apply the setting.
=> Feat: Add infiniband mac address support in nmcli module

plugins/modules/rpm_ostree_pkg.py
In the documentation for the rpm_ostree_pkg module, the example showing how to improve resiliency by using a delay did not work, as delay was misspelled.
rpm_ostree_pkg
=> Fix typo in rpm_ostree_pkg documentation example

changelogs/fragments/9970-pkcs12_alias_cert_alias_optional.yml, plugins/modules/java_cert.py, tests/integration/targets/java_cert/tasks/main.yml
Fixes #6010
This pull request permit the module to use aliases as optional.
java_cert
The keytool util can import a pkcs12 certificate without specify the alias, example:
```keytool -importkeystore -srckeystore mypfxfile.pfx -srcstoretype pkcs12 -destkeystore clientcert.jks -deststoretype JKS```
Omitting the pkcs12_alias and cert_alias result in a command error.
This pull request permit the module to use aliases as optional, a test has been added to test this change.
```paste below
```
=> param pkcs12_alias and cert_alias to be optional in java_cert module 

changelogs/fragments/9987-keycloak-auth-flow-fix-config.yaml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_authentication.py, tests/integration/targets/keycloak_authentication/README.md, tests/integration/targets/keycloak_authentication/aliases, tests/integration/targets/keycloak_authentication/tasks/access_token.yml, tests/integration/targets/keycloak_authentication/tasks/main.yml, tests/integration/targets/keycloak_authentication/vars/main.yml
Fix authentification flow configuration duplication
keycloak_authentication.py
keycloak.py
Modification to authentification flow configuration cause the creation of a duplicate record in AUTHENTICATOR_CONFIG and AUTHENTICATOR_CONFIG_ENTRY
KC26 exported realm:
```json
{
"id": "f76d998c-6eb4-42fa-b3b1-df8ae2be926c",
"alias": "my-conditional-reset-otp-config",
"config": {
"defaultOtpOutcome": "force",
"noOtpRequiredForHeaderPattern": "X-Forwarded-For: 10\\.[0-9\\.:]+"
}
},
{
"id": "e195fad8-4470-47be-ada2-ecf44146a0eb",
"alias": "my-conditional-reset-otp-config",
"config": {
"defaultOtpOutcome": "force",
"noOtpRequiredForHeaderPattern": "X-Original-Forwarded-For: 10.[0-9\\.:]+"
}
}
```
=> Fix Keycloak authentication flow configuration issues

.github/BOTMETA.yml, plugins/connection/wsl.py, tests/integration/targets/connection_wsl/aliases, tests/integration/targets/connection_wsl/dependencies.yml, tests/integration/targets/connection_wsl/files/wsl.exe, tests/integration/targets/connection_wsl/plugin-specific-tests.yml, tests/integration/targets/connection_wsl/runme.sh, tests/integration/targets/connection_wsl/test.sh, tests/integration/targets/connection_wsl/test_connection.inventory, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/unit/plugins/connection/test_wsl.py
This adds the `community.general.wsl` connection plugin.
This allows Ansible to remotely manage a [WSL Distribution](https://learn.microsoft.com/en-us/windows/wsl/install) by using SSH to connect to a Windows machine, then use `wsl.exe` to execute commands inside a WSL Distribution.
This is derived from [the existing `community.general.proxmox_pct_remote` connection plugin](https://github.com/ansible-collections/community.general/blob/main/plugins/connection/proxmox_pct_remote.py).
community.general.wsl
Here's an simple example how to use this. The full example is at the branch at https://github.com/rgl/terraform-libvirt-ansible-windows-example/tree/wsl.
Example inventory:
```yaml
all:
children:
wsl:
hosts:
example-wsl-ubuntu:
ansible_host: 10.17.3.2 # the …
```
=> add the wsl connection plugin

changelogs/fragments/10011-github_deploy_key-check-key-present, changelogs/fragments/10011-github_deploy_key-check-key-present.yml, plugins/modules/github_deploy_key.py
Currently if we add a deploy key, if we get a 422 we consider that the key is already there and exit with changed=false, giving the impression that all is fine.
But in reality there can be many other reason for a 422, for example:
* the key is not in a valid format
* the key is already used in another repository
This is really annoying as one thinks the operation went well, whereas it failed.
The proposed fix it that if we get a 422 response code as we add a key, we check if it's because the key already exists or for another reason. And based on that we return with success or we fail.
fixes: #6718
github_deploy_key
With a key which is a content in base64 that I forgot to decode
Before:
```
TASK [xxxx : add the key on github] …
```
=> fix: github_deploy_key check key exists on 422

changelogs/fragments/9895-proxmox_tags_with_uppercase_chars.yml, plugins/modules/proxmox.py, plugins/modules/proxmox_kvm.py, tests/integration/targets/proxmox/tasks/main.yml
* Fix the 'not a valid tag' error message when the VM or container tag contains uppercase characters
Fixes #9895
minor_changes:
- proxmox and proxmox_kvm modules - allow uppercase characters in VM/container tags (https://github.com/ansible-collections/community.general/issues/9895).
proxmox, proxmox_kvm
Regexp pattern updated to allow uppercase characters in VM and container tags, as there is no such limitation in the PVE WebUI.
```
- name: Now working example creating new VM with tags including uppercase letters
community.general.proxmox_kvm:
api_password: secret
api_host: helldorado
name: spynal
node: sabrewulf
tags:
- Debian
- DEBIAN
- dEBIAN
```
=> Allowing uppercase tags in proxmox & proxmox_kvm

changelogs/fragments/10012-improve-error-handling-homebrew-missing-tap.yml, plugins/modules/homebrew.py
Homebrew: Emit a useful error message if `brew info` reports a package tap is null.  This can happen if an installed package is subsequently removed from the tap (e.g. it is withdrawn by homebrew).  
Fixes #10012
homebrew
Note: the task fails with an error referencing the broken package, as requested in the bug report.  No attempt is made to continue or recover the task.
Note: failure case is hard to reproduce.  No test added.
=> Homebrew: Emit a useful error message if brew info reports a package tap is null.

tests/integration/targets/hg/aliases, tests/integration/targets/hg/meta/main.yml, tests/integration/targets/hg/tasks/install.yml, tests/integration/targets/hg/tasks/uninstall.yml, tests/integration/targets/supervisorctl/aliases, tests/integration/targets/supervisorctl/tasks/install_pip.yml, tests/integration/targets/supervisorctl/tasks/main.yml, tests/integration/targets/supervisorctl/tasks/test.yml, tests/integration/targets/supervisorctl/tasks/test_start.yml, tests/integration/targets/supervisorctl/tasks/test_stop.yml
Right now two integration tests skip Python 3 completely in CI.
This either is an oversight that should be fixed, or the tests should be fixed, or the modules should be deprecated.
hg
supervisorctl
=> Remove blanket skips for Python 3 in CI

changelogs/fragments/9898-keycloak_user-supports-subgroups.yaml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_user.py
This PR fixes #9647 :
You can now address groups in the keycloak_user module by name (e.g. `my-group`) or by path (e.g. `/foo/bar/baz`). Using the path syntax adds support for managing membership of subgroups, which is not possible with ordinary names.
Along the way, it fixes minor bugs in group management and error handling.
keycloak_user
=> Add support for addressing subgroups by paths to the keycloak_user module

.azure-pipelines/azure-pipelines.yml
In ansible-core it has been replaced with 14.1, but we're already testing against that. Ref: https://github.com/ansible/ansible/commit/3546111f2d83dd254c928b6b9e273ef1daf1f296
CI
=> Remove FreeBSD 14.0 from CI

tests/integration/targets/supervisorctl/aliases
They seem to fail when running all tests, but not when only the supervisorctl tests are being run. Also they are disabled for some systems, etc. I think they need a bigger overhaul.
Until that's done, marking them as `unstable` should help CI failing for everyone else because of them.
supervisorctl
=> Mark supervisorctl tests as unstable

.github/BOTMETA.yml, plugins/module_utils/xdg_mime.py, plugins/modules/xdg_mime.py, tests/unit/plugins/modules/test_xdg_mime.py, tests/unit/plugins/modules/test_xdg_mime.yaml
Adds a new module called `xdg_mime`. It's based on `gio_mime` module, but it uses `xdg-mime` instead of `gio` to do the configuration.
My first idea was to create a more generic module called `mime`, but @russoz suggested creating a separated module. Maybe the could merge in the future.
xdg_mime
```paste below
```
=> Add xdg_mime module

docs/docsite/rst/guide_modulehelper.rst
Following up on what I wrote at https://github.com/ansible-collections/community.general/pull/9531#discussion_r1976227059 this PR makes the documentation more explicit abou the fact that `output_params`, `change_params`, `diff_params` and `facts_params` MUST refer to module parameters defined in `argument_spec`.
docs/docsite/rst/guide_modulehelper.rst
=> Improve MH doc

plugins/modules/crypttab.py
The current example includes extra jinja delimiters which
result in double-interpretation of the statement.
Fixes: #10078
=> crypttab: removes jijna delimiters from example using when

.github/workflows/ansible-test.yml, tests/utils/shippable/shippable.sh
community.crypto 3.x.y will require ansible-core >= 2.17. The repo's `main` branch already dropped compatibility for certain things.
CI
=> CI: Use community.crypto 2.x.y for ansible-core 2.16 and before

.github/workflows/ansible-test.yml, tests/utils/shippable/shippable.sh
Backport of #10086 to stable-8.
CI
=> [stable-8] CI: Use community.crypto 2.x.y for ansible-core 2.16 and before (#10086)

changelogs/fragments/10063-cobbler-add-connection-timeout.yml, plugins/inventory/cobbler.py
This adds a `connection_timeout` option to cobbler.  Helpful for when some remote cobbler servers are not accessible.
cobbler
=> Add connection_timeout option to cobbler inventory

antsibull-nox.toml
This is mainly important for #10104.
Ref: https://github.com/ansible-community/antsibull-nox/pull/77
CI
=> antsibull-nox: use community.crypto 2.x.y for ansible-core < 2.17

tests/integration/targets/module_helper/tasks/msimpleda.yml
Merging https://github.com/ansible/ansible/pull/85095 broke the MH deprecation test (unsurprisingly).
module_helper integration tests
=> Fix deprecation test

changelogs/fragments/10102-ini_file-fix-unmatched-whitespace-before-comment.yml, plugins/modules/ini_file.py, tests/integration/targets/ini_file/tasks/tests/06-modify_inactive_option.yml
Expanded the regular expression for inactive ("commented out") options to also match when the comment symbol (`#` or `;`) is preceded by whitespace.
Fixes https://github.com/ansible-collections/community.general/issues/8539
ini_file
Example input
```ini
[section1]
```
Example task using ini_file module
```yaml
- name: Edit option 1 in section 1 to have value = value2
ini_file:
path: /path/to/file
modify_inactive_option: true
section: "section1"
option: "option1"
value: "value2"
```
Output before this change
```ini
[section1]
option1 = value2
```
Output after this change
```ini
[section1]
option1 = value2
```
=> ini_file: fix unmatched whitespace before comment

tests/unit/plugins/connection/test_lxc.py
They currently fail with ansible-core devel since they assume that passing a string through `set_option()`/`get_option()` will have the same identity.
Ref: https://dev.azure.com/ansible/community.general/_build/results?buildId=145426&view=logs&j=b23b1ec0-763d-57f2-9c2f-789c257dd001&t=4c6b7fe9-5394-5461-43e4-9d6229dcb341
lxc connection unit tests
=> lxc: fix unit tests

tests/integration/targets/setup_redis_replication/defaults/main.yml
The tests currently fail because the user `redis` no longer exists. It has been renamed to `valkey`, together with the package.
redis
=> redis_info: adjust tests for Arch Linux

tests/integration/targets/setup_redis_replication/defaults/main.yml, tests/integration/targets/setup_redis_replication/tasks/setup_redis_cluster.yml
Manual backport of #10129 to stable-8.
Needed parts of another commit that added new platforms to CI and introduced infrastructure that #10129 needs.
redis
=> [stable-8] redis_info: adjust tests for Arch Linux

CONTRIBUTING.md, antsibull-nox.toml
Right now, the testing docs do not mention antsibull-nox, and do not mention how to install collections needed for the tests.
testing
=> Allow running sanity and unit tests with antsibull-nox; impove testing documentation

changelogs/fragments/10155-proxmox-bugfix.yml, plugins/modules/proxmox.py
Backport of https://github.com/ansible-collections/community.proxmox/pull/91.
I re-created the commit of that PR as the commit from https://github.com/ansible-collections/community.general/pull/10030 by @iphoneintosh + a commit for the changelog fragment.
proxmox
=> proxmox: fix: cannot access local variable 'identifier' where it is not associated with a value

changelogs/fragments/10145-fix-typeerror-cobbler-xmlrpc.yml, plugins/modules/cobbler_system.py
Fixes #8506 
`cobbler_system` plugin
When running a task with state param set to `present` (default value) as in the following example:
```
- name: Ensure cobbler systems were created
community.general.cobbler_system:
host: <hostname>
username: cobbler
password: <pwd>
name: <profile_name>
use_ssl: false
state: present
```
I get the following error:
```
xmlrpc.client.Fault: <Fault 1: "<class 'TypeError'>:CobblerXMLRPCInterface.get_system_handle() takes 2 positional arguments but 3 were given">
```
Checked Cobbler xmlrpc client and indeed the `get_system_handle`  method only accepts two arguments as can be seen in the code here https://github.com/cobbler/cobbler/blob/main/cobbler/remote.py#L1533
```
Cobbler 3.4.0
```
```
ansible [core 2.14.6]
```
```
community.general …
```
=> Fix TypeError caused by giving more than 2 positional arguments to CobblerXMLRPCInterface.get_system_handle() 

.github/BOTMETA.yml, plugins/callback/print_task.py, tests/integration/targets/callback_print_task/aliases, tests/integration/targets/callback_print_task/tasks/main.yml
Prints task snippet to job output.
I figured this might be useful for debugging purposes when executing playbooks. All this callback plugin is doing, is printing out the task snippet as it would show within the playbook. See example below.
Playbook:
```
---
- name: Test
hosts: all
tasks:
- name: TEST | HEllo
ansible.builtin.shell: echo {{ item }}
when: false
async: 10
poll: 1
loop:
- 1
- 2
- 3
- ansible.builtin.shell: echo hello
- ansible.builtin.ping:
```
Command:
```
ansible-playbook -i inventory playbook.yml -v
```
Output:
```
PLAY [Test] ********************************************************************
TASK [TEST | HEllo] ************************************************************
- name: TEST | HEllo
ansible.builtin.shell: echo {{ item }}
when: false
async: 10 …
```
=> Feat: Add callback plugin print_task

.azure-pipelines/azure-pipelines.yml, README.md, antsibull-nox.toml
community.general 9.x.y will not support newer versions of ansible-core than 2.19.
collection
=> [stable-9] Replace devel with stable-2.19 in CI

changelogs/fragments/8437-xml-children-value.yml, plugins/modules/xml.py, tests/integration/targets/xml/results/test-set-children-elements-value.xml, tests/integration/targets/xml/results/test-set-children-elements-value.xml.license, tests/integration/targets/xml/tasks/main.yml, tests/integration/targets/xml/tasks/test-set-children-elements-value.yml
This change adds support for creating value to node when using add_children/set_children with subnodes in xml module.
[Closes #2372](https://github.com/ansible-collections/community.general/issues/2372).
plugins/modules/xml.py
=> add special word '+value' to add_children/set_children in xml module

.azure-pipelines/azure-pipelines.yml, .github/workflows/ansible-test.yml, README.md, antsibull-nox.toml, changelogs/fragments/ansible-core-support.yml, meta/runtime.yml, plugins/lookup/cartesian.py, plugins/lookup/dependent.py, plugins/lookup/flattened.py, plugins/module_utils/redfish_utils.py, plugins/modules/simpleinit_msb.py
Regular cleanup for a new major release.
various
=> Drop support for ansible-core 2.15; update CI to move ansible-core 2.16 to EOL CI; remove compat code for ansible-core < 2.14

changelogs/fragments/10191-github_key-add-api_url-parameter.yml, plugins/modules/github_key.py, tests/integration/targets/github_key/aliases, tests/integration/targets/github_key/tasks/main.yml, tests/integration/targets/github_key/vars/main.yml
- This PR adds argument `api_url` to `github_key` module to define github URL in case of using self-hosted Github.
Compatible with previous version ( default value - github.com )
- Includes tests
- Made by analogy with [github_repo api_url](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/github_repo.py#L78)
github_key
=> Add api_url in github_key module

tests/integration/targets/alternatives/tasks/subcommands.yml, tests/integration/targets/cmd_runner/vars/main.yml
Apparently the error message returned by AnsibleModule.run_command() when trying to execute a non-existing executable changed. This makes some of the integration tests fail.
Ref: https://github.com/ansible/ansible/commit/600c1e67b488ecaf92554f7b73b0335a8ec768f8
(There are some more CI breakages, I will take a look in another PR.)
alternatives integration tests
cmd_runner integration tests
=> Tests: adjust to ansible-core devel changes

changelogs/fragments/10213-yaml-deprecation.yml, meta/runtime.yml, plugins/callback/yaml.py
I'd like to move the removal of the YAML callback from 13.0.0 to 12.0.0. The latest set of breaking changes in the ansible-core internals we have to use since ansible-core 2.19 shows that we should get rid of this plugin as soon as possible.
Removing it from 11.0.0 already might be a bit too extreme, but I really don't want to keep it around much longer...
(CI will fail because #10212 isn't merged yet.)
yaml callback
=> YAML callback: remove 12.0.0 already

changelogs/fragments/10194-add-pcs-resource-maintenace-mode.yml, plugins/module_utils/pacemaker.py, plugins/modules/pacemaker_resource.py, tests/unit/plugins/modules/test_pacemaker_resource.yaml
* Adds check for pacemaker cluster maintenance mode
* Ignores cluster resource lifecycle if maintenance mode is enabled
* Deleting, enabling, or disabling resources can still be managed by user during maintenance mode
Fixes #10180 
`pacemaker_resource`
Error Replication:
* Create a pacemaker cluster
* Enable pacemaker maintenance mode: `pcs property set maintenance-mode=true`
* Create any pacemaker resource
* Which will error out as no resource can start by pacemaker lifecycle on any mode while maintenance mode is enabled
```paste below
```
=> pacemaker: add cluster maintenance mode checks

.github/BOTMETA.yml, plugins/modules/lpv.py, plugins/modules/lvm_pv.py, tests/integration/targets/lvm_pv/aliases, tests/integration/targets/lvm_pv/meta/main.yml, tests/integration/targets/lvm_pv/tasks/cleanup.yml, tests/integration/targets/lvm_pv/tasks/creation.yml, tests/integration/targets/lvm_pv/tasks/main.yml, tests/integration/targets/lvm_pv/tasks/removal.yml, tests/integration/targets/lvm_pv/tasks/resizing.yml
This pull request introduces a new `lvm_pv` module for managing LVM Physical Volumes. The module provides comprehensive functionality for:
- Creating and removing physical volumes
- Resizing existing PVs (with automatic device rescan capability)
- Forceful operations when needed
- Full idempotency and check mode support
Key features:
- Supports all basic PV operations (`pvcreate`, `pvremove`, `pvresize`)
- Automatically handles device rescans before resize operations
- Provides clear status messages and change detection
- Includes thorough parameter validation and error handling
The module fills a gap in Ansible's storage management capabilities, complementing the existing `lvg` and `lvol` modules.
lvm_pv
Example usage:
```yaml
- name: Creating physical volume on …
```
=> lvm_pv: new module for LVM Physical Volumes

changelogs/fragments/10242-yaml.yml, plugins/callback/yaml.py, tests/integration/targets/callback/tasks/main.yml, tests/integration/targets/callback_yaml/meta/main.yml, tests/integration/targets/callback_yaml/tasks/main.yml
I only found out two days ago (https://github.com/ansible/ansible/issues/84781#issuecomment-2964343652) that ansible-core 2.19.0b2 already came out with a utility function that simplifies fixing the yaml callback for with DT.
This PR tries to implement this. This allows to remove the ugly hacks I introduced earlier.
The downside is that the callback will no longer be compatible with ansible-core 2.19.0b1, but I think that's ok. If someone is still using that version, I don't think we can't help them :)
yaml callback
=> yaml callback: use new util introduced in ansible-core 2.19.0b2

plugins/modules/dnf_config_manager.py, plugins/modules/dnf_versionlock.py
The dnf_* modules do not work with dnf5. Since it doesn't look like anyone is fixing them, let's note this in the docs.
Ref: #10237
Ref: #9127
dnf_config_manager
dnf_versionlock
=> docs: add notes that dnf_* modules do not work with dnf5

changelogs/fragments/10198-cargo-features-parameter.yml, plugins/modules/cargo.py
Hi! I'm using currently cargo module to install many cargo binaries. This is my example [vars/config/main.yaml](https://github.com/Psyhackological/my-ansible/blob/main/collections/konradkon/popos/roles/rustup/vars/main.yaml)
```yaml
---
rustup_cargo_list:
- name: alacritty
dependencies:
- cmake
- g++
- pkg-config
- libfontconfig1-dev
- libxcb-xfixes0-dev
- libxkbcommon-dev
- python3
```
You get the idea, then the logic is in the playbooks so name is passed through `community.general.cargo` and apt packages to `ansible.builtin.apt` module. However in the cargo install there is a `--features` flag that allows:
> Cargo “features” provide a mechanism to express [conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html) and [optional …
=> cargo: add support for --features flag

changelogs/fragments/9692-update-more-than-10-keycloak-sub-groups.yml, plugins/module_utils/identity/keycloak/keycloak.py
Fixes #9690 
When we want to create or update a sub-group, we fetch children of the parent group to know which sub group exist and should be updated.
The [API is paginated by default with a maximum of 10 result](https://www.keycloak.org/docs-api/latest/rest-api/index.html#_get_adminrealmsrealmgroupsgroup_idchildren) and [the api call did not set the corresponding paremeter (`max`)](https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/identity/keycloak/keycloak.py#L1552).
This PR set `max` parameter with the number of existing sub-groups retrieve by another API endpoint
community.general.keycloak_group
=> fix(keycloak): update more than 10 sub-groups (#9690)

docs/docsite/rst/guide_vardict.rst
This should be `json`, not `javascript`.
docs/docsite/rst/guide_vardict.rst
=> Extra docs: normalize code block language

changelogs/fragments/10231-keycloak-add-client-credentials-authentication.yml, plugins/module_utils/identity/keycloak/keycloak.py, plugins/modules/keycloak_authentication.py, plugins/modules/keycloak_authentication_required_actions.py, plugins/modules/keycloak_authz_authorization_scope.py, plugins/modules/keycloak_authz_custom_policy.py, plugins/modules/keycloak_authz_permission.py, plugins/modules/keycloak_authz_permission_info.py, plugins/modules/keycloak_client.py, plugins/modules/keycloak_client_rolemapping.py, plugins/modules/keycloak_clientscope.py, plugins/modules/keycloak_clientscope_type.py, plugins/modules/keycloak_clienttemplate.py, plugins/modules/keycloak_component.py, plugins/modules/keycloak_group.py, plugins/modules/keycloak_identity_provider.py, plugins/modules/keycloak_realm.py, plugins/modules/keycloak_realm_key.py, plugins/modules/keycloak_realm_keys_metadata_info.py, plugins/modules/keycloak_realm_rolemapping.py, plugins/modules/keycloak_role.py, plugins/modules/keycloak_user.py, plugins/modules/keycloak_user_federation.py, plugins/modules/keycloak_user_rolemapping.py, plugins/modules/keycloak_userprofile.py, tests/integration/targets/keycloak_modules_authentication/tasks/main.yml, tests/integration/targets/keycloak_modules_authentication/vars/main.yml
Adds support for client_credentials authentication to all keycloak modules. Applying these changes allows authentication solely with `auth_client_id` and `auth_client_secret` to non-public keycloak realms, which is a common pattern for keycloak configurations in production environments.
Resolves:
- #9561
- #8829 
- #7469 
keycloak
A test case including preparation of keycloak with the appropriate configuration has been added in `tests/integration/targets/keycloak_modules_authentication/tasks/main.yml`.
In general, the keycloak modules did not at all support the `grant_type=client_credentials`, though it was written at different places in the documentation.
```
'grant_type': 'client_credentials',
'client_id': client_id,
'client_secret': client_secret,
```
Reason is, …
=> keycloak: add support for client_credentials authentication

tests/integration/targets/sysrc/tasks/main.yml
See for example https://dev.azure.com/ansible/community.general/_build/results?buildId=148985&view=logs&j=15b15ff5-e25d-5a85-feff-f9fd657743a6&t=f55d911f-2bf9-585b-8bc7-9e61a21207bc&l=6316.
sysrc
=> sysrc jail tests: FreeBSD 14.1 stopped working

changelogs/fragments/10271--disable_lookups.yml, plugins/inventory/icinga2.py, plugins/inventory/linode.py
`Templar.template`'s parameter `disable_lookups` has been deprecated in ansible-core 2.19 (https://github.com/ansible/ansible/blob/34abc83822a4ee118cc813862ecdb8d2a6a1538b/lib/ansible/template/__init__.py#L273-L279). Inventory plugins have been using it (probably copied around from a common source), but they always set it to `False`, which happened to be the default since at least 2017 (I didn't bother to check back even more).
=> Inventory plugins: remove deprecated disable_lookups parameter (which was set to its default anyway)

plugins/modules/slack.py, tests/unit/plugins/modules/test_slack.py
Allow the slack module to work with GovSlack, hosted at https://slack-gov.com/
This re-uses the existing `domain` option so that users can set it to `slack-gov.com` to use GovSlack. To maintain backwards compatibility, any setting of `domain` for WebAPI tokens that is not `slack.com` or `slack-gov.com` is ignored.
slack
```paste below
```
=> slack: support slack-gov.com

docs/docsite/rst/filter_guide.rst, docs/docsite/rst/test_guide.rst
antsibull-docs 2.18.0 has a new role: `:anscollection:`.
extra docs
=> Docs: use :anscollection:

plugins/modules/ipa_dnsrecord.py
Simple comma instead of a period, easy mistake.
Very simple typo correction in the module documentation, no changes to features nor functions.
ipa_dnsrecord
```paste below
```
=> fix typo in ipa_dnsrecord module examples

antsibull-nox.toml
antsibull-nox allows to validate code block languages. This ensures that we stick to a certain set of languages (which can always be updated if we need more). Also the config disallows code blocks without languages, and the usage of `::` (which can cause problems with rstcheck, and can result in random formatting since the syntax highlighting for these is configured on a global level).
CI
=> CI: add checks for code block types in extra docs

plugins/modules/flatpak.py
- Adds a new usage for the `community.general.flatpak` module demonstrating the `executable` parameter, which allows users to specify a custom path to the `flatpak` binary.
- This can be useful in development or testing environments where the system binary is overridden or unavailable.
flatpak (community.general)
=> flatpak: add docs example for install using custom executable path

plugins/modules/lvg.py
-  `community.general.lvg` module demonstrating the use of `remove_extra_pvs: false`.
- how to safely add new physical volumes (PVs) to an existing volume group (VG) without removing previously added PVs. 
lvg (community.general)
=> lvg: add docs example for preserving existing PVs in a volume group using `remove_extra_pvs: false`

changelogs/fragments/10359-dependent.yml, plugins/lookup/dependent.py, tests/unit/plugins/lookup/test_dependent.py
Randomly found this when running some playbook...
Ref: https://github.com/ansible/ansible/issues/85436
dependent lookup plugin
=> dependent lookup: avoid deprecated ansible-core 2.19 functionality

plugins/modules/easy_install.py
- Adds a new task demonstrating usage of the `virtualenv_command` parameter in the `community.general.easy_install` module.  
- This task installs a Python library into a virtual environment using `pyvenv` instead of the default `virtualenv` tool.  
`community.general.easy_install`
=> community.general.easy_install :  use of the virtualenv_command parameter

tests/integration/targets/zpool/aliases
These currently fail due to zfs module not being there.
Example run:
- https://dev.azure.com/ansible/community.general/_build/results?buildId=152245&view=logs&j=4a3db1d6-9138-5151-c46d-05bec78b43c6&t=3a5d6d32-7711-5b90-4da3-38a87efde932
zpool
=> CI: Disable zpool tests on Alpine

changelogs/fragments/10459-deprecations.yml, plugins/modules/apache2_module.py, plugins/modules/htpasswd.py, plugins/modules/syspatch.py, plugins/modules/sysupgrade.py, plugins/modules/zypper_repository.py
I randomly noticed that returning `warnings` in `exit_json()` is deprecated in community.routeros, and when grepping for more occasions I found some modules in community.general.
various
=> Fix ansible-core 2.19 deprecations

changelogs/fragments/10461-cronvar-non-existent-dir-crash-fix.yml, plugins/modules/cronvar.py, tests/integration/targets/cronvar/tasks/main.yml
Fix crash in cronvar module when cron_file is under a non-existent parent directory by validating with os.path.isdir() and returning a clear error.
Fixes #10460 
cronvar
=> Fix cronvar crash when parent dir of cron_file is missing

changelogs/fragments/10458-listen_port_facts-prevent-Type-error-crash.yml, changelogs/fragments/10458-listen_port_facts-prevent-type-error.yml, plugins/modules/listen_ports_facts.py, tests/integration/targets/listen_ports_facts/tasks/main.yml
The module `listen_ports_facts` would crash with a TypeError when required executables were not present. This fix ensures missing dependencies raise a valid OSError without keyword arguments. I also added integration tests.
Fixes  #10457
listen_ports_facts
=> listen_ports_facts: Avoid crash when required commands are missing

changelogs/fragments/10442-apk-fix-empty-names.yml, plugins/modules/apk.py, tests/integration/targets/apk/tasks/main.yml
This PR ensures the apk module rejects empty or whitespace-only package names, which previously led to misleading `status:changed` reports despite no action being taken. 
I also added integration tests to cover various related cases.
Fixes #10441
apk
```paste below
```
=> Ensure apk handles empty name strings properly

changelogs/fragments/10417-sysrc-refactor.yml, plugins/modules/sysrc.py, tests/integration/targets/sysrc/files/10394.conf, tests/integration/targets/sysrc/tasks/main.yml
Refactors the `sysrc` module based on comments from prior PR's. Also fixes #10394.
Closes #10400.
sysrc
Refactored the `sysrc` module.
=> sysrc: refactor

changelogs/fragments/become-pipelining.yml, plugins/become/doas.py, plugins/become/machinectl.py
Fixes #9977 (as much as possible). Closes #9908.
Uses the mechanism introduced in https://github.com/ansible/ansible/pull/78111, which ended up in ansible-core 2.19.
doas become plugin
machinectl become plugin
=> Disable pipelining for doas and machinectl on ansible-core 2.19+

changelogs/fragments/10455-capabilities-improve-error-detection.yml, plugins/modules/capabilities.py
Improve `capabilities` module by detecting `/sbin/getcap` error message and stop early with a meaningful error message.
Fix #5649
capabilities
The `capabilities` module rely on executing `/sbin/getcap` to retrieve the current capabilities of a path.
The `/sbin/getcap` always returns with an `rc == 0` even when the path does not exist or is a symlink:
```
(Pdb) self.module.run_command('/sbin/getcap -v /usr/bin/python3.11')
(0, '/usr/bin/python3.11 cap_net_bind_service=eip\n', '')
(Pdb) self.module.run_command('/sbin/getcap -v /usr/bin/python3')
(0, '/usr/bin/python3 (Not a regular file)\n', '')
(Pdb) self.module.run_command('/sbin/getcap -v /usr/bin/python3_NOT_FOUND')
(0, '', '/usr/bin/python3_NOT_FOUND (No such file or directory)\n')
```
The code checking the …
=> Improve capabilities module by detecting /sbin/getcap error message and stop early with a meaningful error message

changelogs/fragments/108--disable_lookups.yml, changelogs/fragments/151-connection-paramiko.yml, plugins/connection/proxmox_pct_remote.py, plugins/inventory/proxmox.py, tests/unit/plugins/connection/test_proxmox_pct_remote.py
Backports two bugfixes from community.proxmox:
- https://github.com/ansible-collections/community.proxmox/commit/8f90ab075cd6c8ee10be8dac3866add498656799
- https://github.com/ansible-collections/community.proxmox/commit/c0fc31241b1aa5754989c22ad82e829aa6a23ce0
These fix deprecations in ansible-core 2.19.
=> [stable-10] Backport fixes from community.proxmox

changelogs/fragments/10566-merge_variables.yml, plugins/lookup/merge_variables.py
Fixes #10542.
(`Templar.copy_with_new_env()` is there since at least ansible-core 2.13+, which is the minimum ansible-core requirement of community.general 9.x.y.)
merge_variables lookup
=> merge_variables lookup: avoid deprecated Templar.set_temporary_context

tests/unit/requirements.txt
This currently breaks some unit tests.
unit tests
=> CI: python-jenkins 1.8.3 fails to import on Python 2.7

changelogs/fragments/10422-tasks_only-result_format.yml, plugins/callback/tasks_only.py
This allows to configure the output format (YAML vs. JSON) and whether to pretty-format the output (relevant for JSON).
Basically enables these features from ansible-core...
tasks_only callback
=> tasks_only callback: add result_format_callback docs fragment

changelogs/fragments/10493-nagios-services.yml, plugins/modules/nagios.py
Parameter `services` can receive multiple values separated by commas, but little things like whitespaces around commas are not handled. Instead of adding extra logic to do that, it is better to make it a list.
nagios
=> nagios: make services param a list

changelogs/fragments/10538-keycloak-realm-add-support-client-options.yml, plugins/modules/keycloak_realm.py, tests/integration/targets/keycloak_realm/README.md, tests/integration/targets/keycloak_realm/aliases, tests/integration/targets/keycloak_realm/tasks/main.yml, tests/integration/targets/keycloak_realm/vars/main.yml
This pull request adds support for client-related options in the `community.general.keycloak_realm` module. These options allow users to configure client session and device code settings at the realm level.
keycloak_realm
The following options have been added to the module:
- `client_session_idle_timeout`: Time a session is allowed to be idle before it expires for all clients.
- `client_session_max_lifespan`: Maximum lifespan of a session for all clients.
- `client_offline_session_idle_timeout`: Time an offline session can be idle before it expires for all clients.
- `client_offline_session_max_lifespan`: Maximum time before an offline session expires for all clients, regardless of activity.
- `oauth2_device_code_lifespan`: Maximum lifespan of the device code and …
=> Keycloak realm add support for some missing options

changelogs/fragments/lvm_pv.yml, plugins/modules/lvm_pv.py
This change improves error handling by gracefully skipping the rescan operation when dealing with partition devices, avoiding misleading warning messages.
Fixes #10444
lvm_pv
=> lvm_pv - Fixes #10444 - Partition device not found

plugins/filter/jc.py
Comment became redundant at some point.
plugins/filter/jc.py
=> jc filter: remove redundant noqa comment

tests/integration/targets/setup_java_keytool/vars/Debian.yml
Currently the tests fail consistently only on stable-9, but not on stable-10 or stable-11.
setup_java_keytool integration role
=> CI: Make sure to install Java in Debian Bullseye

tests/integration/targets/pacman/tasks/main.yml
AUR's git access is currently restricted / down, due to some apparent DDoS (https://bbs.archlinux.org/viewtopic.php?id=307553).
pacman integration tests
=> pacman: temporary disable yay test

changelogs/fragments/10423-apache_module-condition.yml, plugins/modules/apache2_module.py
Only the activation of the cgi module in threaded mode should be a restriction due to apache2 limitations, not the deactivation. Especially when the cgi module isn't enabled yet at all.
* bug(fix): apache2_module fails to disable cgi module
Trying to disable the cgi module while running in mpm_event module will result in a failure, even when cgi module is already disabled.
Disabling the `cgi` module with `community.general.apache2_module` will fail with the error message `Your MPM seems to be threaded. No automatic actions on module cgi possible.`. Doing the same on the commandline with `a2dismod cgi` will result with the correct messaage `cgi is already disabled`.
Fixes #9140
community.general.apache2_module
Steps to reproduce and discussion
* …
=> apache2_module: updated cgi action conditions

tests/integration/targets/ssh_config/tasks/main.yml
This was introduced in #5868, but causes harm on Debian Trixie. Let's see whether it's still needed.
ssh_config
=> ssh_config tests: remove paramiko version restriction

changelogs/fragments/random_string_seed.yml, plugins/lookup/random_string.py, tests/integration/targets/lookup_random_string/test.yml
* Allow user to specify seed to generate random string
Fixes: #5362
changelogs/fragments/random_string_seed.yml
plugins/lookup/random_string.py
tests/integration/targets/lookup_random_string/test.yml
=> random_string: Specify seed while generating random string

changelogs/fragments/10707-pacemaker-maintenance-mode-regex.yml, plugins/module_utils/pacemaker.py, tests/unit/plugins/modules/test_pacemaker_cluster.yaml, tests/unit/plugins/modules/test_pacemaker_resource.yaml
Add regex matching for `maintenance-mode` for determining maintenance-mode status. Additional unit tests for affected modules.
Fixes #10426
pacemaker
pacemaker_resource
pacemaker_cluster
Depending on OS version, `maintenance-mode` value can be defined such as: `maintenance-mode=true` or `maintenance-mode: true` when performing a `pcs property config`.
```paste below
```
=> pacemaker: Add regex checking for maintenance-mode

plugins/modules/zpool.py
`pool_properties` and `filesystem_properties` accept a dictionary, but not `None`, which the example is passing to them.
Ref: #10766.
zpool
=> zpool: fix broken example

changelogs/fragments/10812-gitlab-variable-add-description.yml, plugins/module_utils/gitlab.py, plugins/modules/gitlab_group_variable.py, plugins/modules/gitlab_instance_variable.py, plugins/modules/gitlab_project_variable.py
Add the ability to configure the description field for group, project, and instance variables.
In addition, `description` is not considered when deleting with `state=absent`. Unsure if this needs to be docced.
I noticed all three modules, when deleting, construct match objects by popping parameters that aren't required to be equal. I suspect `raw`, `masked` etc. were missed from this. I know `hidden` was missed by mistake. I wonder if it's better to construct comparison objects directly from the name and environment scope, rather than subtracting 3+ fields. AFAIK the GitLab API rejects duplicate variables based on variable name and environment scope, so our deletion should probably follow this convention.
Fixes #8584.
Fixes #10809.
gitlab_group_variable, …
=> gitlab_*_variable: add `description` option

changelogs/fragments/10829-fix-keycloak-role-changed-status.yml, plugins/modules/keycloak_role.py, tests/integration/targets/keycloak_role/README.md, tests/integration/targets/keycloak_role/tasks/main.yml, tests/integration/targets/keycloak_role/vars/main.yml
Fixes an issue where `keycloak_role` incorrectly returns `"changed"` when using the alias `clientId` in composite roles.
keycloak_role
```yaml
- name: Unchanged role with composites using aliases - should return no change
community.general.keycloak_role:
auth_keycloak_url: "{{ url }}"
auth_realm: "{{ admin_realm }}"
auth_username: "{{ admin_user }}"
auth_password: "{{ admin_password }}"
name: "Test"
realm: "my-realm"
description: "My composite role"
composite: true
composites:
- name: view-clients
clientId: "realm-management"
state: present
- name: query-clients
clientId: "realm-management"
state: present
keycloak_client_id: test-client
state: present
=> Keycloak role fix changed status
