ansible-collections/community.general

.github/BOTMETA.yml

Initial BOTMETA generated by https://github.com/ansible/ansibullbot/pull/1293
+ removal of `patch` (that's in ansible.posix now)

Initial BOTMETA

---

.github/BOTMETA.yml

As pointed out by @felixfontein in https://github.com/ansible-collections/community.general/pull/7#issuecomment-597469842

Correct non-module paths

---

tests/sanity/ignore-2.10.txt

This was left out of https://github.com/ansible-collections/community.general/pull/14
by mistake.
```paste below
```

Remove virt/libvirt sanity ignore entries

---

shippable.yml
tests/integration/targets/apache2_module/tasks/actualtest.yml
tests/integration/targets/callback_log_plays/runme.sh
tests/integration/targets/cloud_init_data_facts/aliases
tests/integration/targets/connection_chroot/aliases
tests/integration/targets/filter_json_query/tasks/main.yml
tests/integration/targets/filter_random_mac/aliases
tests/integration/targets/filter_random_mac/tasks/main.yml
tests/integration/targets/lookup_hashi_vault/aliases
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_test.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml
tests/integration/targets/lookup_passwordstore/tasks/tests.yml
tests/integration/targets/postgresql_ext/tasks/postgresql_ext_initial.yml
tests/integration/targets/script_inventory_foreman/aliases
tests/integration/targets/script_inventory_foreman/foreman.sh
tests/integration/targets/setup_remote_constraints/aliases
tests/integration/targets/setup_remote_constraints/tasks/main.yml
tests/integration/targets/xfs_quota/aliases
tests/utils/constraints.txt
tests/utils/shippable/shippable.sh

Correct copy-paste error.
This should allow more modules and plugins to be found, so more green in CI.

Shippable: community/general

---

plugins/modules/os_flavor_info.py
plugins/modules/os_image_info.py
plugins/modules/os_keystone_domain_info.py
plugins/modules/os_networks_info.py
plugins/modules/os_port_info.py
plugins/modules/os_project_info.py
plugins/modules/os_server_info.py
plugins/modules/os_subnets_info.py
plugins/modules/os_user_info.py
plugins/modules/zabbix_action.py
plugins/modules/zabbix_group.py
plugins/modules/zabbix_group_info.py
plugins/modules/zabbix_host.py
plugins/modules/zabbix_host_events_info.py
plugins/modules/zabbix_host_info.py
plugins/modules/zabbix_hostmacro.py
plugins/modules/zabbix_maintenance.py
plugins/modules/zabbix_map.py
plugins/modules/zabbix_mediatype.py
plugins/modules/zabbix_proxy.py
plugins/modules/zabbix_screen.py
plugins/modules/zabbix_service.py
plugins/modules/zabbix_template.py
plugins/modules/zabbix_template_info.py
plugins/modules/zabbix_user.py
plugins/modules/zabbix_user_info.py
plugins/modules/zabbix_valuemap.py

These modules have been removed, though the symlinks were missed.

Remove broken link

---

tests/sanity/ignore-2.10.txt

ignore-2.10 action plugins

---

tests/unit/module_utils/xenserver/conftest.py
tests/unit/module_utils/xenserver/test_gather_vm_params_and_facts.py
tests/unit/module_utils/xenserver/test_get_object_ref.py
tests/unit/module_utils/xenserver/test_set_vm_power_state.py
tests/unit/module_utils/xenserver/test_wait_for_functions.py
tests/unit/module_utils/xenserver/test_xapi.py
tests/unit/module_utils/xenserver/test_xenserverobject.py
tests/unit/modules/cloud/xenserver/conftest.py

Hopefull make unit tests ~~run though.~~ fail less badly than before ([like here](https://app.shippable.com/github/ansible-collections/community.general/runs/81/7/console)).
tests/unit/module_utils/xenserver/
tests/unit/modules/cloud/xenserver/conftest.py

Try to fix unit some relative unit test imports

---

plugins/modules/database/postgresql/postgresql_info.py

postgresql_info: remove unnecessary spaces
(i created it mostly for testing but we can merge it anyway)
```plugins/modules/database/postgresql/postgresql_info.py```

postgresql_info: remove unnecessary spaces

---

plugins/modules/net_tools/ipwcli_dns.py

Use the required_if parameter.
The if statements for checking the required params not needed any more.  
ipwcli_dns
```paste below
Better use the module functions than own if statements. 
```
moved from https://github.com/ansible/ansible/pull/68391

ipwcli_dns: Improve module with required_if so if statements not needed

---

shippable.yml
tests/utils/shippable/sanity.sh
tests/utils/shippable/units.sh

Fix unit test paths in tests/utils/shippable/units.sh.
tests/utils/shippable/units.sh

Fix unit test paths in tests/utils/shippable/units.sh, removing fallaxy targets

---

tests/utils/shippable/shippable.sh

Run commands which fetch stuff over network for CI setup up to three times.
tests/utils/shippable/shippable.sh

Run commands which fetch stuff over network for CI setup up to three times

---

plugins/modules/packaging/os/homebrew_tap.py

plugins/modules/packaging/os/homebrew_tap.py

homebrew_tap: Doc fixes

---

tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt

See title. Visible f.ex. in https://app.shippable.com/github/ansible-collections/community.general/runs/212/1/console
ignore.txt

Forgot entry in ignore.txt for module_utils/compat/ipaddress.py

---

tests/integration/targets/connection_docker/test_connection.inventory
tests/integration/targets/connection_jail/test_connection.inventory
tests/integration/targets/connection_libvirt_lxc/test_connection.inventory
tests/integration/targets/connection_lxc/test_connection.inventory
tests/integration/targets/connection_lxd/test_connection.inventory
tests/integration/targets/inventory_cloudscale/playbooks/cleanup.yml
tests/integration/targets/inventory_cloudscale/playbooks/setup.yml
tests/integration/targets/inventory_docker_swarm/playbooks/swarm_setup.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_test.yml
tests/integration/targets/lookup_lmdb_kv/test.yml
tests/integration/targets/lookup_passwordstore/tasks/tests.yml

Fix some integration tests.
CI

Fix FQCRs.

---

tests/integration/targets/archive/meta/main.yml
tests/integration/targets/cloud_init_data_facts/meta/main.yml
tests/integration/targets/consul/meta/main.yml
tests/integration/targets/etcd3/meta/main.yml
tests/integration/targets/filesystem/meta/main.yml
tests/integration/targets/firewalld/meta/main.yml
tests/integration/targets/gem/meta/main.yml
tests/integration/targets/hg/meta/main.yml
tests/integration/targets/iso_extract/meta/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/meta/main.yml
tests/integration/targets/lookup_passwordstore/meta/main.yml
tests/integration/targets/lvg/meta/main.yml
tests/integration/targets/npm/meta/main.yml
tests/integration/targets/sefcontext/meta/main.yml
tests/integration/targets/setup_cron/meta/main.yml
tests/integration/targets/setup_mysql_db/meta/main.yml
tests/integration/targets/setup_openssl/meta/main.yml
tests/integration/targets/setup_pkg_mgr/tasks/main.yml
tests/integration/targets/setup_postgresql_db/meta/main.yml
tests/integration/targets/setup_wildfly_server/meta/main.yml
tests/integration/targets/supervisorctl/meta/main.yml
tests/integration/targets/ufw/meta/main.yml
tests/integration/targets/xattr/meta/main.yml
tests/integration/targets/xml/meta/main.yml
tests/integration/targets/yarn/meta/main.yml

Should improve integration tests in CI.
CI

Set pkg_mgr facts manually for FreeBSD and OpenSUSE

---

shippable.yml

https://github.com/ansible-collections/overview/issues/18

Don't run CI on Master

---

changelogs/fragments/34696-homebrew_cask.yml
plugins/modules/packaging/os/homebrew_cask.py
tests/sanity/ignore-2.10.txt

Follow up changes recommended in code review
plugins/modules/packaging/os/homebrew_cask.py

homebrew_cask: Follow up changes

---

plugins/module_utils/_netapp.py

I forgot to update either ignore.txt files, or add the boilerplate lines.
This PR adds the boilerplate lines.
plugins/module_utils/_netapp.py

Fix sanity test failures for _netapp.py

---

changelogs/fragments/17-postgres_user-no_password_changes-no_log.yml
changelogs/fragments/18-mysql_user-update_password-no_log.yml
changelogs/fragments/19-passwordstore-equal-sign.yml
changelogs/fragments/24-homebrew-upgrade_options.yml
changelogs/fragments/26-influxdb_user-admin-check-mode.yml
changelogs/fragments/36-homebrew-elements.yml
changelogs/fragments/37-homebrew_tap-elements.yml
changelogs/fragments/39-routeros_facts-ipv6-crash.yml

Add changelog fragments for merged PRs #17, #18, #19, #24, #26, #36, #37, #39 which had no changelog fragment yet.
various

Add changelog fragments for merged PRs #17, #18, #19, #24, #26, #36, #37, #39

---

tests/integration/targets/cs_common/tasks/main.yml

Try to fix CI for cloudstack
cloudstack
```paste below
```

cloudstack: ci: wait for sys template available

---

changelogs/fragments/mysql_user_idempotency.yml
plugins/modules/database/mysql/mysql_user.py
tests/integration/targets/mysql_user/tasks/test_privs.yml

Fixes ansible/ansible#68044
mysql_user

Fixed mysql_user idempotency for long privilege lists.

---

tests/sanity/ignore-2.10.txt

Fix ignore.txt.
tests/sanity/ignore-2.10.txt

Fix ignore.txt

---

galaxy.yml
shippable.yml
tests/requirements.yml
tests/utils/shippable/sanity.sh
tests/utils/shippable/shippable.sh
tests/utils/shippable/units.sh

Follow-up for #84. Removes no longer necessary dependencies, and simplies CI a bit.
all

Network removal cleanup

---

plugins/modules/apt_repo.py
plugins/modules/packaging/os/apt_repo.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt

Migrate apt_repo to community.general. Fixes https://github.com/ansible/ansible/issues/68637
plugins/modules/packaging/os/apt_repo.py
```paste below
```

Migrate apt_repo to community.general

---

plugins/connection/libvirt_lxc.py

plugins/connection/libvirt_lxc.py

Add missing libvirt_lxc connection plugin

---

changelogs/fragments/56650-homebrew-update_brew.yml
plugins/modules/packaging/os/homebrew.py
tests/integration/targets/homebrew/tasks/main.yml

Added environment variable to honor update_homebrew argument specified
by user.
Fixes: ansible/ansible#56650
changelogs/fragments/56650-homebrew-update_brew.yml
plugins/modules/packaging/os/homebrew.py

homebrew: Honor update_homebrew value

---

tests/integration/targets/consul/aliases

Temporarily disable consul integration test until #117 has been fixed.
consul

Temporarily disable consul integration tests

---

changelogs/fragments/39-routeros_facts-ipv6-crash.yml

See topic.
Accompanies ansible-collections/community.network#8
changelogs

Remove changelog fragments moved to community.network

---

galaxy.yml
plugins/modules/cloud/ovirt/ovirt_affinity_label_facts.py
plugins/modules/cloud/ovirt/ovirt_api_facts.py
plugins/modules/cloud/ovirt/ovirt_cluster_facts.py
plugins/modules/cloud/ovirt/ovirt_datacenter_facts.py
plugins/modules/cloud/ovirt/ovirt_disk_facts.py
plugins/modules/cloud/ovirt/ovirt_event_facts.py
plugins/modules/cloud/ovirt/ovirt_external_provider_facts.py
plugins/modules/cloud/ovirt/ovirt_group_facts.py
plugins/modules/cloud/ovirt/ovirt_host_facts.py
plugins/modules/cloud/ovirt/ovirt_host_storage_facts.py
plugins/modules/cloud/ovirt/ovirt_network_facts.py
plugins/modules/cloud/ovirt/ovirt_nic_facts.py
plugins/modules/cloud/ovirt/ovirt_permission_facts.py
plugins/modules/cloud/ovirt/ovirt_quota_facts.py
plugins/modules/cloud/ovirt/ovirt_scheduling_policy_facts.py
plugins/modules/cloud/ovirt/ovirt_snapshot_facts.py
plugins/modules/cloud/ovirt/ovirt_storage_domain_facts.py
plugins/modules/cloud/ovirt/ovirt_storage_template_facts.py
plugins/modules/cloud/ovirt/ovirt_storage_vm_facts.py
plugins/modules/cloud/ovirt/ovirt_tag_facts.py
plugins/modules/cloud/ovirt/ovirt_template_facts.py
plugins/modules/cloud/ovirt/ovirt_user_facts.py
plugins/modules/cloud/ovirt/ovirt_vm_facts.py
plugins/modules/cloud/ovirt/ovirt_vmpool_facts.py
tests/requirements.yml
tests/utils/shippable/shippable.sh

The name has been changed to ovirt.ovirt, see ansible/ansible#68448.
dependencies

Adjust name of ovirt dependency

---

tests/integration/targets/setup_mysql_db/tasks/main.yml
tests/integration/targets/zypper/tasks/zypper.yml
tests/integration/targets/zypper_repository/aliases

Fallout from https://github.com/ansible/ansible/issues/68783
- setup_mysql_db tests
- zypper tests

Fix tests for OpenSUSE 15.1

---

plugins/modules/packaging/os/xbps.py

Continuation of ansible/ansible#68099
xbps is the package manager for void linux.
Commit summary:
* one small bugfix
* another refactor
* the last a feature/fix to support changes in xbps behavior, along with some docs
xbps
Please see commit messages.

Xbps various changes

---

changelogs/fragments/alicloud_params_add.yml
plugins/doc_fragments/alicloud.py
plugins/module_utils/alicloud_ecs.py
plugins/modules/cloud/alicloud/ali_instance.py
plugins/modules/cloud/alicloud/ali_instance_info.py
tests/sanity/ignore-2.10.txt

Update alicloud.py, ali_instance and alicloud_ecs to support more params.
- Update module
- Update module_utils
plugins/doc_fragments/alicloud.py
alicloud_ecs.py
ali_instance.py
ali_instance_info.py

Update alicloud.py, ali_instance  and alicloud_ecs to support more params.

---

plugins/modules/database/postgresql/postgresql_user.py

postgresql_user: add session_role parameter to check
a part of https://github.com/ansible-collections/community.general/pull/116 , so, i think, no changelog fragment is needed
```plugins/modules/database/postgresql/postgresql_user.py```

postgresql_user: add session_role parameter to check

---

plugins/modules/source_control/gitlab/gitlab_user.py

Implement fixes and sugestions from #188 
gitlab_user

Fixes for comments from PR #188

---

changelogs/fragments/alicloud_params_add.yml

`changes:` -> `minor_changes`.
changelogs/fragments/alicloud_params_add.yml

Fix changelog fragment with invalid section

---

changelogs/fragments/186-maven_artifact.yml
plugins/modules/packaging/language/maven_artifact.py

Fixes: ansible-collections/community.general#186
changelogs/fragments/186-maven_artifact.yml
plugins/modules/packaging/language/maven_artifact.py

maven_artifact: Convert MD5 values to lowercase before comparison

---

.github/BOTMETA.yml

Add botmeta entry so the maintainers get pinged.

botmeta nios lookup

---

changelogs/fragments/177-postgresql_privs_add_trust_input_parameter.yml
plugins/module_utils/database.py
plugins/modules/database/postgresql/postgresql_privs.py
tests/integration/targets/postgresql_privs/defaults/main.yml
tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
tests/integration/targets/postgresql_privs/tasks/postgresql_privs_session_role.yml

postgresql_privs: add trust_input parameter
```plugins/module_utils/database.py```

postgresql_privs: add trust_input parameter

---

changelogs/fragments/184-postgresql_db_add_trust_input_parameter.yml

changelog fragment for https://github.com/ansible-collections/community.general/pull/184

postgresql_db: add changelog fragment for PR #184

---

changelogs/fragments/212-make-path-option.yml
plugins/modules/system/make.py

Add option to choose a specific make executable in the make module.
Fix ansible-collections#211
Make module

Add option to choose a specific make executable

---

plugins/modules/cloud/misc/proxmox.py

proxmox: fix examples formatting
```plugins/modules/cloud/misc/proxmox.py```

proxmox: fix examples formatting

---

tests/integration/targets/xml/tasks/test-children-elements-xml.yml

Triggered by ansible/ansible#67625.
xml

xml: fix tests (bad boolean)

---

tests/sanity/ignore-2.10.txt
tests/utils/shippable/sanity.sh
tests/utils/shippable/shippable.sh

Avoid sanity excludes so that users can run `ansible-test sanity --docker` and it only reports real problems.
CI

Improve sanity test run for users

---

plugins/modules/packaging/os/flatpak.py
plugins/modules/packaging/os/flatpak_remote.py
tests/sanity/ignore-2.10.txt

Document argument types for flatpak and flatpak_remote
flatpak

Document argument types for flatpak and flatpak_remote

---

plugins/modules/storage/zfs/zfs_delegate_admin.py

zfs_delegate_admin: fix example
```plugins/modules/storage/zfs/zfs_delegate_admin.py```

zfs_delegate_admin: fix example

---

changelogs/fragments/282-postgresql_ext_add_trust_input.yml
plugins/modules/database/postgresql/postgresql_ext.py
tests/integration/targets/postgresql_ext/tasks/postgresql_ext_initial.yml
tests/integration/targets/postgresql_ext/tasks/postgresql_ext_session_role.yml
tests/integration/targets/postgresql_ext/tasks/postgresql_ext_version_opt.yml

Related to #106 and #210
postgresql_ext:
* add trust_input parameter
* Feature Pull Request
`plugins/modules/database/postgresql/postgresql_ext.py`

Add optional input check to postgresql_ext

---

plugins/modules/system/java_keystore.py

https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#examples-block
```plugins/modules/system/java_keystore.py```

java_keystore: fix doc format

---

changelogs/fragments/285-mysql_user_invoke_lambda_support.yml
plugins/modules/database/mysql/mysql_user.py

mysql_user: add invoke lambda privilege support
- Bug Fixes
```plugins/modules/database/mysql/mysql_user.py```

mysql_user: add invoke lambda privilege support

---

changelogs/fragments/274-flatpak-run-command.yaml
plugins/modules/packaging/os/flatpak.py
plugins/modules/packaging/os/flatpak_remote.py
tests/sanity/ignore-2.10.txt

flatpak: Change use of Popen to module.run_command()
flatpak and flatpak_remote

flatpak: Change use of Popen to module.run_command()

---

changelogs/fragments/307-postgresql_table_add_trust_input_parameter.yml
plugins/modules/database/postgresql/postgresql_table.py
tests/integration/targets/postgresql_table/tasks/postgresql_table_initial.yml

postgresql_table: add trust_input parameter
```plugins/modules/database/postgresql/postgresql_table.py```

postgresql_table: add the trust_input parameter

---

tests/integration/targets/etcd3/aliases
tests/integration/targets/lookup_etcd3/aliases

See #322.
tests/integration/targets/lookup_etcd3/
tests/integration/targets/etcd3/

Disable etcd3 tests for now

---

changelogs/fragments/291-postgresql_refactor_modules.yml
plugins/modules/database/postgresql/postgresql_ext.py
plugins/modules/database/postgresql/postgresql_idx.py
plugins/modules/database/postgresql/postgresql_user_obj_stat_info.py

Have given some of the postgresql modules a little refactor to remove some dead code and try to simplify the logic in some of the functions.
**Note** These simplifications make sense to me but if other people think they are too complicated/not useful or notice a better way please let me know and update the changes.
`plugins/modules/database/postgresql/postgresql_ext.py`
`plugins/modules/database/postgresql/postgresql_idx.py`
`plugins/modules/database/postgresql_user_obj_stat_info.py`
```paste below
```

Refactor postgresql modules

---

shippable.yml

It is currently constantly failing.
CI

Disable AIX in CI

---

.github/BOTMETA.yml

I'd like to add my GitHub user to the list of users ignored by notifications bot, as suggested here:
ansible/ansibullbot#1307

Remove tomaszkiewicz from ansibullbot notifications

---

changelogs/fragments/319-syslogger.yml
plugins/modules/notification/syslogger.py

Added new parameter ident to specify the name of application
which is sending the message to syslog using syslogger module.
Fixes: https://github.com/ansible-collections/community.general/issues/319
changelogs/fragments/319-syslogger.yml
plugins/modules/notification/syslogger.py

syslogger: new parameter 'ident'

---

plugins/modules/monitoring/sensu/sensu_silence.py
scripts/inventory/azure_rm.py

New errors due to upgraded default docker image, which contains newer flake8 version.
sensu_silence
scripts/inventory/azure_rm.py

Fix linting errors

---

changelogs/fragments/124-airbrake_deployments-api_v4_for_deploy_notices.yml
plugins/modules/monitoring/airbrake_deployment.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt

The Airbrake v2 deploy endpoint has been [deprecated](https://airbrake.io/docs/legacy-xml-api/#tracking-deploys).
This PR updates the `airbrake_deployment` module to be compatible w/the v4 deploy endpoint
- https://airbrake.io/docs/api/#deploys-v4
- https://airbrake.io/docs/features/deploy-tracking/
airbrake_deployment
To notify Airbrake of a deploy using the v4 endpoint requires the Airbrake
- project_id
- project_key
and expects `POST` data in json format.
Examples below assume project id and key are valid.
**Before**
```
cat > test_old.yml <<EOF
tasks:
- name: notify airbrake about deploy
airbrake_deployment:
repo: https://github.com/phumpal/ansible
token: 'toinfinityandbeyond'
environment: 'production'
user: '{{ lookup("env", "DEPLOY_USER") or …
```

Use api v4 for airbrake deploy notices

---

changelogs/.gitignore
changelogs/config.yaml
shippable.yml
tests/sanity/extra/changelog.json
tests/sanity/extra/changelog.py
tests/sanity/extra/no-unwanted-files.json
tests/sanity/extra/no-unwanted-files.py
tests/utils/shippable/sanity.sh
tests/utils/shippable/shippable.sh

Adds a changelog config and extra sanity tests (using the new runner in community.internal_test_tools). It lints changelog fragments, and makes sure no unwanted files are added to `plugins/`.
CI
changelog

Add extra sanity tests and changelog config

---

tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt

For some reason, the removal in #364 passed tests even though the ignore.txt lines haven't been removed.
CI

google.cloud unit test: Forgot to update ignore.txt

---

changelogs/fragments/fix-oc-conn-plugin-envvar.yml

Changelog for https://github.com/ansible-collections/community.general/pull/377
```paste below
```

Env var case

---

tests/integration/targets/docker_config/tasks/test_docker_config.yml
tests/integration/targets/docker_container_info/tasks/main.yml
tests/integration/targets/docker_login/tasks/tests/docker_login.yml
tests/integration/targets/docker_network_info/tasks/main.yml
tests/integration/targets/docker_node/tasks/main.yml
tests/integration/targets/docker_secret/tasks/test_secrets.yml
tests/integration/targets/docker_volume_info/tasks/main.yml
tests/integration/targets/setup_docker/tasks/main.yml
tests/integration/targets/setup_docker/vars/RedHat-8.yml
tests/integration/targets/setup_docker_registry/handlers/cleanup.yml
tests/integration/targets/setup_docker_registry/tasks/setup.yml

Should (hopefully) fix a lot of CI problems.
setup_docker

Don't die when docker CLI doesn't want to work with docker daemon

---

plugins/modules/database/postgresql/postgresql_db.py

postgresql_db: add an example
related to https://github.com/ansible-collections/community.general/issues/384
postgresql_db

postgresql_db: add an example

---

changelogs/fragments/gitlab-project-variable-variable-type.yml
plugins/modules/source_control/gitlab/gitlab_project_variable.py
tests/integration/targets/gitlab_project_variable/tasks/main.yml

Added support for variable_type (env_var or file).
gitlab_project_variable.py
Tested with gitlab-ce 12.9.2

gitlab_project_variable: added support for variable_type

---

tests/utils/shippable/shippable.sh

Since https://github.com/ansible/ansible/issues/68701 has been fixed, this hack is no longer necessary.
CI

Fix OSX CI hack which is no longer necessary

---

tests/integration/targets/xfs_quota/aliases

Let's see whether this now works.
Fixes #68 (all other problems have been resolved, except deprecation version numbers, which will come as soon as we know more clearly how the versioning schema looks like).
xfs_quota

Re-enable xfs_quota test

---

plugins/modules/cloud/docker/docker_host_info.py

I hope these docs are lying, and this fix makes them say the truth.
docker_host_info

docker_host_info: Do not say you delete what you don't

---

tests/unit/requirements.txt

Avoids CI to fail.
#484 tracks the problem so it can be fixed properly.
gitlab_runner

Temporarily fix gitlab_runner tests by restricting python-gitlab version

---

changelogs/fragments/486-mysql_db_add_check_implicit_admin_parameter.yml
plugins/modules/database/mysql/mysql_db.py
tests/integration/targets/mysql_db/tasks/state_dump_import.yml

Fixes https://github.com/ansible/ansible/issues/24418
mysql_db: add check_implicit_admin parameter
```mysql_db```

mysql_db: add check_implicit_admin parameter

---

changelogs/fragments/494-add-redfish-virtual-media-commands.yml
plugins/module_utils/redfish_utils.py
plugins/modules/remote_management/redfish/redfish_command.py

This PR adds commands to insert and eject virtual media on a Redfish service. This enables, for example, the ability to "insert" a bootable image from a URL into a virtual drive and then boot from that drive into the OS on the image.
[Note: This PR manually migrated from ansible/ansible/pull/68053]
Fixes #493 
Example playbook snippets for the new VirtualMediaInsert and VirtualMediaEject commands:
```
- name: Insert Virtual Media
redfish_command:
category: Manager
command: VirtualMediaInsert
virtual_media:
image_url: 'http://example.com/images/SomeLinux-current.iso'
media_types:
- CD
- DVD
resource_id: BMC
```
```
- name: Eject Virtual Media …
```

add Redfish VirtualMediaInsert and VirtualMediaEject commands

---

changelogs/fragments/58115_nmcli.yml
plugins/modules/net_tools/nmcli.py
tests/unit/plugins/modules/net_tools/test_nmcli.py

Fixes: #472
Signed-off-by: Marcin Sucharski <marcin.sucharski.github@gmail.com>
changelogs/fragments/58115_nmcli.yml
tests/unit/plugins/modules/net_tools/test_nmcli.py

nmcli: Typecast parameter values to string as required

---

plugins/modules/net_tools/nmcli.py

Migrated from https://github.com/ansible/ansible/pull/68259
This is based upon the work done by https://github.com/cdomingos

nmcli: Fix documentation example

---

changelogs/fragments/porting-guide.yml

Add porting guide entries from ansible/ansible's 2.10 porting guide as changelog fragments.
changelog

Porting guide

---

changelogs/fragments/124-airbrake_deployments-api_v4_for_deploy_notices.yml
changelogs/fragments/202-jenkins_plugin-fix-import.yml
changelogs/fragments/63419-docker_container-defaults.yml
changelogs/fragments/63420-docker_container-trust_image_content.yml
changelogs/fragments/63467-docker-stack-return-fix.yml
changelogs/fragments/64635-docker_container-network_mode.yml
changelogs/fragments/66837-zabbix-proxy-interface.yml
changelogs/fragments/clc_aa_policy-remove-unused-wait-parameter.yaml
plugins/lookup/hashi_vault.py
plugins/modules/cloud/smartos/vmadm.py
plugins/modules/database/mysql/mysql_replication.py
plugins/modules/database/postgresql/postgresql_pg_hba.py
plugins/modules/database/postgresql/postgresql_privs.py
plugins/modules/files/archive.py
plugins/modules/monitoring/airbrake_deployment.py
plugins/modules/monitoring/bigpanda.py
plugins/modules/monitoring/datadog/datadog_monitor.py
plugins/modules/net_tools/ldap/ldap_attr.py
plugins/modules/packaging/os/pulp_repo.py
plugins/modules/source_control/gitlab/gitlab_user.py
plugins/modules/system/java_keystore.py

Follow-up to #504: adjust removal/deprecation versions in documentation (docs/changelogs).
collection

Adjust removal versions

---

plugins/modules/system/parted.py

Warn about possible loss of previous partition label and its entries
Fixes: #522 
parted

parted: update label parameter documentation, add warning 

---

plugins/modules/cloud/digital_ocean/digital_ocean_tag.py
plugins/modules/database/postgresql/postgresql_privs.py
plugins/modules/notification/slack.py

modules: improve documentation

modules: improve documentation

---

tests/integration/targets/setup_postgresql_db/tasks/main.yml
tests/integration/targets/setup_postgresql_db/tasks/ssl.yml

CI tests: fix setup_postgresql_db

CI tests: fix setup_postgresql_db

---

shippable.yml

Add Ansible 2.10 runs for CI

---

.github/BOTMETA.yml

Remove andreaso from cloudflare_dns maintainership

---

changelogs/fragments/475-digital_ocean_droplet-add-vpcuuid.yaml
plugins/modules/cloud/digital_ocean/digital_ocean_droplet.py

Adds the new vpc_uuid option for DigitalOcean's new VPC features.
plugins/modules/cloud/digital_ocean/digital_ocean_droplet.py

digital_ocean_droplet: Add new vpc_uuid option

---

tests/integration/targets/firewalld/aliases

Signed-off-by: Adam Miller <admiller@redhat.com>
Fix and enable firewalld tests
firewalld

fix and enable firewalld tests

---

tests/integration/targets/docker_container/filter_plugins/ipaddr_tools.py
tests/integration/targets/docker_container/tasks/main.yml
tests/integration/targets/docker_container/tasks/tests/network.yml

These are currently broken:
https://app.shippable.com/github/ansible-collections/community.general/runs/2283/87/tests
https://app.shippable.com/github/ansible-collections/community.general/runs/2283/93/tests

Fix docker_container tests

---

changelogs/config.yaml

See ansible-community/antsibull-changelog#23.
changelog

Enable flatmapping for changelog generator

---

plugins/modules/database/mysql/mysql_db.py
plugins/modules/database/mysql/mysql_info.py
plugins/modules/database/mysql/mysql_replication.py
plugins/modules/database/mysql/mysql_user.py
plugins/modules/database/mysql/mysql_variables.py
plugins/modules/database/postgresql/postgresql_db.py
plugins/modules/database/postgresql/postgresql_idx.py
plugins/modules/database/postgresql/postgresql_info.py
plugins/modules/database/postgresql/postgresql_membership.py
plugins/modules/database/postgresql/postgresql_owner.py
plugins/modules/database/postgresql/postgresql_ping.py
plugins/modules/database/postgresql/postgresql_privs.py
plugins/modules/database/postgresql/postgresql_query.py
plugins/modules/database/postgresql/postgresql_sequence.py
plugins/modules/database/postgresql/postgresql_set.py
plugins/modules/database/postgresql/postgresql_subscription.py
plugins/modules/database/postgresql/postgresql_table.py
plugins/modules/database/postgresql/postgresql_user.py
plugins/modules/database/postgresql/postgresql_user_obj_stat_info.py

postgresql and mysql modules: fix seealso section
fixes https://github.com/ansible-collections/community.general/pull/580
if it's ok, i can go through other modules in community.general (and maybe community.network) with my script

mysql modules: fix seealso section

---

plugins/lookup/etcd3.py
plugins/modules/database/misc/redis.py
plugins/modules/database/misc/redis_info.py
plugins/modules/net_tools/hetzner_failover_ip.py
plugins/modules/net_tools/hetzner_failover_ip_info.py
plugins/modules/net_tools/hetzner_firewall.py
plugins/modules/net_tools/hetzner_firewall_info.py
plugins/modules/system/lvg.py

Fix seealso sections in community.general https://github.com/ansible-collections/overview/issues/45

modules: fix seealso sections

---

tests/integration/targets/flatpak/tasks/test.yml
tests/integration/targets/flatpak_remote/tasks/test.yml

Fix typo in fatpak tests: state=preset → state=present

---

plugins/modules/files/archive.py

Fix seealso https://github.com/ansible-collections/overview/issues/45#issuecomment-648405709

archive: fix seealso

---

.github/BOTMETA.yml

Removed myself from team_solaris (no time for it)
- Other

- removed danowar2k from team_solaris (no time)

---

plugins/modules/database/postgresql/postgresql_db.py

Documentation when pg_restore is used.
Fixes: #588 
postgresql_db

postgresql_db: document when pg_restore is used

---

plugins/modules/cloud/packet/packet_device.py
plugins/modules/cloud/packet/packet_ip_subnet.py
plugins/modules/cloud/packet/packet_sshkey.py
plugins/modules/cloud/packet/packet_volume.py
plugins/modules/cloud/packet/packet_volume_attachment.py

Migrated from https://github.com/ansible/ansible/pull/68367
Signed-off-by: Radoslav Dimitrov dimitrovr@vmware.com
plugins/modules/cloud/packet/packet_device.py
plugins/modules/cloud/packet/packet_ip_subnet.py
plugins/modules/cloud/packet/packet_sshkey.py
plugins/modules/cloud/packet/packet_volume.py
plugins/modules/cloud/packet/packet_volume_attachment.py

docs: misc fixes for typos

---

tests/integration/targets/postgresql_idx/tasks/postgresql_idx_initial.yml

postgresql_idx: add CI tests for https://github.com/ansible-collections/community.general/issues/520

postgresql_idx: add CI tests

---

tests/integration/targets/postgresql_slot/tasks/postgresql_slot_initial.yml
tests/integration/targets/postgresql_user_obj_stat_info/tasks/postgresql_user_obj_stat_info.yml
tests/integration/targets/setup_postgresql_db/tasks/main.yml

postgresql CI tests: fix timeouts

postgresql CI tests: fix timeouts

---

tests/integration/targets/postgresql_slot/tasks/postgresql_slot_initial.yml
tests/integration/targets/postgresql_user_obj_stat_info/tasks/postgresql_user_obj_stat_info.yml

postgres modules: fix CI timeouts

postgres modules: fix CI timeouts

---

changelogs/fragments/569-pkgng-add-upgrade-action.yaml
plugins/modules/packaging/os/pkgng.py

Adds support for ``name: "*", state: latest`` to upgrade all installed packages, similar to other package providers.
pkgng
Fixes ansible/ansible#35515

pkgng: Add support for upgrading all installed packages 

---

plugins/modules/database/postgresql/postgresql_copy.py
plugins/modules/database/postgresql/postgresql_db.py
plugins/modules/database/postgresql/postgresql_ext.py
plugins/modules/database/postgresql/postgresql_idx.py
plugins/modules/database/postgresql/postgresql_info.py
plugins/modules/database/postgresql/postgresql_lang.py
plugins/modules/database/postgresql/postgresql_membership.py
plugins/modules/database/postgresql/postgresql_owner.py
plugins/modules/database/postgresql/postgresql_pg_hba.py
plugins/modules/database/postgresql/postgresql_ping.py
plugins/modules/database/postgresql/postgresql_privs.py
plugins/modules/database/postgresql/postgresql_publication.py
plugins/modules/database/postgresql/postgresql_query.py
plugins/modules/database/postgresql/postgresql_schema.py
plugins/modules/database/postgresql/postgresql_sequence.py
plugins/modules/database/postgresql/postgresql_set.py
plugins/modules/database/postgresql/postgresql_slot.py
plugins/modules/database/postgresql/postgresql_subscription.py
plugins/modules/database/postgresql/postgresql_table.py
plugins/modules/database/postgresql/postgresql_tablespace.py
plugins/modules/database/postgresql/postgresql_user.py
plugins/modules/database/postgresql/postgresql_user_obj_stat_info.py

postgresql modules: fix examples to use FQCN

postgresql modules: fix examples to use FQCN

---

changelogs/fragments/642-docker_container-python-2.yml
plugins/modules/cloud/docker/docker_container.py

docker_container: make sure to_text() and to_native() are used instead of str()

---

changelogs/fragments/66813_gitlab_project.yml
plugins/modules/source_control/gitlab/gitlab_project.py
tests/unit/plugins/modules/source_control/gitlab/gitlab.py
tests/unit/plugins/modules/source_control/gitlab/test_gitlab_project.py

Migrated from ansible/ansible#66813
Fixes: https://github.com/ansible/ansible/issues/66812
changelogs/fragments/66813_gitlab_project.yml
plugins/modules/source_control/gitlab/gitlab_project.py
tests/unit/plugins/modules/source_control/gitlab/gitlab.py
tests/unit/plugins/modules/source_control/gitlab/test_gitlab_project.py

gitlab_project: add support for merge_method on projects

---

tests/integration/targets/connection/test_connection.yml
tests/integration/targets/postgresql_slot/tasks/postgresql_slot_initial.yml
tests/integration/targets/postgresql_user/tasks/postgresql_user_initial.yml
tests/integration/targets/setup_redis_replication/tasks/setup_redis_cluster.yml
tests/integration/targets/supervisorctl/tasks/start_supervisord.yml

Test of using FQCN for some builtin plugins

Test of using FQCN for some builtin plugins

---

plugins/lookup/hashi_vault.py
plugins/lookup/lmdb_kv.py
plugins/lookup/nios.py
plugins/lookup/nios_next_ip.py
plugins/lookup/nios_next_network.py
plugins/lookup/passwordstore.py
plugins/modules/cloud/docker/docker_compose.py
plugins/modules/cloud/docker/docker_image_info.py
plugins/modules/cloud/google/gce.py
plugins/modules/cloud/opennebula/one_vm.py
plugins/modules/cloud/packet/packet_device.py
plugins/modules/cloud/rackspace/rax_facts.py
plugins/modules/database/postgresql/postgresql_query.py
plugins/modules/remote_management/redfish/idrac_redfish_info.py
plugins/modules/web_infrastructure/apache2_mod_proxy.py
plugins/modules/web_infrastructure/jenkins_plugin.py
plugins/modules/web_infrastructure/jenkins_script.py

modules: fix examples to use FQCN for builtin plugins

modules: fix examples to use FQCN for builtin plugins

---

changelogs/fragments/656-name-with-hyphen.yml
plugins/modules/database/postgresql/postgresql_privs.py
tests/integration/targets/postgresql_privs/defaults/main.yml
tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml

Fixes #656
postgresql-privs
```paste below
```

modules: fix names with hyphens (#656)

---

plugins/modules/database/misc/odbc.py
plugins/modules/odbc.py
tests/integration/targets/odbc/aliases
tests/integration/targets/odbc/defaults/main.yml
tests/integration/targets/odbc/meta/main.yml
tests/integration/targets/odbc/tasks/install_pyodbc.yml
tests/integration/targets/odbc/tasks/main.yml
tests/integration/targets/odbc/tasks/negative_tests.yml
tests/integration/targets/odbc/tasks/no_pyodbc.yml

Adding database ODBC module
odbc
This is a lift of https://github.com/ansible/ansible/pull/50845
```paste below
```

Adding ODBC module

---

changelogs/fragments/676-osx_defaults_fix_handling_negative_ints.yml
plugins/modules/system/osx_defaults.py
tests/integration/targets/osx_defaults/tasks/main.yml

Fixes https://github.com/ansible-collections/community.general/issues/134
Completed copy of https://github.com/ansible-collections/community.general/pull/250 initially made by @pshirshov
osx_defaults: fix handling negative integers
osx_defaults

osx_defaults: fix handling negative integers

---

plugins/inventory/cobbler.py
tests/unit/plugins/inventory/test_cobbler.py

This converts the cobbler inventory script to an inventory plugin.
cobbler
I'm also looking into maintaining this as a separate collection as part of the cobbler project here: https://github.com/cobbler/ansible.  I've requested the cobbler namespace on galaxy, but this may be problematic as there is an existing 'cobbler' user - although with no apparent content.

Add cobbler inventory plugin

---

plugins/modules/launchd.py
plugins/modules/system/launchd.py
tests/integration/targets/launchd/aliases
tests/integration/targets/launchd/files/ansible_test_service.py
tests/integration/targets/launchd/meta/main.yml
tests/integration/targets/launchd/tasks/main.yml
tests/integration/targets/launchd/tasks/setup.yml
tests/integration/targets/launchd/tasks/teardown.yml
tests/integration/targets/launchd/tasks/test.yml
tests/integration/targets/launchd/tasks/tests/test_reload.yml
tests/integration/targets/launchd/tasks/tests/test_restart.yml
tests/integration/targets/launchd/tasks/tests/test_runatload.yml
tests/integration/targets/launchd/tasks/tests/test_start_stop.yml
tests/integration/targets/launchd/tasks/tests/test_unknown.yml
tests/integration/targets/launchd/tasks/tests/test_unload.yml
tests/integration/targets/launchd/templates/launchd.test.service.plist.j2
tests/integration/targets/launchd/templates/modified.launchd.test.service.plist.j2
tests/integration/targets/launchd/vars/main.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

This PR is about introducing a new system module to control launchd services on macOS targets.
I moved the changes from the original PR against ansible repository to this repository (https://github.com/ansible/ansible/pull/45541)
launchd
Tested with Ansible 2.7.5, 2.9

launchd: new module to control launchd services on macOS hosts

---

meta/runtime.yml
plugins/modules/gcpubsub_facts.py

Add missing symlink, sort meta/runtime.yml entries.
collection

Add missing symlink, sort meta/runtime.yml entries

---

.github/BOTMETA.yml

Remove jose-delarosa from team_redfish. Jose moves to a new company and new role last year and is no longer involved with the Redfish module maintenance.
- Other

remove jose-delarosa - new job

---

plugins/modules/cloud/docker/docker_stack_info.py
plugins/modules/docker_stack_info.py
tests/integration/targets/docker_stack_info/aliases
tests/integration/targets/docker_stack_info/files/stack_compose_base.yml
tests/integration/targets/docker_stack_info/files/stack_compose_overrides.yml
tests/integration/targets/docker_stack_info/meta/main.yml
tests/integration/targets/docker_stack_info/tasks/main.yml
tests/integration/targets/docker_stack_info/tasks/test_stack_info.yml
tests/integration/targets/docker_stack_info/vars/main.yml

Implement docker_stack_info functionality
Fixes #540
`docker_stack_info.py`
Shows Docker stack list and tasks from a given stack name
```yaml
---
- name: Docker stack list
tasks:
- name: List stack
docker_stack_info:
register: stacklist
- name: show stack
debug:
msg: "{{ stacklist.results }}"
- name: Get stack first element
docker_stack_info:
name: "{{ stacklist.results[0].Name }}"
action: tasks
register: tasks
- name: Show stack tasks
debug:
msg: "{{ tasks.results }}"
```
Output
```json
"msg": [
{
"name": "grafana",
"namespace": "default",
"orchestrator": "Kubernetes",
"services": "2"
}
]
}
"msg": [
{
"current state": "Running 24 hours ago",
"desired state": …
```

New docker_stack_module with tests

---

changelogs/fragments/704-doas-set-correct-default-values.yml
changelogs/fragments/708-set-correct-default-values.yml
plugins/become/dzdo.py
plugins/become/ksu.py
plugins/become/pbrun.py
tests/unit/plugins/become/test_doas.py
tests/unit/plugins/become/test_dzdo.py
tests/unit/plugins/become/test_ksu.py
tests/unit/plugins/become/test_pbrun.py
tests/unit/plugins/become/test_pfexec.py

Similar to #704.
Also adds more tests.
dzdo
pbrun

Fix more become plugins

---

changelogs/fragments/610_logstash_callback_add_ini_config.yml
plugins/callback/logstash.py

Add ini configuration to callback logstash with new set_options
feature is present in 2.7
callback logstash
https://github.com/ansible/ansible/pull/66162

add ini config to logstash callback

---

plugins/modules/cloud/atomic/atomic_container.py
plugins/modules/cloud/atomic/atomic_host.py
plugins/modules/cloud/atomic/atomic_image.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Fix sanity for modules
```paste below
```

sanity: Fix sanity check for modules

---

tests/integration/targets/setup_wildfly_server/tasks/main.yml

Fixes the ugly hangs we had for some time now.
tests/integration/targets/setup_wildfly_server/tasks/main.yml

Fix jboss test (wildfly didn't start because of some permission problems)

---

plugins/lookup/dig.py
plugins/lookup/filetree.py

Fixes: #727
changelogs/fragments/727_filetree_example.yml
plugins/lookup/dig.py
plugins/lookup/filetree.py

filetree: Update example and documentation for plugin

---

.github/BOTMETA.yml

Removed myself from the Scaleway team.

bot: remove from team

---

plugins/lookup/consul_kv.py
plugins/lookup/cyberarkpassword.py
plugins/lookup/etcd3.py
plugins/lookup/gcp_storage_file.py

plugins/lookup/consul_kv.py
plugins/lookup/cyberarkpassword.py
plugins/lookup/dsv.py
plugins/lookup/etcd3.py
plugins/lookup/gcp_storage_file.py

lookup: Fix minor typos

---

plugins/lookup/dsv.py
plugins/lookup/tss.py

CC @amigus
plugins/lookup/dsv.py

Fix author entry for dsv and tss lookup plugin

---

changelogs/fragments/dsv_fix.yml
plugins/lookup/dsv.py

changelogs/fragments/dsv_fix.yml
plugins/lookup/dsv.py

dsv: Use correct dict usage

---

CHANGELOG.rst
changelogs/changelog.yaml

See #751 for whole discussion. I will move these entries to community.zabbix
Fixes #751 
changelogs/changelog.yaml

Cleanup changelog for not included zabbix plugins

---

plugins/action/shutdown.py
plugins/action/system/shutdown.py
plugins/modules/shutdown.py
plugins/modules/system/shutdown.py
tests/integration/targets/shutdown/aliases
tests/integration/targets/shutdown/tasks/main.yml

New module: shutdown
plugins/modules/system/shutdown.py
Firstly brought up in https://github.com/ansible/ansible/pull/70936, but as ansible team is not "accepting new modules to ansible/ansible directly", here it is.

New module: shutdown

---

changelogs/fragments/galaxy-yml.yml
galaxy.yml

Bump dependencies to 1.0.0. Also add tag.
galaxy.yml

Fix galaxy.yml

---

changelogs/fragments/789-pkg5-wrap-to-modify-package-list.yaml
plugins/modules/packaging/os/pkg5.py

Moved from https://github.com/ansible/ansible/pull/56378

pkg5: wrap 'to modify' package list

---

tests/integration/targets/callback_diy/tasks/main.yml

These fail, probably because a bug was fixed in ansible/ansible which changes one output.
plugins/callback/diy.py

Fix diy callback tests

---

plugins/modules/database/postgresql/postgresql_user.py

Relates to https://github.com/ansible-collections/community.general/pull/100
`plugins/modules/database/postgresql/postgresql_user.py`

postgresql_user: add a note explaining how to work with SCRAM-SHA passwords

---

.github/BOTMETA.yml

BOTMETA.yml: add a new team member to team_virt

BOTMETA.yml: add a new team member to team_virt

---

changelogs/fragments/843-update-slack-messages.yml
plugins/modules/notification/slack.py

Add `ts` option to the Slack module, to allow editing existing messages.
Fixes #304 - the issue I made did not get any replies so I'm just assuming it's fine.
`plugins/modules/notification/slack.py`

add message_id (ts) option to slack module to allow editing messages

---

changelogs/fragments/777-interfaces_file-re-escape.yml
plugins/modules/system/interfaces_file.py

Fixes #777 
interfaces_file
```paste below
```

interfaces_file: re.escape() old value

---

tests/integration/targets/setup_epel/tasks/main.yml

Fix failing integration tests. This was 'caused' by a fix for a CVE: ansible/ansible#71537
CI

Fix failing integration tests

---

.github/BOTMETA.yml

Remove amenonsen from BOTMETA.yml
N/A
N/A

Remove amenonsen from maintainer lists

---

.github/BOTMETA.yml

Add new members to gitlab team
BOTMETA.yml

Add new members to gitlab team

---

changelogs/fragments/943-proxmox-kvm-code-cleanup.yml
plugins/modules/cloud/misc/proxmox_kvm.py

Collections of fixes regarding readability and some very small performance enhancements.
This is more of a proposal right now as I don't want to interfere too much with the long awaited PR #797.
proxmox_kvm

proxmox_kvm: code cleanup

---

changelogs/fragments/941-postgresql_privs_usage_on_types_option.yml
plugins/modules/database/postgresql/postgresql_privs.py
tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml

Fixes https://github.com/ansible-collections/community.general/issues/884
`plugins/modules/database/postgresql/postgresql_privs.py`

postgresql_privs: add usage_on_types option

---

tests/integration/targets/setup_docker/tasks/Fedora.yml
tests/integration/targets/setup_docker/tasks/RedHat-7.yml
tests/integration/targets/setup_docker/tasks/RedHat-8.yml
tests/integration/targets/setup_docker/vars/RedHat-8.yml

Copy of ansible/ansible#71897 for community.general. (See https://app.shippable.com/github/ansible-collections/community.general/runs/3969/35/tests for an error.)
setup_docker

Fix docker test setup

---

changelogs/fragments/943-proxmox-kvm-code-cleanup.yml
plugins/modules/cloud/misc/proxmox_kvm.py

[PR #934 backport][stable-1] proxmox_kvm: code cleanup

---

.github/BOTMETA.yml

@tgoetheyn offered to help maintaining the nagios module (see #820).
@tgoetheyn when added to the maintainer's list for this module, you will receive notifications of all issues and PRs created for this module, and your `shipit`s will count more (not that relevant right now though).
Please give an Approve review to this PR to confirm that you really want to be come a maintainer for the module.
BOTMETA

Add tgoetheyn as maintainer for nagios module

---

.github/BOTMETA.yml

PostgreSQL team: add a new maintainer
DO NOT merge before @ilicmilan approval
team_postgresql

PostgreSQL team: add a new maintainer

---

changelogs/fragments/820_nagios_added_acknowledge_and_servicecheck.yml
plugins/modules/monitoring/nagios.py

Adds the option "acknowledge" and 'schedule_forced_svc_check' to the module actions.
This way the module can be used to acknowledge open host & service problems and to force a recheck of passive services in nagios
nagios
```paste below
```

Nagios: added 'acknowledge' and 'schedule_forced_svc_check' action

---

.github/BOTMETA.yml

django_manage module: add new maintainers
`BOTMETA.yml`

django_manage module: add new maintainers

---

.github/BOTMETA.yml

postgresql modules: fix BOTMETA.yml
BOTMETA.yml

postgresql modules: fix BOTMETA.yml

---

plugins/modules/monitoring/nagios.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Fixed errors in documentation and removed ignored sanity tests
nagios.py
```paste below
```

fixed ignored sanity tests in nagios module

---

changelogs/fragments/1048-postgresql_privs_add_procedure_type.yml
plugins/modules/database/postgresql/postgresql_privs.py
tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml

Fixes: https://github.com/ansible-collections/community.general/issues/1002
postgresql_privs: add procedure type support
`plugins/modules/database/postgresql/postgresql_privs.py`

postgresql_privs: add procedure type support

---

changelogs/fragments/1059-postgresql_privs_fix_failings_when_using_roles_with_hyphen.yml
plugins/modules/database/postgresql/postgresql_privs.py
tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml

Fixes https://github.com/ansible-collections/community.general/issues/1058
`plugins/modules/database/postgresql/postgresql_privs.py`

postgresql_privs: fix module fails when passing roles containing hyphens

---

changelogs/fragments/1081-solaris_zone-python3.yml
plugins/modules/system/solaris_zone.py
tests/unit/plugins/modules/system/test_solaris_zone.py

Fixes #1081 by explicitly opening `tempfile.NamedTemporaryFile` in text mode and adds a test.
`community.general.solaris_zone`
N/A

solaris_zone: fix zone configuration with python3

---

plugins/modules/files/iso_create.py

If pycdlib is missing, module does not fail. This fix adds
check availability of pycdlib.
Documentation updated with new example.
plugins/modules/files/iso_create.py

iso_create: Error handling while importing Pycdlib

---

.github/BOTMETA.yml

BOTMETA.yml cleanup

---

.github/BOTMETA.yml

@briantist did work on that lookup, and reviewed quite some PRs for it.
@briantist: please "Approve" this PR if you agree to become a maintainer.

Add briantist as a maintainer for the hashi_vault lookup

---

.github/BOTMETA.yml
plugins/modules/system/osx_defaults.py

See discussion in #358. The statements made by him in #358 should suffice, so no more pinging here is needed.
plugins/modules/system/osx_defaults.py

Make sure frenck is no longer accidentally contacted

---

changelogs/fragments/1118-docker_login-config-store.yml
plugins/modules/cloud/docker/docker_login.py
tests/integration/targets/docker_login/tasks/main.yml
tests/integration/targets/docker_login/tasks/test.yml
tests/integration/targets/setup_docker_registry/handlers/cleanup.yml
tests/integration/targets/setup_docker_registry/handlers/main.yml
tests/integration/targets/setup_docker_registry/meta/main.yml
tests/integration/targets/setup_docker_registry/tasks/main.yml
tests/integration/targets/setup_docker_registry/tasks/setup.yml

docker_login: fix internal config file storage to handle credentials for more than one registry

---

changelogs/fragments/1124-pg_hba-dictkey bugfix.yaml
changelogs/fragments/1124-pg_hba-dictkey_bugfix.yaml

Fix changelog fragment
`changelogs/fragments/1124-pg_hba-dictkey_bugfix.yaml`

Fix changelog fragment

---

plugins/modules/net_tools/hetzner_firewall.py

hetzner_firewall: use correct state in example

---

.github/BOTMETA.yml

@snopoke please approve this PR to confirm that you want to become a maintainer for the monit module!
This will make the bot ping you for every issue/PR affecting the module, and gives your `shipit` extra weight. And there's no need to do this forever, if you want to step down either tell us or create a PR which undoes this one ;-)
CC @Andersson007 
.github/BOTMETA.yaml

Add snopoke as monit maintainer

---

tests/integration/targets/postgresql_copy/aliases
tests/integration/targets/postgresql_db/aliases
tests/integration/targets/postgresql_ext/aliases
tests/integration/targets/postgresql_idx/aliases
tests/integration/targets/postgresql_info/aliases
tests/integration/targets/postgresql_lang/aliases
tests/integration/targets/postgresql_membership/aliases
tests/integration/targets/postgresql_owner/aliases
tests/integration/targets/postgresql_pg_hba/aliases
tests/integration/targets/postgresql_ping/aliases
tests/integration/targets/postgresql_privs/aliases
tests/integration/targets/postgresql_publication/aliases
tests/integration/targets/postgresql_query/aliases
tests/integration/targets/postgresql_schema/aliases
tests/integration/targets/postgresql_sequence/aliases
tests/integration/targets/postgresql_set/aliases
tests/integration/targets/postgresql_slot/aliases
tests/integration/targets/postgresql_subscription/aliases
tests/integration/targets/postgresql_table/aliases
tests/integration/targets/postgresql_tablespace/aliases
tests/integration/targets/postgresql_user/aliases
tests/integration/targets/postgresql_user_obj_stat_info/aliases

These modules have moved to community.postgresql, so don't run the tests
here in community.general
These modules and tests will be deleted soon

Don't run postgresql tests

---

tests/integration/targets/setup_docker/handlers/main.yml
tests/integration/targets/setup_docker/tasks/Debian.yml
tests/integration/targets/setup_docker_registry/handlers/cleanup.yml
tests/integration/targets/setup_docker_registry/tasks/setup-frontend.yml
tests/integration/targets/setup_docker_registry/tasks/setup.yml

Make them more readable.
setup_docker
setup_docker_registry

Improve docker test setups

---

changelogs/fragments/1179-composer_require_v2_idempotence_fix.yml
plugins/modules/packaging/language/composer.py

Fixes #1179
community.general.composer
N/A

Issue #1179: Fix v2 composer require idempotence

---

changelogs/fragments/1169-getbinpkgonly.yaml
plugins/modules/packaging/os/portage.py

Adds the --getbinpkgonly (-G) option to emerge.

Add getbinpkgonly (-G) to portage

---

changelogs/fragments/1175-zypper-absent-lang.yml
plugins/modules/packaging/os/zypper.py

Fix #1168
- plugins/modules/packaging/os/zypper.py

Fix lang issue on zypper absent

---

shippable.yml
tests/integration/targets/connection_docker/aliases
tests/integration/targets/cronvar/aliases
tests/integration/targets/docker_config/aliases
tests/integration/targets/docker_container/aliases
tests/integration/targets/docker_container_info/aliases
tests/integration/targets/docker_image/aliases
tests/integration/targets/docker_image_info/aliases
tests/integration/targets/docker_login/aliases
tests/integration/targets/docker_network/aliases
tests/integration/targets/docker_network_info/aliases
tests/integration/targets/docker_node/aliases
tests/integration/targets/docker_node_info/aliases
tests/integration/targets/docker_prune/aliases
tests/integration/targets/docker_secret/aliases
tests/integration/targets/docker_stack/aliases
tests/integration/targets/docker_stack_info/aliases
tests/integration/targets/docker_stack_task_info/aliases
tests/integration/targets/docker_swarm/aliases
tests/integration/targets/docker_swarm_info/aliases
tests/integration/targets/docker_swarm_service/aliases
tests/integration/targets/docker_swarm_service_info/aliases
tests/integration/targets/docker_volume/aliases
tests/integration/targets/docker_volume_info/aliases
tests/integration/targets/dpkg_divert/aliases
tests/integration/targets/inventory_docker_machine/aliases
tests/integration/targets/inventory_docker_swarm/aliases
tests/integration/targets/iptables_state/aliases
tests/integration/targets/lookup_passwordstore/aliases

They are now running in community.docker.
CI

Disable docker tests

---

changelogs/fragments/1144-consul-add-tcp-check-support.yml
plugins/modules/clustering/consul/consul.py

Added support for TCP healthcheck to the consul module
Fixes #1128 
consul
```paste below
```

Add TCP healthcheck support for services registered by consul module

---

changelogs/fragments/1105-beadm_bugfix.yaml
plugins/modules/system/beadm.py

Fixes #791 issue
beadm
See https://github.com/ansible-collections/community.general/issues/791 for detailed information

Unbreak beadm module

---

.github/BOTMETA.yml

Remove 'authors' from BOTMETA.yml

Remove 'authors' from BOTMETA.yml

---

plugins/modules/database/postgresql/postgresql_user.py

Copy of https://github.com/ansible-collections/community.postgresql/pull/26
Fixes https://github.com/ansible-collections/community.general/issues/1217
`plugins/modules/database/postgresql/postgresql_user.py`

postgresql_user: fix documentation formatting

---

tests/integration/targets/callback_log_plays/runme.sh

Fix callback_log_plays tests for current devel branch of ansible-base, like https://app.shippable.com/github/ansible-collections/community.general/runs/4906/73/console
log_plays callback integration tests

Fix callback_log_plays tests for current devel branch of ansible-base

---

changelogs/fragments/proxmox_template-appliance-download.yml
plugins/modules/cloud/misc/proxmox_template.py

Download proxmox applicance templates
proxmox_template
Now it is possible to download Proxmox appliance templates.
Proxmox API https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/aplinfo
```
- name: Download proxmox appliance container template
community.general.proxmox_template:
node: uk-mc02
api_password: 1q2w3e
api_host: node1
storage: local
content_type: vztmpl
template: ubuntu-20.04-standard_20.04-1_amd64.tar.gz
```

proxmox_template download appliance templates

---

README.md

Fixes #1231 
documentation
README

Clarify COLLECTIONS_PATH value when using clone

---

changelogs/fragments/1126-influxdb-conditional-path-argument.yml
plugins/doc_fragments/influxdb.py
plugins/module_utils/influxdb.py
plugins/modules/database/influxdb/influxdb_database.py

Make the path argument conditional on the InfluxDB version
Fixes #997 
influxdb_database
```paste below
```

InfluxDB_database: Make the path argument conditional on the InfluxDB version

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/408
Add @imjoseangel as a maintainer

BOTMETA.yml: add a maintainer for syslog_json

---

.github/BOTMETA.yml

Add @rosowiecki as a maintainer of `parted` module

BOTMETA.yml: add a new maintainer of parted module

---

.github/BOTMETA.yml

BOTMETA.yml: add @quidame as a new maintainer of filesystem module
Relates to https://github.com/ansible-collections/community.general/pull/1149

BOTMETA.yml: add a new maintainer of filesystem module

---

.github/BOTMETA.yml

BOTMETA.yml: add a maintainer of pagerduty_change module

BOTMETA.yml: add a maintainer of pagerduty_change module

---

tests/integration/targets/zypper/tasks/zypper.yml

See failed runs in https://app.shippable.com/github/ansible-collections/community.general/runs/5131/summary/console.
zypper

Fix zypper tests

---

tests/integration/targets/iso_extract/vars/Suse.yml

See https://app.shippable.com/github/ansible-collections/community.general/runs/5131/summary/console
CI

Fix iso_extract tests on OpenSuSE

---

changelogs/fragments/fix-plugin-imports.yml
plugins/cache/memcached.py
plugins/cache/redis.py
plugins/inventory/linode.py
plugins/lookup/gcp_storage_file.py

Fixes #1281, fixes #1282, fixes #1283, fixes #1284.
various plugins

Fix plugin imports

---

changelogs/fragments/1305-added-xfconf-tests.yaml
plugins/modules/system/xfconf.py
tests/unit/plugins/modules/system/test_xfconf.py

Added unit test to xfconf, plus a couple of adjustments.
Fixes #695 
xfconf
Nothing changes for the end user, but the module now has unit testing.

Xfconf tests

---

changelogs/fragments/1083-archive-remove-path-folder.yml
plugins/modules/files/archive.py
tests/integration/targets/archive/tasks/main.yml
tests/integration/targets/archive/tasks/remove.yml

Fixes https://github.com/ansible-collections/community.general/issues/1041
archive

archive: remove path folder itself when remove paramater is true

---

changelogs/fragments/1083-archive-remove-path-folder.yml

https://github.com/ansible-collections/community.general/pull/1083 stated as a breaking change after further discussion, this PR fixes the changelog.
https://github.com/ansible-collections/community.general/pull/1083#issuecomment-731346634

Change bugfixes to breaking_changes in 1083 changelog

---

changelogs/fragments/788-fix_omapi_host_on_python3.yaml
plugins/modules/net_tools/omapi_host.py

[2.10] Fix omapi_host on python3

---

changelogs/fragments/hetzner-migration.yml

Similar to ansible-collections/community.general#1303.
changelog

[WIP] [stable-1] Add information on hetzner robot content migration

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/788
BOTMETA.yml

BOTMETA.yml: add a new maintainer for omapi_host module

---

changelogs/fragments/1039-archive-fix-paramater-types.yaml
plugins/modules/files/archive.py
tests/integration/targets/archive/tasks/main.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Fix archive module paramater types and remove sanity ignores.

archive: Fix paramater types

---

changelogs/fragments/797-proxmox-kvm-cloud-init.yaml
plugins/modules/cloud/misc/proxmox_kvm.py

Add cloud-init params to proxmox_kvm module (ported from @nuttybrewer - https://github.com/ansible/ansible/pull/54108)
community.general.proxmox_kvm
Docs: https://pve.proxmox.com/wiki/Cloud-Init_Support

Add Cloud Init variables for Proxmox_KVM module

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/1256
BOTMETA.yml: Add a new maintainer of pkgin module

BOTMETA.yml: Add a new maintainer of pkgin module

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/768
BOTMETA.yml

BOTMETA.yml: add a new maintainer of facter module

---

changelogs/fragments/1383-apache2-module-amend-shib-workaround.yaml
plugins/modules/web_infrastructure/apache2_module.py

Apache2 module: Add another shib module identifier

---

changelogs/fragments/deprecation-removals.yml
galaxy.yml
plugins/action/system/iptables_state.py
plugins/cache/memcached.py
plugins/cache/redis.py
plugins/modules/files/xml.py
tests/integration/targets/xml/tasks/test-get-element-content.yml
tests/unit/plugins/cache/test_memcached.py
tests/unit/plugins/cache/test_redis.py

Bump collection version to 2.0.0.
This is mainly a test ot see which sanity tests will start failing.
collection

Bump version to 2.0.0

---

changelogs/fragments/1428-npm-no-optional.yml
plugins/modules/packaging/language/npm.py

Add no-optional flag to npm

---

changelogs/fragments/1404-proxmox-doc-fragments.yml
plugins/doc_fragments/proxmox.py
plugins/modules/cloud/misc/proxmox.py
plugins/modules/cloud/misc/proxmox_kvm.py
plugins/modules/cloud/misc/proxmox_template.py

Use the common doc_fragment describing the authentication parameters and add a new one specifically for three parameters shared by `proxmox` and `proxmox_kvm`.
- proxmox
- proxmox_kvm
- proxmox_template
I am not particularly sure about the usefulness of commit 70c1f23.

Proxmox doc fragments

---

changelogs/fragments/604-lists_mergeby-new-filter.yml
plugins/filter/list.py
tests/integration/targets/filter_list/aliases
tests/integration/targets/filter_list/tasks/main.yml
tests/integration/targets/filter_list/vars/main.yml

See #249
lists_mergeby
```paste below
```

Added filter plugin lists_mergeby. Fix #249

---

plugins/modules/cloud/linode/linode.py
plugins/modules/cloud/spotinst/spotinst_aws_elastigroup.py
plugins/modules/monitoring/sensu/sensu_check.py
plugins/modules/monitoring/sensu/sensu_client.py
tests/sanity/ignore-2.11.txt

See https://app.shippable.com/github/ansible-collections/community.general/runs/5820/2/tests and https://github.com/ansible/ansible/pull/72699
linode
spotinst_aws_elastigroup
sensu_ceck
sensu_client

Fix new sanity errors

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/1405
BOTMETA.yml

BOTMETA.yml: add maintainers of yum_versionlock module

---

.github/BOTMETA.yml

relates to https://github.com/ansible-collections/community.general/pull/604
BOTMETA.yml

BOTMETA.yml: Add a maintainer of filter/list plugin

---

changelogs/fragments/1455-rhn-register-force.yml
plugins/modules/packaging/os/rhn_register.py

Add a 'force' option to rhn_register module, to allow re-registering a system.
Fixes #1454 
rhn_register
See issue #1454 
```paste below
```

rhn_register: added force option to allow forced registering (#1454)

---

tests/sanity/ignore-2.10.txt

Follow-up to #1451, since https://github.com/ansible/ansible/pull/72864 has been merged into stable-2.10.
CI sanity tests

Add ignore-2.10.txt entry analogous to ignore-2.11.txt entry

---

changelogs/fragments/community.docker-43-docker_container-device_requests.yml
plugins/modules/cloud/docker/docker_container.py

Backport of https://github.com/ansible-collections/community.docker/pull/43 to stable-1.

[stable-1] Fix capabilities validation for device_requests

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/358
BOTMETA.yml

BOTMETA.yml: Add a new maintainer of osx_defaults module

---

tests/integration/targets/docker_image/tasks/tests/old-options.yml
tests/integration/targets/docker_image/tasks/tests/options.yml

Backport of https://github.com/ansible-collections/community.docker/pull/47 to stable-1.
docker_image

[stable-1] Fix docker_image tests

---

tests/integration/targets/filter_list/tasks/lists_mergeby.yml
tests/integration/targets/filter_list/tasks/main.yml
tests/integration/targets/filter_list/vars/main.yml

Added integration tests for target filter_list #604
None
Filter lists_mergeby
None
```

Added integration tests for target filter_list

---

tests/integration/targets/docker_container/tasks/tests/network.yml
tests/integration/targets/setup_docker/library/current_container_facts.py
tests/integration/targets/setup_docker/tasks/RedHat-7.yml
tests/integration/targets/setup_docker/tasks/RedHat-8.yml
tests/integration/targets/setup_docker/tasks/main.yml
tests/integration/targets/setup_docker_registry/tasks/setup-frontend.yml
tests/integration/targets/setup_docker_registry/tasks/setup.yml

Backport of important parts of https://github.com/ansible-collections/community.docker/pull/48 to stable-1.
docker tests in CI

[stable-1] Prepare docker tests for AZP

---

plugins/modules/monitoring/icinga2_host.py

Clarify documentation of variables option and add to the example.
icinga2_host

Icinga doc fix

---

changelogs/fragments/638_cobbler_py3.yml
scripts/inventory/cobbler.py

This fixes #638
inventory/cobbler.py

cobbler: Add Python 3 support

---

changelogs/fragments/1425_bitbucket_pipeline_variable.yml
plugins/modules/source_control/bitbucket/bitbucket_pipeline_variable.py

Bitbucket's pagination for pipeline variables is flawed.
Refactor bitbucket_pipeline_variable code to correct this logic.
Fixes: #1425
changelogs/fragments/1425_bitbucket_pipeline_variable.yml
plugins/modules/source_control/bitbucket/bitbucket_pipeline_variable.py

bitbucket_pipeline_variable: Change pagination logic

---

.azure-pipelines/azure-pipelines.yml
tests/integration/targets/filesystem/tasks/main.yml
tests/integration/targets/nomad/aliases
tests/unit/plugins/callback/test_splunk.py
tests/utils/shippable/shippable.sh

Fix some of the remaining issues.
CI

Fix AZP CI

---

changelogs/fragments/1504_jira.yml
plugins/modules/web_infrastructure/jira.py

* Code refactor
* Handle exception
* Provide useful error message to user when exception is raised
Fixes: #1504
changelogs/fragments/1504_jira.yml
plugins/modules/web_infrastructure/jira.py

jira: Provide useful error message to user

---

changelogs/fragments/1516-ldap_entry-improvements.yaml
plugins/modules/net_tools/ldap/ldap_entry.py

- Added doc details for parameters ``description`` and ``objectClass``
- Added type details to argument_spec of parameters ``description`` and ``objectClass``.
- Removed unused import
- Simplified logic of ``LdapEntry._load_attrs()``
- Replaced parameter validation test with ``required_if``.
ldap_entry.py

Some adjustments/improvements

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/1135
`BOTMETA.yml`

BOTMETA.yml: add maintainers of proxmox_snap module

---

changelogs/fragments/1040-ldap_search-changed-must-be-false.yaml
plugins/modules/net_tools/ldap/ldap_search.py

Made the change.
Also added a small improvement on the ``_load_scope()`` method.
Fixes #1040 
ldap_search

Ensured ``changed`` returns ``False``.

---

changelogs/fragments/1021-git_config-custom-file.yaml
plugins/modules/source_control/git_config.py

Implements the file feature as specified in the issue.
Fixes #1021 
git_config

Added file feature

---

changelogs/fragments/community.docker-53-docker_image-tag-push.yml
plugins/modules/cloud/docker/docker_image.py
tests/integration/targets/docker_image/tasks/tests/docker_image.yml

Backport of ansible-collections/community.docker#53 to stable-1.
docker_image

[stable-1] docker_image: always push, also when tagging is not necessary

---

changelogs/fragments/1506_gitlab_project.yml
plugins/modules/source_control/gitlab/gitlab_project.py

* Update docs
* Update example
* Refactor code
* Add a parameter ``lfs_enabled`` to specify Git Large file systems
Fixes: #1506
changelogs/fragments/1506_gitlab_project.yml
plugins/modules/source_control/gitlab/gitlab_project.py

gitlab_project: Add a parameter to specify Git LFS

---

.github/BOTMETA.yml

Add hnakamur to ignore list for LXD modules

---

changelogs/fragments/jira_improvements.yaml
plugins/modules/web_infrastructure/jira.py

- Fixed examples documentation.
- Module no longer incorrectly reports change for information gathering operations.
- Replaced custom parameter validation with ``required_if``.
- Added the ``traceback`` output to ``fail_json()`` calls deriving from exceptions.
This work was prompted by looking at #1233 but I am not sure whether it solves the issue.
jira

jira - some improvements to the module

---

changelogs/fragments/community.docker-55-docker_image-loading.yml
plugins/modules/cloud/docker/docker_image.py
tests/integration/targets/docker_image/tasks/tests/options.yml

Backport of ansible-collections/community.docker#55 to stable-1.
docker_image

[stable-1] docker_image: check output of load_image and react upon

---

changelogs/fragments/479-ini_file-empty-section.yaml
plugins/modules/files/ini_file.py
tests/integration/targets/ini_file/tasks/main.yml

Fixed case of empty section, plus validating parameter ``value`` if ``state`` is ``present`` and ``allow_no_value`` is ``False``.
Fixes #479 
ini_file

ini_file: fixed case of empty section + parameter validation

---

changelogs/fragments/1553_sendgrid.yml
plugins/modules/notification/sendgrid.py

* Updated docs
* Warn user about required Sendgrid Python library version i.e <=1.6.22
changelogs/fragments/1553_sendgrid.yml
plugins/modules/notification/sendgrid.py

sendgrid: Update docs

---

meta/runtime.yml

Follow-up to #1319.
CC @dmsimard 

Google: add forgotten redirect

---

plugins/modules/cloud/lxc/lxc_container.py

plugins/modules/cloud/lxc/lxc_container.py

lxc_container: update docs

---

plugins/modules/net_tools/snmp_facts.py

plugins/modules/net_tools/snmp_facts.py

snmp_facts: doc update

---

changelogs/fragments/953_syslogger.yml
plugins/modules/notification/syslogger.py

Fixes: #953
changelogs/fragments/953_syslogger.yml
plugins/modules/notification/syslogger.py

syslogger - update syslog.openlog API call for older Python

---

changelogs/fragments/830-pam-limits.yml
plugins/modules/system/pam_limits.py

pam_limits: adds both check and diff modes
Fixes #827, fixes #828.
pam_limits
```paste below
```

pam_limits: adds both check and diff modes

---

plugins/modules/system/pam_limits.py
tests/integration/targets/pam_limits/aliases
tests/integration/targets/pam_limits/files/test_pam_limits.conf
tests/integration/targets/pam_limits/tasks/main.yml

* Add integration tests
plugins/modules/system/pam_limits.py
tests/integration/targets/pam_limits/aliases
tests/integration/targets/pam_limits/files/test_pam_limits.conf
tests/integration/targets/pam_limits/tasks/main.yml

pam_limits: add integration tests

---

tests/integration/targets/nomad/aliases
tests/integration/targets/nomad/tasks/nomad_job.yml

Fixes #1510
tests/integration/targets/nomad/aliases

Re-enable nomad tests

---

changelogs/fragments/55903_kubevirt.yml

Some files were still there.
CC @dmsimard 
collection

Remove kubevirt leftovers

---

changelogs/fragments/kubevirt-migration.yml

Add kubevirt removal announcement.
changelog

[stable-1] Add kubevirt removal announcement

---

tests/integration/targets/hg/aliases
tests/integration/targets/hg/tasks/main.yml
tests/integration/targets/hg/tasks/run-tests.yml

* Update license boilerplate
* Change mercurial repository links
Fixes: #840
tests/integration/targets/hg/aliases
tests/integration/targets/hg/tasks/main.yml
tests/integration/targets/hg/tasks/run-tests.yml

hg: Re-enable tests

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/1147
BOTMETA.yml

BOTMETA.yml: add ipa_pwpolicy module maintainer

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/357
BOTMETA.yml

BOTMETA.yml: add rpm_ostree_pkg module maintainers

---

changelogs/fragments/cloudflare_dns.yml
plugins/modules/net_tools/cloudflare_dns.py

Fall back to reading the API token from the environment if not specified in the arguments.
cloudflare_dns
```paste below
```

cloudflare_dns: read API token from environment

---

tests/integration/targets/monit/aliases

They fail repeatedly: https://dev.azure.com/ansible/community.general/_build/results?buildId=3802&view=logs&jobId=82364942-2998-59d8-4cdd-e3bc93e5f684&j=82364942-2998-59d8-4cdd-e3bc93e5f684&t=b70435cd-a65a-5bf5-a79e-73ec6742743f
monit

Skip monit tests on RHEL.

---

plugins/modules/monitoring/nagios.py

Updated doc. Module not idempotent. delegate_to not needed.

---

.github/BOTMETA.yml

Removing bigmstone from BOTMETA.
- N/A

Remove bigmstone

---

changelogs/fragments/1614_npm.yml
plugins/modules/packaging/language/npm.py
tests/unit/plugins/modules/packaging/language/test_npm.py

* Provide a user friendly message by handling json decode
exception rather than providing a stacktrace
Fixes: #1614
changelogs/fragments/1614_npm.yml
plugins/modules/packaging/language/npm.py

npm - handle json decode exception

---

changelogs/fragments/1197_gitlab_project_variable.yml
plugins/modules/source_control/gitlab/gitlab_project_variable.py
tests/integration/targets/gitlab_project_variable/tasks/main.yml

Manage environment scope for a variable in a gitlab project
gitlab_project_variables
```paste below
```

Add environment scope on gitlab project variables

---

.azure-pipelines/azure-pipelines.yml
tests/integration/targets/filter_jc/runme.sh
tests/integration/targets/filter_json_query/runme.sh

See [here](https://github.com/ansible-collections/overview/issues/45#issuecomment-758250849) for infos.
CI

Add macOS 11.1 tests

---

plugins/lookup/tss.py

Extended line runs past the side of the browser window
```paste below
```

Update tss.py - multiline for an example

---

plugins/lookup/tss.py

Now that it's multiline, it's not exactly easy to read.

Improve readability of example.

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/1460
BOTMETA.yml

BOTMETA: add sysrc module maintainer

---

changelogs/fragments/dconf_refactor.yml
plugins/modules/system/dconf.py

* Updated documentation
* Use ``module.get_bin_path`` API to check existence of
``dbus-send``, ``dconf``, and ``dbus-run-session``
* Return ``out`` and ``err`` in ``fail_json`` which helps debugging
plugins/modules/system/dconf.py

dconf: Code refactor

---

plugins/modules/system/parted.py

Fixes incorrect example highlighted in #1653 
plugin/modules/parted.py

Fix parted resize example in docs (#1653)

---

.azure-pipelines/azure-pipelines.yml
tests/integration/targets/setup_openssl/vars/FreeBSD.yml
tests/integration/targets/setup_postgresql_db/vars/FreeBSD-11-py3.yml
tests/integration/targets/setup_postgresql_db/vars/FreeBSD-12.0-py3.yml
tests/integration/targets/setup_postgresql_db/vars/FreeBSD-12.1-py3.yml
tests/integration/targets/xml/tasks/main.yml

See https://github.com/ansible-collections/overview/issues/45#issuecomment-765009344
CI

Bump CI to FreeBSD 11.4, 12.2.

---

.azure-pipelines/azure-pipelines.yml
tests/integration/targets/mqtt/aliases
tests/integration/targets/mqtt/tasks/main.yml
tests/integration/targets/setup_postgresql_db/vars/Ubuntu-20-py3.yml

Add Ubuntu 20.04 to CI

---

tests/integration/targets/java_cert/aliases
tests/integration/targets/java_cert/meta/main.yml
tests/integration/targets/java_cert/tasks/main.yml
tests/integration/targets/java_keystore/aliases
tests/integration/targets/java_keystore/meta/main.yml
tests/integration/targets/java_keystore/tasks/main.yml
tests/integration/targets/setup_java_keytool/meta/main.yml
tests/integration/targets/setup_java_keytool/tasks/main.yml
tests/integration/targets/setup_java_keytool/vars/Debian.yml
tests/integration/targets/setup_java_keytool/vars/RedHat.yml
tests/integration/targets/setup_java_keytool/vars/Suse.yml

More tests in CI \o/
java_cert
java_keystore

Add CI tests for java_cert and java_keystore

---

.github/BOTMETA.yml
changelogs/fragments/telegram-api-update.yml
plugins/modules/notification/telegram.py

Telegram API changed drastically since 2016. I made some changes to cover latest and future changes in API.
Backward compatibility preserved.
community.general.telegram
see https://core.telegram.org/bots/api#sendmessage
Personally, I missed following new options for "SendMessage":
disable_web_page_preview
disable_notification
parse_mode == MarkdownV2 (wasn't an option)
I also made "api_method" as argument, so you may use other api methods if needed.
So, before we could do only this:
```   
- name: Send a message to chat in playbook (old style)
community.general.telegram:
token: '9999999:XXXXXXXXXXXXXXXXXXXXXXX'
chat_id: 000000
msg: Ansible task finished
```
now you can:
```
- name: Send notify to Telegram
community.general.telegram:
token: …
```

Some improvements to community.general.telegram

---

changelogs/fragments/community.docker-66-ipv6-zones.yml
plugins/modules/cloud/docker/docker_container.py
tests/integration/targets/docker_container/tasks/tests/options.yml

Backport of https://github.com/ansible-collections/community.docker/pull/66 to stable-1.
docker_network

[stable-1] Fix IPv6 zone handling

---

tests/requirements.yml
tests/utils/shippable/shippable.sh

Looks like we forgot this one when removing the kubevirt stuff.
- Testing Pull Request
CI

Remove community.kubernetes testing dependency.

---

changelogs/fragments/1618-ldap_search-switch-off-cheasing-referrals.yaml
plugins/doc_fragments/ldap.py
plugins/module_utils/ldap.py
plugins/modules/net_tools/ldap/ldap_search.py

Switch off client-chasing referrals.
Fixes #1067
community.general.ldap_search
```paste below
```

ldap_search: switch off client-chasing referrals

---

plugins/modules/copr.py
plugins/modules/packaging/os/copr.py
tests/integration/targets/copr/aliases
tests/integration/targets/copr/tasks/main.yml

I'm from the Copr team and we decided to create our own copr module, which contains properties just like `dnf copr enable/remove/disable`. We currently have the module in our pagure repository https://pagure.io/copr/copr/blob/master/f/ansible, so copr users had the opportunity to try the module locally. We decided to make this module more accessible to users and add it to the collection. Copr users wanted to add this module to ansible some time ago, see [#26673](https://github.com/ansible/ansible/issues/26673)
copr

New module: Add copr module

---

plugins/modules/ssh_config.py
plugins/modules/system/ssh_config.py
tests/integration/targets/ssh_config/aliases
tests/integration/targets/ssh_config/tasks/main.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Fixes: #1562
plugins/modules/ssh_config.py
plugins/modules/system/ssh_config.py

ssh_config: new module

---

changelogs/fragments/1690-scaleway-regions.yaml
plugins/inventory/scaleway.py
plugins/module_utils/scaleway.py
plugins/modules/cloud/scaleway/scaleway_compute.py
plugins/modules/cloud/scaleway/scaleway_database_backup.py
plugins/modules/cloud/scaleway/scaleway_image_facts.py
plugins/modules/cloud/scaleway/scaleway_image_info.py
plugins/modules/cloud/scaleway/scaleway_ip.py
plugins/modules/cloud/scaleway/scaleway_ip_facts.py
plugins/modules/cloud/scaleway/scaleway_ip_info.py
plugins/modules/cloud/scaleway/scaleway_lb.py
plugins/modules/cloud/scaleway/scaleway_security_group.py
plugins/modules/cloud/scaleway/scaleway_security_group_facts.py
plugins/modules/cloud/scaleway/scaleway_security_group_info.py
plugins/modules/cloud/scaleway/scaleway_security_group_rule.py
plugins/modules/cloud/scaleway/scaleway_server_facts.py
plugins/modules/cloud/scaleway/scaleway_server_info.py
plugins/modules/cloud/scaleway/scaleway_snapshot_facts.py
plugins/modules/cloud/scaleway/scaleway_snapshot_info.py
plugins/modules/cloud/scaleway/scaleway_user_data.py
plugins/modules/cloud/scaleway/scaleway_volume.py
plugins/modules/cloud/scaleway/scaleway_volume_facts.py
plugins/modules/cloud/scaleway/scaleway_volume_info.py

Scaleway provides some new zones since a while: https://developers.scaleway.com/en/products/instance/api/#endpoints
scaleway
None.

update scaleway zones

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/1592
BOTMETA.yml

BOTMETA.yml: add a new maintainer of the copr module

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/641
BOTMETA.yml

BOTMETA.yml: add logstash plugin maintainer

---

changelogs/fragments/dellemc-migration.yml

Announce #1699 in stable-2 changelog.
Must only be merged once ansible-community/ansible-build-data#58 has been merged.
changelog

[stable-2] DellEMC removal announcement

---

tests/integration/targets/hg/tasks/install.yml
tests/integration/targets/hg/tasks/uninstall.yml

Fix hg tests (see https://dev.azure.com/ansible/community.general/_build/results?buildId=5821&view=logs&j=49a00612-4cd4-56f1-eb97-89982ed15d65&t=250592d1-617c-57f0-64fc-8248cc10921e&l=2302).
hg

Fix mercurial tests

---

.azure-pipelines/azure-pipelines.yml

azure-pipelines: update container version
implements https://github.com/ansible-collections/overview/issues/45#issuecomment-776163864
azure-pipelines.yml

azure-pipelines: update container version

---

changelogs/fragments/1761-redfish-tidy-up-validation.yml
plugins/modules/remote_management/redfish/idrac_redfish_command.py
plugins/modules/remote_management/redfish/idrac_redfish_config.py
plugins/modules/remote_management/redfish/idrac_redfish_info.py
plugins/modules/remote_management/redfish/redfish_command.py
plugins/modules/remote_management/redfish/redfish_config.py
plugins/modules/remote_management/redfish/redfish_info.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt

Removed parameter-list-no-elements validation errors from redfish modules
idrac_redfish_command.py
idrac_redfish_config.py
idrac_redfish_info.py

Removed parameter-list-no-elements validation errors from redfish modules

---

.azure-pipelines/azure-pipelines.yml
tests/integration/targets/mqtt/tasks/main.yml
tests/integration/targets/setup_postgresql_db/vars/Ubuntu-20-py3.yml

Backport of #1658 to stable-1, plus some more.
CI

[stable-1] Add ubuntu2004, upgrade CI to be more similar to main

---

changelogs/fragments/selective-core-2.11.yml
plugins/callback/selective.py

Found by the new import test for plugins :tada:

Make selective callback work with ansible-core 2.11

---

changelogs/fragments/1766-zfs-fixed-sanity.yml
plugins/modules/storage/zfs/zfs.py
plugins/modules/storage/zfs/zfs_delegate_admin.py
plugins/modules/storage/zfs/zfs_facts.py
plugins/modules/storage/zfs/zpool_facts.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Tidy up validation for storage/zfs modules
plugins/modules/storage/zfs/zpool_facts.py
plugins/modules/storage/zfs/zfs_facts.py
plugins/modules/storage/zfs/zfs_delegate_admin.py
plugins/modules/storage/zfs/zfs.py

Tidy up validation for storage/zfs modules

---

changelogs/fragments/1765-proxmox-params.yml
plugins/modules/cloud/misc/proxmox.py
plugins/modules/cloud/misc/proxmox_kvm.py
plugins/modules/cloud/misc/proxmox_template.py

Backport of #1765 to stable-1.
plugins/modules/cloud/misc/proxmox_template.py
plugins/modules/cloud/misc/proxmox_user_info.py

[stable-1] Improved parameter handling on proxmox modules

---

changelogs/fragments/1715-proxmox_kvm-add-vmid-to-returns.yml
plugins/modules/cloud/misc/proxmox_kvm.py

Backport of #1715 to stable-1.
proxmox_kvm

[stable-1] Added VMID to all returns

---

changelogs/fragments/1795-list-elements-batch1.yml
plugins/doc_fragments/oracle_creatable_resource.py
plugins/module_utils/oracle/oci_utils.py
plugins/modules/cloud/lxd/lxd_container.py
plugins/modules/cloud/packet/packet_device.py
plugins/modules/cloud/pubnub/pubnub_blocks.py
plugins/modules/cloud/smartos/vmadm.py
plugins/modules/cloud/softlayer/sl_vm.py
plugins/modules/files/xml.py
plugins/modules/identity/keycloak/keycloak_client.py
plugins/modules/identity/onepassword_info.py
plugins/modules/monitoring/librato_annotation.py
plugins/modules/monitoring/pagerduty.py
plugins/modules/monitoring/statusio_maintenance.py
plugins/modules/net_tools/dnsimple.py
plugins/modules/net_tools/nsupdate.py
plugins/modules/net_tools/omapi_host.py
plugins/modules/notification/mail.py
plugins/modules/notification/nexmo.py
plugins/modules/notification/office_365_connector_card.py
plugins/modules/notification/rocketchat.py
plugins/modules/notification/sendgrid.py
plugins/modules/notification/slack.py
plugins/modules/notification/twilio.py
plugins/modules/packaging/os/redhat_subscription.py
plugins/modules/source_control/gitlab/gitlab_runner.py
plugins/modules/storage/netapp/na_ontap_gather_facts.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Backport of #1795 to stable-1.
plugins/doc_fragments/oracle_creatable_resource.py
plugins/module_utils/oracle/oci_utils.py
plugins/modules/cloud/lxd/lxd_container.py
plugins/modules/cloud/packet/packet_device.py
plugins/modules/cloud/pubnub/pubnub_blocks.py
plugins/modules/cloud/softlayer/sl_vm.py
plugins/modules/files/xml.py
plugins/modules/identity/keycloak/keycloak_client.py
plugins/modules/identity/onepassword_info.py
plugins/modules/monitoring/librato_annotation.py
plugins/modules/monitoring/pagerduty.py
plugins/modules/net_tools/dnsimple.py
plugins/modules/net_tools/nsupdate.py
plugins/modules/net_tools/omapi_host.py
plugins/modules/notification/mail.py
plugins/modules/notification/nexmo.py …

[stable-1] Tidy up validate-modules:parameter-list-no-elements (batch 1)

---

changelogs/fragments/1819-tidyup-pylint-blacklistnames.yml
plugins/callback/hipchat.py
plugins/connection/lxc.py
plugins/modules/cloud/lxc/lxc_container.py
plugins/modules/monitoring/statusio_maintenance.py
plugins/modules/system/alternatives.py
plugins/modules/system/beadm.py
plugins/modules/system/cronvar.py
plugins/modules/system/dconf.py
plugins/modules/system/filesystem.py
plugins/modules/system/gconftool2.py
plugins/modules/system/interfaces_file.py
plugins/modules/system/java_cert.py
plugins/modules/system/lvg.py
plugins/modules/system/lvol.py
plugins/modules/system/parted.py
plugins/modules/system/timezone.py
plugins/modules/web_infrastructure/rundeck_acl_policy.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Tidy up all pylint:blacklisted-name ignore lines
plugins/modules/web_infrastructure/rundeck_acl_policy.py
plugins/modules/system/timezone.py
plugins/modules/system/parted.py
plugins/modules/system/lvol.py
plugins/modules/system/lvg.py
plugins/modules/system/java_cert.py
plugins/modules/system/interfaces_file.py
plugins/modules/system/dconf.py
plugins/modules/system/cronvar.py
plugins/modules/system/beadm.py
plugins/modules/system/alternatives.py
plugins/modules/monitoring/statusio_maintenance.py
plugins/modules/cloud/lxc/lxc_container.py
plugins/callback/hipchat.py

Tidy up all pylint:blacklisted-name ignore lines

---

changelogs/fragments/1838-runit-deprecate-param-dist.yml
plugins/modules/system/runit.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Properly deprecate parameter
runit

runit - deprecate param dist

---

changelogs/fragments/1735-imc-sessions.yml
plugins/modules/remote_management/imc/imc_rest.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Module had a ```logout()``` function defined but instead of calling it directly, the code was using ```atexit.register()```.
Fixes #1735 
plugins/modules/remote_management/imc/imc_rest.py

Fixed imc_rest session logout

---

plugins/modules/gitlab_project_members.py
plugins/modules/source_control/gitlab/gitlab_project_members.py
tests/integration/targets/gitlab_project_members/aliases
tests/integration/targets/gitlab_project_members/defaults/main.yml
tests/integration/targets/gitlab_project_members/tasks/main.yml

this module for add/delete members to/from projects

added gitlab_project_members

---

plugins/modules/cloud/misc/proxmox_storage_info.py
plugins/modules/proxmox_storage_info.py
tests/integration/targets/proxmox/aliases
tests/integration/targets/proxmox/tasks/main.yml

I needed a method to dynamically convert from a storage name to a storage path so I implemented this simple module.
proxmox_storage_info

New module proxmox_storage_info

---

plugins/inventory/linode.py

Backport of #1887 to stable-1.
linode inventory plugin

[stable-1] linode inventory plugin: fix documentation

---

.github/BOTMETA.yml

I don't want to get notifications anymore.
Module etcd3

BOTMETA.yml: Remove vfauth as etcd3 maintainer

---

changelogs/fragments/meta-runtime-deprecations.yml
meta/runtime.yml

Improve meta/runtime.yml deprecation messages.

Improve meta/runtime.yml deprecation messages

---

changelogs/fragments/meta-runtime-deprecations.yml
meta/runtime.yml

Backport of #1918 to stable-2.

[stable-2] Improve meta/runtime.yml deprecation messages

---

changelogs/fragments/1596-xfs_quota-feedback_on_projects_not_initialized_has_changed.yml
plugins/modules/system/xfs_quota.py
tests/integration/targets/xfs_quota/tasks/pquota.yml

The feedback for initializing project quota with xfs_quota has changed since the version it was written for.
xfs_quota
```paste below
```

bugfix: xfs_quota feedback on projects not initialized has changed

---

plugins/modules/jenkins_build.py
plugins/modules/web_infrastructure/jenkins_build.py
tests/unit/plugins/modules/web_infrastructure/test_jenkins_build.py

A module for queuing and deleting jenkins builds.
Designed to have a similar interface as jenkins_job
jenkins_build

Jenkins build module

---

.github/ISSUE_TEMPLATE/bug_report.yml

* Bring inline with ansible/ansible's issue template.
* Add more placeholders

bug_report issue form

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Add other GH Issue forms

---

changelogs/fragments/1972-ini_file-empty-str-value.yml
plugins/modules/files/ini_file.py
tests/integration/targets/ini_file/tasks/main.yml

Added integration test and fixed bug pointed by @manueljacob in #1533
plugins/modules/files/ini_file.py

ini_file - allows adding empty string as a value

---

changelogs/fragments/community.docker-88-docker_container-healthcheck.yml
plugins/modules/cloud/docker/docker_container.py
tests/integration/targets/docker_container/tasks/tests/options.yml

Backport of https://github.com/ansible-collections/community.docker/pull/88 to stable-1.

[stable-1] docker_container: fix healthcheck idempotency issue with strict comparison

---

changelogs/fragments/community.docker-103-docker_swarm-no_log.yml
plugins/modules/cloud/docker/docker_swarm.py

Backport of https://github.com/ansible-collections/community.docker/pull/103 to stable-1.
docker_swarm

[stable-1] docker_swarm: mark join_token as no_log

---

plugins/module_utils/identity/keycloak/keycloak.py
plugins/modules/cloud/linode/linode_v4.py
plugins/modules/cloud/misc/proxmox_kvm.py
plugins/modules/cloud/oneandone/oneandone_server.py
plugins/modules/cloud/profitbricks/profitbricks.py
plugins/modules/cloud/profitbricks/profitbricks_volume.py
plugins/modules/cloud/softlayer/sl_vm.py
plugins/modules/database/aerospike/aerospike_migrations.py
plugins/modules/monitoring/datadog/datadog_event.py
plugins/modules/monitoring/pagerduty_alert.py
plugins/modules/remote_management/manageiq/manageiq_provider.py
plugins/modules/source_control/gitlab/gitlab_user.py

Flagged by ansible/ansible#73882.
keycloak
linode_v4
proxmox_kvm
oneandone_server
profitbricks
profitbricks_volume
sl_vm
aerospike_migrations
datadog_event
pagerduty_alert
gitlab_user

no_log: more false-positives (not flagged by sanity tests yet)

---

.github/BOTMETA.yml

Just adding myself and another maintainer at Linode so that we're kept in the loop of issues.

update linode team

---

changelogs/fragments/2027-add-redfish-session-create-delete-authenticate.yml
plugins/module_utils/redfish_utils.py
plugins/modules/remote_management/redfish/idrac_redfish_command.py
plugins/modules/remote_management/redfish/idrac_redfish_config.py
plugins/modules/remote_management/redfish/idrac_redfish_info.py
plugins/modules/remote_management/redfish/redfish_command.py
plugins/modules/remote_management/redfish/redfish_config.py
plugins/modules/remote_management/redfish/redfish_info.py

The Redfish modules currently only support basic authentication. But it is common for Redfish users to use session login authentication. This change adds two commands, `CreateSession` and `DeleteSession`, to support session creation and deletion. And it also adds an `auth_token` parameter to pass a security token to other Redfish commands for authentication (as an alternative to username and password).
Fixes #1975 
idrac_redfish_command.py
idrac_redfish_config.py
idrac_redfish_info.py
Here is an example playbook showing the use of the two new commands (`CreateSession` and `DeleteSession`) and two new parameters (`auth_token` and `session_uri`): 
```paste below
---
- hosts: myhosts
connection: …
```

Add support for Redfish session create, delete, and authenticate

---

.github/BOTMETA.yml

Backport of #2039 to stable-1.

[stable-1] update linode team

---

tests/integration/targets/archive/tasks/broken-link.yml
tests/integration/targets/archive/tasks/main.yml

Trying to demonstrate #2035 but it seems to be working.
archive

archive - created an integration test that archives broken links

---

plugins/doc_fragments/pritunl.py
plugins/module_utils/net_tools/pritunl/api.py
plugins/modules/net_tools/pritunl/pritunl_user.py
plugins/modules/net_tools/pritunl/pritunl_user_info.py
plugins/modules/pritunl_user.py
plugins/modules/pritunl_user_info.py
tests/unit/plugins/module_utils/net_tools/pritunl/test_api.py
tests/unit/plugins/modules/net_tools/pritunl/test_pritunl_user.py
tests/unit/plugins/modules/net_tools/pritunl/test_pritunl_user_info.py

pritunl_user.py
```
ansible 2.4.0 (devel 44fac2eb5a) last updated 2017/05/04 00:58:43 (GMT -700)
```
[Pritunl](https://pritunl.com/) is an Enterprise Distributed OpenVPN Server. We have been using this technology for about a year and we felt really handy to automate our VPN user management using Ansible.
As Pritunl offers a [REST API](https://pritunl.com/api), we developed two modules to manage VPN users.
Both modules have been sitting on my laptop for about a year. They have been well tested and they work as expected (respect of idempotency, based on urllib, etc...)
This PR was originally tracked here https://github.com/ansible/ansible/pull/26584
Florian

New module: Add Pritunl VPN user module (net_tools/pritunl/)

---

tests/integration/targets/archive/tasks/broken-link.yml
tests/integration/targets/archive/tasks/main.yml

* created an integration test that archives broken links
* sanity fix
(cherry picked from commit f5a9584ae64e6c1d3f6b9edb03214ca75ab63f61)
archive

[PR #2063/f5a9584a backport][stable-1] archive - created an integration test that archives broken links (#2063)

---

changelogs/fragments/2065-snmp-facts-timeout.yml
plugins/modules/net_tools/snmp_facts.py

Add `timeout` and `retries` parameters to module.
Fixes #980 
snmp_facts

snmp_facts - added timeout and retries params to module

---

plugins/modules/files/archive.py

Fixed docs.
Fixes #829
archive

archive - fixed documentation

---

changelogs/fragments/2087-restrict-kubernetes-dependency.yml
galaxy.yml
tests/utils/shippable/shippable.sh

Backport of #2082 to stable-1.
CI

[stable-1] Install collections in CI directly with git

---

plugins/modules/packaging/os/pulp_repo.py

The module operates with Pulp 2 only, which is sunsetting soon. Add a note to inform users before they become frustrated.
pulp_repo

Add a Pulp 2 related note to pulp_repo

---

plugins/modules/identity/ipa/ipa_service.py

ipa_service
```paste below
```

ipa_service - Correct pluralisation of "hosts" in example

---

.github/BOTMETA.yml

I am retiring, so removing myself as a maintainer for the Redfish modules (team_redfish).
- Other

Remove billdodd from team_redfish

---

changelogs/fragments/2125-git-config-scope-file.yml
plugins/modules/source_control/git_config.py
tests/integration/targets/git_config/aliases
tests/integration/targets/git_config/tasks/get_set_state_present_file.yml
tests/integration/targets/git_config/tasks/main.yml
tests/integration/targets/git_config/tasks/setup_no_value.yml
tests/integration/targets/git_config/tasks/setup_value.yml

- scope file was not working
- added test to guarantee that behaviour
- marked integration test as destructive, because it overwrites ~/.gitconfig
Fixes #2117 
git_config

git_config - fixed bug with scope file

---

changelogs/fragments/2091-add-loganalytics-callback-plugin.yml
plugins/callback/loganalytics.py
tests/unit/plugins/callback/test_loganalytics.py

Adding callback plugin support for Azure Log Analytics 
Functional test has been done with a test Azure Log Analytics workspace.

Callback plugin: Azure Log Analytics

---

changelogs/fragments/2142-apache2_mod_proxy-cleanup.yml
plugins/modules/web_infrastructure/apache2_mod_proxy.py

- moved imports from the bottom of the code to the top (ansible-style).
- pythonified/simplified `get_member_status()`/`set_member_status()`
- reduced clutter in `Balancer.__init__()`

apache2_mod_proxy - minor improvements/fixes

---

commit-rights.md

CC @Andersson007 @gundalow
commit-rights.md

[WIP] Committer guidelines

---

changelogs/fragments/2160-list-literals.yml
plugins/lookup/hiera.py
plugins/module_utils/known_hosts.py
plugins/modules/cloud/smartos/nictagadm.py
plugins/modules/cloud/smartos/smartos_image_info.py
plugins/modules/files/xattr.py
plugins/modules/net_tools/ipwcli_dns.py
plugins/modules/packaging/os/svr4pkg.py
plugins/modules/storage/zfs/zfs_facts.py
plugins/modules/storage/zfs/zpool_facts.py
plugins/modules/system/beadm.py

Clearing up some PyCharm inspection code results
plugins/lookup/hiera.py
plugins/module_utils/known_hosts.py
plugins/modules/cloud/smartos/nictagadm.py
plugins/modules/cloud/smartos/smartos_image_info.py
plugins/modules/files/xattr.py
plugins/modules/net_tools/ipwcli_dns.py
plugins/modules/packaging/os/svr4pkg.py
plugins/modules/storage/zfs/zfs_facts.py
plugins/modules/storage/zfs/zpool_facts.py
plugins/modules/system/beadm.py

rewritten as list literals

---

changelogs/fragments/2157-unreachable-code.yml
plugins/modules/cloud/misc/rhevm.py
plugins/modules/cloud/ovh/ovh_ip_failover.py
plugins/modules/source_control/bitbucket/bitbucket_pipeline_variable.py

Clearing up some PyCharm inspection code results
plugins/modules/cloud/misc/rhevm.py
plugins/modules/cloud/ovh/ovh_ip_failover.py
plugins/modules/source_control/bitbucket/bitbucket_pipeline_variable.py

removed unreachable code

---

.azure-pipelines/azure-pipelines.yml
README.md
shippable.yml

As discussed at the community meeting.
When stable-2.11 is actually branched:
1. Rebase
CI

[stable-1] Replace devel tests with stable-2.11

---

changelogs/fragments/2188-xfconf-modhelper-variables.yml
plugins/module_utils/module_helper.py
plugins/modules/system/xfconf.py
tests/unit/plugins/module_utils/test_module_helper.py

Applying the improvements from #2162 to `xfconf`, a couple of improvements/exapansions were found for `ModuleHelper`.

Applying ModuleHelper variable mgmt to xfconf -> improvements on MH

---

changelogs/fragments/2203-modhelper-cause-changes-deco.yml
plugins/module_utils/module_helper.py
tests/unit/plugins/module_utils/test_module_helper.py

The decorator `cause_changes` never really worked before. This PR fixes that and add unit tests for it.

module_helper - fixed decorator cause_changes

---

changelogs/fragments/2146-npm-add_no_bin_links_option.yaml
plugins/modules/packaging/language/npm.py
tests/integration/targets/npm/tasks/no_bin_links.yml
tests/integration/targets/npm/tasks/run.yml

npm: Add no_bin_links option

---

.github/BOTMETA.yml

Grant supershipit to new maintainers
BOTMETA.yml

Grant supershipit to new maintainers

---

plugins/modules/monitoring/spectrum_model_attrs.py
plugins/modules/spectrum_model_attrs.py
tests/integration/targets/spectrum_model_attrs/aliases
tests/integration/targets/spectrum_model_attrs/tasks/main.yml

New module submission
spectrum_model_attrs: Enforce a model's attributes in CA Spectrum.
spectrum_model_attrs: Enforce a model's attributes in CA Spectrum.
```paste below
EXAMPLES:
- name: Enforce maintenance mode for modelxzy01 with a note about why
spectrum_model_attrs:
url: "http://oneclick.url.com"
username: "{{ oneclick_username }}"
password: "{{ oneclick_password }}"
name: "modelxyz01"
type: "Host_Device"
validate_certs: no
attributes:
- name: "isManaged"
value: "false"
- name: "Notes"
value: "MM set on {{ ansible_date_time.iso8601 }} via CO {{ CO }} by {{ tower_user_name | default(ansible_user_id) }}"
register: spectrum_model_attrs_status
RETURN VALUES:
spectrum_model_attrs_status:
description: Information about changed model …
```

spectrum_model_attrs: Initial commit

---

changelogs/fragments/2236-jira-isinstance.yml
plugins/modules/web_infrastructure/jira.py

A code error passed through review, fixing.
Fixes #2234 
jira

jira - fixed isinstance error

---

plugins/modules/clustering/nomad/nomad_job_info.py

Use nomad_job_info in nomad_job_info examples

---

.github/BOTMETA.yml
changelogs/fragments/2218-cpanm-revamp.yml
plugins/modules/packaging/language/cpanm.py
tests/integration/targets/cpanm/aliases
tests/integration/targets/cpanm/meta/main.yml
tests/integration/targets/cpanm/tasks/main.yml
tests/unit/plugins/modules/packaging/language/test_cpanm.py

This PR uses code written in #1976 but expands on that. That PR lagged too far behind `main`, up to the point where it was too time-consuming to rebase, so we closed that one and brought the changes over to here.
In the wake of #208 the module `cpanm` was rewritten with a number of improvements. 
plugins/modules/packaging/language/cpanm.py

cpanm - revamp module

---

changelogs/fragments/2220_nmcli_wifi_support.yaml
plugins/modules/net_tools/nmcli.py

Ability to connect to a Wifi network and also to attach the connection
to a master (bond).

nmcli: add wifi support

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/2232
BOTMETA.yml

filesize: add maintainer

---

changelogs/fragments/2268-validation-univetion.yml
plugins/modules/cloud/univention/udm_dns_record.py
plugins/modules/cloud/univention/udm_dns_zone.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt

Fixed validation errors (and removed lines in `ignore` files.
plugins/modules/cloud/univention/udm_dns_record.py
plugins/modules/cloud/univention/udm_dns_zone.py

Fixed validations in a couple of modules

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/1802
BOTMETA.yml

BOTMETA.yml: monitoring/spectrum_model_attrs - add a maintainer

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/2037
BOTMETA.yml

BOTMETA.yml: filter/from_csv - add a maintainer

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/2091
BOTMETA.yml

BOTMETA: callback/loganalytics - add a maintainer

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/2244
BOTMETA.yml

BOTMETA: hashids plugin - add a maintainer

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/1829#issuecomment-822515614
- 
BOTMETA.yml

BOTMETA.yml: update team_gitlab

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/2008#issuecomment-822587280
BOTMETA.yml

BOTMETA.yml: java_cert - add a new maintainer

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/2180#issuecomment-823036209
BOTMETA.yml

BOTMETA.yml: inventory/proxmox - add a new maintainer

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/2046#issuecomment-823039268
BOTMETA.yml

BOTMETA.yml: expand team_opennebula

---

.github/BOTMETA.yml

Backport of #2287 to stable-1.
BOTMETA.yml

[stable-1] BOTMETA.yml: update team_gitlab

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/2159#issuecomment-822665853
BOTMETA.yml

BOTMETA.yml: update team_ipa

---

.github/BOTMETA.yml

Backport of #2286 and #2304 to stable-1.
BOTMETA

[stable-1] Backport of #2286 and #2304

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/2204#issuecomment-822437997
BOTMETA.yml

BOTMETA.yml: github/github_repo - add a new maintainer

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/1813#issuecomment-823562264
BOTMETA.yml

BOTMETA.yml: lxd/lxd_profile - add a new maintainer

---

plugins/modules/cloud/misc/proxmox_domain_info.py
plugins/modules/cloud/misc/proxmox_group_info.py
plugins/modules/cloud/misc/proxmox_storage_info.py
plugins/modules/cloud/misc/proxmox_user_info.py

Follow-up to #2304: rename in module `author` field and copyright notice.
@tleguern please approve this PR :)
proxmox modules

Rename Aversiste → tleguern

---

plugins/modules/cloud/misc/proxmox_domain_info.py
plugins/modules/cloud/misc/proxmox_group_info.py
plugins/modules/cloud/misc/proxmox_user_info.py

Backport of #2307 to stable-1.
proxmox modules

[stable-1] Rename Aversiste → tleguern

---

tests/integration/targets/sysrc/aliases

See for example https://dev.azure.com/ansible/community.general/_build/results?buildId=12648&view=logs&j=77331c5d-0295-5098-50bd-b050750c4e8c&t=7a18633f-2adf-5bfc-63e3-8f0af4e852fd, https://dev.azure.com/ansible/community.general/_build/results?buildId=12621&view=logs&j=5572c5d1-9090-52f1-863d-f0685fa60071&t=680d3d61-3dc6-51e0-b802-1640af78eb07&l=3069, https://dev.azure.com/ansible/community.general/_build/results?buildId=12634&view=logs&j=5572c5d1-9090-52f1-863d-f0685fa60071&t=680d3d61-3dc6-51e0-b802-1640af78eb07
CI

Temporarily disable sysrc tests since they fail often.

---

changelogs/fragments/2282-nmap-fix-cache-support.yml
plugins/inventory/nmap.py

Fixes #2242
Also updated the verify_file function, should I do some kind of changelog to indicate this? Now requires .nmap.yml or whatever extensions the user has configured
Code feedback deeply appreciated. 
nmap
time ansible-inventory -i inventory.nmap.yml --graph shows second run as 200 ms while first run is ~20 seconds
inventory file used while testing
```yaml
plugin: community.general.nmap
address: 192.168.0.0/24
cache: yes
cache_plugin: community.general.yaml
```

nmap: fix cache support

---

.azure-pipelines/azure-pipelines.yml

See https://github.com/ansible-collections/overview/issues/45#issuecomment-824337164.
AZP

Replace FreeBSD 11.4 with 13.0 for devel testing

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/1993#issuecomment-824811905
BOTMETA.yml

BOTMETA.yml: haproxy - add a maintainer

---

.github/BOTMETA.yml

Backport of #2331 to stable-1.
BOTMETA.yml

[stable-1] BOTMETA.yml: haproxy - add a maintainer

---

.github/BOTMETA.yml

Given that it has been years since I used Consul regularly, and that I no longer have easy access to a Consul cluster, I am resign as a maintainer.
consul

Removes colin-nolan as Consul maintainer

---

changelogs/fragments/2349-jira-bugfix-b64decode.yml
plugins/modules/web_infrastructure/jira.py

Fixed bug when reading base64-enconded contents
jira

jira - fixed base64 decode bug

---

changelogs/fragments/2208-jira-revamp.yml
plugins/modules/web_infrastructure/jira.py
tests/integration/targets/jira/tasks/main.yml

Major revamp in the module, keeping the same behaviour. Code should be simpler to maintain in the future.
(Following up on https://github.com/ansible-collections/community.general/pull/1978#issuecomment-813924732)
Wait for #2192 to merge - after that this PR will require a rebase.
jira

jira - module revamp -> moved code to class

---

.github/BOTMETA.yml

BOTMETA.yml: team_suse - add a maintainer
https://github.com/ansible-collections/community.general/pull/2094#issuecomment-826287071
BOTMETA.yml

BOTMETA.yml: team_suse - add a maintainer

---

changelogs/fragments/2355-spotinst_aws_elastigroup-list-elements.yml
plugins/modules/cloud/spotinst/spotinst_aws_elastigroup.py

Added `elements` to a number of parameters of type `list`.
plugins/modules/cloud/spotinst/spotinst_aws_elastigroup.py

spotinst_aws_elastigroup - fixed elements for many lists

---

tests/sanity/ignore-2.12.txt

Fix CI for ansible/ansible#74408.
CI

Adjust to devel's ansible-test

---

changelogs/fragments/ovirt-fixup.yml
plugins/modules/cloud/misc/ovirt.py
plugins/modules/cloud/ovirt/ovirt_affinity_label_facts.py
plugins/modules/cloud/ovirt/ovirt_api_facts.py
plugins/modules/cloud/ovirt/ovirt_cluster_facts.py
plugins/modules/cloud/ovirt/ovirt_datacenter_facts.py
plugins/modules/cloud/ovirt/ovirt_disk_facts.py
plugins/modules/cloud/ovirt/ovirt_event_facts.py
plugins/modules/cloud/ovirt/ovirt_external_provider_facts.py
plugins/modules/cloud/ovirt/ovirt_group_facts.py
plugins/modules/cloud/ovirt/ovirt_host_facts.py
plugins/modules/cloud/ovirt/ovirt_host_storage_facts.py
plugins/modules/cloud/ovirt/ovirt_network_facts.py
plugins/modules/cloud/ovirt/ovirt_nic_facts.py
plugins/modules/cloud/ovirt/ovirt_permission_facts.py
plugins/modules/cloud/ovirt/ovirt_quota_facts.py
plugins/modules/cloud/ovirt/ovirt_snapshot_facts.py
plugins/modules/cloud/ovirt/ovirt_storage_domain_facts.py
plugins/modules/cloud/ovirt/ovirt_storage_template_facts.py
plugins/modules/cloud/ovirt/ovirt_storage_vm_facts.py
plugins/modules/cloud/ovirt/ovirt_tag_facts.py
plugins/modules/cloud/ovirt/ovirt_template_facts.py
plugins/modules/cloud/ovirt/ovirt_user_facts.py
plugins/modules/cloud/ovirt/ovirt_vm_facts.py
plugins/modules/cloud/ovirt/ovirt_vmpool_facts.py

Fixes errors reported in #2379.
ovirt*

ovirt modules: remove programming error which prevents modules to work with devel

---

.azure-pipelines/azure-pipelines.yml
tests/integration/targets/setup_postgresql_db/tasks/main.yml

See https://github.com/ansible-collections/overview/issues/45#issuecomment-830220740
CI

Add Fedora 34 to CI

---

.github/BOTMETA.yml

Re-create of #2389.
@resmo please approve this PR.
BOTMETA

Remove resmo as composer maintainer

---

.github/BOTMETA.yml

https://github.com/ansible-collections/community.general/pull/2246#issuecomment-822713047
BOTMETA.yml

BOTMETA.yml: terraform - add a new maintainer

---

changelogs/fragments/2373-svr4pkg-fix-typeerror.yml
plugins/modules/packaging/os/svr4pkg.py

Fixes  #2373
svr4pkg
```paste below
```

Fix #2373 - TypeError: a bytes-like object is required, not 'str'

---

plugins/become/sudosu.py
plugins/callback/loganalytics.py
plugins/inventory/lxd.py

Fix issues pointed out by ansible/ansible#71734
plugins/become/sudosu.py
plugins/inventory/lxd.py

Make plugins pass validation

---

plugins/become/sudosu.py
plugins/callback/loganalytics.py

Backport of #2414 to stable-2.
plugins/become/sudosu.py

[stable-2] Make plugins pass validation

---

changelogs/fragments/2435-one_vm-fix_missing_keys.yml
plugins/modules/cloud/opennebula/one_vm.py

Fixes: #685
one_vm.py
```
ansible_collections/community/general/plugins/modules/one_vm.py", line 727, in get_vm_info
KeyError: 'IP'
---
"msg": "result"
}
```

OpenNebula one_vm.py: Fix missing keys

---

.github/BOTMETA.yml

For recently added plugins/modules.
BOTMETA

Add more plugin authors to BOTMETA

---

changelogs/fragments/2448-stackpath_compute-fix.yml
plugins/inventory/stackpath_compute.py

get the lenght for the client_id / client_secret to validate inventory configuration
Stackpath_compute dynamic inventory

fix stackpath_compute validate_config

---

.azure-pipelines/azure-pipelines.yml

See https://github.com/ansible-collections/overview/issues/45#issuecomment-836847770
CI

Run unit tests also with Python 3.10

---

changelogs/fragments/2355-spotinst_aws_elastigroup-list-elements.yml
plugins/modules/cloud/spotinst/spotinst_aws_elastigroup.py

This PR reverts all feature commits that were reverted for 3.0.x releases before 3.1.0.
various

[stable-3] Revert reverted changes for 3.1.0

---

changelogs/fragments/2410-linode-improvements.yml
plugins/modules/cloud/linode/linode.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt

This PR fixes a couple of documentation (and its related validation lines in `ignore` files), plus some minor refactorings.
plugins/modules/cloud/linode/linode.py

linode - docs/validation changes + minor refactorings

---

plugins/lookup/random_pet.py
tests/integration/targets/lookup_random_pet/aliases
tests/integration/targets/lookup_random_pet/dependencies.yml
tests/integration/targets/lookup_random_pet/runme.sh
tests/integration/targets/lookup_random_pet/test.yml

A lookup plugin to generate random pet names based
upon criteria.
plugins/lookup/random_pet.py
tests/integration/targets/lookup_random_pet/aliases
tests/integration/targets/lookup_random_pet/dependencies.yml
tests/integration/targets/lookup_random_pet/runme.sh
tests/integration/targets/lookup_random_pet/test.yml

random_pet: Random pet name generator

---

changelogs/fragments/2520-connection-refactors.yml
plugins/connection/chroot.py
plugins/connection/funcd.py
plugins/connection/iocage.py
plugins/connection/jail.py
plugins/connection/lxc.py
plugins/connection/qubes.py
plugins/connection/saltstack.py
plugins/connection/zone.py

Make pycharm inspection happier
plugins/connection/funcd.py
plugins/connection/iocage.py
plugins/connection/jail.py
plugins/connection/qubes.py
plugins/connection/saltstack.py
plugins/connection/zone.py

Cleanup connections plugins

---

changelogs/fragments/2411-snap-revamp-enabled-disabled-states.yml
plugins/modules/packaging/os/snap.py

Adding the states `enabled` and `disabled`, and while at it, did a major revamp of the module.
Fixes #1990 

snap - revamp + implementing enabled/disabled states

---

plugins/inventory/stackpath_compute.py

plugins/inventory/stackpath_compute.py

Add missing author name

---

changelogs/fragments/2461-ovirt4-fix-configparser.yml
scripts/inventory/ovirt4.py

close #674 
scripts/inventory/ovir4.py
```paste below
```

ovir4 inventory script

---

changelogs/fragments/2578-ini-file-utf8-bom.yml
plugins/modules/files/ini_file.py
tests/integration/targets/ini_file/tasks/main.yml

Opening file using encoding as utf-8-sig.
Fixes #2189 
ini_file

ini_file - opening file as utf-8-sig

---

plugins/modules/files/ini_file.py

Adding docs as an aftermath of #2578 .
ini_file

ini_file - added note in documentation for utf-8 bom

---

tests/unit/plugins/become/test_sudosu.py

Use become test framework for sudosu tests

---

plugins/modules/system/iptables_state.py

This PR fixes a regression introduced by #2525, and that affects hosts using `iptables-nft` alternative (vs. `iptables-legacy`) for versions > 1.8.2
This comes back to the use of ``iptables-restore`` to restore an empty table (that loads relevant kernel modules for good), but as the last resort.
iptables_state
This fix solves the issue on my debian 11 hosts, on which I've detected it.

iptables_state: fix a regression in initialization_from_null_state()

---

.github/BOTMETA.yml

Relates to https://github.com/ansible-collections/community.general/pull/2623

hana_query module: add a maintainer

---

changelogs/fragments/2632-cleanup.yml
meta/runtime.yml

Removes superfluous `__init__.py` files. Sorts meta/runtime.yml entries and writes the file with PyYAML (https://github.com/ansible-collections/community.internal_test_tools/blob/main/tools/meta_runtime.py).

meta/runtime.yml and __init__.py cleanup

---

plugins/modules/files/xml.py

Element node can be deleted based upon the attribute
value.
changelogs/fragments/xml_example.yml
plugins/modules/files/xml.py

xml: Add an example for absent

---

plugins/lookup/random_string.py
tests/integration/targets/lookup_random_string/aliases
tests/integration/targets/lookup_random_string/runme.sh
tests/integration/targets/lookup_random_string/test.yml

New lookup plugin to generate random string based upon
constraints.
plugins/lookup/random_string.py
tests/integration/targets/lookup_random_string/aliases
tests/integration/targets/lookup_random_string/runme.sh
tests/integration/targets/lookup_random_string/test.yml

random_string: a new lookup plugin

---

tests/sanity/extra/extra-docs.json
tests/sanity/extra/extra-docs.py

Uses antsibull-lint to lint extra collection docs (if present).
CI

Add extra docs tests

---

README.md

Stop mentioning Freenode. We're on Libera.chat.

---

changelogs/fragments/2650-composer-add_composer_executable.yml
plugins/modules/packaging/language/composer.py

composer: add composer_executable

---

changelogs/fragments/2671-fix-broken-query-of-async_status-result.yml
plugins/action/system/iptables_state.py
tests/integration/targets/iptables_state/aliases

iptables_state: fix broken query of `async_status` result

---

plugins/modules/cloud/online/online_server_info.py
plugins/modules/cloud/online/online_user_info.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt

Fixed documentation
plugins/modules/cloud/online/online_server_info.py
plugins/modules/cloud/online/online_user_info.py

Fixed sanity checks for cloud/online/ modules

---

docs/docsite/extra-docs.yml
docs/docsite/rst/filter_guide.rst

This adds documentation of the collection's filters. For json_query, I copied the documenation from https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/playbooks_filters.rst#selecting-json-data-json-queries.
I uploaded a docsite build to https://ansible.fontein.de/collections/community/general/ where you can see the results (https://ansible.fontein.de/collections/community/general/docsite/filter_guide.html).
docsite

Add filter docs

---

tests/integration/targets/lookup_random_string/test.yml

Unfortunately AZP is really bad at reporting unstable tests. It basically only says that something fails, but not where so I can't find the log without clicking through all possible logs... This should definitely improve the situation though.
random_string

Fix spurious test errors

---

.github/BOTMETA.yml

Add new module/plugin maintainers to BOTMETA (#778, #2572).
BOTMETA

Add new module/plugin maintainers to BOTMETA

---

.github/BOTMETA.yml

Fix action plugin BOTMETA entries.
BOTMETA

Fix action plugin BOTMETA entries

---

changelogs/fragments/script-removal.yml

Announce removal of inventory and vault scripts from this repository.
changelog

[stable-3] Announce script removal

---

plugins/modules/system/parted.py

Fix repeated word in description of fs_type

---

changelogs/fragments/2684-open_iscsi-single-target-multiple-portal-overrides.yml
plugins/modules/system/open_iscsi.py

Fixes #2683 and #2685
open_iscsi

open_iscsi: allow same target selected portals login and override

---

changelogs/fragments/2711-fix-iptables_state-2700-async_status-call.yml
plugins/action/system/iptables_state.py

Call action plugin rather than its module
Fixes #2700
iptables_state

iptables_state: fix async status call (-> action plugin)

---

changelogs/fragments/2681-stacki-host-bugfix.yml
plugins/modules/remote_management/stacki/stacki_host.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt

Started as fixing the documentation for sanity checks, but ended up with a small bugfix (and minor refactors).
plugins/modules/remote_management/stacki/stacki_host.py

Bugfix + sanity checks for stacki_host

---

changelogs/fragments/2731-mh-cmd-locale.yml
plugins/module_utils/mh/mixins/cmd.py
tests/unit/plugins/modules/packaging/language/test_cpanm.py
tests/unit/plugins/modules/system/test_xfconf.py

Also setting the variable `LC_ALL` when forcing locale
Fixes #2715 

ModuleHelper - also uses LC_ALL to force language

---

commit-rights.md

Add myself to commit-rights.md

---

plugins/modules/cloud/scaleway/scaleway_image_info.py
plugins/modules/cloud/scaleway/scaleway_ip_info.py
plugins/modules/cloud/scaleway/scaleway_security_group_info.py
plugins/modules/cloud/scaleway/scaleway_server_info.py
plugins/modules/cloud/scaleway/scaleway_snapshot_info.py
plugins/modules/cloud/scaleway/scaleway_volume_info.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt

Fixed documentation for all but one module.
plugins/modules/cloud/scaleway/scaleway_image_info.py
plugins/modules/cloud/scaleway/scaleway_ip_info.py
plugins/modules/cloud/scaleway/scaleway_security_group_info.py
plugins/modules/cloud/scaleway/scaleway_server_info.py
plugins/modules/cloud/scaleway/scaleway_snapshot_info.py
plugins/modules/cloud/scaleway/scaleway_volume_info.py

Fixed sanity checks for cloud/scaleway/ modules

---

.github/BOTMETA.yml
commit-rights.md

Some folks believe I can do it. :P

Adding myself to commit-rights.md / removing supershipit in BOTMETA

---

changelogs/fragments/2731-mh-cmd-locale.yml
plugins/module_utils/module_helper.py
tests/unit/plugins/modules/system/test_xfconf.py

Backport of #2731 to stable-2.
@russoz I had to do this manually, please review :)

[stable-2] ModuleHelper - also uses LC_ALL to force language

---

changelogs/fragments/2735-onepassword-add_domain_option.yml
plugins/lookup/onepassword.py

Fixes #2734.
plugins/lookup/onepassword.py

Add domain option to onepassword lookup

---

tests/integration/targets/yum_versionlock/tasks/main.yml

See https://github.com/ansible-collections/community.general/issues/2539
CI
This is not ready yet, please merge this after CI passes.

yum_versionlock: enable fedora34 integration test

---

plugins/inventory/scaleway.py

* Updated example section for ``variables``
* Added link about token generation
* Misc changes in doc
Fixes: #467

scaleway: Misc doc changes

---

plugins/modules/source_control/gitlab/gitlab_runner.py

Documentation description fix for `access_level` parameter of `gitlab_runner`
Fixes: https://github.com/ansible-collections/community.general/issues/2768
gitlab_runner.py

Documentation fix for access_level parameter of gitlab_runner

---

.github/BOTMETA.yml

BOTMETA.yml: supershipit to quidame
BOTMETA.yml

BOTMETA.yml: supershipit to quidame

---

.github/BOTMETA.yml

BOTMETA.yml: grant supershipit
also "triage" was granted to Ajpantuso in c.g. and c.crypto.

BOTMETA.yml: grant supershipit

---

CONTRIBUTING.md

It has happened multiple times which users have been asked how to test the PR branch locally, I think this would help them.
Although I'm not sure about where should this be.
CONTRIBUTING.md

Add Test PRs locally section to CONTRIBUTING.md

---

changelogs/fragments/2845-serverless-deprecate-functions-param.yml
plugins/modules/cloud/misc/serverless.py

Parameter `functions` is blatantly ignored by the module code. Deprecating to make it honest.
plugins/modules/cloud/misc/serverless.py

serverless - deprecating unused param

---

plugins/modules/cloud/softlayer/sl_vm.py

Doesn't really affect what the example does, so this should be a no-brainer.
sl_vm

Adjust example to remove unnecessary offensive language

---

changelogs/fragments/2878-validate-certs-bool.yml
plugins/callback/nrdp.py

There was no `type:` in the argument spec.
nrdp callback

nrdp callback: improve docs, validate option types

---

changelogs/fragments/2875-ini_file-unicode.yml
plugins/modules/files/ini_file.py
tests/integration/targets/ini_file/tasks/main.yml

Fixes the regression reported by @jbronn in #2578.
The first commit basically adds a test that fails. Let's see whether CI actually fails with it, so we can try to understand why we didn't notice this earlier.
ini_file

ini_file: fix regression reported in #2578

---

changelogs/fragments/2824-gitlab_project-project-under-user.yml
plugins/modules/source_control/gitlab/gitlab_project.py

We wanted to create gitlab projects per user, for a use case we have. However, it is only possible to create projects under a group or under the owner of the gitlab api token.
This pull request adds the functionality to create a project under different users using their `username`.
gitlab_project
```paste below
TASK [Create project] ****************************************************************************************************************
changed: [localhost] => {"changed": true, "msg": "Successfully created or updated the project my_first_project2", "project": {"_links": {"events": "https://git.dome.dev/api/v4/projects/544/events", "labels": "https://git.dome.dev/api/v4/projects/544/labels", "members": "https://git.dome.dev/api/v4/projects/544/members", …
```

gitlab_project - Add ability to create project under a user

---

changelogs/fragments/2787-yum_versionlock-fix_idempotency_when_using_wildcard.yml
plugins/modules/packaging/os/yum_versionlock.py
tests/integration/targets/yum_versionlock/tasks/main.yml

Fixes https://github.com/ansible-collections/community.general/issues/2761
This only adds some failing tests for now.

yum_versionlock: fix idempotency when using wildcard (asterisk)

---

changelogs/fragments/2912-snap-module-helper.yml
plugins/module_utils/mh/base.py
plugins/modules/packaging/os/snap.py
tests/integration/targets/snap/aliases
tests/integration/targets/snap/defaults/main.yml
tests/integration/targets/snap/handlers/main.yml
tests/integration/targets/snap/meta/main.yml
tests/integration/targets/snap/tasks/Debian.yml
tests/integration/targets/snap/tasks/Fedora.yml
tests/integration/targets/snap/tasks/RedHat.yml
tests/integration/targets/snap/tasks/default.yml
tests/integration/targets/snap/tasks/main.yml
tests/integration/targets/snap/tasks/nothing.yml

Try to fix snap.
Fixes #2835, #2906.
snap

Fix snap module, and module helper behavior on rc != 0 in output

---

changelogs/fragments/2918-snap-param-order.yml
plugins/modules/packaging/os/snap.py
tests/integration/targets/snap/tasks/default.yml
tests/integration/targets/snap/tasks/main.yml

Parameter order was wrong.
Fixes #2916 

snap - fixed param order

---

changelogs/fragments/2935-lvol-support_check_mode_thinpool.yml
plugins/modules/system/lvol.py

Fixes #2934 
plugins/modules/system/lvol.py

lvol: honor check_mode on thinpool

---

changelogs/fragments/2936-pacman-fix_changed_status_when_ignorepkg_has_been_defined.yml
plugins/modules/packaging/os/pacman.py

pacman: fix changed status when ignorepkg has been defined

---

tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt

Added some comments to the ignore files

Added comments to the ignore files

---

changelogs/fragments/2960-launchd-validation-check.yaml
plugins/modules/system/launchd.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt

Fixed validation check for launchd
plugins/modules/system/launchd.py

launchd - fixed validation check

---

changelogs/fragments/2955-rax_mon_notification_plan-added-elements-to-list-params.yaml
plugins/modules/cloud/rackspace/rax_mon_notification_plan.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt

Fixed validation check for module
plugins/modules/cloud/rackspace/rax_mon_notification_plan.py

rax_mon_notification_plan - fixed validation check

---

changelogs/fragments/2989-pamd-single-line.yaml
plugins/modules/system/pamd.py
tests/integration/targets/pamd/aliases
tests/integration/targets/pamd/files/single_line
tests/integration/targets/pamd/tasks/main.yml

Added conditional to the code, plus an integration test to verify it.
Fixes: #2925 
plugins/modules/system/pamd.py

pamd - fixed single line issue

---

tests/integration/targets/filter_groupby/aliases
tests/integration/targets/filter_groupby/tasks/main.yml
tests/integration/targets/module_helper/aliases
tests/integration/targets/module_helper/tasks/mdepfail.yml
tests/integration/targets/module_helper/tasks/msimple.yml
tests/integration/targets/module_helper/tasks/mstate.yml

Some tests have an invalid group and thus don't run.
CI

Enable tests

---

tests/integration/targets/mqtt/aliases
tests/sanity/extra/aliases.json
tests/sanity/extra/aliases.py

Extra sanity test to check integration test targets.
CI

Check targets

---

changelogs/fragments/3028-snap-channel.yml
plugins/modules/packaging/os/snap.py

snap: fix channel option

---

plugins/module_utils/identity/keycloak/keycloak.py
plugins/modules/identity/keycloak/keycloak_clientscope.py
plugins/modules/keycloak_clientscope.py
tests/unit/plugins/modules/identity/keycloak/test_keycloak_clientscope.py

This PR add a module to manage keycloak clientscope, like keycloak_client manage clients
Module name is keycloak_clientscope

Keycloak: add clientscope management

---

changelogs/fragments/3044-proxmox-inventory-snapshots.yml
plugins/inventory/proxmox.py
tests/unit/plugins/inventory/test_proxmox.py

Add a list of existing snapshots to the host facts.
proxmox inventory
ansible-inventory --host foreman-400
```paste below
{
"proxmox_boot": "order=scsi0;ide2;net0",
"proxmox_cores": 2,
"proxmox_digest": "ccee3b9a6dd8c14bbd36a3e3b283140960636d23",
"proxmox_ide2": {
"disk_image": "data:iso/CentOS-8.2.2004-x86_64-minimal.iso",
"media": "cdrom"
},
"proxmox_memory": 12288,
"proxmox_name": "foreman-400",
"proxmox_net0": {
"bridge": "vmbr0",
"virtio": "2A:DD:72:8D:31:DD"
},
"proxmox_node": "carrier",
"proxmox_numa": 0,
"proxmox_ostype": "l26",
"proxmox_parent": "clean",
"proxmox_scsi0": {
"disk_image": "main:vm-115-disk-0",
"size": "100G"
},
"proxmox_scsihw": "disk_image=virtio-scsi-pci",
"proxmox_smbios1": "uuid=10f553bd-8144-4a8f-aa31-9d37cb0ec05f",
"proxmox_snapshots": …
```

Proxmox inventory: Added snapshots fact

---

tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt

Adding comment to ignore files wrt to composer module.
composer

composer - missed module when created commments in ignore files

---

plugins/modules/system/xfconf.py

Fixed doc in xfconf as mentioned in #3045 

xfconf - fixed doc

---

changelogs/fragments/3041-fix_gitlab_group_members_gitlab_project_mambers.yml
plugins/modules/source_control/gitlab/gitlab_group_members.py
plugins/modules/source_control/gitlab/gitlab_project_members.py

gitlab_group_members/gitlab_project_members - fix pagination issue

---

plugins/modules/system/xfconf_info.py
plugins/modules/xfconf_info.py
tests/unit/plugins/modules/system/test_xfconf_info.py

New module `xfconf_info`.
plugins/modules/system/xfconf_info.py

xfconf_info - new module 

---

.github/BOTMETA.yml
tests/sanity/extra/botmeta.json
tests/sanity/extra/botmeta.py

Adds BOTMETA extra sanity test.
Currently the part that makes sure there's at least one (active or inactive) maintainer for every file is deactivated. (It will fail right now.)
extra sanity tests

Add BOTMETA extra sanity test

---

changelogs/fragments/3067-taiga-bugfix.yaml
plugins/modules/web_infrastructure/taiga_issue.py

Bugfix + improvements on the module.
plugins/modules/web_infrastructure/taiga_issue.py

taiga_issue - bugfix + pythonification

---

changelogs/fragments/3068-supervisorctl-bugfix.yaml
plugins/modules/web_infrastructure/supervisorctl.py
tests/integration/targets/supervisorctl/tasks/main.yml

Bugfix + improvements in the module.
plugins/modules/web_infrastructure/supervisorctl.py
```paste below
```

supervisorctl - bugfix + using ansible validation + pythonification

---

.github/BOTMETA.yml
plugins/become/doas.py
plugins/become/dzdo.py
plugins/become/ksu.py
plugins/become/machinectl.py
plugins/become/pbrun.py
plugins/become/pfexec.py
plugins/become/pmrun.py
plugins/connection/funcd.py
plugins/lookup/dependent.py
tests/sanity/extra/botmeta.json
tests/sanity/extra/botmeta.py

Follow-up to #3064. Updates BOTMETA to make sure all plugin/module authors are mentioned; improve BOTMETA sanity test; and fixes some  plugin author fields.
BOTMETA
several plugins

Update BOTMETA, fix some plugin authors, improve BOTMETA extra sanity test

---

.github/BOTMETA.yml
CONTRIBUTING.md
tests/sanity/extra/botmeta.py

This is a follow-up to #3069: fixes some details I forgot, adds documentation on how to add new plugins/modules which mentions BOTMETA, and enables sanity test which enforces this.
BOTMETA

BOTMETA: enforce entries for new plugins/modules, add documentation for creating new plugins/modules

---

changelogs/fragments/3084-info-checkmode.yaml
plugins/module_utils/oneview.py
plugins/modules/cloud/alicloud/ali_instance_info.py
plugins/modules/cloud/memset/memset_memstore_info.py
plugins/modules/cloud/memset/memset_server_info.py
plugins/modules/cloud/misc/xenserver_facts.py
plugins/modules/cloud/rackspace/rax_facts.py
plugins/modules/cloud/smartos/smartos_image_info.py
plugins/modules/database/vertica/vertica_info.py
plugins/modules/net_tools/snmp_facts.py
plugins/modules/remote_management/oneview/oneview_datacenter_info.py
plugins/modules/remote_management/oneview/oneview_enclosure_info.py
plugins/modules/remote_management/oneview/oneview_ethernet_network_info.py
plugins/modules/remote_management/oneview/oneview_fc_network_info.py
plugins/modules/remote_management/oneview/oneview_fcoe_network_info.py
plugins/modules/remote_management/oneview/oneview_logical_interconnect_group_info.py
plugins/modules/remote_management/oneview/oneview_network_set_info.py
plugins/modules/remote_management/oneview/oneview_san_manager_info.py
plugins/modules/remote_management/redfish/idrac_redfish_info.py
plugins/modules/remote_management/redfish/redfish_info.py
plugins/modules/system/xfconf_info.py
plugins/modules/web_infrastructure/sophos_utm/utm_aaa_group_info.py
plugins/modules/web_infrastructure/sophos_utm/utm_ca_host_key_cert_info.py
plugins/modules/web_infrastructure/sophos_utm/utm_network_interface_address_info.py
plugins/modules/web_infrastructure/sophos_utm/utm_proxy_frontend_info.py
plugins/modules/web_infrastructure/sophos_utm/utm_proxy_location_info.py

Added `supports_check_mode=True` to `*_info` and `*_facts` modules.
plugins/modules/cloud/alicloud/ali_instance_info.py
plugins/modules/cloud/memset/memset_memstore_info.py
plugins/modules/cloud/memset/memset_server_info.py
plugins/modules/cloud/rackspace/rax_facts.py
plugins/modules/cloud/smartos/smartos_image_info.py
plugins/modules/net_tools/snmp_facts.py
plugins/modules/remote_management/redfish/idrac_redfish_info.py
plugins/modules/remote_management/redfish/redfish_info.py
plugins/modules/system/xfconf_info.py
plugins/modules/web_infrastructure/sophos_utm/utm_aaa_group_info.py
plugins/modules/web_infrastructure/sophos_utm/utm_ca_host_key_cert_info.py
plugins/modules/web_infrastructure/sophos_utm/utm_network_interface_address_info.py

added supports_check_mode=True to info/facts modules

---

tests/sanity/extra/botmeta.py

While finishing the BOTMETA sanity test I got side-tracked and screwed up by making it actually not reporting new modules/plugins which aren't covered.

Actually enable BOTMETA sanity test to force new plugins/modules to have BOTMETA entry

---

changelogs/fragments/3093-ejabberd_user-refactor.yaml
plugins/modules/web_infrastructure/ejabberd_user.py

* Replaced in-code check with `required_if`
* Using `get_bin_path()` for the command
* Passing args to `run_command()` as list instead of string.
plugins/modules/web_infrastructure/ejabberd_user.py

ejabberd_user - refactoring and simplification

---

changelogs/fragments/3092-gunicorn-refactor.yaml
plugins/modules/web_infrastructure/gunicorn.py

Removed some extraneous code, plus added 
plugins/modules/web_infrastructure/gunicorn.py

gunicorn - minor refactoring

---

changelogs/fragments/3104-deploy_helper-required_if.yaml
plugins/modules/web_infrastructure/deploy_helper.py

Changed in-code parameter check with required_if
plugins/modules/web_infrastructure/deploy_helper.py

deploy_helper - changed in-code condition to required_if

---

.github/BOTMETA.yml
plugins/modules/ansible_galaxy_install.py
plugins/modules/packaging/language/ansible_galaxy_install.py
tests/integration/targets/ansible_galaxy_install/aliases
tests/integration/targets/ansible_galaxy_install/files/test.yml
tests/integration/targets/ansible_galaxy_install/tasks/main.yml
tests/integration/targets/ansible_galaxy_install/vars/main.yml

New module to interact with `ansible-galaxy`, allowing the installation of collections and/or roles.
Fixes #371 

ansible_galaxy_install - new module

---

changelogs/fragments/3106-apache2_module-review.yaml
plugins/modules/web_infrastructure/apache2_module.py
tests/integration/targets/apache2_module/meta/main.yml
tests/integration/targets/apache2_module/tasks/actualtest.yml
tests/integration/targets/apache2_module/tasks/main.yml

Refactoring in the module code, plus fixing the tests.
plugins/modules/web_infrastructure/apache2_module.py
tests/integration/targets/apache2_module/tasks/actualtest.yml
tests/integration/targets/apache2_module/tasks/main.yml

apache2_module - multiple improvements

---

changelogs/fragments/3079-report-power-state-hpilo.yaml
plugins/modules/remote_management/hpilo/hpilo_info.py

Implement system power state in hpilo_info module.
Fixes #2999 
hpilo_info

Feature: implement hpilo_info system power info

---

plugins/modules/source_control/github/github_issue.py

Output key did not match the actual result from the code.
plugins/modules/source_control/github/github_issue.py

github_issue - fixed RETURN doc

---

changelogs/fragments/2946-python-dnsimple-v2-rewrite.yml
plugins/modules/net_tools/dnsimple.py
tests/unit/plugins/modules/net_tools/test_dnsimple.py
tests/unit/requirements.txt

Update dnsimple module to work with python-dnsimple >=2.0.0
Fixes https://github.com/ansible-collections/community.general/issues/1605
dnsimple
* implement handling for dnsimple account & user keys
* implement pagination
* add `sandbox` module parameter

dnsimple update for python-dnsimple >=2.0.0

---

.azure-pipelines/azure-pipelines.yml
tests/integration/targets/django_manage/aliases
tests/integration/targets/yum_versionlock/aliases

See https://github.com/ansible-collections/overview/issues/45#issuecomment-889538991
CI

Update AZP config

---

changelogs/fragments/pkgin-output-after-error.yml
plugins/modules/packaging/os/pkgin.py

In case of any error during pkgin invocation, display stdout and stderr, to be able to investigate what was the root cause of issue
pkgin
Related to Feature request https://github.com/ansible-collections/community.general/issues/3146

pkgin: display stdout and stderr in case the error occurs

---

CONTRIBUTING.md

Turns out we never mentioned it in there... Thanks to @sebix for pointing this out :)
CC @Andersson007 @russoz
CONTRIBUTING.md

Inform contributors on changelog fragments in CONTRIBUTING.md

---

changelogs/fragments/3191-vdo-refactor.yml
plugins/modules/system/vdo.py

Improved run_command calls, plus some pythonification of the code.
plugins/modules/system/vdo.py

vdo - refactor

---

changelogs/fragments/3205-slack-minor-refactor.yaml
plugins/modules/notification/slack.py

Minor refactoring:
- unused parameters in functions
- extraneous parenthesis
- redundant spec for some arguments
plugins/modules/notification/slack.py

slack - minor refactoring and pythonifying

---

changelogs/fragments/3199-tss-lookup-plugin-bugfix-for-backwards-compatibility.yml
plugins/lookup/tss.py

Fixes #3192 
Adds backwards compatibility for SDK version v0.0.5.
tss lookup plugin
I was able to reproduce the error. The error was isolated to SDK version <= 0.0.5.

tss: added fix for bug report in issue #3192

---

changelogs/fragments/3252-tss_lookup_plugin-refactor.yml
plugins/lookup/tss.py
tests/unit/plugins/lookup/test_tss.py

General cleanup after recent changes for compatibility with various versions of the `python-tss-sdk` library.
- Decouples the SDK and isolates version specific behavior from the `Lookup` class itself
- Adds some cohesion with other `Ansible` plugins/modules with regards to imports

tss_lookup_plugin - Refactor and decoupling

---

changelogs/fragments/3284-openwrt_init-improvements.yaml
plugins/modules/system/openwrt_init.py

Generic improvements on openwrt_init: pythonification + run_command with list of args instead of string
plugins/modules/system/openwrt_init.py

openwrt_init - improvements

---

changelogs/fragments/3211-snap-error-handling.yml
plugins/modules/packaging/os/snap.py

Improved error handling for the module, especially for the cases when snapcraft servers are unreachable.
Fixes #2970 

snap - improved error handling

---

changelogs/fragments/3283-django_manage-fix-command-splitting.yaml
plugins/modules/web_infrastructure/django_manage.py
tests/integration/targets/django_manage/files/base_test/simple_project/p1/p1/settings.py
tests/integration/targets/django_manage/tasks/main.yaml

Added splitting generic CLI arguments from the `command` parameter
Fixes #3215 

django_manage - added splitting the command parameter for running

---

plugins/inventory/proxmox.py

Adding a minimal example and correcting the existing example to demonstrate proper use of `constructed` options.
Fixes #2860
N/A

proxmox inventory plugin - Update examples documentation

---

changelogs/fragments/3286-open_iscsi-improvements.yaml
plugins/modules/system/open_iscsi.py

Minor refactoring.
plugins/modules/system/open_iscsi.py

open_iscsi - minor refactoring

---

plugins/modules/source_control/gitlab/gitlab_group_members.py

Follow-up to #3047, with some things I missed.

gitlab_group_members: fix documentation bugs

---

changelogs/fragments/3332-zpool_facts-pythonify.yaml
plugins/modules/storage/zfs/zpool_facts.py

Minor refactorning.
plugins/modules/storage/zfs/zpool_facts.py

zpool_facts - pythonification

---

changelogs/fragments/3337-linode-fix.yml
plugins/inventory/linode.py

Fixes #3337.
linode inventory plugin

linode inventory plugin: fix default value of new option

---

.github/BOTMETA.yml
plugins/doc_fragments/redis.py
plugins/module_utils/redis.py
plugins/modules/database/misc/redis_data_info.py
plugins/modules/redis_data_info.py
tests/unit/plugins/modules/database/misc/test_redis_data_info.py

Added:
- redis_data_info module and suggested 'exists' return flag.
- module_utils for redis with a base class that handles database connections.
- inhereited unit tests and added some new ones for the exit flag
Adds `redis_data_info` module. Originally from #3144. Applied suggested changes and added some more unit tests.
`redis_data_info`

Adds redis_data_info module

---

.github/BOTMETA.yml
commit-rights.md

Removing myself from `supershipit` and inserting my information to the committers table.
Thanks for the oppurtunity!

commit-rights - Adding Ajpantuso as maintainer

---

.github/BOTMETA.yml
commit-rights.md

This is a backport of PR #3349 as merged into main (05fe587).
Removing myself from supershipit and inserting my information to the committers table.
Thanks for the oppurtunity!

[PR #3349/05fe587a backport][stable-2] commit-rights - Adding Ajpantuso as maintainer

---

.github/BOTMETA.yml
changelogs/fragments/3359-add-unicode_normalize-filter.yml
docs/docsite/rst/filter_guide.rst
plugins/filter/unicode_normalize.py
tests/integration/targets/filter_unicode_normalize/aliases
tests/integration/targets/filter_unicode_normalize/tasks/main.yml
tests/integration/targets/filter_unicode_normalize/vars/main.yml

Adding new filter plugin for normalizing Unicode strings (useful for more advanced string comparisons).
plugins/filter/unicode_normalization.py
Originally discussed [here](https://github.com/ansible-collections/community.crypto/issues/270#issuecomment-917134671)

New filter plugin - unicode_normalization

---

.github/BOTMETA.yml
plugins/inventory/icinga2.py
tests/unit/plugins/inventory/test_icinga2.py

Adding an inventory plugin made for Ansible/AWX that allows for interfacing with Icinga2
Icinga2 Inventory Plugin
```paste below
```

Icinga2 inventory plugin

---

changelogs/fragments/3379-gitlab_project-ci_cd_properties.yml
plugins/modules/source_control/gitlab/gitlab_project.py

Enhance existing community.general.gitlab_project to add CI/CD properties:
- ci_config_path
- shared_runners_enabled
gitlab_project
Has been tested on our gitlab instance.

Add gitlab_project CI/CD properties

---

changelogs/fragments/3329-kernel_blacklist-improvements.yaml
plugins/modules/system/kernel_blacklist.py
tests/integration/targets/kernel_blacklist/aliases
tests/integration/targets/kernel_blacklist/files/blacklist
tests/integration/targets/kernel_blacklist/meta/main.yml
tests/integration/targets/kernel_blacklist/tasks/main.yml

Revamped the module.
kernel_blacklist

kernel_blacklist - revamped the module

---

tests/integration/targets/ansible_galaxy_install/aliases
tests/integration/targets/interfaces_file/meta/main.yml
tests/integration/targets/interfaces_file/tasks/main.yml
tests/integration/targets/one_template/meta/main.yml
tests/integration/targets/setup_opennebula/meta/main.yml
tests/integration/targets/setup_opennebula/tasks/main.yml
tests/sanity/extra/aliases.py

Uses ansible/ansible#75605 instead of devel in CI. Let's see what happens and if there are surprises :-)
CI

Make ready for split-controller testing in ansible-core

---

tests/integration/targets/one_template/meta/main.yml
tests/integration/targets/setup_opennebula/meta/main.yml
tests/integration/targets/setup_opennebula/tasks/main.yml
tests/sanity/extra/aliases.py

Backport of #3345 to stable-2.

[stable-2] Make ready for split-controller testing in ansible-core

---

changelogs/fragments/3356-fix_task_structure_xcc_redfish_command.yml
plugins/modules/remote_management/lenovoxcc/xcc_redfish_command.py

Part of Ansible contributer summit hackathon. 
Relates #3354 (Andersson007 changed Fixes to Relates to prevent closing of the issue after the PR gets merged)
Adhere to proper task structure with task names.

fix structure xcc_redfish_command

---

.azure-pipelines/azure-pipelines.yml

CI config needs adjustment.
CI

devel dropped support for Python 2.6

---

changelogs/fragments/3450-callback_opentelemetry-exception_handling.yml
plugins/callback/opentelemetry.py

Apply some of the suggestions in the code review for https://github.com/ansible-collections/community.general/pull/3380
ansible/ansible#75726

[opentelemetry] minor changes in the import, docs and exception

---

changelogs/fragments/3478-yaml-callback.yml
plugins/callback/yaml.py
tests/integration/targets/callback_yaml/tasks/main.yml

Fixes #3471.
yaml callback plugin

yaml callback: prevent plugin from modifying PyYAML

---

.github/BOTMETA.yml
plugins/modules/packaging/language/pipx.py
plugins/modules/pipx.py
tests/integration/targets/pipx/aliases
tests/integration/targets/pipx/tasks/main.yml

New module to automate the use of the `pipx` command.

pipx - new module

---

changelogs/fragments/3611-pipx-fix-inject.yml
plugins/modules/packaging/language/pipx.py
tests/integration/targets/pipx/tasks/main.yml

The logic for `state=inject` had bug, a `.items()` was missing. The PR contains tests for this case.
pipx

pipx - fixed bug in state=inject

---

changelogs/fragments/3606-pacman-speed-up-check-if-package-is-installed.yml
plugins/modules/packaging/os/pacman.py

When checking if a package is installed or not (without checking for the `latest` version), pacman doesn't need to check the remote repository's package details
pacman
When using the `pacman` module in my playbooks, it seemed a little slow for tasks where I just wanted to check that a package is installed (regardless of version). It turns out that this delay is mainly caused by checking with the remote repository to fetch the latest version number
Therefore, this change is to skip checking with the remote repository when we don't need to know whether the package installed is the latest or not. This should result in a nice speed increase for particular use cases of `pacman` :smile: 
Before - Checking that 30 existing packages are installed:
```
TASK [temp : Install 30 …
```

[Pacman Module] Allow for the pacman repository check to be skipped when it's not needed

---

changelogs/fragments/3551-supervisor-all.yml
plugins/modules/web_infrastructure/supervisorctl.py

Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>
This PR:
- Adds the possibility to restart all supervisorctl programs and groups
- Fixes #3551 
plugins/modules/web_infrastructure/supervisorctl.py
```sh
~$ supervisorctl status
myapp0                           RUNNING   pid 24516, uptime 0:00:02
myappgroup:myapp1                RUNNING   pid 24506, uptime 0:00:08
myappgroup:myapp2                RUNNING   pid 24513, uptime 0:00:04
```
```yaml
---
any_errors_fatal: true
tasks:
- name: Restart Supervisor processes
supervisorctl:
name: all
state: restarted
- name: Stop myapp0
supervisorctl:
name: myapp0
state: stopped
```
```sh
~$ ansible-playbook -i '127.0.0.1,' -c local supervisorctl.yaml -v
Using /home/vagrant/.ansible.cfg as …
```

add the possibility to restart all supervisorctl programs and groups

---

.github/BOTMETA.yml
plugins/modules/packaging/os/snap.py
plugins/modules/packaging/os/snap_alias.py
plugins/modules/snap_alias.py
tests/integration/targets/snap_alias/aliases
tests/integration/targets/snap_alias/defaults/main.yml
tests/integration/targets/snap_alias/handlers/main.yml
tests/integration/targets/snap_alias/meta/main.yml
tests/integration/targets/snap_alias/tasks/Debian.yml
tests/integration/targets/snap_alias/tasks/Fedora.yml
tests/integration/targets/snap_alias/tasks/RedHat.yml
tests/integration/targets/snap_alias/tasks/default.yml
tests/integration/targets/snap_alias/tasks/main.yml
tests/integration/targets/snap_alias/tasks/nothing.yml
tests/integration/targets/snap_alias/tasks/test.yml

New module `snap_alias` to manage aliases for installed `snap`s.
Fixes: #566
snap_alias

snap_alias - new module

---

tests/integration/targets/callback_yaml/aliases

So CI actually passes until #3643 or something similar gets merged.
yaml callback plugin

Temporarily disable yaml callback tests

---

changelogs/fragments/3634-pipx-improve-changed.yaml
plugins/modules/packaging/language/pipx.py

Simplified the logic to determine `changed`
pipx

pipx: minor refactor

---

CHANGELOG.rst
changelogs/changelog.yaml

The module is urpmi, not urmpi.
changelog

Fix urpmi typo in changelog

---

changelogs/fragments/3660-a_module-tombstone.yml
plugins/test/a_module.py
tests/integration/targets/test_a_module/runme.yml

Fixes the issue reported in https://github.com/ansible-collections/community.general/pull/3628#discussion_r742184155 by @dmsimard.
a_module test plugin

a_module test: fix crash in case of tombstoning

---

.azure-pipelines/azure-pipelines.yml
tests/integration/targets/filesystem/tasks/main.yml
tests/integration/targets/filesystem/tasks/setup.yml

See https://github.com/ansible-collections/overview/issues/45#issuecomment-963553255.
CI

Replace Fedora 33 with Fedora 35 for devel tests

---

plugins/modules/clustering/consul/consul.py

Fix some docs issues exhibited by https://github.com/ansible/ansible/pull/76262.
some modules

Fix docs issues.

---

.github/BOTMETA.yml

BOTMETA.yml: add new maintainer to gitlab team

BOTMETA.yml: add new maintainer to gitlab team

---

changelogs/fragments/3709-support-batch-mode.yml
plugins/callback/counter_enabled.py

Enable counter_enabled.py to support batch playbook executions using the serial tag in plays. Currently, the host counter gets reset at the beginning of every task. However, during batch executions we want it to keep track of the previous batch executions and print the host counter based on the previous runs. This proposal keeps track of how many servers have been updated in previous batches and starts the host counter at that tracked value.
counter_enabled
When executing a playbook in batch mode, i.e., with the serial attribute like
```
- hosts: all
serial:
- 3
- 15%
- 20%
- 35%
- 55%
- 90%
- 100%
tasks:
- name: Ping Hello!
ping:
data: "Hello!!!!"
```
The callback plugin `counter_enabled` does not keep track of batch size. This is a bug fix to …

Enable counter_enabled.py to support batch mode

---

changelogs/fragments/deprecate-ansible-2.9-2.10.yml

Implements announcement of https://github.com/ansible-community/community-topics/issues/50 for community.general.
changelog

[stable-4] Announce deprecation of support for Ansible 2.9 and ansible-base 2.10

---

tests/integration/targets/setup_redis_replication/defaults/main.yml
tests/integration/targets/setup_redis_replication/meta/main.yml
tests/integration/targets/setup_redis_replication/tasks/setup_redis_cluster.yml
tests/utils/constraints.txt

Backport of #3733 to stable-1.
redis integration tests

[stable-1] Restrict redis version in CI

---

.azure-pipelines/azure-pipelines.yml
tests/integration/targets/django_manage/aliases
tests/integration/targets/django_manage/tasks/main.yaml

See https://github.com/ansible-collections/overview/issues/45#issuecomment-970959091
CI

CI: Replace RHEL 8.4 by RHEL 8.5 for devel

---

plugins/inventory/xen_orchestra.py
tests/unit/plugins/inventory/test_xen_orchestra.py

Adds support for groups, keyed_groups and compose
xen_orchestra

Xen orchestra inventory: Added groups, keyed_groups and compose support

---

changelogs/fragments/3780-add-keycloak-sssd-user-federation.yml
plugins/modules/identity/keycloak/keycloak_user_federation.py

Allow 'sssd' provider_id for user federation
Fixes #3767

Keycloak: add sssd provider for user federation

---

changelogs/fragments/3768-nmcli_fix_changed_when_no_mask_set.yml
changelogs/fragments/3768-nmcli_fix_changed_when_no_mask_set_add_multiple_ipv6_address_support.yml
plugins/modules/net_tools/nmcli.py
tests/unit/plugins/modules/net_tools/test_nmcli.py

This PR was requested in #3776. So this just fork of branch in #3776 but with bugfix(#3768)
Most of information can be find in #3776. I should mention that i forked this way because this fix depends on adding list support in ipv6 parameter. That's why diff contains diff from #3776.

Fixing ip address without mask bug

---

changelogs/fragments/3807-logentries-run_command-list.yaml
plugins/modules/monitoring/logentries.py

plugins/modules/monitoring/logentries.py

logentries - invoke run_command passing list

---

changelogs/fragments/3805-iso_extract-run_command-list.yaml
plugins/modules/files/iso_extract.py

plugins/modules/files/iso_extract.py

iso_extract - invoke run_command passing list

---

plugins/modules/packaging/language/ansible_galaxy_install.py

Minor adjustments in documentation.

ansible_galaxy_install - minor documentation fix

---

changelogs/fragments/3797-python_requirements_info-improvements.yaml
plugins/modules/system/python_requirements_info.py
tests/integration/targets/python_requirements_info/tasks/main.yml

Returns python version broken down into its components, and some minor refactoring.
plugins/modules/system/python_requirements_info.py

python_requirements_info - improvements

---

changelogs/fragments/3800-pipx-include-apps.yaml
plugins/modules/packaging/language/pipx.py
tests/integration/targets/pipx/tasks/main.yml

Fixes the bug and adds a test for it.
Fixes #3791 

pipx - fixed --include-apps bug

---

changelogs/fragments/3801-mh-deprecate-vardict-attr.yaml
plugins/module_utils/mh/module_helper.py
tests/integration/targets/module_helper/library/msimpleda.py
tests/integration/targets/module_helper/library/mstate.py
tests/integration/targets/module_helper/tasks/mstate.yml

Deprecates the attribute. 
plugins/module_utils/mh/module_helper.py

ModuleHelper - deprecate attribute VarDict

---

changelogs/fragments/3822-ip_netns-run-list.yaml
plugins/modules/net_tools/ip_netns.py

plugins/modules/net_tools/ip_netns.py

ip_netns - invoke run_command passing list

---

changelogs/fragments/3829-svc-run-list.yaml
plugins/modules/system/svc.py

svc - invoke run_command passing list

---

.azure-pipelines/azure-pipelines.yml

I guess I should have done this ealier... (once I created `stable-4`)
CI

Add stable-4 to nightly CI jobs; make stable-2 weekly

---

tests/integration/targets/module_helper/tasks/msimpleda.yml

Extra test for DeprecateAttrMixin 
tests/integration/targets/module_helper/tasks/msimpleda.yml

MH additional test

---

.github/BOTMETA.yml
plugins/inventory/online.py
plugins/inventory/scaleway.py
plugins/modules/cloud/online/online_server_info.py
plugins/modules/cloud/online/online_user_info.py
plugins/modules/cloud/scaleway/scaleway_compute.py
plugins/modules/cloud/scaleway/scaleway_image_info.py
plugins/modules/cloud/scaleway/scaleway_ip.py
plugins/modules/cloud/scaleway/scaleway_ip_info.py
plugins/modules/cloud/scaleway/scaleway_lb.py
plugins/modules/cloud/scaleway/scaleway_organization_info.py
plugins/modules/cloud/scaleway/scaleway_security_group_info.py
plugins/modules/cloud/scaleway/scaleway_server_info.py
plugins/modules/cloud/scaleway/scaleway_snapshot_info.py
plugins/modules/cloud/scaleway/scaleway_sshkey.py
plugins/modules/cloud/scaleway/scaleway_user_data.py
plugins/modules/cloud/scaleway/scaleway_volume_info.py

update scaleway maintainers

---

plugins/modules/system/timezone.py

Mention Alpine Linux in timezone docs
Fixes #3242
timezone

small docs update for timezone module

---

.github/BOTMETA.yml
plugins/modules/gitlab_branch.py
plugins/modules/source_control/gitlab/gitlab_branch.py
tests/integration/targets/gitlab_branch/aliases
tests/integration/targets/gitlab_branch/defaults/main.yml
tests/integration/targets/gitlab_branch/tasks/main.yml

- add module gitlab-branch to create/delete branch in project gitlab
- 
gitlab_branch

add module gitlab_branch

---

changelogs/fragments/3833-aix_filesystem-run-list.yaml
plugins/modules/system/aix_filesystem.py

plugins/modules/system/aix_filesystem.py

aix_filesystems - invoke run_command passing list

---

changelogs/fragments/3834-aix-lvg-run-list.yaml
plugins/modules/system/aix_lvg.py

plugins/modules/system/aix_lvg.py

aix_lvg - invoke run_command passing list

---

changelogs/fragments/1088-add_multiple_ipv6_address_support.yml
plugins/modules/net_tools/nmcli.py
tests/unit/plugins/modules/net_tools/test_nmcli.py

Manual backport of #3776 to stable-4.
nmcli

[stable-4] nmcli: adding ipv6 address list support

---

changelogs/fragments/3851-lxc-container-run-list.yaml
plugins/modules/cloud/lxc/lxc_container.py

plugins/modules/cloud/lxc/lxc_container.py

lxc_container - invoke run_command passing list

---

.github/BOTMETA.yml
plugins/modules/dnsimple_info.py
plugins/modules/net_tools/dnsimple_info.py
tests/unit/plugins/modules/net_tools/test_dnsimple_info.py

ad module to get info from dnsimple api
dnsimple_info
this is to resolve: https://github.com/ansible-collections/community.general/issues/3569

add dnsimple_info module, see issue #3569

---

plugins/lookup/etcd3.py
plugins/modules/database/misc/redis_data.py
plugins/modules/database/misc/redis_data_incr.py
plugins/modules/database/misc/redis_data_info.py
plugins/modules/net_tools/snmp_facts.py
plugins/modules/system/nosh.py

Fixes some docs issues, and improves some other docs.
various

Docs improvements

---

plugins/lookup/etcd3.py
plugins/modules/database/misc/redis_data_info.py
plugins/modules/net_tools/snmp_facts.py
plugins/modules/system/nosh.py

Backport of #3893 to stable-3.
various

[stable-3] Docs improvements

---

changelogs/fragments/3867-jira-fix-body.yaml
plugins/modules/web_infrastructure/jira.py

The key may not be there, replacing `[]` with `.get()`
Fixes #3419 
plugins/modules/web_infrastructure/jira.py

jira - fixed 'body' dict key error

---

tests/integration/targets/snap/aliases
tests/integration/targets/snap_alias/aliases

They are constantly failing right now.
CI

Disable snap tests

---

tests/integration/targets/snap/aliases

Backport of #3922 to stable-3.
CI

[stable-3] Disable snap tests

---

.github/BOTMETA.yml
changelogs/fragments/3921-add-counter-filter-plugin.yml
docs/docsite/rst/filter_guide.rst
plugins/filter/counter.py
tests/integration/targets/filter_counter/aliases
tests/integration/targets/filter_counter/tasks/main.yml

A filter to count (hashable) elements in a sequence:
- count the number of occurrences of each character in a string
- count occurrences of each element in a list
filter

Add counter filter

---

.github/BOTMETA.yml
plugins/modules/system/sudoers.py
tests/sanity/extra/botmeta.py

Fixes https://github.com/ansible-collections/community.general/pull/3977#discussion_r778345561, more similar cases, and the underlying issue why the sanity test didn't report this.
BOTMETA
sudoers module

Fix BOTMETA and corresponding sanity test

---

.github/BOTMETA.yml
tests/sanity/extra/botmeta.py

Backport of #3989 to stable-3.
BOTMETA

[stable-3] Fix BOTMETA and corresponding sanity test

---

plugins/module_utils/version.py

Fix comment.
plugins/module_utils/version.py

Fix comment.

---

.github/BOTMETA.yml
plugins/modules/cargo.py
plugins/modules/packaging/language/cargo.py
tests/integration/targets/cargo/aliases
tests/integration/targets/cargo/tasks/main.yml
tests/integration/targets/cargo/tasks/setup.yml
tests/integration/targets/cargo/tasks/test_general.yml
tests/integration/targets/cargo/tasks/test_version.yml

New module to automate the use of cargo packager.
Closes #3975.
plugins/modules/packaging/language/cargo.py

New module for cargo command

---

.azure-pipelines/azure-pipelines.yml

See https://github.com/ansible-collections/overview/issues/45#issuecomment-1011453621.
CI

Update CI matrix for Remote Devel

---

changelogs/fragments/3943-add-option-options-to-snap-module.yml
plugins/modules/packaging/os/snap.py
tests/integration/targets/snap/tasks/main.yml

Provide functionality suggested in https://github.com/ansible-collections/community.general/issues/666
Closes #666
snap
n/a

Add option "options" to snap module

---

.github/BOTMETA.yml
plugins/modules/homectl.py
plugins/modules/system/homectl.py
tests/integration/targets/homectl/aliases
tests/integration/targets/homectl/tasks/main.yml

#3931
New module (WIP) for adding module homectl to manage systemd-homed user accounts.
homectl
WIP for now creates user account and removes them.
Would appreciate any feedback or issues anyone sees / suggestions/ comments

New Module: Homectl module for managing systemd-homed

---

changelogs/fragments/4068-add-include_file-option.yml
plugins/inventory/cobbler.py

Also some minor cleanup
Adds the ability to include only specific profiles or exclude profiles from the list of systems.

[inventory/cobbler] Add include_profiles option

---

changelogs/fragments/4049-profile-for-scaleway-inventory.yml
plugins/inventory/scaleway.py

Add profile parameter for scaleway inventory to set profile in inventory file
Scaleway Inventory Plugin

Add profile parameter for scaleway inventory

---

tests/integration/targets/setup_pkg_mgr/tasks/main.yml

Suggested by @sivel in IRC. If this doesn't help, let's kick CentOS 8 out.
CI

Fix CentOS 8 in CI for now

---

.github/BOTMETA.yml

@nejch and @lgatellier I would like to promote you to GitLab module maintainers, assuming you are interested :)
This practically means:
1. You will get pinged in all issues and PRs regarding GitLab modules;
2. Two maintainer `shipit`s can merge a PR (in case nobody with commit rights is around to press the button for you).
Please approve this PR if you want to become module maintainers. If you don't just write it, then I will remove you from this PR :)
Ref: https://github.com/ansible-collections/community.general/pull/4136#issuecomment-1038444003

Add nejch and lgatellier as GitLab module maintainers

---

changelogs/fragments/4154-ini_file_changed.yml
plugins/modules/files/ini_file.py
tests/integration/targets/ini_file/tasks/tests/02-values.yml

fixes #4154 
ini_file
```paste below
```

ini_file: Don't report changed=true when removing if nothing is changed.

---

changelogs/fragments/4232-text-converter-import.yml
plugins/inventory/opennebula.py
plugins/modules/remote_management/redfish/ilo_redfish_config.py
plugins/modules/remote_management/redfish/ilo_redfish_info.py

Some managed to sneak in since the last cleanup :)
plugins/inventory/opennebula.py
plugins/modules/remote_management/redfish/ilo_redfish_config.py
plugins/modules/remote_management/redfish/ilo_redfish_info.py

Fix some more instances of ansible.module_utils._text

---

tests/integration/targets/ansible_galaxy_install/aliases

Re-enable ansible_galaxy_install tests

---

changelogs/fragments/4275-pacman-sysupgrade.yml
plugins/modules/packaging/os/pacman.py
tests/unit/plugins/modules/packaging/os/test_pacman.py

Fixes #4274
Sorry about that, I tested the upgrade in check mode only apparently... (and even the test were wrong :facepalm: )

pacman: fix upgrade: yes

---

tests/integration/targets/pacman/aliases
tests/integration/targets/pacman/meta/main.yml
tests/integration/targets/pacman/tasks/basic.yml
tests/integration/targets/pacman/tasks/main.yml

First version for #4272.
pacman

Add very basic integration tests for pcaman

---

tests/integration/targets/timezone/tasks/main.yml

Make timezone tests work on Alpine

---

changelogs/fragments/4303-pipx-editable.yml
plugins/modules/packaging/language/pipx.py

Added the options as requested.
Fixes #4300 

pipx: added options editable and pip_args

---

.github/BOTMETA.yml

I'm no longer using Ansible.
N/A
N/A

Remove DWSR from BOTMETA.yml

---

plugins/cache/memcached.py
plugins/inventory/cobbler.py
plugins/inventory/gitlab_runners.py
plugins/inventory/linode.py
plugins/inventory/nmap.py
plugins/inventory/online.py
plugins/inventory/scaleway.py
plugins/lookup/consul_kv.py
plugins/lookup/credstash.py
plugins/lookup/dnstxt.py
plugins/modules/cloud/centurylink/clc_blueprint_package.py
plugins/modules/cloud/centurylink/clc_firewall_policy.py
plugins/modules/cloud/centurylink/clc_loadbalancer.py
plugins/modules/cloud/centurylink/clc_server_snapshot.py
plugins/modules/cloud/huawei/hwc_vpc_security_group.py
plugins/modules/cloud/rackspace/rax_cdb.py
plugins/modules/database/vertica/vertica_info.py
plugins/modules/database/vertica/vertica_role.py
plugins/modules/database/vertica/vertica_schema.py
plugins/modules/database/vertica/vertica_user.py
plugins/modules/monitoring/datadog/datadog_monitor.py
plugins/modules/net_tools/infinity/infinity.py
plugins/modules/system/open_iscsi.py
plugins/modules/system/selinux_permissive.py

Fix documentation sanity issues reported by https://github.com/ansible/ansible/pull/77268.
various

Fix some sanity issues

---

plugins/cache/memcached.py
plugins/inventory/cobbler.py
plugins/inventory/gitlab_runners.py
plugins/inventory/linode.py
plugins/inventory/nmap.py
plugins/inventory/online.py
plugins/inventory/scaleway.py
plugins/lookup/consul_kv.py
plugins/lookup/credstash.py
plugins/lookup/dnstxt.py
plugins/modules/cloud/centurylink/clc_blueprint_package.py
plugins/modules/cloud/centurylink/clc_firewall_policy.py
plugins/modules/cloud/centurylink/clc_loadbalancer.py
plugins/modules/cloud/centurylink/clc_server_snapshot.py
plugins/modules/cloud/huawei/hwc_vpc_security_group.py
plugins/modules/cloud/rackspace/rax_cdb.py
plugins/modules/database/vertica/vertica_info.py
plugins/modules/database/vertica/vertica_role.py
plugins/modules/database/vertica/vertica_schema.py
plugins/modules/database/vertica/vertica_user.py
plugins/modules/monitoring/datadog/datadog_monitor.py
plugins/modules/net_tools/infinity/infinity.py
plugins/modules/system/open_iscsi.py
plugins/modules/system/selinux_permissive.py

Backport of #4346 to stable-3.
various

[stable-3] Fix some sanity issues

---

changelogs/fragments/4337-pacman-update_cache.yml
plugins/modules/packaging/os/pacman.py
tests/integration/targets/pacman/tasks/main.yml
tests/integration/targets/pacman/tasks/update_cache.yml
tests/unit/plugins/modules/packaging/os/test_pacman.py

Basically what was discussed in https://github.com/ansible-collections/community.general/pull/4330#pullrequestreview-902692869.
@jraby @foutrelis
pacman

pacman: implement change detection for update_cache=true; add cache_updated return value

---

plugins/modules/packaging/os/pacman.py

@aminvakil suggested to have this also in the examples (see #4330).
pacman

pacman: add description on keeping old behavior and already switching to new behavior

---

changelogs/fragments/4368-reverts-4281.yml
plugins/modules/cloud/misc/terraform.py

Backport of #4368 to stable-4. Fixes #4367.
terraform

[stable-4] Revert "Allow complex values in variables parameter of terraform module (#4281)"

---

README.md

Fixed a typo and adjusted the sentence in README.

README: typo+wordsmithing 

---

.azure-pipelines/azure-pipelines.yml
README.md

Replace devel with stable-2.13 in stable-3 CI.
CI

[stable-3] Replace devel with stable-2.13 in CI

---

.azure-pipelines/azure-pipelines.yml
README.md
tests/sanity/ignore-2.14.txt

Add stable-2.13 to CI, thin out older version matrix to avoid costs to grow (too much).
CI

Add stable-2.13 to CI, thin out older version matrix

---

changelogs/fragments/4386-proxmox-support-templating-in-inventory-file.yml
plugins/inventory/proxmox.py

Add support for templating in the proxmox inventory file for the fields bellow: 
- url
- user
- password
Fixes #3949 
proxmox inventory

Proxmox Inventory: Add support for templating in inventory file

---

plugins/modules/identity/onepassword_info.py

Just a small typo
```paste below
```

Fix small typo

---

tests/sanity/extra/aliases.py
tests/sanity/extra/extra-docs.json
tests/sanity/extra/extra-docs.py

Use antsibull-docs instad of antsibull in CI.
CI

Switch from antsibull to antsibull-docs

---

changelogs/fragments/4471-seport-refactor.yaml
plugins/modules/system/seport.py

Minor refactor
plugins/modules/system/seport.py

seport: minor refactor

---

tests/integration/targets/pkgng/aliases

Temporarily disable the pkgng tests

---

.azure-pipelines/azure-pipelines.yml

Backport of applicable parts of #4511 to stable-3.
CI

[stable-3] CI: remove FreeBSD 12.0 and 12.2

---

.azure-pipelines/azure-pipelines.yml

See #4511 and https://dev.azure.com/ansible/community.general/_build/results?buildId=40242&view=results.
CI

[stable-2] Remove FreeBSD 12.0 and 12.2 from CI

---

plugins/modules/system/xfconf.py

Improved YAML formatting, added `seealso` links and revamped the description for `value_type`.
xfconf

xfconf: improve docs

---

changelogs/fragments/4534-xfconf-added-value-types.yaml
plugins/modules/system/xfconf.py

Checking a bit further into `xfconf-query` code, it's been found that a number of possible values were missing.
xfconf

xfconf: added missing value types

---

tests/unit/plugins/modules/database/saphana/test_hana_query.py

Fix wrong unit test import.
hana_query unit test

Unit tests: fix import

---

.github/BOTMETA.yml
plugins/modules/cloud/lxd/lxd_project.py
plugins/modules/lxd_project.py
tests/integration/targets/lxd_project/aliases
tests/integration/targets/lxd_project/tasks/main.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.9.txt

Add ``lxd_project`` module to provide managing [LXD projects](https://linuxcontainers.org/lxd/docs/master/projects/)
User can use this module to add, modify, rename delete LXD projects
``lxd_project``
Example:
```
tasks:
- name: Create a project
community.general.lxd_project:
name: ansible-test-project
state: present
config: {}
description: my new project
```

New Module: LXD Projects

---

.github/BOTMETA.yml
plugins/modules/alerta_customer.py
plugins/modules/monitoring/alerta_customer.py
tests/integration/targets/alerta_customer/aliases
tests/integration/targets/alerta_customer/defaults/main.yml
tests/integration/targets/alerta_customer/tasks/main.yml
tests/unit/plugins/modules/monitoring/test_alerta_customer.py

New module to manage customers in Alerta.
Alerta is a monitoring tool to maintain alerts: https://github.com/alerta/alerta
It is possible to create customer views via the API: https://docs.alerta.io/api/reference.html#customers
alerta_customer
For integration tests alerta + postgres containers are needed. Executed the tests in my repo: https://github.com/CWollinger/ansible.alerta
The API also allows to manage user and roles. So, maybe more modules will follow.

New module alerta_customer

---

tests/sanity/extra/no-unwanted-files.py

Now that #4562 has been merged, let's make sure nobody accidentally re-adds symlinks to plugins/.
CI

Make sure plugins/ contains no symbolic links or other things that aren't regular files

---

.github/BOTMETA.yml
plugins/filter/to_seconds.yml

example of documenting filters when multiple exist inside one file
filters/to_seconds

documenting to_seconds filter

---

plugins/filter/random_mac.py

local testing shows fine, adding here as example for other filters/tests
random_mac

Add docs for ansible-core 2.13 use

---

.github/BOTMETA.yml
plugins/filter/counter.py
plugins/filter/dict.py
plugins/filter/dict_kv.py
plugins/filter/from_csv.py
plugins/filter/groupby.py
plugins/filter/hashids_decode.yml
plugins/filter/hashids_encode.yml
plugins/filter/jc.py
plugins/filter/json_query.py
plugins/filter/list.py
plugins/filter/random_mac.py
plugins/filter/to_days.yml
plugins/filter/to_hours.yml
plugins/filter/to_milliseconds.yml
plugins/filter/to_minutes.yml
plugins/filter/to_months.yml
plugins/filter/to_seconds.yml
plugins/filter/to_time_unit.yml
plugins/filter/to_weeks.yml
plugins/filter/to_years.yml
plugins/filter/unicode_normalize.py
plugins/filter/version_sort.py
plugins/lookup/cyberarkpassword.py
plugins/modules/files/read_csv.py
plugins/test/a_module.py

Add filter and test documentation using the new sidecar docs feature for ansible-core 2.13. Rendered with https://github.com/ansible-community/antsibull-docs/pull/6 to:
- https://ansible.fontein.de/collections/community/general/index.html#filter-plugins
- https://ansible.fontein.de/collections/community/general/index.html#test-plugins
filter plugin documentation
test plugin documentation

Document all filter and test plugins

---

.github/BOTMETA.yml
plugins/filter/dict.py
plugins/filter/dict_kv.py
plugins/filter/from_csv.py
plugins/filter/groupby.py
plugins/filter/hashids_decode.yml
plugins/filter/hashids_encode.yml
plugins/filter/jc.py
plugins/filter/json_query.py
plugins/filter/list.py
plugins/filter/random_mac.py
plugins/filter/to_days.yml
plugins/filter/to_hours.yml
plugins/filter/to_milliseconds.yml
plugins/filter/to_minutes.yml
plugins/filter/to_months.yml
plugins/filter/to_time_unit.yml
plugins/filter/to_weeks.yml
plugins/filter/to_years.yml
plugins/filter/unicode_normalize.py
plugins/filter/version_sort.py
plugins/lookup/cyberarkpassword.py
plugins/modules/files/read_csv.py

Manual backport of #4603 to stable-3.
filter plugin documentation
test plugin documentation

[stable-3] Document all filter and test plugins

---

plugins/filter/dict.py
plugins/filter/from_csv.py
plugins/filter/json_query.py
plugins/filter/list.py

Small docs fixes

---

plugins/filter/to_time_unit.yml

minor doc fix, removed duplicate
time_filter
```paste below
```

doc: time_filter: fix duplicate

---

changelogs/fragments/4581-vmadm-improvements.yaml
plugins/modules/cloud/smartos/vmadm.py

Some refactoring/pythonification.

vmadm: improvements

---

plugins/callback/logstash.py

Clarify what ansible_pre_command_output actually is
+label: docsite_pr
the descripton of `ansible_pre_command_output` needed a few more words.
community.general.logstash

Clarify ansible_pre_command_output
